Repository trustwallet/assets, pull requests merged in 2019-12, with the labels that each got.

#823 Update list.json
  blockchains/waves/validators/list.json
Labels: Status: On Hold

#825 Add Tezos validator - HappyTezos
  blockchains/tezos/validators/assets/tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q/logo.png
  blockchains/tezos/validators/list.json
Labels: Status: On Hold

#853 Add WavesAssist to Trust Wallet
  blockchains/waves/validators/assets/3PEjdMgnR7a48RnZoW8RF8TeEqidue28Wgm/logo.png
  blockchains/waves/validators/list.json
Labels: Status: On Hold, Status: Requested More Info

#846 Update logo for CyberTronChain
  blockchains/ethereum/assets/0x1cdca6811e2ef23d6099d09d2754211d3c7b5af1.png
  blockchains/ethereum/assets/0x9F76Ff3336597FeAB30f5A66a053ae4A4a7eBe13.png
Labels: Status: Correction needed

#833 add BoxiNode to trust wallet
  blockchains/waves/validators/assets/3P2cC7cwEwnz4z6RFyx7DWnWCtTHBcaL53P/logo.png
  blockchains/waves/validators/list.json
Labels: Status: On Hold

#855 Added P2P Validator to Tezos
  blockchains/tezos/validators/assets/tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb/logo.png
  blockchains/tezos/validators/list.json
Labels: Status: Requested More Info

#874 Add Stir (Cosmos / Tezos / Waves Validator)
  blockchains/cosmos/validators/assets/cosmosvaloper1d0aup392g3enru7eash83sedqclaxvp7fzh6gk/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/tezos/validators/assets/tz1LH4L6XYT2JNPhvWYC4Zq3XEiGgEwzNRvo/logo.png
  blockchains/tezos/validators/list.json
  blockchains/waves/validators/assets/3PPRLpTAn9ku11YpPh1YfZcojCgopeet6er/logo.png
  blockchains/waves/validators/list.json
Labels: Status: On Hold, Status: Requested More Info

#868 Added wavesnode.net
  blockchains/waves/validators/list.json
Labels: Status: On Hold, Status: Requested More Info

#930 Add Baking Tacos tezos validator
  blockchains/tezos/validators/assets/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1/logo.png
  blockchains/tezos/validators/list.json
Labels: Status: On Hold, Status: Requested More Info
