Repository trustwallet/assets, pull requests merged in 2020-08, with the labels that each got.

#2956 Add logo of TENDIES (TEND) token. tendies.dev
  blockchains/ethereum/assets/0x1453Dbb8A29551ADe11D89825CA812e05317EAEB/info.json
  blockchains/ethereum/assets/0x1453Dbb8A29551ADe11D89825CA812e05317EAEB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#2973 AIR DANCE
  blockchains/ethereum/assets/0xdF1d11025F2A22b9DC01C7A100B4F6DdEBAc82A3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#2977 Please upload on Trust Wallet ASAP
  blockchains/ethereum/assets/0x336492A0601CC85e08C14D390BF07d960328aaf4/logo.png
  blockchains/ethereum/assets/0x4EB81375d34F493a7879c041BA86098f2AfD4139/logo.png
  blockchains/ethereum/assets/0xC83e0B5110f94C45739FB4995566f57c2542eAF8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2957 Benjamindlea brainiac chess
  blockchains/ethereum/assets/0x5f75112bBB4E1aF516fBE3e21528C63DA2B6a1A5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2981 add ENVT network logo
  blockchains/ethereum/assets/0x8CD6e29d3686d24d3C2018CEe54621eA0f89313B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2978 Remove incorrect Abyss tokens
  blockchains/ethereum/assets/0x1800aF9d001f7B3AF7cE7a8a72dA73722Beec377/info.json
  blockchains/ethereum/assets/0x1800aF9d001f7B3AF7cE7a8a72dA73722Beec377/logo.png
  blockchains/ethereum/assets/0x7692e0b323ef3bbf8704AbfD52764edBfeF95f56/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2980 Adding Skrumble Network V2 logo
  blockchains/ethereum/assets/0x048Fe49BE32adfC9ED68C37D32B5ec9Df17b3603/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2984 Add DGN Token
  blockchains/ethereum/assets/0x7461C43bb1E96863233D72A09191008ee9217Ee8/info.json
  blockchains/ethereum/assets/0x7461C43bb1E96863233D72A09191008ee9217Ee8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2985 Add files via upload
  blockchains/ethereum/assets/0xd690AA91dc5C68E3967495E9533E09930c723E73/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2987 Add BMPL token image
  blockchains/ethereum/assets/0x5eBDd407FE6D47eC4af2DbBEf7d790100C567aB6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2988 Add ETHV token logo
  blockchains/ethereum/assets/0xEeEeeeeEe2aF8D0e1940679860398308e0eF24d6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2989 SRC TOKEN LOGO UPLODE
  blockchains/ethereum/assets/0x221F7d0F2Fa0bFbd5F8B0d0340425906F2F9968c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2990 Add files via upload
  blockchains/ethereum/assets/0x20B01f9D524777bb1988c7F3CD42Fe0Ff10D5615/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3008 Wymax Logo
  blockchains/ethereum/assets/0xC841210471aE257824b1Ddaf24D0eF64f2297485/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3007 Add logo
  blockchains/ethereum/assets/0xb96207E0a45a953953109B6E2DCB8F4b72eC7462/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3010 Rename non-checksum-format duplicate from backlist
  blockchains/ethereum/blacklist.json
Labels: Payment Status: Requested

#2993 change address of token
  blockchains/ethereum/assets/0x04bA6FC674D8B7f00C96d5d0a6872e7eb270Bd7C/info.json
  blockchains/ethereum/assets/0x04bA6FC674D8B7f00C96d5d0a6872e7eb270Bd7C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3011 Fix delisting, was in blacklist in non-checksum format, 0x1Cdca6811e2ef23D6099d09D2754211d3c7b5aF1
  blockchains/ethereum/assets/0x1Cdca6811e2ef23D6099d09D2754211d3c7b5aF1/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3009 Techno Defi Solution (TDS)
  blockchains/ethereum/assets/0x388fbFf7fef6CEe150E4820BBD4e22C377E80201/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2996 AGA Token Logo Image
  blockchains/ethereum/assets/0x2D80f5F5328FdcB6ECeb7Cacf5DD8AEDaEC94e20/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2999 Add STOCKSD token
  blockchains/ethereum/assets/0x9E2cF95Ab33AdC202BfDF13136cA19A5226aE5Ba/info.json
  blockchains/ethereum/assets/0x9E2cF95Ab33AdC202BfDF13136cA19A5226aE5Ba/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3000 Add uFire logo
  blockchains/ethereum/assets/0x660AD693D77FB33325aCdf0250E5417d929F8d7d/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2994 blacklist_SMT
  blockchains/ethereum/assets/0x55F93985431Fc9304077687a35A1BA103dC1e081/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3014 Trendering xYield (xTRND)
  blockchains/ethereum/assets/0xed5b8eC6b1f60A4b08ef72FB160fFe422064c227/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3002 Submit Logo for Bionik Protocol ( ERC20 Platform )
  blockchains/ethereum/assets/0x1d3B136dA37689C11919Ec5441BC89AF8E03BDe0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3020 [internal] Update badge for Periodic Update.
  README.md
Labels: Payment Status: Requested

#3018 Add Equus in assets/Ethereum
  blockchains/ethereum/assets/0xa462d0E6Bb788c7807B1B1C96992CE1f7069E195/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3006 Add logo
  blockchains/ethereum/assets/0x35fe0fA49a1A18cBe3844E2f9913f2e9e2db6B0b/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3015 Add logo for ERC20 token MDT (0x4Dfd148B532e934a2a26eA65689cf6268753e…
  blockchains/ethereum/assets/0x4Dfd148B532e934a2a26eA65689cf6268753e130/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3016 uvwFi updated
  blockchains/ethereum/assets/0xf83ae621A52737e3Ef9307af91df834Ed8431aC3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3021 Update logo for token KJK
  blockchains/ethereum/assets/0xac4cE3D16bb77511d0A2cB8bEFd3983142B858E0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3022 Add: CLT Logo
  blockchains/ethereum/assets/0x2001f2A0Cf801EcFda622f6C28fb6E10d803D969/info.json
  blockchains/ethereum/assets/0x2001f2A0Cf801EcFda622f6C28fb6E10d803D969/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3024 Add logo
  blockchains/ethereum/assets/0x2Eb047352BD8F2C6cAded05c0e264BDF770de5d6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3025 new logo
  blockchains/ethereum/assets/0x28e9C2F30b5e935b2eD38Fe8d796e1B39C4EFc91/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3026 BetProtocol Logo Upload
  blockchains/ethereum/assets/0x786001c9c5CA6E502dEB8a8a72480d2147891f32/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3027 IPT ( ERC20 ) Logo Submit.
  blockchains/ethereum/assets/0x8aF1ED18AF94CBC846991731702111AfbF904b45/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3029 add_PHT_TRC10
  blockchains/tron/assets/1003095/logo.png
Labels: Payment Status: Requested

#3030 Adding RMPL logo
  blockchains/ethereum/assets/0xE17f017475a709De58E976081eB916081ff4c9d5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3017 Submitting Kyber.org under dApps
  dapps/kyber.org.png
Labels: Payment Status: Paid, Payment Status: Requested

#3031 Add SUKU token
  blockchains/ethereum/assets/0x0763fdCCF1aE541A5961815C0872A8c5Bc6DE4d7/info.json
  blockchains/ethereum/assets/0x0763fdCCF1aE541A5961815C0872A8c5Bc6DE4d7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2882 Adding ZPAE (ZelaaPayAE)
  blockchains/ethereum/assets/0x045Eb7e34e94B28C7A3641BC5e1A1F61f225Af9F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3034 Changed logo to new branding
  blockchains/ethereum/assets/0xE17f017475a709De58E976081eB916081ff4c9d5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3037 Add logo file for XFT
  blockchains/ethereum/assets/0xABe580E7ee158dA464b51ee1a83Ac0289622e6be/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3033 [internal] Reduce TWT fee to 1000 (from 2000), in reaction to rate increase.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid, Payment Status: Requested

#3036 Add mcr token logo
  blockchains/ethereum/assets/0xeD351575b9869AADA94435e0066ba38E08800b60/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3043 Please add these logos
  blockchains/ethereum/assets/0x8a99E2dAE13e4df4A6aA2A9Db2d6A7901eD0107D/logo.png
  blockchains/ethereum/assets/0x93C1119a6a7bf9CD207DbC72e8614A5D82Ff427b/logo.png
  blockchains/ethereum/assets/0x993628A05907c12B56b55Aa95Dd47EC46d9CDBB7/logo.png
  blockchains/ethereum/assets/0xB8992E45a223a6841250A005B0Ed3301a1Fef9BD/logo.png
  blockchains/ethereum/assets/0xCAD6C3293C795816505F961631Cb0eF4812Dc9Ba/logo.png
  blockchains/ethereum/assets/0xba3BEB53b4e82fCFB15fD890F7213dc22C4883a5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3041 Adicionar o logotipo LEC
  blockchains/ethereum/assets/0xD58Ce16264F8D2422103Cd11d0f1Cc5987E79B5c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3048 Add logo
  blockchains/ethereum/assets/0x5a011bC3B10191782DFA67806f8864bD5cF9d3ae/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3019 Create GOLDx.
  blockchains/ethereum/assets/0x355C665e101B9DA58704A8fDDb5FeeF210eF20c0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3051 [internal] Experiment with fix build running on the PR (fix-pr).
  .github/workflows/fix-pr.yml
Labels: Payment Status: Paid, Payment Status: Requested

#3052 [internal] Fix-pr does not work, due to credentials issue; removing it.
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix-pr.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
Labels: Payment Status: Paid, Payment Status: Requested

#3040 MILES Token Logo Update
  blockchains/ethereum/assets/0x01E2087BE8C34fB06229Aa9e49BF801a89d30d9D/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3028 Add FLEx Token
  blockchains/ethereum/assets/0x6D45640F5D0B75280647f2F37CCD19c1167f833c/info.json
  blockchains/ethereum/assets/0x6D45640F5D0B75280647f2F37CCD19c1167f833c/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3057 add_CNR_TRC20
  blockchains/tron/assets/TYLrbh1pVcx95bop33XQ1iYdh7r3ogEQ8Q/logo.png
Labels: Payment Status: Requested

#3050 Add files via upload
  blockchains/ethereum/assets/0x466912bAA9430a4a460b141ee8C580D817441449/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3054 Add TTX Token
  blockchains/ethereum/assets/0xd6c730B861F9A4DED3C20105ad152Accd7621F9b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3058 Add CNC Token
  blockchains/ethereum/assets/0x0dAa561DcD6769eb7128e4b99be6FE9C7957EaB1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3055 Atualizar logotipo LearnCoin (LEC)
  blockchains/ethereum/assets/0xD58Ce16264F8D2422103Cd11d0f1Cc5987E79B5c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3061 remove_XLMG
  blockchains/ethereum/assets/0x851be0d936cb611d2caB3C3963338288445C1e52/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3062 Add files via upload
  blockchains/ethereum/assets/0x38EE6cE5b38Dc3AFb8de706FFf527f6fAE4d9eC1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3065 add sntvt asset
  blockchains/ethereum/assets/0x7865af71cf0b288b4E7F654f4F7851EB46a2B7F8/info.json
  blockchains/ethereum/assets/0x7865af71cf0b288b4E7F654f4F7851EB46a2B7F8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3066 Added BLZ token (ERC-20)
  blockchains/ethereum/assets/0x5732046A883704404F284Ce41FfADd5b007FD668/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3069 Add logo
  blockchains/ethereum/assets/0x23E4D69E477295547c89f36ca0df40646e72F998/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3067 add SChain Wallet (SCHA) token info (logo, json)
  blockchains/ethereum/assets/0x2cAd4991f62fc6Fcd8EC219f37E7DE52B688B75A/info.json
  blockchains/ethereum/assets/0x2cAd4991f62fc6Fcd8EC219f37E7DE52B688B75A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3068 Add files via upload
  blockchains/ethereum/assets/0x309013d55fB0E8C17363bcC79F25d92f711A5802/info.json
  blockchains/ethereum/assets/0x309013d55fB0E8C17363bcC79F25d92f711A5802/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3064 remove_AE_ERC20
  blockchains/ethereum/assets/0x5CA9a71B1d01849C0a95490Cc00559717fCF0D1d/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3053 New Helysia token
  blockchains/ethereum/assets/0x4C7065Bca76FE44AFb0D16C2441B1e6E163354E2/info.json
  blockchains/ethereum/assets/0x4C7065Bca76FE44AFb0D16C2441B1e6E163354E2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3045 PROOF (PRF) logo and description
  blockchains/ethereum/assets/0x74F9595874b595c7A5af9cf78AC051C2E7387173/info.json
  blockchains/ethereum/assets/0x74F9595874b595c7A5af9cf78AC051C2E7387173/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3077 [internal] Add support for BEP8 mini tokens.
  README.md
  script/action/binance.ts
  src/test/helpers.ts
  src/test/index.test.ts
Labels: Payment Status: Paid, Payment Status: Requested

#3042 Pls add BHC logo
  blockchains/binance/assets/BHC-3E8M/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3070 change of logo
  blockchains/ethereum/assets/0x57700244B20f84799a31c6C96DadFF373ca9D6c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3074 Update WIN
  blockchains/ethereum/assets/0x9D57aEEAFB19f606A42d29FdbFEd0FE3D61a0E69/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3075 Add DeFiPIE token
  blockchains/ethereum/assets/0x607C794cDa77efB21F8848B7910ecf27451Ae842/info.json
  blockchains/ethereum/assets/0x607C794cDa77efB21F8848B7910ecf27451Ae842/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3083 Change Tokens logo
  blockchains/ethereum/assets/0x44b6e3e85561ce054aB13Affa0773358D795D36D/logo.png
  blockchains/ethereum/assets/0xC6D76756Fec88A289B20091846b81C23997BFD00/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3091 [internal] Optimize BEP asset info retrieval from dex (rate limit)
  blockchains/ethereum/whitelist.json
  script/action/binance.ts
Labels: Payment Status: Paid

#3088 Please add SAFY on TrustWallet
  blockchains/ethereum/assets/0xF2C2e42BA757f21Cb51eE2bb3B10389df9A44b36/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3078 PROOF coin logo update
  blockchains/ethereum/assets/0x74F9595874b595c7A5af9cf78AC051C2E7387173/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3093 change logo for DeFiPIE Token
  blockchains/ethereum/assets/0x607C794cDa77efB21F8848B7910ecf27451Ae842/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3097 Tokens logo change
  blockchains/ethereum/assets/0x34612903Db071e888a4dADcaA416d3EE263a87b9/logo.png
  blockchains/ethereum/assets/0xC6D76756Fec88A289B20091846b81C23997BFD00/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3094 Add AludraNetwork
  blockchains/ethereum/assets/0xb339FcA531367067e98d7c4f9303Ffeadff7B881/info.json
  blockchains/ethereum/assets/0xb339FcA531367067e98d7c4f9303Ffeadff7B881/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3072 Kindly add PeerEx logo
  blockchains/ethereum/assets/0x3C6ff50c9Ec362efa359317009428d52115fe643/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3098 Add POMP token logo
  .github/workflows/fix-pr.yml
  blockchains/ethereum/assets/0x3f7D27c41fdCD1Afc660F64290d314e08ea576Ea/info.json
  blockchains/ethereum/assets/0x3f7D27c41fdCD1Afc660F64290d314e08ea576Ea/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3110 [internal] fix-pr diff
  .github/workflows/fix-pr.yml
Labels: Payment Status: Requested

#3111 [internal] Fix-pr build: ref, not head_ref.
  .github/workflows/fix-pr.yml
Labels: Payment Status: Requested

#3112 [internal] Fix-pr build must be on a branch, to be able to commit.
  .github/workflows/fix-pr.yml
Labels: Payment Status: Requested

#3115 [internal] Fix PR on pull_request_target event.
  .github/workflows/fix-pr-target.yml
Labels: Payment Status: Requested

#3116 [internal] Fix build for forks
  .github/workflows/check.yml
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix-fork.yml
  .github/workflows/fix-pr-target.yml
  .github/workflows/fix.yml
  .github/workflows/pr-ci.yml
Labels: Payment Status: Requested

#3117 [Internal] One fix build for all.
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix-fork.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
Labels: Payment Status: Requested

#3082 Added BNS Token logo and info
  blockchains/ethereum/assets/0xd996035Db82cae33Ba1f16fDF23B816E5E9fAaBb/info.json
  blockchains/ethereum/assets/0xd996035Db82cae33Ba1f16fDF23B816E5E9fAaBb/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3104 Add Logo DLAF Token
  blockchains/ethereum/assets/0xd996035Db82cae33Ba1f16fDF23B816E5E9fAaBb/info.json
  blockchains/ethereum/assets/0xe455D0862B18B9106141F733e85f3336A38e3D78/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3107 Add ITAM Games Token
  blockchains/ethereum/assets/0x3b4f7CB9e60362A49dD04EB0091A374d340E3EfD/info.json
  blockchains/ethereum/assets/0x3b4f7CB9e60362A49dD04EB0091A374d340E3EfD/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3096 mkcy logo upload
  blockchains/ethereum/assets/0xF3281c539716a08c754EC4C8F2B4cEe0faB64BB9/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3121 [Internal] Fix build uses different tokens
  .github/workflows/fix.yml
  .github/workflows/s3_upload.yml
Labels: Payment Status: Requested

#3124 [internal] Fix commit: disable on forks, as commit there causes no CI runs
  .github/workflows/fix.yml
Labels: Payment Status: Requested

#3127 [internal] Better error messages in whitelist check.
  script/action/whitelists.ts
  script/common/types.ts
  test/index.test.ts
Labels: Payment Status: Requested

#3129 [internal] Chains with whitelist, extend checks to Binance and few others.
  blockchains/binance/blacklist.json
  blockchains/binance/whitelist.json
  blockchains/vechain/whitelist.json
  script/common/blockchains.ts
Labels: Payment Status: Requested

#3130 [internal] Make whitelist check more reliable, case-insensitive.
  blockchains/ethereum/blacklist.json
  script/action/whitelists.ts
  script/common/types.ts
  test/index.test.ts
Labels: Payment Status: Requested

#3133 [internal] Add logo size check to all chains, logos.
  blockchains/xdai/assets/0x1e16aa4Df73d29C029d94CeDa3e3114EC191E25A/logo.png
  script/action/eth-forks.ts
  script/action/logo-size.ts
  script/action/tron.ts
  script/common/image.ts
Labels: Payment Status: Requested

#3128 Add Cream logo
  blockchains/ethereum/assets/0x2ba592F78dB6436527729929AAf6c908497cB200/info.json
  blockchains/ethereum/assets/0x2ba592F78dB6436527729929AAf6c908497cB200/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3125 Add logo Wellness Cash Coin (WCC) to trust wallet
  blockchains/ethereum/assets/0xad5307C84B31F0B4E1C8bCaA67704F57FbdAe74F/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3131 Add BRR
  blockchains/ethereum/assets/0x49f941FA7f5731fe302068d79c8604C24C5E7196/info.json
  blockchains/ethereum/assets/0x49f941FA7f5731fe302068d79c8604C24C5E7196/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3135 Adding BSWP BetSwap Exchange Token
  blockchains/ethereum/assets/0xd08575F5F4DE7212123731088980D069CB75873D/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3138 yang token load
  blockchains/ethereum/assets/0x81611aCD4460Fd996Aa657835aF044644Fa8ae29/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3134 change markaccy logo
  blockchains/ethereum/assets/0xF3281c539716a08c754EC4C8F2B4cEe0faB64BB9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3060 Add PlutusDefi Token Logo
  blockchains/ethereum/assets/0x9fBFed658919A896B5Dc7b00456Ce22D780f9B65/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3141 Add files via upload
  blockchains/ethereum/assets/0x2129fF6000b95A973236020BCd2b2006B0D8E019/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3145 Add logo
  blockchains/ethereum/assets/0x59641DCaD70239473503DDaa27af4f1017e3c998/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3147 Add FinNexus Wanchain Token (FNX), #3100
  blockchains/ethereum/assets/0xeF9Cd7882c067686691B6fF49e650b43AFBBCC6B/info.json
  blockchains/ethereum/assets/0xeF9Cd7882c067686691B6fF49e650b43AFBBCC6B/logo.png
  blockchains/ethereum/whitelist.json
  blockchains/wanchain/assets/0xC6F4465A6a521124C8e3096B62575c157999D361/info.json
  blockchains/wanchain/assets/0xC6F4465A6a521124C8e3096B62575c157999D361/logo.png
  blockchains/wanchain/whitelist.json
  script/action/eth-forks.ts
Labels: Payment Status: Requested

#3146 Movement DAO Token (MDT) Asset Upload - 1
  blockchains/ethereum/assets/0x32A087D5fdF8c84eC32554c56727a7C81124544E/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3150 TrayV Block ( ERC20 )
  blockchains/ethereum/assets/0x0923067100b2A4839F1803ad73b24097e20109Df/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3152 Canote Token
  blockchains/ethereum/assets/0x3C3f450Aa47C87c822D3E305b066e713dF04C1B3/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3165 [internal] Experiment with manual-trigger for builds.
  .github/workflows/check.yml
Labels: Payment Status: Requested

#3166 [internal] More manual-trigger builds.
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
  .github/workflows/pr-ci.yml
  .github/workflows/s3_upload.yml
Labels: Payment Status: Requested

#3164 Add Bitpaid
  blockchains/ethereum/assets/0x5f038e82bB69b6A52FeC7A4A38163340b98fb1e4/info.json
  blockchains/ethereum/assets/0x5f038e82bB69b6A52FeC7A4A38163340b98fb1e4/logo.png
  blockchains/ethereum/whitelist.json
  dapps/bitpaid.org.png
Labels: Payment Status: Paid, Payment Status: Requested

#3144 Added TSX logo
  blockchains/ethereum/assets/0x64Ee5a075701f75359F10626BC986Aae844Ad9a7/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3162 ETHPlus Token logo
  blockchains/ethereum/assets/0xEED736b2b809550D89A941C2005dE93588c628e2/info.json
  blockchains/ethereum/assets/0xEED736b2b809550D89A941C2005dE93588c628e2/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3161 PRR token logo upload
  blockchains/ethereum/assets/0x2DDA85bDb6e977E2637A09913cbE7419429F7819/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3156 Add MXT Logo
  blockchains/ethereum/assets/0x6251E725CD45Fb1AF99354035a414A2C0890B929/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3160 Add Fomo Protocol
  blockchains/ethereum/assets/0xf16D45806BFb0ABe59087CD8F388E0042ec7D0d3/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3167 add r.Pepe token assets
  blockchains/ethereum/assets/0x5c7499CF00E8278AA232982fF178ee9735024091/info.json
  blockchains/ethereum/assets/0x5c7499CF00E8278AA232982fF178ee9735024091/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3168 Add logo
  blockchains/ethereum/assets/0x75Dfa37dAC9D323f1d1E1249F248Bed52a6FaBA9/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3171 Adding Qubix Credit Logo
  blockchains/ethereum/assets/0x8ABAF9a8ae10Cd4AF52C1B336cC5Bd4eaF6C5A7B/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3189 add_BAL_info
  blockchains/ethereum/assets/0xba100000625a3754423978a60c9317c58a424e3D/info.json
Labels: Payment Status: Requested

#3195 ALLBI_new_contract
  blockchains/ethereum/assets/0x4Bebdd7312e81b184274d75e4c37a6D4A4d23163/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3173 ECC Logo
  blockchains/ethereum/assets/0xD5bF66fF3Dab4c74Ac6014fd2181Bd3aD1bBaF32/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3174 Add TCFX token
  blockchains/ethereum/assets/0x36dCffe069a3F2878Fab2A46D81e83D462d0cBF7/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3176 hundred logo update
  blockchains/ethereum/assets/0x243434048cC22eFdDB8AaB75673618CcBD63D155/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3178 Add logo for synthetic BREE tokens
  blockchains/ethereum/assets/0x25377ddb16c79C93B0CBf46809C8dE8765f03FCd/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3179 Add logo and info for ARNX and update logo for ARN
  blockchains/binance/assets/ARN-71B/logo.png
  blockchains/ethereum/assets/0x0C37Bcf456bC661C14D596683325623076D7e283/info.json
  blockchains/ethereum/assets/0x0C37Bcf456bC661C14D596683325623076D7e283/logo.png
  blockchains/ethereum/assets/0xBA5F11b16B155792Cf3B2E6880E8706859A8AEB6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3194 Create logo.png
  blockchains/ethereum/assets/0xCF67CEd76E8356366291246A9222169F4dBdBe64/info.json
  blockchains/ethereum/assets/0xCF67CEd76E8356366291246A9222169F4dBdBe64/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3200 Add US Money token to TrustWallet
  blockchains/ethereum/assets/0x074f54191abdC71fd4108C51BA3C669CC6c3c245/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3181 Add P2PGO (P2PG) Token
  blockchains/ethereum/assets/0xA2A19165C17B36a5C753A246c1e188489754A693/logo.png
  blockchains/ethereum/assets/0xe2B7a0c7bC21E000B8327713513b9D4d2620A414/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3186 Add files via upload asap please
  blockchains/ethereum/assets/0x8A79DD3b266F681211a7bB0a4c5345A4Cc90F413/logo.png
  blockchains/ethereum/assets/0x8e9934b2F0EA602cA5Be89e9274669E896C05Ac3/logo.png
  blockchains/ethereum/assets/0xF96459323030137703483B46fD59A71D712BF0aa/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3192 Adding assets for $TACO coin
  blockchains/ethereum/assets/0x00D1793D7C3aAE506257Ba985b34C76AaF642557/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3159 Add BPF logo #3155
  blockchains/ethereum/assets/0x5197FBE1a86679FF1360E27862BF88B0c5119BD8/logo.png
Labels: Payment Status: Requested

#3157 Add AMAL Logo
  blockchains/ethereum/assets/0xBFd78659212F00dE65A6411DAdC75878930725Ec/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#3202 EVA Token logo
  blockchains/ethereum/assets/0x7698211Cf413a2e5953e1c155bbDdCB033CC31e3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3203 0xd511a64BfC1039Eccf503aC0Ef111c6C1c630B95 Logo
  blockchains/ethereum/assets/0xd511a64BfC1039Eccf503aC0Ef111c6C1c630B95/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3204 0xe2Ed8B2beb61C85BeafF764cb5c2F2a93e0179e2 logo
  blockchains/ethereum/assets/0xe2Ed8B2beb61C85BeafF764cb5c2F2a93e0179e2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3190 Add Antiample Logo
  blockchains/ethereum/assets/0xf911a7ec46a2c6fa49193212fe4a2a9B95851c27/info.json
  blockchains/ethereum/assets/0xf911a7ec46a2c6fa49193212fe4a2a9B95851c27/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#3205 Update US Money Token
  blockchains/ethereum/assets/0x074f54191abdC71fd4108C51BA3C669CC6c3c245/logo.png
Labels: Payment Status: Requested

#3210 Add Community Token (COM) to trust wallet
  blockchains/ethereum/assets/0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#3207 Logo for buidler Token
  blockchains/ethereum/assets/0xB813879550B7c7B7f59F83962e86e5fAA7E763a1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3206 Add FERA Token
  blockchains/ethereum/assets/0x539F3615C1dBAfa0D008d87504667458acBd16Fa/info.json
  blockchains/ethereum/assets/0x539F3615C1dBAfa0D008d87504667458acBd16Fa/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3209 Add logo
  blockchains/ethereum/assets/0x2c13344Db0D0142789722bc4Dea0CdED7C0ED663/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3211 met logo update
  blockchains/ethereum/assets/0x133834219045eD0cf692619D63abcd251e6B1ca1/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3213 up token logo update
  blockchains/ethereum/assets/0xea0Db24174739aC14110FA992da89d2dAa98E50E/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3188 Add Shell Matrix Token
  blockchains/ethereum/assets/0x3017Cb31A678fE1d247f4314Eee8bc1b86b0D4b4/info.json
  blockchains/ethereum/assets/0x3017Cb31A678fE1d247f4314Eee8bc1b86b0D4b4/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3214 mewfi logo update
  blockchains/ethereum/assets/0xF260608a577B64000747D533e27bbc2e53F9108D/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#3216 [internal] Wanchain uses special reverse checksum format
  blockchains/wanchain/assets/0x0f2e7C0E904a525A24FF6f658053f6bA5Ce7A209/logo.png
  blockchains/wanchain/assets/0x350bb91C9C8Ef4e8C0e19fbdc6A90A24bcb1eC2A/logo.png
  blockchains/wanchain/assets/0x3BEB80170272f07aCA12987AF86A59888255A807/logo.png
  blockchains/wanchain/assets/0x51316966907ef568689775066e97c46a4Ffde1a4/logo.png
  blockchains/wanchain/assets/0xA13a41a2349D09C1E3a0dD4d9448Af4aD799fC4A/logo.png
  blockchains/wanchain/assets/0xc6f4465a6A521124c8E3096b62575C157999d361/info.json
  blockchains/wanchain/assets/0xc6f4465a6A521124c8E3096b62575C157999d361/logo.png
  blockchains/wanchain/whitelist.json
  script/action/eth-forks.ts
  script/common/eth-web3.ts
  script/common/types.ts
  test/index.test.ts
Labels: Payment Status: Requested
