Repository trustwallet/assets, pull requests merged in 2020-06, with the labels that each got.

#2232 Upload Logo
  blockchains/0xbb2f95F286ec090555dCa7c0BB49948C59494FdC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2231 PR to add Pamp Network (PAMP) to Trust Wallet
  blockchains/ethereum/assets/0xCe833222051740Aa5427D089A46fF3918763107f/info.json
  blockchains/ethereum/assets/0xCe833222051740Aa5427D089A46fF3918763107f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2228 add IPUX logo
  blockchains/ethereum/assets/0x5f236f062f16a9b19819c535127398df9a01d762/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2227 add TooCoin logo
  blockchains/ethereum/assets/0x2614e04133209a492ba276a6c35095aad11ad06e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2244 Add ERA20 and GBC
  blockchains/ethereum/assets/0x2AcF7dB66B767a431acfDfE9F8834DdF5835c53d/logo.png
  blockchains/ethereum/assets/0xb30fAE8C3496455dfa29C171096e9B55076B1561/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2233 logo upload finn
  blockchains/ethereum/assets/0x85eBa557C06c348395fD49e35d860F58a4F7c95a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2251 blacklist_BAR
  blockchains/ethereum/blacklist.json
Labels: Payment Status: Requested

#2252 Add information about new Kava validator : BNB48 Club
  blockchains/kava/validators/assets/kavavaloper1nhcvgj0j7mrvrat3dfhudpypaqn00eaf2dh0gp/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2249 Add logo file
  blockchains/ethereum/assets/0xDDa4d26A8D5F64e3d509fE3bd0c908176f2c9E87/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2257 add stormx token
  blockchains/ethereum/assets/0xbE9375C6a420D2eEB258962efB95551A5b722803/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2246 logo upload
  blockchains/ethereum/assets/0x09Ccd2DA5dCDd0510268d4979e792381337138b8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2256 add OKS Token
  blockchains/tron/assets/TWVVcRqRmpyAi9dASvTXrqnS7FrwvDezMn/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2261 Add UAX ERC-20 token
  blockchains/ethereum/assets/0x1Fc31488f28ac846588FFA201cDe0669168471bD/info.json
  blockchains/ethereum/assets/0x1Fc31488f28ac846588FFA201cDe0669168471bD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2254 TrustUSD ERC20 token
  blockchains/ethereum/assets/0xDD436a0Dce9244B36599AE7b22f0373b4e33992d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2263 Add COMP & cUSDT token asset to repo
  blockchains/ethereum/assets/0xc00e94Cb662C3520282E6f5717214004A7f26888/info.json
  blockchains/ethereum/assets/0xc00e94Cb662C3520282E6f5717214004A7f26888/logo.png
  blockchains/ethereum/assets/0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9/info.json
  blockchains/ethereum/assets/0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9/logo.png
Labels: Payment Status: Requested

#2268 Please add MCOM on TrustWallet
  blockchains/ethereum/assets/0x50dc23F6A26825209670c2b6A6a93506F9732f00/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2267 UniPower token logo addition
  blockchains/ethereum/assets/0xF2f9A7e93f845b3ce154EfbeB64fB9346FCCE509/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2272 Include tagged user in Paid message.
  .github/merge-fee-bot.yaml
Labels: FeePayment: Paid, Payment Status: Requested

#2275 Add Walleteum Token logo to Trust wallet
  blockchains/ethereum/assets/0x3071a55a0f7916d796b54a2d095db85df693d956/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2269 Upload token KAI
  blockchains/ethereum/assets/0xbd6467a31899590474ce1e84f70594c53d628e46/info/info.json
  blockchains/ethereum/assets/0xbd6467a31899590474ce1e84f70594c53d628e46/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2279 Add logo IFA
  blockchains/ethereum/assets/0x8081749f7F049d0B7E32BB33DEcaD9eeD96693D5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2280 Logo asset for HEX2T token
  blockchains/ethereum/assets/0xEd1199093b1aBd07a368Dd1C0Cdc77D8517BA2A0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2284 Add AiBestToken
  blockchains/ethereum/assets/0x776c5DebB8759e25ba7Ac1A2950F7158816E2705/info.json
  blockchains/ethereum/assets/0x776c5DebB8759e25ba7Ac1A2950F7158816E2705/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2288 Add HEXULTRA token logo
  blockchains/ethereum/assets/0x11bbad1c935b87cb83543b9288d1a2a73a90bf1c/info.json
  blockchains/ethereum/assets/0x11bbad1c935b87cb83543b9288d1a2a73a90bf1c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2292 Wrapped BOMB (WBOMB) Logo
  blockchains/ethereum/assets/0x5f75112bBB4E1aF516fBE3e21528C63DA2B6a1A5/logo.png
  blockchains/ethereum/assets/0xbBB38bE7c6D954320c0297c06Ab3265a950CDF89/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2289 Add 2KEY
  blockchains/ethereum/assets/0xE48972fCd82a274411c01834e2f031D4377Fa2c0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2281 Add PAMP to trust wallet
  blockchains/ethereum/assets/0xCe833222051740Aa5427D089A46fF3918763107f/info.json
  blockchains/ethereum/assets/0xF0FAC7104aAC544e4a7CE1A55ADF2B5a25c65bD1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2298 Add token logo
  blockchains/ethereum/assets/0x2A4F61Ca0e03e260E6BE91692e430293D73998F0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2297 Added Assets of BandChain
  blockchains/band/info/info.json
  blockchains/band/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2295 delete logo file
  blockchains/ethereum/assets/0x86eCAA22459BCc7c356765f65e05Afd456eC51F9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2294 New TRC20 Token
  blockchains/tron/assets/TUH63441fBWg2Jam4qTYC8aKX7Np3fHi1b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2287 NECOS Token Logo Update
  blockchains/ethereum/assets/0x6e55027CAe60cfdB7BACA78f3e6514aEE716fCf9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2303 Unibomb logo
  blockchains/ethereum/assets/0xe31DEbd7AbFF90B06bCA21010dD860d8701fd901/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2307 Delete logo.png
  blockchains/ethereum/assets/0xDDa4d26A8D5F64e3d509fE3bd0c908176f2c9E87/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2309 Add token - mooncoin
  blockchains/ethereum/assets/0x94b86C1F3682D6e87a84bCD9E2d281286CB7A904/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2312 Add mUSD token
  blockchains/ethereum/assets/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5/info.json
  blockchains/ethereum/assets/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2314 Add Token IDXT
  blockchains/ethereum/assets/0x18a4979bbb4c88275d4575d66b9c9cd6bea0cd5e/info.json
  blockchains/ethereum/assets/0x18a4979bbb4c88275d4575d66b9c9cd6bea0cd5e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2308 Added Flama Token
  blockchains/ethereum/assets/0x2afd9cE07D4186e8F3671D52200850760a8E1F70/info.json
  blockchains/ethereum/assets/0x2afd9cE07D4186e8F3671D52200850760a8E1F70/logo.png
  src/test/helpers.ts
  src/test/index.test.ts
Labels: Payment Status: Paid, Payment Status: Requested

#2316 Add CHALLENGE-CLG Logo
  blockchains/ethereum/assets/0x839961692c56270b73538F9906f8736fC1DA4fA6/logo.png
  script/arrange_files.ts
  src/test/helpers.ts
  src/test/index.test.ts
Labels: Payment Status: Paid, Payment Status: Requested

#2317 Add CXKJ
  blockchains/ethereum/assets/0x13056817f997bC3f15e1BC68207Efe8d2D197308/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2322 [R4R] feat: update kava assets
  blockchains/kava/info/info.json
  blockchains/kava/info/logo.png
Labels: Payment Status: Requested

#2329 Add KIT token logo
  blockchains/ethereum/assets/0x63b619A040CcE5f90c12b230d7258E5809E91082/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2324 added bandchain validator for WeStaking
  blockchains/band/validators/assets/bandvaloper1qgvcttnjx3enjqg9pnhclt6d4z7qdknavg4q9c/logo.png
  blockchains/band/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2323 updated unibomb logo request
  blockchains/ethereum/assets/0xe31DEbd7AbFF90B06bCA21010dD860d8701fd901/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2331 Falcon Token smart contract
  blockchains/ethereum/assets/0xDc5864eDe28BD4405aa04d93E05A0531797D9D59/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2333 Please add EMEX on TrustWallet
  blockchains/ethereum/assets/0x8B334C54997BC6c1c347d19cac73e015E3DDdf40/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2337 Add DUST Token
  blockchains/ethereum/assets/0xbca3c97837a39099ec3082df97e28ce91be14472/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2340 adding bizcoin address and logo
  blockchains/ethereum/assets/0x5d7F6540b8d592E81deF42904C853a6DD01bD486/logo.png
Labels: Payment Status: Requested

#2344 Adding Nydronia Token (NIA)
  blockchains/ethereum/assets/0xdB11F6Fc8E16c02719e9c2Eb3c4C762feE8F5C5b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2343 Adding CryptoTrust Token (CTE)
  blockchains/ethereum/assets/0x3E083D08aDa591fe5356c52fBb89FE725fd9D670/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2342 Add logo for 0x256845e721C0c46d54E6afBD4FA3B52CB72353EA
  blockchains/ethereum/assets/0x256845e721C0c46d54E6afBD4FA3B52CB72353EA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2320 Add Becaz logo folder
  blockchains/ethereum/assets/0x08399ab5eBBE96870B289754A7bD21E7EC8c6FCb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2345 Add GridPlus GRID Token info.
  blockchains/ethereum/assets/0x12B19D3e2ccc14Da04FAe33e63652ce469b3F2FD/info.json
Labels: Payment Status: Requested

#2347 Update app.zerion.io.png
  dapps/app.zerion.io.png
Labels: Payment Status: Requested

#2349 Add research option to Bitcoin
  blockchains/bitcoin/info/info.json
Labels: Payment Status: Requested

#2351 Upload Retric logo
  blockchains/ethereum/assets/0xAb89A337Ed77004937cB635BA5Bb5D63d5B272eA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2350 Add Logo
  blockchains/ethereum/assets/0xcC275e3543D42b8A31dCF8EC859f2fBd384B4B57/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2360 update logo and info
  blockchains/ethereum/assets/0x69DC5556A91DFab39f8D50f6FE552296F2268Dda/info.json
  blockchains/ethereum/assets/0x69DC5556A91DFab39f8D50f6FE552296F2268Dda/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2359 Add ALEPH token ERC-20, NEP-5 and NRC-20 (aleph.im project)
  blockchains/ethereum/assets/0xC0134b5B924c2FCA106eFB33C45446c466FBe03e/info.json
  blockchains/ethereum/assets/0xC0134b5B924c2FCA106eFB33C45446c466FBe03e/logo.png
  blockchains/ethereum/whitelist.json
  blockchains/neo/assets/2efdb22c152896964665d0a8214dc7bd59232162/info.json
  blockchains/neo/assets/2efdb22c152896964665d0a8214dc7bd59232162/logo.png
  blockchains/neo/blacklist.json
  blockchains/neo/whitelist.json
  blockchains/nuls/assets/NULSd6HgyZkiqLnBzTaeSQfx1TNg2cqbzq51h/info.json
  blockchains/nuls/assets/NULSd6HgyZkiqLnBzTaeSQfx1TNg2cqbzq51h/logo.png
  blockchains/nuls/blacklist.json
  blockchains/nuls/whitelist.json
  script/gen_list.ts
Labels: Payment Status: Paid, Payment Status: Requested

#2367 erush has been added.
  blockchains/ethereum/assets/0x3cC5EB07E0e1227613F1DF58f38b549823d11cB9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2353 TAM erc20 Cryptocurrency
  blockchains/ethereum/assets/0x9dBBCE383808b1981441dAa62989Ef584274AB2f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2368 Trips token
  blockchains/ethereum/assets/0x1350fbe8ce27762ec19134bf8fc405a427fe9bf1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2357 Adding Y.S Token Logo
  blockchains/ethereum/assets/0x627B9057549CE79ca1dE9dE5019EE5cfa1EaDC86/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2371 add icon to monnos token
  blockchains/ethereum/assets/0x53884b61963351C283118a8E1Fc05BA464a11959/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2370 Add logo for FairRun.Money
  blockchains/ethereum/assets/0x316B888BaA51AA71B5B7fCbeD4FeFb5B22EB6Ae1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2374 Added Bankroll Vault Token
  blockchains/ethereum/assets/0x6b785a0322126826d8226d77e173d75DAfb84d11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2376 Updated padding for Bankroll Vault Token
  blockchains/ethereum/assets/0x6b785a0322126826d8226d77e173d75DAfb84d11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2378 Merge-bot config: add user kolya182 as assign-on-pay.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#2377 Add FSXC
  blockchains/ethereum/assets/0x0c2e3bbc4646c872a3F5A745D2902aFFda82C58a/logo.png
  script/arrange_files.ts
  src/test/helpers.ts
Labels: Payment Status: Requested

#2385 Merge bot config: Include zachzwei github user.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#2380 Add new logo for 0x4b5889a61bacf0ec18472ea4861c2bf0ae61e2e1
  blockchains/ethereum/assets/0x4b5889a61bACf0EC18472EA4861c2bf0Ae61e2E1/logo.png
Labels: Payment Status: Requested

#2391 Added research links
  blockchains/aeternity/info/info.json
  blockchains/aion/info/info.json
  blockchains/algorand/info/info.json
  blockchains/ark/info/info.json
  blockchains/band/info/info.json
  blockchains/binance/info/info.json
  blockchains/bitcoin/info/info.json
  blockchains/bitcoincash/info/info.json
  blockchains/bitcoingold/info/info.json
  blockchains/cardano/info/info.json
  blockchains/classic/info/info.json
  blockchains/cosmos/info/info.json
  blockchains/dash/info/info.json
  blockchains/doge/info/info.json
  blockchains/eos/info/info.json
  blockchains/ethereum/info/info.json
  blockchains/gochain/info/info.json
  blockchains/groestlcoin/info/info.json
  blockchains/harmony/info/info.json
  blockchains/icon/info/info.json
  blockchains/iost/info/info.json
  blockchains/iotex/info/info.json
  blockchains/kava/info/info.json
  blockchains/litecoin/info/info.json
  blockchains/nano/info/info.json
  blockchains/nebulas/info/info.json
  blockchains/neo/info/info.json
  blockchains/nuls/info/info.json
  blockchains/ontology/info/info.json
  blockchains/poa/info/info.json
  blockchains/qtum/info/info.json
  blockchains/ravencoin/info/info.json
  blockchains/ripple/info/info.json
  blockchains/solana/info/info.json
  blockchains/steem/info/info.json
  blockchains/stellar/info/info.json
  blockchains/tezos/info/info.json
  blockchains/theta/info/info.json
  blockchains/thundertoken/info/info.json
  blockchains/tomochain/info/info.json
  blockchains/tron/info/info.json
  blockchains/vechain/info/info.json
  blockchains/viacoin/info/info.json
  blockchains/wanchain/info/info.json
  blockchains/waves/info/info.json
  blockchains/xrp/info/info.json
  blockchains/zcash/info/info.json
  blockchains/zcoin/info/info.json
  blockchains/zilliqa/info/info.json
Labels: Payment Status: Requested

#2386 COJAM Logo Upload
  blockchains/ethereum/assets/0x5c1209acd4fAE170Eea93c830A0CB74Bc5f9eF2b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2393 Add for.tube logo
  dapps/for.tube.png
Labels: Payment Status: Paid, Payment Status: Requested

#2390 TOKEN BADGE NEWOWIYAH Buffalo
  blockchains/ethereum/assets/0x132b2EDECC3EC84C887fab43B35db7A5F87629D4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2394 Update LOVE logo
  blockchains/ethereum/assets/0x58e1a16Cc86FE135b6f0e478B383a2f8D75B4652/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2397 Add BAGS Token to Trust Wallet
  blockchains/ethereum/assets/0x69b6ab6866bcebeca2a1afb203d210bac57d6267/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2396 Add Token Logo
  blockchains/ethereum/assets/0x6eC4Bd455ccEc9695A24A9DD702ed8fa8f69b27e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2402 Update asset logo requirements, with note on dark mode.
  README.md
Labels: Payment Status: Requested

#2400 Fixed links for research
  blockchains/dash/info/info.json
  blockchains/decred/info/info.json
Labels: Payment Status: Requested

#2404 Add logo for HXB
  blockchains/ethereum/assets/0x0FFF95D5ab18c763c42C209F137C47354af104a8/logo.png
  blockchains/ethereum/assets/0x69b6AB6866bCeBECa2A1AFB203D210BaC57D6267/logo.png
  blockchains/ethereum/assets/0x9BB6fd000109E24Eb38B0Deb806382fF9247E478/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2388 Updated DAC token address
  blockchains/ethereum/assets/0x2c9ff8cd4266de4ba3a8a8e53391853cdb595c23/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2406 Update ethereum whitelist
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#2407 Update ethereum whitelist and blacklist
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#2415 Add logo to Trustwallet
  blockchains/ethereum/assets/0xF7f1e82886491c1D3224945Aa7d318e111130Fa9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2408 Wise Token Logo Update
  blockchains/ethereum/assets/0x511759F0318750c7A9B5d2e083253720F4cE63A6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2413 Please add POINT on TrustWallet
  blockchains/ethereum/assets/0x675a1f8750C1e6a3fd8708E224283dE843BF28EC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2410 List giga token
  blockchains/ethereum/assets/0xF524F62058e5bb80AEcec2E8795fBAdbFcd8Dac0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2421 Pr/2420
  blockchains/ethereum/assets/0xD6940A1FfD9F3B025D1F1055AbCfd9F7CdA81eF9/logo.png
Labels: Payment Status: Requested

#2423 Add UniBombv3 logo
  blockchains/ethereum/assets/0x265Ba42daF2D20F3F358a7361D9f69Cb4E28F0E6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2422 VTIS
  blockchains/ethereum/assets/0xBCD2Eac03b41c8afb199455fDe76F11f5249A7b1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2427 GetBlockCard.com TERN Crypto credit card.
  blockchains/ethereum/assets/0x9687F9dbEBb76a2A469925CCE797F3015d2C68fd/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2432 Pr/2428
  blockchains/ethereum/assets/0xa7AB17FE18fe2EF1b211b95BE0D3B3a121823758/logo.png
Labels: Payment Status: Requested

#2433 update readme.md
  README.md
Labels: Payment Status: Requested

#2431 EMIT is a Token Liquidity layer for a liquidity pool.
  blockchains/ethereum/assets/0x7cE0641D19095ed3226fC5222836901bcE41585D/logo.png
  blockchains/ethereum/assets/0xb5f278Ee11811eFEC0692EC61b1e9f9984f2de11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2435 Cygnity Token logo Update
  blockchains/ethereum/assets/0x254bCa53A17A1C6E1AdA05C06aff042684E846c2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2437 Ethart logo
  blockchains/ethereum/assets/0x44b6e3e85561ce054aB13Affa0773358D795D36D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2438 Different address
  blockchains/ethereum/assets/0x24283732C3DF91EE1e4354a3934C14B88B2d9a51/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2440 Velantis
  blockchains/ethereum/assets/0x07bAd4bCD55F39B96f00ddfFca09201d86BCF3aC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2444 NMP token logo update
  blockchains/ethereum/assets/0x4D6b9f281AF31916a0f16D1cEA2ec7384851EAAb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2445 Add $STONK token logo
  blockchains/ethereum/assets/0xb60Fde5D798236fBF1e2697B2A0645380921FccF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2446 Atlantis token
  blockchains/ethereum/assets/0x821144518dfE9e7b44fCF4d0824e15e8390d4637/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2447 Add files via upload
  blockchains/ethereum/assets/0x61cDb66e56FAD942a7b5cE3F419FfE9375E31075/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2448 Update logo.png
  blockchains/binance/assets/TOMOB-4BC/logo.png
Labels: Payment Status: Requested

#2436 BET Token logo update
  blockchains/ethereum/assets/0x64d0260eF0BA835c427603a3DECEe49f539653E9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2450 Add BAL (Balancer Governance Token)
  blockchains/ethereum/assets/0xba100000625a3754423978a60c9317c58a424e3D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2452 I am adding my erc20 token: HELL (HELL)
  blockchains/ethereum/assets/0x1bdcFe02C54362cE935D13D5314ac76e0Af20AB7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2451 Statera's index fund BPT token logo
  blockchains/ethereum/assets/0x0e511Aa1a137AaD267dfe3a6bFCa0b856C1a3682/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2398 Updated logo to work in dark and light modes
  blockchains/ethereum/assets/0x58b6A8A3302369DAEc383334672404Ee733aB239/logo.png
Labels: Payment Status: Requested

#2458 adding logo and info to EasySwap
  blockchains/ethereum/assets/0xA0471cdd5c0dc2614535fD7505b17A651a8F0DAB/info.json
  blockchains/ethereum/assets/0xA0471cdd5c0dc2614535fD7505b17A651a8F0DAB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2459 Add PoWM token
  blockchains/ethereum/assets/0xa12BD9d0f059349055a3Dc4e38833171B4ad2A35/info.json
  blockchains/ethereum/assets/0xa12BD9d0f059349055a3Dc4e38833171B4ad2A35/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2457 Merge bot config: Make closing message more informative
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#2434 pull code
  blockchains/ethereum/assets/0xBD6467a31899590474cE1e84F70594c53D628e46/info.json
  blockchains/ethereum/assets/0xBD6467a31899590474cE1e84F70594c53D628e46/logo.png
Labels: Payment Status: Requested

#2465 Upload TKX
  blockchains/ethereum/assets/0x058Ef0Ba85E053e55d357C8A95BC6Ea7458Def8a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2469 Add Aryacoin
  blockchains/aryacoin/info/info.json
  blockchains/aryacoin/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2466 Add files via upload
  blockchains/ethereum/assets/0x19EdFbe9814AF6eeE88289fdd789BC473e84f8F7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2468 Add logo to trustwallet
  blockchains/ethereum/assets/0x1E32dDef10781e3C6a19883430F0E78A10B21217/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2472 Please add BLT1 on TrustWallet
  blockchains/ethereum/assets/0x28317D822b6AC5A9f5B374536Eb157E3f424c8D0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2461 Addition of Aave Uniswap Market aTokens and fixes
  blockchains/ethereum/assets/0x048930eec73c91B44b0844aEACdEBADC2F2b6efb/info.json
  blockchains/ethereum/assets/0x048930eec73c91B44b0844aEACdEBADC2F2b6efb/logo.png
  blockchains/ethereum/assets/0x1D0e53A0e524E3CC92C1f0f33Ae268FfF8D7E7a5/info.json
  blockchains/ethereum/assets/0x1D0e53A0e524E3CC92C1f0f33Ae268FfF8D7E7a5/logo.png
  blockchains/ethereum/assets/0x3a3A65aAb0dd2A17E3F1947bA16138cd37d08c04/info.json
  blockchains/ethereum/assets/0x3a3A65aAb0dd2A17E3F1947bA16138cd37d08c04/logo.png
  blockchains/ethereum/assets/0x6179078872605396Ee62960917128F9477a5DdbB/info.json
  blockchains/ethereum/assets/0x6179078872605396Ee62960917128F9477a5DdbB/logo.png
  blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/info.json
  blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/logo.png
  blockchains/ethereum/assets/0x84BBcaB430717ff832c3904fa6515f97fc63C76F/info.json
  blockchains/ethereum/assets/0x84BBcaB430717ff832c3904fa6515f97fc63C76F/logo.png
  blockchains/ethereum/assets/0x8c69f7A4C9B38F1b48005D216c398Efb2F1Ce3e4/info.json
  blockchains/ethereum/assets/0x8c69f7A4C9B38F1b48005D216c398Efb2F1Ce3e4/logo.png
  blockchains/ethereum/assets/0x9548DB8b1cA9b6c757485e7861918b640390169c/info.json
  blockchains/ethereum/assets/0x9548DB8b1cA9b6c757485e7861918b640390169c/logo.png
  blockchains/ethereum/assets/0xBbBb7F2aC04484F7F04A2C2C16f20479791BbB44/info.json
  blockchains/ethereum/assets/0xBbBb7F2aC04484F7F04A2C2C16f20479791BbB44/logo.png
  blockchains/ethereum/assets/0xb977ee318010A5252774171494a1bCB98E7fab65/info.json
  blockchains/ethereum/assets/0xb977ee318010A5252774171494a1bCB98E7fab65/logo.png
  blockchains/ethereum/assets/0xc88ebbf7C523f38Ef3eB8A151273C0F0dA421e63/info.json
  blockchains/ethereum/assets/0xc88ebbf7C523f38Ef3eB8A151273C0F0dA421e63/logo.png
  blockchains/ethereum/assets/0xe02b2Ad63eFF3Ac1D5827cBd7AB9DD3DaC4f4AD0/info.json
  blockchains/ethereum/assets/0xe02b2Ad63eFF3Ac1D5827cBd7AB9DD3DaC4f4AD0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2473 resubmit_pr2466
  blockchains/ethereum/assets/0x19EdFbe9814AF6eeE88289fdd789BC473e84f8F7/logo.png
Labels: Payment Status: Requested

#2478 Coin Fella Token (CFT) logo and photo added
  blockchains/ethereum/assets/0xF989E16233ad1aD0F2aF739547eF92745341F52B/info.json
  blockchains/ethereum/assets/0xF989E16233ad1aD0F2aF739547eF92745341F52B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2477 Please add latest INNBC on TrustWallet with latest logo
  blockchains/ethereum/assets/0xB67718b98d52318240c52E71A898335da4A28c42/logo.png
  blockchains/ethereum/assets/0xEb70bbf15Fd1c0542896A80f2aF90C8FD40a9ec5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2470 Add files via upload
  blockchains/ethereum/assets/0xfE94c504D07aDBa98b23AA7C765D35357Bd185a3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2480 Roam Coin Logo Update
  blockchains/ethereum/assets/0xE9f44784396005C053dCb8EbCA74E65192a9c3Ea/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2483 Adding info.json for Blockchain Certfied Data Token
  blockchains/ethereum/assets/0xAcfa209Fb73bF3Dd5bBfb1101B9Bc999C49062a5/info.json
  blockchains/ethereum/assets/0xAcfa209Fb73bF3Dd5bBfb1101B9Bc999C49062a5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2479 Add SSAL TOKEN image
  blockchains/ethereum/assets/0xf60cc637D2C501aD6935ffC8C8032963b0Fc419a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2485 Added Celo Blockchain Logo
  blockchains/celo/info/info.json
  blockchains/celo/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2486 Please update these logos on Trust Wallet...
  blockchains/ethereum/assets/0x05cA0E11e7C183Dd01131Cd8Bb00c87464B7a285/logo.png
  blockchains/ethereum/assets/0x4826B0316f31bEe41CfFA4a4277d2B62557f915C/logo.png
  blockchains/ethereum/assets/0xA4B4ce78A05f1e5250B1174F056ee64Db2dab38C/logo.png
  blockchains/ethereum/assets/0xE4687bD6e72E3f905fB95bCc32b82cA3D1AF4998/logo.png
  blockchains/ethereum/assets/0xda038eFdada1112992d2E7f4e14e44DE47eb2C7C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2488 Add SWINGBY-888
  blockchains/binance/assets/SWINGBY-888/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2490 Add RWS token
  blockchains/ethereum/assets/0x08AD83D779BDf2BBE1ad9cc0f78aa0D24AB97802/info.json
  blockchains/ethereum/assets/0x08AD83D779BDf2BBE1ad9cc0f78aa0D24AB97802/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2491 Update BCDT logo
  blockchains/ethereum/assets/0xAcfa209Fb73bF3Dd5bBfb1101B9Bc999C49062a5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2489 Cryptocricketclub
  blockchains/ethereum/assets/0x4f56221252d117f35E2f6Ab937A3F77CAd38934D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2493 resubmit_pr2492
  blockchains/ethereum/assets/0x60e7f0518102A4E70431960F88c1EBC98f994159/logo.png
Labels: Payment Status: Requested

#2499 Bitanium (BI) ERC20 Token Logo
  blockchains/ethereum/assets/0x5b5bB9765eff8D26c24B9FF0DAa09838a3Cd78E9/info.json
  blockchains/ethereum/assets/0x5b5bB9765eff8D26c24B9FF0DAa09838a3Cd78E9/logo.png
Labels: Payment Status: Requested

#2500 Add ETEHERUMtoken logo.
  blockchains/ethereum/assets/0x8266897D3044A030f1FCa81F18c9Ad2DaF9e5f09/logo.png
Labels: Payment Status: Requested

#2505 Please add CHOP on TrustWallet
  blockchains/ethereum/assets/0x8C60423251C62f653855777C476d76280b853960/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2504 add_kava_BinanceStaking
  blockchains/kava/validators/assets/kavavaloper1wu8m65vqazssv2rh8rthv532hzggfr3h9azwz9/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Requested

#2506 Please add latest INNBCL [0x0Cc9FCCFF81252F4bd8C5c6b359B14ae2Ed851cf]…
  blockchains/ethereum/assets/0x0Cc9FCCFF81252F4bd8C5c6b359B14ae2Ed851cf/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2501 Adding logo image for MaskFactory Token
  blockchains/ethereum/assets/0x6b60d7285504D73DD88547cf1289c3B5528827d3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2507 ADD ARTDOTDCOIN TOKEN (ADC)
  blockchains/ethereum/assets/0xc5451c3b432687A5a796c4DafD0cb4702874F92D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2508 pyrabank private
  blockchains/ethereum/assets/0xE9Bb22B2063daBA021b0384d8535Badd1426FbA7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2511 Add ATBank
  blockchains/ethereum/assets/0x2C66164F7a8564dCAAadcA8319b9f917ac418E4e/info.json
  blockchains/ethereum/assets/0x2C66164F7a8564dCAAadcA8319b9f917ac418E4e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2509 Adding Game Credits to Trust Wallet
  blockchains/ethereum/assets/0x63f88A2298a5c4AEE3c216Aa6D926B184a4b2437/info.json
  blockchains/ethereum/assets/0x63f88A2298a5c4AEE3c216Aa6D926B184a4b2437/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2510 Update Logo
  blockchains/ethereum/assets/0x2121a1B68E9C2Cc8fF4Bfd8bCD0F891ece331c51/info.json
  blockchains/ethereum/assets/0x2121a1B68E9C2Cc8fF4Bfd8bCD0F891ece331c51/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2502 Add FUCO
  dapps/futbolcoin.org.png
Labels: Payment Status: Paid, Payment Status: Requested

#2513 Add Five Token
  blockchains/ethereum/assets/0x21839a7f7e88c19a6089AdBFB3fB52606Ac6f0Dd/info.json
  blockchains/ethereum/assets/0x21839a7f7e88c19a6089AdBFB3fB52606Ac6f0Dd/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2515 Update $STONK logo for migrated 1:1 swap token.
  blockchains/ethereum/assets/0xb4058411967D5046f3510943103805be61f0600E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2512 Add Logo
  blockchains/ethereum/assets/0x49a6123356b998EF9478C495E3D162A2F4eC4363/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2516 Please Add These Logos ASAP
  blockchains/ethereum/assets/0x383891338E0e377b1B995f543758b998eb87D065/logo.png
  blockchains/ethereum/assets/0xC2Ba253771006c7fe2952e67f1780703c4707bEa/logo.png
  blockchains/ethereum/assets/0xedacc3cBcDF37fCefd16F02670c51C9cf2720015/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2495 Edit GET logo
  blockchains/ethereum/assets/0x8a854288a5976036A725879164Ca3e91d30c6A1B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
