Repository trustwallet/assets, pull requests merged in 2020-04, with the labels that each got.

#1827 Upload LOGO ZXTH
  blockchains/ethereum/assets/0xF9933cb5f0397bf020Bb950C307e30dd8f62080f/logo.png
Labels: Status: On Hold

#1873 Geopay master
  .github/workflows/generator.yml
  blockchains/ether-1/info/logo.png
  blockchains/ethereum/assets/0x04A289fe4cE5fa87a76F58d0214340fb5893A58c/logo.png
  blockchains/ethereum/assets/0x2915acaa744E36bEFb3C539c3d99d7F82ad8e6c9/logo.png
  blockchains/ethereum/assets/0x73489CE024bF775498D6eEC5dC56688f66Db48e1/logo.png
  blockchains/ethereum/assets/0x7F77a0cc3caCE8c58ccE9D153c070f312D1a1088/logo.png
  blockchains/ethereum/assets/0xafcCbdA168681038419908470e79E2353a798E1f/logo.png
  blockchains/xdc/info/logo.png
Labels: FeePayment: Requested

#1877 BITTO coin
  blockchains/ethereum/assets/0xa101E27f06A97985B925E244111b61560Ecd97DB/logo.png
Labels: FeePayment: Paid, FeePayment: Requested

#1879 Pr/1874
  .github/workflows/generator.yml
  Dangerfile
  blockchains/ethereum/assets/0x92298Fa0647b5dcFf6eEaBAb97c9Bd81b5c30D06/info.json
  blockchains/ethereum/assets/0x92298Fa0647b5dcFf6eEaBAb97c9Bd81b5c30D06/logo.png
  src/test/helpers.ts
  src/test/index.test.ts
Labels: FeePayment: Paid, FeePayment: Requested

#1880 Pr/1876
  blockchains/ethereum/assets/0xfF759254e578bc7F725428CEcb612A502E604f42/logo.png
Labels: FeePayment: Requested

#1887 Update labels used by merge-fee-bot.
  .github/merge-fee-bot.yaml
  blockchains/ethereum/assets/0xfF759254e578bc7F725428CEcb612A502E604f42/logo.png
Labels: FeePayment: Requested

#1882 Add daily update action and formatter
  .github/workflows/compress_images.yml
  .github/workflows/daily_update.yml
  .github/workflows/formatter.yml
  .github/workflows/generator.yml
  blockchains/ethereum/assets/0x42726d074BBa68Ccc15200442B72Afa2D495A783/logo.png
  blockchains/ethereum/assets/0xd7E1e4530D95717506633E58437f056A49c1FABB/logo.png
  script/erc20_to_checksum.ts
  script/format_files_name.ts
  src/test/helpers.ts
Labels: FeePayment: Requested

#1894 Update InTime (ITO) Contract Address
  blockchains/ethereum/assets/0x293B0Cd0991DB07c8529fEBb01bc7D052315C5Ab/logo.png
  blockchains/ethereum/assets/0x5E5Bc236D024Cd26BE780802aaf1E0dC118fc484/logo.png
Labels: FeePayment: Paid, Payment Status: Requested

#1895 Update Logo
  blockchains/ethereum/assets/0x31126416F0dbC1283DC5295EE6ea04Ff83eE3531/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1897 Update OnTime (OTO) Contract Address
  blockchains/ethereum/assets/0x028CE5EA3298a50c0D8a27b937b1F48Cf0d68b56/logo.png
  blockchains/ethereum/assets/0xC52b11283f4CA6bD20cbC4AdDD2C136a193F6aF1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1893 First Update Logo
  blockchains/ethereum/assets/0x851be0d936cb611d2caB3C3963338288445C1e52/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1899 HETM
  blockchains/ethereum/assets/0x7A5E6ca9d335e343D1Ed12239F67248E056AFE2f/logo.png
Labels: Payment Status: Requested

#1896 Upload Bitcollar Max
  blockchains/ethereum/assets/0xF5Bb691215fd2839Bc14Aa93335e13d839A4767f/logo.png
  package-lock.json
  package.json
  script/arrange_files.ts
  src/test/helpers.ts
Labels: FeePayment: Paid, Payment Status: Requested

#1898 Upload UNB
  blockchains/ethereum/assets/0xCaBeC58a571979f9fE825885fcb8F7A93892eaB0/logo.png
Labels: FeePayment: Paid, Payment Status: Requested

#1875 DBD Token logo update
  blockchains/ethereum/assets/0x6D6CC526EB192D0bf8feabA959bAbA384C5Cf100/logo.png
Labels: FeePayment: Requested

#1907 Add files via upload
  blockchains/ethereum/assets/0x2e3C062E16c1a3a04Ddc5003c62E294305d83684/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1883 JAC Token Logo update
  blockchains/ethereum/assets/0x2d2621A2A41dd907CFBd01F66c826e2BEE14e198/logo.png
Labels: FeePayment: Requested, Status: Correction needed

#1901 Blacklist E2C ERC20
  blockchains/ethereum/assets/0x2e3C062E16c1a3a04Ddc5003c62E294305d83684/logo.png
  blockchains/ethereum/assets/0x7e4A9B2BfDDcc37D042B881e48344A560Ad7c462/logo.png
  blockchains/ethereum/assets/0x9e0aC56cbC1B247Cac5bE03d1ee757aB88E0771c/logo.png
  blockchains/ethereum/assets/0xCaBeC58a571979f9fE825885fcb8F7A93892eaB0/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: FeePayment: Paid, Payment Status: Requested

#1926 Pr/1923
  blockchains/ethereum/assets/0x60ec679cf3a48d89EfA774FCcD3Dc59Ef1401330/info.json
  blockchains/ethereum/assets/0x60ec679cf3a48d89EfA774FCcD3Dc59Ef1401330/logo.png
Labels: Payment Status: Requested

#1927 Pr/1914
  blockchains/ethereum/assets/0x441e2C4EB49c00f835b9d2dE1Aa59F27b69F949f/logo.png
Labels: Payment Status: Requested

#1913 Add new Logo for token
  blockchains/ethereum/assets/0x6aB9DcA785E4a8Fe7F716302dFBC0fC3129407F8/logo.png
Labels: FeePayment: Paid, Payment Status: Requested

#1917 Add files via upload
  blockchains/ethereum/assets/0x8aF5648EC4ACa18484a2718c6f7672e51DC152BF/logo.png
Labels: FeePayment: Paid, Payment Status: Requested

#1890 Updates pTokens pBTC
  blockchains/ethereum/assets/0x5228a22e72ccC52d415EcFd199F99D0665E7733b/info.json
  blockchains/ethereum/assets/0x5228a22e72ccC52d415EcFd199F99D0665E7733b/logo.png
Labels: FeePayment: Paid, Payment Status: Requested

#1916 DTO token logo update
  blockchains/ethereum/assets/0xd0207f76A97aD3779b7731ab1fc4cF926a508E87/logo.png
Labels: Payment Status: Requested

#1928 Add logo to Cybitex token
  .github/workflows/daily_update.yml
  blockchains/ethereum/assets/0x8DE0f21eaa95f589A8a2fE69c5752fFdADA83EaD/info.json
  blockchains/ethereum/assets/0x8DE0f21eaa95f589A8a2fE69c5752fFdADA83EaD/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: FeePayment: Paid, Payment Status: Requested

#1930 update
  blockchains/tezos/validators/list.json
Labels: FeePayment: Paid, Payment Status: Requested

#1932 Added Sora token (XOR)
  blockchains/ethereum/assets/0x40FD72257597aA14C7231A7B1aaa29Fce868F677/info.json
  blockchains/ethereum/assets/0x40FD72257597aA14C7231A7B1aaa29Fce868F677/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1905 BITSCOIN
  blockchains/ethereum/assets/0x9388f54fa978aa9e24395a8b69033304eccea4df/loog.png
Labels: FeePayment: Paid, Payment Status: Requested

#1934 Run all script in daily update action
  .github/workflows/daily_update.yml
  .github/workflows/danger.yml
  .github/workflows/formatter.yml
Labels: Payment Status: Requested

#1935 Merge-fee-bot config for auto close.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1937 Update ethereum whitelist/blacklist
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#1938 Upload MXN
  blockchains/ethereum/assets/0x59A11e14514b15D5486b7fAa190Ab234DE04EdB4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1936 update wetoken logo
  blockchains/ethereum/assets/0x621E0D4E21683459A1fc4784A525095677461DbE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1945 Merge-fee-bot configuration: add maxIdleRemindHours: 13.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1946 Please Add these Tokens on Trust Wallet
  blockchains/ethereum/assets/0x7f7Cac26A300Cb2E911B0241F71A5C18f6481C9D/logo.png
  blockchains/ethereum/assets/0x9e0aC56cbC1B247Cac5bE03d1ee757aB88E0771c/logo.png
  blockchains/ethereum/assets/0xdb352e55DaAd68B632554410F2D392263fF22b06/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1947 Update Cent logo
  dapps/beta.cent.co.png
Labels: Payment Status: Requested

#1948 README.md
  README.md
Labels: Payment Status: Requested

#1951 Merge bot config: add reminder message
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1950 create egyptoken.com.png
  dapps/egyptoken.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#1949 Added 4 New Tokens to Trust Wallet to iBBT.io
  blockchains/ethereum/assets/0x2915ACAA744E36BEFB3C539C3D99D7F82AD8E6C9/logo.png
  blockchains/ethereum/assets/0x76ace4e080c49f04a6c12756c036d3627f6b1e69/logo.png
  blockchains/ethereum/assets/0x88f400F6a26465c9ac6AE5c1C8C14Cf12B515C96/logo.png
  blockchains/ethereum/assets/0xAFCCBDA168681038419908470E79E2353A798E1F/logo.png
  blockchains/ethereum/assets/0xF80417fac69547A1776D68F8c9DFB16Ba0eAE09D/logo.png
  blockchains/ethereum/assets/0xb35e3E3E8A95Fd245d5C912118045459AaB9243b/logo.png
  blockchains/ethereum/assets/0xd7a150D2eDfE324166436ea0766294634B811Bb5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1953 Update YUNG
  blockchains/ethereum/assets/0xbE47f50c85d9f3da055bc8CddAA33DEa16926D9D/logo.png
Labels: Payment Status: Requested

#1952 Merge bot: Increase fee amount (2000 TWT, 1.0 BNB).
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1956 Add logo for UMA voting token v1
  blockchains/ethereum/assets/0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1957 Update info.json
  blockchains/decred/info/info.json
Labels: Payment Status: Requested

#1960 Merge fee bot: Adjust price to 1 BNB (0.5 was left in static text).
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1965 adds PegNet pUsd asset
  blockchains/ethereum/assets/0x93d3296cac208422BF587c3597D116e809870f2b/info.json
  blockchains/ethereum/assets/0x93d3296cac208422BF587c3597D116e809870f2b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1964 Add STPAY
  blockchains/ethereum/assets/0x5c250ff9b993C6991cC4A3cC543716e53b478018/info.json
  blockchains/ethereum/assets/0x5c250ff9b993C6991cC4A3cC543716e53b478018/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1954 M/tezos bakers info
  blockchains/ethereum/assets/0x2915acaa744E36bEFb3C539c3d99d7F82ad8e6c9/0x2915acaa744E36bEFb3C539c3d99d7F82ad8e6c9-temp/logo.png
  blockchains/ethereum/assets/0xafcCbdA168681038419908470e79E2353a798E1f/0xafcCbdA168681038419908470e79E2353a798E1f-temp/logo.png
  blockchains/tezos/validators/list.json
  package.json
  script/gen_validators_tezos.ts
  src/test/helpers.ts
  src/test/index.test.ts
  src/test/models.ts
Labels: Payment Status: Requested

#1959 Add auto update validators info
  .github/workflows/update_validators_info.yml
Labels: Payment Status: Requested

#1976 ADD Best US Token (BEST) token logo Trust wallet
  blockchains/ethereum/assets/0x71C830A05d787c1316a55bf9055a6f5920218537/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1970 First update logo
  blockchains/ethereum/assets/0xd09B4a4Cc6F092959478C693F3933cD27dA75244/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1972 ADD Nise Chain (STO) token logo Trust wallet
  blockchains/ethereum/assets/0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5.png
Labels: Payment Status: Paid, Payment Status: Requested

#1979 Please add these Tokens on Trust Wallet
  blockchains/ethereum/assets/0x514DFb37fd6F9d8F0bf653828aAdA3fD1D96bF8C/logo.png
  blockchains/ethereum/assets/0x6275181a6480Deb056B60c2ABa055bFD56C3c5fb/logo.png
  blockchains/ethereum/assets/0x812456F20215B291fd1246a4A63065E38961949f/logo.png
  blockchains/ethereum/assets/0xa9F7c93EFB9FFAe7dFaC51FFb168a9a2C06afdB1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1958 Add auto assign
  .github/CODEOWNERS
Labels: Payment Status: Requested

#1963 Updated logo for REV asset
  blockchains/ethereum/assets/0x2ef52Ed7De8c5ce03a4eF0efbe9B7450F2D7Edc9/logo.png
Labels: Payment Status: Requested

#1978 Add token logo
  blockchains/thundertoken/assets/0x876e7D048c6151e3D0F93AaBfBf5B7Da605d416F/logo.png
Labels: Payment Status: Paid

#1983 OTRN token logo update
  blockchains/ethereum/assets/0xf500e14c35298b7b741a42fd1f0effbae46d5393/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1989 Update Logo
  blockchains/ethereum/assets/0x0eB43ce1708f415DfB1734A3F69a89403011A4C1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1984 Merge-fee-bot config: Reduce reminder frequency, reduce closing time.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#1986 Add files via upload
  blockchains/thundertoken/assets/0xDDf952D68ff6aBC03B6Dd06E98DaD8829a1d2bb3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1996 Pr/1995
  blockchains/ethereum/assets/0x521A2aC7b33b09fA21A1aD7C040F4e1b5912C1d0/logo.png
  script/arrange_files.ts
Labels: Payment Status: Requested

#1982 PLUS token logo update
  blockchains/ethereum/assets/0xdf8673049bfcac01244847d955d139d20815ea84/logo.png
Labels: Payment Status: Requested

#2004 Add files via upload
  blockchains/ethereum/assets/0x8a5ad873a1a615001acc1757214f67e1ba145cc9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2003 Add Logo
  blockchains/ethereum/assets/0x07B1F172268e1737C3176b50033dCbD7755284EE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2000 Add Halloween Token
  blockchains/ethereum/assets/0x82Ef11f04Bc3cb863373aDdf5558dbc01d8F9b9b/info.json
  blockchains/ethereum/assets/0x82Ef11f04Bc3cb863373aDdf5558dbc01d8F9b9b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1999 add-assets-cartesi-ctsi
  blockchains/ethereum/assets/0x491604c0FDF08347Dd1fa4Ee062a822A5DD06B5D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1998 Add files via upload
  blockchains/ethereum/assets/0x0bCd6FaeF90877ac73bB245dF6CE3C0EC9E95BfE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#1997 Add PR test CI
  .github/workflows/daily_update.yml
  .github/workflows/pr-ci.yml
  README.md
  azure-pipelines.yml
  blockchains/ethereum/assets/0x13c2B7F851E756415cF7d51d04dcF4F94A5b382E/logo.png
  blockchains/ethereum/assets/0x5ABaFf0B83F81DC061C590AAdcbA013C69237fd7/logo.png
  blockchains/ethereum/assets/0x686C650dbcFEaa75D09B883621Ad810F5952bD5d/logo.png
  blockchains/ethereum/assets/0x79C5a1Ae586322A07BfB60be36E1b31CE8C84A1e/logo.png
  blockchains/ethereum/assets/0xa0B207103F764A920b4AF9e691F5bd956DE14DED/logo.png
  package-lock.json
  package.json
  pricing/coinmarketcap/mapping.json
  script/commit.sh
Labels: Payment Status: Requested

#2005 Add PALA INT COMM
  blockchains/thundertoken/assets/0xeff6f1612d03205BA5E8d26cAc1397bf778ab1AC/logo.png
  blockchains/thundertoken/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2008 Add PALA INT COMM
  blockchains/ethereum/assets/0xD20fb5cf926Dc29c88f64725e6f911f40f7bf531/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2007 Add GlobalEdu (GEFT)
  blockchains/ethereum/assets/0xd0464A1985edB76Ba82602534a2d89d8cCf3B7Ec/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2009 Add 3FA Ethereum token logo
  blockchains/ethereum/assets/0x4263A2f0456305d7d10F8a4555f8c3B593b3b895/info.json
  blockchains/ethereum/assets/0x4263A2f0456305d7d10F8a4555f8c3B593b3b895/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2012 Add Ethereum GRIG token logo and info
  blockchains/ethereum/assets/0x618aCb9601cb54244F5780F09536DB07d2C7aCf4/info.json
  blockchains/ethereum/assets/0x618aCb9601cb54244F5780F09536DB07d2C7aCf4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2013 Add files via upload
  blockchains/ethereum/assets/0x245b78F9957F0Dc435D1c093C64D2DEFE78577b2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2006 Update validators requirements
  README.md
  blockchains/tezos/validators/assets/tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA/logo.png
  blockchains/tezos/validators/assets/tz1RSWMYKGAykpizFteowByYMueCYv9TMn1L/logo.png
  blockchains/tezos/validators/assets/tz1STeamwbp68THcny9zk3LsbG3H36DMvbRK/logo.png
  blockchains/tezos/validators/assets/tz1XXayQohB8XRXN7kMoHbf2NFwNiH3oMRQQ/logo.png
  blockchains/tezos/validators/assets/tz1XhnCdVENzgko5x1MMswLHSoQbJ5NPwLZ6/logo.png
  blockchains/tezos/validators/assets/tz1d6Fx42mYgVFnHUW8T8A7WBfJ6nD9pVok8/logo.png
  blockchains/tezos/validators/assets/tz1dNVDWPf3Q59SdJqnjdnu277iyvReiRS9M/logo.png
  blockchains/tezos/validators/assets/tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS/logo.png
  blockchains/tezos/validators/assets/tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194/logo.png
  blockchains/tezos/validators/assets/tz1isXamBXpTUgbByQ6gXgZQg4GWNW7r6rKE/logo.png
  blockchains/tezos/validators/list.json
  script/gen_validators_tezos.ts
  src/test/models.ts
Labels: Payment Status: Requested

#2018 Addition Of The ProNet Coin Information To Trust Wallet
  blockchains/ethereum/assets/0x33fefc811a86474a832d38926428a1dade431f25/info.json
  blockchains/ethereum/assets/0x33fefc811a86474a832d38926428a1dade431f25/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
