Repository trustwallet/assets, pull requests merged in 2020-12, with the labels that each got.

#4928 Smart Node, Being Trust Wallet validators list
  blockchains/tezos/validators/assets/tz1NMNQYrYrfNpmUqQrMhJypf6ovnaDZhJHM/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#4965 add app.swipe.org logo
  dapps/app.swipe.org.png
Labels: Payment Status: Requested

#4968 add venus vTokens
  blockchains/smartchain/assets/0x151B1e2635A717bcDc836ECd6FbB62B674FE3E1D/info.json
  blockchains/smartchain/assets/0x151B1e2635A717bcDc836ECd6FbB62B674FE3E1D/logo.png
  blockchains/smartchain/assets/0x2fF3d0F6990a40261c66E1ff2017aCBc282EB6d0/info.json
  blockchains/smartchain/assets/0x2fF3d0F6990a40261c66E1ff2017aCBc282EB6d0/logo.png
  blockchains/smartchain/assets/0x95c78222B3D6e262426483D42CfA53685A67Ab9D/info.json
  blockchains/smartchain/assets/0x95c78222B3D6e262426483D42CfA53685A67Ab9D/logo.png
  blockchains/smartchain/assets/0xA07c5b74C9B40447a954e1466938b865b6BBea36/info.json
  blockchains/smartchain/assets/0xA07c5b74C9B40447a954e1466938b865b6BBea36/logo.png
  blockchains/smartchain/assets/0xecA88125a5ADbe82614ffC12D0DB554E2e2867C8/info.json
  blockchains/smartchain/assets/0xecA88125a5ADbe82614ffC12D0DB554E2e2867C8/logo.png
  blockchains/smartchain/assets/0xfD5840Cd36d94D7229439859C0112a4185BC0255/info.json
  blockchains/smartchain/assets/0xfD5840Cd36d94D7229439859C0112a4185BC0255/logo.png
Labels: Payment Status: Requested

#4975 update BCH logos
  blockchains/binance/assets/BCH-1FD/logo.png
  blockchains/binance/assets/BCHA-959/logo.png
Labels: Payment Status: Requested

#4985 Update Netkoin logo and info
  blockchains/ethereum/assets/0x5D4d57cd06Fa7fe99e26fdc481b468f77f05073C/info.json
  blockchains/ethereum/assets/0x5D4d57cd06Fa7fe99e26fdc481b468f77f05073C/logo.png
Labels: Payment Status: Paid

#4977 Added top Uniswap ERC20/BEP20 to Tokenlist 12-02-2020
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#4980 Updating BART Logo
  blockchains/ethereum/assets/0x54C9EA2E9C9E8eD865Db4A4ce6711C2a0d5063Ba/info.json
  blockchains/ethereum/assets/0x54C9EA2E9C9E8eD865Db4A4ce6711C2a0d5063Ba/logo.png
Labels: Payment Status: Paid

#4998 [internal] update documentation link
  .github/merge-fee-bot.yaml
  README.md
  blockchains/ethereum/assets/0x54C9EA2E9C9E8eD865Db4A4ce6711C2a0d5063Ba/info.json
  blockchains/ethereum/assets/0x5D4d57cd06Fa7fe99e26fdc481b468f77f05073C/info.json
Labels: Payment Status: Requested

#4962 add SKL logo
  blockchains/ethereum/assets/0x00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7/info.json
  blockchains/ethereum/assets/0x00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4999 [internal] Revert BarterTrade info (deleted accidentally)
  blockchains/ethereum/assets/0x54C9EA2E9C9E8eD865Db4A4ce6711C2a0d5063Ba/info.json
Labels: Payment Status: Requested

#5004 add ERC20 BASE
  blockchains/ethereum/assets/0x07150e919B4De5fD6a63DE1F9384828396f25fDC/logo.png
Labels: Payment Status: Requested

#5000 [internal] Add Solana token infrastructure, Serum token.
  blockchains/solana/allowlist.json
  blockchains/solana/assets/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/info.json
  blockchains/solana/assets/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt/logo.png
  blockchains/solana/denylist.json
  script/generic/asset-infos.ts
  script/generic/blockchains.ts
Labels: Payment Status: Requested

#5007 Add NEX Token (Logo+Info)
  blockchains/ethereum/assets/0xE2dc070524A6e305ddB64d8513DC444B6a1ec845/info.json
  blockchains/ethereum/assets/0xE2dc070524A6e305ddB64d8513DC444B6a1ec845/logo.png
Labels: Payment Status: Paid

#5024 [Zcoin] Add new firo logo
  blockchains/zcoin/info/logo.png
Labels: Payment Status: Requested

#5030 Add PPAY token logo and info
  blockchains/ethereum/assets/0x054D64b73d3D8A21Af3D764eFd76bCaA774f3Bb2/info.json
  blockchains/ethereum/assets/0x054D64b73d3D8A21Af3D764eFd76bCaA774f3Bb2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5014 add tgx token
  blockchains/ethereum/assets/0x364A7381A5b378CeD7AB33d1CDf6ff1bf162Bfd6/info.json
  blockchains/ethereum/assets/0x364A7381A5b378CeD7AB33d1CDf6ff1bf162Bfd6/logo.png
Labels: Payment Status: Paid

#5031 Add Folder Protocol Token FOL
  blockchains/ethereum/assets/0xA8580F3363684d76055bdC6660CaeFe8709744e1/info.json
  blockchains/ethereum/assets/0xA8580F3363684d76055bdC6660CaeFe8709744e1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5025 Update Cybervein Logo
  blockchains/ethereum/assets/0xBe428c3867F05deA2A89Fc76a102b544eaC7f772/info.json
  blockchains/ethereum/assets/0xBe428c3867F05deA2A89Fc76a102b544eaC7f772/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5044 add vBTC, vETH, vLTC and vXRP
  blockchains/smartchain/assets/0x57A5297F2cB2c0AaC9D554660acd6D385Ab50c6B/info.json
  blockchains/smartchain/assets/0x57A5297F2cB2c0AaC9D554660acd6D385Ab50c6B/logo.png
  blockchains/smartchain/assets/0x882C173bC7Ff3b7786CA16dfeD3DFFfb9Ee7847B/info.json
  blockchains/smartchain/assets/0x882C173bC7Ff3b7786CA16dfeD3DFFfb9Ee7847B/logo.png
  blockchains/smartchain/assets/0xB248a295732e0225acd3337607cc01068e3b9c10/info.json
  blockchains/smartchain/assets/0xB248a295732e0225acd3337607cc01068e3b9c10/logo.png
  blockchains/smartchain/assets/0xf508fCD89b8bd15579dc79A6827cB4686A3592c8/info.json
  blockchains/smartchain/assets/0xf508fCD89b8bd15579dc79A6827cB4686A3592c8/logo.png
Labels: Payment Status: Requested

#5049 add ERC20 BONDLY
  blockchains/ethereum/assets/0xD2dDa223b2617cB616c1580db421e4cFAe6a8a85/logo.png
Labels: Payment Status: Requested

#5035 Add SPN Token Logo and Info
  blockchains/ethereum/assets/0x20F7A3DdF244dc9299975b4Da1C39F8D5D75f05A/info.json
  blockchains/ethereum/assets/0x20F7A3DdF244dc9299975b4Da1C39F8D5D75f05A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5036 Wloki
  blockchains/ethereum/assets/0x5ff668ddfDcBB7505f41ED56e626E4D4719DcB26/info.json
  blockchains/ethereum/assets/0x5ff668ddfDcBB7505f41ED56e626E4D4719DcB26/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5047 Add WIOV
  blockchains/ethereum/assets/0x175D9Dfd6850AA96460E29bC0cEad05756965E91/info.json
  blockchains/ethereum/assets/0x175D9Dfd6850AA96460E29bC0cEad05756965E91/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5027 Add Mirror Protocol (MIR)
  blockchains/ethereum/assets/0x09a3EcAFa817268f77BE1283176B946C4ff2E608/info.json
  blockchains/ethereum/assets/0x09a3EcAFa817268f77BE1283176B946C4ff2E608/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5050 Update tokenlist.json
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid, Payment Status: Requested

#5040 add RFUEL token
  blockchains/ethereum/assets/0xaf9f549774ecEDbD0966C52f250aCc548D3F36E5/info.json
  blockchains/ethereum/assets/0xaf9f549774ecEDbD0966C52f250aCc548D3F36E5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5051 Add WOZX logo
  blockchains/ethereum/assets/0x34950Ff2b487d9E5282c5aB342d08A2f712eb79F/info.json
  blockchains/ethereum/assets/0x34950Ff2b487d9E5282c5aB342d08A2f712eb79F/logo.png
Labels: Payment Status: Paid

#5052 Add BADGER info and logo
  blockchains/ethereum/assets/0x3472A5A71965499acd81997a54BBA8D852C6E53d/info.json
  blockchains/ethereum/assets/0x3472A5A71965499acd81997a54BBA8D852C6E53d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5055 Add a new token "origin D (OD)"
  blockchains/ethereum/assets/0x3C2cf21b9d4b543B93A9BcFe637F673d8BD944D8/info.json
  blockchains/ethereum/assets/0x3C2cf21b9d4b543B93A9BcFe637F673d8BD944D8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5070 edit ERC20 CYFM
  blockchains/ethereum/assets/0x4a621d9f1b19296d1C0f87637b3A8D4978e9bf82/logo.png
Labels: Payment Status: Requested

#5068 Add ACryptoS DApp (acryptos.com) and native tokens ACS, ACSI
  blockchains/smartchain/assets/0x4197C6EF3879a08cD51e5560da5064B773aa1d29/info.json
  blockchains/smartchain/assets/0x4197C6EF3879a08cD51e5560da5064B773aa1d29/logo.png
  blockchains/smartchain/assets/0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389/info.json
  blockchains/smartchain/assets/0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389/logo.png
  dapps/acryptos.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#5073 update TGX logo
  blockchains/ethereum/assets/0x364A7381A5b378CeD7AB33d1CDf6ff1bf162Bfd6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5076 update thugs logo & info
  blockchains/smartchain/assets/0xE10e9822A5de22F8761919310DDA35CD997d63c0/info.json
  blockchains/smartchain/assets/0xE10e9822A5de22F8761919310DDA35CD997d63c0/logo.png
Labels: Payment Status: Paid

#5089 edit ERC20 KEY
  blockchains/ethereum/assets/0x4CC19356f2D37338b9802aa8E8fc58B0373296E7/info.json
  blockchains/ethereum/assets/0x4CC19356f2D37338b9802aa8E8fc58B0373296E7/logo.png
Labels: Payment Status: Requested

#5079 add xUSD token
  blockchains/ethereum/assets/0x5C71bF122B5e1eEC7fb2cf029D6fAB7B224BD94F/info.json
  blockchains/ethereum/assets/0x5C71bF122B5e1eEC7fb2cf029D6fAB7B224BD94F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5078 Add Street Credit (CRED)
  blockchains/smartchain/assets/0x571D0B55fe30eb1F6E68e8799F181c46De6B0059/info.json
  blockchains/smartchain/assets/0x571D0B55fe30eb1F6E68e8799F181c46De6B0059/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5091 add BEP20 ETC
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x3d6545b08693daE087E957cb1180ee38B9e3c25E/info.json
  blockchains/smartchain/assets/0x3d6545b08693daE087E957cb1180ee38B9e3c25E/logo.png
Labels: Payment Status: Requested

#5092 Add TVK logo and info
  blockchains/ethereum/assets/0xd084B83C305daFD76AE3E1b4E1F1fe2eCcCb3988/info.json
  blockchains/ethereum/assets/0xd084B83C305daFD76AE3E1b4E1F1fe2eCcCb3988/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4993 Add Hub Token
  blockchains/ethereum/assets/0xba358B6f5b4c0215650444B8C30D870B55050D2D/info.json
  blockchains/ethereum/assets/0xba358B6f5b4c0215650444B8C30D870B55050D2D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5096 Add PiSwap Token (PIS) (erc20)
  blockchains/ethereum/assets/0xCE1298eF635326d9F197963E49E1E67422761897/info.json
  blockchains/ethereum/assets/0xCE1298eF635326d9F197963E49E1E67422761897/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5098 New rebranding - New Logo, Name, Description - Noia Network > Syntropy
  blockchains/ethereum/assets/0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca/info.json
  blockchains/ethereum/assets/0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca/logo.png
Labels: Payment Status: Requested, Status: More Info / Change Requested

#5077 Add DrugsV2
  blockchains/smartchain/assets/0x339550404Ca4d831D12B1b2e4768869997390010/info.json
  blockchains/smartchain/assets/0x339550404Ca4d831D12B1b2e4768869997390010/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5100 follow up of PR #4926
  blockchains/ethereum/assets/0x5D00d312e171Be5342067c09BaE883f9Bcb2003B/info.json
  blockchains/ethereum/assets/0x5D00d312e171Be5342067c09BaE883f9Bcb2003B/logo.png
Labels: Payment Status: Paid

#5082 Add rbase.finance logo
  blockchains/ethereum/assets/0xE8b251822d003a2b2466ee0E38391C2db2048739/info.json
  blockchains/ethereum/assets/0xE8b251822d003a2b2466ee0E38391C2db2048739/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5048 Add FNK token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xB5FE099475d3030DDe498c3BB6F3854F762A48Ad/info.json
  blockchains/ethereum/assets/0xB5FE099475d3030DDe498c3BB6F3854F762A48Ad/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4992 Added ART Token logo and description
  blockchains/ethereum/assets/0xE51f24B251430A6e615f66e0d3c3A97c442aB38C/info.json
  blockchains/ethereum/assets/0xE51f24B251430A6e615f66e0d3c3A97c442aB38C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5105 Update Base Protocol logo
  blockchains/ethereum/assets/0x07150e919B4De5fD6a63DE1F9384828396f25fDC/info.json
  blockchains/ethereum/assets/0x07150e919B4De5fD6a63DE1F9384828396f25fDC/logo.png
Labels: Payment Status: Paid

#5118 yvs.finance update
  blockchains/ethereum/assets/0xEC681F28f4561c2a9534799AA38E0d36A83Cf478/info.json
  blockchains/ethereum/assets/0xEC681F28f4561c2a9534799AA38E0d36A83Cf478/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4943 add narwhalswap protocol
  blockchains/smartchain/assets/0x4BbB275012EBE258556B8debE5C07bE98e8d3859/info.json
  blockchains/smartchain/assets/0x4BbB275012EBE258556B8debE5C07bE98e8d3859/logo.png
  blockchains/smartchain/assets/0x8f4087Cb09E0F378f4278a314C94A636665dE24b/info.json
  blockchains/smartchain/assets/0x8f4087Cb09E0F378f4278a314C94A636665dE24b/logo.png
  blockchains/smartchain/assets/0xA1303E6199b319a891b79685F0537D289af1FC83/info.json
  blockchains/smartchain/assets/0xA1303E6199b319a891b79685F0537D289af1FC83/logo.png
  dapps/info.narwhalswap.org.png
  dapps/narwhalswap.org.png
Labels: Payment Status: Paid

#5121 Add Graph Token (GRT)
  blockchains/ethereum/assets/0xc944E90C64B2c07662A292be6244BDf05Cda44a7/info.json
  blockchains/ethereum/assets/0xc944E90C64B2c07662A292be6244BDf05Cda44a7/logo.png
Labels: Payment Status: Requested

#5122 [Kin] Add SPL token info
  blockchains/solana/allowlist.json
  blockchains/solana/assets/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/info.json
  blockchains/solana/assets/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/logo.png
Labels: Payment Status: Requested

#5125 Add Cream crTokens
  blockchains/smartchain/assets/0x0E9d900C884964dC4B26db96Ba113825B1a09Baa/info.json
  blockchains/smartchain/assets/0x0E9d900C884964dC4B26db96Ba113825B1a09Baa/logo.png
  blockchains/smartchain/assets/0x11883Cdea6bAb720092791cc89affa54428Ce069/info.json
  blockchains/smartchain/assets/0x11883Cdea6bAb720092791cc89affa54428Ce069/logo.png
  blockchains/smartchain/assets/0x19eE64850862cFd234e20c0db4edA286f12ec907/info.json
  blockchains/smartchain/assets/0x19eE64850862cFd234e20c0db4edA286f12ec907/logo.png
  blockchains/smartchain/assets/0x1Ffe17B99b439bE0aFC831239dDECda2A790fF3A/info.json
  blockchains/smartchain/assets/0x1Ffe17B99b439bE0aFC831239dDECda2A790fF3A/logo.png
  blockchains/smartchain/assets/0x1aF8c1C3AD36A041cb6678feD86B1E095004fd16/info.json
  blockchains/smartchain/assets/0x1aF8c1C3AD36A041cb6678feD86B1E095004fd16/logo.png
  blockchains/smartchain/assets/0x264Bc4Ea2F45cF6331AD6C3aC8d7257Cf487FcbC/info.json
  blockchains/smartchain/assets/0x264Bc4Ea2F45cF6331AD6C3aC8d7257Cf487FcbC/logo.png
  blockchains/smartchain/assets/0x2Bc4eb013DDee29D37920938B96d353171289B7C/info.json
  blockchains/smartchain/assets/0x2Bc4eb013DDee29D37920938B96d353171289B7C/logo.png
  blockchains/smartchain/assets/0x2d3bfaDF9BC94E3Ab796029A030e863F1898aA06/info.json
  blockchains/smartchain/assets/0x2d3bfaDF9BC94E3Ab796029A030e863F1898aA06/logo.png
  blockchains/smartchain/assets/0x3942936782d788ce69155F776A51A5F1C9dd9B22/info.json
  blockchains/smartchain/assets/0x3942936782d788ce69155F776A51A5F1C9dd9B22/logo.png
  blockchains/smartchain/assets/0x3B0Be453a4008EBc2eDd457e7Bd355f1C5469d68/info.json
  blockchains/smartchain/assets/0x3B0Be453a4008EBc2eDd457e7Bd355f1C5469d68/logo.png
  blockchains/smartchain/assets/0x426D6D53187be3288fe37f214e3F6901D8145b62/info.json
  blockchains/smartchain/assets/0x426D6D53187be3288fe37f214e3F6901D8145b62/logo.png
  blockchains/smartchain/assets/0x53D88d2ffDBE71E81D95b08AE0cA49D0C4A8515f/info.json
  blockchains/smartchain/assets/0x53D88d2ffDBE71E81D95b08AE0cA49D0C4A8515f/logo.png
  blockchains/smartchain/assets/0x738f3810b3dA0F3e6dC8C689D0d72f3b4992c43b/info.json
  blockchains/smartchain/assets/0x738f3810b3dA0F3e6dC8C689D0d72f3b4992c43b/logo.png
  blockchains/smartchain/assets/0x81C15D3E956e55e77E1f3F257f0A65Bd2725fC55/info.json
  blockchains/smartchain/assets/0x81C15D3E956e55e77E1f3F257f0A65Bd2725fC55/logo.png
  blockchains/smartchain/assets/0x8cc7E2a6de999758499658bB702143FD025E09B2/info.json
  blockchains/smartchain/assets/0x8cc7E2a6de999758499658bB702143FD025E09B2/logo.png
  blockchains/smartchain/assets/0x9095e8d707E40982aFFce41C61c10895157A1B22/info.json
  blockchains/smartchain/assets/0x9095e8d707E40982aFFce41C61c10895157A1B22/logo.png
  blockchains/smartchain/assets/0xAa46e2c21B7763a73DB48e9b318899253E66e20C/info.json
  blockchains/smartchain/assets/0xAa46e2c21B7763a73DB48e9b318899253E66e20C/logo.png
  blockchains/smartchain/assets/0xCb87Cee8c77CdFD310fb3C58ff72e688d46f90b1/info.json
  blockchains/smartchain/assets/0xCb87Cee8c77CdFD310fb3C58ff72e688d46f90b1/logo.png
  blockchains/smartchain/assets/0xD83C88DB3A6cA4a32FFf1603b0f7DDce01F5f727/info.json
  blockchains/smartchain/assets/0xD83C88DB3A6cA4a32FFf1603b0f7DDce01F5f727/logo.png
  blockchains/smartchain/assets/0xE692714717a89E4F2ab89dd17d8DDdD7bb52De8e/info.json
  blockchains/smartchain/assets/0xE692714717a89E4F2ab89dd17d8DDdD7bb52De8e/logo.png
  blockchains/smartchain/assets/0xEA466cd2583A0290b9E7b987a769a7Eb468FB0A5/info.json
  blockchains/smartchain/assets/0xEA466cd2583A0290b9E7b987a769a7Eb468FB0A5/logo.png
  blockchains/smartchain/assets/0xEF6d459FE81C3Ed53d292c936b2df5a8084975De/info.json
  blockchains/smartchain/assets/0xEF6d459FE81C3Ed53d292c936b2df5a8084975De/logo.png
  blockchains/smartchain/assets/0xb31f5d117541825D6692c10e4357008EDF3E2BCD/info.json
  blockchains/smartchain/assets/0xb31f5d117541825D6692c10e4357008EDF3E2BCD/logo.png
Labels: Payment Status: Requested

#5120 Adds Thugs DApps
  dapps/streetswap.vip.png
  dapps/traphouse.vip.png
Labels: Payment Status: Paid

#5116 Add CRU
  blockchains/ethereum/assets/0x32a7C02e79c4ea1008dD6564b35F131428673c41/info.json
  blockchains/ethereum/assets/0x32a7C02e79c4ea1008dD6564b35F131428673c41/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4987 ChronoTech TIME token update
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x485d17A6f1B8780392d53D64751824253011A260/info.json
  blockchains/ethereum/assets/0x485d17A6f1B8780392d53D64751824253011A260/logo.png
  blockchains/ethereum/assets/0x6531f133e6DeeBe7F2dcE5A0441aA7ef330B4e53/info.json
Labels: Payment Status: Paid

#5128 [internal] USDC (ERC20) -> DAI (ERC20) wrong pair
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4834 DeFi For You - Add DFY token info and logo
  blockchains/smartchain/assets/0xD98560689C6e748DC37bc410B4d3096B1aA3D8C2/info.json
  blockchains/smartchain/assets/0xD98560689C6e748DC37bc410B4d3096B1aA3D8C2/logo.png
Labels: Payment Status: Paid

#5136 Add Alchemy (ACH) (erc20)
  blockchains/ethereum/assets/0xEd04915c23f00A313a544955524EB7DBD823143d/info.json
  blockchains/ethereum/assets/0xEd04915c23f00A313a544955524EB7DBD823143d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5117 add hland logo and info
  blockchains/ethereum/assets/0xba7b2C094C1A4757f9534a37d296a3BeD7f544DC/info.json
  blockchains/ethereum/assets/0xba7b2C094C1A4757f9534a37d296a3BeD7f544DC/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#5133 0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A
  blockchains/smartchain/assets/0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A/info.json
  blockchains/smartchain/assets/0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A/logo.png
Labels: Payment Status: Paid

#5146 Update new BHC contract address
  blockchains/smartchain/assets/0x6fd7c98458a943f469E1Cf4eA85B173f5Cd342F4/info.json
  blockchains/smartchain/assets/0x6fd7c98458a943f469E1Cf4eA85B173f5Cd342F4/logo.png
  blockchains/smartchain/assets/0xeDa21B525Ac789EaB1a08ef2404dd8505FfB973D/info.json
  blockchains/smartchain/assets/0xeDa21B525Ac789EaB1a08ef2404dd8505FfB973D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5149 [internal] Removed old contract of BHC token (see #5146)
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/info.json
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/logo.png
Labels: Payment Status: Requested

#5154 Adding asset for SYNC Network
  blockchains/ethereum/assets/0xB6ff96B8A8d214544Ca0dBc9B33f7AD6503eFD32/info.json
  blockchains/ethereum/assets/0xB6ff96B8A8d214544Ca0dBc9B33f7AD6503eFD32/logo.png
Labels: Payment Status: Requested

#5159 Add DLP Duck Token
  blockchains/ethereum/assets/0xC0bA369c8Db6eB3924965e5c4FD0b4C1B91e305F/info.json
  blockchains/ethereum/assets/0xC0bA369c8Db6eB3924965e5c4FD0b4C1B91e305F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5157 Add Logo DuckDaoDime
  blockchains/ethereum/assets/0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20/info.json
  blockchains/ethereum/assets/0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5155 Add ELG logo and info
  blockchains/ethereum/assets/0xA2085073878152aC3090eA13D1e41bD69e60Dc99/info.json
  blockchains/ethereum/assets/0xA2085073878152aC3090eA13D1e41bD69e60Dc99/logo.png
Labels: Payment Status: Requested

#5143 DeFi For You - Update BEP2 logo
  blockchains/binance/allowlist.json
  blockchains/binance/assets/DFY-EA0/info.json
  blockchains/binance/assets/DFY-EA0/logo.png
  blockchains/smartchain/denylist.json
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5172 Add logo for MahaDAO (MAHA)
  blockchains/ethereum/assets/0xB4d930279552397bbA2ee473229f89Ec245bc365/info.json
  blockchains/ethereum/assets/0xB4d930279552397bbA2ee473229f89Ec245bc365/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5168 Add LON token logo
  blockchains/ethereum/assets/0x0000000000095413afC295d19EDeb1Ad7B71c952/info.json
  blockchains/ethereum/assets/0x0000000000095413afC295d19EDeb1Ad7B71c952/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5178 [internal] WAVES tokens
  blockchains/waves/assets/4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8/logo.png
  blockchains/waves/assets/6nSpVyNH7yM69eg446wrQR94ipbbcmZMU1ENPwanC97g/logo.png
  blockchains/waves/assets/8inca5fv4xr6KZtRMRPYr7vADfk8fd6G2z1gMoRkbUYS/logo.png
  blockchains/waves/assets/9sQutD5HnRvjM1uui5cVC4w9xkMPAfYEV8ymug3Mon2Y/logo.png
  blockchains/waves/assets/DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p/logo.png
  blockchains/waves/assets/DGbqkzM6Ds5NAF2B3GHYfyZRmWKt7xLYRYcwpMm7D6V4/logo.png
  blockchains/waves/assets/DHgwrRvVyqJsepd32YbBqUeDH4GJ1N984X8QoekjgH8J/logo.png
  blockchains/waves/assets/DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t/logo.png
  blockchains/waves/assets/DhaaqiG8xz8njeBuMtTM2G6avg9Jdhfrxw5onm5GaXx1/logo.png
  blockchains/waves/assets/DxFwXxS1r3uZ2QEiSqhe6uoXMJBsz4ShLtHvr4HDzNri/logo.png
  blockchains/waves/assets/bPWkA3MNyEr1TuDchWgdpqJZhGhfPXj7dJdr3qiW2kD/logo.png
  blockchains/waves/assets/eWeMD5KNeuRaALCAb4uuJKtAvon2JcTyXQyoBMhuN2X/logo.png
Labels: Payment Status: Requested

#5185 Add 1Inch token
  blockchains/ethereum/assets/0x111111111117dC0aa78b770fA6A738034120C302/info.json
  blockchains/ethereum/assets/0x111111111117dC0aa78b770fA6A738034120C302/logo.png
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#5183 Add luna
  blockchains/ethereum/assets/0xd2877702675e6cEb975b4A1dFf9fb7BAF4C91ea9/info.json
  blockchains/ethereum/assets/0xd2877702675e6cEb975b4A1dFf9fb7BAF4C91ea9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5175 Add DefHold logo
  blockchains/ethereum/assets/0xe481f2311C774564D517d015e678c2736A25Ddd3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5181 Add logo for WSTA
  blockchains/ethereum/assets/0x59F96b8571E3B11f859A09Eaf5a790A138FC64D0/logo.png
  blockchains/ethereum/assets/0xeDEec5691f23E4914cF0183A4196bBEb30d027a0/info.json
  blockchains/ethereum/assets/0xeDEec5691f23E4914cF0183A4196bBEb30d027a0/logo.png
Labels: Payment Status: Paid

#5167 add logo for DEUS Synthetic Coinbase IOU Token (wCOINBASE-IOU)
  blockchains/ethereum/assets/0x4185cf99745B2a20727B37EE798193DD4a56cDfa/info.json
  blockchains/ethereum/assets/0x4185cf99745B2a20727B37EE798193DD4a56cDfa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5187 add_kp3rb
  blockchains/smartchain/assets/0x5EA29eEe799aA7cC379FdE5cf370BC24f2Ea7c81/info.json
  blockchains/smartchain/assets/0x5EA29eEe799aA7cC379FdE5cf370BC24f2Ea7c81/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5148 Add YLD logo
  blockchains/ethereum/assets/0xDcB01cc464238396E213a6fDd933E36796eAfF9f/info.json
  blockchains/ethereum/assets/0xDcB01cc464238396E213a6fDd933E36796eAfF9f/logo.png
Labels: Payment Status: Paid

#5196 Added cezo logo and info
  blockchains/ethereum/assets/0xFEbc25f4c5fc3E90a7eFaE0b4d436A77c9e131B3/info.json
  blockchains/ethereum/assets/0xFEbc25f4c5fc3E90a7eFaE0b4d436A77c9e131B3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5182 Add logo for DITTO token
  blockchains/smartchain/assets/0x233d91A0713155003fc4DcE0AFa871b508B3B715/info.json
  blockchains/smartchain/assets/0x233d91A0713155003fc4DcE0AFa871b508B3B715/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5150 Add EPAN logo and info
  blockchains/ethereum/assets/0x72630B1e3B42874bf335020Ba0249e3E9e47Bafc/info.json
  blockchains/ethereum/assets/0x72630B1e3B42874bf335020Ba0249e3E9e47Bafc/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5199 Add files via upload
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#5194 Replace Logo
  blockchains/ethereum/assets/0x83e6f1E41cdd28eAcEB20Cb649155049Fac3D5Aa/info.json
  blockchains/ethereum/assets/0x83e6f1E41cdd28eAcEB20Cb649155049Fac3D5Aa/logo.png
Labels: Payment Status: Paid

#5153 Add SparkPoint Fuel logo and info
  blockchains/smartchain/assets/0x37Ac4D6140e54304D77437A5c11924f61a2D976f/info.json
  blockchains/smartchain/assets/0x37Ac4D6140e54304D77437A5c11924f61a2D976f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5207 add BEP20 REEF
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xF21768cCBC73Ea5B6fd3C687208a7c2def2d966e/info.json
  blockchains/smartchain/assets/0xF21768cCBC73Ea5B6fd3C687208a7c2def2d966e/logo.png
Labels: Payment Status: Requested

#5211 add ERC20 REEF
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xFE3E6a25e6b192A42a44ecDDCd13796471735ACf/info.json
  blockchains/ethereum/assets/0xFE3E6a25e6b192A42a44ecDDCd13796471735ACf/logo.png
Labels: Payment Status: Requested

#5202 Add bALBT token to BSC
  blockchains/smartchain/assets/0x72fAa679E1008Ad8382959FF48E392042A8b06f7/info.json
  blockchains/smartchain/assets/0x72fAa679E1008Ad8382959FF48E392042A8b06f7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5193 Add bDollar (bep20)
  blockchains/smartchain/assets/0x190b589cf9Fb8DDEabBFeae36a813FFb2A702454/info.json
  blockchains/smartchain/assets/0x190b589cf9Fb8DDEabBFeae36a813FFb2A702454/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5195 Dynamic Set Token.
  blockchains/ethereum/assets/0xBD2F0Cd039E0BFcf88901C98c0bFAc5ab27566e3/info.json
  blockchains/ethereum/assets/0xBD2F0Cd039E0BFcf88901C98c0bFAc5ab27566e3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Correction needed

#5107 Added logo for BOND token(0x5Dc02Ea99285E17656b8350722694c35154DB1E8)
  blockchains/ethereum/assets/0x5Dc02Ea99285E17656b8350722694c35154DB1E8/info.json
  blockchains/ethereum/assets/0x5Dc02Ea99285E17656b8350722694c35154DB1E8/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5227 Julswap Token
  blockchains/smartchain/assets/0x5A41F637C3f7553dBa6dDC2D3cA92641096577ea/info.json
  blockchains/smartchain/assets/0x5A41F637C3f7553dBa6dDC2D3cA92641096577ea/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
