Repository trustwallet/assets, pull requests merged in 2020-05, with the labels that each got.

#2014 nuu token logo update
  blockchains/ethereum/assets/0xcD2d415835D4746f5498950F3Fc48e01e64F89f9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2023 Add CACHE Gold info
  blockchains/ethereum/assets/0xF5238462E7235c7B62811567E63Dd17d12C2EAA0/info.json
  blockchains/ethereum/assets/0xF5238462E7235c7B62811567E63Dd17d12C2EAA0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2025 Update CACHE icon
  blockchains/ethereum/assets/0xF5238462E7235c7B62811567E63Dd17d12C2EAA0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2029 GBPT added
  blockchains/ethereum/assets/0xCC9254107D18493D018EE87C843a1D6d0c483c3C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#2026 Add Balancer Logo
  dapps/balancer.exchange.png
Labels: Payment Status: Requested

#2033 Upload Euros
  blockchains/ethereum/assets/0x36E85A6403ffF21669980b436792129C96e7002e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2036 Merge-bot config: Extend message when paid; set amount tolerance to 98%.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#2038 Merge bot config: Yaml format fix.
  .github/merge-fee-bot.yaml
Labels: FeePayment: Requested

#2039 Add Tezos baker min delegation amount property
  .github/workflows/update_validators_info.yml
  blockchains/tezos/validators/list.json
  script/gen_validators_tezos.ts
Labels: Payment Status: Requested

#2027 Synth Updates
  blockchains/ethereum/assets/0x57ab1ec28d129707052df4df418d58a2d46d5f51/logo.png
  blockchains/ethereum/assets/0x5e74c9036fb86bd7ecdcb084a0673efc32ea31cb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2051 Add NNX
  blockchains/ethereum/assets/0x68f54CeF8DB7Ca1d3aC1bdd4cB56bC7A6Ec26Faa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2050 blacklist_WON
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2045 Add BPT logo
  blockchains/ethereum/assets/0x283669123bd83dA2536bB534e20512101c18E5D8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2056 Add ShahinMedical
  blockchains/ethereum/assets/0x138537DDba70aB69C05497b89Ee2e34F9201DCec/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2055 Add STAKE
  blockchains/ethereum/assets/0x0Ae055097C6d159879521C384F1D2123D1f195e6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2046 Add mtb20 logo
  blockchains/ethereum/assets/0x6a2f414e1298264ecd446d6bb9da012760336a4f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2044 new assets images for renBTC, renZEC, and renBCH
  blockchains/ethereum/assets/0x1C5db575E2Ff833E46a2E9864C22F4B22E0B37C2/logo.png
  blockchains/ethereum/assets/0x459086F2376525BdCebA5bDDA135e4E9d3FeF5bf/logo.png
  blockchains/ethereum/assets/0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2057 Upload BOF logo
  blockchains/ethereum/assets/0x5c4E325d2c570443f4ea3Ed5623c58dE221E9475/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2059 Add DXD
  blockchains/ethereum/assets/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521/info.json
  blockchains/ethereum/assets/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2063 Please add BNC on TrustWallet
  blockchains/ethereum/assets/0x0B0a57287BC86eb066f677825BBa5da69Df446d2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2062 Two stablecoins EUR36 and CHF36
  blockchains/ethereum/assets/0x0CDE550b066Ff98dA123377eeB0A149607C9ca17/info.json
  blockchains/ethereum/assets/0x0CDE550b066Ff98dA123377eeB0A149607C9ca17/logo.png
  blockchains/ethereum/assets/0xf67c3000943c74186B64A1Bc84Cb5880E5198661/info.json
  blockchains/ethereum/assets/0xf67c3000943c74186B64A1Bc84Cb5880E5198661/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2061 feat(): add ZYJ token info
  blockchains/ethereum/assets/0xBC6150a1197842E4E1Ecb21dEf1f4F53Da609BBb/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2068 Upload TopToken Logo
  blockchains/ethereum/assets/0x6Ccb2AdECc8cE829F768465280586F0E04a6959c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2073 Update mtl logo
  blockchains/ethereum/assets/0xF433089366899D83a9f26A773D59ec7eCF30355e/logo.png
Labels: Payment Status: Requested

#2074 Add files via upload
  blockchains/ethereum/assets/0x6Ccb2AdECc8cE829F768465280586F0E04a6959c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2066 Add JREX logo
  blockchains/ethereum/assets/0x638155F4BD8F85d401Da32498D8866eE39A150B8/info.json
  blockchains/ethereum/assets/0x638155F4BD8F85d401Da32498D8866eE39A150B8/logo.png
  blockchains/jrex/info/info.json
  blockchains/jrex/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2069 Add VINX
  blockchains/ethereum/assets/0x010c282118aA76174CE5952572BA715CF60A0c9B/info.json
  blockchains/ethereum/assets/0x010c282118aA76174CE5952572BA715CF60A0c9B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2086 Upload XEMX Logo
  blockchains/ethereum/assets/0x59321ace77C8087FF8Cb9F94C8384807E4Fd8a3c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2087 CUBE token logo update
  blockchains/ethereum/assets/0x5b0CFFdB6E04992eBFe4748F6fD8FA868f216Fdb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2097 Add Logo BTCE
  blockchains/ethereum/assets/0xbfd4fdc84e1cc26db7ec504caa32d78ae67612a7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2079 Add Logo BATM Version 1
  blockchains/ethereum/assets/0x05b8cb3F1f1F46cEAE3187c56AF5B223CF2D831A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2081 Modify VINX icon
  blockchains/ethereum/assets/0x010c282118aA76174CE5952572BA715CF60A0c9B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2093 Add RADAR RELAY Logo
  dapps/relay.radar.tech.png
Labels: Payment Status: Paid, Payment Status: Requested

#2088 Added logo for BEN coin
  blockchains/ethereum/assets/0x4d21563feB6c880AbC2A6a74B090D1a7cbF06Ca8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2089 Add ELD token logo
  blockchains/ethereum/assets/0xf0C6521b1F8ad9C33a99Aaf056F6C6247A3862BA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2101 Added validator logos for harmony
  blockchains/harmony/validators/assets/one170xqsfzm4xdmuyax54t5pvtp5l5yt66u50ctrp/logo.png
  blockchains/harmony/validators/assets/one1gm8xwupd9e77ja46eaxv8tk4ea7re5zknaauvq/logo.png
  blockchains/harmony/validators/assets/one1j9gr0maryak7mmgkgw67gsgz3wxhmnv6cpvnqy/logo.png
  blockchains/harmony/validators/assets/one1pul5cd3hewakyfcewdn2m2xhuk7w0ese9u733s/logo.png
  blockchains/harmony/validators/assets/one1ryuvxq3mgcvj0a2ukpa5dkuxmlc2gdf7pcc775/logo.png
  blockchains/harmony/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2100 Added logo for YAS Coin
  blockchains/ethereum/assets/0x89B6A8Ca0001948d33F5807Bc3aB65D541641e27/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2113 UPload BEX logo
  blockchains/ethereum/assets/0x81DDbc1394c02D15946D76C16485b829Aa5CCc43/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2112 Please update these logos
  blockchains/ethereum/assets/0x07BA7D3bF57ac6FbAA817Ab698C710c8Bf5A6F08/logo.png
  blockchains/ethereum/assets/0x1626e3d05De1428FD209BBfb911d78E0E06a73F2/logo.png
  blockchains/ethereum/assets/0x164AdC5E46324A9D5fC520f0f753B62Dd01Dc556/logo.png
  blockchains/ethereum/assets/0x657f624dd8Eef219E020C456A991A68f3e205a3D/logo.png
  blockchains/ethereum/assets/0x93453fbCf7fD8CcF9F3740af2fb9D14960a23b39/logo.png
  blockchains/ethereum/assets/0xabF56cCe897D89e96502970053E52321F03d9c71/logo.png
  blockchains/ethereum/assets/0xacF79E1bEb54703bcf14B4C7012dDD4e6b360905/logo.png
  blockchains/ethereum/assets/0xf729dE55b9Ca9412F5DD12935AfF0201fdB1Ea8F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2109 Added more harmony validators
  blockchains/harmony/validators/assets/one108uwrdejhf3es7rn6h4cdjqnvnpv75pp7t5ne9/logo.png
  blockchains/harmony/validators/assets/one129gp9e7ghsyecxevp4che033dmk0sew7swvk66/logo.png
  blockchains/harmony/validators/assets/one14wyp73qmn3zch98dqnjvu4rprcz79tlrxq3al6/logo.png
  blockchains/harmony/validators/assets/one16yvnyrac2nfaapm8tyraesa7khtg3d9tr786pv/logo.png
  blockchains/harmony/validators/assets/one18hum2avunkz3u448lftwmk7wr88qswdlfvvrdm/logo.png
  blockchains/harmony/validators/assets/one18je40sxd9s6awtgx4akhuda8d75km3663eep37/logo.png
  blockchains/harmony/validators/assets/one1920ku8c9uerwyavk9hnxgpdshak7w7dn9gm632/logo.png
  blockchains/harmony/validators/assets/one1a0au0p33zrns49h3qw7prn02s4wphu0ggcqrhm/logo.png
  blockchains/harmony/validators/assets/one1aha9g2d6scsyktjgx7wm9jwssxjp6lrtl8959z/logo.png
  blockchains/harmony/validators/assets/one1d2zjm9czlfzdes97pfuzdydflw0t80kspwst0x/logo.png
  blockchains/harmony/validators/assets/one1dcmp24uqgwszcvmm8n6r5dvhqhuukdj86pkg6n/logo.png
  blockchains/harmony/validators/assets/one1efat5elqnvttf7gm86q9kmt48z69njax464rhv/logo.png
  blockchains/harmony/validators/assets/one1f5yhhwn42qnxkj2n6xucrl5plqgy03082xuw25/logo.png
  blockchains/harmony/validators/assets/one1fllqjv6hq8vfvz5kwyhaknw0f2emvfqmq0s2tu/logo.png
  blockchains/harmony/validators/assets/one1kf42rl6yg2avkjsu34ch2jn8yjs64ycn4n9wdj/logo.png
  blockchains/harmony/validators/assets/one1ldthk5zyrea6w60rptcfyzlftd8fsn9fhkeps7/logo.png
  blockchains/harmony/validators/assets/one1leh5rmuclw5u68gw07d86kqxjd69zuny3h23c3/logo.png
  blockchains/harmony/validators/assets/one1lpgxyxvgxnprgflx4myzh5m9se83u0racw22du/logo.png
  blockchains/harmony/validators/assets/one1nef0c8kgy30delcckf87jaegdp7s7ntrknvajj/logo.png
  blockchains/harmony/validators/assets/one1qk7mp94ydftmq4ag8xn6y80876vc28q7s9kpp7/logo.png
  blockchains/harmony/validators/assets/one1r55rwumsrm6w3d20uhaa3hm4rxr442k0qx9gj8/logo.png
  blockchains/harmony/validators/assets/one1sqy7dgkrrmc4tacrzyts37vf8gvmtesqstg8ff/logo.png
  blockchains/harmony/validators/assets/one1xv62dz2gmshaqac4gn87qkh44g80mcpquvn2tk/logo.png
  blockchains/harmony/validators/assets/one1zdxjy50aa9kk33pxrjy8yerpgz49hx0nhc2r6k/logo.png
  blockchains/harmony/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2111 Update wonder logo and description
  blockchains/ethereum/assets/0x69DC5556A91DFab39f8D50f6FE552296F2268Dda/info.json
  blockchains/ethereum/assets/0x69DC5556A91DFab39f8D50f6FE552296F2268Dda/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2098 COPA Coin
  blockchains/ethereum/assets/0x5ec41a158e09de1dba6410aebe72f504f2428052/logo.png
  blockchains/ethereum/assets/0xae3274d06b7de181c4a6fbbb5f8bb945a15b5094/logo.png
Labels: Payment Status: Requested

#2116 MX3 Token logo update
  blockchains/ethereum/assets/0x291fa2725d153bcc6c7e1c304bcad47fdef1ef84/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2117 blacklist_fake_JUV
  blockchains/ethereum/blacklist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2126 Add TAPE
  blockchains/ethereum/assets/0x9Bfb088C9f311415E3F9B507DA73081c52a49d8c/logo.png
Labels: Payment Status: Requested

#2131 Add DAWN Token
  blockchains/ethereum/assets/0x580c8520dEDA0a441522AEAe0f9F7A5f29629aFa/info.json
  blockchains/ethereum/assets/0x580c8520dEDA0a441522AEAe0f9F7A5f29629aFa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2132 Please add YCN on TrustWallet
  blockchains/ethereum/assets/0xD9D2C606EC5F7a01dF496768cfC9E5003B23d193/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2134 Add Robonomics (XRT)
  blockchains/ethereum/assets/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7/info.json
  blockchains/ethereum/assets/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2139 Add proofofbake baking service
  blockchains/tezos/validators/assets/tz3QCNyySViKHmeSr45kzDxzchys7NiXCWoa/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2143 Update cmc generation script
  .github/workflows/daily_update.yml
  package.json
  pricing/coinmarketcap/mapping.json
  pricing/coinmarketcap/script.ts
  src/test/index.test.ts
Labels: Payment Status: Requested

#2146 add_JST
  blockchains/tron/assets/TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9/logo.png
  blockchains/tron/assets/TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT/logo.png
  blockchains/tron/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2144 Add COTR token logo
  blockchains/ethereum/assets/0x40428fdd5588197c15dd00b22fe9b9a48afeeb23/info.json
  blockchains/ethereum/assets/0x40428fdd5588197c15dd00b22fe9b9a48afeeb23/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2137 Updating OWL logo
  blockchains/ethereum/assets/0x1A5F9352Af8aF974bFC03399e3767DF6370d82e4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2141 Update AFDLT info
  blockchains/ethereum/assets/0x08130635368AA28b217a4dfb68E1bF8dC525621C/logo.png
  blockchains/ethereum/assets/0xD8a8843b0a5aba6B030E92B3F4d669FaD8A5BE50/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2138 Updating GNO logo
  blockchains/ethereum/assets/0x6810e776880C02933D47DB1b9fc05908e5386b96/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2154 Upload Soon Token
  blockchains/ethereum/assets/0xc074Dd87663b97097f06d805A164b6B271158738/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2142 Add files PLM
  blockchains/ethereum/assets/0x80d211718f9B9Ba31959a14328Acd8D8c9d5382f/info.json
  blockchains/ethereum/assets/0x80d211718f9B9Ba31959a14328Acd8D8c9d5382f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2156 Upload Glory Token
  blockchains/ethereum/assets/0xCcc9545ea5838f7d6d34DcDa1Bc39d2D077F7Cde/logo.png
Labels: Payment Status: Requested

#2166 Please add these Tokens on Trust Wallet
  blockchains/ethereum/assets/0x2C4d804E27Da8071e4f54A2323d9c6Fc14d7CC46/logo.png
  blockchains/ethereum/assets/0x7A69F675eA3886892a3bd15C1DD2A5a579b7f7dc/logo.png
  blockchains/ethereum/assets/0xE3d208D74e4C167245913C942df8C4Ee03b9abBA/logo.png
  blockchains/ethereum/assets/0xa69431858DB49BDa621192c29F366BE4d386CCAf/logo.png
  blockchains/ethereum/assets/0xe3152D33c08807Ba9C301c5110e78B9203137C0c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2169 Adding logo
  blockchains/ethereum/assets/0xfa91f4177476633f100c59d336c0f2ffad414cba/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2158 EURO logo has been added.
  blockchains/ethereum/assets/0x46C440EA7C7d06559d46640112FC78F7Ab5a0262/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2155 Create logo.png
  blockchains/ethereum/assets/0xC88C59d0C573043C477fB9084990Ea14bc3C3817/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2176 Submit Libfx token logo
  blockchains/ethereum/assets/0xA66a5F51667da71179C23Db79a58C16193dD84a1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2177 please update logo file
  blockchains/ethereum/assets/0x8B554bF7304065e60F89915a4eb1aBa7E7EB301c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2183 Add TelFx logo and information
  blockchains/ethereum/assets/0xd2567afbA8704547466d32336A23777232AE18cA/info.json
  blockchains/ethereum/assets/0xd2567afbA8704547466d32336A23777232AE18cA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2185 Added BUIDL Logo 0xD6F0Bb2A45110f819e908a915237D652Ac7c5AA8
  blockchains/ethereum/assets/0xD6F0Bb2A45110f819e908a915237D652Ac7c5AA8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2187 Add ZNT
  blockchains/ethereum/0x138fd9A2B4b283676109d5E76cf3b83de7d15F25.png
Labels: Payment Status: Paid, Payment Status: Requested

#2192 New Evestake baker added, old -> renamed Everstake Legacy
  blockchains/tezos/validators/assets/tz1aRoaRhSpRYvFdyvgWLL6TGyRoGF51wDjM/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#2196 Add COL (ThePay.Cash)
  blockchains/ethereum/assets/0xC76FB75950536d98FA62ea968E1D6B45ffea2A55/info.json
  blockchains/ethereum/assets/0xC76FB75950536d98FA62ea968E1D6B45ffea2A55/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2191 Robonomics XRT: update logo
  blockchains/ethereum/assets/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2190 Add Learno (LRT) token LOGO TO trust wallet
  blockchains/ethereum/assets/0x7194BB18C95c638F9b9604C2f20064B66A0de8fE.png
Labels: Payment Status: Paid, Payment Status: Requested

#2189 Add AUDION GAMING TOKEN (AGT) Logo to Trust Wallet
  blockchains/ethereum/assets/0x352cfed33922fa8d34fcb8eb58525a60ca6821fc.png
Labels: Payment Status: Paid, Payment Status: Requested

#2180 Add social money logos (Part-5)
  blockchains/ethereum/assets/0x17491ae8B359E73ca06F0ABb52223daA878140a9/logo.png
  blockchains/ethereum/assets/0x1e906717De2E4A4600F13b6909736b0346bDde3E/logo.png
  blockchains/ethereum/assets/0x3A3A1B3A584C7bC41B561d958e092ae291bD7F93/logo.png
  blockchains/ethereum/assets/0x3A75731f9e16244dE01DD431636Db7c07D42A166/logo.png
  blockchains/ethereum/assets/0x72b984078E270CfDdcb9E04643A18605507d1d77/logo.png
  blockchains/ethereum/assets/0x7841B2A48D1F6e78ACeC359FEd6D874Eb8a0f63c/logo.png
  blockchains/ethereum/assets/0x7C918dF91f8F4e8D707a7A4013b8e7247C0293B1/logo.png
  blockchains/ethereum/assets/0x81B1bFD6CB9Ad42DB395c2a27F73D4DCf5777e2D/logo.png
  blockchains/ethereum/assets/0x9355372396e3F6daF13359B7b607a3374cc638e0/logo.png
  blockchains/ethereum/assets/0x9a05f21d2F89837Ebd94E92084fd0Edb407f67C4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2201 Added BTCE Token Logo
  blockchains/ethereum/assets/0x877391140c33B93a913478a6A1DF5157edC08320/info.json
  blockchains/ethereum/assets/0x877391140c33B93a913478a6A1DF5157edC08320/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2198 add STATERA PROJECT
  blockchains/ethereum/assets/0xe343245DE92181bc06ba5Cd1152C705A2C5F3E2F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2199 Add Tez Baker to the Tezos validators
  blockchains/tezos/validators/assets/tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#2203 Update blacklist.json
  blockchains/tron/blacklist.json
Labels: Payment Status: Requested

#2202 Robonomics XRT: update logo
  blockchains/ethereum/assets/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7/logo.png
Labels: Payment Status: Requested

#2208 Finetune merge fee bot messages.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid, Payment Status: Requested

#2211 STATERA V3
  blockchains/ethereum/assets/0xa7de087329bfcda5639247f96140f9dabe3deed1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2212 add bexpress token logo
  blockchains/ethereum/assets/0xc002141f62961afa759f7b22aaeb151bf80a3d8d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2210 Insula Token
  blockchains/ethereum/assets/0x697eF32B4a3F5a4C39dE1cB7563f24CA7BfC5947/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2215 Add GHOST BY McAfee
  blockchains/ethereum/assets/0x4c327471C44B2dacD6E90525f9D629bd2e4f662C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2213 Please delete logo for this contract.
  blockchains/ethereum/assets/0xe343245DE92181bc06ba5Cd1152C705A2C5F3E2F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2217 blacklist_IOST
  blockchains/ethereum/assets/0xFA1a856Cfa3409CFa145Fa4e20Eb270dF3EB21ab/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2218 Add Logo Token - Unifier (Trust Wallet)
  blockchains/ethereum/assets/0xEC02cEc4eDD54196D2767b61F43b29A49b056fe6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2219 Add TTRP
  blockchains/tron/assets/1002963/logo.png
  src/test/index.test.ts
Labels: Payment Status: Paid, Payment Status: Requested
