Repository trustwallet/assets, pull requests merged in 2020-07, with the labels that each got.

#2532 Please add MARE on TrustWallet
  blockchains/ethereum/assets/0x98eb850a587D908980328ED3Fde3e335C0cc4426/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2534 Add FOX Token
  blockchains/ethereum/assets/0xc770EEfAd204B5180dF6a14Ee197D99d808ee52d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2535 Add logo ACID token
  blockchains/ethereum/assets/0xc68B73D9509F5343602480656F5dA512a5A20b9e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2538 Flama SmartContract Update
  blockchains/ethereum/assets/0x0f8794f66C7170c4f9163a8498371A747114f6C4/info.json
  blockchains/ethereum/assets/0x0f8794f66C7170c4f9163a8498371A747114f6C4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2533 Add XAVIA token logo
  blockchains/ethereum/assets/0x91Ee7472540CeF675EbC11e3fac69dE24C38495E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2539 Add MRDN
  blockchains/ethereum/assets/0x896a07e3788983ec52eaf0F9C6F6E031464Ee2CC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2540 Add KASH
  blockchains/ethereum/assets/0x2c50ba1ED5e4574C1b613b044Bd1876f0B0B87a9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2529 CTC old contract
  blockchains/ethereum/blacklist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2531 Add correct giv logo
  blockchains/binance/assets/GIV-94E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, wontfix

#2542 AST logo
  blockchains/ethereum/assets/0xa872E0a44BBd66c1486a756CB5BD3F0bEEC4e32e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2526 Add Reserve (RSV) logo
  blockchains/ethereum/assets/0x1C5857e110CD8411054660F60B5De6a6958CfAE2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2562 Add FLUX logo
  blockchains/ethereum/assets/0x469eDA64aEd3A3Ad6f868c44564291aA415cB1d9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2566 Add files via upload
  blockchains/ethereum/assets/0x0Bb7Db697567178c590eFA64A7DcB2ce6213768C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2561 Fiat Token
  blockchains/ethereum/assets/0x30e8da02f92252E2b9A40AF2973fEa18eCA4df87/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2567 resubmit_pr2502
  blockchains/ethereum/assets/0xa9f2C8EF5Eeb27dC7819cD1712f02e816dB02056/logo.png
Labels: Payment Status: Requested

#2568 Add Benscoin Logo
  blockchains/ethereum/assets/0xcfAD57a67689809CdA997f655802a119838c9ceC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2571 Update ethereum blacklist, whitelist, assets
  blockchains/ethereum/assets/0xC011A72400E58ecD99Ee497CF89E3775d4bd732F/info.json
  blockchains/ethereum/assets/0xC011A72400E58ecD99Ee497CF89E3775d4bd732F/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#2572 Update eth whitelist, blacklist, assets
  blockchains/ethereum/assets/0xC011A72400E58ecD99Ee497CF89E3775d4bd732F/info.json
  blockchains/ethereum/assets/0xC011A72400E58ecD99Ee497CF89E3775d4bd732F/logo.png
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Requested

#2573 Movement DAO - Asset Upload 2020
  blockchains/ethereum/assets/0x3D46454212c61ECb7b31248047Fa033120B88668/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2576 Add AceD Token
  blockchains/ethereum/assets/0x4B3a0c6d668B43F3f07904E124328659b90Bb4Ca/info.json
  blockchains/ethereum/assets/0x4B3a0c6d668B43F3f07904E124328659b90Bb4Ca/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2580 Add Askobar Network (ASKO) ethereum ERC20 asset
  blockchains/ethereum/assets/0xeEEE2a622330E6d2036691e983DEe87330588603/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2579 Upload BIGTIGER token
  blockchains/ethereum/assets/0xAa5d424c64De2b60800786d7Eaa7c7FEF42aB2f6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2577 Add files via upload
  blockchains/ethereum/assets/0x178c820f862B14f316509ec36b13123DA19A6054/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2582 Run daily update
  blockchains/cosmos/validators/list.json
  blockchains/ethereum/assets/0x048930eec73c91B44b0844aEACdEBADC2F2b6efb/info.json
  blockchains/ethereum/assets/0x08AD83D779BDf2BBE1ad9cc0f78aa0D24AB97802/info.json
  blockchains/ethereum/assets/0x1D0e53A0e524E3CC92C1f0f33Ae268FfF8D7E7a5/info.json
  blockchains/ethereum/assets/0x21839a7f7e88c19a6089AdBFB3fB52606Ac6f0Dd/info.json
  blockchains/ethereum/assets/0x2C66164F7a8564dCAAadcA8319b9f917ac418E4e/info.json
  blockchains/ethereum/assets/0x3a3A65aAb0dd2A17E3F1947bA16138cd37d08c04/info.json
  blockchains/ethereum/assets/0x4Ba012f6e411a1bE55b98E9E62C3A4ceb16eC88B/info.json
  blockchains/ethereum/assets/0x5b5bB9765eff8D26c24B9FF0DAa09838a3Cd78E9/info.json
  blockchains/ethereum/assets/0x6179078872605396Ee62960917128F9477a5DdbB/info.json
  blockchains/ethereum/assets/0x63f88A2298a5c4AEE3c216Aa6D926B184a4b2437/info.json
  blockchains/ethereum/assets/0x72f5eA105faC794fb3CF0Af0f5e65DF8dDd3519B/info.json
  blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/info.json
  blockchains/ethereum/assets/0x84BBcaB430717ff832c3904fa6515f97fc63C76F/info.json
  blockchains/ethereum/assets/0x8c69f7A4C9B38F1b48005D216c398Efb2F1Ce3e4/info.json
  blockchains/ethereum/assets/0x9548DB8b1cA9b6c757485e7861918b640390169c/info.json
  blockchains/ethereum/assets/0xAcfa209Fb73bF3Dd5bBfb1101B9Bc999C49062a5/info.json
  blockchains/ethereum/assets/0xBbBb7F2aC04484F7F04A2C2C16f20479791BbB44/info.json
  blockchains/ethereum/assets/0xF989E16233ad1aD0F2aF739547eF92745341F52B/info.json
  blockchains/ethereum/assets/0xb977ee318010A5252774171494a1bCB98E7fab65/info.json
  blockchains/ethereum/assets/0xc88ebbf7C523f38Ef3eB8A151273C0F0dA421e63/info.json
  blockchains/ethereum/assets/0xe02b2Ad63eFF3Ac1D5827cBd7AB9DD3DaC4f4AD0/info.json
  blockchains/ethereum/blacklist.json
  blockchains/ethereum/whitelist.json
  blockchains/kava/validators/list.json
  blockchains/tron/whitelist.json
  pricing/coinmarketcap/mapping.json
Labels: Payment Status: Requested

#2586 Update .gitignore
  .gitignore
Labels: Payment Status: Requested

#2587 Update .gitignore
  .gitignore
Labels: Payment Status: Requested

#2578 Entone Logo
  blockchains/ethereum/assets/0xEc1a718D1A6F8F8d94eCEc6fe91465697bb2b88C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2583 Add BNB
  blockchains/ethereum/assets/0x9B3a0aB8a2A1cfED0e1edEc1745077B7C3838AE4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2591 delete_VSF_old
  blockchains/ethereum/assets/0xBA3a79D758f19eFe588247388754b8e4d6EddA81/logo.png
Labels: Payment Status: Requested

#2594 Add files via upload
  blockchains/ethereum/assets/0x1b76d0364e803fB94c1d5cA9Faf55f05Ee494731/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2593 Adding Cap.finance (CAP) logo
  blockchains/ethereum/assets/0x43044f861ec040DB59A7e324c40507adDb673142/info.json
  blockchains/ethereum/assets/0x43044f861ec040DB59A7e324c40507adDb673142/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2595 Update Logo Benscoin
  blockchains/ethereum/assets/0xAb418c5A8a85f9cC0fbA1802a57a30Bf7dB34d7C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2596 add bbg info
  blockchains/ethereum/assets/0xdB70949d01Dc647B973e865A570361c223dAf358/info.json
  blockchains/ethereum/assets/0xdB70949d01Dc647B973e865A570361c223dAf358/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2589 Adding social money logos
  blockchains/ethereum/assets/0x0006634f2FDB9A12b179D05A2b5165B3210bade8/logo.png
  blockchains/ethereum/assets/0x039c642289e45EB7eE1B88123f4fC3aa94D34359/logo.png
  blockchains/ethereum/assets/0x0f961c328a96c23216B97b58947c2e8a741DE912/logo.png
  blockchains/ethereum/assets/0x1010603473C78277924A195A22115Ee9daB432a6/logo.png
  blockchains/ethereum/assets/0x174897edD3ce414084A009d22db31C7b7826400d/logo.png
  blockchains/ethereum/assets/0x19060094373C32E7f7d95eb4d1231f0779C91c23/logo.png
  blockchains/ethereum/assets/0x1eA1aaA7508cE9bB697478E16BEc57C438EB015c/logo.png
  blockchains/ethereum/assets/0x24eBA89651aa88810924D4669256Bb56832902fe/logo.png
  blockchains/ethereum/assets/0x258B3D55941BC8BCE4a80e7AE7CF685D245A24dc/logo.png
  blockchains/ethereum/assets/0x35840c161E1F677AEfb6cFF534fd8C5C93Af4824/logo.png
  blockchains/ethereum/assets/0x370DaE2AB60ECbc0EE793E837D94ca8040Dd6786/logo.png
  blockchains/ethereum/assets/0x3a4282b8fFBae5De5AB6E29bAd3d08d83902Ebd2/logo.png
  blockchains/ethereum/assets/0x4277DF6De4Cb2e25a2080DCf64aE533c9Aca8196/logo.png
  blockchains/ethereum/assets/0x42CB4AB485Fc91cdf6D07e224e5b55E44f0378a7/logo.png
  blockchains/ethereum/assets/0x43E248b058438F05e78CEb66aFC1555a97CB280F/logo.png
  blockchains/ethereum/assets/0x491614641F2e9456AB8d4B41a83534B71C4c4f85/logo.png
  blockchains/ethereum/assets/0x4BF93B7F68612Cc9ADef21dEA08ef74DCF0B6a6a/logo.png
  blockchains/ethereum/assets/0x56687cf29Ac9751Ce2a4E764680B6aD7E668942e/logo.png
  blockchains/ethereum/assets/0x6C03106799Fedd0060804aF8f05d007b8216C5AA/logo.png
  blockchains/ethereum/assets/0x6C5A643F582408a640068Ed68443D9185Fb2b0B8/logo.png
  blockchains/ethereum/assets/0x6e9DE2e85A8C1188995FeCea289b3F22E489bB12/logo.png
  blockchains/ethereum/assets/0x75FE5F25A39ac56083af564cFfA8F00c1b89011C/logo.png
  blockchains/ethereum/assets/0x8ee38cd3d0Ce2620d94Ad7DF54ac5B85d7d28935/logo.png
  blockchains/ethereum/assets/0x9621bad6E7E2b9758349DdCb308df7F63Fd46668/logo.png
  blockchains/ethereum/assets/0x9656d60bfcD8199E83621E0Ff24CD37f19AB9F57/logo.png
  blockchains/ethereum/assets/0x9903A4Cd589DA8e434f264deAFc406836418578E/logo.png
  blockchains/ethereum/assets/0xA67C912303b5227D6D4Dc7d16088342718a05bdf/logo.png
  blockchains/ethereum/assets/0xB58A2ebBB0Abe5797c78D69DBc419e98eB7A3b52/logo.png
  blockchains/ethereum/assets/0xB662CA3C91cb0811845f404bE7EE6dfc8E0B72e5/logo.png
  blockchains/ethereum/assets/0xC2579552eCb8e7c001564cE0e8E0DB77a0587E0e/logo.png
  blockchains/ethereum/assets/0xDd72b45AE5D8879D1dCE0B83fAD1E77390e3aD23/logo.png
  blockchains/ethereum/assets/0xE9cDA0749f2393254773Fd75A1Ca1639D9B25A17/logo.png
  blockchains/ethereum/assets/0xFdB655EDff5c7e733074a739B2b713B5CF567a8A/logo.png
  blockchains/ethereum/assets/0xa05a31924F767D23a03B0b1b2cF48654D0C87E0f/logo.png
  blockchains/ethereum/assets/0xa19A40FbD7375431fAB013a4B08F00871B9a2791/logo.png
  blockchains/ethereum/assets/0xa4A92262C8DFb70f35599996c64169EFf6E309ca/logo.png
  blockchains/ethereum/assets/0xb28f9C9B71B0C3885AE441A3c0F51027b760a991/logo.png
  blockchains/ethereum/assets/0xc14338C0eaa4bf7E4473C9DD7226001C8ae3B454/logo.png
  blockchains/ethereum/assets/0xc59fB1211F8226fD716180fCfA29D0A2FeE00FeD/logo.png
  blockchains/ethereum/assets/0xd6f4815213D6212Bd2B0ec80F2df084e5B9dbDAb/logo.png
  blockchains/ethereum/assets/0xdD349046eE302f843dEAbc61e3618Ab48eC19F5F/logo.png
  blockchains/ethereum/assets/0xe05C99fd798C09C066B87d841eCF89Dac4B4856E/logo.png
  blockchains/ethereum/assets/0xe47EE8d2A389EE924C5d0fE88296D6FAd55DA573/logo.png
  blockchains/ethereum/assets/0xe9406953401344819dF0392ECdfF238C5396C2A2/logo.png
  blockchains/ethereum/assets/0xf0AaBeAcbC2D91BAf21bDA0006C9D65DE736053a/logo.png
  blockchains/ethereum/assets/0xf552b656022c218C26dAd43ad88881Fc04116F76/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2590 Add Money Token (MNT) logo
  blockchains/ethereum/assets/0x310DA5e1E61cD9d6ECed092F085941089267E71E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2599 Add Logo to BWCToken
  blockchains/ethereum/assets/0xb7C86bBb0cE3F993E2C7076FB3505EA28D583FCE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2597 Add logo IMG
  blockchains/ethereum/assets/0xd1F579cc0a5405D7610346b371371bEd1528D18b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2605 resubmit_pr2602
  blockchains/ethereum/assets/0x61D71973A6FfD07d5F1095AED53b06E5673E64BC/logo.png
Labels: Payment Status: Requested

#2607 update c19 token
  blockchains/ethereum/assets/0x3CF82d81C9b71B112C8DD0C05fa05CdCDEe90189/info.json
  blockchains/ethereum/assets/0x3CF82d81C9b71B112C8DD0C05fa05CdCDEe90189/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2606 Pls add BHT (BillionHappiness)
  blockchains/ethereum/assets/0x32e3298939D56D0bb0dA5BD20dE8b589FF5e1B57/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2613 Logo for CTXT
  blockchains/ethereum/assets/0x5E4334fD53B95dF63993c805066d693bb8CE5dFc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2620 resubmit_pr2614
  blockchains/ethereum/assets/0x4730fB1463A6F1F44AEB45F6c5c422427f37F4D0/logo.png
Labels: Payment Status: Requested

#2604 Update list.json
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#2612 Add logo for the statera's delta UPT
  blockchains/ethereum/assets/0x59F96b8571E3B11f859A09Eaf5a790A138FC64D0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2608 Added Bridge Protocol (BRDG) tokens and logo
  blockchains/ethereum/assets/0xb736bA66aAd83ADb2322D1f199Bfa32B3962f13C/info.json
  blockchains/ethereum/assets/0xb736bA66aAd83ADb2322D1f199Bfa32B3962f13C/logo.png
  blockchains/neo/assets/bac0d143a547dc66a1d6a2b7d66b06de42614971/info.json
  blockchains/neo/assets/bac0d143a547dc66a1d6a2b7d66b06de42614971/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2625 add erc20 token icon
  blockchains/ethereum/assets/0x79327212F66c259f0A0b46961D2aEF91A503a9E1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2628 delete_old_INNBCL
  blockchains/ethereum/assets/0x8CC3E2BdC17682c622eB789EDA23FbD6988C84Da/logo.png
Labels: Payment Status: Requested

#2629 Add DAP token
  blockchains/ethereum/assets/0x780ec47d3696Fe6fc8Cd273D2420721bCEf936c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2635 Add this STST logo
  blockchains/ethereum/assets/0x6aD03307Fd545a68A391F99eFdd31CEC86569A4C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2603 Update logo and info for SS token
  blockchains/ethereum/assets/0xbbFF862d906E348E9946Bfb2132ecB157Da3D4b4/info.json
  blockchains/ethereum/assets/0xbbFF862d906E348E9946Bfb2132ecB157Da3D4b4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2636 Update New Logo of Unifier
  blockchains/ethereum/assets/0xEC02cEc4eDD54196D2767b61F43b29A49b056fe6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2639 Please add these logos ASAP...
  blockchains/ethereum/assets/0x5EF42C9eFFa0Ab4a6fAEB101CD328baA53Fa2268/logo.png
  blockchains/ethereum/assets/0x752fd71994776Bde43C91e943F8612517F242432/logo.png
  blockchains/ethereum/assets/0x7Fc03EEB44F260a72f9885fb10c74CF890962Ea7/logo.png
  blockchains/ethereum/assets/0xBc0d84FA6260E065F330d51621d682d2630F4Aa2/logo.png
  blockchains/ethereum/assets/0xEB6078B0f28291eC6328eE3f1f2804035145a5eD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2647 resubmit_pr2641
  blockchains/ethereum/assets/0xA740684C9022dc07540031b10dD57984640bAbef/logo.png
Labels: Payment Status: Requested

#2643 Add USD++
  blockchains/ethereum/assets/0x9A48BD0EC040ea4f1D3147C025cd4076A2e71e3e/info.json
  blockchains/ethereum/assets/0x9A48BD0EC040ea4f1D3147C025cd4076A2e71e3e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2615 Adding UNC - UniCrypt logo
  blockchains/ethereum/assets/0xf29e46887FFAE92f1ff87DfE39713875Da541373/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2644 update lvx token address
  blockchains/ethereum/assets/0x261638EC8ee8100484130EBD2fEBfDAdC0D8742a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2650 Update Pamp Network logo
  blockchains/ethereum/assets/0xF0FAC7104aAC544e4a7CE1A55ADF2B5a25c65bD1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2648 UPDATE DECASH
  blockchains/ethereum/assets/0xA740684C9022dc07540031b10dD57984640bAbef/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2621 Add Axiom (XOM)
  blockchains/classic/assets/0x5eB99507170F41bAA521cb71C9bCEa2a8A96827C/logo.png
  blockchains/classic/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2655 Please add uTOPIA logo
  blockchains/ethereum/assets/0x1F8f123bf24849443a56eD9fC42b9265b7F3A39a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2660 Adding Ruletka Token logo
  blockchains/ethereum/assets/0x1F6DEADcb526c4710Cf941872b86dcdfBbBD9211/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2623 Add Miraz token Token logo to Trust wallet
  blockchains/ethereum/assets/0xe571519185098b2f4914cA973d48c090426D69ee/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2659 Add BITLoTo (BTT) Token logo to Trust wallet
  blockchains/ethereum/assets/0x439ad7Ac2b7D92a24C25537CF1AA243f365D0CB0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2661 Add CRS Token (CRSTK) Token logo to Trust wallet
  blockchains/ethereum/assets/0x2cf98D4B9C06487ADBd33D54ee54E16aa8515382/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2663 upload FBCC logo
  blockchains/ethereum/assets/0xc6E2970cf8b1943fb58dB5b3c19CFc2ee146f376/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2658 baarbird token logo update
  blockchains/ethereum/assets/0x9da66Fe42480141b4b238e9573a0F83880D83a51/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2664 Add files via upload
  blockchains/ethereum/assets/0xC30A5e36072612a5884AA6BDc2289fC5e8901638/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2665 Add $buidl V2 Logo
  blockchains/ethereum/assets/0x7b123f53421b1bF8533339BFBdc7C98aA94163db/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2666 ADD ULLU LOGO
  blockchains/ethereum/assets/0x5313E18463Cf2F4b68b392a5b11f94dE5528D01d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2667 Add TPX
  blockchains/ethereum/assets/0x162b3b37aAB1c09BD852F6227B17d4a5a9F60962/info.json
  blockchains/ethereum/assets/0x162b3b37aAB1c09BD852F6227B17d4a5a9F60962/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2670 resubmit_pr2668
  blockchains/ethereum/assets/0x6710c63432A2De02954fc0f851db07146a6c0312/logo.png
Labels: Payment Status: Requested

#2671 add OMC logo and info
  blockchains/binance/assets/ECO-083/logo.png
  blockchains/ethereum/assets/0xd6bD97a26232bA02172Ff86b055d5D7bE789335B/info.json
  blockchains/ethereum/assets/0xd6bD97a26232bA02172Ff86b055d5D7bE789335B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2677 add FMO token
  blockchains/ethereum/assets/0xE9b8897f3bd92a5845CDEAAeBEa1be5703D53fe2/info.json
  blockchains/ethereum/assets/0xE9b8897f3bd92a5845CDEAAeBEa1be5703D53fe2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2676 Add xDai chain and xMoon, Honey tokens
  blockchains/xdai/assets/0x1e16aa4Df73d29C029d94CeDa3e3114EC191E25A/logo.png
  blockchains/xdai/assets/0x71850b7E9Ee3f13Ab46d67167341E4bDc905Eef9/logo.png
  blockchains/xdai/blacklist.json
  blockchains/xdai/info/info.json
  blockchains/xdai/info/logo.png
  blockchains/xdai/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2679 Upload logo
  blockchains/ethereum/assets/0x4Ba6dDd7b89ed838FEd25d208D4f644106E34279/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2681 Add New Logo
  blockchains/ethereum/assets/0xF7a6ACd437eDC08320AB17644Bb5963753a4E6D8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2683 ADD TRUSTSWAP LOGO
  blockchains/ethereum/assets/0xCC4304A31d09258b0029eA7FE63d032f52e44EFe/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2680 BEP2 : Adding RNO-14E
  blockchains/binance/assets/RNO-14E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2685 adding moon logo
  blockchains/ethereum/assets/0x73f8406eAACe2CE69BA49a67551464FDa1D11F14/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2686 Create add logo to ETHK
  blockchains/ethereum/assets/0xC2fbab8de59F2671d55137DfD837f68e9a040867/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2691 Update CLN token logo on trust wallet
  blockchains/ethereum/assets/0xaD2aa3C57570AD9811bA8Ee90316f9C73F78035A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2687 Add files via upload
  blockchains/ethereum/assets/0x88277055dF2EE38dA159863dA2F56ee0A6909D62/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2688 Add FSXA logo
  blockchains/ethereum/assets/0xf0B0A13d908253D954BA031a425dFd54f94a2e3D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2693 Delete use of @trustwallet/types
  package-lock.json
  package.json
  pricing/coinmarketcap/script.ts
  src/test/helpers.ts
Labels: Payment Status: Requested

#2692 Please Add Logos On Trust Wallet ASAP
  blockchains/ethereum/assets/0x4E6b679780e0Ffa47D7e05A1a21B5e0A7834039e/logo.png
  blockchains/ethereum/assets/0x752fd71994776Bde43C91e943F8612517F242432/logo.png
  blockchains/ethereum/assets/0x96e6002A97Cd804aDA9E4864AC306CaDDBfeB73B/logo.png
  blockchains/ethereum/assets/0x997DD3880C08d55B3551232Fb8f666975fDbBf58/logo.png
  blockchains/ethereum/assets/0xAe9D7C1FD1980E1Ca40AAB0b94140ca27435ea27/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2699 resubmit_pr2682
  blockchains/ethereum/assets/0x81e70eA3d76D713Ea1F501f89417aF9BCc2A5f9F/logo.png
Labels: Payment Status: Requested

#2698 Update list.json
  blockchains/tezos/validators/assets/tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#2690 TB token logo
  blockchains/ethereum/assets/0xA2DCA432DCe9c67Bfa31B29A8af0c7852cFf4713/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2704 replaced ODE logo
  blockchains/ethereum/assets/0x6F6d15e2DAbD182c7C0830dB1bDfF1f920b57ffA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2708 polypux
  blockchains/ethereum/assets/0xE277aC35F9D327A670c1A3F3eeC80a83022431e4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2710 Add files via upload
  blockchains/ethereum/assets/0x9F54a5ec929dec40E600f76252e68595Fe91ed20/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2718 new logo
  blockchains/ethereum/assets/0x5A2fe67e429fB02ceBc3344a23e90E242263205D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2719 logo
  blockchains/ethereum/assets/0x5219D24CAa72040F055fC547Cc786a29e025E767/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2721 Trc20 csto
  blockchains/tron/assets/TDh4z44NbqrCGVCCqBe753UqHW2CcDpurB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2705 Add LKSCOIN
  blockchains/ethereum/assets/0xfC4A2Cd574bdcC385173f03A6a52cC3B853BB9d4/logo.png
  blockchains/ethereum/whitelist.json
  blockchains/lkscoin/info/info.json
  blockchains/lkscoin/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2714 Adding PayAccept Logo
  blockchains/ethereum/assets/0x1Fe72034dA777ef22533eaa6Dd7cBE1D80bE50Fa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2723 add EASTERN LIGHT CAPITAL (ELC) token logo on trust wallet
  blockchains/ethereum/assets/0x9577Daade444cE9b53026ABbFD4aA45bD4a7fDEc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2725 Submit logo for Startchain (STC)
  blockchains/ethereum/assets/0x6752787D5A119DAD443E97cC6CC4449C655ED5d2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2728 0xe4f7A608B0eEdC93A97d1249c8bbDa0e98077d29
  blockchains/ethereum/assets/0xe4f7A608B0eEdC93A97d1249c8bbDa0e98077d29/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2726 Update info
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#2727 add our new logo
  blockchains/tezos/validators/assets/tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8/logo.png
Labels: Payment Status: Requested

#2732 Add ATB Token
  blockchains/ethereum/assets/0x31371618e52a1dCD55Caa07f6E81628Bd4371585/info.json
  blockchains/ethereum/assets/0x31371618e52a1dCD55Caa07f6E81628Bd4371585/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2735 Submit logo for Swissy Stable Coin
  blockchains/ethereum/assets/0xa09CEBC152553e1086bE9cE5efBd9dcbb6641479/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2734 Add TRVx Logo
  blockchains/tron/assets/TQhfmGiZvRt3oe9vKv6W9WXRr4oErxc8RE/logo.png
  blockchains/tron/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2743 Add TPT in ETH
  blockchains/ethereum/assets/0x4161725D019690a3E0de50f6bE67b07a86A9fAe1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2748 Add mStable MTA and update mStable mUSD
  blockchains/ethereum/assets/0xa3BeD4E1c75D00fa6f4E5E6922DB7261B5E9AcD2/info.json
  blockchains/ethereum/assets/0xa3BeD4E1c75D00fa6f4E5E6922DB7261B5E9AcD2/logo.png
  blockchains/ethereum/assets/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5/info.json
  blockchains/ethereum/assets/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2731 Add Satoshi Vision Coin (SVC) logo
  blockchains/ethereum/assets/0x64EA2c6104F1CF3035E28Be0f781B6286d50934D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2722 Add logo for CRVT
  blockchains/ethereum/assets/0x0Eb6E56aAcae6A21BdE99c826ac798D225488C3D/logo.png
  blockchains/ethereum/assets/0xb83Cd8d39462B761bb0092437d38b37812dd80A2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2741 bzrx and vbzrx tokens added
  blockchains/ethereum/assets/0x56d811088235F11C8920698a204A5010a788f4b3/info.json
  blockchains/ethereum/assets/0x56d811088235F11C8920698a204A5010a788f4b3/logo.png
  blockchains/ethereum/assets/0xB72B31907C1C95F3650b64b2469e08EdACeE5e8F/info.json
  blockchains/ethereum/assets/0xB72B31907C1C95F3650b64b2469e08EdACeE5e8F/logo.png
  blockchains/ethereum/whitelist.json
Labels: Payment Status: Paid, Payment Status: Requested

#2749 Please add CRS on TrustWallet
  blockchains/ethereum/assets/0xEc7D3E835dA3F6118079fA9a236b267D044FD7cA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2751 Add Havens Nook (HXN)
  blockchains/ethereum/assets/0x0E1fe60bc4aC0e3102343752ae7E49d01d444c0b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2742 add SGT icon (trustwallet)
  blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/info.json
  blockchains/ethereum/assets/0xc4199fB6FFDb30A829614becA030f9042f1c3992/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2747 add MCB logo and info.json
  blockchains/ethereum/assets/0x4e352cF164E64ADCBad318C3a1e222E9EBa4Ce42/info.json
  blockchains/ethereum/assets/0x4e352cF164E64ADCBad318C3a1e222E9EBa4Ce42/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2752 Add files via upload
  blockchains/ethereum/assets/0x0442BC99441F55244131CC13A2E717C493DDbF01/info.json
  blockchains/ethereum/assets/0x0442BC99441F55244131CC13A2E717C493DDbF01/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2754 Update outdated explorer link for Solana
  blockchains/solana/info/info.json
Labels: Payment Status: Requested

#2711 Upload Exchain token
  blockchains/ethereum/assets/0xd77604D92cFC8D51C945A52908b8532aB7bD19D2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2755 Add Logo for Tatcoin
  blockchains/ethereum/assets/0x37Ee79E0B44866876de2fB7F416d0443DD5ae481/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2757 Add logo for Liber Forex
  blockchains/ethereum/assets/0xc0ea83113038987d974FE667831a36E442e661E7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2756 [ethereum-assets/decentr] Logo and info.json are added for DEC (Decentr) token
  blockchains/ethereum/assets/0x30f271C9E86D2B7d00a6376Cd96A1cFBD5F0b9b3/info.json
  blockchains/ethereum/assets/0x30f271C9E86D2B7d00a6376Cd96A1cFBD5F0b9b3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2744 add vanCoin Logo
  blockchains/ethereum/assets/0x7bF219195f0A3E109886AE5901298A9ba34DD1F6/info.json
  blockchains/ethereum/assets/0x7bF219195f0A3E109886AE5901298A9ba34DD1F6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2762 Logo for DST
  blockchains/ethereum/assets/0x66b213c6C76C578C58973184bB09aCB6e6F99D7C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2769 alter logo
  blockchains/ethereum/assets/0xB5cc99F4Ff0EcAA55D705e83106296E00E507f93/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2768 Added Flapp Token
  blockchains/ethereum/assets/0xCfb72ED3647cC8E7FA52E4F121eCdAbEfC305e7f/info.json
  blockchains/ethereum/assets/0xCfb72ED3647cC8E7FA52E4F121eCdAbEfC305e7f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2765 VXC info.json
  blockchains/ethereum/assets/0x14F0a12A43c36C49D4b403dD6e1A9B8222BE456C/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#2764 Add logo for Derivatives Smart Contract Token
  blockchains/ethereum/assets/0xf434f92a7867025204d1A2419d0731316b3F6c6a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2746 Add logo for 0xa10ae543dB5D967a73E9Abcc69c81a18A7Fc0A78
  blockchains/ethereum/assets/0xa10ae543dB5D967a73E9Abcc69c81a18A7Fc0A78/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2763 Lending Platform ( LPT ) Logo
  blockchains/ethereum/assets/0xF5CB11bAD09093E71E91a38c06Fe78e4c4042058/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2766 Add Logo for DIMT
  blockchains/ethereum/assets/0x81246a3F5fab7Aa9f4F625866105F3CAfFc67686/info.json
  blockchains/ethereum/assets/0x81246a3F5fab7Aa9f4F625866105F3CAfFc67686/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2753 Change logo file
  blockchains/binance/assets/GIV-94E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2773 THIRM TOKEN
  blockchains/ethereum/assets/0xa93f2a6b50D92BD64848f5ea15164F558B75ce9C/info.json
  blockchains/ethereum/assets/0xa93f2a6b50D92BD64848f5ea15164F558B75ce9C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2759 Add triatics logo
  blockchains/ethereum/assets/0xe74d6339890d6640eF12e6FBcaF7116f331D6d5D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2775 Add Logo for Pi Futures
  blockchains/ethereum/assets/0xe875c61d4721424A6988E5fA2dFB8d6CA6af5c64/info.json
  blockchains/ethereum/assets/0xe875c61d4721424A6988E5fA2dFB8d6CA6af5c64/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2774 Add hybrix project, info and logo files
  blockchains/ethereum/assets/0x9b53E429B0baDd98ef7F01F03702986c516a5715/info.json
  blockchains/ethereum/assets/0x9b53E429B0baDd98ef7F01F03702986c516a5715/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2776 Add Fireball (FIRE) logo on trust wallet apps
  blockchains/ethereum/assets/0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2778 new PIXBY asset
  blockchains/ethereum/assets/0xB53e08B97724126Bda6d237B94F766c0b81C90fE/info.json
  blockchains/ethereum/assets/0xB53e08B97724126Bda6d237B94F766c0b81C90fE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2779 Update DOV token icon and info
  blockchains/ethereum/assets/0xac3211a5025414Af2866FF09c23FC18bc97e79b1/info.json
  blockchains/ethereum/assets/0xac3211a5025414Af2866FF09c23FC18bc97e79b1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2781 Add FRY logo
  blockchains/ethereum/assets/0x6c972b70c533E2E045F333Ee28b9fFb8D717bE69/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2783 Inserting Libertas Logo
  blockchains/ethereum/assets/0x49184E6dAe8C8ecD89d8Bdc1B950c597b8167c90/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2750 Create SeChain
  blockchains/ethereum/assets/0xF5717f5DF41eA67Ef67DFD3c1d02F9940bcF5d08/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2785 DHT Logo
  blockchains/ethereum/assets/0x5555e6B8e710BBCd7804f5172395b87c09621f80/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2780 Add ORN token icon and info
  blockchains/ethereum/assets/0x8fB00FDeBb4E83f2C58b3bcD6732AC1B6A7b7221/info.json
  blockchains/ethereum/assets/0x8fB00FDeBb4E83f2C58b3bcD6732AC1B6A7b7221/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2789 Create info.json, Update Ticker on trustwallet from "dht" to "DHT"
  blockchains/ethereum/assets/0x5555e6B8e710BBCd7804f5172395b87c09621f80/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#2790 Add logo DFA
  blockchains/ethereum/assets/0x8Bedb57393F24FbdDf36A76881E21Ed5037d00a4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2794 add bonk logo
  blockchains/ethereum/assets/0x6D6506E6F438edE269877a0A720026559110B7d5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2795 Bichoncoin Logo Update
  blockchains/ethereum/assets/0xA5a2892d3FbB46d461D990469d5b797A1E6655cc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2796 update TRC20 CBC Logo
  blockchains/tron/assets/TDFRfJLThnLXgtEBBBmA2LGwz3Ex9dAMCE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2799 Upload ARAKAN DAN GAR token
  blockchains/ethereum/assets/0x4e7363E2B4253f07D786Fd12CFeE45f121DdaE98/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2800 Upload Backero Token logo
  blockchains/ethereum/assets/0x33589ad907a47313166d34Cb8eE0a2aCC2c00d8E/info.json
  blockchains/ethereum/assets/0x33589ad907a47313166d34Cb8eE0a2aCC2c00d8E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2801 Update WRC token logo on trust wallet
  blockchains/ethereum/assets/0x7c9D8Fb3bDe3D9Ea6e89170618C2dC3d16695D36/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#2791 Add RARI Logo
  blockchains/ethereum/assets/0xFca59Cd816aB1eaD66534D82bc21E7515cE441CF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
