Repository trustwallet/assets, pull requests merged in 2020-11, with the labels that each got.

#4648 Adding our Companies new Token eRSDL for Uniswap and hopefully TrustW…
  blockchains/ethereum/assets/0x5218E472cFCFE0b64A064F055B43b4cdC9EfD3A6/info.json
  blockchains/ethereum/assets/0x5218E472cFCFE0b64A064F055B43b4cdC9EfD3A6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Correction needed

#4652 Add ABY Logo
  blockchains/ethereum/assets/0x26c5331a8AAEDe3d3Af276fD61329163a55ECbCa/info.json
  blockchains/ethereum/assets/0x26c5331a8AAEDe3d3Af276fD61329163a55ECbCa/logo.png
Labels: Payment Status: Paid

#4686 update info
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#4689 [internal] Update TFD (Te-Food) to TONE
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x2Ab6Bb8408ca3199B8Fa6C92d5b455F820Af03c4/info.json
  blockchains/ethereum/assets/0x2Ab6Bb8408ca3199B8Fa6C92d5b455F820Af03c4/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4662 Upload UTU icon
  blockchains/ethereum/assets/0x29E9fDF5933824ad21Bc6dbb8BF156EFA3735e32/info.json
  blockchains/ethereum/assets/0xBd2949F67DcdC549c6Ebe98696449Fa79D988A9F/info.json
  blockchains/ethereum/assets/0xa58a4f5c4Bb043d2CC1E170613B74e767c94189B/info.json
  blockchains/ethereum/assets/0xa58a4f5c4Bb043d2CC1E170613B74e767c94189B/logo.png
Labels: Payment Status: Paid

#4685 Request to add RFOX token logo to trustwallet assets
  blockchains/ethereum/assets/0xa1d6Df714F91DeBF4e0802A542E13067f31b8262/info.json
  blockchains/ethereum/assets/0xa1d6Df714F91DeBF4e0802A542E13067f31b8262/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4582 NRG Added logo and info
  blockchains/ethereum/assets/0x1416946162B1C2c871A73B07E932D2fB6C932069/info.json
  blockchains/ethereum/assets/0x1416946162B1C2c871A73B07E932D2fB6C932069/logo.png
Labels: Payment Status: Paid

#4602 Adding ZEFU Info (ERC-20)
  blockchains/ethereum/assets/0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229/info.json
  blockchains/ethereum/assets/0xB1e9157c2Fdcc5a856C8DA8b2d89b6C32b3c1229/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#4695 [internal] Change merge fee
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#4696 [internal][TokenList] 22 popular tokens added for Ethereum
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4697 [internal][TokenList] Remove duplicate
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4698 [internal][TokeList] USDC decimals fixed
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4702 StarCurve rebranded to StarDEX
  blockchains/ethereum/assets/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f/info.json
  blockchains/ethereum/assets/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f/logo.png
Labels: Payment Status: Paid

#4700 Added information and logo for Holyheld (HOLY) token
  blockchains/ethereum/assets/0x39eAE99E685906fF1C11A962a743440d0a1A6e09/info.json
  blockchains/ethereum/assets/0x39eAE99E685906fF1C11A962a743440d0a1A6e09/logo.png
Labels: Payment Status: Paid

#4691 Update StakingShop Tezos validator
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#4710 Prqboost logo
  blockchains/ethereum/assets/0xa211F450Ce88deb31D3F12Ae3C1EBf6b0e55A5d9/info.json
  blockchains/ethereum/assets/0xa211F450Ce88deb31D3F12Ae3C1EBf6b0e55A5d9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4705 Add bsc.farm dapp logo
  dapps/bsc.farm.png
Labels: Payment Status: Paid

#4701 add HARD and USDX asset icons to kava blockchain
  blockchains/kava/assets/hard/logo.png
  blockchains/kava/assets/usdx/logo.png
Labels: Payment Status: Requested

#4711 [internal][Smartchain] TWT/WBNB/Cake added into TokenList
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#4687 Add Keep4r (KP4R) Token.
  blockchains/ethereum/assets/0xA89ac6e529aCf391CfbBD377F3aC9D93eae9664e/info.json
  blockchains/ethereum/assets/0xA89ac6e529aCf391CfbBD377F3aC9D93eae9664e/logo.png
Labels: Payment Status: Paid

#4708 Added AUDIT.one - Cosmos, Terra and Kava validators
  blockchains/cosmos/validators/assets/cosmosvaloper1udpsgkgyutgsglauk9vk9rs03a3skc62gup9ny/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/assets/kavavaloper14gfgngrgg0pj494euuuvhygrhfptzf2hxllsev/logo.png
  blockchains/kava/validators/list.json
  blockchains/terra/validators/assets/terravaloper1n7pkcal0jkp0ac9r338qp9cm5x6cakfnremtnt/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#4688 Add COR (Coreto) Token
  blockchains/ethereum/assets/0x9C2dc0c3CC2BADdE84B0025Cf4df1c5aF288D835/info.json
  blockchains/ethereum/assets/0x9C2dc0c3CC2BADdE84B0025Cf4df1c5aF288D835/logo.png
Labels: Payment Status: Paid

#4714 [internal] Move binance tokenlist generation from fix to update
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#4716 Added DYT to TrustSwap support...
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid, Payment Status: Requested

#4718 Updating logo color
  blockchains/filecoin/info/logo.png
Labels: Payment Status: Requested

#4719 Updating FIL logo with official color + Binance peg indicators for Filecoin-related logos
  blockchains/binance/assets/FIL-E2C/logo.png
  blockchains/ethereum/assets/0x8E16bf47065Fe843A82f4399bAF5aBac4E0822B7/logo.png
  blockchains/smartchain/assets/0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153/logo.png
Labels: Payment Status: Requested

#4722 [internal] Lint fix
  script/generic/asset-infos.ts
Labels: Payment Status: Requested

#4715 Updating the logo for Indorse IND token
  blockchains/ethereum/assets/0xf8e386EDa857484f5a12e4B5DAa9984E06E73705/info.json
  blockchains/ethereum/assets/0xf8e386EDa857484f5a12e4B5DAa9984E06E73705/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4724 modify BEP20 HARD
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x19474B9B4BD7a81FA612307f69B5A44618d42595/info.json
  blockchains/smartchain/assets/0xf79037F6f6bE66832DE4E7516be52826BC3cBcc4/info.json
  blockchains/smartchain/assets/0xf79037F6f6bE66832DE4E7516be52826BC3cBcc4/logo.png
  blockchains/smartchain/denylist.json
Labels: Payment Status: Requested

#4728 Add SmartKey logo and info
  blockchains/ethereum/assets/0x06A01a4d579479Dd5D884EBf61A31727A3d8D442/info.json
  blockchains/ethereum/assets/0x06A01a4d579479Dd5D884EBf61A31727A3d8D442/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4690 Adding support for GALA (gala.games)
  blockchains/ethereum/assets/0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA/info.json
  blockchains/ethereum/assets/0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA/logo.png
Labels: Payment Status: Paid

#4739 add ERC20 Research 11/8
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x0258F474786DdFd37ABCE6df6BBb1Dd5dfC4434a/info.json
  blockchains/ethereum/assets/0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828/info.json
  blockchains/ethereum/assets/0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998/info.json
  blockchains/ethereum/assets/0x18aAA7115705e8be94bfFEBDE57Af9BFc265B998/logo.png
  blockchains/ethereum/assets/0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44/info.json
  blockchains/ethereum/assets/0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44/logo.png
  blockchains/ethereum/assets/0x4575f41308EC1483f3d399aa9a2826d74Da13Deb/info.json
  blockchains/ethereum/assets/0x5bEaBAEBB3146685Dd74176f68a0721F91297D37/info.json
  blockchains/ethereum/assets/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419/info.json
  blockchains/ethereum/assets/0x8Ab7404063Ec4DBcfd4598215992DC3F8EC853d7/info.json
  blockchains/ethereum/assets/0xB8BAa0e4287890a5F79863aB62b7F175ceCbD433/info.json
  blockchains/ethereum/assets/0xF5D669627376EBd411E34b98F19C868c8ABA5ADA/info.json
  blockchains/ethereum/assets/0xF5D669627376EBd411E34b98F19C868c8ABA5ADA/logo.png
  blockchains/ethereum/assets/0xdc9Ac3C20D1ed0B540dF9b1feDC10039Df13F99c/info.json
Labels: Payment Status: Requested

#4729 Add Atari Token Logo
  blockchains/ethereum/assets/0xdacD69347dE42baBfAEcD09dC88958378780FB62/info.json
  blockchains/ethereum/assets/0xdacD69347dE42baBfAEcD09dC88958378780FB62/logo.png
Labels: Payment Status: Paid

#4676 Add PLNT logo and info
  blockchains/smartchain/assets/0x3AbfC084a54E5f4e23196e1B9a9c48c3B3021519/info.json
  blockchains/smartchain/assets/0x3AbfC084a54E5f4e23196e1B9a9c48c3B3021519/logo.png
Labels: Payment Status: Paid

#4748 Add Origin Dollar (OUSD) and update the info for OGN
  blockchains/ethereum/assets/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86/info.json
  blockchains/ethereum/assets/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86/logo.png
  blockchains/ethereum/assets/0x8207c1FfC5B6804F6024322CcF34F29c3541Ae26/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#4750 Add APY.Finance token to Trust Wallet
  blockchains/ethereum/assets/0x95a4492F028aa1fd432Ea71146b433E7B4446611/info.json
  blockchains/ethereum/assets/0x95a4492F028aa1fd432Ea71146b433E7B4446611/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4723 Update Asko Logo & Add info.json
  blockchains/ethereum/assets/0xeEEE2a622330E6d2036691e983DEe87330588603/info.json
  blockchains/ethereum/assets/0xeEEE2a622330E6d2036691e983DEe87330588603/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4749 Add ADX-LOYALTY logo and info
  blockchains/ethereum/assets/0xd9A4cB9dc9296e111c66dFACAb8Be034EE2E1c2C/info.json
  blockchains/ethereum/assets/0xd9A4cB9dc9296e111c66dFACAb8Be034EE2E1c2C/logo.png
Labels: Payment Status: Paid

#4738 Add UNCL logo and info
  blockchains/ethereum/assets/0x2f4eb47A1b1F4488C71fc10e39a4aa56AF33Dd49/info.json
  blockchains/ethereum/assets/0x2f4eb47A1b1F4488C71fc10e39a4aa56AF33Dd49/logo.png
  blockchains/ethereum/assets/0xf29e46887FFAE92f1ff87DfE39713875Da541373/info.json
  blockchains/ethereum/assets/0xf29e46887FFAE92f1ff87DfE39713875Da541373/logo.png
Labels: Payment Status: Paid

#4744 Add DOKI info and logo
  blockchains/ethereum/assets/0x9cEB84f92A0561fa3Cc4132aB9c0b76A59787544/info.json
  blockchains/ethereum/assets/0x9cEB84f92A0561fa3Cc4132aB9c0b76A59787544/logo.png
Labels: Payment Status: Paid

#4758 swapliquidity dapp
  dapps/swapliquidity.org.png
Labels: Payment Status: Paid

#4760 SmartCredit.io token info and logo
  blockchains/ethereum/assets/0x72e9D9038cE484EE986FEa183f8d8Df93f9aDA13/info.json
  blockchains/ethereum/assets/0x72e9D9038cE484EE986FEa183f8d8Df93f9aDA13/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4737 Update token list of ThunderCore network
  blockchains/thundertoken/allowlist.json
  blockchains/thundertoken/assets/0x18fB0A62f207A2a082cA60aA78F47a1af4985190/info.json
  blockchains/thundertoken/assets/0x18fB0A62f207A2a082cA60aA78F47a1af4985190/logo.png
  blockchains/thundertoken/assets/0x22e89898A04eaf43379BeB70bf4E38b1faf8A31e/info.json
  blockchains/thundertoken/assets/0x22e89898A04eaf43379BeB70bf4E38b1faf8A31e/logo.png
  blockchains/thundertoken/assets/0x2b31e3b88847f03c1335E99A0d1274A2c72059DE/info.json
  blockchains/thundertoken/assets/0x4f3C8E20942461e2c3Bdd8311AC57B0c222f2b82/info.json
  blockchains/thundertoken/assets/0x6576Bb918709906DcbFDCeae4bB1e6df7C8a1077/info.json
  blockchains/thundertoken/assets/0x6576Bb918709906DcbFDCeae4bB1e6df7C8a1077/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4803 add ERC20 BUSD
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4778 Change Tadpole Logo
  blockchains/ethereum/assets/0x9f7229aF0c4b9740e207Ea283b9094983f78ba04/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4807 modify ERC20 CAPP
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x11613b1f840bb5A40F8866d857e24DA126B79D73/info.json
  blockchains/ethereum/assets/0x11613b1f840bb5A40F8866d857e24DA126B79D73/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4743 Add social money logos
  blockchains/ethereum/assets/0x1710Ce5A145199Fb7F4C68d16eDF32C95b2850D9/logo.png
  blockchains/ethereum/assets/0x1eCe1739DAE08253aE582C404511B37355B42C84/logo.png
  blockchains/ethereum/assets/0x21C7F008970bFAbcCF9D44Fe7EE7e1f4A5401FEb/logo.png
  blockchains/ethereum/assets/0x28ebC92E995Ef0a2C9A069D39F991c55A512e07c/logo.png
  blockchains/ethereum/assets/0x2Ad128fBEFF2B781D028148DEc82bBe2498Dc08e/logo.png
  blockchains/ethereum/assets/0x2DE4ef1Eb481cF4a7b8C9f88f6D2E47387cFAf5F/logo.png
  blockchains/ethereum/assets/0x2Feb105FBb4c922597b125C56822B3db7351B55d/logo.png
  blockchains/ethereum/assets/0x2ef31d97FA8Ab9440d911f38c6D53921C5a64257/logo.png
  blockchains/ethereum/assets/0x35872fea6A4843fACBCDbCe99e3B69596A3680b8/logo.png
  blockchains/ethereum/assets/0x4Ae20b59138431597C09A4531CD3d3156940d596/logo.png
  blockchains/ethereum/assets/0x521cdd9083b751dba264e9E000d11511993836e9/logo.png
  blockchains/ethereum/assets/0x537A9095b78517597b5f2058EDcd6E1978095909/logo.png
  blockchains/ethereum/assets/0x5B9DeCe6E8E703BFfC25E794e6f5DfaEbd26D543/logo.png
  blockchains/ethereum/assets/0x5f9172EcEeaC7bBac9DD6A8013bfA9a30F5E5628/logo.png
  blockchains/ethereum/assets/0x67b562802aE7Da63283741103d14F508597f6380/logo.png
  blockchains/ethereum/assets/0x6CE10f66B4D47601Be2BEd4aC20653D9b90d0759/logo.png
  blockchains/ethereum/assets/0x740B88Dd18D4987f1b0Fe02d59E174be59938EBb/logo.png
  blockchains/ethereum/assets/0x7f791C8B4Fd1AA6EF52157Cca3436f7cE9844058/logo.png
  blockchains/ethereum/assets/0x833E4c02c47B7e38f5b9A80b26eb07D23d1961f4/logo.png
  blockchains/ethereum/assets/0x9401d929B299e634b34b66BbE24BFB4568553e7F/logo.png
  blockchains/ethereum/assets/0x9496b91175490C26887DBD18cc423AD40CcD274E/logo.png
  blockchains/ethereum/assets/0x9CF140FEB1109dd6E5a602C17a7A5aEd9a9b1DdC/logo.png
  blockchains/ethereum/assets/0xA7aB21CA0a11d63369de020601b1342baA71144E/logo.png
  blockchains/ethereum/assets/0xB663DF075579FdCAA17E4335aB8E7189BdEBe69b/logo.png
  blockchains/ethereum/assets/0xC53a9c309Ee2F3E333BD6ecA806A31d0e2Dca5C5/logo.png
  blockchains/ethereum/assets/0xC5e51F32d0C8BbeF06882045db98FF8bC7fAfC49/logo.png
  blockchains/ethereum/assets/0xC7cae65F4C0C98e643155d85616B95eE71F64Ca5/logo.png
  blockchains/ethereum/assets/0xC91b81df82534eA95C547abE86db455976ce70F8/logo.png
  blockchains/ethereum/assets/0xD1eED78FdB470d20aCfa35329879b5051eE68738/logo.png
  blockchains/ethereum/assets/0xDB9EA477A2E1985B437e02c2Cd84d72E6Bf72c76/logo.png
  blockchains/ethereum/assets/0xF5D669627376EBd411E34b98F19C868c8ABA5ADA/logo.png
  blockchains/ethereum/assets/0xa2f96EF6ed3d67A0352e659B1E980f13e098619F/logo.png
  blockchains/ethereum/assets/0xa59D9c42eb26a619c39D250b4574BD76023A760E/logo.png
  blockchains/ethereum/assets/0xdB147d66851Fa80CD40A51E81E16Da26bA4Ea6B0/logo.png
  blockchains/ethereum/assets/0xf5593de88c5391722873AFBA0cbe16fEc11066d5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4785 sorare dapp logo
  dapps/sorare.com.png
Labels: Payment Status: Paid

#4815 [Smartchain] Fix CTK token and disable swap
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#4811 Added request to be listed as a validator on Tezos network
  blockchains/tezos/validators/assets/tz1aDiEJf9ztRrAJEXZfcG3CKimoKsGhwVAi/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Paid

#4791 new logo for pylon (old one was skewed)
  blockchains/ethereum/assets/0xD7B7d3C0bdA57723Fb54ab95Fd8F9EA033AF37f2/info.json
  blockchains/ethereum/assets/0xD7B7d3C0bdA57723Fb54ab95Fd8F9EA033AF37f2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4813 Add HEGIC logo and information
  blockchains/ethereum/assets/0x584bC13c7D411c00c01A62e8019472dE68768430/info.json
  blockchains/ethereum/assets/0x584bC13c7D411c00c01A62e8019472dE68768430/logo.png
Labels: Payment Status: Paid

#4820 ARTE INFO UPDATE
  blockchains/ethereum/assets/0x34612903Db071e888a4dADcaA416d3EE263a87b9/info.json
  blockchains/ethereum/assets/0x34612903Db071e888a4dADcaA416d3EE263a87b9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4822 Add cBRL in BEP20 Network
  blockchains/smartchain/assets/0x9E691FD624410D631c082202b050694233031cB7/info.json
  blockchains/smartchain/assets/0x9E691FD624410D631c082202b050694233031cB7/logo.png
Labels: Payment Status: Paid

#4837 Add VOXb logo and info
  blockchains/smartchain/assets/0xC227f8EECC481A8e8BAa30A4754B109b81C4DfA4/info.json
  blockchains/smartchain/assets/0xC227f8EECC481A8e8BAa30A4754B109b81C4DfA4/logo.png
Labels: Payment Status: Paid

#4821 Add sav3 token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x6E10AAcb89A28d6FA0FE68790777fec7E7f01890/info.json
  blockchains/ethereum/assets/0x6E10AAcb89A28d6FA0FE68790777fec7E7f01890/logo.png
Labels: Payment Status: Paid

#4824 AllWin Token logo request
  blockchains/ethereum/assets/0xc6358C02A4BaFcbcd85360ae046e6bEe556429c1/info.json
  blockchains/ethereum/assets/0xc6358C02A4BaFcbcd85360ae046e6bEe556429c1/logo.png
Labels: Payment Status: Paid

#4840 added UBT and RLC
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4845 remove TON related tokens
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xD6E6a28eB0a72AF2336f80E143E7311bc3108B97/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4848 update ERC20 SHR
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xd98F75b1A3261dab9eEd4956c93F33749027a964/info.json
  blockchains/ethereum/assets/0xd98F75b1A3261dab9eEd4956c93F33749027a964/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4847 [internal] Do not automatically add tokens to denylist
  script/generic/allowlists.ts
Labels: Payment Status: Requested

#4863 add BEP20 HARD
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#4858 Added QuiverX logo and info.
  blockchains/ethereum/assets/0x6e0daDE58D2d89eBBe7aFc384e3E4f15b70b14D8/info.json
  blockchains/ethereum/assets/0x6e0daDE58D2d89eBBe7aFc384e3E4f15b70b14D8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4833 Add xSushi token
  blockchains/ethereum/assets/0x8798249c2E607446EfB7Ad49eC89dD1865Ff4272/info.json
  blockchains/ethereum/assets/0x8798249c2E607446EfB7Ad49eC89dD1865Ff4272/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4754 Add LTX
  blockchains/ethereum/assets/0xa393473d64d2F9F026B60b6Df7859A689715d092/info.json
  blockchains/ethereum/assets/0xa393473d64d2F9F026B60b6Df7859A689715d092/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4777 Add files via upload
  blockchains/ethereum/assets/0xa8B0F154A688c22142E361707df64277e0A0bE66/info.json
  blockchains/ethereum/assets/0xa8B0F154A688c22142E361707df64277e0A0bE66/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4678 Add Dango logo ( BEP20 Token )
  blockchains/smartchain/assets/0x0957C57C9EB7744850dCC95db5A06eD4a246236E/info.json
  blockchains/smartchain/assets/0x0957C57C9EB7744850dCC95db5A06eD4a246236E/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4830 Add Wormhole Finance Token Logo and Info
  blockchains/ethereum/assets/0xe6179bB571D2d69837bE731da88C76e377ec4738/info.json
  blockchains/ethereum/assets/0xe6179bB571D2d69837bE731da88C76e377ec4738/logo.png
Labels: Payment Status: Paid

#4861 feat: update dext dextools.io logo & info
  blockchains/ethereum/assets/0x26CE25148832C04f3d7F26F32478a9fe55197166/info.json
  blockchains/ethereum/assets/0x26CE25148832C04f3d7F26F32478a9fe55197166/logo.png
Labels: Payment Status: Paid

#4872 kava validator addition-anchorstaking
  blockchains/kava/validators/assets/kavavaloper195j72kgpuel75kwfpeu0kt7nc7rgzm47tytl7p/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#4873 Add Axion (AXN) (erc20)
  blockchains/ethereum/assets/0x7D85e23014F84E6E21d5663aCD8751bEF3562352/info.json
  blockchains/ethereum/assets/0x7D85e23014F84E6E21d5663aCD8751bEF3562352/logo.png
Labels: Payment Status: Paid

#4877 [internal] Allowlist: auto-allow only assets with both logo and info
  script/generic/allowlists.ts
Labels: Payment Status: Requested

#4881 OBRB update
  blockchains/smartchain/assets/0xe49ed1B44117BB7379c1506cf5815aE33089e1A7/info.json
  blockchains/smartchain/assets/0xe49ed1B44117BB7379c1506cf5815aE33089e1A7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4876 Missing images for tokens only
  blockchains/ethereum/assets/0x12513335ffD5DAfc2334e98625d27c1CA84bff86/logo.png
  blockchains/ethereum/assets/0x9Dfc4B433D359024Eb3E810d77d60fbE8B0d9B82/info.json
  blockchains/ethereum/assets/0x9Dfc4B433D359024Eb3E810d77d60fbE8B0d9B82/logo.png
  blockchains/smartchain/assets/0x3FdA9383A84C05eC8f7630Fe10AdF1fAC13241CC/info.json
  blockchains/smartchain/assets/0x3FdA9383A84C05eC8f7630Fe10AdF1fAC13241CC/logo.png
  blockchains/tron/assets/TN7zQd2oCCguSQykZ437tZzLEaGJ7EGyha/info.json
  blockchains/tron/assets/TN7zQd2oCCguSQykZ437tZzLEaGJ7EGyha/logo.png
Labels: Payment Status: Requested

#4891 Update GPYX logo and info
  blockchains/ethereum/assets/0xBC7F402F3bC1c6D56C8041F551b47a0AD7714D1b/info.json
  blockchains/ethereum/assets/0xBC7F402F3bC1c6D56C8041F551b47a0AD7714D1b/logo.png
Labels: Payment Status: Requested

#4894 add ERC20 CREAM
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4900 add BEP20 UNFI and BLINK
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x63870A18B6e42b01Ef1Ad8A2302ef50B7132054F/info.json
  blockchains/smartchain/assets/0x63870A18B6e42b01Ef1Ad8A2302ef50B7132054F/logo.png
  blockchains/smartchain/assets/0x728C5baC3C3e370E372Fc4671f9ef6916b814d8B/info.json
  blockchains/smartchain/assets/0x728C5baC3C3e370E372Fc4671f9ef6916b814d8B/logo.png
Labels: Payment Status: Requested

#4902 add ERC20 AXS and SLP to tokenlist
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#4899 Drakoin DRK Logo Upload
  blockchains/ethereum/assets/0x2369686fC9FB6E1fDc46541891568c2f341906eF/info.json
  blockchains/ethereum/assets/0x2369686fC9FB6E1fDc46541891568c2f341906eF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4850 Add KP2R
  blockchains/ethereum/assets/0x9BdE098Be22658d057C3F1F185e3Fd4653E2fbD1/info.json
  blockchains/ethereum/assets/0x9BdE098Be22658d057C3F1F185e3Fd4653E2fbD1/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4909 Added Ethereum Yield Logo
  blockchains/ethereum/assets/0xd1AFBCCC9A2c2187ea544363B986EA0AB6EF08B5/info.json
  blockchains/ethereum/assets/0xd1AFBCCC9A2c2187ea544363B986EA0AB6EF08B5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4911 add missing ERC20 images S3
  blockchains/ethereum/assets/0x0189d31F6629c359007f72B8D5Ec8Fa1C126f95c/logo.png
  blockchains/ethereum/assets/0x01995786f1435743C42B7f2276C496a610B58612/logo.png
  blockchains/ethereum/assets/0x0f801928106c4C4272275e130Be1473dBD8b492c/logo.png
  blockchains/ethereum/assets/0x13bDd7dcc28B585f193241B31995AF22f1b0256E/logo.png
  blockchains/ethereum/assets/0x1A1B161962a7EFE85BE39A24F18AD7d4a504e10C/logo.png
  blockchains/ethereum/assets/0x25a1DE1C3eE658FE034B8914a1D8d34110423AF8/logo.png
  blockchains/ethereum/assets/0x25e1474170c4c0aA64fa98123bdc8dB49D7802fa/logo.png
  blockchains/ethereum/assets/0x27BC53596Dc0EA71dE3c65C799d8E6c96C1dDA98/logo.png
  blockchains/ethereum/assets/0x3565402f2936D3284264F03615D065803330E392/logo.png
  blockchains/ethereum/assets/0x35dF7c5fB0Df360a6C9d26bC53b97C5f082b6A1C/logo.png
  blockchains/ethereum/assets/0x386dd8f88994f848763060672580Ea61676cD601/logo.png
  blockchains/ethereum/assets/0x4C9d5672Ae33522240532206Ab45508116daF263/logo.png
  blockchains/ethereum/assets/0x4F38f4229924bfa28D58eeda496Cc85e8016bCCC/logo.png
  blockchains/ethereum/assets/0x534c5EC7bF392d0B6b228EBEfBe3F6606a2b3484/logo.png
  blockchains/ethereum/assets/0x576097fA17E1F702bB9167f0f08F2eA0898a3EA5/logo.png
  blockchains/ethereum/assets/0x5D0fa08AEb173AdE44B0Cf7F31d506D8E04f0ac8/logo.png
  blockchains/ethereum/assets/0x6eab9C5e768C8C37e94dC236c6Cde7dbA4d0F3b3/logo.png
  blockchains/ethereum/assets/0x77D0112d005D21c1740A323F513bb088916B9A14/logo.png
  blockchains/ethereum/assets/0x7afA2BbC06Dad88487b5171EA2bcDF938A6b7Ff9/logo.png
  blockchains/ethereum/assets/0x825130Aa1bEeF07BdF4f389705321816D05b0d0f/logo.png
  blockchains/ethereum/assets/0x8377ee6d3545Bc6ff1425ee3015DC648B149C7B2/logo.png
  blockchains/ethereum/assets/0x85993bE4EF5BEc00B62BA7e46a8a70f353182b3e/logo.png
  blockchains/ethereum/assets/0x8888801aF4d980682e47f1A9036e589479e835C5/logo.png
  blockchains/ethereum/assets/0x8a0ba07B4358dE33eFecff2f09f55c85CDa14670/logo.png
  blockchains/ethereum/assets/0x8e57c27761EBBd381b0f9d09Bb92CeB51a358AbB/logo.png
  blockchains/ethereum/assets/0x9AA9F330aB322e8a6F044C46a109B5910fa373CE/logo.png
  blockchains/ethereum/assets/0xA5996f6b731B349E25d7d5F4Dd93A5CE9947841F/logo.png
  blockchains/ethereum/assets/0xA891CF72AEDa692570928eFe1A832342e9783CDC/logo.png
  blockchains/ethereum/assets/0xD375a513692336cF9eEBCE5e38869B447948016f/logo.png
  blockchains/ethereum/assets/0xDfF991Af459d05175B3bb766b950aFC697B68dF0/logo.png
  blockchains/ethereum/assets/0xE3a64A3c4216B83255b53Ec7eA078B13f21a7daD/logo.png
  blockchains/ethereum/assets/0xb810Ad9007E4F2d9Aab2e7181A0385d02437eA6e/logo.png
  blockchains/ethereum/assets/0xba7435A4b4C747E0101780073eedA872a69Bdcd4/logo.png
  blockchains/ethereum/assets/0xc92e74b131D7b1D46E60e07F3FaE5d8877Dd03F0/logo.png
  blockchains/ethereum/assets/0xce853db3359326dB6D03981C9fb42983BbCdd007/logo.png
  blockchains/ethereum/assets/0xd0834d08c83dbE216811AAea0EEfFb2349E57634/logo.png
Labels: Payment Status: Requested

#4913 add BEP20 missing images
  blockchains/smartchain/assets/0x009cF7bC57584b7998236eff51b98A168DceA9B0/logo.png
  blockchains/smartchain/assets/0x10747e2045a0ef884a0586AC81558F43285ea3c7/logo.png
  blockchains/smartchain/assets/0x4247aeB8E759e575Fe350921cD174C48df304F2A/logo.png
  blockchains/smartchain/assets/0x4d4e595d643dc61EA7FCbF12e4b1AAA39f9975B8/logo.png
  blockchains/smartchain/assets/0x897fE07d613037c206429628611A2665E18C657d/logo.png
  blockchains/smartchain/assets/0xDE4e179CC1d3b298216B96893767b9b01A6Bc413/logo.png
Labels: Payment Status: Requested

#4914 Add trc missing 11 22
  blockchains/tron/assets/1003406/logo.png
  blockchains/tron/assets/TJSBUFSe2E1Ncp5jo9ERD8LajjzpMa7F3C/logo.png
  blockchains/tron/assets/TMNyGQm6DxaaKxH2sSebScgRNsMgqANEzY/logo.png
Labels: Payment Status: Requested

#4917 add BEP20 AEDART and KING
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x4247aeB8E759e575Fe350921cD174C48df304F2A/info.json
  blockchains/smartchain/assets/0x4247aeB8E759e575Fe350921cD174C48df304F2A/logo.png
  blockchains/smartchain/assets/0xDE4e179CC1d3b298216B96893767b9b01A6Bc413/info.json
  blockchains/smartchain/assets/0xDE4e179CC1d3b298216B96893767b9b01A6Bc413/logo.png
Labels: Payment Status: Requested

#4818 Add ALPHA logos and info
  blockchains/ethereum/assets/0xa1faa113cbE53436Df28FF0aEe54275c13B40975/info.json
  blockchains/ethereum/assets/0xa1faa113cbE53436Df28FF0aEe54275c13B40975/logo.png
Labels: Payment Status: Requested

#4919 Add GIV token info for Binance Smart Chain
  blockchains/smartchain/assets/0xE49b84771470A87F4D9544685ea0F0517933B2B4/info.json
  blockchains/smartchain/assets/0xE49b84771470A87F4D9544685ea0F0517933B2B4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4814 Request to add "ICHI" and "oneETH" Tokens
  blockchains/ethereum/assets/0x6fcBBB527Fb2954BED2B224A5BB7c23C5AeEb6E1/info.json
  blockchains/ethereum/assets/0x6fcBBB527Fb2954BED2B224A5BB7c23C5AeEb6E1/logo.png
  blockchains/ethereum/assets/0x903bEF1736CDdf2A537176cf3C64579C3867A881/info.json
  blockchains/ethereum/assets/0x903bEF1736CDdf2A537176cf3C64579C3867A881/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4921 [Internal] Add ETH BEP20 in the Smartchain tokenlist
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#4910 Add bROOBEE token information
  blockchains/smartchain/assets/0xE64F5Cb844946C1F102Bd25bBD87a5aB4aE89Fbe/info.json
  blockchains/smartchain/assets/0xE64F5Cb844946C1F102Bd25bBD87a5aB4aE89Fbe/logo.png
Labels: Payment Status: Paid

#4923 add QUSD and KUN
  blockchains/ethereum/assets/0x59d4CCC94A9C4C3d3b4bA2Aa343a9bDF95145DD1/info.json
  blockchains/ethereum/assets/0x59d4CCC94A9C4C3d3b4bA2Aa343a9bDF95145DD1/logo.png
  blockchains/ethereum/assets/0x65d9bC970aA9B2413027fA339F7f179B3F3f2604/info.json
  blockchains/ethereum/assets/0x65d9bC970aA9B2413027fA339F7f179B3F3f2604/logo.png
  blockchains/smartchain/assets/0x1A2fb0Af670D0234c2857FaD35b789F8Cb725584/info.json
  blockchains/smartchain/assets/0x1A2fb0Af670D0234c2857FaD35b789F8Cb725584/logo.png
  blockchains/smartchain/assets/0xb8C540d00dd0Bf76ea12E4B4B95eFC90804f924E/info.json
  blockchains/smartchain/assets/0xb8C540d00dd0Bf76ea12E4B4B95eFC90804f924E/logo.png
Labels: Payment Status: Paid

#4922 CUB Coin Image Change
  blockchains/ethereum/assets/0x7A12a550cC13cE7c38c40a58465BfbB55D1EdC36/info.json
  blockchains/ethereum/assets/0x7A12a550cC13cE7c38c40a58465BfbB55D1EdC36/logo.png
Labels: Payment Status: Paid

#4657 Add TKNT
  blockchains/ethereum/assets/0xbcE7BD79558dda90B261506768f265c5543A9f90/info.json
  blockchains/ethereum/assets/0xbcE7BD79558dda90B261506768f265c5543A9f90/logo.png
Labels: Payment Status: Paid

#4906 Add PlotX Info and Logo
  blockchains/ethereum/assets/0x72F020f8f3E8fd9382705723Cd26380f8D0c66Bb/info.json
  blockchains/ethereum/assets/0x72F020f8f3E8fd9382705723Cd26380f8D0c66Bb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4944 Add ENB token
  blockchains/ethereum/assets/0xa6FB1DF483b24EEAB569e19447E0e107003B9E15/info.json
  blockchains/ethereum/assets/0xa6FB1DF483b24EEAB569e19447E0e107003B9E15/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4932 change address of LCT
  blockchains/ethereum/assets/0xFc178d0F36ddd2B44f925EB13bF51f5cB9B42192/info.json
  blockchains/ethereum/assets/0xFc178d0F36ddd2B44f925EB13bF51f5cB9B42192/logo.png
Labels: Payment Status: Paid
