Repository trustwallet/assets, pull requests merged in 2020-10, with the labels that each got.

#4229 Add YOLK logo and info
  blockchains/ethereum/assets/0xa54A6767aFdd9e1d3Cb9045FC9612ABBF3DA0DE9/info.json
  blockchains/ethereum/assets/0xa54A6767aFdd9e1d3Cb9045FC9612ABBF3DA0DE9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4097 add tomoe logo
  blockchains/ethereum/assets/0x05D3606d5c81EB9b7B18530995eC9B29da05FaBa/info.json
  blockchains/ethereum/assets/0x05D3606d5c81EB9b7B18530995eC9B29da05FaBa/logo.png
  blockchains/ethereum/assets/0xB1f66997A5760428D3a87D68b90BfE0aE64121cC/info.json
  blockchains/ethereum/assets/0xB1f66997A5760428D3a87D68b90BfE0aE64121cC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested, Status: On Hold

#4237 del_ERC-20_10-01-2020
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x25a1DE1C3eE658FE034B8914a1D8d34110423AF8/logo.png
  blockchains/ethereum/assets/0x27BC53596Dc0EA71dE3c65C799d8E6c96C1dDA98/logo.png
  blockchains/ethereum/assets/0x85993bE4EF5BEc00B62BA7e46a8a70f353182b3e/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4182 Added Propel info.json
  blockchains/binance/assets/PROPEL-6D9/info.json
  blockchains/binance/assets/PROPEL-6D9/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#4222 Adding InBit Token Logo
  blockchains/ethereum/assets/0x9c12d9b1223130B641154d8d3DB35F91D81c8dfd/info.json
  blockchains/ethereum/assets/0x9c12d9b1223130B641154d8d3DB35F91D81c8dfd/logo.png
Labels: Payment Status: Requested

#4258 Add YFFS logo and info
  blockchains/ethereum/assets/0x90D702f071d2af33032943137AD0aB4280705817/info.json
  blockchains/ethereum/assets/0x90D702f071d2af33032943137AD0aB4280705817/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4256 Add TAVITT token logo
  blockchains/ethereum/assets/0xdd690D8824c00C84d64606FFb12640e932C1AF56/info.json
  blockchains/ethereum/assets/0xdd690D8824c00C84d64606FFb12640e932C1AF56/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3718 Add TIMERS (IPM) token Logo and info.json
  blockchains/ethereum/assets/0x8fEEf860E9fA9326ff9d7E0058F637bE8579Cc29/info.json
  blockchains/ethereum/assets/0x8fEEf860E9fA9326ff9d7E0058F637bE8579Cc29/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4269 Update Logo for SHARE and add logos for EUR/EUR Share
  blockchains/ethereum/assets/0x39795344CBCc76cC3Fb94B9D1b15C23c2070C66D/logo.png
  blockchains/ethereum/assets/0x6898F926b74251e71eD0a8D894Bb45FEfF2E40FD/info.json
  blockchains/ethereum/assets/0x6898F926b74251e71eD0a8D894Bb45FEfF2E40FD/logo.png
  blockchains/ethereum/assets/0xFF440aE0Bb96ee0C6a024E9D9BDb9face23ceC6b/info.json
  blockchains/ethereum/assets/0xFF440aE0Bb96ee0C6a024E9D9BDb9face23ceC6b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4274 Add YFFC logo and info
  blockchains/ethereum/assets/0xea004e8FA3701B8E58E41b78D50996e0f7176CbD/info.json
  blockchains/ethereum/assets/0xea004e8FA3701B8E58E41b78D50996e0f7176CbD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4257 Add $YFDOT
  blockchains/ethereum/assets/0x2e6539edc3b76f1E21B71d214527FAbA875F70F3/info.json
  blockchains/ethereum/assets/0x2e6539edc3b76f1E21B71d214527FAbA875F70F3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4255 Add NOIA Network logo and info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca/info.json
  blockchains/ethereum/assets/0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca/logo.png
  blockchains/wanchain/allowlist.json
  blockchains/wanchain/denylist.json
Labels: Payment Status: Paid, Payment Status: Requested

#4271 Remove old WOM Token and Add new WOM Token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xBd356a39BFf2cAda8E9248532DD879147221Cf76/info.json
  blockchains/ethereum/assets/0xBd356a39BFf2cAda8E9248532DD879147221Cf76/logo.png
  blockchains/ethereum/assets/0xa982B2e19e90b2D9F7948e9C1b65D119F1CE88D6/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Paid, Payment Status: Requested

#4252 logo Yearn Land
  blockchains/ethereum/assets/0xd0658324074D6249a51876438916f7C423075451/info.json
  blockchains/ethereum/assets/0xd0658324074D6249a51876438916f7C423075451/logo.png
Labels: Payment Status: Paid

#4272 Update MOAR logo
  blockchains/ethereum/assets/0xBf131dCbE3436dab8a7c82D9C3666d652ca38eaB/info.json
  blockchains/ethereum/assets/0xBf131dCbE3436dab8a7c82D9C3666d652ca38eaB/logo.png
Labels: Payment Status: Paid

#4250 Please add WAXE ERC Token by https://wax.io/
  blockchains/ethereum/assets/0x7a2Bc711E19ba6aff6cE8246C546E8c4B4944DFD/info.json
  blockchains/ethereum/assets/0x7a2Bc711E19ba6aff6cE8246C546E8c4B4944DFD/logo.png
Labels: Payment Status: Paid

#4251 Please add WAXG ERC Token by https://wax.io/
  blockchains/ethereum/assets/0xb140A429c342083E97Daf42d5D82634bd7Ade7d4/info.json
  blockchains/ethereum/assets/0xb140A429c342083E97Daf42d5D82634bd7Ade7d4/logo.png
Labels: Payment Status: Paid

#4227 Update BGTT logo
  blockchains/ethereum/assets/0x7a545Ed3863221A974F327199Ac22F7f12535F11/info.json
  blockchains/ethereum/assets/0x7a545Ed3863221A974F327199Ac22F7f12535F11/logo.png
Labels: Payment Status: Paid

#4247 Add ZPAE trc20 (already paid)
  blockchains/tron/assets/TLGd97zsjrkomUDF962ZFMerdQxPffG7hX/info.json
  blockchains/tron/assets/TLGd97zsjrkomUDF962ZFMerdQxPffG7hX/logo.png
Labels: Payment Status: Paid

#4266 add DEUS logo token
  blockchains/ethereum/assets/0x3b62F3820e0B035cc4aD602dECe6d796BC325325/info.json
  blockchains/ethereum/assets/0x3b62F3820e0B035cc4aD602dECe6d796BC325325/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4286 Add Denarii (ARI) Logo
  blockchains/ethereum/assets/0x8A8b5318d3A59fa6D1d0A83A1B0506f2796b5670/info.json
  blockchains/ethereum/assets/0x8A8b5318d3A59fa6D1d0A83A1B0506f2796b5670/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4287 Add Yearn Finance Passive Income
  blockchains/ethereum/assets/0x05D27CdD23E22ca63e7f9c7C6D1B79ede9C4fCF5/info.json
  blockchains/ethereum/assets/0x05D27CdD23E22ca63e7f9c7C6D1B79ede9C4fCF5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4281 Add Stabilize.Finance ERC20 Logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xB987D48Ed8f2C468D52D6405624EADBa5e76d723/info.json
  blockchains/ethereum/assets/0xB987D48Ed8f2C468D52D6405624EADBa5e76d723/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4204 CentFi Token Info and Official Logo
  blockchains/ethereum/assets/0x4ae63e92ddA9072Fc47bfffD623737Fc736533F9/info.json
  blockchains/ethereum/assets/0x4ae63e92ddA9072Fc47bfffD623737Fc736533F9/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4280 Add YFOX Logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x706CB9E741CBFee00Ad5b3f5ACc8bd44D1644a74/info.json
  blockchains/ethereum/assets/0x706CB9E741CBFee00Ad5b3f5ACc8bd44D1644a74/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4295 Added YNK
  blockchains/ethereum/assets/0x87C00817ABe35eD4C093e59043fae488238d2F74/info.json
  blockchains/ethereum/assets/0x87C00817ABe35eD4C093e59043fae488238d2F74/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4292 Add DEPAY token information
  blockchains/ethereum/assets/0xa0bEd124a09ac2Bd941b10349d8d224fe3c955eb/info.json
  blockchains/ethereum/assets/0xa0bEd124a09ac2Bd941b10349d8d224fe3c955eb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4289 add minereum logo and info
  blockchains/ethereum/assets/0x426CA1eA2406c07d75Db9585F22781c096e3d0E0/info.json
  blockchains/ethereum/assets/0x426CA1eA2406c07d75Db9585F22781c096e3d0E0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4278 MilkyWayToken: added descriptions and logo
  blockchains/ethereum/assets/0x80c8C3dCfB854f9542567c8Dac3f44D709eBc1de/info.json
  blockchains/ethereum/assets/0x80c8C3dCfB854f9542567c8Dac3f44D709eBc1de/logo.png
Labels: Payment Status: Paid

#4307 New VIDT Datalink ERC20 contract address
  blockchains/ethereum/assets/0xfeF4185594457050cC9c23980d301908FE057Bb1/info.json
  blockchains/ethereum/assets/0xfeF4185594457050cC9c23980d301908FE057Bb1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4306 Add VIDT Datalink BEP20
  blockchains/ethereum/assets/0x3f515f0a8e93F2E2f891ceeB3Db4e62e202d7110/info.json
  blockchains/ethereum/assets/0x3f515f0a8e93F2E2f891ceeB3Db4e62e202d7110/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4302 add smol
  blockchains/ethereum/assets/0x2216e873ea4282EbEf7A02aC5aeA220bE6391A7C/info.json
  blockchains/ethereum/assets/0x2216e873ea4282EbEf7A02aC5aeA220bE6391A7C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4303 Add YFED Logo & Info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x2DBd330bC9B7f3A822a9173aB52172BdDDcAcE2A/info.json
  blockchains/ethereum/assets/0x2DBd330bC9B7f3A822a9173aB52172BdDDcAcE2A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4312 Add IYF.finance logo
  blockchains/ethereum/assets/0x5D762F76b9E91F71cc4F94391BDFe6333dB8519c/info.json
  blockchains/ethereum/assets/0x5D762F76b9E91F71cc4F94391BDFe6333dB8519c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4311 Add LEAD logo and info page
  blockchains/ethereum/assets/0x1dD80016e3d4ae146Ee2EBB484e8edD92dacC4ce/info.json
  blockchains/ethereum/assets/0x1dD80016e3d4ae146Ee2EBB484e8edD92dacC4ce/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4288 Updated MYST address
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x4Cf89ca06ad997bC732Dc876ed2A7F26a9E7f361/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4316 Add support for Ethereum and Binance Chain
  blockchains/binance/tokenlist.json
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
  script/generic/repo-structure.ts
Labels: Payment Status: Requested

#4317 raven protocol logo and info added for binance smartchain
  blockchains/smartchain/assets/0xcD7C5025753a49f1881B31C48caA7C517Bb46308/info.json
  blockchains/smartchain/assets/0xcD7C5025753a49f1881B31C48caA7C517Bb46308/logo.png
Labels: Payment Status: Requested

#4309 SquirrelFinance token logo addition
  blockchains/ethereum/assets/0x84294FC9710e1252d407d3D80A84bC39001bd4A8/info.json
  blockchains/ethereum/assets/0x84294FC9710e1252d407d3D80A84bC39001bd4A8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4339 Add info and logo for INDEX
  blockchains/ethereum/assets/0x0954906da0Bf32d5479e25f46056d22f08464cab/info.json
  blockchains/ethereum/assets/0x0954906da0Bf32d5479e25f46056d22f08464cab/logo.png
Labels: Payment Status: Requested

#4343 Add OWL logo and info
  blockchains/ethereum/assets/0x2a7f709eE001069771ceB6D42e85035f7D18E736/info.json
  blockchains/ethereum/assets/0x2a7f709eE001069771ceB6D42e85035f7D18E736/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4322 replaced logo with 512x512 and better crop
  blockchains/ethereum/assets/0x6369c3DadfC00054A42BA8B2c09c48131dd4Aa38/logo.png
Labels: Payment Status: Requested

#4338 Add DFT.P logo and info
  blockchains/ethereum/assets/0x8c9d8f5CC3427F460e20F63b36992f74AA19e27d/info.json
  blockchains/ethereum/assets/0x8c9d8f5CC3427F460e20F63b36992f74AA19e27d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4333 New social money logos from Roll
  blockchains/ethereum/assets/0x116a790417c31Ab790436A519D1C1F3353Edd4a2/logo.png
  blockchains/ethereum/assets/0x443dC1c35cf812156C840Fe90639836C8a7371b0/logo.png
  blockchains/ethereum/assets/0x63A2CcD492E316EEFAB5B3326dB3C7b0a94c3726/logo.png
  blockchains/ethereum/assets/0x7DE580D247D0f5d72c522b2750089E18f26e1cF9/logo.png
  blockchains/ethereum/assets/0x7d91e637589EC3Bb54D8213a9e92Dc6E8D12da91/logo.png
  blockchains/ethereum/assets/0xA7925aA2A6e4575ab0C74D169f3BC3e03D4C319A/logo.png
  blockchains/ethereum/assets/0xAf162491C0B21900C01F4Cc0F7110238AAcdebE7/logo.png
  blockchains/ethereum/assets/0xDDa8AE425F50eC838b73E9DA6C75D5B01D1f642E/logo.png
  blockchains/ethereum/assets/0xDd8A49180E44806Bd56873bda359C1115F7E98b5/logo.png
  blockchains/ethereum/assets/0xF7dEaF8f20546880cE40441c7bF47733006af98c/logo.png
  blockchains/ethereum/assets/0xcE8089fF023dF2db04b56d2d5156681144a86b82/logo.png
  blockchains/ethereum/assets/0xf42De14aBbdA1244D66b12387cb87fC91EfcFE85/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4324 ShakeToken Added
  blockchains/ethereum/assets/0x6006FC2a849fEdABa8330ce36F5133DE01F96189/info.json
  blockchains/ethereum/assets/0x6006FC2a849fEdABa8330ce36F5133DE01F96189/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4320 Request to add Clover Token and Logo
  blockchains/ethereum/assets/0x22222C03318440305aC3e8a7820563d6A9FD777F/info.json
  blockchains/ethereum/assets/0x22222C03318440305aC3e8a7820563d6A9FD777F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4318 Add Aavegotchi logo
  dapps/aavegotchi.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#4331 Add KATANA logo and info
  blockchains/ethereum/assets/0xe6410569602124506658Ff992F258616Ea2D4A3D/info.json
  blockchains/ethereum/assets/0xe6410569602124506658Ff992F258616Ea2D4A3D/logo.png
Labels: Payment Status: Paid

#4332 Add POX trc20 token logo
  blockchains/tron/assets/TMnqP8yuZrKJFXN59KoVDthkmM3LRkiZXP/info.json
  blockchains/tron/assets/TMnqP8yuZrKJFXN59KoVDthkmM3LRkiZXP/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4345 Add FREE coin
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x12e34cDf6A031a10FE241864c32fB03a4FDaD739/info.json
  blockchains/smartchain/assets/0x12e34cDf6A031a10FE241864c32fB03a4FDaD739/logo.png
Labels: Payment Status: Requested

#4344 Add Testa Token Logo
  blockchains/ethereum/assets/0x1da65B1868e2d36d06d7A44DBD2Be98e49E1f7f9/info.json
  blockchains/ethereum/assets/0x1da65B1868e2d36d06d7A44DBD2Be98e49E1f7f9/logo.png
Labels: Payment Status: Requested, Status: More Info / Change Requested

#4098 Add TLN info and logo
  blockchains/ethereum/assets/0x679131F591B4f369acB8cd8c51E68596806c3916/info.json
  blockchains/ethereum/assets/0x679131F591B4f369acB8cd8c51E68596806c3916/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4328 Listing Wrapped Assets of EcoCelium DeFi
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x08cE027e68e7F12818C862faB14CFFE5B9C606FE/info.json
  blockchains/ethereum/assets/0x08cE027e68e7F12818C862faB14CFFE5B9C606FE/logo.png
  blockchains/ethereum/assets/0x2ACFf9cc74B104CD8540E9a2F691f22d3BD924d7/info.json
  blockchains/ethereum/assets/0x2ACFf9cc74B104CD8540E9a2F691f22d3BD924d7/logo.png
  blockchains/ethereum/assets/0x63c9c6BBb3C1dC7769512fD7a9ED49226bEf52f7/info.json
  blockchains/ethereum/assets/0x63c9c6BBb3C1dC7769512fD7a9ED49226bEf52f7/logo.png
  blockchains/ethereum/assets/0x91600b412A68F2CB7c0FeD48A70127CC75341DBa/info.json
  blockchains/ethereum/assets/0x91600b412A68F2CB7c0FeD48A70127CC75341DBa/logo.png
  blockchains/ethereum/assets/0xD1b8D649Ba4C65Fdc382515E27E3B470Dc9a0585/info.json
  blockchains/ethereum/assets/0xD1b8D649Ba4C65Fdc382515E27E3B470Dc9a0585/logo.png
  blockchains/ethereum/assets/0xa37cb0e224A6D57e636185D65AF9b97c3E940303/info.json
  blockchains/ethereum/assets/0xa37cb0e224A6D57e636185D65AF9b97c3E940303/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#4347 Add PowerTrade fuel assets
  blockchains/ethereum/assets/0xC57d533c50bC22247d49a368880fb49a1caA39F7/info.json
  blockchains/ethereum/assets/0xC57d533c50bC22247d49a368880fb49a1caA39F7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4354 update ERC20 RNDR
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x6De037ef9aD2725EB40118Bb1702EBb27e4Aeb24/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4340 Add BiffysLove (LOVE) Asset
  blockchains/ethereum/assets/0xf7F35Fe2ede3aDDee7Cf176f4Ef20D9436E498dc/info.json
  blockchains/ethereum/assets/0xf7F35Fe2ede3aDDee7Cf176f4Ef20D9436E498dc/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested, Status: On Hold

#4336 add hxro
  blockchains/ethereum/assets/0x4bD70556ae3F8a6eC6C4080A0C327B24325438f3/info.json
  blockchains/ethereum/assets/0x4bD70556ae3F8a6eC6C4080A0C327B24325438f3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4358 Add YFARM logo and info
  blockchains/ethereum/assets/0xF5D0FefAaB749d8B14C27F0De60cC6e9e7f848d1/info.json
  blockchains/ethereum/assets/0xF5D0FefAaB749d8B14C27F0De60cC6e9e7f848d1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4285 add Rebase logo on update version contract
  blockchains/ethereum/assets/0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF/info.json
  blockchains/ethereum/assets/0x87F5F9eBE40786D49D35E1B5997b07cCAA8ADbFF/logo.png
Labels: Payment Status: Paid

#4364 adding ERC20 AAVE
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/info.json
  blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/logo.png
Labels: Payment Status: Requested

#4365 PARSIQ Token Swap
  blockchains/ethereum/assets/0x362bc847A3a9637d3af6624EeC853618a43ed7D2/info.json
  blockchains/ethereum/assets/0x362bc847A3a9637d3af6624EeC853618a43ed7D2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4366 Updated Inlock logo, added info
  blockchains/ethereum/assets/0xF784682C82526e245F50975190EF0fff4E4fC077/info.json
  blockchains/ethereum/assets/0xF784682C82526e245F50975190EF0fff4E4fC077/logo.png
Labels: Payment Status: Requested

#4359 phoswap.io logo
  dapps/Phoswap.io.png
Labels: Payment Status: Requested, Status: Correction needed

#4363 Add TEAM logo
  blockchains/ethereum/assets/0xb05AF453011d7ad68a92b0065FFD9d1277eD2741/info.json
  blockchains/ethereum/assets/0xb05AF453011d7ad68a92b0065FFD9d1277eD2741/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4370 Add kfc token logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xE63684BcF2987892CEfB4caA79BD21b34e98A291/info.json
  blockchains/ethereum/assets/0xE63684BcF2987892CEfB4caA79BD21b34e98A291/logo.png
Labels: Payment Status: Paid

#3522 Add cryptochrome
  blockchains/ethereum/assets/0x538a151Dd910C1D1227719bd400D6C4f99ea06d0/info.json
  blockchains/ethereum/assets/0x538a151Dd910C1D1227719bd400D6C4f99ea06d0/logo.png
  dapps/cryptochrome.org.png
Labels: Payment Status: Paid, Payment Status: Requested

#4373 added Tapcoin logo and info
  blockchains/ethereum/assets/0x9F599410D207f3D2828a8712e5e543AC2E040382/info.json
  blockchains/ethereum/assets/0x9F599410D207f3D2828a8712e5e543AC2E040382/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4375 Remove legacy bsc folder
  blockchains/bsc/allowlist.json
  blockchains/bsc/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/info.json
  blockchains/bsc/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/logo.png
  blockchains/bsc/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/info.json
  blockchains/bsc/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/logo.png
  blockchains/bsc/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/info.json
  blockchains/bsc/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/logo.png
  blockchains/bsc/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/info.json
  blockchains/bsc/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/logo.png
  blockchains/bsc/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/info.json
  blockchains/bsc/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/logo.png
  blockchains/bsc/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/info.json
  blockchains/bsc/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/logo.png
  blockchains/bsc/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/info.json
  blockchains/bsc/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/logo.png
  blockchains/bsc/assets/0x55d398326f99059fF775485246999027B3197955/info.json
  blockchains/bsc/assets/0x55d398326f99059fF775485246999027B3197955/logo.png
  blockchains/bsc/assets/0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6/info.json
  blockchains/bsc/assets/0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6/logo.png
  blockchains/bsc/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/info.json
  blockchains/bsc/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/logo.png
  blockchains/bsc/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/info.json
  blockchains/bsc/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/logo.png
  blockchains/bsc/assets/0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf/info.json
  blockchains/bsc/assets/0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf/logo.png
  blockchains/bsc/assets/0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18/info.json
  blockchains/bsc/assets/0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18/logo.png
  blockchains/bsc/assets/0xE4Ae305ebE1AbE663f261Bc00534067C80ad677C/info.json
  blockchains/bsc/assets/0xE4Ae305ebE1AbE663f261Bc00534067C80ad677C/logo.png
  blockchains/bsc/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/bsc/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/logo.png
  blockchains/bsc/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/info.json
  blockchains/bsc/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/logo.png
  blockchains/bsc/assets/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c/info.json
  blockchains/bsc/assets/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c/logo.png
  blockchains/bsc/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/info.json
  blockchains/bsc/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/logo.png
  blockchains/bsc/denylist.json
  blockchains/bsc/info/info.json
  blockchains/bsc/info/logo.png
  script/generic/blockchains.ts
Labels: Payment Status: Requested

#4376 Add RLE token informations
  blockchains/tron/assets/TDXJ1dSPLsN52jhP32NvVyhQ5X265BNU5c/info.json
  blockchains/tron/assets/TDXJ1dSPLsN52jhP32NvVyhQ5X265BNU5c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4377 added DHT logo and details
  blockchains/ethereum/assets/0xca1207647Ff814039530D7d35df0e1Dd2e91Fa84/info.json
  blockchains/ethereum/assets/0xca1207647Ff814039530D7d35df0e1Dd2e91Fa84/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4379 Add DiFy.Finance logo and info
  blockchains/ethereum/assets/0x4be40bc9681D0A7C24A99b4c92F85B9053Fc2A45/info.json
  blockchains/ethereum/assets/0x4be40bc9681D0A7C24A99b4c92F85B9053Fc2A45/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4356 Add New Token LIMIT
  blockchains/ethereum/assets/0x1712Aad2C773ee04bdC9114b32163c058321CD85/info.json
  blockchains/ethereum/assets/0x1712Aad2C773ee04bdC9114b32163c058321CD85/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4382 add thugs token
  blockchains/smartchain/assets/0xE10e9822A5de22F8761919310DDA35CD997d63c0/info.json
  blockchains/smartchain/assets/0xE10e9822A5de22F8761919310DDA35CD997d63c0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4381 add logo and info
  blockchains/smartchain/assets/0xef5CeB00AE3eb617773016B4ca886b61FA4e027E/info.json
  blockchains/smartchain/assets/0xef5CeB00AE3eb617773016B4ca886b61FA4e027E/logo.png
Labels: Payment Status: Paid

#4385 modify ERC20 KAI
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xD9Ec3ff1f8be459Bb9369b4E79e9Ebcf7141C093/info.json
  blockchains/ethereum/assets/0xD9Ec3ff1f8be459Bb9369b4E79e9Ebcf7141C093/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4383 Update list.json
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#4384 Add QCORE.FINANCE (QCORE) Logo & Info
  blockchains/ethereum/assets/0x82866b4A71BA9d930Fe338C386B6A45a7133eb36/info.json
  blockchains/ethereum/assets/0x82866b4A71BA9d930Fe338C386B6A45a7133eb36/logo.png
Labels: Payment Status: Paid

#4402 modify ERC20 NOIA
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xfc858154C0b2c4A3323046Fb505811F110EBdA57/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4403 added info for fry.world
  blockchains/smartchain/assets/0x393B312C01048b3ed2720bF1B090084C09e408A1/info.json
  blockchains/smartchain/assets/0x393B312C01048b3ed2720bF1B090084C09e408A1/logo.png
Labels: Payment Status: Paid

#4405 adding BEP20 assets 10/12
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x4824A7b64E3966B0133f4f4FFB1b9D6bEb75FFF7/info.json
  blockchains/ethereum/assets/0xA91ac63D040dEB1b7A5E4d4134aD23eb0ba07e14/info.json
  blockchains/ethereum/assets/0xA91ac63D040dEB1b7A5E4d4134aD23eb0ba07e14/logo.png
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8/info.json
  blockchains/smartchain/assets/0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8/logo.png
  blockchains/smartchain/assets/0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350/info.json
  blockchains/smartchain/assets/0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350/logo.png
  blockchains/smartchain/assets/0x8443f091997f06a61670B735ED92734F5628692F/info.json
  blockchains/smartchain/assets/0x8443f091997f06a61670B735ED92734F5628692F/logo.png
  blockchains/smartchain/assets/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5/info.json
  blockchains/smartchain/assets/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5/logo.png
  blockchains/smartchain/assets/0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44/info.json
  blockchains/smartchain/assets/0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44/logo.png
  blockchains/smartchain/assets/0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9/info.json
  blockchains/smartchain/assets/0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9/logo.png
Labels: Payment Status: Requested

#4393 YFIM
  blockchains/ethereum/assets/0x2e2f3246b6c65CCc4239c9Ee556EC143a7E5DE2c/info.json
  blockchains/ethereum/assets/0x2e2f3246b6c65CCc4239c9Ee556EC143a7E5DE2c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4409 Add Logo and Info XUNII
  blockchains/ethereum/assets/0x5a50B3d55e9a1089029824a26caaA8f2abFC4bb0/info.json
  blockchains/ethereum/assets/0x5a50B3d55e9a1089029824a26caaA8f2abFC4bb0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4401 add DEA token logo and info
  blockchains/ethereum/assets/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778/info.json
  blockchains/ethereum/assets/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4413 remove ERC20 BCD
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x31126416F0dbC1283DC5295EE6ea04Ff83eE3531/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4414 Unipumper patch 1
  blockchains/ethereum/assets/0x04B5E13000C6e9A3255Dc057091F3e3Eeee7b0f0/info.json
  blockchains/ethereum/assets/0x04B5E13000C6e9A3255Dc057091F3e3Eeee7b0f0/logo.png
Labels: Payment Status: Paid

#4416 New DEXTF logo
  blockchains/ethereum/assets/0x5F64Ab1544D28732F0A24F4713c2C8ec0dA089f0/info.json
  blockchains/ethereum/assets/0x5F64Ab1544D28732F0A24F4713c2C8ec0dA089f0/logo.png
Labels: Payment Status: Requested

#4420 [internal] Merge-fee-bot: Refresh message, lower TWT amount to 250
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#4421 Add MXX Token
  blockchains/ethereum/assets/0x8a6f3BF52A26a21531514E23016eEAe8Ba7e7018/info.json
  blockchains/ethereum/assets/0x8a6f3BF52A26a21531514E23016eEAe8Ba7e7018/logo.png
Labels: Payment Status: Paid

#4428 Add token list support for pairs on binance chain
  blockchains/binance/tokenlist.json
  package-lock.json
  package.json
  script/blockchain/binance.ts
  script/config.ts
  script/generic/allowlists.ts
  script/generic/asset.ts
  script/generic/numbers.ts
  script/generic/tokenlists.ts
  script/generic/update-all.ts
  test/asset.test.ts
  test/numbers.test.ts
Labels: Payment Status: Requested

#4427 Adding Beefy.finance files
  blockchains/smartchain/assets/0xCa3F508B8e4Dd382eE878A314789373D80A5190A/info.json
  blockchains/smartchain/assets/0xCa3F508B8e4Dd382eE878A314789373D80A5190A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4424 Update Value Logo & information
  blockchains/ethereum/assets/0x49E833337ECe7aFE375e44F4E3e8481029218E5c/info.json
  blockchains/ethereum/assets/0x49E833337ECe7aFE375e44F4E3e8481029218E5c/logo.png
Labels: Payment Status: Paid

#4433 [internal] Revert BNB fee option removal
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#4436 Update YFV & vUSD & vETH logo
  blockchains/ethereum/assets/0x1B8E12F839BD4e73A47adDF76cF7F0097d74c14C/info.json
  blockchains/ethereum/assets/0x1B8E12F839BD4e73A47adDF76cF7F0097d74c14C/logo.png
  blockchains/ethereum/assets/0x45f24BaEef268BB6d63AEe5129015d69702BCDfa/info.json
  blockchains/ethereum/assets/0x45f24BaEef268BB6d63AEe5129015d69702BCDfa/logo.png
  blockchains/ethereum/assets/0x76A034e76Aa835363056dd418611E4f81870f16e/info.json
  blockchains/ethereum/assets/0x76A034e76Aa835363056dd418611E4f81870f16e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4426 Add JNTR/e token logo & info for Jointer website.
  blockchains/ethereum/assets/0x1368452Bfb5Cd127971C8DE22C58fBE89D35A6BF/info.json
  blockchains/ethereum/assets/0x1368452Bfb5Cd127971C8DE22C58fBE89D35A6BF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4341 wANATHA logo add
  blockchains/ethereum/assets/0x3383c5a8969Dc413bfdDc9656Eb80A1408E4bA20/info.json
  blockchains/ethereum/assets/0x3383c5a8969Dc413bfdDc9656Eb80A1408E4bA20/logo.png
Labels: Payment Status: Paid

#4443 modify ERC20 FET
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85/info.json
  blockchains/ethereum/assets/0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4438 Add logo for UniLend Finance Token ($UFT)
  blockchains/ethereum/assets/0x0202Be363B8a4820f3F4DE7FaF5224fF05943AB1/info.json
  blockchains/ethereum/assets/0x0202Be363B8a4820f3F4DE7FaF5224fF05943AB1/logo.png
Labels: Payment Status: Paid

#4451 xETH info and logo
  blockchains/ethereum/assets/0xaA19673aA1b483a5c4f73B446B4f851629a7e7D6/info.json
  blockchains/ethereum/assets/0xaA19673aA1b483a5c4f73B446B4f851629a7e7D6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4439 Adding CXN Network
  blockchains/ethereum/assets/0xb48E0F69e6A3064f5498D495F77AD83e0874ab28/info.json
  blockchains/ethereum/assets/0xb48E0F69e6A3064f5498D495F77AD83e0874ab28/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4445 add SWAG.Finance logo
  blockchains/ethereum/assets/0x87eDfFDe3E14c7a66c9b9724747a1C5696b742e6/info.json
  blockchains/ethereum/assets/0x87eDfFDe3E14c7a66c9b9724747a1C5696b742e6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4446 Add CNTR logo and info
  blockchains/ethereum/assets/0x03042482d64577A7bdb282260e2eA4c8a89C064B/info.json
  blockchains/ethereum/assets/0x03042482d64577A7bdb282260e2eA4c8a89C064B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4442 ADD Unistake Logo & Info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x9Ed8e7C9604790F7Ec589F99b94361d8AAB64E5E/info.json
  blockchains/ethereum/assets/0x9Ed8e7C9604790F7Ec589F99b94361d8AAB64E5E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4449 update jamm logo
  blockchains/ethereum/assets/0x56687cf29Ac9751Ce2a4E764680B6aD7E668942e/info.json
  blockchains/ethereum/assets/0x56687cf29Ac9751Ce2a4E764680B6aD7E668942e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4454 Please add VIDTC smart contract
  blockchains/ethereum/assets/0xE0bA1564A889f0d2Ba8eF4978027C1b072b56EbB/info.json
  blockchains/ethereum/assets/0xE0bA1564A889f0d2Ba8eF4978027C1b072b56EbB/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4491 Add Dracula Protocol logo and ingo
  blockchains/ethereum/assets/0xb78B3320493a4EFaa1028130C5Ba26f0B6085Ef8/info.json
  blockchains/ethereum/assets/0xb78B3320493a4EFaa1028130C5Ba26f0B6085Ef8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4472 Axia Protocol Token Logo and Info
  blockchains/ethereum/assets/0x793786e2dd4Cc492ed366a94B88a3Ff9ba5E7546/info.json
  blockchains/ethereum/assets/0x793786e2dd4Cc492ed366a94B88a3Ff9ba5E7546/logo.png
Labels: Payment Status: Paid

#4505 modify ERC20 PRE
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xEC213F83defB583af3A000B1c0ada660b1902A0F/info.json
  blockchains/ethereum/assets/0xEC213F83defB583af3A000B1c0ada660b1902A0F/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4450 Add DGTX info and logo
  blockchains/ethereum/assets/0xc666081073E8DfF8D3d1c2292A29aE1A2153eC09/info.json
  blockchains/ethereum/assets/0xc666081073E8DfF8D3d1c2292A29aE1A2153eC09/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4453 New Abyss Token logo
  blockchains/ethereum/assets/0x0E8d6b471e332F140e7d9dbB99E5E3822F728DA6/info.json
  blockchains/ethereum/assets/0x0E8d6b471e332F140e7d9dbB99E5E3822F728DA6/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4465 Add Seal Finance Assets
  blockchains/ethereum/assets/0x33c2DA7Fd5B125E629B3950f3c38d7f721D7B30D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4469 PRIA - Token logo and information submission
  blockchains/ethereum/assets/0xb9871cB10738eADA636432E86FC0Cb920Dc3De24/info.json
  blockchains/ethereum/assets/0xb9871cB10738eADA636432E86FC0Cb920Dc3De24/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4460 Add Hermez Network Token (HEZ) Logo and Info
  blockchains/ethereum/assets/0xEEF9f339514298C6A857EfCfC1A762aF84438dEE/info.json
  blockchains/ethereum/assets/0xEEF9f339514298C6A857EfCfC1A762aF84438dEE/logo.png
Labels: Payment Status: Paid

#4502 Upload Logo USF
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x31733F69232Bdb189934B54A18Ab9bDe5144E74d/info.json
  blockchains/ethereum/assets/0x31733F69232Bdb189934B54A18Ab9bDe5144E74d/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4516 [internal] Revert "Upload Logo USF (#4502)"
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x31733F69232Bdb189934B54A18Ab9bDe5144E74d/info.json
  blockchains/ethereum/assets/0x31733F69232Bdb189934B54A18Ab9bDe5144E74d/logo.png
Labels: Payment Status: Requested

#4500 New vi info
  blockchains/ethereum/assets/0x8b6c3b7C01D9dB4393f9aa734750F36df1543E9A/info.json
  blockchains/ethereum/assets/0x8b6c3b7C01D9dB4393f9aa734750F36df1543E9A/logo.png
Labels: Payment Status: Requested

#4489 Add Swirge coin logo and info
  blockchains/ethereum/assets/0x92eF4FFBfe0Df030837b65d7FcCFE1ABd6549579/info.json
  blockchains/ethereum/assets/0x92eF4FFBfe0Df030837b65d7FcCFE1ABd6549579/logo.png
Labels: Payment Status: Paid

#4519 Add Void Reserve Currency
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xB65aA347A28d40039f62F3a488c9FD2799cB5a95/info.json
  blockchains/ethereum/assets/0xB65aA347A28d40039f62F3a488c9FD2799cB5a95/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4524 [internal] Assets checks: Info.json check for every chain (was for eth forks only).
  blockchains/tron/assets/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC/info.json
  script/generic/asset-info.ts
  script/generic/asset-infos.ts
  script/generic/eth-forks.ts
  script/generic/folders-and-files.ts
  script/generic/logo-size.ts
  script/generic/repo-structure.ts
  script/generic/update-all.ts
Labels: Payment Status: Requested

#4534 add ERC20 YFIIS
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x32F3b9B5Bd6C76F41ee3B389573f340468666861/info.json
  blockchains/ethereum/assets/0x32F3b9B5Bd6C76F41ee3B389573f340468666861/logo.png
Labels: Payment Status: Requested

#3963 Add HUB Token
  blockchains/ethereum/assets/0x4790f605CBDBa5fCe4F209868B5A05B3bFf7272c/info.json
  blockchains/ethereum/assets/0x4790f605CBDBa5fCe4F209868B5A05B3bFf7272c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4513 ZinFinance
  blockchains/ethereum/assets/0x033e223870f766644f7f7a4B7dc2E91573707d06/info.json
  blockchains/ethereum/assets/0x033e223870f766644f7f7a4B7dc2E91573707d06/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4526 IYFI token logo
  blockchains/ethereum/assets/0x251B5C9eFf2d9F04DC525f601E13293bfE40E4f5/info.json
  blockchains/ethereum/assets/0x251B5C9eFf2d9F04DC525f601E13293bfE40E4f5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4522 Add Pull The Rug
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xEdFBd6c48c3dDfF5612Ade14B45bb19F916809ba/info.json
  blockchains/ethereum/assets/0xEdFBd6c48c3dDfF5612Ade14B45bb19F916809ba/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4537 Add UXT logo and info
  blockchains/ethereum/assets/0x27824111DD062Ca9062067B493Fbf512328928BA/info.json
  blockchains/ethereum/assets/0x27824111DD062Ca9062067B493Fbf512328928BA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4536 Updated Tokenomy logo
  blockchains/ethereum/assets/0xDD16eC0F66E54d453e6756713E533355989040E4/info.json
  blockchains/ethereum/assets/0xDD16eC0F66E54d453e6756713E533355989040E4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4530 ADD FIN Token Logo
  blockchains/ethereum/assets/0x054f76beED60AB6dBEb23502178C52d6C5dEbE40/info.json
  blockchains/ethereum/assets/0x054f76beED60AB6dBEb23502178C52d6C5dEbE40/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4517 Add SSL Token Logo
  blockchains/ethereum/assets/0x0d9227f9c4ab3972f994FCcC6EeBa3213C0305c4/info.json
  blockchains/ethereum/assets/0x0d9227f9c4ab3972f994FCcC6EeBa3213C0305c4/logo.png
Labels: Payment Status: Paid

#4462 VIDTC NFT's for Binance Smart Chain (3 addresses)
  blockchains/smartchain/assets/0x0567D7fad179dCd2a89508B77cCe93E26f8998F7/info.json
  blockchains/smartchain/assets/0x0567D7fad179dCd2a89508B77cCe93E26f8998F7/logo.png
  blockchains/smartchain/assets/0x7A2172F3728962F6B952a1Cc1AD794DACbf9f3DA/info.json
  blockchains/smartchain/assets/0x7A2172F3728962F6B952a1Cc1AD794DACbf9f3DA/logo.png
  blockchains/smartchain/assets/0x7B7D3B71A12906270b1b4c187C75f45188E9aEf6/info.json
  blockchains/smartchain/assets/0x7B7D3B71A12906270b1b4c187C75f45188E9aEf6/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested, Status: On Hold

#4531 UniDark Logo
  blockchains/ethereum/assets/0xafB43414e6344f6310f29e9D7dc95D817ffd89E8/info.json
  blockchains/ethereum/assets/0xafB43414e6344f6310f29e9D7dc95D817ffd89E8/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#4553 [internal] Add two assets retrieved from Binance chain, after manual resize
  blockchains/binance/assets/INJ-FAE/logo.png
  blockchains/binance/assets/YFI-1A4/logo.png
Labels: Payment Status: Requested

#4549 NFY logo and info
  blockchains/ethereum/assets/0x1cBb83EbcD552D5EBf8131eF8c9CD9d9BAB342bC/info.json
  blockchains/ethereum/assets/0x1cBb83EbcD552D5EBf8131eF8c9CD9d9BAB342bC/logo.png
Labels: Payment Status: Paid

#4545 Add PAYT logo and info
  blockchains/ethereum/assets/0x8EF47555856f6Ce2E0cd7C36AeF4FAb317d2e2E2/info.json
  blockchains/ethereum/assets/0x8EF47555856f6Ce2E0cd7C36AeF4FAb317d2e2E2/logo.png
Labels: Payment Status: Paid

#4551 adding BOND (BarnBridge) logo and info
  blockchains/ethereum/assets/0x0391D2021f89DC339F60Fff84546EA23E337750f/info.json
  blockchains/ethereum/assets/0x0391D2021f89DC339F60Fff84546EA23E337750f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4539 Add KORE
  blockchains/ethereum/assets/0xA866F0198208Eb07c83081d5136BE7f775c2399e/info.json
  blockchains/ethereum/assets/0xA866F0198208Eb07c83081d5136BE7f775c2399e/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#3725 Add logo files via upload
  blockchains/ethereum/assets/0x33D0568941C0C64ff7e0FB4fbA0B11BD37deEd9f/info.json
  blockchains/ethereum/assets/0x33D0568941C0C64ff7e0FB4fbA0B11BD37deEd9f/logo.png
Labels: Payment Status: Paid

#4558 remove_ERC20_ESH_old
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xDf329603BD378021698f9833cD5205b52F9E370e/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4560 Update our new BHC logo
  blockchains/ethereum/assets/0x32e3298939D56D0bb0dA5BD20dE8b589FF5e1B57/logo.png
  blockchains/ethereum/denylist.json
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/info.json
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/logo.png
Labels: Payment Status: Paid

#4564 [internal] Remove scam-suspect UniDark, #4531
  blockchains/ethereum/assets/0xafB43414e6344f6310f29e9D7dc95D817ffd89E8/info.json
  blockchains/ethereum/assets/0xafB43414e6344f6310f29e9D7dc95D817ffd89E8/logo.png
Labels: Payment Status: Requested

#4566 [internal] Refine explorerUrl check, fix existing warnings.
  blockchains/ethereum/assets/0x03042482d64577A7bdb282260e2eA4c8a89C064B/info.json
  blockchains/ethereum/assets/0xB63B606Ac810a52cCa15e44bB630fd42D8d1d83d/info.json
  blockchains/ethereum/assets/0xD9Ec3ff1f8be459Bb9369b4E79e9Ebcf7141C093/info.json
  blockchains/ethereum/assets/0xE41d2489571d322189246DaFA5ebDe1F4699F498/info.json
  blockchains/ethereum/assets/0xbbFF862d906E348E9946Bfb2132ecB157Da3D4b4/info.json
  blockchains/ethereum/assets/0xbe038A2FDfec62Cf1beD852f141A43005035edcC/info.json
  blockchains/neo/assets/2efdb22c152896964665d0a8214dc7bd59232162/info.json
  blockchains/neo/assets/bac0d143a547dc66a1d6a2b7d66b06de42614971/info.json
  script/generic/asset-infos.ts
Labels: Payment Status: Requested

#4556 Add BPLC token logo
  blockchains/ethereum/assets/0x426FC8BE95573230f6e6bc4af91873F0c67b21b4/info.json
  blockchains/ethereum/assets/0x426FC8BE95573230f6e6bc4af91873F0c67b21b4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4567 Upload Cashback
  blockchains/ethereum/assets/0xA8eC2B2F021B55d7d594c8d12Bbd6d23C05245D7/info.json
  blockchains/ethereum/assets/0xA8eC2B2F021B55d7d594c8d12Bbd6d23C05245D7/logo.png
Labels: Payment Status: Requested

#4573 [TokenList] Binance tokens list
  blockchains/binance/tokenlist.json
  blockchains/ethereum/tokenlist.json
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#4574 Add ARCD logo and info
  blockchains/ethereum/assets/0xb581E3a7dB80fBAA821AB39342E9Cbfd2ce33c23/info.json
  blockchains/ethereum/assets/0xb581E3a7dB80fBAA821AB39342E9Cbfd2ce33c23/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4548 Add Pazzi to Trustwallet
  blockchains/ethereum/assets/0xf2D4A5dd017d78289C404DE98c37cE245e417C7f/info.json
  blockchains/ethereum/assets/0xf2D4A5dd017d78289C404DE98c37cE245e417C7f/logo.png
Labels: Payment Status: Paid

#4575 add drugstoken
  blockchains/smartchain/assets/0xfD26889cd6454D8751562f1c0FcF88b18B46F7B7/info.json
  blockchains/smartchain/assets/0xfD26889cd6454D8751562f1c0FcF88b18B46F7B7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4559 submit dapp png
  blockchains/smartchain/assets/0x393B312C01048b3ed2720bF1B090084C09e408A1/info.json
  dapps/fry.world.png
Labels: Payment Status: Paid, Payment Status: Requested

#4561 Add Go9tro Logo
  blockchains/ethereum/assets/0x556237E86Df9325017c330E295c13A6c7d0E71a7/info.json
  blockchains/ethereum/assets/0x556237E86Df9325017c330E295c13A6c7d0E71a7/logo.png
Labels: Payment Status: Requested, Status: More Info / Change Requested

#4576 Please add DRC logo and information (JSON file name is updated)
  blockchains/ethereum/assets/0xa150Db9b1Fa65b44799d4dD949D922c0a33Ee606/info.json
  blockchains/ethereum/assets/0xa150Db9b1Fa65b44799d4dD949D922c0a33Ee606/logo.png
Labels: Payment Status: Requested

#4572 ANTISEAL Logo and Informations
  blockchains/ethereum/assets/0xE95e4440493E5b96e79D63E8Dc43AB676Dd44E4C/info.json
  blockchains/ethereum/assets/0xE95e4440493E5b96e79D63E8Dc43AB676Dd44E4C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4568 Cropped logo.png
  blockchains/ethereum/assets/0x426FC8BE95573230f6e6bc4af91873F0c67b21b4/info.json
  blockchains/ethereum/assets/0x426FC8BE95573230f6e6bc4af91873F0c67b21b4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
