Repository trustwallet/assets, pull requests merged in 2020-09, with the labels that each got.

#3706 add hbtc contract logo
  blockchains/ethereum/assets/0x0316EB71485b0Ab14103307bf65a021042c6d380/info.json
  blockchains/ethereum/assets/0x0316EB71485b0Ab14103307bf65a021042c6d380/logo.png
Labels: Payment Status: Requested

#3731 Add AMPLG token
  blockchains/ethereum/assets/0x8003C49f6ebACDdC493EA47CAB45e892d1B638a1/info.json
  blockchains/ethereum/assets/0x8003C49f6ebACDdC493EA47CAB45e892d1B638a1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Requested More Info

#3736 [internal] Binance validators: change dummy to a real validator
  blockchains/binance/validators/assets/bnb18cy9pjf3ym239w5qec0kkeuktyywx8wpq3jt0c/logo.png
  blockchains/binance/validators/assets/bva1r57gcwpa7f0slcef7z8jl7m50e2vmc854wnf7l/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#3719 Add StarCurve (XSTAR)
  blockchains/ethereum/assets/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f/info.json
  blockchains/ethereum/assets/0xC0E47007e084EEF3EE58eb33D777b3B4Ca98622f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3728 Add Swapfolio (SWFL) logo icon
  blockchains/ethereum/assets/0xBa21Ef4c9f433Ede00badEFcC2754B8E74bd538A/info.json
  blockchains/ethereum/assets/0xBa21Ef4c9f433Ede00badEFcC2754B8E74bd538A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Requested More Info

#3743 Com Token Update
  blockchains/ethereum/assets/0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF/info.json
  blockchains/ethereum/assets/0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3742 Adding WednesdayCoin info and logo
  blockchains/ethereum/assets/0x7848ae8F19671Dc05966dafBeFbBbb0308BDfAbD/info.json
  blockchains/ethereum/assets/0x7848ae8F19671Dc05966dafBeFbBbb0308BDfAbD/logo.png
Labels: Payment Status: Requested

#3744 Add DUCATO info and logo
  blockchains/ethereum/assets/0xa117ea1c0c85CEf648df2b6f40e50bb5475C228d/info.json
  blockchains/ethereum/assets/0xa117ea1c0c85CEf648df2b6f40e50bb5475C228d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3745 Add Binance Smart Chain logo
  blockchains/bsc/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3750 Add PWQ logo, #3730
  blockchains/ethereum/assets/0xa9241C6Bc2f536ddbedca8d95b83Af05988f6AFe/info.json
  blockchains/ethereum/assets/0xa9241C6Bc2f536ddbedca8d95b83Af05988f6AFe/logo.png
Labels: Payment Status: Requested

#3752 update design of bsc
  blockchains/bsc/info/logo.png
Labels: Payment Status: Requested

#3751 Add COIN files
  blockchains/ethereum/assets/0x69b9e58Dcc2680cf07c66399b7E50670F7452459/info.json
  blockchains/ethereum/assets/0x69b9e58Dcc2680cf07c66399b7E50670F7452459/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3746 Added logo and metadata for SHIB
  blockchains/ethereum/assets/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE/info.json
  blockchains/ethereum/assets/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3753 Add YFIVE.FINANCE
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xd3E8695d2Bef061EAb38B5EF526c0f714108119C/info.json
  blockchains/ethereum/assets/0xd3E8695d2Bef061EAb38B5EF526c0f714108119C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3755 Add files via upload
  blockchains/ethereum/assets/0x26E43759551333e57F073bb0772F50329A957b30/info.json
  blockchains/ethereum/assets/0x26E43759551333e57F073bb0772F50329A957b30/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3734 Add SBX
  blockchains/ethereum/assets/0xDaF8a0E12fc3b109A17ED5CbB943A8f3f86081f7/info.json
  blockchains/ethereum/assets/0xDaF8a0E12fc3b109A17ED5CbB943A8f3f86081f7/logo.png
Labels: Payment Status: Paid, Status: On Hold

#3733 DOGEFI - adding logo to UNISWAP
  blockchains/ethereum/assets/0x9B9087756eCa997C5D595C840263001c9a26646D/info.json
  blockchains/ethereum/assets/0x9B9087756eCa997C5D595C840263001c9a26646D/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#3787 Add support for BEP20 tokens
  blockchains/bsc/allowlist.json
  blockchains/bsc/denylist.json
  blockchains/bsc/info/info.json
  package-lock.json
  package.json
  script/common/blockchains.ts
Labels: Payment Status: Requested

#3786 Add grap token
  blockchains/ethereum/assets/0xC8D2AB2a6FdEbC25432E54941cb85b55b9f152dB/info.json
  blockchains/ethereum/assets/0xC8D2AB2a6FdEbC25432E54941cb85b55b9f152dB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3783 Add YFT.finance
  blockchains/ethereum/assets/0x26B3038a7Fc10b36c426846a9086Ef87328dA702/info.json
  blockchains/ethereum/assets/0x26B3038a7Fc10b36c426846a9086Ef87328dA702/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3781 add RCKT assets
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xbD03BD923c7D51019Fd84571D84e4eBcf7213509/info.json
  blockchains/ethereum/assets/0xbD03BD923c7D51019Fd84571D84e4eBcf7213509/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3771 Added correct Globitex Token Logo + info.json
  blockchains/ethereum/assets/0x12fCd6463E66974cF7bBC24FFC4d40d6bE458283/info.json
  blockchains/ethereum/assets/0x12fCd6463E66974cF7bBC24FFC4d40d6bE458283/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3782 ADD yfBEta Logo
  blockchains/ethereum/assets/0x89eE58Af4871b474c30001982c3D7439C933c838/info.json
  blockchains/ethereum/assets/0x89eE58Af4871b474c30001982c3D7439C933c838/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3796 adding LINK and USDT to BEP20 tokens
  blockchains/bsc/allowlist.json
  blockchains/bsc/assets/0x55d398326f99059fF775485246999027B3197955/info.json
  blockchains/bsc/assets/0x55d398326f99059fF775485246999027B3197955/logo.png
  blockchains/bsc/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/bsc/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/logo.png
Labels: Payment Status: Requested

#3805 Add GoMoney2 Logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x48783486ddD7fa85ECa6B0C4AE8920Bc25DfbcD7/info.json
  blockchains/ethereum/assets/0x48783486ddD7fa85ECa6B0C4AE8920Bc25DfbcD7/logo.png
Labels: Payment Status: Paid

#3790 add logo YFIBusiness.Finance (YFIB) to trust wallet
  blockchains/ethereum/assets/0x47632dA9227E322EDa59F9e7691eAcC6430Ac87C/info.json
  blockchains/ethereum/assets/0x47632dA9227E322EDa59F9e7691eAcC6430Ac87C/logo.png
Labels: Payment Status: Paid

#3789 ULU LOGO PR
  blockchains/ethereum/assets/0x035bfe6057E15Ea692c0DfdcaB3BB41a64Dd2aD4/info.json
  blockchains/ethereum/assets/0x035bfe6057E15Ea692c0DfdcaB3BB41a64Dd2aD4/logo.png
Labels: Payment Status: Paid

#3777 Update FLOW logo
  blockchains/ethereum/assets/0xC6e64729931f60D2c8Bc70A27D66D9E0c28D1BF9/info.json
  blockchains/ethereum/assets/0xC6e64729931f60D2c8Bc70A27D66D9E0c28D1BF9/logo.png
Labels: Payment Status: Paid

#3763 Add Rainbow
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x33c23d44679433A88B89ca38D3311A9a3D160699/info.json
  blockchains/ethereum/assets/0x33c23d44679433A88B89ca38D3311A9a3D160699/logo.png
Labels: Payment Status: Paid

#3822 Xiotri (XIOT) token logo
  blockchains/ethereum/assets/0x31024A4C3e9aEeb256B825790F5cb7ac645e7cD5/info.json
  blockchains/ethereum/assets/0x31024A4C3e9aEeb256B825790F5cb7ac645e7cD5/logo.png
Labels: Payment Status: Paid

#3810 Adding YIELD farming token
  blockchains/ethereum/assets/0x6768063279E2B185Dc0c972b97f11f231d0B45ad/info.json
  blockchains/ethereum/assets/0x6768063279E2B185Dc0c972b97f11f231d0B45ad/logo.png
Labels: Payment Status: Paid

#3804 Add logo for BREE
  blockchains/ethereum/assets/0x4639cd8cd52EC1CF2E496a606ce28D8AfB1C792F/info.json
  blockchains/ethereum/assets/0x4639cd8cd52EC1CF2E496a606ce28D8AfB1C792F/logo.png
Labels: Payment Status: Paid

#3774 added info
  blockchains/ethereum/assets/0x912B38134F395D1BFAb4C6F9db632C31667ACF98/info.json
  blockchains/ethereum/assets/0x912B38134F395D1BFAb4C6F9db632C31667ACF98/logo.png
Labels: Payment Status: Paid

#3791 Add QCASH logo create 0xe74b35425fe7e33ea190b149805baf31139a8290
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xE74B35425fE7E33EA190b149805baF31139a8290/info.json
  blockchains/ethereum/assets/0xE74B35425fE7E33EA190b149805baF31139a8290/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#3806 Logo for uSD (Unified Stable Dollar)
  blockchains/ethereum/assets/0x44086035439E676c02D411880FcCb9837CE37c57/info.json
  blockchains/ethereum/assets/0x44086035439E676c02D411880FcCb9837CE37c57/logo.png
Labels: Payment Status: Paid, Status: On Hold

#3840 [internal] Refine 'Closing' message by merge bot.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#3761 Add logo file for BTSE Token
  blockchains/ethereum/assets/0x666d875C600AA06AC1cf15641361dEC3b00432Ef/info.json
  blockchains/ethereum/assets/0x666d875C600AA06AC1cf15641361dEC3b00432Ef/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#3841 bXIOT logo and info
  blockchains/ethereum/assets/0x5c4ac68aAc56eBe098D621Cd8CE9F43270Aaa355/info.json
  blockchains/ethereum/assets/0x5c4ac68aAc56eBe098D621Cd8CE9F43270Aaa355/logo.png
Labels: Payment Status: Requested

#3838 JUL update
  blockchains/ethereum/assets/0x5580ab97F226C324c671746a1787524AEF42E415/info.json
  blockchains/ethereum/assets/0x5580ab97F226C324c671746a1787524AEF42E415/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3844 Harvest.Finance
  blockchains/ethereum/assets/0xa0246c9032bC3A600820415aE600c6388619A14D/info.json
  blockchains/ethereum/assets/0xa0246c9032bC3A600820415aE600c6388619A14D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3843 Add Swerve Finance
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xB8BAa0e4287890a5F79863aB62b7F175ceCbD433/info.json
  blockchains/ethereum/assets/0xB8BAa0e4287890a5F79863aB62b7F175ceCbD433/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3533 Add Zombie Logo/info/whitelist
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xd55BD2C12B30075b325Bc35aEf0B46363B3818f8/info.json
  blockchains/ethereum/assets/0xd55BD2C12B30075b325Bc35aEf0B46363B3818f8/logo.png
Labels: Payment Status: Paid, Status: On Hold

#3850 Added DeltaHub Capital Logo
  blockchains/ethereum/assets/0x152687Bc4A7FCC89049cF119F9ac3e5aCF2eE7ef/info.json
  blockchains/ethereum/assets/0x152687Bc4A7FCC89049cF119F9ac3e5aCF2eE7ef/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3853 [internal] Adjusments to bot message
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#3845 Adding COIN - Coin Artist token
  blockchains/ethereum/assets/0x87b008E57F640D94Ee44Fd893F0323AF933F9195/info.json
  blockchains/ethereum/assets/0x87b008E57F640D94Ee44Fd893F0323AF933F9195/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3813 Add Amp
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xfF20817765cB7f73d4bde2e66e067E58D11095C2/info.json
  blockchains/ethereum/assets/0xfF20817765cB7f73d4bde2e66e067E58D11095C2/logo.png
Labels: Payment Status: Paid

#3857 Exnt asset
  blockchains/ethereum/assets/0xD6c67B93a7b248dF608a653d82a100556144c5DA/info.json
  blockchains/ethereum/assets/0xD6c67B93a7b248dF608a653d82a100556144c5DA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3860 Add ZDEX logo in changed Smart contract
  blockchains/ethereum/assets/0x5150956E082C748Ca837a5dFa0a7C10CA4697f9c/info.json
  blockchains/ethereum/assets/0x5150956E082C748Ca837a5dFa0a7C10CA4697f9c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3858 New buidl logo
  blockchains/ethereum/assets/0x7b123f53421b1bF8533339BFBdc7C98aA94163db/info.json
  blockchains/ethereum/assets/0x7b123f53421b1bF8533339BFBdc7C98aA94163db/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3862 Add Treecle Logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x0a9d68886a0D7Db83a30ec00d62512483e5Ad437/info.json
  blockchains/ethereum/assets/0x0a9d68886a0D7Db83a30ec00d62512483e5Ad437/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3866 EXOLOVER (EXO) token's info and logo
  blockchains/ethereum/assets/0xE58E751abA3B9406367B5F3CbC39c2Fa9B519789/info.json
  blockchains/ethereum/assets/0xE58E751abA3B9406367B5F3CbC39c2Fa9B519789/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3870 Add YfDAI.finance
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xf4CD3d3Fda8d7Fd6C5a500203e38640A70Bf9577/info.json
  blockchains/ethereum/assets/0xf4CD3d3Fda8d7Fd6C5a500203e38640A70Bf9577/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3871 Block old ZDEX contract 0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#3868 gKIMCHI info update
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x4b7DfAe2567181E54776337C840e142ACb42AA1F/info.json
  blockchains/ethereum/assets/0x4b7DfAe2567181E54776337C840e142ACb42AA1F/logo.png
Labels: Payment Status: Paid

#3881 Add New Smart Chain
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x55d398326f99059fF775485246999027B3197955/info.json
  blockchains/smartchain/assets/0x55d398326f99059fF775485246999027B3197955/logo.png
  blockchains/smartchain/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/info.json
  blockchains/smartchain/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/logo.png
  blockchains/smartchain/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/smartchain/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/logo.png
  blockchains/smartchain/assets/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c/info.json
  blockchains/smartchain/assets/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c/logo.png
  blockchains/smartchain/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/info.json
  blockchains/smartchain/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/logo.png
  blockchains/smartchain/denylist.json
  blockchains/smartchain/info/info.json
  blockchains/smartchain/info/logo.png
  package-lock.json
  package.json
  script/common/blockchains.ts
Labels: Payment Status: Requested

#3875 Add Predix Network ($PRDX) to assets
  blockchains/ethereum/assets/0x556148562d5DdeB72545D7EC4B3eC8edc8F55Ba7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3873 Added BNSD Finance logos and info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x668DbF100635f593A3847c0bDaF21f0a09380188/info.json
  blockchains/ethereum/assets/0x668DbF100635f593A3847c0bDaF21f0a09380188/logo.png
  dapps/bns.finance.png
Labels: Payment Status: Paid, Payment Status: Requested

#3864 add logo for Perpetual Protocol Token (PERP)
  blockchains/ethereum/assets/0xbC396689893D065F41bc2C6EcbeE5e0085233447/info.json
  blockchains/ethereum/assets/0xbC396689893D065F41bc2C6EcbeE5e0085233447/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested, Status: On Hold

#3876 Add GRO token info and logo
  blockchains/ethereum/assets/0x09e64c2B61a5f1690Ee6fbeD9baf5D6990F8dFd0/info.json
  blockchains/ethereum/assets/0x09e64c2B61a5f1690Ee6fbeD9baf5D6990F8dFd0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3877 Add tixl
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41/info.json
  blockchains/ethereum/assets/0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3879 Please add logo to LOCK token !
  blockchains/ethereum/assets/0xB9464ef80880c5aeA54C7324c0b8Dd6ca6d05A90/info.json
  blockchains/ethereum/assets/0xB9464ef80880c5aeA54C7324c0b8Dd6ca6d05A90/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3891 [internal] Update dependencies
  package-lock.json
  package.json
Labels: Payment Status: Requested

#3892 Mark deprecated Zeedex logo with a red cross #3860
  blockchains/ethereum/assets/0x73DBbf72d427076BDd73CF905fDFc442c9C67D4a/logo.png
Labels: Payment Status: Requested

#3899 add Binance pegged BEP20 tokens
  blockchains/bsc/allowlist.json
  blockchains/bsc/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/info.json
  blockchains/bsc/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/logo.png
  blockchains/bsc/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/info.json
  blockchains/bsc/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/logo.png
  blockchains/bsc/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/info.json
  blockchains/bsc/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/logo.png
  blockchains/bsc/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/info.json
  blockchains/bsc/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/logo.png
  blockchains/bsc/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/info.json
  blockchains/bsc/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/logo.png
  blockchains/bsc/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/info.json
  blockchains/bsc/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/logo.png
  blockchains/bsc/assets/0x55d398326f99059fF775485246999027B3197955/info.json
  blockchains/bsc/assets/0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6/info.json
  blockchains/bsc/assets/0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6/logo.png
  blockchains/bsc/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/info.json
  blockchains/bsc/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/logo.png
  blockchains/bsc/assets/0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf/info.json
  blockchains/bsc/assets/0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf/logo.png
  blockchains/bsc/assets/0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18/info.json
  blockchains/bsc/assets/0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18/logo.png
  blockchains/bsc/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/bsc/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/info.json
  blockchains/bsc/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/logo.png
Labels: Payment Status: Requested

#3900 add DICE token (TRC20)
  blockchains/tron/allowlist.json
  blockchains/tron/assets/TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd/info.json
  blockchains/tron/assets/TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd/logo.png
Labels: Payment Status: Requested

#3902 Add peculium
  blockchains/ethereum/assets/0x0F02e27745e3b6e9e1310d19469e2b5D7B5eC99A/info.json
  blockchains/ethereum/assets/0x0F02e27745e3b6e9e1310d19469e2b5D7B5eC99A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3883 Added Shroom finance asset
  blockchains/ethereum/assets/0xEd0439EACf4c4965AE4613D77a5C2Efe10e5f183/info.json
  blockchains/ethereum/assets/0xEd0439EACf4c4965AE4613D77a5C2Efe10e5f183/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3906 Update logo icon
  blockchains/ethereum/assets/0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3887 Please add logo to MOON token !
  blockchains/ethereum/assets/0x68a3637bA6E75c0f66B61A42639c4e9fCD3D4824/info.json
  blockchains/ethereum/assets/0x68a3637bA6E75c0f66B61A42639c4e9fCD3D4824/logo.png
Labels: Payment Status: Paid, Status: On Hold

#3911 Add AllianceBlock ALBT token
  blockchains/ethereum/assets/0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0/info.json
  blockchains/ethereum/assets/0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0/logo.png
Labels: Payment Status: Requested

#3915 Add DPI logo
  blockchains/ethereum/assets/0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b/info.json
  blockchains/ethereum/assets/0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b/logo.png
Labels: Payment Status: Requested

#3926 remove ANY token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x582D4A3f546F130e29f0B29CCe6C654F7513e05F/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#3916 Add ASTRO logo & info
  blockchains/ethereum/assets/0xcbd55D4fFc43467142761A764763652b48b969ff/info.json
  blockchains/ethereum/assets/0xcbd55D4fFc43467142761A764763652b48b969ff/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3930 Dollar Protocol Add
  blockchains/ethereum/assets/0x6B583Cf4abA7Bf9d6f8A51B3F1F7C7B2ce59Bf15/info.json
  blockchains/ethereum/assets/0x6B583Cf4abA7Bf9d6f8A51B3F1F7C7B2ce59Bf15/logo.png
  blockchains/ethereum/assets/0xd233D1f6FD11640081aBB8db125f722b5dc729dc/info.json
  blockchains/ethereum/assets/0xd233D1f6FD11640081aBB8db125f722b5dc729dc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3917 Add PhoenixDAO Icon
  blockchains/ethereum/assets/0x38A2fDc11f526Ddd5a607C1F251C065f40fBF2f7/info.json
  blockchains/ethereum/assets/0x38A2fDc11f526Ddd5a607C1F251C065f40fBF2f7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#3927 Add ECO erc20 version token logo and info
  blockchains/ethereum/assets/0x191557728e4d8CAa4Ac94f86af842148c0FA8F7E/info.json
  blockchains/ethereum/assets/0x191557728e4d8CAa4Ac94f86af842148c0FA8F7E/logo.png
Labels: Payment Status: Requested

#3919 Add logo ZenFinance
  blockchains/ethereum/assets/0xB24f135C954b71B75dD413b288835b5a8d4AFa74/info.json
  blockchains/ethereum/assets/0xB24f135C954b71B75dD413b288835b5a8d4AFa74/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3957 adding Yield farming tokens BEP20
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x40929FB2008c830731A3d972950bC13f70161c75/info.json
  blockchains/smartchain/assets/0x40929FB2008c830731A3d972950bC13f70161c75/logo.png
  blockchains/smartchain/assets/0x8E9f5173e16Ff93F81579d73A7f9723324d6B6aF/info.json
  blockchains/smartchain/assets/0x8E9f5173e16Ff93F81579d73A7f9723324d6B6aF/logo.png
  blockchains/smartchain/assets/0xE02dF9e3e622DeBdD69fb838bB799E3F168902c5/info.json
  blockchains/smartchain/assets/0xE02dF9e3e622DeBdD69fb838bB799E3F168902c5/logo.png
  blockchains/smartchain/assets/0xaCd6b5f76Db153FB45EAE6D5be5BDbd45d1b2A8C/info.json
  blockchains/smartchain/assets/0xaCd6b5f76Db153FB45EAE6D5be5BDbd45d1b2A8C/logo.png
  blockchains/smartchain/assets/0xaF53d56ff99f1322515E54FdDE93FF8b3b7DAFd5/info.json
  blockchains/smartchain/assets/0xaF53d56ff99f1322515E54FdDE93FF8b3b7DAFd5/logo.png
Labels: Payment Status: Requested

#3950 Add xfi logo
  blockchains/ethereum/assets/0x5BEfBB272290dD5b8521D4a938f6c4757742c430/info.json
  blockchains/ethereum/assets/0x5BEfBB272290dD5b8521D4a938f6c4757742c430/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3809 Add files via upload
  blockchains/tron/assets/1003257/info.json
  blockchains/tron/assets/1003257/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested, Status: On Hold

#3956 Update MTL logo
  blockchains/ethereum/assets/0xF433089366899D83a9f26A773D59ec7eCF30355e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3959 Added Ofin Token Details
  blockchains/ethereum/assets/0x3b4cAAAF6F3ce5Bee2871C89987cbd825Ac30822/info.json
  blockchains/ethereum/assets/0x3b4cAAAF6F3ce5Bee2871C89987cbd825Ac30822/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3955 Add logo for Frontier Token ($FRONT)
  blockchains/ethereum/assets/0xf8C3527CC04340b208C854E985240c02F7B7793f/info.json
  blockchains/ethereum/assets/0xf8C3527CC04340b208C854E985240c02F7B7793f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#3976 chads.vc logo and info (fixed)
  blockchains/ethereum/assets/0x69692D3345010a207b759a7D1af6fc7F38b35c5E/info.json
  blockchains/ethereum/assets/0x69692D3345010a207b759a7D1af6fc7F38b35c5E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3967 Add FORS token logo and info
  blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/info.json
  blockchains/ethereum/assets/0xb1EC548F296270BC96B8A1b3b3C8F3f04b494215/logo.png
Labels: Payment Status: Requested

#3969 Add blocery #3964 (payed)
  blockchains/ethereum/assets/0xf8aD7dFe656188A23e89da09506Adf7ad9290D5d/info.json
  blockchains/ethereum/assets/0xf8aD7dFe656188A23e89da09506Adf7ad9290D5d/logo.png
Labels: Payment Status: Requested

#3942 Add logo for SAKE
  blockchains/ethereum/assets/0x066798d9ef0833ccc719076Dab77199eCbd178b0/info.json
  blockchains/ethereum/assets/0x066798d9ef0833ccc719076Dab77199eCbd178b0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3986 [internal] Mention token limits in Readme
  README.md
Labels: Payment Status: Requested

#3990 [internal] Checks: multiple errors from a check
  script/action/allowlists.ts
  script/action/binance.ts
  script/action/cosmos.ts
  script/action/eth-forks.ts
  script/action/folders-and-files.ts
  script/action/interface.ts
  script/action/json.ts
  script/action/kava.ts
  script/action/logo-size.ts
  script/action/terra.ts
  script/action/tezos.ts
  script/action/tron.ts
  script/action/update-all.ts
  script/action/validators.ts
  script/action/waves.ts
Labels: Payment Status: Requested

#3984 Adding assets for YMEN.finance token
  blockchains/ethereum/assets/0xd0c59798F986d333554688cD667033d469C2398e/info.json
  blockchains/ethereum/assets/0xd0c59798F986d333554688cD667033d469C2398e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3991 [internal] Check for existence of info.json files (warning only).
  script/action/folders-and-files.ts
  script/action/update-all.ts
Labels: Payment Status: Requested

#3992 [internal] Cleanup script-old.
  script-old/arrange_files.ts
  script-old/gen_info.ts
  script-old/helpers.ts
Labels: Payment Status: Requested

#3994 adding BEP20 tokens 09-16
  blockchains/ethereum/assets/0xa1d0E215a23d7030842FC67cE582a6aFa3CCaB83/info.json
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x0Eb3a705fc54725037CC9e008bDede697f62F335/info.json
  blockchains/smartchain/assets/0x0Eb3a705fc54725037CC9e008bDede697f62F335/logo.png
  blockchains/smartchain/assets/0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb/info.json
  blockchains/smartchain/assets/0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb/logo.png
  blockchains/smartchain/assets/0x7F70642d88cf1C4a3a7abb072B53B929b653edA5/info.json
  blockchains/smartchain/assets/0x7F70642d88cf1C4a3a7abb072B53B929b653edA5/logo.png
  blockchains/smartchain/assets/0xd4CB328A82bDf5f03eB737f37Fa6B370aef3e888/info.json
  blockchains/smartchain/assets/0xd4CB328A82bDf5f03eB737f37Fa6B370aef3e888/logo.png
  blockchains/smartchain/denylist.json
Labels: Payment Status: Requested

#4000 Yield Farming Known as Ash
  blockchains/ethereum/assets/0x4086692D53262b2Be0b13909D804F0491FF6Ec3e/info.json
  blockchains/ethereum/assets/0x4086692D53262b2Be0b13909D804F0491FF6Ec3e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4005 Add Elrond blockchain
  blockchains/elrond/info/info.json
  blockchains/elrond/info/logo.png
Labels: Payment Status: Requested

#3977 Add PICKLE logo and info
  blockchains/ethereum/assets/0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5/info.json
  blockchains/ethereum/assets/0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4006 Add UNI token and info
  blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/info.json
  blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/logo.png
Labels: Payment Status: Paid

#4012 [internal] Assisted external update, some BEP logos manually updated
  blockchains/binance/allowlist.json
  blockchains/binance/assets/ADA-9F4/logo.png
  blockchains/binance/assets/BAND-34B/logo.png
  blockchains/binance/assets/DAI-D75/logo.png
  blockchains/binance/assets/DOT-64C/logo.png
  blockchains/binance/assets/LINK-AAD/logo.png
  blockchains/binance/assets/TBC-3A7/logo.png
  blockchains/binance/assets/USDT-6D8/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#4011 ALBT white paper URL fix
  blockchains/ethereum/assets/0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0/info.json
Labels: Payment Status: Requested

#4018 add AVN logo
  dapps/avnrichdefi.com.png
  dapps/avnswap.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#4002 Requesting pull to add new tezos baker, Tezos Wake n' Bake
  blockchains/tezos/validators/assets/tz1WctSwL49BZtdWAQ75NY6vr4xsAx6oKdah/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#4008 Add Ystar
  blockchains/ethereum/assets/0xD9A947789974bAD9BE77E45C2b327174A9c59D71/info.json
  blockchains/ethereum/assets/0xD9A947789974bAD9BE77E45C2b327174A9c59D71/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3966 Add Creed Token
  blockchains/ethereum/assets/0x675E7d927Af7e6D0082e0153dc3485B687a6F0ad/info.json
  blockchains/ethereum/assets/0x675E7d927Af7e6D0082e0153dc3485B687a6F0ad/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4032 Add files via upload
  blockchains/ethereum/assets/0x4B4b1d389d4f4E082B30F75c6319c0CE5ACBd619/info.json
  blockchains/ethereum/assets/0x4B4b1d389d4f4E082B30F75c6319c0CE5ACBd619/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4026 BITTO
  blockchains/ethereum/assets/0x55a290f08Bb4CAe8DcF1Ea5635A3FCfd4Da60456/info.json
  blockchains/ethereum/assets/0x55a290f08Bb4CAe8DcF1Ea5635A3FCfd4Da60456/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4033 Remove old BITTO contract, 0xa101E27f06A97985B925E244111b61560Ecd97DB
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xa101E27f06A97985B925E244111b61560Ecd97DB/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4037 Update copy
  README.md
Labels: Payment Status: Requested

#4040 [internal] Set up Linting
  .eslintignore
  .eslintrc.js
  .github/workflows/check.yml
  .github/workflows/pr-ci.yml
  dangerfile.ts
  package-lock.json
  package.json
  script/action/allowlists.ts
  script/action/binance.ts
  script/action/cosmos.ts
  script/action/eth-forks.ts
  script/action/folders-and-files.ts
  script/action/json.ts
  script/action/kava.ts
  script/action/logo-size.ts
  script/action/terra.ts
  script/action/tezos.ts
  script/action/tron.ts
  script/action/update-all.ts
  script/action/validators.ts
  script/action/waves.ts
  script/common/asset-info.ts
  script/common/eth-web3.ts
  script/common/filesystem.ts
  script/common/image.ts
  script/common/json.ts
  script/common/repo-structure.ts
  script/common/types.ts
  script/config.ts
  script/main/check-sanity.ts
  script/main/check.ts
  script/main/fix-sanity.ts
  script/main/fix.ts
  script/main/update.ts
  test/index.test.ts
Labels: Payment Status: Requested

#4041 [internal] Remove warning for missing info.json (there are too many missing).
  script/action/folders-and-files.ts
Labels: Payment Status: Requested

#4042 adding ANKR BEP20
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xf307910A4c7bbc79691fD374889b36d8531B08e3/info.json
  blockchains/smartchain/assets/0xf307910A4c7bbc79691fD374889b36d8531B08e3/logo.png
Labels: Payment Status: Requested

#4066 Add logo and info for Eye of God (EOG) token.
  blockchains/ethereum/assets/0x8Ae6AE8F172d7fc103CCfa5890883d6fE46038C9/info.json
  blockchains/ethereum/assets/0x8Ae6AE8F172d7fc103CCfa5890883d6fE46038C9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4058 Soft Yearn Finance logo and info submission
  blockchains/ethereum/assets/0x322124122DF407b0d0D902cB713B3714FB2e2E1F/info.json
  blockchains/ethereum/assets/0x322124122DF407b0d0D902cB713B3714FB2e2E1F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4055 Update Token Contract Address + Logo + Info
  blockchains/ethereum/assets/0x1dA01e84F3d4e6716F274c987Ae4bEE5DC3C8288/info.json
  blockchains/ethereum/assets/0x1dA01e84F3d4e6716F274c987Ae4bEE5DC3C8288/logo.png
  blockchains/ethereum/assets/0x912B38134F395D1BFAb4C6F9db632C31667ACF98/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4050 ChartEx logo and info submission
  blockchains/ethereum/assets/0x1d37986F252d0e349522EA6C3B98Cb935495E63E/info.json
  blockchains/ethereum/assets/0x1d37986F252d0e349522EA6C3B98Cb935495E63E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4036 Logo removed and replaced by new one
  blockchains/ethereum/assets/0xA663121582725aA0eb8BF20B0F56F1917762e873/logo.png
  blockchains/ethereum/assets/0xd0c59798F986d333554688cD667033d469C2398e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3996 Update WALT Logo
  blockchains/ethereum/assets/0x15bCDFAd12498DE8a922E62442Ae4CC4bd33bd25/info.json
  blockchains/ethereum/assets/0x15bCDFAd12498DE8a922E62442Ae4CC4bd33bd25/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4025 added YFMS logo
  blockchains/ethereum/assets/0xfef3bEf71A5EB97E097039038776fD967ae5B106/info.json
  blockchains/ethereum/assets/0xfef3bEf71A5EB97E097039038776fD967ae5B106/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested, wontfix

#4062 Add HOUSE logo and info
  blockchains/ethereum/assets/0x19810559dF63f19cfE88923313250550eDADB743/info.json
  blockchains/ethereum/assets/0x19810559dF63f19cfE88923313250550eDADB743/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#4060 Add logo and info for HBTT token
  blockchains/ethereum/assets/0x43257DDCf6f22987062a7Dbe032Ffa67E4e0bB3a/info.json
  blockchains/ethereum/assets/0x43257DDCf6f22987062a7Dbe032Ffa67E4e0bB3a/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4068 Add OCTO logo and info
  blockchains/ethereum/assets/0x7240aC91f01233BaAf8b064248E80feaA5912BA3/info.json
  blockchains/ethereum/assets/0x7240aC91f01233BaAf8b064248E80feaA5912BA3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4069 yUSD logo and info submission
  blockchains/ethereum/assets/0x5dbcF33D8c2E976c6b560249878e6F1491Bca25c/info.json
  blockchains/ethereum/assets/0x5dbcF33D8c2E976c6b560249878e6F1491Bca25c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4015 Add Coti Logo
  blockchains/ethereum/assets/0xDDB3422497E61e13543BeA06989C0789117555c5/info.json
  blockchains/ethereum/assets/0xDDB3422497E61e13543BeA06989C0789117555c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4054 Please advise for adding EVC on your list
  blockchains/ethereum/assets/0xAa843f65872a25D6E9552eA0B360Fb1d5E333124/info.json
  blockchains/ethereum/assets/0xAa843f65872a25D6E9552eA0B360Fb1d5E333124/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4053 ff
  blockchains/ethereum/assets/0xab0bd01101877597C1360a82f515515FEb178B9E/info.json
  blockchains/ethereum/assets/0xab0bd01101877597C1360a82f515515FEb178B9E/logo.png
Labels: Payment Status: Paid

#4075 Add BRG and info
  blockchains/tron/assets/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC/info.json
  blockchains/tron/assets/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC/logo.png
Labels: Payment Status: Requested

#4095 Add LINA token info and logo
  blockchains/ethereum/assets/0x3E9BC21C9b189C09dF3eF1B824798658d5011937/info.json
  blockchains/ethereum/assets/0x3E9BC21C9b189C09dF3eF1B824798658d5011937/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: More Info / Change Requested

#4083 Add QHC
  blockchains/ethereum/assets/0x5df94780f00140FE72d239D0D261f7797E3Fbd1B/info.json
  blockchains/ethereum/assets/0x5df94780f00140FE72d239D0D261f7797E3Fbd1B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4077 Add logo + info SSJ the first "Item Token"
  blockchains/ethereum/assets/0xB4ae194a0DCF1B4080b164C1d775ee06E0817305/info.json
  blockchains/ethereum/assets/0xB4ae194a0DCF1B4080b164C1d775ee06E0817305/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4073 JULb update
  blockchains/bsc/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/info.json
  blockchains/bsc/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4048 add hatch logo
  blockchains/ethereum/assets/0x6F3009663470475F0749A6b76195375f95495fcB/info.json
  blockchains/ethereum/assets/0x6F3009663470475F0749A6b76195375f95495fcB/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4100 Add MINDS token
  blockchains/ethereum/assets/0xB26631c6dda06aD89B93C71400D25692de89c068/info.json
  blockchains/ethereum/assets/0xB26631c6dda06aD89B93C71400D25692de89c068/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4105 Update YFDAI logo
  blockchains/ethereum/assets/0xf4CD3d3Fda8d7Fd6C5a500203e38640A70Bf9577/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4084 Add MaggotToken and RottenToken
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x163c754eF4D9C03Fc7Fa9cf6Dd43bFc760E6Ce89/info.json
  blockchains/ethereum/assets/0x163c754eF4D9C03Fc7Fa9cf6Dd43bFc760E6Ce89/logo.png
  blockchains/ethereum/assets/0xD04785C4d8195e4A54d9dEc3a9043872875ae9E2/info.json
  blockchains/ethereum/assets/0xD04785C4d8195e4A54d9dEc3a9043872875ae9E2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#3952 Read This Contract (RTC) ecosystem assets
  blockchains/ethereum/assets/0x3ac2AB91dDF57e2385089202Ca221C360CED0062/info.json
  blockchains/ethereum/assets/0x3ac2AB91dDF57e2385089202Ca221C360CED0062/logo.png
  blockchains/ethereum/assets/0x59AD6061A0be82155E7aCcE9F0C37Bf59F9c1e3C/info.json
  blockchains/ethereum/assets/0x59AD6061A0be82155E7aCcE9F0C37Bf59F9c1e3C/logo.png
  blockchains/ethereum/assets/0x7f9A00E03c2E53A3aF6031C17A150DBeDaAab3dC/info.json
  blockchains/ethereum/assets/0x7f9A00E03c2E53A3aF6031C17A150DBeDaAab3dC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4109 Added Morpher (MPH) Logo in 256x256 and info.json
  blockchains/ethereum/assets/0x6369c3DadfC00054A42BA8B2c09c48131dd4Aa38/info.json
  blockchains/ethereum/assets/0x6369c3DadfC00054A42BA8B2c09c48131dd4Aa38/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4114 [internal] Add Atom (binance) logo, with correct size.
  blockchains/binance/assets/ATOM-596/logo.png
Labels: Payment Status: Requested

#4070 [internal] Script restructuring/refactoring
  dangerfile.ts
  package.json
  script/blockchain/binance.ts
  script/blockchain/cosmos.ts
  script/blockchain/kava.ts
  script/blockchain/terra.ts
  script/blockchain/tezos.ts
  script/blockchain/tron.ts
  script/blockchain/waves.ts
  script/entrypoint/check-sanity.ts
  script/entrypoint/check.ts
  script/entrypoint/fix-sanity.ts
  script/entrypoint/fix.ts
  script/entrypoint/update.ts
  script/generic/allowlists.ts
  script/generic/asset-info.ts
  script/generic/blockchains.ts
  script/generic/eth-forks.ts
  script/generic/eth-web3.ts
  script/generic/filesystem.ts
  script/generic/folders-and-files.ts
  script/generic/image.ts
  script/generic/interface.ts
  script/generic/json-format.ts
  script/generic/json.ts
  script/generic/logo-size.ts
  script/generic/repo-structure.ts
  script/generic/types.ts
  script/generic/update-all.ts
  script/generic/validator-models.ts
  script/generic/validators.ts
  test/index.test.ts
Labels: Payment Status: Requested

#4115 remove NTN
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x3a4a5E27Fc28D32f50dd9774a42F489214109811/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#4120 kSEED
  blockchains/ethereum/assets/0x3F09400313e83d53366147e3ea0e4e2279D80850/info.json
  blockchains/ethereum/assets/0x3F09400313e83d53366147e3ea0e4e2279D80850/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4044 add realio.fund RIO erc20 token
  blockchains/ethereum/assets/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097/info.json
  blockchains/ethereum/assets/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097/logo.png
Labels: Payment Status: Paid, Status: On Hold

#4104 Add yTSLA logo and info
  blockchains/ethereum/assets/0x5322A3556F979cE2180B30e689a9436fDDCB1021/info.json
  blockchains/ethereum/assets/0x5322A3556F979cE2180B30e689a9436fDDCB1021/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4125 [internal] Update Morpher logo #4124
  blockchains/ethereum/assets/0x6369c3DadfC00054A42BA8B2c09c48131dd4Aa38/logo.png
Labels: Payment Status: Requested

#4126 SaTT token submission
  blockchains/ethereum/assets/0xDf49C9f599A0A9049D97CFF34D0C30E468987389/info.json
  blockchains/ethereum/assets/0xDf49C9f599A0A9049D97CFF34D0C30E468987389/logo.png
Labels: Payment Status: Paid

#4131 Add BHC
  blockchains/bsc/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/info.json
  blockchains/bsc/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/logo.png
Labels: Payment Status: Requested

#4110 CAT Token Logo
  blockchains/ethereum/assets/0x56015BBE3C01fE05bc30A8a9a9Fd9A88917e7dB3/info.json
  blockchains/ethereum/assets/0x56015BBE3C01fE05bc30A8a9a9Fd9A88917e7dB3/logo.png
Labels: Payment Status: Paid

#4134 Add xBTC.
  blockchains/ethereum/assets/0xECbF566944250ddE88322581024E611419715f7A/info.json
  blockchains/ethereum/assets/0xECbF566944250ddE88322581024E611419715f7A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#4121 ARTT Logo
  blockchains/ethereum/assets/0x77dF79539083DCd4a8898dbA296d899aFef20067/info.json
  blockchains/ethereum/assets/0x77dF79539083DCd4a8898dbA296d899aFef20067/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#4141 [internal] Move over updated/new tokens from bsc folder to smartchain; issue #4140
  blockchains/smartchain/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/logo.png
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/info.json
  blockchains/smartchain/assets/0xA6381C6Fd8f40A44721eF4f61eDc1a8CCCa7BF3d/logo.png
Labels: Payment Status: Requested

#3968 Add FNSP logo and info
  blockchains/ethereum/assets/0x3B78dc5736a49BD297Dd2E4d62daA83D35A22749/info.json
  blockchains/ethereum/assets/0x3B78dc5736a49BD297Dd2E4d62daA83D35A22749/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#4142 Add new logo
  blockchains/ethereum/assets/0xc84F7ABE4904ee4f20a8c5dFA3cC4BF1829330AB/info.json
  blockchains/ethereum/assets/0xc84F7ABE4904ee4f20a8c5dFA3cC4BF1829330AB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
