Repository trustwallet/assets, pull requests merged in 2021-04, with the labels that each got.

#6160 Add Everlasting Parachain (BEP20)
  blockchains/smartchain/assets/0xE3894CB9E92ca78524Fb6a30Ff072FA5E533c162/info.json
  blockchains/smartchain/assets/0xE3894CB9E92ca78524Fb6a30Ff072FA5E533c162/logo.png
Labels: Payment Status: Paid

#6153 Add WLQX (Wrapped LQX)
  blockchains/smartchain/assets/0x4495e673eE53c61CE79c35D5e299733639362aEc/info.json
  blockchains/smartchain/assets/0x4495e673eE53c61CE79c35D5e299733639362aEc/logo.png
Labels: Payment Status: Paid

#6182 Add 0xzx (BEP20)
  blockchains/smartchain/assets/0x1fBB6cA220dCBE732f796Fa9b13dd21cD654511b/info.json
  blockchains/smartchain/assets/0x1fBB6cA220dCBE732f796Fa9b13dd21cD654511b/logo.png
Labels: Payment Status: Paid

#6194 [Internal] RCO token
  blockchains/ethereum/assets/0x1600C5502E7e94CaCf73C124331cfa3e20ADd40e/info.json
Labels: Payment Status: Paid

#6176 Add COPE
  blockchains/solana/assets/3K6rftdAaQYMPunrtNRHgnK2UAtjm2JwyT2oCiTDouYE/info.json
  blockchains/solana/assets/3K6rftdAaQYMPunrtNRHgnK2UAtjm2JwyT2oCiTDouYE/logo.png
Labels: Payment Status: Paid

#6192 Add Tenset token - 10SET(ERC20)
  blockchains/ethereum/assets/0x7FF4169a6B5122b664c51c95727d87750eC07c84/info.json
  blockchains/ethereum/assets/0x7FF4169a6B5122b664c51c95727d87750eC07c84/logo.png
Labels: Payment Status: Paid

#6155 Added SAFESTAR logo and info
  blockchains/smartchain/assets/0x3C00F8FCc8791fa78DAA4A480095Ec7D475781e2/info.json
  blockchains/smartchain/assets/0x3C00F8FCc8791fa78DAA4A480095Ec7D475781e2/logo.png
Labels: Payment Status: Paid

#6199 [Internal] Tokenlist update, increase max count from API
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
  script/config.ts
Labels: Payment Status: Paid

#6201 [Internal] Force-add STMX to tokenlist
  blockchains/ethereum/tokenlist.json
  script/config.ts
Labels: Payment Status: Paid

#6196 Marked old HOLY token as deprecated and changed info for Mover token
  blockchains/ethereum/assets/0x39eAE99E685906fF1C11A962a743440d0a1A6e09/info.json
  blockchains/ethereum/assets/0x3FA729B4548beCBAd4EaB6EF18413470e6D5324C/info.json
  blockchains/ethereum/assets/0x3FA729B4548beCBAd4EaB6EF18413470e6D5324C/logo.png
Labels: Payment Status: Paid

#6195 Add OXB token
  blockchains/smartchain/assets/0x3fd5B5746315E3F8d43A46b09c826a001EBb977d/info.json
  blockchains/smartchain/assets/0x3fd5B5746315E3F8d43A46b09c826a001EBb977d/logo.png
  blockchains/smartchain/assets/0xdcAf1Afc07d9e1C057bd5cd144659910C4b91682/info.json
  blockchains/smartchain/assets/0xdcAf1Afc07d9e1C057bd5cd144659910C4b91682/logo.png
Labels: Payment Status: Paid

#6180 Update logo for ELP
  blockchains/smartchain/assets/0xE3894CB9E92ca78524Fb6a30Ff072FA5E533c162/logo.png
Labels: Payment Status: Paid

#6162 Add Unmarshal token from Unmarshal
  blockchains/ethereum/assets/0x5a666c7d92E5fA7Edcb6390E4efD6d0CDd69cF37/info.json
  blockchains/ethereum/assets/0x5a666c7d92E5fA7Edcb6390E4efD6d0CDd69cF37/logo.png
Labels: Payment Status: Paid

#6173 Harmony Etherum Bridge Token
  blockchains/ethereum/assets/0xD5cd84D6f044AbE314Ee7E414d37cae8773ef9D3/info.json
  blockchains/ethereum/assets/0xD5cd84D6f044AbE314Ee7E414d37cae8773ef9D3/logo.png
Labels: Payment Status: Paid

#6157 Updated Logo
  blockchains/smartchain/assets/0x380624A4a7e69dB1cA07deEcF764025FC224D056/logo.png
Labels: Payment Status: Requested

#6178 Add Fei Protocol (ERC20)
  blockchains/ethereum/assets/0x956F47F50A910163D8BF957Cf5846D573E7f87CA/info.json
  blockchains/ethereum/assets/0x956F47F50A910163D8BF957Cf5846D573E7f87CA/logo.png
  blockchains/ethereum/assets/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B/info.json
  blockchains/ethereum/assets/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B/logo.png
Labels: Payment Status: Paid

#6231 Added VANCAT Token Logo
  blockchains/smartchain/assets/0x8597ba143AC509189E89aaB3BA28d661A5dD9830/info.json
  blockchains/smartchain/assets/0x8597ba143AC509189E89aaB3BA28d661A5dD9830/logo.png
Labels: Payment Status: Paid

#6215 Elongate fix ID
  blockchains/smartchain/assets/0x2A9718defF471f3Bb91FA0ECEAB14154F150a385/info.json
  blockchains/smartchain/assets/0x2A9718defF471f3Bb91FA0ECEAB14154F150a385/logo.png
Labels: Payment Status: Paid

#6146 adding GUM
  blockchains/ethereum/assets/0x4f5fa8f2d12e5eB780f6082Dd656C565C48E0f24/logo.png
  blockchains/smartchain/assets/0xc53708664b99DF348dd27C3Ac0759d2DA9c40462/info.json
  blockchains/smartchain/assets/0xc53708664b99DF348dd27C3Ac0759d2DA9c40462/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#6202 Add SWAMP logo
  blockchains/smartchain/assets/0xc5A49b4CBe004b6FD55B30Ba1dE6AC360FF9765d/info.json
  blockchains/smartchain/assets/0xc5A49b4CBe004b6FD55B30Ba1dE6AC360FF9765d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5876 Update ARGON Logo
  blockchains/smartchain/assets/0x851F7a700c5d67DB59612b871338a85526752c25/logo.png
Labels: Payment Status: Paid

#6228 add τBitcoin
  blockchains/smartchain/assets/0x2cD1075682b0FCCaADd0Ca629e138E64015Ba11c/info.json
  blockchains/smartchain/assets/0x2cD1075682b0FCCaADd0Ca629e138E64015Ba11c/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6181 Add BITTO (BEP20)
  blockchains/smartchain/assets/0x816e9e589F8C07149dA4E2496C547952338B27e2/info.json
  blockchains/smartchain/assets/0x816e9e589F8C07149dA4E2496C547952338B27e2/logo.png
Labels: Payment Status: Paid

#6264 Add MVI info and logo
  blockchains/ethereum/assets/0x72e364F2ABdC788b7E918bc238B21f109Cd634D7/info.json
  blockchains/ethereum/assets/0x72e364F2ABdC788b7E918bc238B21f109Cd634D7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6211 Add SAFEP Token
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xA8c514D991F59baB02d32b68f04204cB89261c88/info.json
  blockchains/smartchain/assets/0xA8c514D991F59baB02d32b68f04204cB89261c88/logo.png
Labels: Payment Status: Paid

#6198 Add swapx.launchzone.org.png and poolx.launchzone.org.png
  dapps/poolx.launchzone.org.png
  dapps/swapx.launchzone.org.png
Labels: Payment Status: Paid

#6230 Added SafeEarth Info and Logo (ERC20)
  blockchains/ethereum/assets/0xE6F1966d04CfcB9cd1B1dC4E8256D8b501b11CbA/info.json
  blockchains/ethereum/assets/0xE6F1966d04CfcB9cd1B1dC4E8256D8b501b11CbA/logo.png
Labels: Payment Status: Paid

#6237 Requesting Logo and Info update for FOX token on BSC (0xFAd8E46123D7b4e77496491769C167FF894d2ACB)
  blockchains/smartchain/assets/0xFAd8E46123D7b4e77496491769C167FF894d2ACB/info.json
  blockchains/smartchain/assets/0xFAd8E46123D7b4e77496491769C167FF894d2ACB/logo.png
Labels: Payment Status: Paid

#6238 Add BCP Token
  blockchains/ethereum/assets/0xe047705117Eb07e712C3d684f5B18E74577e83aC/info.json
  blockchains/ethereum/assets/0xe047705117Eb07e712C3d684f5B18E74577e83aC/logo.png
Labels: Payment Status: Paid

#6187 Add Cartesi Token (CTSI) BEP-20 Version
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x8dA443F84fEA710266C8eB6bC34B71702d033EF2/info.json
  blockchains/smartchain/assets/0x8dA443F84fEA710266C8eB6bC34B71702d033EF2/logo.png
Labels: Payment Status: Paid

#6240 Add Logo and Token Info for SeedifyFund (BEP20)
  blockchains/smartchain/assets/0x477bC8d23c634C154061869478bce96BE6045D12/info.json
  blockchains/smartchain/assets/0x477bC8d23c634C154061869478bce96BE6045D12/logo.png
Labels: Payment Status: Paid

#6245 Update new logo asset
  blockchains/smartchain/assets/0x3C00F8FCc8791fa78DAA4A480095Ec7D475781e2/logo.png
Labels: Payment Status: Paid

#6247 Add MOONSHOT logo and info
  blockchains/smartchain/assets/0xd27D3F7f329D93d897612E413F207A4dbe8bF799/info.json
  blockchains/smartchain/assets/0xd27D3F7f329D93d897612E413F207A4dbe8bF799/logo.png
Labels: Payment Status: Paid

#6250 Add BSCPAD (BEP20)
  blockchains/smartchain/assets/0x5A3010d4d8D3B5fB49f8B6E57FB9E48063f16700/info.json
  blockchains/smartchain/assets/0x5A3010d4d8D3B5fB49f8B6E57FB9E48063f16700/logo.png
Labels: Payment Status: Paid

#6282 [Internal] Increase reminder/autoclose timeouts
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#6268 Added $FAIRMOON (BEP20)
  blockchains/smartchain/assets/0xfe75cD11E283813eC44B4592476109Ba3706cef6/info.json
  blockchains/smartchain/assets/0xfe75cD11E283813eC44B4592476109Ba3706cef6/logo.png
Labels: Payment Status: Paid

#6190 Adding GATENet token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x9d7630aDF7ab0b0CB00Af747Db76864df0EC82E4/info.json
  blockchains/ethereum/assets/0x9d7630aDF7ab0b0CB00Af747Db76864df0EC82E4/logo.png
Labels: Payment Status: Paid

#6251 Add BOR token info and logo
  blockchains/ethereum/assets/0x3c9d6c1C73b31c837832c72E04D3152f051fc1A9/info.json
  blockchains/ethereum/assets/0x3c9d6c1C73b31c837832c72E04D3152f051fc1A9/logo.png
Labels: Payment Status: Paid

#6083 update LPOOL logo
  blockchains/ethereum/assets/0x6149C26Cd2f7b5CCdb32029aF817123F6E37Df5B/logo.png
Labels: Payment Status: Paid

#6277 Add BTCA logo and info
  blockchains/smartchain/assets/0xd54Fd5D0C349C06373f3FE914151D1555b629fB6/info.json
  blockchains/smartchain/assets/0xd54Fd5D0C349C06373f3FE914151D1555b629fB6/logo.png
Labels: Payment Status: Paid

#6267 Please add Liquity's LUSD and LQTY tokens
  blockchains/ethereum/assets/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0/info.json
  blockchains/ethereum/assets/0x5f98805A4E8be255a32880FDeC7F6728C6568bA0/logo.png
  blockchains/ethereum/assets/0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D/info.json
  blockchains/ethereum/assets/0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6242 add FRAX and FXS bsc info
  blockchains/smartchain/assets/0x29cED01C447166958605519F10DcF8b0255fB379/info.json
  blockchains/smartchain/assets/0x29cED01C447166958605519F10DcF8b0255fB379/logo.png
  blockchains/smartchain/assets/0xDE2F075f6F14EB9D96755b24E416A53E736Ca363/info.json
  blockchains/smartchain/assets/0xDE2F075f6F14EB9D96755b24E416A53E736Ca363/logo.png
Labels: Payment Status: Paid

#6296 Revert "SafeToken logo and info"
  blockchains/smartchain/assets/0x31045e7023e6c388F9447E632a3f9EaFF90393fa/info.json
  blockchains/smartchain/assets/0x31045e7023e6c388F9447E632a3f9EaFF90393fa/logo.png
Labels: Payment Status: Requested

#6297 Bonk to megaBONK migration
  blockchains/ethereum/assets/0xacFe45C352C902ae3A3F9B6bfE6eC994c5D791BF/info.json
  blockchains/ethereum/assets/0xacFe45C352C902ae3A3F9B6bfE6eC994c5D791BF/logo.png
Labels: Payment Status: Requested

#6252 FastMoon BEP20 token Trust Wallet
  blockchains/smartchain/assets/0x869Dd7A64AfBe5370a8c591d9B8650BE60c0B8f6/info.json
  blockchains/smartchain/assets/0x869Dd7A64AfBe5370a8c591d9B8650BE60c0B8f6/logo.png
Labels: Payment Status: Paid

#6295 Add RISKMOON info and logo.
  blockchains/smartchain/assets/0xa96f3414334F5A0A529ff5d9D8ea95f42147b8C9/info.json
  blockchains/smartchain/assets/0xa96f3414334F5A0A529ff5d9D8ea95f42147b8C9/logo.png
Labels: Payment Status: Paid

#6298 1002992
  blockchains/tron/assets/1002992/info.json
  blockchains/tron/assets/1002992/logo.png
Labels: Payment Status: Paid

#6300 add FRY token
  blockchains/smartchain/assets/0xc04e039aE8587e71f8024b36d630f841cc2106CC/info.json
  blockchains/smartchain/assets/0xc04e039aE8587e71f8024b36d630f841cc2106CC/logo.png
Labels: Payment Status: Paid

#6302 Add ORF logo and info
  blockchains/smartchain/assets/0xEF2ec90e0b8D4CdFdB090989EA1Bc663F0D680BF/info.json
  blockchains/smartchain/assets/0xEF2ec90e0b8D4CdFdB090989EA1Bc663F0D680BF/logo.png
Labels: Payment Status: Paid

#6305 added a missing info.json file for TheDAO
  blockchains/ethereum/assets/0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413/info.json
Labels: Payment Status: Requested

#6303 Add CCAKE Token
  blockchains/smartchain/assets/0xc7091AA18598b87588e37501b6Ce865263CD67Ce/info.json
  blockchains/smartchain/assets/0xc7091AA18598b87588e37501b6Ce865263CD67Ce/logo.png
Labels: Payment Status: Paid

#6310 Add Nicheman (BEP20)
  blockchains/smartchain/assets/0xF27580F6a58FF785c60B7c15fD394AB442aAA451/info.json
  blockchains/smartchain/assets/0xF27580F6a58FF785c60B7c15fD394AB442aAA451/logo.png
Labels: Payment Status: Paid

#6284 Please add DDIM BEP20 Token
  blockchains/smartchain/assets/0xc9132C76060F6b319764Ea075973a650A1a53bC9/info.json
  blockchains/smartchain/assets/0xc9132C76060F6b319764Ea075973a650A1a53bC9/logo.png
Labels: Payment Status: Requested, Status: Correction needed

#6315 [Internal] Adjust external update build times.
  .github/workflows/periodic-update.yml
Labels: Payment Status: Paid

#6286 Add NMX logo and info
  blockchains/smartchain/assets/0xd32d01A43c869EdcD1117C640fBDcfCFD97d9d65/info.json
  blockchains/smartchain/assets/0xd32d01A43c869EdcD1117C640fBDcfCFD97d9d65/logo.png
Labels: Payment Status: Paid

#6330 Updated DACXI token address and information #6299
  blockchains/ethereum/assets/0x2c9Ff8Cd4266De4ba3a8a8e53391853cDb595c23/info.json
  blockchains/ethereum/assets/0xEfaB7248D36585e2340E5d25F8a8D243E6e3193F/info.json
  blockchains/ethereum/assets/0xEfaB7248D36585e2340E5d25F8a8D243E6e3193F/logo.png
Labels: Payment Status: Paid

#6313 Updated VANCAT Token logo.
  blockchains/smartchain/assets/0x8597ba143AC509189E89aaB3BA28d661A5dD9830/logo.png
Labels: Payment Status: Paid

#6326 Add PooCoin Logo and Info
  blockchains/smartchain/assets/0xB27ADAfFB9fEa1801459a1a81B17218288c097cc/info.json
  blockchains/smartchain/assets/0xB27ADAfFB9fEa1801459a1a81B17218288c097cc/logo.png
Labels: Payment Status: Paid

#6329 Add Lava Token (BEP20)
  blockchains/smartchain/assets/0xfaFf5251EA98f90540D6BacDf7A458f61b456C06/info.json
  blockchains/smartchain/assets/0xfaFf5251EA98f90540D6BacDf7A458f61b456C06/logo.png
Labels: Payment Status: Paid

#6185 Add PYX to smartchain (Logo and info)
  blockchains/smartchain/assets/0x3ebb316D8c387ef235BAa38978cbB9B97C8C3017/info.json
  blockchains/smartchain/assets/0x3ebb316D8c387ef235BAa38978cbB9B97C8C3017/logo.png
Labels: Payment Status: Paid

#6331 Add WAD Token (BEP20)
  blockchains/smartchain/assets/0x0fEAdcC3824E7F3c12f40E324a60c23cA51627fc/info.json
  blockchains/smartchain/assets/0x0fEAdcC3824E7F3c12f40E324a60c23cA51627fc/logo.png
  dapps/wardenswap.finance.png
Labels: Payment Status: Paid

#6322 update FERA assets
  blockchains/ethereum/assets/0x539F3615C1dBAfa0D008d87504667458acBd16Fa/logo.png
Labels: Payment Status: Paid

#6316 Please add DUCK BEP-20 Version
  blockchains/smartchain/assets/0x5D186E28934c6B0fF5Fc2feCE15D1F34f78cBd87/info.json
  blockchains/smartchain/assets/0x5D186E28934c6B0fF5Fc2feCE15D1F34f78cBd87/logo.png
Labels: Payment Status: Paid

#6355 Add Eleven finance logo and info
  blockchains/smartchain/assets/0xAcD7B3D9c10e97d0efA418903C0c7669E702E4C0/info.json
  blockchains/smartchain/assets/0xAcD7B3D9c10e97d0efA418903C0c7669E702E4C0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6353 Add Juggernaut DeFi (BEP20)
  blockchains/smartchain/assets/0xC13B7a43223BB9Bf4B69BD68Ab20ca1B79d81C75/info.json
  blockchains/smartchain/assets/0xC13B7a43223BB9Bf4B69BD68Ab20ca1B79d81C75/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6372 Add SNBL info and Logo
  blockchains/smartchain/assets/0xa1FD60c51C0BDAC1Ff5BB6067A24d61441E39569/info.json
  blockchains/smartchain/assets/0xa1FD60c51C0BDAC1Ff5BB6067A24d61441E39569/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6339 mello token info update
  blockchains/smartchain/assets/0x651BfbB26455294408Aabc61a7ADF427bf149898/info.json
  blockchains/smartchain/assets/0x651BfbB26455294408Aabc61a7ADF427bf149898/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6311 PancakeTools Token
  blockchains/smartchain/assets/0x3b831d36ed418e893F42d46ff308C326C239429f/info.json
  blockchains/smartchain/assets/0x3b831d36ed418e893F42d46ff308C326C239429f/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#6309 Adding MBOX Token Logo
  blockchains/smartchain/assets/0x3203c9E46cA618C8C1cE5dC67e7e9D75f5da2377/info.json
  blockchains/smartchain/assets/0x3203c9E46cA618C8C1cE5dC67e7e9D75f5da2377/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#6020 SquirrelFinance token logo addition
  blockchains/smartchain/assets/0x8893D5fA71389673C5c4b9b3cb4EE1ba71207556/info.json
  blockchains/smartchain/assets/0x8893D5fA71389673C5c4b9b3cb4EE1ba71207556/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6177 Add POLVEN token and info.json
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x4a6AB9792e9f046C3AB22D8602450DE5186Be9A7/info.json
  blockchains/ethereum/assets/0x4a6AB9792e9f046C3AB22D8602450DE5186Be9A7/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6348 Add SnowgeCoin (BEP20)
  blockchains/smartchain/assets/0x5E9280d53F28281Ce098C8F64e49F5f5DC9Ea185/info.json
  blockchains/smartchain/assets/0x5E9280d53F28281Ce098C8F64e49F5f5DC9Ea185/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6344 Add Zeppelin.dao smartchain asset info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x2E291e1c9f85a86d0C58Ae15621aaC005a8b2EAD/info.json
  blockchains/smartchain/assets/0x2E291e1c9f85a86d0C58Ae15621aaC005a8b2EAD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6239 Fix logo based on unexpected trustwallet app crop
  blockchains/smartchain/assets/0x2A9718defF471f3Bb91FA0ECEAB14154F150a385/logo.png
Labels: Payment Status: Paid

#6333 Adding XSPACE logo
  blockchains/smartchain/assets/0xAD90c05BC51672eEdfeE36E58b3ff1A78bbC146d/info.json
  blockchains/smartchain/assets/0xAD90c05BC51672eEdfeE36E58b3ff1A78bbC146d/logo.png
Labels: Payment Status: Paid

#6321 Add WTON token (ERC20)
  blockchains/ethereum/assets/0xdB3C2515Da400e11Bcaf84f3b5286f18ffF1868F/info.json
  blockchains/ethereum/assets/0xdB3C2515Da400e11Bcaf84f3b5286f18ffF1868F/logo.png
Labels: Payment Status: Paid

#6336 Add RSD Logo
  blockchains/ethereum/assets/0x61Ed1C66239d29Cc93C8597c6167159e8F69a823/info.json
  blockchains/ethereum/assets/0x61Ed1C66239d29Cc93C8597c6167159e8F69a823/logo.png
  blockchains/smartchain/assets/0x61Ed1C66239d29Cc93C8597c6167159e8F69a823/info.json
  blockchains/smartchain/assets/0x61Ed1C66239d29Cc93C8597c6167159e8F69a823/logo.png
Labels: Payment Status: Paid

#6337 Added Logo and Info for OCTANS Token
  blockchains/smartchain/assets/0x86c3E4FfAcdB3AF628ef985a518cd6ee22A22b28/info.json
  blockchains/smartchain/assets/0x86c3E4FfAcdB3AF628ef985a518cd6ee22A22b28/logo.png
Labels: Payment Status: Paid

#6342 Add SafePitbull (BEP20)
  blockchains/smartchain/assets/0xe2F4516aA9bd7b864FF0C6DD4EbB8878E1BBc97D/info.json
  blockchains/smartchain/assets/0xe2F4516aA9bd7b864FF0C6DD4EbB8878E1BBc97D/logo.png
Labels: Payment Status: Paid

#6343 Add FOMO (BEP20)
  blockchains/smartchain/assets/0x5EEF8c4320e2Bf8D1e6231A31500FD7a87D02985/info.json
  blockchains/smartchain/assets/0x5EEF8c4320e2Bf8D1e6231A31500FD7a87D02985/logo.png
Labels: Payment Status: Paid

#6388 [Internal] Rename Polygon (Matic) chain folder to polygon
  blockchains/polygon/info/info.json
  blockchains/polygon/info/logo.png
Labels: Payment Status: Paid

#6301 Add files via upload
  blockchains/smartchain/assets/0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e/info.json
  blockchains/smartchain/assets/0xa9eA4b786ee5b7A733c035564Bfd9341A4c9FC1e/logo.png
Labels: Payment Status: Paid

#6345 Add RASTA (BEP20)
  blockchains/smartchain/assets/0xE3e8cC42DA487d1116D26687856e9FB684817c52/info.json
  blockchains/smartchain/assets/0xE3e8cC42DA487d1116D26687856e9FB684817c52/logo.png
Labels: Payment Status: Paid

#6349 Add LYPTUS BEP20 https://koaladefi.finance/
  blockchains/smartchain/assets/0xBA26397cdFF25F0D26E815d218Ef3C77609ae7f1/info.json
  blockchains/smartchain/assets/0xBA26397cdFF25F0D26E815d218Ef3C77609ae7f1/logo.png
Labels: Payment Status: Paid

#6350 Add Bafe.io (BEP20)
  blockchains/smartchain/assets/0x7bb362962F2a4E2089466C79566572B37CFc5D78/info.json
  blockchains/smartchain/assets/0x7bb362962F2a4E2089466C79566572B37CFc5D78/logo.png
Labels: Payment Status: Paid

#6314 SafeBTC new logo
  blockchains/smartchain/assets/0x380624A4a7e69dB1cA07deEcF764025FC224D056/info.json
  blockchains/smartchain/assets/0x380624A4a7e69dB1cA07deEcF764025FC224D056/logo.png
Labels: Payment Status: Paid

#6393 [Internal][WIP] Upload to IPFS
  .github/workflows/upload-ipfs.yml
Labels: Payment Status: Paid

#6417 [Internal] Fix ipfs build
  .github/workflows/upload-ipfs.yml
Labels: Payment Status: Paid

#6363 Add VGD token logo and info
  blockchains/smartchain/assets/0xFd91Fa8fab5cA11569E256fa8844Bc2abecc331D/info.json
  blockchains/smartchain/assets/0xFd91Fa8fab5cA11569E256fa8844Bc2abecc331D/logo.png
Labels: Payment Status: Paid

#6317 add ORK
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xCed0CE92F4bdC3c2201E255FAF12f05cf8206dA8/info.json
  blockchains/smartchain/assets/0xCed0CE92F4bdC3c2201E255FAF12f05cf8206dA8/logo.png
Labels: Payment Status: Paid

#6379 Add Strite (BEP20)
  blockchains/smartchain/assets/0x9b93c29595dd603f75854EbA3C5f4EE078EE4454/info.json
  blockchains/smartchain/assets/0x9b93c29595dd603f75854EbA3C5f4EE078EE4454/logo.png
Labels: Payment Status: Paid

#6383 Add KING OF DEFI (TRC20)
  blockchains/tron/assets/TTUwzoZAK6rpDjpSh8B2XFTnxGfbMLHJaq/info.json
  blockchains/tron/assets/TTUwzoZAK6rpDjpSh8B2XFTnxGfbMLHJaq/logo.png
Labels: Payment Status: Paid

#6387 Add RAI (ERC20 Ethereum)
  blockchains/ethereum/assets/0x03ab458634910AaD20eF5f1C8ee96F1D6ac54919/info.json
  blockchains/ethereum/assets/0x03ab458634910AaD20eF5f1C8ee96F1D6ac54919/logo.png
Labels: Payment Status: Paid

#6433 Add Airnfts DApp Image
  dapps/app.airnfts.com.png
Labels: Payment Status: Requested

#6439 redoing from earlier pull 6437
  blockchains/ethereum/assets/0x773258b03c730F84aF10dFcB1BfAa7487558B8Ac/info.json
  blockchains/ethereum/assets/0x773258b03c730F84aF10dFcB1BfAa7487558B8Ac/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6398 Add MoonToken to TW
  blockchains/smartchain/assets/0x81E4d494b85A24a58a6BA45c9B418b32a4E039de/info.json
  blockchains/smartchain/assets/0x81E4d494b85A24a58a6BA45c9B418b32a4E039de/logo.png
Labels: Payment Status: Paid

#6391 Add MRAT LOGO
  blockchains/smartchain/assets/0x6D949f9297A522c0f97C232CC209a67Bd7CfA471/info.json
  blockchains/smartchain/assets/0x6D949f9297A522c0f97C232CC209a67Bd7CfA471/logo.png
Labels: Payment Status: Paid

#6399 Add EarnX Logo and Info
  blockchains/smartchain/assets/0x9C28E48Ea9170d9A9cB76d338655b8bd4124BC7A/info.json
  blockchains/smartchain/assets/0x9C28E48Ea9170d9A9cB76d338655b8bd4124BC7A/logo.png
Labels: Payment Status: Paid

#6347 Please add CLIMB logo to trustwallet!
  blockchains/smartchain/assets/0x2A1d286ed5edAD78BeFD6E0d8BEb38791e8cD69d/info.json
  blockchains/smartchain/assets/0x2A1d286ed5edAD78BeFD6E0d8BEb38791e8cD69d/logo.png
Labels: Payment Status: Paid

#6367 adding MOONI
  blockchains/smartchain/assets/0xEd438051437c22A9Ef249B68c7E292435fE8B858/info.json
  blockchains/smartchain/assets/0xEd438051437c22A9Ef249B68c7E292435fE8B858/logo.png
Labels: Payment Status: Paid

#6409 Update the logo of SeedifyFund (BEP20) and Add the Price Ticker for SeedifyFund
  blockchains/smartchain/assets/0x477bC8d23c634C154061869478bce96BE6045D12/logo.png
Labels: Payment Status: Paid

#6420 add deeper network ERC20 token info and logo
  blockchains/ethereum/assets/0xf3AE5d769e153Ef72b4e3591aC004E89F48107a1/info.json
  blockchains/ethereum/assets/0xf3AE5d769e153Ef72b4e3591aC004E89F48107a1/logo.png
Labels: Payment Status: Paid

#6422 Logo PeacockCoin trust wallet
  blockchains/smartchain/assets/0x050787DE0cF5Da03D9387b344334D51cAE5DD0Fd/info.json
  blockchains/smartchain/assets/0x050787DE0cF5Da03D9387b344334D51cAE5DD0Fd/logo.png
Labels: Payment Status: Paid

#6427 Add Martian DAO (BEP20)
  blockchains/smartchain/assets/0x904d7Ac5d005d16DBDc69f713D029e3C1800F8Ca/info.json
  blockchains/smartchain/assets/0x904d7Ac5d005d16DBDc69f713D029e3C1800F8Ca/logo.png
Labels: Payment Status: Paid

#6454 [Internal] Update tokenlist
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#6465 [Internal] Add Thorchain info
  blockchains/thorchain/info/info.json
  blockchains/thorchain/info/logo.png
Labels: Payment Status: Paid

#6457 Add Strike sTokens logo and info
  blockchains/ethereum/assets/0x18A908eD663823C908A900b934D6249d4befbE44/info.json
  blockchains/ethereum/assets/0x18A908eD663823C908A900b934D6249d4befbE44/logo.png
  blockchains/ethereum/assets/0x280f76a218DDC8d56B490B5835e251E55a2e8F8d/info.json
  blockchains/ethereum/assets/0x280f76a218DDC8d56B490B5835e251E55a2e8F8d/logo.png
  blockchains/ethereum/assets/0x3774E825d567125988Fb293e926064B6FAa71DAB/info.json
  blockchains/ethereum/assets/0x3774E825d567125988Fb293e926064B6FAa71DAB/logo.png
  blockchains/ethereum/assets/0x3F3B3B269d9f7088B022290906acff8710914be1/info.json
  blockchains/ethereum/assets/0x3F3B3B269d9f7088B022290906acff8710914be1/logo.png
  blockchains/ethereum/assets/0x4164e5b047842Ad7dFf18fc6A6e63a1e40610f46/info.json
  blockchains/ethereum/assets/0x4164e5b047842Ad7dFf18fc6A6e63a1e40610f46/logo.png
  blockchains/ethereum/assets/0x69702cfd7DAd8bCcAA24D6B440159404AAA140F5/info.json
  blockchains/ethereum/assets/0x69702cfd7DAd8bCcAA24D6B440159404AAA140F5/logo.png
  blockchains/ethereum/assets/0x9d1C2A187cf908aEd8CFAe2353Ef72F06223d54D/info.json
  blockchains/ethereum/assets/0x9d1C2A187cf908aEd8CFAe2353Ef72F06223d54D/logo.png
  blockchains/ethereum/assets/0xA28d2EC98C6bb076A2e152dC9e0d94C8C01e36B0/info.json
  blockchains/ethereum/assets/0xA28d2EC98C6bb076A2e152dC9e0d94C8C01e36B0/logo.png
  blockchains/ethereum/assets/0xbEe9Cf658702527b0AcB2719c1FAA29EdC006a92/info.json
  blockchains/ethereum/assets/0xbEe9Cf658702527b0AcB2719c1FAA29EdC006a92/logo.png
  blockchains/ethereum/assets/0xdBee1d8C452c781C17Ea20115CbaD0d5f627a680/info.json
  blockchains/ethereum/assets/0xdBee1d8C452c781C17Ea20115CbaD0d5f627a680/logo.png
Labels: Payment Status: Requested

#6473 Add STRK asset logo and info
  blockchains/ethereum/assets/0x74232704659ef37c08995e386A2E26cc27a8d7B1/info.json
  blockchains/ethereum/assets/0x74232704659ef37c08995e386A2E26cc27a8d7B1/logo.png
Labels: Payment Status: Requested

#6364 Add Alchemy (ERC20)
  blockchains/ethereum/assets/0x0000A1c00009A619684135B824Ba02f7FbF3A572/info.json
  blockchains/ethereum/assets/0x0000A1c00009A619684135B824Ba02f7FbF3A572/logo.png
Labels: Payment Status: Paid

#6496 Flux Rebrand
  blockchains/zelcash/info/info.json
  blockchains/zelcash/info/logo.png
Labels: Payment Status: Requested

#6442 Add DODO
  dapps/app.dodoex.io.png
Labels: Payment Status: Paid, Payment Status: Requested

#6444 Update LYPTUS BEP20 Logo
  blockchains/smartchain/assets/0xBA26397cdFF25F0D26E815d218Ef3C77609ae7f1/logo.png
Labels: Payment Status: Requested

#6412 OMI Logo Update
  blockchains/smartchain/assets/0x0Ca958394bf4F68D30454421388A6A4Af8652E4B/info.json
  blockchains/smartchain/assets/0x0Ca958394bf4F68D30454421388A6A4Af8652E4B/logo.png
Labels: Payment Status: Paid

#6424 Add ETNA LOGO ( BEP20 )
  blockchains/smartchain/assets/0x51F35073FF7cF54c9e86b7042E59A8cC9709FC46/info.json
  blockchains/smartchain/assets/0x51F35073FF7cF54c9e86b7042E59A8cC9709FC46/logo.png
Labels: Payment Status: Paid

#6458 Add Student Coin logo and info
  blockchains/ethereum/assets/0x15B543e986b8c34074DFc9901136d9355a537e7E/info.json
  blockchains/ethereum/assets/0x15B543e986b8c34074DFc9901136d9355a537e7E/logo.png
Labels: Payment Status: Paid

#6468 Update Moonshot Logo
  blockchains/smartchain/assets/0xd27D3F7f329D93d897612E413F207A4dbe8bF799/logo.png
Labels: Payment Status: Paid

#6470 Add IceToken to Ethereum and smartchain
  blockchains/ethereum/assets/0xf16e81dce15B08F326220742020379B855B87DF9/info.json
  blockchains/ethereum/assets/0xf16e81dce15B08F326220742020379B855B87DF9/logo.png
  blockchains/smartchain/assets/0xf16e81dce15B08F326220742020379B855B87DF9/info.json
  blockchains/smartchain/assets/0xf16e81dce15B08F326220742020379B855B87DF9/logo.png
Labels: Payment Status: Paid

#6467 Update MOONI logo_v2
  blockchains/smartchain/assets/0xEd438051437c22A9Ef249B68c7E292435fE8B858/logo.png
Labels: Payment Status: Paid

#6507 New FinxFlo Logo
  blockchains/ethereum/assets/0x8a40c222996f9F3431f63Bf80244C36822060f12/logo.png
Labels: Payment Status: Requested

#6516 Add WINDY Token Logo
  blockchains/smartchain/assets/0xD1587Ee50e0333f0C4aDcF261379A61B1486c5d2/info.json
  blockchains/smartchain/assets/0xD1587Ee50e0333f0C4aDcF261379A61B1486c5d2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6529 Integrate Rocket Moon to Trust Wallet
  blockchains/smartchain/assets/0x78bc22a215C1eF8a2e41Fa1c39CD7BDC09bd5174/info.json
  blockchains/smartchain/assets/0x78bc22a215C1eF8a2e41Fa1c39CD7BDC09bd5174/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6531 Add SafeUniverse (BEP20)
  blockchains/smartchain/assets/0x16Feb16F7Ee2190312D03f449eeEc2339add2D83/info.json
  blockchains/smartchain/assets/0x16Feb16F7Ee2190312D03f449eeEc2339add2D83/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6514 Add FLX
  blockchains/ethereum/assets/0x6243d8CEA23066d098a15582d81a598b4e8391F4/info.json
  blockchains/ethereum/assets/0x6243d8CEA23066d098a15582d81a598b4e8391F4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6513 Add ENA token to trust wallet
  blockchains/smartchain/assets/0x3713c1fc64C1Deefdf0Ca65D098d15de050EeD1e/info.json
  blockchains/smartchain/assets/0x3713c1fc64C1Deefdf0Ca65D098d15de050EeD1e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6572 Revert "Add ENA token to trust wallet"
  blockchains/smartchain/assets/0x3713c1fc64C1Deefdf0Ca65D098d15de050EeD1e/info.json
  blockchains/smartchain/assets/0x3713c1fc64C1Deefdf0Ca65D098d15de050EeD1e/logo.png
Labels: Payment Status: Requested

#6498 Add ADD token logo and info
  blockchains/ethereum/assets/0x635d081fD8F6670135D8a3640E2cF78220787d56/info.json
  blockchains/ethereum/assets/0x635d081fD8F6670135D8a3640E2cF78220787d56/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6486 add_BEP20_SLD
  blockchains/smartchain/assets/0x8A9030c0ED9A5b9C7Ab39EBfEE11D90aF9945f6F/info.json
  blockchains/smartchain/assets/0x8A9030c0ED9A5b9C7Ab39EBfEE11D90aF9945f6F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6478 Add AIOZ logo & info (BEP20) in BSC
  blockchains/smartchain/assets/0x33d08D8C7a168333a85285a68C0042b39fC3741D/info.json
  blockchains/smartchain/assets/0x33d08D8C7a168333a85285a68C0042b39fC3741D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6526 Add FEG
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/info.json
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6328 add RaiFinance token
  blockchains/ethereum/assets/0xf30547ff2Df1F1CBE5C8DD758B3dd098C856e38f/info.json
  blockchains/ethereum/assets/0xf30547ff2Df1F1CBE5C8DD758B3dd098C856e38f/logo.png
  blockchains/smartchain/assets/0x0e128Fb9f266F0CFedEb3B789f6fd4AF50d51b84/info.json
  blockchains/smartchain/assets/0x0e128Fb9f266F0CFedEb3B789f6fd4AF50d51b84/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6206 Add GAMEE Token info and logo
  blockchains/ethereum/assets/0xD9016A907Dc0ECfA3ca425ab20B6b785B42F2373/info.json
  blockchains/ethereum/assets/0xD9016A907Dc0ECfA3ca425ab20B6b785B42F2373/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5617 add Token Logo & Description
  blockchains/ethereum/assets/0x19A2cF2A1B2f76e52E2b0c572bD80A95B4Fa8643/info.json
  blockchains/ethereum/assets/0x19A2cF2A1B2f76e52E2b0c572bD80A95B4Fa8643/logo.png
Labels: Payment Status: Paid, Status: On Hold

#6451 Add Wrapped MonetaryUnit (WMUE, BEP20)
  blockchains/smartchain/assets/0x00abaA93fAF8fDc4f382135a7A56F9Cf7C3EdD21/info.json
  blockchains/smartchain/assets/0x00abaA93fAF8fDc4f382135a7A56F9Cf7C3EdD21/logo.png
Labels: Payment Status: Paid

#6494 Add logo and info
  blockchains/smartchain/assets/0xEE738a9e5FB78c24D26ceCD30389ED977C38D0Ca/info.json
  blockchains/smartchain/assets/0xEE738a9e5FB78c24D26ceCD30389ED977C38D0Ca/logo.png
Labels: Payment Status: Paid

#6587 [Internal] Bot config (collaborators)
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#6576 Add Rope Token (ROPE) (SPL)
  blockchains/solana/assets/8PMHT4swUMtBzgHnh5U564N5sjPSiUz2cjEQzFnnP1Fo/info.json
  blockchains/solana/assets/8PMHT4swUMtBzgHnh5U564N5sjPSiUz2cjEQzFnnP1Fo/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6592 Add Spaceman(SML) Logo and Info
  blockchains/smartchain/assets/0xD930f493E153d745aFB124F9859bE8479e4b1862/info.json
  blockchains/smartchain/assets/0xD930f493E153d745aFB124F9859bE8479e4b1862/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6544 Add BDCC COIN (BEP20)
  blockchains/smartchain/assets/0x5b8DC8b4f438b1932Ddb2F320b4b7Ea65BA41798/info.json
  blockchains/smartchain/assets/0x5b8DC8b4f438b1932Ddb2F320b4b7Ea65BA41798/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6543 add PAPEL token info and logo
  blockchains/smartchain/assets/0x557dd6700e66818AF340ccE17FD4508CED81fBc1/info.json
  blockchains/smartchain/assets/0x557dd6700e66818AF340ccE17FD4508CED81fBc1/logo.png
Labels: Payment Status: Paid

#6578 Add World of Whales (BEP20)
  blockchains/smartchain/assets/0x2DD337F94A36449C6e5fD4f523Ce2e55A5Ad1008/info.json
  blockchains/smartchain/assets/0x2DD337F94A36449C6e5fD4f523Ce2e55A5Ad1008/logo.png
Labels: Payment Status: Paid

#6584 update/change new logo on trustwallet
  blockchains/smartchain/assets/0xFd91Fa8fab5cA11569E256fa8844Bc2abecc331D/info.json
  blockchains/smartchain/assets/0xFd91Fa8fab5cA11569E256fa8844Bc2abecc331D/logo.png
Labels: Payment Status: Paid

#6588 Add Satozhi (BEP20)
  blockchains/smartchain/assets/0xf4341fA52669cea0c1836095529A7E9B04b8b88D/info.json
  blockchains/smartchain/assets/0xf4341fA52669cea0c1836095529A7E9B04b8b88D/logo.png
Labels: Payment Status: Paid

#6596 Add DAFI Token (DAFI) (ERC20)
  blockchains/ethereum/assets/0xFc979087305A826c2B2a0056cFAbA50aad3E6439/info.json
  blockchains/ethereum/assets/0xFc979087305A826c2B2a0056cFAbA50aad3E6439/logo.png
Labels: Payment Status: Paid

#6593 Add logo The Luxury Coin (TLB)
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e/info.json
  blockchains/smartchain/assets/0xB5791d504367dEE4BA3A379fb3d3d5A6B955cb2e/logo.png
Labels: Payment Status: Paid

#6559 Add Wrapped Navcoin (WNAV)
  blockchains/smartchain/assets/0xBFEf6cCFC830D3BaCA4F6766a0d4AaA242Ca9F3D/info.json
  blockchains/smartchain/assets/0xBFEf6cCFC830D3BaCA4F6766a0d4AaA242Ca9F3D/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#6602 Add UDT (ERC20)
  blockchains/ethereum/assets/0x90DE74265a416e1393A450752175AED98fe11517/info.json
  blockchains/ethereum/assets/0x90DE74265a416e1393A450752175AED98fe11517/logo.png
Labels: Payment Status: Paid

#6603 Adding Logo for Moonstar Token
  blockchains/smartchain/assets/0xCe5814eFfF15D53EFd8025B9F2006D4d7D640b9B/info.json
  blockchains/smartchain/assets/0xCe5814eFfF15D53EFd8025B9F2006D4d7D640b9B/logo.png
Labels: Payment Status: Paid

#6605 Add MUST logo and info
  blockchains/smartchain/assets/0xa042d20aBE198E516d885Da52a633B6D44F339B9/info.json
  blockchains/smartchain/assets/0xa042d20aBE198E516d885Da52a633B6D44F339B9/logo.png
Labels: Payment Status: Paid

#6585 Add BCMC1 logo & info
  blockchains/ethereum/assets/0xD5e2A54Fef5f9E4A6b21EC646Bbed7A160a00F18/info.json
  blockchains/ethereum/assets/0xD5e2A54Fef5f9E4A6b21EC646Bbed7A160a00F18/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6536 Add SafeGalaxy (BEP20)
  blockchains/smartchain/assets/0x6b51231c43B1604815313801dB5E9E614914d6e4/info.json
  blockchains/smartchain/assets/0x6b51231c43B1604815313801dB5E9E614914d6e4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
