Repository trustwallet/assets, pull requests merged in 2021-12, with the labels that each got.

#16030 Add binance-peg tag
  .github/assets.config.yaml
  blockchains/smartchain/assets/0x0Eb3a705fc54725037CC9e008bDede697f62F335/info.json
  blockchains/smartchain/assets/0x101d82428437127bF1608F699CD651e6Abf9766E/info.json
  blockchains/smartchain/assets/0x14016E85a25aeb13065688cAFB43044C2ef86784/info.json
  blockchains/smartchain/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/info.json
  blockchains/smartchain/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/info.json
  blockchains/smartchain/assets/0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb/info.json
  blockchains/smartchain/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/info.json
  blockchains/smartchain/assets/0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63/info.json
  blockchains/smartchain/assets/0x1f9f6a696C6Fd109cD3956F45dC709d2b3902163/info.json
  blockchains/smartchain/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/info.json
  blockchains/smartchain/assets/0x2859e4544C4bB03966803b044A93563Bd2D0DD4D/info.json
  blockchains/smartchain/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/info.json
  blockchains/smartchain/assets/0x3d6545b08693daE087E957cb1180ee38B9e3c25E/info.json
  blockchains/smartchain/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/info.json
  blockchains/smartchain/assets/0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8/info.json
  blockchains/smartchain/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/info.json
  blockchains/smartchain/assets/0x715D400F88C167884bbCc41C5FeA407ed4D2f8A0/info.json
  blockchains/smartchain/assets/0x8076C74C5e3F5852037F31Ff0093Eeb8c8ADd8D3/info.json
  blockchains/smartchain/assets/0x8595F9dA7b868b1822194fAEd312235E43007b49/info.json
  blockchains/smartchain/assets/0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e/info.json
  blockchains/smartchain/assets/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d/info.json
  blockchains/smartchain/assets/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5/info.json
  blockchains/smartchain/assets/0x9Ac983826058b8a9C7Aa1C9171441191232E8404/info.json
  blockchains/smartchain/assets/0xBf5140A22578168FD562DCcF235E5D43A02ce9B1/info.json
  blockchains/smartchain/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/smartchain/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/info.json
  blockchains/smartchain/assets/0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094/info.json
  blockchains/smartchain/assets/0xbA2aE424d960c26247Dd6c32edC70B295c744C43/info.json
  blockchains/smartchain/assets/0xbF7c81FFF98BbE61B40Ed186e4AfD6DDd01337fe/info.json
  blockchains/smartchain/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/info.json
  script/tags-config.ts
Labels: Payment Status: Paid

#16263 Add DART Inu (BEP20)
  blockchains/smartchain/assets/0x49152DD96bE5a710fAcF9a8aB7DE4343A49186d5/info.json
  blockchains/smartchain/assets/0x49152DD96bE5a710fAcF9a8aB7DE4343A49186d5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16265 Add Doge Raca (BEP20)
  blockchains/smartchain/assets/0xB547607EAE3B10d94B211DA84A3B51BFa545774d/info.json
  blockchains/smartchain/assets/0xB547607EAE3B10d94B211DA84A3B51BFa545774d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16283 Add BIGH BULL (BEP20)
  blockchains/smartchain/assets/0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62/info.json
  blockchains/smartchain/assets/0x64B55Bb2F27c3710349d9cA024d0D1Ff2DAB7f62/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16262 Add Consensus One Validator to Kava
  blockchains/kava/validators/assets/kavavaloper1m8428ygqwa4yahjtc9ulp9n7eqwt7dn37n8vas/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#16280 Add CHEEMSINU (BEP20)
  blockchains/smartchain/assets/0xdFE6891ce8E5a5c7Cf54fFdE406A6C2C54145F71/info.json
  blockchains/smartchain/assets/0xdFE6891ce8E5a5c7Cf54fFdE406A6C2C54145F71/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16237 Add metaraca info
  blockchains/smartchain/assets/0x63eC19c2983bfB0D43232aa9C792Fe6F27F63361/info.json
  blockchains/smartchain/assets/0x63eC19c2983bfB0D43232aa9C792Fe6F27F63361/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16302 add MSCP logo and info
  blockchains/smartchain/assets/0x27d72484f1910F5d0226aFA4E03742c9cd2B297a/info.json
  blockchains/smartchain/assets/0x27d72484f1910F5d0226aFA4E03742c9cd2B297a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16313 Change status and delete logo XDATA
  blockchains/ethereum/assets/0x0Cf0Ee63788A0849fE5297F3407f701E122cC023/info.json
  blockchains/ethereum/assets/0x0Cf0Ee63788A0849fE5297F3407f701E122cC023/logo.png
Labels: Payment Status: Paid

#16275 Add Streamr (ERC20)
  blockchains/ethereum/assets/0x8f693ca8D21b157107184d29D398A8D082b38b76/info.json
  blockchains/ethereum/assets/0x8f693ca8D21b157107184d29D398A8D082b38b76/logo.png
Labels: Payment Status: Paid

#16316 Change status for SALSA
  blockchains/ethereum/assets/0x82E5aeC4e37b37FCA34925C13429506209A98536/info.json
  blockchains/ethereum/assets/0x82E5aeC4e37b37FCA34925C13429506209A98536/logo.png
Labels: Payment Status: Paid

#13043 Adding info and logo Sphynx Network (SPH) Token
  blockchains/smartchain/assets/0x8bAc6b4AF65C8c1967a0FBc27cd37FD6059daa00/info.json
  blockchains/smartchain/assets/0x8bAc6b4AF65C8c1967a0FBc27cd37FD6059daa00/logo.png
Labels: Payment Status: Paid

#16314 Add Polkalokr (BEP20)
  blockchains/smartchain/assets/0xA5Ff48e326958E0CE6FdF9518de561F2B5f57dA3/info.json
  blockchains/smartchain/assets/0xA5Ff48e326958E0CE6FdF9518de561F2B5f57dA3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16318 Change status for old Xtremcoin
  blockchains/smartchain/assets/0x927fF4AD97991C1eeC44AB02c6970088ffa85250/info.json
  blockchains/smartchain/assets/0x927fF4AD97991C1eeC44AB02c6970088ffa85250/logo.png
Labels: Payment Status: Paid

#16317 Add Xtremcoin (BEP20)
  blockchains/smartchain/assets/0x5EcFcced226bA9fCcD8663e7b3263cBd8C84eDB5/info.json
  blockchains/smartchain/assets/0x5EcFcced226bA9fCcD8663e7b3263cBd8C84eDB5/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#16309 Add Gyro DAO (BEP20)
  blockchains/smartchain/assets/0x1B239ABe619e74232c827FBE5E49a4C072bD869D/info.json
  blockchains/smartchain/assets/0x1B239ABe619e74232c827FBE5E49a4C072bD869D/logo.png
Labels: Payment Status: Paid

#16308 Token logo submit
  blockchains/smartchain/assets/0x80d04E44955AA9c3F24041B2A824A20A88E735a8/info.json
  blockchains/smartchain/assets/0x80d04E44955AA9c3F24041B2A824A20A88E735a8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16341 Laqira Protocol (LQR) token was added to TrustWallet repo
  blockchains/smartchain/assets/0xbc81ea817b579eC0334BcA8E65E436b7cB540147/info.json
  blockchains/smartchain/assets/0xbc81ea817b579eC0334BcA8E65E436b7cB540147/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#16373 Add Transhuman Coin (BEP20)
  blockchains/smartchain/assets/0x56083560594E314b5cDd1680eC6a493bb851BBd8/info.json
  blockchains/smartchain/assets/0x56083560594E314b5cDd1680eC6a493bb851BBd8/logo.png
Labels: Payment Status: Paid

#16374 Add Lunar (BEP20)
  blockchains/smartchain/assets/0x9D4451151A8dE5B545a1bC6c8fdEB9d94a2868e1/info.json
  blockchains/smartchain/assets/0x9D4451151A8dE5B545a1bC6c8fdEB9d94a2868e1/logo.png
Labels: Payment Status: Paid

#16387 Add Celo cUSD cEUR (ERC20)
  blockchains/celo/info/0x765DE816845861e75A25fCA122bb6898B8B1282a/info.json
  blockchains/celo/info/0x765DE816845861e75A25fCA122bb6898B8B1282a/logo.png
  blockchains/celo/info/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73/info.json
  blockchains/celo/info/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73/logo.png
Labels: Payment Status: Paid

#16414 Add validator Blockdaemon (cosmos)
  blockchains/cosmos/validators/assets/cosmosvaloper10nzaaeh2kq28t3nqsh5m8kmyv90vx7ym5mpakx/logo.png
  blockchains/cosmos/validators/list.json
Labels: Payment Status: Paid

#13866 Add MCB (BEP20) token
  blockchains/smartchain/assets/0x5fE80d2CD054645b9419657d3d10d26391780A7B/info.json
  blockchains/smartchain/assets/0x5fE80d2CD054645b9419657d3d10d26391780A7B/logo.png
Labels: Payment Status: Paid

#16384 Adding token information and logo for Magic Internet Money
  blockchains/ethereum/assets/0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3/info.json
  blockchains/ethereum/assets/0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3/logo.png
Labels: Payment Status: Paid

#16168 Add ATL logo and info
  blockchains/smartchain/assets/0x1fD991fb6c3102873ba68a4e6e6a87B3a5c10271/info.json
  blockchains/smartchain/assets/0x1fD991fb6c3102873ba68a4e6e6a87B3a5c10271/logo.png
Labels: Status: On Hold, Payment Status: Paid

#16426 put celo assets to correct location
  blockchains/celo/assets/0x765DE816845861e75A25fCA122bb6898B8B1282a/info.json
  blockchains/celo/assets/0x765DE816845861e75A25fCA122bb6898B8B1282a/logo.png
  blockchains/celo/assets/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73/info.json
  blockchains/celo/assets/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73/logo.png
  script/generic/asset-infos.ts
Labels: Payment Status: Requested

#16375 Add HODL (BEP20)
  blockchains/smartchain/assets/0x0E9766dF73973abCfEDDE700497c57110ee5c301/info.json
  blockchains/smartchain/assets/0x0E9766dF73973abCfEDDE700497c57110ee5c301/logo.png
Labels: Payment Status: Paid

#16441 Add Shiba Games (BEP20)
  blockchains/smartchain/assets/0x0EA526b4799541797D8b880b48Cc65d71d1e273B/info.json
  blockchains/smartchain/assets/0x0EA526b4799541797D8b880b48Cc65d71d1e273B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16428 Add Thetan Token (BEP20)
  blockchains/smartchain/assets/0x9fD87aEfe02441B123c3c32466cD9dB4c578618f/info.json
  blockchains/smartchain/assets/0x9fD87aEfe02441B123c3c32466cD9dB4c578618f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16450 Add P2E Token (BEP20)
  blockchains/smartchain/assets/0x7f9C20c4C09c32478AE10A7543E5199C2F53691d/info.json
  blockchains/smartchain/assets/0x7f9C20c4C09c32478AE10A7543E5199C2F53691d/logo.png
Labels: Payment Status: Paid

#16459 Re-add Nuke logo and info + audiit
  blockchains/smartchain/assets/0x03C580eecf2c36Ab8a77a71d56d867EcD495552D/info.json
  blockchains/smartchain/assets/0x03C580eecf2c36Ab8a77a71d56d867EcD495552D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16470 Add tag stablecoin
  blockchains/celo/assets/0x765DE816845861e75A25fCA122bb6898B8B1282a/info.json
  blockchains/celo/assets/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73/info.json
  blockchains/ethereum/assets/0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd/info.json
  blockchains/ethereum/assets/0x122A86b5DFF2D085AfB49600b4cd7375D0d94A5f/info.json
  blockchains/ethereum/assets/0x196f4727526eA7FB1e17b2071B3d8eAA38486988/info.json
  blockchains/ethereum/assets/0x1c48f86ae57291F7686349F12601910BD8D470bb/info.json
  blockchains/ethereum/assets/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86/info.json
  blockchains/ethereum/assets/0x4DF812F6064def1e5e029f1ca858777CC98D2D81/info.json
  blockchains/ethereum/assets/0x4Fabb145d64652a948d72533023f6E7A623C7C53/info.json
  blockchains/ethereum/assets/0x4f3AfEC4E5a3F2A6a1A411DEF7D7dFe50eE057bF/info.json
  blockchains/ethereum/assets/0x57Ab1E02fEE23774580C119740129eAC7081e9D3/info.json
  blockchains/ethereum/assets/0x674C6Ad92Fd080e4004b2312b45f796a192D27a0/info.json
  blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json
  blockchains/ethereum/assets/0x70e8dE73cE538DA2bEEd35d14187F6959a8ecA96/info.json
  blockchains/ethereum/assets/0x853d955aCEf822Db058eb8505911ED77F175b99e/info.json
  blockchains/ethereum/assets/0x8762db106B2c2A0bccB3A80d1Ed41273552616E8/info.json
  blockchains/ethereum/assets/0x8E870D67F660D95d5be530380D0eC0bd388289E1/info.json
  blockchains/ethereum/assets/0x956F47F50A910163D8BF957Cf5846D573E7f87CA/info.json
  blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/info.json
  blockchains/ethereum/assets/0xA4Bdb11dc0a2bEC88d24A3aa1E6Bb17201112eBe/info.json
  blockchains/ethereum/assets/0xB4272071eCAdd69d933AdcD19cA99fe80664fc08/info.json
  blockchains/ethereum/assets/0xE0B7927c4aF23765Cb51314A0E0521A9645F0E2A/info.json
  blockchains/ethereum/assets/0xa47c8bf37f92aBed4A126BDA807A7b7498661acD/info.json
  blockchains/ethereum/assets/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B/info.json
  blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/info.json
  blockchains/ethereum/assets/0xdB25f211AB05b1c97D595516F45794528a807ad8/info.json
  blockchains/ethereum/assets/0xdF574c24545E5FfEcb9a659c229253D4111d87e1/info.json
  blockchains/ethereum/assets/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5/info.json
  blockchains/smartchain/assets/0x4BD17003473389A42DAF6a0a729f6Fdb328BbBd7/info.json
Labels: Payment Status: Paid

#16439 Add Zuki Moba (BEP20)
  blockchains/smartchain/assets/0xE81257d932280AE440B17AFc5f07C8A110D21432/info.json
  blockchains/smartchain/assets/0xE81257d932280AE440B17AFc5f07C8A110D21432/logo.png
Labels: Payment Status: Paid

#16482 Add GamingShiba (BEP20)
  blockchains/smartchain/assets/0x41cf3E9534156405a133Cda545aF9fF0E586500A/info.json
  blockchains/smartchain/assets/0x41cf3E9534156405a133Cda545aF9fF0E586500A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16451 add Mars Ecosystem assets info
  blockchains/smartchain/assets/0x7859B01BbF675d67Da8cD128a50D155cd881B576/info.json
  blockchains/smartchain/assets/0x7859B01BbF675d67Da8cD128a50D155cd881B576/logo.png
  dapps/app.marsecosystem.com.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16486 Add new file ad logo
  blockchains/smartchain/assets/0xb07905396A419B121213efe1d17cfD0ff20aE597/info.json
  blockchains/smartchain/assets/0xb07905396A419B121213efe1d17cfD0ff20aE597/logo.png
Labels: Payment Status: Paid

#16438 Add KOROMARU (KOROMARU) (ERC20)
  blockchains/ethereum/assets/0xD0D42005e7B3c0812b1268F0e5FAF97Ff2423651/info.json
  blockchains/ethereum/assets/0xD0D42005e7B3c0812b1268F0e5FAF97Ff2423651/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16501 Add DOGEDI (BEP20)
  blockchains/smartchain/assets/0xDc49d53330317cBc6924fA53042e0C9bCa0A8d63/info.json
  blockchains/smartchain/assets/0xDc49d53330317cBc6924fA53042e0C9bCa0A8d63/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16409 Update logo for $EGC
  blockchains/smartchain/assets/0xC001BBe2B87079294C63EcE98BdD0a88D761434e/info.json
Labels: Status: Correction needed, Payment Status: Paid

#16446 Add CANDYLAD (BEP20)
  blockchains/smartchain/assets/0x136BFcdec5DB31b565052451AD806014ab9F2b38/info.json
  blockchains/smartchain/assets/0x136BFcdec5DB31b565052451AD806014ab9F2b38/logo.png
Labels: Payment Status: Paid

#16435 Added token information and logo for GMR v2
  blockchains/smartchain/assets/0xADCa52302e0a6c2d5D68EDCdB4Ac75DeB5466884/info.json
  blockchains/smartchain/assets/0xADCa52302e0a6c2d5D68EDCdB4Ac75DeB5466884/logo.png
Labels: Payment Status: Paid

#16526 Add CEEK (BEP20)
  blockchains/smartchain/assets/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66/info.json
  blockchains/smartchain/assets/0xe0F94Ac5462997D2BC57287Ac3a3aE4C31345D66/logo.png
Labels: Payment Status: Paid

#16543 Add MetaMatrix (BEP20)
  blockchains/smartchain/assets/0xD1A6eFF20958403F9fa137760e62dfDE4516a0b1/info.json
  blockchains/smartchain/assets/0xD1A6eFF20958403F9fa137760e62dfDE4516a0b1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16504 Add MetaPets (BEP20)
  blockchains/smartchain/assets/0x24cE3d571fBcFD9D81dc0e1a560504636a4D046d/info.json
  blockchains/smartchain/assets/0x24cE3d571fBcFD9D81dc0e1a560504636a4D046d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16553 Add Project-X (BEP20)
  blockchains/smartchain/assets/0x2963dCc52549573BBFBe355674724528532C0867/info.json
  blockchains/smartchain/assets/0x2963dCc52549573BBFBe355674724528532C0867/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16535 Add SavePlanetEarth V3 (BEP20)
  blockchains/smartchain/assets/0x4ac81e3631DcDa62109e3117c4CAE7bf70BbbbD2/info.json
  blockchains/smartchain/assets/0x4ac81e3631DcDa62109e3117c4CAE7bf70BbbbD2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16555 update Netcoincapital smartcontract
  blockchains/tron/assets/TCDgp5bwtixaShPifUm7HpZ71C1pe6zif1/info.json
  blockchains/tron/assets/TCDgp5bwtixaShPifUm7HpZ71C1pe6zif1/logo.png
Labels: Payment Status: Paid

#16566 Add Black Phoenix (TRC20)
  blockchains/tron/assets/TXBcx59eDVndV5upFQnTR2xdvqFd5reXET/info.json
  blockchains/tron/assets/TXBcx59eDVndV5upFQnTR2xdvqFd5reXET/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16582 Add Andromeda V2 (BEP20)
  blockchains/smartchain/assets/0xB46aCB1f8D0fF6369C2f00146897aeA1dFCf2414/info.json
  blockchains/smartchain/assets/0xB46aCB1f8D0fF6369C2f00146897aeA1dFCf2414/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16565 Add Zuna (BEP20)
  blockchains/smartchain/assets/0x5D07eDAbA2151a3C6802B28636eCC23082398EdB/info.json
  blockchains/smartchain/assets/0x5D07eDAbA2151a3C6802B28636eCC23082398EdB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16593 Add tag governance
  blockchains/ethereum/assets/0x054D64b73d3D8A21Af3D764eFd76bCaA774f3Bb2/info.json
  blockchains/ethereum/assets/0x0E29e5AbbB5FD88e28b2d355774e73BD47dE3bcd/info.json
  blockchains/ethereum/assets/0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e/info.json
  blockchains/ethereum/assets/0x0f51bb10119727a7e5eA3538074fb341F56B09Ad/info.json
  blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B/info.json
  blockchains/ethereum/assets/0x1FCdcE58959f536621d76f5b7FfB955baa5A672F/info.json
  blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/info.json
  blockchains/ethereum/assets/0x28cb7e841ee97947a86B06fA4090C8451f64c0be/info.json
  blockchains/ethereum/assets/0x2ba592F78dB6436527729929AAf6c908497cB200/info.json
  blockchains/ethereum/assets/0x3472A5A71965499acd81997a54BBA8D852C6E53d/info.json
  blockchains/ethereum/assets/0x5218E472cFCFE0b64A064F055B43b4cdC9EfD3A6/info.json
  blockchains/ethereum/assets/0x62359Ed7505Efc61FF1D56fEF82158CcaffA23D7/info.json
  blockchains/ethereum/assets/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2/info.json
  blockchains/ethereum/assets/0x7240aC91f01233BaAf8b064248E80feaA5912BA3/info.json
  blockchains/ethereum/assets/0x77FbA179C79De5B7653F68b5039Af940AdA60ce0/info.json
  blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/info.json
  blockchains/ethereum/assets/0x8798249c2E607446EfB7Ad49eC89dD1865Ff4272/info.json
  blockchains/ethereum/assets/0x88EF27e69108B2633F8E1C184CC37940A075cC02/info.json
  blockchains/ethereum/assets/0x89Ab32156e46F46D02ade3FEcbe5Fc4243B9AAeD/info.json
  blockchains/ethereum/assets/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2/info.json
  blockchains/ethereum/assets/0xB8BAa0e4287890a5F79863aB62b7F175ceCbD433/info.json
  blockchains/ethereum/assets/0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F/info.json
  blockchains/ethereum/assets/0xD291E7a03283640FDc51b121aC401383A46cC623/info.json
  blockchains/ethereum/assets/0xD533a949740bb3306d119CC777fa900bA034cd52/info.json
  blockchains/ethereum/assets/0xD7EFB00d12C2c13131FD319336Fdf952525dA2af/info.json
  blockchains/ethereum/assets/0xE41d2489571d322189246DaFA5ebDe1F4699F498/info.json
  blockchains/ethereum/assets/0xEd0439EACf4c4965AE4613D77a5C2Efe10e5f183/info.json
  blockchains/ethereum/assets/0xFca59Cd816aB1eaD66534D82bc21E7515cE441CF/info.json
  blockchains/ethereum/assets/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521/info.json
  blockchains/ethereum/assets/0xc3771d47E2Ab5A519E2917E61e23078d0C05Ed7f/info.json
  blockchains/ethereum/assets/0xc7283b66Eb1EB5FB86327f08e1B5816b0720212B/info.json
  blockchains/ethereum/assets/0xca1207647Ff814039530D7d35df0e1Dd2e91Fa84/info.json
  blockchains/ethereum/assets/0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202/info.json
  blockchains/ethereum/assets/0xf4CD3d3Fda8d7Fd6C5a500203e38640A70Bf9577/info.json
  blockchains/smartchain/assets/0xF6Cb4ad242BaB681EfFc5dE40f7c8FF921a12d63/info.json
  blockchains/solana/assets/MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac/info.json
Labels: Payment Status: Paid

#16586 Add Portuma (BEP20)
  blockchains/smartchain/assets/0x9000Cac49C3841926Baac5b2E13c87D43e51B6a4/info.json
  blockchains/smartchain/assets/0x9000Cac49C3841926Baac5b2E13c87D43e51B6a4/logo.png
Labels: Payment Status: Paid

#16573 Add files via upload
  blockchains/smartchain/assets/0x87ECEa8512516Ced5db9375c63c23A0846c73a57/info.json
  blockchains/smartchain/assets/0x87ECEa8512516Ced5db9375c63c23A0846c73a57/logo.png
Labels: Payment Status: Paid

#16564 Add Facebook Metaverse (BEP20)
  blockchains/smartchain/assets/0x3e0b5807515756635c6347CDeeBF95946E604BCF/info.json
  blockchains/smartchain/assets/0x3e0b5807515756635c6347CDeeBF95946E604BCF/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16610 Add ISLAMICOIN (POLYGON)
  blockchains/polygon/assets/0x9c891326fd8b1a713974f73bb604677e1e63396d/info.json
  blockchains/polygon/assets/0x9c891326fd8b1a713974f73bb604677e1e63396d/logo.png
Labels: Payment Status: Paid

#16613 Add ELMON info and logo
  blockchains/smartchain/assets/0xE3233fdb23F1c27aB37Bd66A19a1f1762fCf5f3F/info.json
  blockchains/smartchain/assets/0xE3233fdb23F1c27aB37Bd66A19a1f1762fCf5f3F/logo.png
Labels: Payment Status: Paid

#16631 Add KmonCoin (BEP20)
  blockchains/smartchain/assets/0xc732B6586A93b6B7CF5FeD3470808Bc74998224D/info.json
  blockchains/smartchain/assets/0xc732B6586A93b6B7CF5FeD3470808Bc74998224D/logo.png
Labels: Payment Status: Paid

#16635 Add tag wrapped
  blockchains/ethereum/assets/0x09a3EcAFa817268f77BE1283176B946C4ff2E608/info.json
  blockchains/ethereum/assets/0x0cae9e4d663793c2a2A0b211c1Cf4bBca2B9cAa7/info.json
  blockchains/ethereum/assets/0x13B02c8dE71680e71F0820c996E4bE43c2F57d15/info.json
  blockchains/ethereum/assets/0x21cA39943E91d704678F5D00b6616650F066fD63/info.json
  blockchains/ethereum/assets/0x41BbEDd7286dAab5910a1f15d12CBda839852BD7/info.json
  blockchains/ethereum/assets/0x56aA298a19C93c6801FDde870fA63EF75Cc0aF72/info.json
  blockchains/ethereum/assets/0x59A921Db27Dd6d4d974745B7FfC5c33932653442/info.json
  blockchains/ethereum/assets/0x9d1555d8cB3C846Bb4f7D5B1B1080872c3166676/info.json
  blockchains/ethereum/assets/0xC8d674114bac90148d11D3C1d33C61835a0F9DCD/info.json
  blockchains/ethereum/assets/0xd36932143F6eBDEDD872D5Fb0651f4B72Fd15a84/info.json
  blockchains/ethereum/assets/0xf72FCd9DCF0190923Fadd44811E240Ef4533fc86/info.json
Labels: Payment Status: Paid

#16634 invlidate cloudfront on new assets upload to s3
  .github/workflows/s3_upload.yml
Labels: Payment Status: Requested

#16618 Add REALM token for ETH and BSC chains
  blockchains/ethereum/assets/0x464FdB8AFFC9bac185A7393fd4298137866DCFB8/info.json
  blockchains/ethereum/assets/0x464FdB8AFFC9bac185A7393fd4298137866DCFB8/logo.png
  blockchains/smartchain/assets/0x464FdB8AFFC9bac185A7393fd4298137866DCFB8/info.json
  blockchains/smartchain/assets/0x464FdB8AFFC9bac185A7393fd4298137866DCFB8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16623 Add Merchant Token (MTO) (ERC20)
  blockchains/ethereum/assets/0xE66b3AA360bB78468c00Bebe163630269DB3324F/info.json
  blockchains/ethereum/assets/0xE66b3AA360bB78468c00Bebe163630269DB3324F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16646 Add CryptoGuards (BEP20)
  blockchains/smartchain/assets/0x432C7cf1dE2b97a013f1130f199ed9d1363215BA/info.json
  blockchains/smartchain/assets/0x432C7cf1dE2b97a013f1130f199ed9d1363215BA/logo.png
Labels: Payment Status: Paid

#16659 Add tag deflationary
  blockchains/ethereum/assets/0x27C70Cd1946795B66be9d954418546998b546634/info.json
  blockchains/ethereum/assets/0x3301Ee63Fb29F863f2333Bd4466acb46CD8323E6/info.json
  blockchains/ethereum/assets/0x43f11c02439e2736800433b4594994Bd43Cd066D/info.json
  blockchains/ethereum/assets/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE/info.json
  blockchains/ethereum/assets/0xbb1EE07d6c7BAeB702949904080eb61f5D5e7732/info.json
  blockchains/ethereum/assets/0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA/info.json
  blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607/info.json
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/info.json
  blockchains/smartchain/assets/0xE4FAE3Faa8300810C835970b9187c268f55D998F/info.json
  blockchains/solana/assets/9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE/info.json
Labels: Payment Status: Paid

#16652 Add files via upload
  blockchains/smartchain/assets/0xF73d8276C15Ce56b2f4AeE5920e62F767A7f3aEA/info.json
  blockchains/smartchain/assets/0xF73d8276C15Ce56b2f4AeE5920e62F767A7f3aEA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16500 Update for token info and image
  blockchains/tron/assets/1002357/info.json
  blockchains/tron/assets/1002357/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#16639 only invalidate if added or modified files
  .github/workflows/s3_upload.yml
Labels: Payment Status: Requested

#16641 Add FoxGirl (BEP20)
  blockchains/smartchain/assets/0x599beec263FA6eA35055011967597B259FC012A4/info.json
  blockchains/smartchain/assets/0x599beec263FA6eA35055011967597B259FC012A4/logo.png
Labels: Payment Status: Paid

#16697 KODA migration
  blockchains/smartchain/assets/0x9E993671976a5AC51bBfB3Db9E34eAC8d518fe82/info.json
  blockchains/smartchain/assets/0x9E993671976a5AC51bBfB3Db9E34eAC8d518fe82/logo.png
Labels: Payment Status: Paid

#16681 PumpETH Logo Update
  blockchains/smartchain/assets/0x2e74Ee4fc4466d0883eF5E12A0Ce344BFe15BE8D/info.json
  blockchains/smartchain/assets/0x2e74Ee4fc4466d0883eF5E12A0Ce344BFe15BE8D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16729 s3_upload workflow typo fixed
  .github/workflows/s3_upload.yml
Labels: Payment Status: Requested

#16711 Add VITE token
  blockchains/smartchain/assets/0x2794DAD4077602eD25A88d03781528D1637898B4/info.json
  blockchains/smartchain/assets/0x2794DAD4077602eD25A88d03781528D1637898B4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16735 Add RPL token
  blockchains/ethereum/assets/0xD33526068D116cE69F19A9ee46F0bd304F21A51f/info.json
  blockchains/ethereum/assets/0xD33526068D116cE69F19A9ee46F0bd304F21A51f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16740 RPL migration
  blockchains/ethereum/assets/0xB4EFd85c19999D84251304bDA99E90B92300Bd93/info.json
  blockchains/ethereum/assets/0xB4EFd85c19999D84251304bDA99E90B92300Bd93/logo.png
Labels: Payment Status: Paid

#16730 added HUH Token files
  blockchains/smartchain/assets/0xc15e89f2149bcc0cbd5fb204c9e77fe878f1e9b2/info.json
  blockchains/smartchain/assets/0xc15e89f2149bcc0cbd5fb204c9e77fe878f1e9b2/logo.png
Labels: Payment Status: Paid

#16745 Add HeroesTD (BEP20)
  blockchains/smartchain/assets/0x5E2689412Fae5c29BD575fbe1d5C1CD1e0622A8f/info.json
  blockchains/smartchain/assets/0x5E2689412Fae5c29BD575fbe1d5C1CD1e0622A8f/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16647 Add METAMUSK Token logo and info
  blockchains/smartchain/assets/0x734c5F3f8F6ad9697b26eCC6388678aaFd3dB3B2/info.json
  blockchains/smartchain/assets/0x734c5F3f8F6ad9697b26eCC6388678aaFd3dB3B2/logo.png
Labels: Status: On Hold, Payment Status: Paid

#16696 Add new KODA V2 coin to TrustWallet
  blockchains/smartchain/assets/0x8094e772fA4A60bdEb1DfEC56AB040e17DD608D5/info.json
  blockchains/smartchain/assets/0x8094e772fA4A60bdEb1DfEC56AB040e17DD608D5/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#16773 Equalizer to Polygon, not a brand new token.
  blockchains/polygon/assets/0xEAf631ac57F3CDDDd261770dD47F85066131a156/info.json
  blockchains/polygon/assets/0xEAf631ac57F3CDDDd261770dD47F85066131a156/logo.png
Labels: Payment Status: Paid

#16792 Add Sphynx BSC (BEP20)
  blockchains/smartchain/assets/0xe64972C311840cFaf2267DCfD365571F9D9544d9/info.json
  blockchains/smartchain/assets/0xe64972C311840cFaf2267DCfD365571F9D9544d9/logo.png
Labels: Payment Status: Paid

#16734 Add TrustWallet Support for GalaxyGoggle
  blockchains/avalanchec/assets/0xF2F7CE610a091B94d41D69f4fF1129434a82E2f0/info.json
  blockchains/avalanchec/assets/0xF2F7CE610a091B94d41D69f4fF1129434a82E2f0/logo.png
Labels: Payment Status: Paid

#16764 Add LIMOCOIN SWAP (BEP20)
  blockchains/smartchain/assets/0x383094a91Ef2767Eed2B063ea40465670bf1C83f/info.json
  blockchains/smartchain/assets/0x383094a91Ef2767Eed2B063ea40465670bf1C83f/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16791 add BinaHero token
  blockchains/smartchain/assets/0x78C3AdE403438B37638304F9FbbFB1b76608c1BD/info.json
  blockchains/smartchain/assets/0x78C3AdE403438B37638304F9FbbFB1b76608c1BD/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16798 Add OpenDAO token (ERC20)
  blockchains/ethereum/assets/0x3b484b82567a09e2588A13D54D032153f0c0aEe0/info.json
  blockchains/ethereum/assets/0x3b484b82567a09e2588A13D54D032153f0c0aEe0/logo.png
Labels: Payment Status: Paid

#16828 Add Shambala (BEP20)
  blockchains/smartchain/assets/0x34bA3af693d6c776d73C7fa67e2B2e79be8ef4ED/info.json
  blockchains/smartchain/assets/0x34bA3af693d6c776d73C7fa67e2B2e79be8ef4ED/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16793 add GYEN
  blockchains/ethereum/assets/0xC08512927D12348F6620a698105e1BAac6EcD911/info.json
  blockchains/ethereum/assets/0xC08512927D12348F6620a698105e1BAac6EcD911/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16856 Add Santa Floki (BEP20)
  blockchains/smartchain/assets/0xb8a5e028f833F08A29564ded368b4CaCB4e18FF5/info.json
  blockchains/smartchain/assets/0xb8a5e028f833F08A29564ded368b4CaCB4e18FF5/logo.png
Labels: Payment Status: Paid

#16801 Add SpookyShiba (BEP20)
  blockchains/smartchain/assets/0xed74Bc5DC139356E08dE28143996F5eF6e4334a4/info.json
  blockchains/smartchain/assets/0xed74Bc5DC139356E08dE28143996F5eF6e4334a4/logo.png
Labels: Payment Status: Paid

#16818 update DEUS token and DEA token, fee already paid 16648
  blockchains/ethereum/assets/0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3/info.json
  blockchains/ethereum/assets/0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3/logo.png
  blockchains/ethereum/assets/0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44/info.json
  blockchains/ethereum/assets/0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44/logo.png
  blockchains/polygon/assets/0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3/info.json
  blockchains/polygon/assets/0xDE12c7959E1a72bbe8a5f7A1dc8f8EeF9Ab011B3/logo.png
  blockchains/polygon/assets/0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44/info.json
  blockchains/polygon/assets/0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44/logo.png
Labels: Payment Status: Paid

#16888 Add TITANO logo and info
  blockchains/smartchain/assets/0xBA96731324dE188ebC1eD87ca74544dDEbC07D7f/info.json
  blockchains/smartchain/assets/0xBA96731324dE188ebC1eD87ca74544dDEbC07D7f/logo.png
Labels: Payment Status: Paid

#16905 Add Parallel Token (BEP20)
  blockchains/smartchain/assets/0xd07e82440A395f3F3551b42dA9210CD1Ef4f8B24/info.json
  blockchains/smartchain/assets/0xd07e82440A395f3F3551b42dA9210CD1Ef4f8B24/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16889 Add Streamr (POLYGON)
  blockchains/polygon/assets/0x3a9A81d576d83FF21f26f325066054540720fC34/info.json
  blockchains/polygon/assets/0x3a9A81d576d83FF21f26f325066054540720fC34/logo.png
Labels: Payment Status: Paid

#16887 Add Streamr (BEP20)
  blockchains/smartchain/assets/0x0864c156b3C5F69824564dEC60c629aE6401bf2a/info.json
  blockchains/smartchain/assets/0x0864c156b3C5F69824564dEC60c629aE6401bf2a/logo.png
Labels: Payment Status: Paid

#16886 DOGO logo update
  blockchains/smartchain/assets/0x9E6B3E35c8f563B45d864f9Ff697A144ad28A371/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16912 Change logo for Spell Token (ERC20)
  blockchains/ethereum/assets/0x090185f2135308BaD17527004364eBcC2D37e5F6/logo.png
Labels: Payment Status: Paid

#15503 Add IDM Token (BEP20)
  blockchains/smartchain/assets/0x14B13E06f75E1F0Fd51ca2E699589Ef398E10F4C/info.json
  blockchains/smartchain/assets/0x14B13E06f75E1F0Fd51ca2E699589Ef398E10F4C/logo.png
Labels: Payment Status: Paid

#16902 Add LucidLandsGem (BEP20)
  blockchains/smartchain/assets/0x4691F60c894d3f16047824004420542E4674E621/info.json
  blockchains/smartchain/assets/0x4691F60c894d3f16047824004420542E4674E621/logo.png
Labels: Payment Status: Paid

#16927 New Year Token binance smart chain
  blockchains/smartchain/assets/0xfDfF7a8eDA6a3739132867f989bE4bf84E803c15/info.json
  blockchains/smartchain/assets/0xfDfF7a8eDA6a3739132867f989bE4bf84E803c15/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16920 Migration for SAFEMOON (BEP20)
  blockchains/smartchain/assets/0x42981d0bfbAf196529376EE702F2a9Eb9092fcB5/info.json
  blockchains/smartchain/assets/0x42981d0bfbAf196529376EE702F2a9Eb9092fcB5/logo.png
  blockchains/smartchain/assets/0x8076C74C5e3F5852037F31Ff0093Eeb8c8ADd8D3/info.json
  blockchains/smartchain/assets/0x8076C74C5e3F5852037F31Ff0093Eeb8c8ADd8D3/logo.png
Labels: Payment Status: Paid

#16957 add Coinscope token info
  blockchains/smartchain/assets/0xD41C4805A9A3128f9F7A7074Da25965371Ba50d5/info.json
  blockchains/smartchain/assets/0xD41C4805A9A3128f9F7A7074Da25965371Ba50d5/logo.png
Labels: Payment Status: Paid

#16947 Adding SILVA
  blockchains/smartchain/assets/0x68b5edb385b59E30a7A7Db1E681a449E94DF0213/info.json
  blockchains/smartchain/assets/0x68b5edb385b59E30a7A7Db1E681a449E94DF0213/logo.png
Labels: Payment Status: Paid

#16936 Add Life Token v2 (BEP20)
  blockchains/smartchain/assets/0x167e5455E4C978883B414E7f02c0147eec9a18e9/info.json
  blockchains/smartchain/assets/0x167e5455E4C978883B414E7f02c0147eec9a18e9/logo.png
Labels: Status: Correction needed, Payment Status: Paid
