Repository trustwallet/assets, pull requests merged in 2021-09, with the labels that each got.

#13248 [Internal] Opensea.io icon updated
  dapps/opensea.io.png
Labels: Payment Status: Requested

#13260 Add Diamond Boyz Coin (BEP20)
  blockchains/smartchain/assets/0x7a983559e130723B70e45bd637773DbDfD3F71Db/info.json
  blockchains/smartchain/assets/0x7a983559e130723B70e45bd637773DbDfD3F71Db/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13238 Add LDFI (BEP20)
  blockchains/smartchain/assets/0x8F1E60D84182db487aC235acC65825e50b5477a1/info.json
  blockchains/smartchain/assets/0x8F1E60D84182db487aC235acC65825e50b5477a1/logo.png
Labels: Payment Status: Paid

#13267 Add POTENT (BEP20)
  blockchains/smartchain/assets/0x057AFf3E314e1ca15BED75510df81A20098cE456/info.json
  blockchains/smartchain/assets/0x057AFf3E314e1ca15BED75510df81A20098cE456/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13236 Add CryptoCars (BEP20)
  blockchains/smartchain/assets/0x50332bdca94673F33401776365b66CC4e81aC81d/info.json
  blockchains/smartchain/assets/0x50332bdca94673F33401776365b66CC4e81aC81d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13293 Add fantom blockchain
  blockchains/fantom/allowlist.json
  blockchains/fantom/denylist.json
  blockchains/fantom/info/info.json
  blockchains/fantom/info/logo.png
Labels: Payment Status: Requested

#13296 Add fantom / arbitrum token type
  blockchains/arbitrum/allowlist.json
  blockchains/arbitrum/denylist.json
  blockchains/arbitrum/info/info.json
  blockchains/arbitrum/info/logo.png
  script/generic/asset-infos.ts
  script/generic/blockchains.ts
  script/generic/eth-forks.ts
Labels: Payment Status: Requested

#13264 Add Binemon (BIN) info and logo
  blockchains/smartchain/assets/0xe56842Ed550Ff2794F010738554db45E60730371/info.json
  blockchains/smartchain/assets/0xe56842Ed550Ff2794F010738554db45E60730371/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13308 BUMN Logo - Revised Audit Report Release
  blockchains/smartchain/assets/0x3AefF4E27E1F9144eD75Ba65a80BdfEE345F413e/info.json
  blockchains/smartchain/assets/0x3AefF4E27E1F9144eD75Ba65a80BdfEE345F413e/logo.png
Labels: Payment Status: Paid

#13270 add OSWAP token
  blockchains/ethereum/assets/0xb32aC3C79A94aC1eb258f3C830bBDbc676483c93/info.json
  blockchains/ethereum/assets/0xb32aC3C79A94aC1eb258f3C830bBDbc676483c93/logo.png
  blockchains/smartchain/assets/0xb32aC3C79A94aC1eb258f3C830bBDbc676483c93/info.json
  blockchains/smartchain/assets/0xb32aC3C79A94aC1eb258f3C830bBDbc676483c93/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13311 Add GoMining Token (ERC20, BEP20)
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13301 Add X World Games (BEP20)
  blockchains/smartchain/assets/0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc/info.json
  blockchains/smartchain/assets/0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc/logo.png
Labels: Payment Status: Paid

#13266 Adding PLAY
  blockchains/smartchain/assets/0x9a3077F34cC30F9BF8E93A0369119bae0113d9cC/info.json
  blockchains/smartchain/assets/0x9a3077F34cC30F9BF8E93A0369119bae0113d9cC/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13049 Add FXF logo and info
  blockchains/smartchain/assets/0x8a40c222996f9F3431f63Bf80244C36822060f12/info.json
  blockchains/smartchain/assets/0x8a40c222996f9F3431f63Bf80244C36822060f12/logo.png
Labels: Payment Status: Paid

#13324 Add Huobi ECO Chain blockchain
  blockchains/heco/allowlist.json
  blockchains/heco/denylist.json
  blockchains/heco/info/info.json
  blockchains/heco/info/logo.png
Labels: Payment Status: Requested

#13313 Add SMON Logo And Token Info
  blockchains/smartchain/assets/0xAB15B79880f11cFfb58dB25eC2bc39d28c4d80d2/info.json
  blockchains/smartchain/assets/0xAB15B79880f11cFfb58dB25eC2bc39d28c4d80d2/logo.png
Labels: Payment Status: Paid

#13307 XCUR - BEP20 logo update
  blockchains/smartchain/assets/0x708C671Aa997da536869B50B6C67FA0C32Ce80B2/info.json
  blockchains/smartchain/assets/0x708C671Aa997da536869B50B6C67FA0C32Ce80B2/logo.png
Labels: Payment Status: Paid

#13327 Change Raydium logo
  blockchains/solana/assets/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png
Labels: Payment Status: Requested

#13291 [Info] Hertz Network (HTZ BEP-20)
  blockchains/smartchain/assets/0xb5BBA78B4dF2D47DD46078514a3e296AB3c344Fe/info.json
  blockchains/smartchain/assets/0xb5BBA78B4dF2D47DD46078514a3e296AB3c344Fe/logo.png
Labels: Payment Status: Paid

#13344 Add files via upload
  dapps/autofarm.network.png
Labels: Payment Status: Requested

#13336 Hertz network updates
  blockchains/smartchain/assets/0xb5BBA78B4dF2D47DD46078514a3e296AB3c344Fe/logo.png
Labels: Payment Status: Requested

#13345 Change symbol to RAY
  blockchains/solana/assets/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/info.json
Labels: Payment Status: Requested

#13328 Submission for LOFIDEFI
  blockchains/smartchain/assets/0x17D8519F57450E2B7E6aE1163E0E448322a8aF17/info.json
  blockchains/smartchain/assets/0x17D8519F57450E2B7E6aE1163E0E448322a8aF17/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13321 Add DKYC Logo and Info
  blockchains/smartchain/assets/0xdf5Fac537aa09e1eb0F3f8DD1d34CBdC42CA1076/info.json
  blockchains/smartchain/assets/0xdf5Fac537aa09e1eb0F3f8DD1d34CBdC42CA1076/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13338 Adding info and logo for SpacePortCoin (SPC)
  blockchains/smartchain/assets/0x21EA8618b9168Eb8936c3e02F0809BBE901282ac/info.json
  blockchains/smartchain/assets/0x21EA8618b9168Eb8936c3e02F0809BBE901282ac/logo.png
Labels: Payment Status: Paid

#13337 Update: Real Trump Token v1
  blockchains/smartchain/assets/0x158648792927eBb7a5c0D598BaB4D23417465E0B/info.json
  blockchains/smartchain/assets/0x158648792927eBb7a5c0D598BaB4D23417465E0B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13332 add logo token for Mini Cardano
  blockchains/smartchain/assets/0xF70c14AD93905f39eE3Df2D4fB92b87c31D779e0/info.json
  blockchains/smartchain/assets/0xF70c14AD93905f39eE3Df2D4fB92b87c31D779e0/logo.png
Labels: Status: On Hold, Payment Status: Paid

#13355 Add Autofarm Logo
  dapps/autofram.network.png
Labels: Payment Status: Requested

#13356 Delete autofarm.network.png
  dapps/autofarm.network.png
Labels: Payment Status: Requested

#13357 Delete autofram.network.png
  dapps/autofram.network.png
Labels: Payment Status: Requested

#13358 Re-add correct Autofarm logo
  dapps/autofarm.network.png
Labels: Payment Status: Requested

#13287 Add Step Hero logo
  blockchains/smartchain/assets/0xE8176d414560cFE1Bf82Fd73B986823B89E4F545/info.json
  blockchains/smartchain/assets/0xE8176d414560cFE1Bf82Fd73B986823B89E4F545/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13330 push logo
  blockchains/smartchain/assets/0x95a1199EBA84ac5f19546519e287d43D2F0E1b41/info.json
  blockchains/smartchain/assets/0x95a1199EBA84ac5f19546519e287d43D2F0E1b41/logo.png
Labels: Payment Status: Paid

#13364 Add links MADA (BEP20)
  blockchains/smartchain/assets/0xF70c14AD93905f39eE3Df2D4fB92b87c31D779e0/info.json
Labels: Payment Status: Requested

#13367 Rename Binance validator
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#13351 Add logo and info of kaby arena token
  blockchains/smartchain/assets/0x02A40C048eE2607B5f5606e445CFc3633Fb20b58/info.json
  blockchains/smartchain/assets/0x02A40C048eE2607B5f5606e445CFc3633Fb20b58/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13317 Add SafeDrive (BEP20)
  blockchains/smartchain/assets/0xa321fC1171EB85498faD47D3d127368eBa70265C/info.json
  blockchains/smartchain/assets/0xa321fC1171EB85498faD47D3d127368eBa70265C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13399 Add HONEYPAD (BEP20)
  blockchains/smartchain/assets/0xdb607c61Aaa2a954Bf1f9d117953F12d6c319E15/info.json
  blockchains/smartchain/assets/0xdb607c61Aaa2a954Bf1f9d117953F12d6c319E15/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13386 add logo LIGHT and infos
  blockchains/smartchain/assets/0x842668E2B9A73240aBF6532DEdC89c9c3e050C98/info.json
  blockchains/smartchain/assets/0x842668E2B9A73240aBF6532DEdC89c9c3e050C98/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13292 Adding TDW Token logo and info.
  blockchains/smartchain/assets/0xc5a72FC4324EF3fcEBAFf9b5E729487719Eb5B7A/info.json
  blockchains/smartchain/assets/0xc5a72FC4324EF3fcEBAFf9b5E729487719Eb5B7A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13375 Migrate and Add HyperChain X (BEP20)
  blockchains/smartchain/assets/0x0469F8Ca65Ce318888cc0d6459d0c7cbe5912c98/info.json
  blockchains/smartchain/assets/0x0469F8Ca65Ce318888cc0d6459d0c7cbe5912c98/logo.png
Labels: Payment Status: Requested

#13424 Add MGP (BEP20)
  blockchains/smartchain/assets/0xa677bc9bDb10329E488A4d8387ED7a08b2fc9005/info.json
  blockchains/smartchain/assets/0xa677bc9bDb10329E488A4d8387ED7a08b2fc9005/logo.png
Labels: Payment Status: Paid

#13428 update SHOPX logo
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/info.json
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/logo.png
Labels: Payment Status: Paid

#13361 Add: Real Trump Token V2
  blockchains/smartchain/assets/0xF41082C4CB71FB4628a9b17214B2624e0e2048a9/info.json
  blockchains/smartchain/assets/0xF41082C4CB71FB4628a9b17214B2624e0e2048a9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13412 Add Crypto Island (BEP20)
  blockchains/smartchain/assets/0x09d975C3351DBdED28617517FC6982284a787f03/info.json
  blockchains/smartchain/assets/0x09d975C3351DBdED28617517FC6982284a787f03/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13402 Add Multigame information and logo
  blockchains/smartchain/assets/0x3e6C9eE69B90B53628051F8D6CB5b6b2EaCCB438/info.json
  blockchains/smartchain/assets/0x3e6C9eE69B90B53628051F8D6CB5b6b2EaCCB438/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13445 Add MOVE token logo and info
  blockchains/smartchain/assets/0x231cF6F78620e42Fe00D0c5C3088b427F355d01c/info.json
  blockchains/smartchain/assets/0x231cF6F78620e42Fe00D0c5C3088b427F355d01c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13457 Update icon for DYDX (ERC-20)
  blockchains/ethereum/assets/0x92D6C1e31e14520e676a687F0a93788B716BEff5/info.json
  blockchains/ethereum/assets/0x92D6C1e31e14520e676a687F0a93788B716BEff5/logo.png
Labels: Payment Status: Requested

#13352 Add SOCIAL NFT (BEP20)
  blockchains/smartchain/assets/0x406c3ed15D4537DD23870260cad503B591fF1b31/info.json
  blockchains/smartchain/assets/0x406c3ed15D4537DD23870260cad503B591fF1b31/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13436 Add HoneyMoon (BEP20)
  blockchains/smartchain/assets/0xE8c93310af068aa50bd7bF0ebFa459Df2a02ceba/info.json
  blockchains/smartchain/assets/0xE8c93310af068aa50bd7bF0ebFa459Df2a02ceba/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13453 Request add Mu Continent Token Logo
  blockchains/smartchain/assets/0xCE262761DF57c72999146b7A6a752da03835db4a/info.json
  blockchains/smartchain/assets/0xCE262761DF57c72999146b7A6a752da03835db4a/logo.png
Labels: Payment Status: Paid

#13408 Add Agrocash X (BEP20)
  blockchains/smartchain/assets/0xD80BeA63a208770e1c371DFBF70Cb13469D29Ae6/info.json
  blockchains/smartchain/assets/0xD80BeA63a208770e1c371DFBF70Cb13469D29Ae6/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13415 Added RAINBOW icon and info to trust wallet
  blockchains/smartchain/assets/0x673Da443da2f6aE7c5c660A9F0D3DD24d1643D36/info.json
  blockchains/smartchain/assets/0x673Da443da2f6aE7c5c660A9F0D3DD24d1643D36/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13460 Venus tokens request
  blockchains/smartchain/assets/0x26DA28954763B92139ED49283625ceCAf52C6f94/info.json
  blockchains/smartchain/assets/0x26DA28954763B92139ED49283625ceCAf52C6f94/logo.png
  blockchains/smartchain/assets/0x5F84ce30DC3cF7909101C69086c50De191895883/info.json
  blockchains/smartchain/assets/0x5c9476FcD6a4F9a3654139721c949c2233bBbBc8/info.json
  blockchains/smartchain/assets/0x5c9476FcD6a4F9a3654139721c949c2233bBbBc8/logo.png
  blockchains/smartchain/assets/0x86aC3974e2BD0d60825230fa6F355fF11409df5c/info.json
  blockchains/smartchain/assets/0x86aC3974e2BD0d60825230fa6F355fF11409df5c/logo.png
Labels: Payment Status: Requested

#13432 adding SPO logo & info
  blockchains/ethereum/assets/0xcbE771323587EA16dACB6016e269D7F08A7ACC4E/info.json
  blockchains/ethereum/assets/0xcbE771323587EA16dACB6016e269D7F08A7ACC4E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13470 Add files via upload
  blockchains/smartchain/assets/0x041640eA980e3fE61e9C4ca26D9007Bc70094C15/info.json
  blockchains/smartchain/assets/0x041640eA980e3fE61e9C4ca26D9007Bc70094C15/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13480 Add ANN token
  blockchains/smartchain/assets/0x1Aa4BDb03f27B08Ad203Aa083e88Eb425CEdD330/info.json
  blockchains/smartchain/assets/0x1Aa4BDb03f27B08Ad203Aa083e88Eb425CEdD330/logo.png
  blockchains/smartchain/assets/0x35b2a25087A4D33dADBFB7625bfa7f1e0853f723/info.json
  blockchains/smartchain/assets/0x35b2a25087A4D33dADBFB7625bfa7f1e0853f723/logo.png
  blockchains/smartchain/assets/0x4f5d48D3d28Ff10113283A896952A7722Eaaacd8/info.json
  blockchains/smartchain/assets/0x4f5d48D3d28Ff10113283A896952A7722Eaaacd8/logo.png
  blockchains/smartchain/assets/0x8401aAbA08f0be0d30B7D136C50fe5C461DBFA05/info.json
  blockchains/smartchain/assets/0x8401aAbA08f0be0d30B7D136C50fe5C461DBFA05/logo.png
  blockchains/smartchain/assets/0x98936Bde1CF1BFf1e7a8012Cee5e2583851f2067/info.json
  blockchains/smartchain/assets/0x98936Bde1CF1BFf1e7a8012Cee5e2583851f2067/logo.png
  blockchains/smartchain/assets/0xC5a83aD9f3586e143D2C718E8999206887eF9dDc/info.json
  blockchains/smartchain/assets/0xC5a83aD9f3586e143D2C718E8999206887eF9dDc/logo.png
  blockchains/smartchain/assets/0xE4145407d1952B6C1d5bE9039a2EfFA3A0ed3baa/info.json
  blockchains/smartchain/assets/0xE4145407d1952B6C1d5bE9039a2EfFA3A0ed3baa/logo.png
Labels: Payment Status: Requested

#13492 Add links ANT (ERC20)
  blockchains/ethereum/assets/0x960b236A07cf122663c4303350609A66A7B288C0/info.json
Labels: Payment Status: Requested

#13509 [Internal] Change fee to 1000 TWT (from 2000)
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#13503 Add social NFT (BEP20)
  blockchains/smartchain/assets/0x406c3ed15D4537DD23870260cad503B591fF1b31/info.json
  blockchains/smartchain/assets/0x406c3ed15D4537DD23870260cad503B591fF1b31/logo.png
Labels: Payment Status: Requested

#13475 Add DZOO logo and info
  blockchains/smartchain/assets/0x5419291D81C68c103363E06046F40a9056ab2B7f/info.json
  blockchains/smartchain/assets/0x5419291D81C68c103363E06046F40a9056ab2B7f/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13510 Revise Logo BUMN Token
  blockchains/smartchain/assets/0x3AefF4E27E1F9144eD75Ba65a80BdfEE345F413e/logo.png
Labels: Payment Status: Requested

#13521 Changed MOVE token name to MarketMove.ai - related to PR #13464
  blockchains/smartchain/assets/0x231cF6F78620e42Fe00D0c5C3088b427F355d01c/info.json
Labels: Payment Status: Paid

#13514 Add Nobility Logo and Info
  blockchains/smartchain/assets/0xA67a13c9283Da5AABB199Da54a9Cb4cD8B9b16bA/info.json
  blockchains/smartchain/assets/0xA67a13c9283Da5AABB199Da54a9Cb4cD8B9b16bA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13491 Add $CRDN logo and info
  blockchains/smartchain/assets/0xFa17b330bCC4e7F3E2456996d89A5a54AB044831/info.json
  blockchains/smartchain/assets/0xFa17b330bCC4e7F3E2456996d89A5a54AB044831/logo.png
Labels: Payment Status: Paid

#13511 Add INPA Coin (BEP20)
  blockchains/smartchain/assets/0xD9CBc18e554Aec0d99E9D99324dECC9b4b473af0/info.json
  blockchains/smartchain/assets/0xD9CBc18e554Aec0d99E9D99324dECC9b4b473af0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13523 Add ACT logo and info
  blockchains/smartchain/assets/0x9F3BCBE48E8b754F331Dfc694A894e8E686aC31D/info.json
  blockchains/smartchain/assets/0x9F3BCBE48E8b754F331Dfc694A894e8E686aC31D/logo.png
Labels: Payment Status: Paid

#13542 Fix decimals for SpaceRat
  blockchains/polygon/assets/0x1132f58810Ee9fF13E97aECCd8DDa688Cc5eb8F4/info.json
Labels: Payment Status: Requested

#13543 Add links IRON Titanium
  blockchains/polygon/assets/0xaAa5B9e6c589642f98a1cDA99B9D024B8407285A/info.json
Labels: Payment Status: Requested

#13544 fix decimals maUSDC
  blockchains/polygon/assets/0x9719d867A500Ef117cC201206B8ab51e794d3F82/info.json
Labels: Payment Status: Requested

#13545 Add links Crypto.com
  blockchains/polygon/assets/0xAdA58DF0F643D959C2A47c9D4d4c1a4deFe3F11C/info.json
Labels: Payment Status: Requested

#13546 Fix symbol Augury Finance token
  blockchains/polygon/assets/0x76e63a3E7Ba1e2E61D3DA86a87479f983dE89a7E/info.json
Labels: Payment Status: Requested

#13547 Add links PolyDoge
  blockchains/polygon/assets/0x8A953CfE442c5E8855cc6c61b1293FA648BAE472/info.json
Labels: Payment Status: Requested

#13548 fix decimals 0xBTC
  blockchains/polygon/assets/0x71B821aa52a49F32EEd535fCA6Eb5aa130085978/info.json
Labels: Payment Status: Requested

#13549 fix symbol Qi Dao token
  blockchains/polygon/assets/0x580A84C73811E1839F75d86d75d88cCa0c241fF4/info.json
Labels: Payment Status: Requested

#13371 Add BSocial (BINS) logo and info
  blockchains/smartchain/assets/0x822DC83fA4dc997fFf24D0BC0A66fCB2954a6156/info.json
  blockchains/smartchain/assets/0x822DC83fA4dc997fFf24D0BC0A66fCB2954a6156/logo.png
Labels: Payment Status: Paid

#13550 Add links WaultSwap
  blockchains/polygon/assets/0x4c4BF319237D98a30A929A96112EfFa8DA3510EB/info.json
Labels: Payment Status: Requested

#13535 Adding updated Shrew contract, logo and information
  blockchains/smartchain/assets/0x3c168c8E0bb11B0A6DEEba6c0c6Be100E82451BB/info.json
  blockchains/smartchain/assets/0x3c168c8E0bb11B0A6DEEba6c0c6Be100E82451BB/logo.png
Labels: Payment Status: Requested

#13561 Change Wave's logo
  blockchains/waves/info/logo.png
Labels: Payment Status: Requested

#13554 Add CoinWind (COW) BEP20
  blockchains/smartchain/assets/0x422E3aF98bC1dE5a1838BE31A56f75DB4Ad43730/info.json
  blockchains/smartchain/assets/0x422E3aF98bC1dE5a1838BE31A56f75DB4Ad43730/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13541 Add Giftedhands (GHD) ERC20 and Giftedhands on BSC (GHD) BEP20
  blockchains/ethereum/assets/0x3b544e6fcf6C8dCE9D8B45A4FdF21C9B02f9fDa9/info.json
  blockchains/ethereum/assets/0x3b544e6fcf6C8dCE9D8B45A4FdF21C9B02f9fDa9/logo.png
  blockchains/smartchain/assets/0xfDFD27aE39cebefDBaAc8615F18aa68DDD0F15f5/info.json
  blockchains/smartchain/assets/0xfDFD27aE39cebefDBaAc8615F18aa68DDD0F15f5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13552 Add PKR token
  blockchains/smartchain/assets/0xc49DDe62B4A0810074721fAcA54Aab52369f486a/info.json
  blockchains/smartchain/assets/0xc49DDe62B4A0810074721fAcA54Aab52369f486a/logo.png
Labels: Payment Status: Paid

#13579 Upload Insurace logo
  dapps/insurace.png
Labels: Payment Status: Requested

#13580 Upload Fractional.art logo
  dapps/fractional.art.png
Labels: Payment Status: Requested

#13581 upload bscproject logo
  dapps/bscproject.org.png
Labels: Payment Status: Requested

#13566 Add BurningMoon Logo
  blockchains/smartchain/assets/0x97c6825e6911578A515B11e25B552Ecd5fE58dbA/info.json
  blockchains/smartchain/assets/0x97c6825e6911578A515B11e25B552Ecd5fE58dbA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13597 Updating with new contract info and setting old contract to "abandoned" status.
  blockchains/smartchain/assets/0x85EE8e3E0068EdeeEE960979958d7F61416a9d84/info.json
  blockchains/smartchain/assets/0x85EE8e3E0068EdeeEE960979958d7F61416a9d84/logo.png
  blockchains/smartchain/assets/0xa1bc3505BB77735cE17484d00FfdE8C6eF53707b/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#13584 Add Biconomy Token (BEP20)
  blockchains/smartchain/assets/0xc864019047B864B6ab609a968ae2725DFaee808A/info.json
  blockchains/smartchain/assets/0xc864019047B864B6ab609a968ae2725DFaee808A/logo.png
Labels: Payment Status: Paid

#13538 Add info and logo of ULTI Coin
  blockchains/smartchain/assets/0x42BFE4A3E023f2C90aEBFfbd9B667599Fa38514F/info.json
  blockchains/smartchain/assets/0x42BFE4A3E023f2C90aEBFfbd9B667599Fa38514F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13576 Add SUB (BEP20) token
  blockchains/smartchain/assets/0xfd290c590866f8282d89671A85Ac9964b165d682/info.json
  blockchains/smartchain/assets/0xfd290c590866f8282d89671A85Ac9964b165d682/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13594 Adding Krown
  blockchains/smartchain/assets/0x1446f3CEdf4d86a9399E49f7937766E6De2A3AAB/info.json
  blockchains/smartchain/assets/0x1446f3CEdf4d86a9399E49f7937766E6De2A3AAB/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13577 Add HUGHUG (BEP20)
  blockchains/smartchain/assets/0xb626213cb1D52Caa1eD71e2a0e62c0113eD8d642/info.json
  blockchains/smartchain/assets/0xb626213cb1D52Caa1eD71e2a0e62c0113eD8d642/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13613 [Internal] Adjust bot assignes
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#13612 Add Lido DAO Token (ERC20)
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32/info.json
  blockchains/ethereum/assets/0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32/logo.png
Labels: Payment Status: Requested

#13615 LeonicornSwap Logo Change
  blockchains/smartchain/assets/0x2c8368f8F474Ed9aF49b87eAc77061BEb986c2f1/logo.png
Labels: Payment Status: Paid

#13621 Add MaskDoge Coin logo and info
  blockchains/smartchain/assets/0x18fF245c134D9DAA6fED977617654490ba4DA526/info.json
  blockchains/smartchain/assets/0x18fF245c134D9DAA6fED977617654490ba4DA526/logo.png
Labels: Payment Status: Paid

#13499 update wCCX in Polygon & Solana
  blockchains/polygon/assets/0x137Ee749f0F8c2eD34cA00dE33BB59E3dafA494A/info.json
  blockchains/polygon/assets/0x137Ee749f0F8c2eD34cA00dE33BB59E3dafA494A/logo.png
  blockchains/solana/assets/CzqJTjTp3R9opDHmzF5Gy1G2NKDHEyMufa4Keiju4PLu/info.json
  blockchains/solana/assets/CzqJTjTp3R9opDHmzF5Gy1G2NKDHEyMufa4Keiju4PLu/logo.png
Labels: Payment Status: Requested

#13556 adding BSL
  blockchains/ethereum/assets/0x0AF55d5fF28A3269d69B98680Fd034f115dd53Ac/info.json
  blockchains/ethereum/assets/0x0AF55d5fF28A3269d69B98680Fd034f115dd53Ac/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13607 Add XPNET (BEP20)
  blockchains/smartchain/assets/0x8cf8238abf7b933Bf8BB5Ea2C7E4Be101c11de2A/info.json
  blockchains/smartchain/assets/0x8cf8238abf7b933Bf8BB5Ea2C7E4Be101c11de2A/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13642 add Tranchess logo
  dapps/tranchess.com.png
Labels: Payment Status: Requested

#13643 Update tranchess logo
  dapps/tranchess.com.png
Labels: Payment Status: Requested

#13640 [Urgent] Please add LOGO and INFO to X2P. PAID #13593
  blockchains/smartchain/assets/0xdfd85305A752d70A07A995Fa724Ac4Ff787EBef2/info.json
  blockchains/smartchain/assets/0xdfd85305A752d70A07A995Fa724Ac4Ff787EBef2/logo.png
Labels: Payment Status: Paid

#13644 change status for X2P
  blockchains/smartchain/assets/0x53dcD4eF8E21FE014594a0854c4271a0623B31eC/info.json
Labels: Payment Status: Requested

#13645 Add Hotcross logo
  dapps/hotcross.com.png
Labels: Payment Status: Requested

#13637 Hamster Token Migration
  blockchains/smartchain/assets/0x679D5b2d94f454c950d683D159b87aa8eae37C9e/info.json
  blockchains/smartchain/assets/0x679D5b2d94f454c950d683D159b87aa8eae37C9e/logo.png
  blockchains/smartchain/assets/0xb7b36CA86685Af52186f1f9394e91d115A9Da654/info.json
Labels: Payment Status: Requested

#13427 Update BLANK Token in tokenlist.json
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#13647 Add powerpool.finance logo
  dapps/powerpool.finance.png
Labels: Payment Status: Requested

#13603 Add ALPHAKOMBAT Info + Logo
  blockchains/smartchain/assets/0x8379B36826675450c35e1eb45d2fd1E1aE8494A4/info.json
  blockchains/smartchain/assets/0x8379B36826675450c35e1eb45d2fd1E1aE8494A4/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#13591 Adding GART
  blockchains/smartchain/assets/0xd1ECFDD45c49057479c4Ca95E045855370bC4F5B/info.json
  blockchains/smartchain/assets/0xd1ECFDD45c49057479c4Ca95E045855370bC4F5B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13575 Add Shirtum (BEP20)
  blockchains/smartchain/assets/0x7269d98Af4aA705e0B1A5D8512FadB4d45817d5a/info.json
  blockchains/smartchain/assets/0x7269d98Af4aA705e0B1A5D8512FadB4d45817d5a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13671 Fix status "abandoned" Vanity (BEP20)
  blockchains/smartchain/assets/0x2dE161f13Ab594aECD8F2A93e885A08d0ad362c7/info.json
Labels: Payment Status: Requested

#12778 Add Vanity (BEP20)
  blockchains/smartchain/assets/0xAbc69f2025bDb12efcdB8fd048d240fFf943ca82/info.json
  blockchains/smartchain/assets/0xAbc69f2025bDb12efcdB8fd048d240fFf943ca82/logo.png
Labels: Payment Status: Requested

#13675 delete uluna
  blockchains/terra/assets/uluna/logo.png
Labels: Payment Status: Requested

#13668 Add MiniSports Token And Logo (BEP20)
  blockchains/smartchain/assets/0x75856ea207CE7194E4E65c334BEc143D77701E4a/info.json
  blockchains/smartchain/assets/0x75856ea207CE7194E4E65c334BEc143D77701E4a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13656 update PERP logo
  blockchains/ethereum/assets/0xbC396689893D065F41bc2C6EcbeE5e0085233447/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13688 [Internal] Add info for Terra tokens
  blockchains/terra/assets/terra1sndgzq62wp23mv20ndr4sxg6k8xcsudsy87uph/info.json
  blockchains/terra/assets/terra1sndgzq62wp23mv20ndr4sxg6k8xcsudsy87uph/logo.png
  blockchains/terra/assets/terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6/info.json
  blockchains/terra/assets/terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6/logo.png
  blockchains/terra/assets/terra1zw0kfxrxgrs5l087mjm79hcmj3y8z6tljuhpmc/info.json
  blockchains/terra/assets/terra1zw0kfxrxgrs5l087mjm79hcmj3y8z6tljuhpmc/logo.png
  blockchains/terra/assets/tterra1vs2vuks65rq7xj78mwtvn7vvnm2gn7adjlr002/info.json
  blockchains/terra/assets/tterra1vs2vuks65rq7xj78mwtvn7vvnm2gn7adjlr002/logo.png
  script/generic/asset-infos.ts
  script/generic/folders-and-files.ts
Labels: Payment Status: Requested

#13630 Add VitaDAO (VITA) (ERC20)
  blockchains/ethereum/assets/0x81f8f0bb1cB2A06649E51913A151F0E7Ef6FA321/info.json
  blockchains/ethereum/assets/0x81f8f0bb1cB2A06649E51913A151F0E7Ef6FA321/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13687 Update AST
  blockchains/ethereum/assets/0x27054b13b1B798B345b591a4d22e6562d47eA75a/info.json
  blockchains/ethereum/assets/0x27054b13b1B798B345b591a4d22e6562d47eA75a/logo.png
Labels: Payment Status: Requested

#13694 adding GRV
  blockchains/smartchain/assets/0x1337ace33C2B3Fc17d85f33dbD0Ed73a896148B5/info.json
  blockchains/smartchain/assets/0x1337ace33C2B3Fc17d85f33dbD0Ed73a896148B5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13702 Change status to abandoned for PIXL
  blockchains/smartchain/assets/0x5B2b5BD1e5C53870fE135Fb7b289D686f762858d/info.json
Labels: Payment Status: Requested

#13700 Add DefiConnect (BEP20)
  blockchains/smartchain/assets/0x996c1bf72Ec220289ae0edd3a8d77080642121a2/info.json
  blockchains/smartchain/assets/0x996c1bf72Ec220289ae0edd3a8d77080642121a2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13660 Add SMD Coin (BEP20)
  blockchains/smartchain/assets/0x2b31b83D2a960d648e9c8d3B84dF5452c80aB947/info.json
  blockchains/smartchain/assets/0x2b31b83D2a960d648e9c8d3B84dF5452c80aB947/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13661 Add My Pet Social (BEP20)
  blockchains/smartchain/assets/0x9Eb5B7902D2be0B5AaBa2F096e043d3cD804e6dF/info.json
  blockchains/smartchain/assets/0x9Eb5B7902D2be0B5AaBa2F096e043d3cD804e6dF/logo.png
Labels: Payment Status: Paid

#13715 [Internal] Allow logo to be missing for abandoned tokens
  script/generic/folders-and-files.ts
Labels: Payment Status: Requested

#13672 remove logo for old Vanity
  blockchains/smartchain/assets/0x2dE161f13Ab594aECD8F2A93e885A08d0ad362c7/logo.png
  script/generic/folders-and-files.ts
Labels: Payment Status: Requested

#13704 Add MONI token info
  blockchains/smartchain/assets/0x9573c88aE3e37508f87649f87c4dd5373C9F31e0/info.json
  blockchains/smartchain/assets/0x9573c88aE3e37508f87649f87c4dd5373C9F31e0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13717 change status for air
  blockchains/smartchain/assets/0xa123aB52a32267Dc357B7599739d3C6CAF856fe4/info.json
Labels: Payment Status: Requested

#13723 Add validator tron (Poloniex)
  blockchains/tron/validators/assets/TJvaAeFb8Lykt9RQcVyyTFN2iDvGMuyD4M/logo.png
  blockchains/tron/validators/list.json
Labels: Payment Status: Requested

#13722 Add XXT-Token (BEP20)
  blockchains/smartchain/assets/0xEA01a1a3CF143f90b4aC6D069Bd369826574CD45/info.json
  blockchains/smartchain/assets/0xEA01a1a3CF143f90b4aC6D069Bd369826574CD45/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13565 Update logo & information
  blockchains/smartchain/assets/0x0A7bB2bddA1c0eA02d98a7b048f4bF809F40277b/info.json
  blockchains/smartchain/assets/0x0A7bB2bddA1c0eA02d98a7b048f4bF809F40277b/logo.png
Labels: Payment Status: Paid

#13724 Add tron validator
  blockchains/tron/validators/assets/TCEo1hMAdaJrQmvnGTCcGT2LqrGU4N7Jqf/logo.png
  blockchains/tron/validators/assets/TSNbzxac4WhxN91XvaUfPTKP2jNT18mP6T/logo.png
  blockchains/tron/validators/assets/TUD4YXYdj2t1gP5th3A7t97mx1AUmrrQRt/logo.png
  blockchains/tron/validators/assets/TWkpg1ZQ4fTv7sj41zBUTMo1kuJEUWTere/logo.png
  blockchains/tron/validators/list.json
Labels: Payment Status: Requested

#13727 update logo
  blockchains/smartchain/assets/0x0EF008FF963572d3DAbc12E222420F537ddaBf94/info.json
  blockchains/smartchain/assets/0x0EF008FF963572d3DAbc12E222420F537ddaBf94/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13732 remove logo
  blockchains/smartchain/assets/0xa123aB52a32267Dc357B7599739d3C6CAF856fe4/logo.png
Labels: Payment Status: Requested

#13733 remove logo for PIXL
  blockchains/smartchain/assets/0x5B2b5BD1e5C53870fE135Fb7b289D686f762858d/logo.png
Labels: Payment Status: Requested

#13708 Add MaticVerse (BEP20)
  blockchains/smartchain/assets/0xAf7BfA6240745Fd41D1ED4b5fADE9DCAF369bA6c/info.json
  blockchains/smartchain/assets/0xAf7BfA6240745Fd41D1ED4b5fADE9DCAF369bA6c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13735 remove logo for GST1
  blockchains/ethereum/assets/0x88d60255F917e3eb94eaE199d827DAd837fac4cB/logo.png
Labels: Payment Status: Requested

#13736 remove logo for EVE
  blockchains/ethereum/assets/0x923108a439C4e8C2315c4f6521E5cE95B44e9B4c/logo.png
Labels: Payment Status: Requested

#13737 remove logo for TBCC
  blockchains/smartchain/assets/0x00000ee41472D518B364FA09866532A792F4009B/logo.png
Labels: Payment Status: Requested

#13738 Remove logo X2P
  blockchains/smartchain/assets/0x53dcD4eF8E21FE014594a0854c4271a0623B31eC/logo.png
Labels: Payment Status: Requested

#13741 remove logo for DOGEMOON
  blockchains/smartchain/assets/0x2f801292924433F41E34669b0817F990764EcAA0/logo.png
Labels: Payment Status: Requested

#13742 remove logo for STOR
  blockchains/smartchain/assets/0xa1bc3505BB77735cE17484d00FfdE8C6eF53707b/logo.png
Labels: Payment Status: Requested

#13743 remove logo for TRY
  blockchains/ethereum/assets/0xe431a4c5DB8B73c773e06cf2587dA1EB53c41373/logo.png
Labels: Payment Status: Requested

#13746 remove logo for HYPER
  blockchains/smartchain/assets/0x25b15E17164b97202616e36Af1234Db944121185/logo.png
Labels: Payment Status: Requested

#13745 remove logo for VGX
  blockchains/ethereum/assets/0x5Af2Be193a6ABCa9c8817001F45744777Db30756/logo.png
Labels: Payment Status: Requested

#13747 Remove logo for TCT
  blockchains/smartchain/assets/0x2095d2346e47Ed497d4F39FcfA59918b4346cd65/logo.png
Labels: Payment Status: Requested

#13744 Remove logo for DEXT
  blockchains/ethereum/assets/0x26CE25148832C04f3d7F26F32478a9fe55197166/logo.png
Labels: Payment Status: Requested

#13680 Migration Moonwilly v2 Request
  blockchains/smartchain/assets/0xF520f5D709dCD40529caaFc02B297e7225ff8372/info.json
  blockchains/smartchain/assets/0xF520f5D709dCD40529caaFc02B297e7225ff8372/logo.png
Labels: Payment Status: Requested

#13749 remove logo for MNWL
  blockchains/smartchain/assets/0xd4D2aBBeF1b26458504e7027233D5e7F09ea476d/logo.png
Labels: Payment Status: Requested

#12758 Add Bankless DAO (BANK) (ERC20)
  blockchains/ethereum/assets/0x2d94AA3e47d9D5024503Ca8491fcE9A2fB4DA198/info.json
  blockchains/ethereum/assets/0x2d94AA3e47d9D5024503Ca8491fcE9A2fB4DA198/logo.png
Labels: Payment Status: Paid

#13754 Add Magic Beasties (BEP20)
  blockchains/smartchain/assets/0xc77Dd3AdE7b717583E0924466E4E474A5673332c/info.json
  blockchains/smartchain/assets/0xc77Dd3AdE7b717583E0924466E4E474A5673332c/logo.png
Labels: Payment Status: Paid
