Repository trustwallet/assets, pull requests merged in 2021-01, with the labels that each got.

#5210 Add Axion (AXN) (erc20)
  blockchains/ethereum/assets/0x71F85B2E46976bD21302B64329868fd15eb0D127/info.json
  blockchains/ethereum/assets/0x71F85B2E46976bD21302B64329868fd15eb0D127/logo.png
  blockchains/ethereum/assets/0x7D85e23014F84E6E21d5663aCD8751bEF3562352/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5222 Exceedme Add
  blockchains/ethereum/assets/0xee573a945B01B788B9287CE062A0CFC15bE9fd86/info.json
  blockchains/ethereum/assets/0xee573a945B01B788B9287CE062A0CFC15bE9fd86/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5224 Add E-RADIX (eXRD) ERC20 token info and logo
  blockchains/ethereum/assets/0x6468e79A80C0eaB0F9A2B574c8d5bC374Af59414/info.json
  blockchains/ethereum/assets/0x6468e79A80C0eaB0F9A2B574c8d5bC374Af59414/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5226 Add WISE Token logo and info
  blockchains/ethereum/assets/0x66a0f676479Cee1d7373f3DC2e2952778BfF5bd6/info.json
  blockchains/ethereum/assets/0x66a0f676479Cee1d7373f3DC2e2952778BfF5bd6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5221 Add bDollar Share (bep20)
  blockchains/smartchain/assets/0x0d9319565be7f53CeFE84Ad201Be3f40feAE2740/info.json
  blockchains/smartchain/assets/0x0d9319565be7f53CeFE84Ad201Be3f40feAE2740/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5232 Update TOKO's smart contract address and logo
  blockchains/ethereum/assets/0x0c963A1B52Eb97C5e457c7D76696F8b95c3087eD/logo.png
  blockchains/ethereum/assets/0xa0F0546Eb5E3eE7e8cfC5DA12e5949F3AE622675/info.json
  blockchains/ethereum/assets/0xa0F0546Eb5E3eE7e8cfC5DA12e5949F3AE622675/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5250 add SPL USDC
  blockchains/solana/allowlist.json
  blockchains/solana/assets/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/info.json
  blockchains/solana/assets/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png
Labels: Payment Status: Requested

#5249 julswap dapp
  dapps/julswap.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#5244 Add Basis Cash (ERC20) Logo and Info
  blockchains/ethereum/assets/0x3449FC1Cd036255BA1EB19d65fF4BA2b8903A69a/info.json
  blockchains/ethereum/assets/0x3449FC1Cd036255BA1EB19d65fF4BA2b8903A69a/logo.png
Labels: Payment Status: Paid

#5245 Add Basis Share (ERC20) Logo and Info
  blockchains/ethereum/assets/0xa7ED29B253D8B4E3109ce07c80fc570f81B63696/info.json
  blockchains/ethereum/assets/0xa7ED29B253D8B4E3109ce07c80fc570f81B63696/logo.png
Labels: Payment Status: Paid

#5240 Update SUSHI logo
  blockchains/ethereum/assets/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2/info.json
  blockchains/ethereum/assets/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2/logo.png
Labels: Payment Status: Paid

#5239 Fix border around DITTO logo
  blockchains/smartchain/assets/0x233d91A0713155003fc4DcE0AFa871b508B3B715/logo.png
Labels: Payment Status: Paid

#5238 Add mettalex token logo
  blockchains/ethereum/assets/0x2e1E15C44Ffe4Df6a0cb7371CD00d5028e571d14/info.json
  blockchains/ethereum/assets/0x2e1E15C44Ffe4Df6a0cb7371CD00d5028e571d14/logo.png
Labels: Payment Status: Paid

#5257 [internal] Update axios dep
  package-lock.json
  package.json
Labels: Payment Status: Requested

#5261 add BEP20 BETH
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B/info.json
  blockchains/smartchain/assets/0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B/logo.png
Labels: Payment Status: Requested

#4658 Add ORAI
  blockchains/ethereum/assets/0x4c11249814f11b9346808179Cf06e71ac328c1b5/info.json
  blockchains/ethereum/assets/0x4c11249814f11b9346808179Cf06e71ac328c1b5/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5264 Add YLD logo
  blockchains/ethereum/assets/0xF94b5C5651c888d928439aB6514B93944eEE6F48/info.json
  blockchains/ethereum/assets/0xF94b5C5651c888d928439aB6514B93944eEE6F48/logo.png
Labels: Payment Status: Paid

#5114 Add mUSDK and mUSDT
  blockchains/ethereum/assets/0x84d4AfE150dA7Ea1165B9e45Ff8Ee4798d7C38DA/info.json
  blockchains/ethereum/assets/0x84d4AfE150dA7Ea1165B9e45Ff8Ee4798d7C38DA/logo.png
  blockchains/ethereum/assets/0xD1670Cb7c01987a8DdD6976C4894463460Eeb8a2/info.json
  blockchains/ethereum/assets/0xD1670Cb7c01987a8DdD6976C4894463460Eeb8a2/logo.png
Labels: Payment Status: Paid

#5258 add openocean.finance logo
  dapps/openocean.finance.png
Labels: Payment Status: Paid, Payment Status: Requested

#5269 add BEP20 BTCST
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x78650B139471520656b9E7aA7A5e9276814a38e9/info.json
  blockchains/smartchain/assets/0x78650B139471520656b9E7aA7A5e9276814a38e9/logo.png
Labels: Payment Status: Requested

#5268 Commit added coins to Trust Wallet
  blockchains/ethereum/assets/0xE95A203B1a91a908F9B9CE46459d101078c2c3cb/info.json
  blockchains/ethereum/assets/0xE95A203B1a91a908F9B9CE46459d101078c2c3cb/logo.png
Labels: Payment Status: Requested

#5275 [Internal] Merge fee bot config: add config options for collaborators, for comme…
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#5246 Add BSCX token to Trust Wallet
  blockchains/smartchain/assets/0x5Ac52EE5b2a633895292Ff6d8A89bB9190451587/info.json
  blockchains/smartchain/assets/0x5Ac52EE5b2a633895292Ff6d8A89bB9190451587/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5265 add Frax and Frax Share (ERC20) logos and info
  blockchains/ethereum/assets/0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0/info.json
  blockchains/ethereum/assets/0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0/logo.png
  blockchains/ethereum/assets/0x853d955aCEf822Db058eb8505911ED77F175b99e/info.json
  blockchains/ethereum/assets/0x853d955aCEf822Db058eb8505911ED77F175b99e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5270 Add DODO
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x43Dfc4159D86F3A37A5A4B3D4580b888ad7d4DDd/info.json
  blockchains/ethereum/assets/0x43Dfc4159D86F3A37A5A4B3D4580b888ad7d4DDd/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5279 Addition of OML to Trust Wallet
  blockchains/ethereum/assets/0x224DB5E6180761df4C3d8936585f6b8b83879770/info.json
  blockchains/ethereum/assets/0x224DB5E6180761df4C3d8936585f6b8b83879770/logo.png
Labels: Payment Status: Paid

#5287 add DApp Lido.fi
  dapps/lido.fi.png
Labels: Payment Status: Requested

#5285 update
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#5286 Added SPL BRZ
  blockchains/solana/allowlist.json
  blockchains/solana/assets/FtgGSFADXBtroxq8VCausXRr2of47QBf5AS1NtZCu4GD/info.json
  blockchains/solana/assets/FtgGSFADXBtroxq8VCausXRr2of47QBf5AS1NtZCu4GD/logo.png
Labels: Payment Status: Paid

#5288 Add bearn.fi (bep20)
  blockchains/smartchain/assets/0x81859801b01764D4f0Fa5E64729f5a6C3b91435b/info.json
  blockchains/smartchain/assets/0x81859801b01764D4f0Fa5E64729f5a6C3b91435b/logo.png
Labels: Payment Status: Paid

#5291 [Internal] Enable comment deletion; temp with restricted set of users
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#5292 add ETH stETH
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84/info.json
  blockchains/ethereum/assets/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84/logo.png
Labels: Payment Status: Requested

#5295 [Internal] Extend list of allowed contributors
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#5272 Add Rootkit (ROOT) Token Logo and Info
  blockchains/ethereum/assets/0xCb5f72d37685C3D5aD0bB5F982443BC8FcdF570E/info.json
  blockchains/ethereum/assets/0xCb5f72d37685C3D5aD0bB5F982443BC8FcdF570E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5301 add ERC20 RUNE
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x3155BA85D5F96b2d030a4966AF206230e46849cb/info.json
  blockchains/ethereum/assets/0x3155BA85D5F96b2d030a4966AF206230e46849cb/logo.png
Labels: Payment Status: Requested

#5300 Add SBS logo and info
  blockchains/smartchain/assets/0xc1D99537392084Cc02D3F52386729b79d01035ce/info.json
  blockchains/smartchain/assets/0xc1D99537392084Cc02D3F52386729b79d01035ce/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5302 edit ERC20 CHR
  blockchains/ethereum/assets/0x8A2279d4A90B6fe1C4B30fa660cC9f926797bAA2/logo.png
Labels: Payment Status: Requested

#5303 add BEP20 Venus tokens 1/14
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x1610bc33319e9398de5f57B33a5b184c806aD217/info.json
  blockchains/smartchain/assets/0x1610bc33319e9398de5f57B33a5b184c806aD217/logo.png
  blockchains/smartchain/assets/0x20bff4bbEDa07536FF00e073bd8359E5D80D733d/info.json
  blockchains/smartchain/assets/0x20bff4bbEDa07536FF00e073bd8359E5D80D733d/logo.png
  blockchains/smartchain/assets/0x334b3eCB4DCa3593BCCC3c7EBD1A1C1d1780FBF1/info.json
  blockchains/smartchain/assets/0x334b3eCB4DCa3593BCCC3c7EBD1A1C1d1780FBF1/logo.png
  blockchains/smartchain/assets/0x5F0388EBc2B94FA8E123F404b79cCF5f40b29176/info.json
  blockchains/smartchain/assets/0x5F0388EBc2B94FA8E123F404b79cCF5f40b29176/logo.png
  blockchains/smartchain/assets/0x650b940a1033B8A1b1873f78730FcFC73ec11f1f/info.json
  blockchains/smartchain/assets/0x650b940a1033B8A1b1873f78730FcFC73ec11f1f/logo.png
  blockchains/smartchain/assets/0x972207A639CC1B374B893cc33Fa251b55CEB7c07/info.json
  blockchains/smartchain/assets/0x972207A639CC1B374B893cc33Fa251b55CEB7c07/logo.png
  blockchains/smartchain/assets/0xeBD0070237a0713E8D94fEf1B728d3d993d290ef/info.json
  blockchains/smartchain/assets/0xeBD0070237a0713E8D94fEf1B728d3d993d290ef/logo.png
  blockchains/smartchain/assets/0xf91d58b5aE142DAcC749f58A49FCBac340Cb0343/info.json
  blockchains/smartchain/assets/0xf91d58b5aE142DAcC749f58A49FCBac340Cb0343/logo.png
Labels: Payment Status: Requested

#5283 Add Beast DAO token
  blockchains/ethereum/assets/0xdBB2F12CB89Af05516768C2c69A771D92A25D17c/info.json
  blockchains/ethereum/assets/0xdBB2F12CB89Af05516768C2c69A771D92A25D17c/logo.png
Labels: Payment Status: Paid

#5273 Add Wrapped ZCore
  blockchains/ethereum/assets/0x72896d5478aD86B14a6d4f6e7441740d4970083d/info.json
  blockchains/ethereum/assets/0x72896d5478aD86B14a6d4f6e7441740d4970083d/logo.png
Labels: Payment Status: Paid

#5305 Add BBR Token
  blockchains/ethereum/assets/0x7671904eed7f10808B664fc30BB8693FD7237abF/info.json
  blockchains/ethereum/assets/0x7671904eed7f10808B664fc30BB8693FD7237abF/logo.png
Labels: Payment Status: Paid

#5309 add BEP+SPL FRONT
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x928e55daB735aa8260AF3cEDadA18B5f70C72f1b/info.json
  blockchains/smartchain/assets/0x928e55daB735aa8260AF3cEDadA18B5f70C72f1b/logo.png
  blockchains/solana/allowlist.json
  blockchains/solana/assets/9S4t2NEAiJVMvPdRYKVrfJpBafPBLtvbvyS3DecojQHw/info.json
  blockchains/solana/assets/9S4t2NEAiJVMvPdRYKVrfJpBafPBLtvbvyS3DecojQHw/logo.png
Labels: Payment Status: Requested

#5310 add ERC20 TORN
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x77777FeDdddFfC19Ff86DB637967013e6C6A116C/info.json
  blockchains/ethereum/assets/0x77777FeDdddFfC19Ff86DB637967013e6C6A116C/logo.png
Labels: Payment Status: Requested

#5315 ETHb update
  blockchains/smartchain/assets/0xc5137E8e017799e71A65e0cFe3F340d719AF17D3/info.json
  blockchains/smartchain/assets/0xc5137E8e017799e71A65e0cFe3F340d719AF17D3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5311 Rebrand Zcoin to Firo
  blockchains/firo/info/info.json
  blockchains/firo/info/logo.png
  blockchains/zcoin/info/info.json
Labels: Payment Status: Requested

#5255 Adding YOP token
  blockchains/ethereum/assets/0xAE1eaAE3F627AAca434127644371b67B18444051/info.json
  blockchains/ethereum/assets/0xAE1eaAE3F627AAca434127644371b67B18444051/logo.png
Labels: Payment Status: Paid

#5319 Update BEPRO token -- #5312
  blockchains/ethereum/assets/0xCF3C8Be2e2C42331Da80EF210e9B1b307C03d36A/info.json
  blockchains/ethereum/assets/0xCF3C8Be2e2C42331Da80EF210e9B1b307C03d36A/logo.png
Labels: Payment Status: Requested

#5322 edit ERC20 PERL
  blockchains/ethereum/assets/0xb5A73f5Fc8BbdbcE59bfD01CA8d35062e0dad801/logo.png
  blockchains/ethereum/assets/0xeca82185adCE47f39c684352B0439f030f860318/logo.png
Labels: Payment Status: Requested

#5324 Added information and logo for Holyheld v2 (HH) token
  blockchains/ethereum/assets/0x3FA729B4548beCBAd4EaB6EF18413470e6D5324C/info.json
  blockchains/ethereum/assets/0x3FA729B4548beCBAd4EaB6EF18413470e6D5324C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5336 Delete old BEFX token!
  blockchains/ethereum/assets/0xB91C2a2b953D72f3EF890490669a0A41B0ADD5f7/logo.png
Labels: Payment Status: Requested

#5329 Add Belifex ( BEFX ) token
  blockchains/ethereum/assets/0xFBcECb002177e530695B8976638fBd18d2038C3C/info.json
  blockchains/ethereum/assets/0xFBcECb002177e530695B8976638fBd18d2038C3C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5334 Add TrueFi (TRU) Token
  blockchains/ethereum/assets/0x4C19596f5aAfF459fA38B0f7eD92F11AE6543784/info.json
  blockchains/ethereum/assets/0x4C19596f5aAfF459fA38B0f7eD92F11AE6543784/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5280 Add RLY token
  blockchains/ethereum/assets/0xf1f955016EcbCd7321c7266BccFB96c68ea5E49b/info.json
  blockchains/ethereum/assets/0xf1f955016EcbCd7321c7266BccFB96c68ea5E49b/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5357 [Internal] Adjust binance tokenlist generation, fix array types
  script/blockchain/binance.ts
  script/generic/tokenlists.ts
  script/generic/update-all.ts
Labels: Payment Status: Requested

#5358 [Internal] Tokenlists.json: Common save, type fixes
  script/blockchain/binance.ts
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#5328 Add Newscrypto (NWC) token
  blockchains/ethereum/assets/0x968F6f898a6Df937fC1859b323aC2F14643e3fED/info.json
  blockchains/ethereum/assets/0x968F6f898a6Df937fC1859b323aC2F14643e3fED/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5373 Add SFI (saffron.finance) logo and info
  blockchains/ethereum/assets/0xb753428af26E81097e7fD17f40c88aaA3E04902c/info.json
  blockchains/ethereum/assets/0xb753428af26E81097e7fD17f40c88aaA3E04902c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5377 [Internal] Binance tokenlist update changes
  package-lock.json
  package.json
  script/blockchain/binance.ts
  script/generic/asset.ts
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#5379 [Internal] Tokenlist version update
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#5382 [Internal] Tokenlists: sort and format smartchain & ethereum tokenlists
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#5376 Add EGG Protocol token info and logo
  blockchains/ethereum/assets/0xd0983dD6a0334c71d0478255D1F794508026b888/info.json
  blockchains/ethereum/assets/0xd0983dD6a0334c71d0478255D1F794508026b888/logo.png
Labels: Payment Status: Paid

#5388 Add HelmetInsure Helmet token info and logo
  blockchains/smartchain/assets/0x948d2a81086A075b3130BAc19e4c6DEe1D2E3fE8/info.json
  blockchains/smartchain/assets/0x948d2a81086A075b3130BAc19e4c6DEe1D2E3fE8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5398 add_BEP20_EGLD
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xbF7c81FFF98BbE61B40Ed186e4AfD6DDd01337fe/info.json
  blockchains/smartchain/assets/0xbF7c81FFF98BbE61B40Ed186e4AfD6DDd01337fe/logo.png
Labels: Payment Status: Requested

#5399 add_BEP20_MirrorAssets
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x23396cF899Ca06c4472205fC903bDB4de249D6fC/info.json
  blockchains/smartchain/assets/0x23396cF899Ca06c4472205fC903bDB4de249D6fC/logo.png
  blockchains/smartchain/assets/0x3947B992DC0147D2D89dF0392213781b04B25075/info.json
  blockchains/smartchain/assets/0x3947B992DC0147D2D89dF0392213781b04B25075/logo.png
  blockchains/smartchain/assets/0x62D71B23bF15218C7d2D7E48DBbD9e9c650B173f/info.json
  blockchains/smartchain/assets/0x62D71B23bF15218C7d2D7E48DBbD9e9c650B173f/logo.png
  blockchains/smartchain/assets/0xF215A127A196e3988C09d052e16BcFD365Cd7AA3/info.json
  blockchains/smartchain/assets/0xF215A127A196e3988C09d052e16BcFD365Cd7AA3/logo.png
  blockchains/smartchain/assets/0xa04F060077D90Fe2647B61e4dA4aD1F97d6649dc/info.json
  blockchains/smartchain/assets/0xa04F060077D90Fe2647B61e4dA4aD1F97d6649dc/logo.png
Labels: Payment Status: Requested

#5393 Armor and arNXM Addition Request
  blockchains/ethereum/assets/0x1337DEF16F9B486fAEd0293eb623Dc8395dFE46a/info.json
  blockchains/ethereum/assets/0x1337DEF16F9B486fAEd0293eb623Dc8395dFE46a/logo.png
  blockchains/ethereum/assets/0x1337DEF18C680aF1f9f45cBcab6309562975b1dD/info.json
  blockchains/ethereum/assets/0x1337DEF18C680aF1f9f45cBcab6309562975b1dD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5402 edit_ERC20_SAND
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x3845badAde8e6dFF049820680d1F14bD3903a5d0/info.json
  blockchains/ethereum/assets/0x3845badAde8e6dFF049820680d1F14bD3903a5d0/logo.png
  blockchains/ethereum/denylist.json
Labels: Payment Status: Requested

#5369 adding shopping.io token
  blockchains/ethereum/assets/0x9B02dD390a603Add5c07f9fd9175b7DABE8D63B7/info.json
  blockchains/ethereum/assets/0x9B02dD390a603Add5c07f9fd9175b7DABE8D63B7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5390 Modify the description of Helmet Token
  blockchains/smartchain/assets/0x948d2a81086A075b3130BAc19e4c6DEe1D2E3fE8/info.json
Labels: Payment Status: Requested

#5342 Update CAG logo & info
  blockchains/ethereum/assets/0x7d4b8Cce0591C9044a22ee543533b72E976E36C3/info.json
  blockchains/ethereum/assets/0x7d4b8Cce0591C9044a22ee543533b72E976E36C3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5347 Add RBC to assets
  blockchains/ethereum/assets/0xA4EED63db85311E22dF4473f87CcfC3DaDCFA3E3/info.json
  blockchains/ethereum/assets/0xA4EED63db85311E22dF4473f87CcfC3DaDCFA3E3/logo.png
Labels: Payment Status: Paid

#5408 Add Toman token #5318 #5381
  blockchains/tron/assets/1003611/info.json
  blockchains/tron/assets/1003611/logo.png
Labels: Payment Status: Paid

#5081 add GYSR ERC20 asset
  blockchains/ethereum/assets/0xbEa98c05eEAe2f3bC8c3565Db7551Eb738c8CCAb/info.json
  blockchains/ethereum/assets/0xbEa98c05eEAe2f3bC8c3565Db7551Eb738c8CCAb/logo.png
Labels: Payment Status: Paid

#5406 Add logo and info for Oasis Network
  blockchains/oasis/info/info.json
  blockchains/oasis/info/logo.png
Labels: Payment Status: Requested

#5395 Update new logo for Bird.Money
  blockchains/ethereum/assets/0x70401dFD142A16dC7031c56E862Fc88Cb9537Ce0/info.json
  blockchains/ethereum/assets/0x70401dFD142A16dC7031c56E862Fc88Cb9537Ce0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5411 [Internal] Merge fee bot config: Change fee to TWT 500 (from 1000)
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#5400 Add Poolz Token logo
  blockchains/ethereum/assets/0x69A95185ee2a045CDC4bCd1b1Df10710395e4e23/info.json
  blockchains/ethereum/assets/0x69A95185ee2a045CDC4bCd1b1Df10710395e4e23/logo.png
Labels: Payment Status: Paid

#5414 [Internal] One-time update of BSC & ETH tokenlists, pairs from PancakeSwap/Uniswap
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#5355 [Internal] Retrieve trading pairs from PancakeSwap
  blockchains/ethereum/tokenlist_base.json
  blockchains/smartchain/tokenlist_base.json
  script/blockchain/binance.ts
  script/blockchain/ethereum.ts
  script/blockchain/smartchain.ts
  script/config.ts
  script/generic/asset.ts
  script/generic/repo-structure.ts
  script/generic/subgraph.ts
  script/generic/tokenlists.ts
  script/generic/update-all.ts
Labels: Payment Status: Paid

#5429 [Internal] Fix for running in Action; Adjust token validity check
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
  blockchains/tezos/validators/list.json
  script/blockchain/ethereum.ts
  script/blockchain/smartchain.ts
  script/generic/subgraph.ts
  script/generic/tokenlists.ts
Labels: Payment Status: Requested

#5416 Add XIO (erc20)
  blockchains/ethereum/assets/0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704/info.json
  blockchains/ethereum/assets/0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704/logo.png
  blockchains/ethereum/assets/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8/info.json
  blockchains/ethereum/assets/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8/logo.png
Labels: Payment Status: Paid

#5440 [Internal] Add BIFI and FRONT trading pairs (Pancakeswap)
  blockchains/smartchain/tokenlist_base.json
Labels: Payment Status: Paid

#5441 [Internal] Disable for now auto-update of Eth&Bsc trading pairs
  script/blockchain/ethereum.ts
  script/blockchain/smartchain.ts
Labels: Payment Status: Paid

#5422 Paid Network
  blockchains/ethereum/assets/0x8c8687fC965593DFb2F0b4EAeFD55E9D8df348df/info.json
  blockchains/ethereum/assets/0x8c8687fC965593DFb2F0b4EAeFD55E9D8df348df/logo.png
Labels: Payment Status: Paid
