Repository trustwallet/assets, pull requests merged in 2021-05, with the labels that each got.

#7156 Add SafeYield Token and Info
  blockchains/smartchain/assets/0x2AE7Bf2937F47FEDbDcE48db8aCa4c5e0b814632/info.json
  blockchains/smartchain/assets/0x2AE7Bf2937F47FEDbDcE48db8aCa4c5e0b814632/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7129 Add TreeDefi - TREE Token
  blockchains/smartchain/assets/0xf0Fcd737fcE18F95621CC7841EbE0eA6EFCCf77e/info.json
  blockchains/smartchain/assets/0xf0Fcd737fcE18F95621CC7841EbE0eA6EFCCf77e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7086 Initial logo files and info json about forestry token
  blockchains/smartchain/assets/0x8c5a93Fa9BB2b0f396E80b51323767043C58E686/info.json
  blockchains/smartchain/assets/0x8c5a93Fa9BB2b0f396E80b51323767043C58E686/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7183 Add BEP20 Kryptobellion token
  blockchains/smartchain/assets/0x9f9830631cd280d62772944a2AF06213E7A23771/info.json
  blockchains/smartchain/assets/0x9f9830631cd280d62772944a2AF06213E7A23771/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7185 Add PantherSwap PANTHER token info
  blockchains/smartchain/assets/0x1f546aD641B56b86fD9dCEAc473d1C7a357276B7/info.json
  blockchains/smartchain/assets/0x1f546aD641B56b86fD9dCEAc473d1C7a357276B7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7075 Update Fairmoon contract address and token info
  blockchains/smartchain/assets/0xCa578afEe65FD2268D383f8Fc4a9fc6Ae1d2Def0/info.json
  blockchains/smartchain/assets/0xCa578afEe65FD2268D383f8Fc4a9fc6Ae1d2Def0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7186 Add PinkMoon logo and information
  blockchains/smartchain/assets/0xb6090a50f66046E3c6aFB9311846a6432E45060A/info.json
  blockchains/smartchain/assets/0xb6090a50f66046E3c6aFB9311846a6432E45060A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7076 World of Waves Token Information
  blockchains/smartchain/assets/0x47e7dd5fA9BBd280C5422E5106b1Da444344c206/info.json
  blockchains/smartchain/assets/0x47e7dd5fA9BBd280C5422E5106b1Da444344c206/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7206 Add BLOWF logo and info
  blockchains/smartchain/assets/0xA55BB91dE33B4abdf3aC64913D98A55ad84Dc3A8/info.json
  blockchains/smartchain/assets/0xA55BB91dE33B4abdf3aC64913D98A55ad84Dc3A8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7205 SafeComet Protocol
  blockchains/smartchain/assets/0xB667bbfE0DcEdae1a53555a0e8B0a14EAf0d5231/info.json
  blockchains/smartchain/assets/0xB667bbfE0DcEdae1a53555a0e8B0a14EAf0d5231/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7163 check summed ready to go
  blockchains/smartchain/assets/0x86432b9beA373172C852D5bbAB1c275FeC3f15aE/info.json
  blockchains/smartchain/assets/0x86432b9beA373172C852D5bbAB1c275FeC3f15aE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7208 Add Tako Token (BEP20)
  blockchains/smartchain/assets/0x2F3391AeBE27393aBa0a790aa5E1577fEA0361c2/info.json
  blockchains/smartchain/assets/0x2F3391AeBE27393aBa0a790aa5E1577fEA0361c2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7210 Add MRST logo and Info
  blockchains/smartchain/assets/0xcCc2d670E801570247E9De1841480F52A62Eb6F3/info.json
  blockchains/smartchain/assets/0xcCc2d670E801570247E9De1841480F52A62Eb6F3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7031 Add BSC Gold ( BSCGold ) LOGO Bep20
  blockchains/smartchain/assets/0x34195FD824355aec1BDCeEA97697B35be691bcB3/info.json
  blockchains/smartchain/assets/0x34195FD824355aec1BDCeEA97697B35be691bcB3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Correction needed

#7160 Add QuickSwap token & info
  blockchains/ethereum/assets/0x6c28AeF8977c9B773996d0e8376d2EE379446F2f/info.json
  blockchains/ethereum/assets/0x6c28AeF8977c9B773996d0e8376d2EE379446F2f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Correction needed

#7180 add OCTI info and logo
  blockchains/smartchain/assets/0x6c1dE9907263F0c12261d88b65cA18F31163F29D/info.json
  blockchains/smartchain/assets/0x6c1dE9907263F0c12261d88b65cA18F31163F29D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: Correction needed

#7231 Add AquaGoat (BEP20)
  blockchains/smartchain/assets/0x07af67b392B7A202fAD8E0FBc64C34F33102165B/info.json
  blockchains/smartchain/assets/0x07af67b392B7A202fAD8E0FBc64C34F33102165B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7243 Add SafePanda Logo and Icon
  blockchains/smartchain/assets/0x75e3CF3DC6748ff6c92FE77646bE7d2fdFdFA623/info.json
  blockchains/smartchain/assets/0x75e3CF3DC6748ff6c92FE77646bE7d2fdFdFA623/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7242 Add SafeXI
  blockchains/smartchain/assets/0xA327179d47faD68d09e4501a838daaaf74faBb7c/info.json
  blockchains/smartchain/assets/0xA327179d47faD68d09e4501a838daaaf74faBb7c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6885 Saito ERC20
  blockchains/ethereum/assets/0xFa14Fa6958401314851A17d6C5360cA29f74B57B/info.json
  blockchains/ethereum/assets/0xFa14Fa6958401314851A17d6C5360cA29f74B57B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7226 GDM Logo Update
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x9FdB6a13BdCF1188FbAFe5CD435A8b92a327D92e/info.json
  blockchains/smartchain/assets/0x9FdB6a13BdCF1188FbAFe5CD435A8b92a327D92e/logo.png
Labels: Payment Status: Paid

#7252 Add GEMS logo and info
  blockchains/smartchain/assets/0xDfDec49462f7D3C3b0A48E729F77A0645CDFA7c0/info.json
  blockchains/smartchain/assets/0xDfDec49462f7D3C3b0A48E729F77A0645CDFA7c0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7254 Migrate BitStash (STASH) token re-opened from previous pull request
  blockchains/ethereum/assets/0x965F109d31CCb77005858DEfaE0Ebaf7B4381652/info.json
  blockchains/ethereum/assets/0xE4F356EcCe6FbDA81eCDea2E38527e59422861C2/info.json
  blockchains/ethereum/assets/0xE4F356EcCe6FbDA81eCDea2E38527e59422861C2/logo.png
Labels: Payment Status: Paid

#7250 Updated our token info and logo to be accurate
  blockchains/smartchain/assets/0xB3225aC90B741f762BecA76dEA1eaD278Ef26A96/info.json
  blockchains/smartchain/assets/0xB3225aC90B741f762BecA76dEA1eaD278Ef26A96/logo.png
Labels: Payment Status: Paid

#7142 Add MCHC
  blockchains/ethereum/assets/0xD69F306549e9d96f183B1AecA30B8f4353c2ECC3/info.json
  blockchains/ethereum/assets/0xD69F306549e9d96f183B1AecA30B8f4353c2ECC3/logo.png
Labels: Payment Status: Paid

#7093 Add KILIMANJARO (BEP20)
  blockchains/smartchain/assets/0x865d0c78d08BD6e5f0db6BCbF36d3F8EB4ad48F8/info.json
  blockchains/smartchain/assets/0x865d0c78d08BD6e5f0db6BCbF36d3F8EB4ad48F8/logo.png
Labels: Payment Status: Paid

#7077 SafeSex Finance Info and Logo
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x6eA05F63DAF6b0Dc6b8bea94342330CC602c5536/info.json
  blockchains/smartchain/assets/0x6eA05F63DAF6b0Dc6b8bea94342330CC602c5536/logo.png
Labels: Payment Status: Paid

#7041 Update logo sizing and round shape
  blockchains/smartchain/assets/0xFE7E350009a1f3915352022B1BFc2087D7B1D1CD/logo.png
Labels: Payment Status: Paid

#6959 Upload CumRocket Logo and Info
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/info.json
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/logo.png
Labels: Payment Status: Paid

#6938 Add XMPT Logo And Info
  blockchains/smartchain/assets/0x8099C0c7b3E530F563d4B121Abd2Ee365c72fB78/info.json
  blockchains/smartchain/assets/0x8099C0c7b3E530F563d4B121Abd2Ee365c72fB78/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6803 Add ProjectPanda
  blockchains/smartchain/assets/0x4273d797Ebc0063d5d887B1e67daD4A43E2Fd244/info.json
  blockchains/smartchain/assets/0x4273d797Ebc0063d5d887B1e67daD4A43E2Fd244/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6941 Add Sheesh Logo and Info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x7E5d52C3335C91Af0da392BEa4BB9e43F2AbA62C/info.json
  blockchains/smartchain/assets/0x7E5d52C3335C91Af0da392BEa4BB9e43F2AbA62C/logo.png
Labels: Payment Status: Paid

#7273 Update DEPAY information
  blockchains/ethereum/assets/0xa0bEd124a09ac2Bd941b10349d8d224fe3c955eb/info.json
  blockchains/ethereum/assets/0xa0bEd124a09ac2Bd941b10349d8d224fe3c955eb/logo.png
Labels: Payment Status: Paid

#7276 Adding Logo and Information for IronyMan (BSC)
  blockchains/smartchain/assets/0x2C40a80565B595C03cd94217c077c47E3F41937E/info.json
  blockchains/smartchain/assets/0x2C40a80565B595C03cd94217c077c47E3F41937E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7279 Add KOBT logo and info
  blockchains/smartchain/assets/0x96bbE4376802eCc0eFD330AF76B8873183270671/info.json
  blockchains/smartchain/assets/0x96bbE4376802eCc0eFD330AF76B8873183270671/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7239 Adding Nestle Finance logo and INFO
  blockchains/smartchain/assets/0xf79a6caDa446F331BC560CDE7946d09AEF0EE18B/info.json
  blockchains/smartchain/assets/0xf79a6caDa446F331BC560CDE7946d09AEF0EE18B/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#7282 Update logo
  blockchains/smartchain/assets/0x8c5a93Fa9BB2b0f396E80b51323767043C58E686/info.json
  blockchains/smartchain/assets/0x8c5a93Fa9BB2b0f396E80b51323767043C58E686/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6625 Add Macaron Swap Token (MCRN)
  blockchains/smartchain/assets/0xacb2d47827C9813AE26De80965845D80935afd0B/info.json
  blockchains/smartchain/assets/0xacb2d47827C9813AE26De80965845D80935afd0B/logo.png
Labels: Payment Status: Paid, Status: On Hold

#7222 update info + logo for bakerytools
  blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/info.json
  blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#7297 Add 8PAY logo and info
  blockchains/smartchain/assets/0xFeea0bDd3D07eb6FE305938878C0caDBFa169042/info.json
  blockchains/smartchain/assets/0xFeea0bDd3D07eb6FE305938878C0caDBFa169042/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7308 Add Securabyte (BEP20)
  blockchains/smartchain/assets/0x0Fe3e956D2034BCEF01FbA8A2BfCA389cdb72699/info.json
  blockchains/smartchain/assets/0x0Fe3e956D2034BCEF01FbA8A2BfCA389cdb72699/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7277 update logo and info BSCS token
  blockchains/smartchain/assets/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D/info.json
  blockchains/smartchain/assets/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7318 Sheep Token info and logo
  blockchains/smartchain/assets/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4/info.json
  blockchains/smartchain/assets/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7310 Updated logo and twitter information
  blockchains/smartchain/assets/0x3D29Aa78fB558F84112bbC48a84F371147A920C9/info.json
  blockchains/smartchain/assets/0x3D29Aa78fB558F84112bbC48a84F371147A920C9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7082 Add LEM logo and info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xc35f46aAEb8aD17bCbAa78c03540FEffa44790Cb/info.json
  blockchains/smartchain/assets/0xc35f46aAEb8aD17bCbAa78c03540FEffa44790Cb/logo.png
Labels: Payment Status: Paid

#7294 Add Euler (BEP20)
  blockchains/smartchain/assets/0x3920123482070C1a2dff73AaD695c60e7c6F6862/info.json
  blockchains/smartchain/assets/0x3920123482070C1a2dff73AaD695c60e7c6F6862/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7327 Add SAFESPACE (BEP20)
  blockchains/smartchain/assets/0xe1DB3d1eE5CfE5C6333BE96e6421f9Bd5b85c987/info.json
  blockchains/smartchain/assets/0xe1DB3d1eE5CfE5C6333BE96e6421f9Bd5b85c987/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7326 Update info.json
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#7306 Add Power Cash (PRCH), TRC20 token.
  blockchains/tron/assets/TA6JuPYq2bFCRdTGyQtdTa2Xj5B4NB7sm1/info.json
  blockchains/tron/assets/TA6JuPYq2bFCRdTGyQtdTa2Xj5B4NB7sm1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7334 Added img + support files for GAMER (GMR) Token
  blockchains/smartchain/assets/0x0523215DCafbF4E4aA92117d13C6985a3BeF27D7/info.json
  blockchains/smartchain/assets/0x0523215DCafbF4E4aA92117d13C6985a3BeF27D7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6823 FTS
  blockchains/smartchain/assets/0x4437743ac02957068995c48E08465E0EE1769fBE/info.json
  blockchains/smartchain/assets/0x4437743ac02957068995c48E08465E0EE1769fBE/logo.png
Labels: Payment Status: Paid

#7322 Add Franklin (FLy) (ERC20)
  blockchains/ethereum/assets/0x85f6eB2BD5a062f5F8560BE93FB7147e16c81472/info.json
  blockchains/ethereum/assets/0x85f6eB2BD5a062f5F8560BE93FB7147e16c81472/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7296 Update info.json
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/info.json
Labels: Payment Status: Requested

#7304 fixes for logo.png
  blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/info.json
  blockchains/smartchain/assets/0x26D6e280F9687c463420908740AE59f712419147/logo.png
Labels: Payment Status: Paid

#7288 Add upBNB (upBNB) logo and info
  blockchains/smartchain/assets/0x9C3Bbff333F4AEAB60B3c060607b7C505Ff30C82/info.json
  blockchains/smartchain/assets/0x9C3Bbff333F4AEAB60B3c060607b7C505Ff30C82/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#7030 Add Wrapped IQ.Cash (WIQ, BEP20) [Multi-Chain]
  blockchains/smartchain/assets/0x8F1B7df4a34C8Dd072CF6408Be9c778CFABdf8D0/info.json
  blockchains/smartchain/assets/0x8F1B7df4a34C8Dd072CF6408Be9c778CFABdf8D0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7339 add Jigstack token
  blockchains/ethereum/assets/0x1F8A626883d7724DBd59eF51CBD4BF1Cf2016D13/info.json
  blockchains/ethereum/assets/0x1F8A626883d7724DBd59eF51CBD4BF1Cf2016D13/logo.png
Labels: Payment Status: Paid

#7352 Add ALPACA logo and info
  blockchains/smartchain/assets/0x8F0528cE5eF7B51152A59745bEfDD91D97091d2F/info.json
  blockchains/smartchain/assets/0x8F0528cE5eF7B51152A59745bEfDD91D97091d2F/logo.png
Labels: Payment Status: Paid

#7358 Add Ares Protocol (ERC20)
  blockchains/ethereum/assets/0x358AA737e033F34df7c54306960a38d09AaBd523/info.json
  blockchains/ethereum/assets/0x358AA737e033F34df7c54306960a38d09AaBd523/logo.png
Labels: Payment Status: Paid

#7365 Add ACXT token on Trust Wallet and Uniswap
  blockchains/ethereum/assets/0x7bE00ed6796B21656732E8f739Fc1b8F1C53DA0D/info.json
  blockchains/ethereum/assets/0x7bE00ed6796B21656732E8f739Fc1b8F1C53DA0D/logo.png
Labels: Payment Status: Paid

#7362 Added BICHON info and logo files
  blockchains/smartchain/assets/0xDf394853D830424CaFCCF7Be7dF065366cF31a69/info.json
  blockchains/smartchain/assets/0xDf394853D830424CaFCCF7Be7dF065366cF31a69/logo.png
Labels: Payment Status: Paid

#7342 Add FEG ETH token
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/info.json
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/logo.png
  blockchains/ethereum/assets/0x52b65CE1391C49eaE108017c4442077b3C2Bd17a/info.json
  blockchains/ethereum/assets/0x52b65CE1391C49eaE108017c4442077b3C2Bd17a/logo.png
  blockchains/ethereum/assets/0x979838c9C16FD365C9fE028B0bEa49B1750d86e9/info.json
  blockchains/ethereum/assets/0x979838c9C16FD365C9fE028B0bEa49B1750d86e9/logo.png
  blockchains/ethereum/assets/0xe3cDB92b094a3BeF3f16103b53bECfb17A3558ad/info.json
  blockchains/ethereum/assets/0xe3cDB92b094a3BeF3f16103b53bECfb17A3558ad/logo.png
  blockchains/smartchain/assets/0x42fDd09fcA12359f32E3D36f1700E480Ff6eBb49/info.json
  blockchains/smartchain/assets/0x42fDd09fcA12359f32E3D36f1700E480Ff6eBb49/logo.png
  blockchains/smartchain/assets/0xB723F6dCE74BbdE8f19ac882e539C1C53fDb888B/info.json
  blockchains/smartchain/assets/0xB723F6dCE74BbdE8f19ac882e539C1C53fDb888B/logo.png
  blockchains/smartchain/assets/0xD3ba3FB9014AB0b67ea9af05d9b690BFa2305DC2/info.json
  blockchains/smartchain/assets/0xD3ba3FB9014AB0b67ea9af05d9b690BFa2305DC2/logo.png
  blockchains/smartchain/assets/0xEf11aB854b475Bd0c5Db37f6bFFAB443219d656d/info.json
  blockchains/smartchain/assets/0xEf11aB854b475Bd0c5Db37f6bFFAB443219d656d/logo.png
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/info.json
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/logo.png
  blockchains/smartchain/assets/0xfB17D214d83643da1b079d410647c33aBcE972e2/info.json
  blockchains/smartchain/assets/0xfB17D214d83643da1b079d410647c33aBcE972e2/logo.png
Labels: Payment Status: Paid

#7353 Added EQL info & logo for BSC
  blockchains/smartchain/assets/0x5C7e71f46e49Cf816f9863461EEB36e3bc8E3B51/info.json
  blockchains/smartchain/assets/0x5C7e71f46e49Cf816f9863461EEB36e3bc8E3B51/logo.png
Labels: Payment Status: Paid

#6497 Add files via upload
  blockchains/smartchain/assets/0xCE195c777e1ce96C30ebeC54C91d20417a068706/info.json
  blockchains/smartchain/assets/0xCE195c777e1ce96C30ebeC54C91d20417a068706/logo.png
Labels: Payment Status: Paid

#6609 Decentral Games logo and info.json
  blockchains/ethereum/assets/0xEE06A81a695750E71a662B51066F2c74CF4478a0/info.json
  blockchains/ethereum/assets/0xEE06A81a695750E71a662B51066F2c74CF4478a0/logo.png
Labels: Payment Status: Paid

#6612 Add UnderDog Logo & Info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xF94CA0B303e52d68b63626Bed7f680fa4DC3f779/info.json
  blockchains/smartchain/assets/0xF94CA0B303e52d68b63626Bed7f680fa4DC3f779/logo.png
Labels: Payment Status: Paid

#6725 Add Berryswap Logo and Info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x8626F099434d9A7E603B8f0273880209eaBfc1c5/info.json
  blockchains/smartchain/assets/0x8626F099434d9A7E603B8f0273880209eaBfc1c5/logo.png
Labels: Payment Status: Paid

#7381 submit XPO logo and info
  blockchains/smartchain/assets/0xeBB59CeBFb63f218db6B5094DC14AbF34d56D35D/info.json
  blockchains/smartchain/assets/0xeBB59CeBFb63f218db6B5094DC14AbF34d56D35D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7020 Submitting a Token Logo and information updation request for Quamnetwork
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8/info.json
  blockchains/smartchain/assets/0x1AdE17B4B38B472B5259BbC938618226dF7b5Ca8/logo.png
Labels: Payment Status: Paid

#7387 Add PAPP Mobile (BEP20)
  blockchains/smartchain/assets/0xCd77880edea8E7D1f2be011BE560B45B96Ba68Ad/info.json
  blockchains/smartchain/assets/0xCd77880edea8E7D1f2be011BE560B45B96Ba68Ad/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7386 Add LEOPARD (BEP20)
  blockchains/smartchain/assets/0x4Efab39b14167Da54aebed2094a61aA1FD384056/info.json
  blockchains/smartchain/assets/0x4Efab39b14167Da54aebed2094a61aA1FD384056/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7388 Add COPTER logo and info
  blockchains/smartchain/assets/0xBC12aD556581ff7162E595E5956F5F3845FDB38c/info.json
  blockchains/smartchain/assets/0xBC12aD556581ff7162E595E5956F5F3845FDB38c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6126 Update WHIRL info
  blockchains/smartchain/assets/0x7f479d78380Ad00341fdD7322fE8AEf766e29e5A/info.json
Labels: Payment Status: Paid, Status: Correction needed

#7402 Add SafeUniverse (BEP20)
  blockchains/smartchain/assets/0xfb68406D38BaF071297f5a3AB97AfFd5945c1db9/info.json
  blockchains/smartchain/assets/0xfb68406D38BaF071297f5a3AB97AfFd5945c1db9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7400 SafeBANK submission
  blockchains/smartchain/assets/0x2aB90FBb649bA3DDD4269764eb2975d8F32b7b5a/info.json
  blockchains/smartchain/assets/0x2aB90FBb649bA3DDD4269764eb2975d8F32b7b5a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7396 Add CLEANOCEAN
  blockchains/smartchain/assets/0x579F11C75Eb4e47F5290122e87CA411644aDCD97/info.json
  blockchains/smartchain/assets/0x579F11C75Eb4e47F5290122e87CA411644aDCD97/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7347 Add GoldCoin Reserve (BEP20)
  blockchains/smartchain/assets/0x451D0e4B04A16223BbaeCe67b2276223DB0d19dA/info.json
  blockchains/smartchain/assets/0x451D0e4B04A16223BbaeCe67b2276223DB0d19dA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7427 Add Raydium (SPL)
  blockchains/solana/assets/7nJGERf1LZpjn4uTfcDZLJ6YRtvdSExAB9uK851zT6do/info.json
  blockchains/solana/assets/7nJGERf1LZpjn4uTfcDZLJ6YRtvdSExAB9uK851zT6do/logo.png
Labels: Payment Status: Requested

#7424 Add Poodledog logo
  blockchains/smartchain/assets/0x4487A8a40caa9fA0e70B9041C368b6e0d4089314/info.json
  blockchains/smartchain/assets/0x4487A8a40caa9fA0e70B9041C368b6e0d4089314/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7345 Added SG-1 Cosmos and Kava validators
  blockchains/cosmos/validators/assets/cosmosvaloper196ax4vc0lwpxndu9dyhvca7jhxp70rmcvrj90c/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/assets/kavavaloper1ppj7c8tqt2e3rzqtmztsmd6ea6u3nz6qggcp5e/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Requested

#7434 Add LAZACA (BEP20)
  blockchains/smartchain/assets/0x5EC8B32Ff33f8df977402F44602A59998941d240/info.json
  blockchains/smartchain/assets/0x5EC8B32Ff33f8df977402F44602A59998941d240/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7437 add BEP20 ODS(OpenBiSea.io) token
  blockchains/smartchain/assets/0x490DbA6180b089d8E36eBb1E56a33F1aE9B96b87/info.json
  blockchains/smartchain/assets/0x490DbA6180b089d8E36eBb1E56a33F1aE9B96b87/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7404 corrected logo for Helicopter Finance
  blockchains/smartchain/assets/0xBC12aD556581ff7162E595E5956F5F3845FDB38c/logo.png
Labels: Payment Status: Paid

#7443 KimJongMoon Token submission
  blockchains/smartchain/assets/0x737f0E47c4d4167a3eEcde5FA87306b6eEe3140e/info.json
  blockchains/smartchain/assets/0x737f0E47c4d4167a3eEcde5FA87306b6eEe3140e/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#7458 Adding SAFEBULL
  blockchains/smartchain/assets/0xFA344C08C93066A4d6266063C6Ebc63925a18467/info.json
  blockchains/smartchain/assets/0xFA344C08C93066A4d6266063C6Ebc63925a18467/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7480 Add JDI Token (BEP20)
  blockchains/smartchain/assets/0x0491648C910ad2c1aFaab733faF71D30313Df7FC/info.json
  blockchains/smartchain/assets/0x0491648C910ad2c1aFaab733faF71D30313Df7FC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7463 Add TrustPad info
  blockchains/smartchain/assets/0xADCFC6bf853a0a8ad7f9Ff4244140D10cf01363C/info.json
  blockchains/smartchain/assets/0xADCFC6bf853a0a8ad7f9Ff4244140D10cf01363C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7460 Add Hokkaidu Inu (HOKK) (ERC20)
  blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/info.json
  blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7487 Add Milk (BEP20)
  blockchains/smartchain/assets/0xb7CEF49d89321e22dd3F51a212d58398Ad542640/info.json
  blockchains/smartchain/assets/0xb7CEF49d89321e22dd3F51a212d58398Ad542640/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6966 Add Thanos Token Logo
  blockchains/smartchain/assets/0x295F2122EbfCC5c38b4Bd33879A37348195b61fb/info.json
  blockchains/smartchain/assets/0x295F2122EbfCC5c38b4Bd33879A37348195b61fb/logo.png
Labels: Payment Status: Paid, Status: On Hold

#7448 add logo info
  blockchains/smartchain/assets/0x1b9E14122Cb416845F0f21967f38b5c3e74De774/info.json
  blockchains/smartchain/assets/0x1b9E14122Cb416845F0f21967f38b5c3e74De774/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7495 [Internal] Fix ERC20 explorers
  blockchains/ethereum/assets/0x054D64b73d3D8A21Af3D764eFd76bCaA774f3Bb2/info.json
  blockchains/ethereum/assets/0x111111111117dC0aa78b770fA6A738034120C302/info.json
  blockchains/ethereum/assets/0x1337DEF16F9B486fAEd0293eb623Dc8395dFE46a/info.json
  blockchains/ethereum/assets/0x1337DEF18C680aF1f9f45cBcab6309562975b1dD/info.json
  blockchains/ethereum/assets/0x175D9Dfd6850AA96460E29bC0cEad05756965E91/info.json
  blockchains/ethereum/assets/0x1F8A626883d7724DBd59eF51CBD4BF1Cf2016D13/info.json
  blockchains/ethereum/assets/0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0/info.json
  blockchains/ethereum/assets/0x3A880652F47bFaa771908C07Dd8673A787dAEd3A/info.json
  blockchains/ethereum/assets/0x3C03b4EC9477809072FF9CC9292C9B25d4A8e6c6/info.json
  blockchains/ethereum/assets/0x4A64515E5E1d1073e83f30cB97BEd20400b66E10/info.json
  blockchains/ethereum/assets/0x50DE6856358Cc35f3A9a57eAAA34BD4cB707d2cd/info.json
  blockchains/ethereum/assets/0x53c4871322Bb47e7A24136fce291a6dcC832a294/info.json
  blockchains/ethereum/assets/0x5Dc02Ea99285E17656b8350722694c35154DB1E8/info.json
  blockchains/ethereum/assets/0x5Eaa69B29f99C84Fe5dE8200340b4e9b4Ab38EaC/info.json
  blockchains/ethereum/assets/0x5a666c7d92E5fA7Edcb6390E4efD6d0CDd69cF37/info.json
  blockchains/ethereum/assets/0x62A6738d887F47e297676FaB05b902709B106C64/info.json
  blockchains/ethereum/assets/0x639ae8F3EEd18690bF451229d14953a5A5627b72/info.json
  blockchains/ethereum/assets/0x6e1A19F235bE7ED8E3369eF73b196C07257494DE/info.json
  blockchains/ethereum/assets/0x725C263e32c72dDC3A19bEa12C5a0479a81eE688/info.json
  blockchains/ethereum/assets/0x72630B1e3B42874bf335020Ba0249e3E9e47Bafc/info.json
  blockchains/ethereum/assets/0x7BD198b9107496fD5cC3d7655AF52f43a8eDBc4C/info.json
  blockchains/ethereum/assets/0x88EF27e69108B2633F8E1C184CC37940A075cC02/info.json
  blockchains/ethereum/assets/0x961C8c0B1aaD0c0b10a51FeF6a867E3091BCef17/info.json
  blockchains/ethereum/assets/0x9EA3b5b4EC044b70375236A281986106457b20EF/info.json
  blockchains/ethereum/assets/0xA3865E64121537b5b59B5e239Db4aCBe6F36aa74/info.json
  blockchains/ethereum/assets/0xBBC7f7A6AADAc103769C66CBC69AB720f7F9Eae3/info.json
  blockchains/ethereum/assets/0xBD2F0Cd039E0BFcf88901C98c0bFAc5ab27566e3/info.json
  blockchains/ethereum/assets/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6/info.json
  blockchains/ethereum/assets/0xD5cd84D6f044AbE314Ee7E414d37cae8773ef9D3/info.json
  blockchains/ethereum/assets/0xE452E6Ea2dDeB012e20dB73bf5d3863A3Ac8d77a/info.json
  blockchains/ethereum/assets/0xE61fDAF474Fac07063f2234Fb9e60C1163Cfa850/info.json
  blockchains/ethereum/assets/0xEA1ea0972fa092dd463f2968F9bB51Cc4c981D71/info.json
  blockchains/ethereum/assets/0xEB58343b36C7528F23CAAe63a150240241310049/info.json
  blockchains/ethereum/assets/0xF59ae934f6fe444afC309586cC60a84a0F89Aaea/info.json
  blockchains/ethereum/assets/0xF94b5C5651c888d928439aB6514B93944eEE6F48/info.json
  blockchains/ethereum/assets/0xad3E3Fc59dff318BecEaAb7D00EB4F68b1EcF195/info.json
  blockchains/ethereum/assets/0xbA745513ACEbcBb977497C569D4F7d340f2A936B/info.json
  blockchains/ethereum/assets/0xba358B6f5b4c0215650444B8C30D870B55050D2D/info.json
  blockchains/ethereum/assets/0xba7b2C094C1A4757f9534a37d296a3BeD7f544DC/info.json
Labels: Payment Status: Paid

#7482 Update FEED description
  blockchains/smartchain/assets/0xB1731E5e035CB039298159EcB191cB3fe666Dd0e/info.json
  blockchains/smartchain/assets/0xB1731E5e035CB039298159EcB191cB3fe666Dd0e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7506 FINAL UPDATED LOGO AND INFO already paid #7435
  blockchains/smartchain/assets/0xAc4c2903fb2f073e94De57c79D8Bec5155662122/info.json
  blockchains/smartchain/assets/0xAc4c2903fb2f073e94De57c79D8Bec5155662122/logo.png
Labels: Payment Status: Requested

#7512 Add NFTPunk.Finance (BEP20)
  blockchains/smartchain/assets/0x31DE61D9a39CB9f479570Bd3dC3AC93BC0402CDB/info.json
  blockchains/smartchain/assets/0x31DE61D9a39CB9f479570Bd3dC3AC93BC0402CDB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7521 Add SAT logo and info
  blockchains/smartchain/assets/0xA1928c0D8F83C0bFB7ebE51B412b1FD29A277893/info.json
  blockchains/smartchain/assets/0xA1928c0D8F83C0bFB7ebE51B412b1FD29A277893/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7539 Add DragonMusk Logo
  blockchains/smartchain/assets/0x338196a509B4c66749c3f44c21C00501E6ACF7BC/info.json
  blockchains/smartchain/assets/0x338196a509B4c66749c3f44c21C00501E6ACF7BC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7536 Add GETART Token (BEP20)
  blockchains/smartchain/assets/0x5507f52C96e64e5e5c3dF0Ea90d3515fc0c7d9dF/info.json
  blockchains/smartchain/assets/0x5507f52C96e64e5e5c3dF0Ea90d3515fc0c7d9dF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7503 Add SHOPX token (ERC20)
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/info.json
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7461 Add MEPAD Logo And Info
  blockchains/smartchain/assets/0x9d70a3EE3079A6FA2bB16591414678b7Ad91f0b5/info.json
  blockchains/smartchain/assets/0x9d70a3EE3079A6FA2bB16591414678b7Ad91f0b5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7530 Add Safeicarus logo and info
  blockchains/smartchain/assets/0xD2f9B51C6a1b5598f0ea51eF95d70cB045692D0F/info.json
  blockchains/smartchain/assets/0xD2f9B51C6a1b5598f0ea51eF95d70cB045692D0F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7532 Add HyperChain (BEP20)
  blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/info.json
  blockchains/smartchain/assets/0x565D931cBa7C7E1af3925f77124D5e2d68311BBE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7511 Add Moonlight Token (BEP20)
  blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json
  blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Status: On Hold

#7545 Add bird token info Request
  blockchains/smartchain/assets/0x7f1296e5aA692a98d86EaAe3ac1CD7723E74878d/info.json
  blockchains/smartchain/assets/0x7f1296e5aA692a98d86EaAe3ac1CD7723E74878d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7476 Add new wrapped tokens
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/info.json
  blockchains/ethereum/assets/0x8E4B1E38c082C7cEb638c084C102352421FE607F/info.json
  blockchains/ethereum/assets/0x8E4B1E38c082C7cEb638c084C102352421FE607F/logo.png
  blockchains/ethereum/assets/0xBC84F95f089b9291C552EBA09D30Fd56A932AFC9/info.json
  blockchains/ethereum/assets/0xBC84F95f089b9291C552EBA09D30Fd56A932AFC9/logo.png
  blockchains/ethereum/assets/0xf786c34106762Ab4Eeb45a51B42a62470E9D5332/info.json
  blockchains/ethereum/assets/0xf786c34106762Ab4Eeb45a51B42a62470E9D5332/logo.png
  blockchains/smartchain/assets/0x05c1EFdEbB8A12f2F3A8DEE07eC4Aa5c452BDAF0/info.json
  blockchains/smartchain/assets/0x05c1EFdEbB8A12f2F3A8DEE07eC4Aa5c452BDAF0/logo.png
  blockchains/smartchain/assets/0x38b4119845b5A60D48178a17C9215162E84856ed/info.json
  blockchains/smartchain/assets/0x38b4119845b5A60D48178a17C9215162E84856ed/logo.png
  blockchains/smartchain/assets/0x7e2d99B3b4854E741dC6ada101937A1a3aAb861e/info.json
  blockchains/smartchain/assets/0x7e2d99B3b4854E741dC6ada101937A1a3aAb861e/logo.png
  blockchains/smartchain/assets/0x87b1AccE6a1958E522233A737313C086551a5c76/info.json
  blockchains/smartchain/assets/0x87b1AccE6a1958E522233A737313C086551a5c76/logo.png
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#7514 bficoin We are adding bfic coin logo
  blockchains/smartchain/assets/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/info.json
  blockchains/smartchain/assets/0xF0a0913BA2b173c1fbCa1c1b2FCFC0E3678f66a9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7548 Add Corgi doge - CORGI
  blockchains/smartchain/assets/0x802C68730212295149f2bEa78C25e2Cf5A05B8A0/info.json
  blockchains/smartchain/assets/0x802C68730212295149f2bEa78C25e2Cf5A05B8A0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7546 add_BEP20_UNAGI
  blockchains/smartchain/assets/0x8f20eBD7Cdb3eFdb51D58D582a21e1A0b41F4436/info.json
  blockchains/smartchain/assets/0x8f20eBD7Cdb3eFdb51D58D582a21e1A0b41F4436/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7528 Update TACO logo and add SALSA logo
  blockchains/ethereum/assets/0x00D1793D7C3aAE506257Ba985b34C76AaF642557/info.json
  blockchains/ethereum/assets/0x00D1793D7C3aAE506257Ba985b34C76AaF642557/logo.png
  blockchains/ethereum/assets/0x82E5aeC4e37b37FCA34925C13429506209A98536/info.json
  blockchains/ethereum/assets/0x82E5aeC4e37b37FCA34925C13429506209A98536/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7550 Add wBIS logo and info
  blockchains/ethereum/assets/0xf5cB350b40726B5BcF170d12e162B6193b291B41/info.json
  blockchains/ethereum/assets/0xf5cB350b40726B5BcF170d12e162B6193b291B41/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7544 feat: Add Fire Token Data
  blockchains/smartchain/assets/0xBaCbF768795C50FC5E877830A127276741651D0a/info.json
  blockchains/smartchain/assets/0xBaCbF768795C50FC5E877830A127276741651D0a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7561 Add MDX (ERC20)
  blockchains/ethereum/assets/0x947AEb02304391f8fbE5B25D7D98D649b57b1788/info.json
  blockchains/ethereum/assets/0x947AEb02304391f8fbE5B25D7D98D649b57b1788/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7527 Add Dopple (DOP) Token
  blockchains/smartchain/assets/0x844FA82f1E54824655470970F7004Dd90546bB28/info.json
  blockchains/smartchain/assets/0x844FA82f1E54824655470970F7004Dd90546bB28/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7570 HalalCoin BSC Token add
  blockchains/smartchain/assets/0x9AeF8F6a15cC1de43Ce6445A6fE2d344D3843a29/info.json
  blockchains/smartchain/assets/0x9AeF8F6a15cC1de43Ce6445A6fE2d344D3843a29/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7579 Adding Logo for Rhyme$Coin
  blockchains/smartchain/assets/0x55183148d5C3360cbB0e1EDb38b30e091aEE4D65/info.json
  blockchains/smartchain/assets/0x55183148d5C3360cbB0e1EDb38b30e091aEE4D65/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7574 new token and info
  blockchains/ethereum/assets/0x668C50B1c7f46EFFBE3f242687071d7908AAB00A/info.json
  blockchains/ethereum/assets/0x668C50B1c7f46EFFBE3f242687071d7908AAB00A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7573 Add Anonymous (BEP20)
  blockchains/smartchain/assets/0xFd78aAEd1e3f2d06DbDE9510C6dC14112eCA896D/info.json
  blockchains/smartchain/assets/0xFd78aAEd1e3f2d06DbDE9510C6dC14112eCA896D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7572 Add SharedStake Governance Token logo and info
  blockchains/ethereum/assets/0x84810bcF08744d5862B8181f12d17bfd57d3b078/info.json
  blockchains/ethereum/assets/0x84810bcF08744d5862B8181f12d17bfd57d3b078/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7253 Add Shih Tzu logo and Info
  blockchains/ethereum/assets/0x841FB148863454A3b3570f515414759BE9091465/info.json
  blockchains/ethereum/assets/0x841FB148863454A3b3570f515414759BE9091465/logo.png
Labels: Payment Status: Paid, Status: On Hold

#7584 fixed logo it wasn't showing correctly everywhere
  blockchains/smartchain/assets/0xFd78aAEd1e3f2d06DbDE9510C6dC14112eCA896D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7557 Add ElonSperm logo and info
  blockchains/smartchain/assets/0x7Abf7f54F30a45c7c43D728A75d6741440d7c591/info.json
  blockchains/smartchain/assets/0x7Abf7f54F30a45c7c43D728A75d6741440d7c591/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7586 Add WILLIE logo and info
  blockchains/smartchain/assets/0x27327672D1dc51F4Dc58c9F413E1FA7e7ad8245e/info.json
  blockchains/smartchain/assets/0x27327672D1dc51F4Dc58c9F413E1FA7e7ad8245e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7571 Add Vulkania (BEP20)
  blockchains/smartchain/assets/0x0921d788E7f7498f80adb0A0A62B8A9476F2Db92/info.json
  blockchains/smartchain/assets/0x0921d788E7f7498f80adb0A0A62B8A9476F2Db92/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7591 Adding PitJupiter informations
  blockchains/smartchain/assets/0x359f35085202C8527a0c767557339635A335Eb76/info.json
  blockchains/smartchain/assets/0x359f35085202C8527a0c767557339635A335Eb76/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7590 adding SANSHU logo and info
  blockchains/ethereum/assets/0xc73C167E7a4Ba109e4052f70D5466D0C312A344D/info.json
  blockchains/ethereum/assets/0xc73C167E7a4Ba109e4052f70D5466D0C312A344D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7596 Add Froge.Finance (ERC20)
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/info.json
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7600 julb logo update
  blockchains/smartchain/assets/0x32dFFc3fE8E3EF3571bF8a72c0d0015C5373f41D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7601 Add GNT logo and info
  blockchains/smartchain/assets/0xF750A26EB0aCf95556e8529E72eD530f3b60f348/info.json
  blockchains/smartchain/assets/0xF750A26EB0aCf95556e8529E72eD530f3b60f348/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7567 Update logo.png and website details
  blockchains/smartchain/assets/0xAB844d316B5a5093b7e7EdDE11cc08BeCCA36d1C/info.json
  blockchains/smartchain/assets/0xAB844d316B5a5093b7e7EdDE11cc08BeCCA36d1C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7623 add_BEP20_TRX+WIN
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x85EAC5Ac2F758618dFa09bDbe0cf174e7d574D5B/info.json
  blockchains/smartchain/assets/0x85EAC5Ac2F758618dFa09bDbe0cf174e7d574D5B/logo.png
  blockchains/smartchain/assets/0xaeF0d72a118ce24feE3cD1d43d383897D05B4e99/info.json
  blockchains/smartchain/assets/0xaeF0d72a118ce24feE3cD1d43d383897D05B4e99/logo.png
Labels: Payment Status: Requested

#7615 Add ZETBNB logo
  blockchains/smartchain/assets/0xB89ADD4A17eaDB084a065f9CAcE752a268dab8b3/info.json
  blockchains/smartchain/assets/0xB89ADD4A17eaDB084a065f9CAcE752a268dab8b3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7613 add blackberry token logo
  blockchains/smartchain/assets/0x86bBc9838C3370e0fD570b4ee8087f5aCa299977/info.json
  blockchains/smartchain/assets/0x86bBc9838C3370e0fD570b4ee8087f5aCa299977/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7610 Revert "Add Froge.Finance (ERC20)"
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/info.json
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7606 Add info for HotDoge token
  blockchains/smartchain/assets/0x1991501f1398663F69dD7391C055bb0DF6514F76/info.json
  blockchains/smartchain/assets/0x1991501f1398663F69dD7391C055bb0DF6514F76/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7589 Change of token name
  blockchains/smartchain/assets/0x55183148d5C3360cbB0e1EDb38b30e091aEE4D65/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#7538 Update cbc info.json
  blockchains/ethereum/assets/0x26DB5439F651CAF491A87d48799dA81F191bDB6b/info.json
  blockchains/ethereum/assets/0x26DB5439F651CAF491A87d48799dA81F191bDB6b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7628 Add Froge Finance (ERC20)
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/info.json
  blockchains/ethereum/assets/0x29502fE4d233EF0b45C3647101Fa1252cE0634BD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7618 Info
  blockchains/smartchain/assets/0xBE2a26889CE30a1515055a192797083B1FDe8844/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#7633 Add Equalizer (EQZ) ERC20 Token
  blockchains/ethereum/assets/0x1Da87b114f35E1DC91F72bF57fc07A768Ad40Bb0/info.json
  blockchains/ethereum/assets/0x1Da87b114f35E1DC91F72bF57fc07A768Ad40Bb0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7635 Add FLUNAR logo and info
  blockchains/smartchain/assets/0xDCD289ECF644bEC54393ba6Ce8dB35e9B5Ff75e7/info.json
  blockchains/smartchain/assets/0xDCD289ECF644bEC54393ba6Ce8dB35e9B5Ff75e7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7638 Info & Logo
  blockchains/smartchain/assets/0xD50787A5f21bcC10C1a738E7DE33001786c5fc24/info.json
  blockchains/smartchain/assets/0xD50787A5f21bcC10C1a738E7DE33001786c5fc24/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7639 Update logo MPF and info
  blockchains/smartchain/assets/0xEc7d0327fC48ef7EfA975A4e3327F28576C3ef96/info.json
  blockchains/smartchain/assets/0xEc7d0327fC48ef7EfA975A4e3327F28576C3ef96/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7640 add COV info and logo
  blockchains/ethereum/assets/0xADA86b1b313D1D5267E3FC0bB303f0A2b66D0Ea7/info.json
  blockchains/ethereum/assets/0xADA86b1b313D1D5267E3FC0bB303f0A2b66D0Ea7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7508 [Internal] Replace custom explorers
  blockchains/ethereum/assets/0x0F5D2fB29fb7d3CFeE444a200298f468908cC942/info.json
  blockchains/ethereum/assets/0x9b53E429B0baDd98ef7F01F03702986c516a5715/info.json
  blockchains/ethereum/assets/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2/info.json
  blockchains/ethereum/assets/0xB63B606Ac810a52cCa15e44bB630fd42D8d1d83d/info.json
  blockchains/ethereum/assets/0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC/info.json
  blockchains/ethereum/assets/0xD9Ec3ff1f8be459Bb9369b4E79e9Ebcf7141C093/info.json
  blockchains/ethereum/assets/0xE41d2489571d322189246DaFA5ebDe1F4699F498/info.json
  blockchains/ethereum/assets/0xa74476443119A942dE498590Fe1f2454d7D4aC0d/info.json
  blockchains/ethereum/assets/0xbe038A2FDfec62Cf1beD852f141A43005035edcC/info.json
  blockchains/ethereum/assets/0xdd974D5C2e2928deA5F71b9825b8b646686BD200/info.json
Labels: Payment Status: Paid

#7655 [Internal] Change all explorers to standard explorer
  script/generic/asset-infos.ts
Labels: Payment Status: Requested

#7520 Add Wenlambo (BEP20)
  blockchains/smartchain/assets/0xd8A31016cD7da048ca21FFE04256C6d08C3A2251/info.json
  blockchains/smartchain/assets/0xd8A31016cD7da048ca21FFE04256C6d08C3A2251/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5970 Add FUSII BEP20 fusible.io
  blockchains/smartchain/assets/0x3A50d6daacc82f17A2434184fE904fC45542A734/info.json
  blockchains/smartchain/assets/0x3A50d6daacc82f17A2434184fE904fC45542A734/logo.png
Labels: Payment Status: Paid, Status: On Hold

#7652 Added logo and info
  blockchains/smartchain/assets/0x71e1611075800E89A460463FCDfbA3d0FEA8c01d/info.json
  blockchains/smartchain/assets/0x71e1611075800E89A460463FCDfbA3d0FEA8c01d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7673 Fix decimals of Blackberry token, #7613
  blockchains/smartchain/assets/0x86bBc9838C3370e0fD570b4ee8087f5aCa299977/info.json
Labels: Payment Status: Requested

#7583 Add vEth2 info and logo
  blockchains/ethereum/assets/0x898BAD2774EB97cF6b94605677F43b41871410B1/info.json
  blockchains/ethereum/assets/0x898BAD2774EB97cF6b94605677F43b41871410B1/logo.png
Labels: Payment Status: Paid
