Repository trustwallet/assets, pull requests merged in 2021-07, with the labels that each got.

#11019 we reached 2500 users
  blockchains/smartchain/assets/0x118F073796821DA3E9901061B05c0b36377B877e/info.json
  blockchains/smartchain/assets/0x451329F2FCb88C398A4cDD4A8a98780B4D62873C/info.json
  blockchains/smartchain/assets/0x451329F2FCb88C398A4cDD4A8a98780B4D62873C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#10928 Add files via upload
  blockchains/smartchain/assets/0xF1A71bcCe29b598d812a30BaedFf860a7Dce0aff/info.json
  blockchains/smartchain/assets/0xF1A71bcCe29b598d812a30BaedFf860a7Dce0aff/logo.png
Labels: Payment Status: Paid

#11028 add kishubaby logo and info
  blockchains/smartchain/assets/0x97Ad911101d4285a13A3240Ee35618edC511A435/info.json
  blockchains/smartchain/assets/0x97Ad911101d4285a13A3240Ee35618edC511A435/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#10986 Fix decimal error
  blockchains/smartchain/assets/0xEf11aB854b475Bd0c5Db37f6bFFAB443219d656d/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#11025 Add info & Logo
  blockchains/smartchain/assets/0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8/info.json
  blockchains/smartchain/assets/0x6bbf411a9a50ef4427d64d1Ea74ad294c2BBb0c8/logo.png
Labels: Payment Status: Paid

#11037 Add AppleB (BEP20)
  blockchains/smartchain/assets/0x4Dc7c9148A1F495872A5b31CF459ac7989cDCE79/info.json
  blockchains/smartchain/assets/0x4Dc7c9148A1F495872A5b31CF459ac7989cDCE79/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11044 Add SIMBCOIN SWAP (SMB SWAP) (ERC20)
  blockchains/ethereum/assets/0x53Bd789F2cDb846b227d8ffc7B46eD4263231FDf/info.json
  blockchains/ethereum/assets/0x53Bd789F2cDb846b227d8ffc7B46eD4263231FDf/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11045 Add EpiK Protocol (EPK) (ERC20)
  blockchains/ethereum/assets/0xDaF88906aC1DE12bA2b1D2f7bfC94E9638Ac40c4/info.json
  blockchains/ethereum/assets/0xDaF88906aC1DE12bA2b1D2f7bfC94E9638Ac40c4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11039 Add Vain (BEP20)
  blockchains/smartchain/assets/0x6067652Fe687Aa221B6F86F398aF4d0fe9bF45E3/info.json
  blockchains/smartchain/assets/0x6067652Fe687Aa221B6F86F398aF4d0fe9bF45E3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#10693 Add BuyBack Token Logo
  blockchains/smartchain/assets/0xB3670F91E86a96EeDA0c75b1573035A6277226fb/info.json
  blockchains/smartchain/assets/0xB3670F91E86a96EeDA0c75b1573035A6277226fb/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#11058 Add Tether/EURO (BEP20)
  blockchains/smartchain/assets/0xF7F80f8437ACb6338329677280172368676b3401/info.json
  blockchains/smartchain/assets/0xF7F80f8437ACb6338329677280172368676b3401/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11060 Add USD Coin (TRC20)
  blockchains/tron/assets/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/info.json
  blockchains/tron/assets/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#10967 Modified Save Planet Earth (SPE) details and logo
  blockchains/smartchain/assets/0xdBaAa36B347d56b77Ce0e36f050fCeEBbF9fbc38/info.json
  blockchains/smartchain/assets/0xdBaAa36B347d56b77Ce0e36f050fCeEBbF9fbc38/logo.png
Labels: Payment Status: Paid

#11061 WalletSwap Logo Info Added.
  blockchains/smartchain/assets/0xC72cC401122dBDC812EC88a2150AAD5a39467401/info.json
  blockchains/smartchain/assets/0xC72cC401122dBDC812EC88a2150AAD5a39467401/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11006 Add Micro-Gaming-Protocol (MGP) logo and info
  blockchains/smartchain/assets/0x57bEa4F720F755150f6b773c13bC78c09ac85740/info.json
  blockchains/smartchain/assets/0x57bEa4F720F755150f6b773c13bC78c09ac85740/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11065 gmpx logo
  blockchains/smartchain/assets/0x221FD3FAFfd3cCab2369ffD6A24c7845674787C6/info.json
  blockchains/smartchain/assets/0x221FD3FAFfd3cCab2369ffD6A24c7845674787C6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11063 Add SafePizza lnfo and Logo
  blockchains/smartchain/assets/0x72Eb1aFddB5652e0f5c7B9A6cc1C3241348b16c6/info.json
  blockchains/smartchain/assets/0x72Eb1aFddB5652e0f5c7B9A6cc1C3241348b16c6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11068 Add USD Coin (TRC20)
  blockchains/tron/assets/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/info.json
  blockchains/tron/assets/TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8/logo.png
Labels: Payment Status: Requested

#11082 Submit info
  blockchains/smartchain/assets/0xA6Fd7B5C9eee30309B00B65436a284e2053251e5/info.json
  blockchains/smartchain/assets/0xA6Fd7B5C9eee30309B00B65436a284e2053251e5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11083 Addin CATGE V2
  blockchains/smartchain/assets/0x3e07a8a8f260edeeca24139B6767A073918E8674/info.json
  blockchains/smartchain/assets/0x3e07a8a8f260edeeca24139B6767A073918E8674/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11081 Added Olympus token info and logo
  blockchains/smartchain/assets/0x18b426813731C144108c6D7FAf5EdE71a258fD9A/info.json
  blockchains/smartchain/assets/0x18b426813731C144108c6D7FAf5EdE71a258fD9A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11079 Add Token Logo and info
  blockchains/smartchain/assets/0xDE619A9E0eEeAA9F8CD39522Ed788234837F3B26/info.json
  blockchains/smartchain/assets/0xDE619A9E0eEeAA9F8CD39522Ed788234837F3B26/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11085 Add RAKUC logo and info
  blockchains/smartchain/assets/0xc094b9604225062c7edCA29DB444B9b035f78C8B/info.json
  blockchains/smartchain/assets/0xc094b9604225062c7edCA29DB444B9b035f78C8B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11086 Update info.json
  blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/info.json
Labels: Payment Status: Requested

#11088 Add files via upload
  blockchains/smartchain/assets/0xa3F4a5E5411dB7d6630aa531D7645c72cFDDa41a/info.json
  blockchains/smartchain/assets/0xa3F4a5E5411dB7d6630aa531D7645c72cFDDa41a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11090 Add BAPE logo and info
  blockchains/smartchain/assets/0xCB35e52bEbFE06909C216bE822fa982EfDD60F95/info.json
  blockchains/smartchain/assets/0xCB35e52bEbFE06909C216bE822fa982EfDD60F95/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11093 Add bernard (BEP20)
  blockchains/smartchain/assets/0x27d0408A868Cf4E89B37D20b5E32888dcED95BCB/info.json
  blockchains/smartchain/assets/0x27d0408A868Cf4E89B37D20b5E32888dcED95BCB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11096 Update info.json
  blockchains/smartchain/assets/0x55d398326f99059fF775485246999027B3197955/info.json
Labels: Payment Status: Requested

#11097 Update info.json
  blockchains/tron/assets/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/info.json
Labels: Payment Status: Requested

#11101 Update info.json
  blockchains/solana/assets/BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4/info.json
Labels: Payment Status: Requested

#11103 Update info.json
  blockchains/smartchain/assets/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d/info.json
Labels: Payment Status: Requested

#11104 Update info.json
  blockchains/solana/assets/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/info.json
Labels: Payment Status: Requested

#11105 Update info.json
  blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/info.json
Labels: Payment Status: Requested

#11109 Update info.json
  blockchains/smartchain/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/info.json
Labels: Payment Status: Requested

#11102 Add URG logo and info
  blockchains/smartchain/assets/0xfAF9Cc03C9855777FB56D02bC2Bcb9d57e0755DE/info.json
  blockchains/smartchain/assets/0xfAF9Cc03C9855777FB56D02bC2Bcb9d57e0755DE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11112 Add files via upload
  blockchains/smartchain/assets/0x62613F4b4F7600C7C0F16c97Aefc29c8A2CA524F/info.json
  blockchains/smartchain/assets/0x62613F4b4F7600C7C0F16c97Aefc29c8A2CA524F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11114 Update info.json
  blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/info.json
Labels: Payment Status: Requested

#11115 Update info.json
  blockchains/smartchain/assets/0xBf5140A22578168FD562DCcF235E5D43A02ce9B1/info.json
Labels: Payment Status: Requested

#11117 Update info.json
  blockchains/ethereum/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599/info.json
Labels: Payment Status: Requested

#11118 Update info.json
  blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/info.json
Labels: Payment Status: Requested

#11119 Update info.json
  blockchains/smartchain/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/info.json
Labels: Payment Status: Requested

#11123 Update info.json
  blockchains/ethereum/assets/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE/info.json
Labels: Payment Status: Requested

#11116 Velorex Logo and info.json
  blockchains/smartchain/assets/0xc029A12e4A002c6858878FD9D3cc74E227cc2DDa/info.json
  blockchains/smartchain/assets/0xc029A12e4A002c6858878FD9D3cc74E227cc2DDa/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#11098 Added Epstein Token Description and Logo
  blockchains/ethereum/assets/0x051cF5178f60e9DEf5d5a39b2a988a9f914107cB/info.json
  blockchains/ethereum/assets/0x051cF5178f60e9DEf5d5a39b2a988a9f914107cB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11126 Add Lunar (BEP20)
  blockchains/smartchain/assets/0xf4206e5F264420630520e0D23c14D8Dd5645e6C3/info.json
  blockchains/smartchain/assets/0xf4206e5F264420630520e0D23c14D8Dd5645e6C3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11129 Add Proton (BEP20)
  blockchains/smartchain/assets/0x5de3939b2F811A61d830E6F52d13B066881412ab/info.json
  blockchains/smartchain/assets/0x5de3939b2F811A61d830E6F52d13B066881412ab/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11131 Add Meong Token Logo in Trustwallet
  blockchains/smartchain/assets/0x464ACc420607d818f271875552868dDF8095CAfE/info.json
  blockchains/smartchain/assets/0x464ACc420607d818f271875552868dDF8095CAfE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11125 Update info.json
  blockchains/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/info.json
Labels: Payment Status: Requested

#11140 Update info.json
  blockchains/ethereum/assets/0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b/info.json
Labels: Payment Status: Requested

#11120 Update info.json
  blockchains/smartchain/assets/0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E/info.json
Labels: Payment Status: Requested

#11141 Update info.json
  blockchains/ethereum/assets/0x50D1c9771902476076eCFc8B2A83Ad6b9355a4c9/info.json
Labels: Payment Status: Requested

#11142 Add links to MKR token
  blockchains/ethereum/assets/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2/info.json
Labels: Payment Status: Requested

#11143 Add links to MKR token
  blockchains/smartchain/assets/0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350/info.json
Labels: Payment Status: Requested

#11144 Add links to BTCB token
  blockchains/smartchain/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/info.json
Labels: Payment Status: Requested

#11145 Add links to BTCB token
  blockchains/binance/assets/BTCB-1DE/info.json
Labels: Payment Status: Requested

#11147 Add links to AMP token
  blockchains/ethereum/assets/0xfF20817765cB7f73d4bde2e66e067E58D11095C2/info.json
Labels: Payment Status: Requested

#11149 Add links to LEO token
  blockchains/ethereum/assets/0x2AF5D2aD76741191D15Dfe7bF6aC92d4Bd912Ca3/info.json
Labels: Payment Status: Requested

#11150 Add links to COMP token
  blockchains/ethereum/assets/0xc00e94Cb662C3520282E6f5717214004A7f26888/info.json
Labels: Payment Status: Requested

#11151 Add links to HT token
  blockchains/ethereum/assets/0x6f259637dcD74C767781E37Bc6133cd6A68aa161/info.json
Labels: Payment Status: Requested

#11154 Add links to TUSD token
  blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json
Labels: Payment Status: Requested

#11155 Add links to TUSDB token
  blockchains/binance/assets/TUSDB-888/info.json
Labels: Payment Status: Requested

#11153 Add links to GRT token
  blockchains/ethereum/assets/0xc944E90C64B2c07662A292be6244BDf05Cda44a7/info.json
Labels: Payment Status: Requested

#11156 Add links to CELtoken
  blockchains/ethereum/assets/0xaaAEBE6Fe48E54f431b0C390CfaF0b017d09D42d/info.json
Labels: Payment Status: Requested

#11157 Add links to CHZ token
  blockchains/ethereum/assets/0x3506424F91fD33084466F402d5D97f05F8e3b4AF/info.json
Labels: Payment Status: Requested

#11158 Add links to CHZ token
  blockchains/binance/assets/CHZ-ECD/info.json
Labels: Payment Status: Requested

#11159 Add links to TEL token
  blockchains/ethereum/assets/0x467Bccd9d29f223BcE8043b84E8C8B282827790F/info.json
Labels: Payment Status: Requested

#11161 Add links to YFI token
  blockchains/smartchain/assets/0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e/info.json
Labels: Payment Status: Requested

#11146 Add links to CAKE token
  blockchains/smartchain/assets/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82/info.json
Labels: Payment Status: Requested

#11160 Add links to YFI token
  blockchains/ethereum/assets/0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e/info.json
Labels: Payment Status: Requested

#11162 Add links to HOT token
  blockchains/ethereum/assets/0x6c6EE5e31d828De241282B9606C8e98Ea48526E2/info.json
Labels: Payment Status: Requested

#11163 Add links to SUSHI token
  blockchains/ethereum/assets/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2/info.json
Labels: Payment Status: Requested

#11135 Requesting to add GrandpaDoge logo and info
  blockchains/smartchain/assets/0x326E1d2D9e7F8F3a4Df13766Aa3B3AeF33546546/info.json
  blockchains/smartchain/assets/0x326E1d2D9e7F8F3a4Df13766Aa3B3AeF33546546/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11164 Add links to SUSHI token
  blockchains/smartchain/assets/0x947950BcC74888a40Ffa2593C5798F11Fc9124C4/info.json
Labels: Payment Status: Requested

#11165 Add links to ENJ token
  blockchains/ethereum/assets/0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c/info.json
Labels: Payment Status: Requested

#11166 Add links to MANA token
  blockchains/ethereum/assets/0x0F5D2fB29fb7d3CFeE444a200298f468908cC942/info.json
Labels: Payment Status: Requested

#11167 Add links to QNT token
  blockchains/ethereum/assets/0x4a220E6096B25EADb88358cb44068A3248254675/info.json
Labels: Payment Status: Requested

#11170 Add links to BAT token
  blockchains/smartchain/assets/0x101d82428437127bF1608F699CD651e6Abf9766E/info.json
Labels: Payment Status: Requested

#11169 Add links to BAT token
  blockchains/ethereum/assets/0x0D8775F648430679A709E98d2b0Cb6250d2887EF/info.json
Labels: Payment Status: Requested

#11172 Add links to PAX token
  blockchains/ethereum/assets/0x8E870D67F660D95d5be530380D0eC0bd388289E1/info.json
Labels: Payment Status: Requested

#11173 Add links to PAX token
  blockchains/smartchain/assets/0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094/info.json
Labels: Payment Status: Requested

#11174 Add links to NEXO token
  blockchains/ethereum/assets/0xB62132e35a6c13ee1EE0f84dC5d40bad8d815206/info.json
Labels: Payment Status: Requested

#11176 Add links to SNX token
  blockchains/ethereum/assets/0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F/info.json
Labels: Payment Status: Requested

#11175 Add links to NEXO token
  blockchains/binance/assets/NEXO-A84/info.json
Labels: Payment Status: Requested

#11177 Add links to SNX token
  blockchains/smartchain/assets/0x9Ac983826058b8a9C7Aa1C9171441191232E8404/info.json
Labels: Payment Status: Requested

#11179 Add links to REV token
  blockchains/ethereum/assets/0x2ef52Ed7De8c5ce03a4eF0efbe9B7450F2D7Edc9/info.json
Labels: Payment Status: Requested

#11178 Add links to BNT token
  blockchains/ethereum/assets/0x1F573D6Fb3F13d689FF844B4cE37794d79a7FF1C/info.json
Labels: Payment Status: Requested

#11180 Add links to CRV token
  blockchains/ethereum/assets/0xD533a949740bb3306d119CC777fa900bA034cd52/info.json
Labels: Payment Status: Requested

#11181 Add links to OKB token
  blockchains/ethereum/assets/0x75231F58b43240C9718Dd58B4967c5114342a86c/info.json
Labels: Payment Status: Requested

#11183 Add links to ZRX token
  blockchains/ethereum/assets/0xE41d2489571d322189246DaFA5ebDe1F4699F498/info.json
Labels: Payment Status: Requested

#11182 Add links to CHSB token
  blockchains/ethereum/assets/0xba9d4199faB4f26eFE3551D490E3821486f135Ba/info.json
Labels: Payment Status: Requested

#11185 Add Happiness (TRC20)
  blockchains/tron/assets/TUH4wj8tox7sVxvkTqHLogn6mRVKfrK71M/info.json
  blockchains/tron/assets/TUH4wj8tox7sVxvkTqHLogn6mRVKfrK71M/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11184 Add Floki Shiba Inu Token in Trustwallet
  blockchains/smartchain/assets/0x2A42B6896E4B756621f08A1996162D8EA5A9c580/info.json
  blockchains/smartchain/assets/0x2A42B6896E4B756621f08A1996162D8EA5A9c580/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11186 Add links to OMG token
  blockchains/ethereum/assets/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07/info.json
Labels: Payment Status: Requested

#11187 Add links to KCS token
  blockchains/ethereum/assets/0xf34960d9d60be18cC1D5Afc1A6F012A723a28811/info.json
Labels: Payment Status: Requested

#11188 Add links to HUSD token
  blockchains/ethereum/assets/0xdF574c24545E5FfEcb9a659c229253D4111d87e1/info.json
Labels: Payment Status: Requested

#11189 Add links to UMA token
  blockchains/ethereum/assets/0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828/info.json
Labels: Payment Status: Requested

#11191 Add links to ANKR token
  blockchains/ethereum/assets/0x8290333ceF9e6D528dD5618Fb97a76f268f3EDD4/info.json
Labels: Payment Status: Requested

#11190 Add links to VGX token
  blockchains/ethereum/assets/0x5Af2Be193a6ABCa9c8817001F45744777Db30756/info.json
Labels: Payment Status: Requested

#11192 Add links to ANKR token
  blockchains/smartchain/assets/0xf307910A4c7bbc79691fD374889b36d8531B08e3/info.json
Labels: Payment Status: Requested

#11193 Add links to ANKR token
  blockchains/binance/assets/ANKR-E97/info.json
Labels: Payment Status: Requested

#11195 Add links to BAKE token
  blockchains/smartchain/assets/0xE02dF9e3e622DeBdD69fb838bB799E3F168902c5/info.json
Labels: Payment Status: Requested

#11197 Add links to 1INCH token
  blockchains/ethereum/assets/0x111111111117dC0aa78b770fA6A738034120C302/info.json
Labels: Payment Status: Requested

#11198 Add links to 1INCH token
  blockchains/smartchain/assets/0x111111111117dC0aa78b770fA6A738034120C302/info.json
Labels: Payment Status: Requested

#11199 Add Token Tether (BEP20)
  blockchains/smartchain/assets/0x63b7e5aE00cc6053358fb9b97B361372FbA10a5e/info.json
  blockchains/smartchain/assets/0x63b7e5aE00cc6053358fb9b97B361372FbA10a5e/logo.png
Labels: Payment Status: Requested

#11202 Add links to LPT token
  blockchains/ethereum/assets/0x58b6A8A3302369DAEc383334672404Ee733aB239/info.json
Labels: Payment Status: Requested

#11203 Add links to renBTC token
  blockchains/ethereum/assets/0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D/info.json
Labels: Payment Status: Requested

#11205 Add links to REN token
  blockchains/ethereum/assets/0x408e41876cCCDC0F92210600ef50372656052a38/info.json
Labels: Payment Status: Requested

#11204 DLF TOKEN
  blockchains/smartchain/assets/0x942Ed7dfA2a564984747420D47C4f49c2b3140F9/info.json
  blockchains/smartchain/assets/0x942Ed7dfA2a564984747420D47C4f49c2b3140F9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11206 Add links to WRX token
  blockchains/binance/assets/WRX-ED1/info.json
Labels: Payment Status: Requested

#11207 Add links to KNCL token
  blockchains/ethereum/assets/0xdd974D5C2e2928deA5F71b9825b8b646686BD200/info.json
Labels: Payment Status: Requested

#11209 Add links to RSR token
  blockchains/ethereum/assets/0x8762db106B2c2A0bccB3A80d1Ed41273552616E8/info.json
Labels: Payment Status: Requested

#11211 Add links to LRC token
  blockchains/ethereum/assets/0xBBbbCA6A901c926F240b89EacB641d8Aec7AEafD/info.json
Labels: Payment Status: Requested

#11212 Add links to WIN token
  blockchains/tron/assets/TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7/info.json
Labels: Payment Status: Requested

#11213 Add links to KAVA token
  blockchains/binance/assets/KAVA-10C/info.json
Labels: Payment Status: Requested

#11214 Add links to GNO token
  blockchains/ethereum/assets/0x6810e776880C02933D47DB1b9fc05908e5386b96/info.json
Labels: Payment Status: Requested

#11216 Add links to GT token
  blockchains/ethereum/assets/0xE66747a101bFF2dBA3697199DCcE5b743b454759/info.json
Labels: Payment Status: Requested

#11217 Add links to GUSD token
  blockchains/ethereum/assets/0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd/info.json
Labels: Payment Status: Requested

#11218 Please add STARDUST logo and info
  blockchains/smartchain/assets/0xf647d6B49ea7bb880EcbCFf9913dF0d634875D33/info.json
  blockchains/smartchain/assets/0xf647d6B49ea7bb880EcbCFf9913dF0d634875D33/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11219 Add links to SNT token
  blockchains/ethereum/assets/0x744d70FDBE2Ba4CF95131626614a1763DF805B9E/info.json
Labels: Payment Status: Requested

#11220 Add links to WOO token
  blockchains/ethereum/assets/0x4691937a7508860F876c9c0a2a617E7d9E945D4B/info.json
Labels: Payment Status: Requested

#11215 Add links to OCEAN token
  blockchains/ethereum/assets/0x967da4048cD07aB37855c090aAF366e4ce1b9F48/info.json
Labels: Payment Status: Requested

#11230 Add Throne (THN) (ERC20)
  blockchains/ethereum/assets/0x2E95Cea14dd384429EB3c4331B776c4CFBB6FCD9/info.json
  blockchains/ethereum/assets/0x2E95Cea14dd384429EB3c4331B776c4CFBB6FCD9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11235 Adding Million Token https://milliontoken.org/
  blockchains/ethereum/assets/0x6B4c7A5e3f0B99FCD83e9c089BDDD6c7FCe5c611/info.json
  blockchains/ethereum/assets/0x6B4c7A5e3f0B99FCD83e9c089BDDD6c7FCe5c611/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#10630 Changing Logo for old coin
  blockchains/smartchain/assets/0x55183148d5C3360cbB0e1EDb38b30e091aEE4D65/info.json
  blockchains/smartchain/assets/0x55183148d5C3360cbB0e1EDb38b30e091aEE4D65/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11246 Update info.json
  blockchains/smartchain/assets/0x63b7e5aE00cc6053358fb9b97B361372FbA10a5e/info.json
Labels: Payment Status: Requested

#11245 Update info.json
  blockchains/ethereum/assets/0x2E95Cea14dd384429EB3c4331B776c4CFBB6FCD9/info.json
Labels: Payment Status: Requested

#11251 delete Token Tether (USDT)
  blockchains/smartchain/assets/0x63b7e5aE00cc6053358fb9b97B361372FbA10a5e/info.json
  blockchains/smartchain/assets/0x63b7e5aE00cc6053358fb9b97B361372FbA10a5e/logo.png
Labels: Payment Status: Requested

#11254 Update Gold Tether logo (ERC20)
  blockchains/ethereum/assets/0x4922a015c4407F87432B179bb209e125432E4a2A/info.json
  blockchains/ethereum/assets/0x4922a015c4407F87432B179bb209e125432E4a2A/logo.png
Labels: Payment Status: Requested

#11256 Update LUNAR description
  blockchains/smartchain/assets/0xf4206e5F264420630520e0D23c14D8Dd5645e6C3/info.json
Labels: Payment Status: Requested

#11258 Update EPK description
  blockchains/ethereum/assets/0xDaF88906aC1DE12bA2b1D2f7bfC94E9638Ac40c4/info.json
Labels: Payment Status: Requested

#11261 Update SMB SWAP description
  blockchains/ethereum/assets/0x53Bd789F2cDb846b227d8ffc7B46eD4263231FDf/info.json
Labels: Payment Status: Requested

#11262 Update AIDI description
  blockchains/ethereum/assets/0xdA1E53E088023Fe4D1DC5a418581748f52CBd1b8/info.json
Labels: Payment Status: Requested

#11263 Update MARS description
  blockchains/smartchain/assets/0xF1A71bcCe29b598d812a30BaedFf860a7Dce0aff/info.json
Labels: Payment Status: Requested

#11266 Update RiseofNebula(RON) logo
  blockchains/smartchain/assets/0x40300e0045239Fe76Cd07251313f923B29df1e55/info.json
  blockchains/smartchain/assets/0x40300e0045239Fe76Cd07251313f923B29df1e55/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11264 Add LEGION Token and Logo
  blockchains/smartchain/assets/0x7CF23DfF6DEDBf80211FfaDa15Ae01463C47D034/info.json
  blockchains/smartchain/assets/0x7CF23DfF6DEDBf80211FfaDa15Ae01463C47D034/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11241 Add TBCC (BEP20)
  blockchains/smartchain/assets/0x00000ee41472D518B364FA09866532A792F4009B/info.json
  blockchains/smartchain/assets/0x00000ee41472D518B364FA09866532A792F4009B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11275 Update PAPADOGE description
  blockchains/smartchain/assets/0xbCeeE918077F63fB1B9e10403F59cA40C7061341/info.json
Labels: Payment Status: Requested

#11276 Update BabyWolf description
  blockchains/smartchain/assets/0x5B5a3A45002736413613B8A4C46cC0d9D1D6F4Ae/info.json
Labels: Payment Status: Requested

#11278 Update SAITAMA description
  blockchains/ethereum/assets/0x8B3192f5eEBD8579568A2Ed41E6FEB402f93f73F/info.json
Labels: Payment Status: Requested

#11279 Update CAPS description
  blockchains/ethereum/assets/0x03Be5C903c727Ee2C8C4e9bc0AcC860Cca4715e2/info.json
Labels: Payment Status: Requested

#11280 Update KELPIE Description
  blockchains/ethereum/assets/0x672D7b3333d0F069a28b73A268bC6eAeC65F2E1a/info.json
Labels: Payment Status: Requested

#11281 Update EPAY description
  blockchains/ethereum/assets/0x2b5cA2F9510cf1e3595Ff219f24D75D4244585EA/info.json
Labels: Payment Status: Requested

#11282 Update MRS description
  blockchains/ethereum/assets/0x9Af5A20AaC8D83230ba68542Ba29d132d50cbe08/info.json
Labels: Payment Status: Requested

#11283 Update CUMINU description
  blockchains/ethereum/assets/0xd6327ce1fb9D6020E8C2c0E124A1eC23DCAb7536/info.json
Labels: Payment Status: Requested

#11285 Update BIOS description
  blockchains/ethereum/assets/0xAACa86B876ca011844b5798ECA7a67591A9743C8/info.json
Labels: Payment Status: Requested

#11286 Update BUDA description
  blockchains/smartchain/assets/0x4b63f8C52E3286CA871Cd66b7C84e26556b2DE8e/info.json
Labels: Payment Status: Requested

#11287 Update MYOBU description
  blockchains/ethereum/assets/0x75D12E4F91Df721faFCae4c6cD1d5280381370AC/info.json
Labels: Payment Status: Requested

#11288 Update DGO description
  blockchains/smartchain/assets/0xfAEce5aCc269774Eb1D544Ee8D45671A55516296/info.json
Labels: Payment Status: Requested

#11289 Update GEMS description
  blockchains/smartchain/assets/0x48A64f116Ce221fD7c1119775ba7892701F9911d/info.json
Labels: Payment Status: Requested

#11290 Update EVA Description
  blockchains/ethereum/assets/0xd6cAF5Bd23CF057f5FcCCE295Dcc50C01C198707/info.json
Labels: Payment Status: Requested
