Repository trustwallet/assets, pull requests merged in 2021-11, with the labels that each got.

#14755 TOON:BSC logo and asset details
  blockchains/ethereum/assets/0xaeE433ADeBe0FBB88dAa47eF0C1A513CaA52EF02/info.json
  blockchains/ethereum/assets/0xaeE433ADeBe0FBB88dAa47eF0C1A513CaA52EF02/logo.png
  blockchains/smartchain/assets/0xaeE433ADeBe0FBB88dAa47eF0C1A513CaA52EF02/info.json
  blockchains/smartchain/assets/0xaeE433ADeBe0FBB88dAa47eF0C1A513CaA52EF02/logo.png
Labels: Status: On Hold, Payment Status: Paid

#14876 Add BaitCoin (BEP20)
  blockchains/smartchain/assets/0x10f6F43d8321A3C86c2986BA4753ceBEba477BAa/info.json
  blockchains/smartchain/assets/0x10f6F43d8321A3C86c2986BA4753ceBEba477BAa/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14849 Added Afrostar
  blockchains/smartchain/assets/0x2F4e9c97aAFFD67D98A640062d90e355B4a1C539/info.json
  blockchains/smartchain/assets/0x2F4e9c97aAFFD67D98A640062d90e355B4a1C539/logo.png
Labels: Payment Status: Paid

#14928 TitsV2 token information
  blockchains/smartchain/assets/0xA753D241fFcE10A3570eDa72f6561C04b1f9Ae77/info.json
  blockchains/smartchain/assets/0xA753D241fFcE10A3570eDa72f6561C04b1f9Ae77/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14931 Shiba Watch info and logo
  blockchains/smartchain/assets/0x52941a733F7bAb6E52d5C8f2045c9D9D9eA246Ff/info.json
  blockchains/smartchain/assets/0x52941a733F7bAb6E52d5C8f2045c9D9D9eA246Ff/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14867 Add Loveswap DEX (BEP20)
  blockchains/smartchain/assets/0x8baf35803b452836a05A3e01ac36F3DDbF98bbE8/info.json
  blockchains/smartchain/assets/0x8baf35803b452836a05A3e01ac36F3DDbF98bbE8/logo.png
Labels: Payment Status: Paid

#14935 Add Doge Floki Coin (BEP20)
  blockchains/smartchain/assets/0xF9d6DDF44016953dBf7aB135A0F64d7A41870EDE/info.json
  blockchains/smartchain/assets/0xF9d6DDF44016953dBf7aB135A0F64d7A41870EDE/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14918 Add GloryDoge logo and info
  blockchains/smartchain/assets/0xCC5667333F5e997aC9F0C26d41b7ddA65b2b675a/info.json
  blockchains/smartchain/assets/0xCC5667333F5e997aC9F0C26d41b7ddA65b2b675a/logo.png
Labels: Payment Status: Paid

#14947 Add BOOST info and logo
  blockchains/smartchain/assets/0x773b532126b9F307665942b0fa4cDa0540CeDb71/info.json
  blockchains/smartchain/assets/0x773b532126b9F307665942b0fa4cDa0540CeDb71/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14939 Add Lunapad (BEP20)
  blockchains/smartchain/assets/0xD1FdF57241df3C36dad469060caC9f1ea2eE7585/info.json
  blockchains/smartchain/assets/0xD1FdF57241df3C36dad469060caC9f1ea2eE7585/logo.png
Labels: Payment Status: Paid

#14959 Add Shibosu (BEP20)
  blockchains/smartchain/assets/0x5dfb6437489235fe08a8F706Bb261938f4E2D849/info.json
  blockchains/smartchain/assets/0x5dfb6437489235fe08a8F706Bb261938f4E2D849/logo.png
Labels: Payment Status: Paid

#14880 Add Space SIP (BEP20)
  blockchains/smartchain/assets/0x9e5965d28E8D44CAE8F9b809396E0931F9Df71CA/info.json
  blockchains/smartchain/assets/0x9e5965d28E8D44CAE8F9b809396E0931F9Df71CA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14919 Add Token X (BEP20)
  blockchains/smartchain/assets/0x4D864E4f542b4b40acB3151C9daD2e2C9236a88f/info.json
  blockchains/smartchain/assets/0x4D864E4f542b4b40acB3151C9daD2e2C9236a88f/logo.png
Labels: Payment Status: Paid

#14923 add NAOS Token (ERC20,BEP20)
  blockchains/ethereum/assets/0x4a615bB7166210CCe20E6642a6f8Fb5d4D044496/info.json
  blockchains/ethereum/assets/0x4a615bB7166210CCe20E6642a6f8Fb5d4D044496/logo.png
  blockchains/smartchain/assets/0x758d08864fB6cCE3062667225ca10b8F00496cc2/info.json
  blockchains/smartchain/assets/0x758d08864fB6cCE3062667225ca10b8F00496cc2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14979 Add BrandPad Finance (BEP20)
  blockchains/smartchain/assets/0x4d993ec7b44276615bB2F6F20361AB34FbF0ec49/info.json
  blockchains/smartchain/assets/0x4d993ec7b44276615bB2F6F20361AB34FbF0ec49/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14981 Add MiniFlokiADA (BEP20)
  blockchains/smartchain/assets/0x48CbC7f87C657fEA3B297F658a5133a5deeF9b04/info.json
  blockchains/smartchain/assets/0x48CbC7f87C657fEA3B297F658a5133a5deeF9b04/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14998 Add PumpShibaX (BEP20)
  blockchains/smartchain/assets/0x9F70625680a4bd250d3c59C755632B09cD6D34Bc/info.json
  blockchains/smartchain/assets/0x9F70625680a4bd250d3c59C755632B09cD6D34Bc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14949 Somax logo and info
  blockchains/smartchain/assets/0x586330013C8f2352AB5f57215F9E56747eE8837E/info.json
  blockchains/smartchain/assets/0x586330013C8f2352AB5f57215F9E56747eE8837E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15011 Add TTH Logo And info
  blockchains/smartchain/assets/0xF19b09DA89722F0a6960F9bF9701A63AE891603A/info.json
  blockchains/smartchain/assets/0xF19b09DA89722F0a6960F9bF9701A63AE891603A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15017 Add Zilliqa (BEP20)
  blockchains/smartchain/assets/0xb86AbCb37C3A4B64f74f59301AFF131a1BEcC787/info.json
  blockchains/smartchain/assets/0xb86AbCb37C3A4B64f74f59301AFF131a1BEcC787/logo.png
Labels: Payment Status: Requested

#15028 Add MetaPlay (BEP20)
  blockchains/smartchain/assets/0x9E3aD692084737DAF3f8e92bdFB4030965d2d5E6/info.json
  blockchains/smartchain/assets/0x9E3aD692084737DAF3f8e92bdFB4030965d2d5E6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15031 Add missing CoinGecko URL
  blockchains/smartchain/assets/0xCC5667333F5e997aC9F0C26d41b7ddA65b2b675a/info.json
Labels: Payment Status: Paid

#14913 Add EverestCoin (BEP20)
  blockchains/smartchain/assets/0x84B7BB9614Cf28226d1b0a07499472bc107e3000/info.json
  blockchains/smartchain/assets/0x84B7BB9614Cf28226d1b0a07499472bc107e3000/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14987 Add MONO logo and info
  blockchains/smartchain/assets/0xD4099A517f2Fbe8a730d2ECaad1D0824B75e084a/info.json
  blockchains/smartchain/assets/0xD4099A517f2Fbe8a730d2ECaad1D0824B75e084a/logo.png
Labels: Payment Status: Paid

#15041 Add ENS token (ERC20)
  blockchains/ethereum/assets/0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72/info.json
  blockchains/ethereum/assets/0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72/logo.png
Labels: Payment Status: Requested

#15007 Added Dinger Token logo and info
  blockchains/ethereum/assets/0x9e5BD9D9fAd182ff0A93bA8085b664bcab00fA68/info.json
  blockchains/ethereum/assets/0x9e5BD9D9fAd182ff0A93bA8085b664bcab00fA68/logo.png
Labels: Status: On Hold, Payment Status: Paid

#15051 Add SHIBORG INU logo and info
  blockchains/smartchain/assets/0x389c13d5be24bED2af35C30F211E042225CB06fF/info.json
  blockchains/smartchain/assets/0x389c13d5be24bED2af35C30F211E042225CB06fF/logo.png
Labels: Payment Status: Paid

#15015 Add French Connection Finance (BEP20)
  blockchains/smartchain/assets/0x4673f018cc6d401AAD0402BdBf2abcBF43dd69F3/info.json
  blockchains/smartchain/assets/0x4673f018cc6d401AAD0402BdBf2abcBF43dd69F3/logo.png
Labels: Payment Status: Paid

#15057 Add AnpanSwap Token (BEP20)
  blockchains/smartchain/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/info.json
  blockchains/smartchain/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/logo.png
Labels: Payment Status: Requested

#15019 Update status
  blockchains/ethereum/assets/0xc770EEfAd204B5180dF6a14Ee197D99d808ee52d/info.json
Labels: Payment Status: Requested

#15058 Uploading logo and information in JSON format to the XMINE Token.
  blockchains/smartchain/assets/0x0fA9651a0ecC19906843C13c60443300B9d37355/info.json
  blockchains/smartchain/assets/0x0fA9651a0ecC19906843C13c60443300B9d37355/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15075 Add TWT logo and info for shibanomics
  blockchains/smartchain/assets/0xe2cBF8572EAb769311A8c562b00A14Ca55eaa0EA/info.json
  blockchains/smartchain/assets/0xe2cBF8572EAb769311A8c562b00A14Ca55eaa0EA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15079 fix CMC link for SavePlanetEarth
  blockchains/smartchain/assets/0x5A4f765476Fd1BF010783B47a25CbF10974e6A37/info.json
Labels: Payment Status: Paid

#15084 Add Baby Floki Up Logo and Info
  blockchains/smartchain/assets/0x8927282a3d05EF5F7dc24eD0eE009be264d2ebd7/info.json
  blockchains/smartchain/assets/0x8927282a3d05EF5F7dc24eD0eE009be264d2ebd7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15113 Add SparkLab (BEP20)
  blockchains/smartchain/assets/0x683b383E9D6Cc523F4C9764daceBB5752892fc53/info.json
  blockchains/smartchain/assets/0x683b383E9D6Cc523F4C9764daceBB5752892fc53/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15116 Add Floki Elon (BEP20)
  blockchains/smartchain/assets/0xc4a54699d24C5C130cf866974181E41e22bb3b07/info.json
  blockchains/smartchain/assets/0xc4a54699d24C5C130cf866974181E41e22bb3b07/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15136 remove old logo for SLP
  blockchains/ethereum/assets/0x37236CD05b34Cc79d3715AF2383E96dd7443dCF1/logo.png
Labels: Payment Status: Requested

#15132 Updated info for RPG
  blockchains/smartchain/assets/0x01E0d17a533E5930A349C2BB71304F04F20AB12B/info.json
  blockchains/smartchain/assets/0x01E0d17a533E5930A349C2BB71304F04F20AB12B/logo.png
Labels: Payment Status: Paid

#15144 Change status to abandoned for inSure (ERC20)
  blockchains/ethereum/assets/0xb5a4ac5b04E777230bA3381195EfF6a60c3934F2/info.json
Labels: Payment Status: Paid

#15157 Add Starpunk (BEP20)
  blockchains/smartchain/assets/0xcb2B25e783A414f0d20A65aFa741C51b1Ad84c49/info.json
  blockchains/smartchain/assets/0xcb2B25e783A414f0d20A65aFa741C51b1Ad84c49/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15154 Add SurfMoon Token (BEP20)
  blockchains/smartchain/assets/0xc47f53c425d08f8457471538Ae641655814bEAe8/info.json
  blockchains/smartchain/assets/0xc47f53c425d08f8457471538Ae641655814bEAe8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15161 Add Boom Shiba (BEP20)
  blockchains/smartchain/assets/0x14aF0e9D51d9FE25c1675cC580409b640286167F/info.json
  blockchains/smartchain/assets/0x14aF0e9D51d9FE25c1675cC580409b640286167F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15085 Add Blockmonsters (BEP20)
  blockchains/smartchain/assets/0x287Db351d5230716246CfB46AF8153025eDa6A0a/info.json
  blockchains/smartchain/assets/0x287Db351d5230716246CfB46AF8153025eDa6A0a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15181 Add Wolverine (BEP20)
  blockchains/smartchain/assets/0xBe6dE6b614b079236839404440E3e8867B5d6751/info.json
  blockchains/smartchain/assets/0xBe6dE6b614b079236839404440E3e8867B5d6751/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15164 Add EDXA(BEP20) - resubmit
  blockchains/smartchain/assets/0x952cEbF65f3A9F11ef0222Aefe0608d26621B097/info.json
  blockchains/smartchain/assets/0x952cEbF65f3A9F11ef0222Aefe0608d26621B097/logo.png
Labels: Payment Status: Paid

#15185 Omax token logo update
  blockchains/smartchain/assets/0xeB84be66c8E71f07eA57Cf3b21626d7784F32A7F/info.json
  blockchains/smartchain/assets/0xeB84be66c8E71f07eA57Cf3b21626d7784F32A7F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15163 Coin of Nature
  blockchains/smartchain/assets/0xe0e0Fbc7E8D881953d39CF899409410B50b8C924/info.json
  blockchains/smartchain/assets/0xe0e0Fbc7E8D881953d39CF899409410B50b8C924/logo.png
Labels: Payment Status: Paid

#15241 Add BabyDogeZilla Logo To Trust Wallet
  blockchains/smartchain/assets/0x0fbc08905c1d683Cf7530bb2a70Bb0BDE231E5B9/info.json
  blockchains/smartchain/assets/0x0fbc08905c1d683Cf7530bb2a70Bb0BDE231E5B9/logo.png
Labels: Payment Status: Paid

#15234 Add BlackEyeGalaxy Token (BEP20)
  blockchains/smartchain/assets/0x4F7B627b88651e3DddcA0240bcA68a3062632C8c/info.json
  blockchains/smartchain/assets/0x4F7B627b88651e3DddcA0240bcA68a3062632C8c/logo.png
Labels: Payment Status: Paid

#15214 Add AVNRich Token (BEP20)
  blockchains/smartchain/assets/0xbf151F63D8d1287db5FC7a3bc104a9c38124cdeB/info.json
  blockchains/smartchain/assets/0xbf151F63D8d1287db5FC7a3bc104a9c38124cdeB/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15212 Add Shib Army (BEP20)
  blockchains/smartchain/assets/0x940230b6b7ef1979a28F32196A8e3439C645BA49/info.json
  blockchains/smartchain/assets/0x940230b6b7ef1979a28F32196A8e3439C645BA49/logo.png
Labels: Payment Status: Paid

#15194 Add Idle Cyber (BEP20)
  blockchains/smartchain/assets/0xbA0B46F556633Bd742546E4F37D66D416753003B/info.json
  blockchains/smartchain/assets/0xbA0B46F556633Bd742546E4F37D66D416753003B/logo.png
Labels: Payment Status: Paid

#15186 Add Scorpion Finance (BEP20)
  blockchains/smartchain/assets/0x475C8dF9860E42605d9917f0a2E522cC861cbf82/info.json
  blockchains/smartchain/assets/0x475C8dF9860E42605d9917f0a2E522cC861cbf82/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#15195 Add Ridotto (ERC20 & BEP20)
  blockchains/ethereum/assets/0x4740735AA98Dc8aa232BD049f8F0210458E7fCa3/info.json
  blockchains/ethereum/assets/0x4740735AA98Dc8aa232BD049f8F0210458E7fCa3/logo.png
  blockchains/smartchain/assets/0xe9c64384dEb0C2bF06D991A8D708c77eb545E3d5/info.json
  blockchains/smartchain/assets/0xe9c64384dEb0C2bF06D991A8D708c77eb545E3d5/logo.png
Labels: Payment Status: Paid

#15275 Add BuffedShiba (BEP20)
  blockchains/smartchain/assets/0xD8F61cdECA41dEF1a7923F308a042F678109f54B/info.json
  blockchains/smartchain/assets/0xD8F61cdECA41dEF1a7923F308a042F678109f54B/logo.png
Labels: Payment Status: Paid

#15202 Add CryptonlyFanz (BEP20)
  blockchains/smartchain/assets/0xC477c189d6C572F6C618eA76658B062b1530224c/info.json
  blockchains/smartchain/assets/0xC477c189d6C572F6C618eA76658B062b1530224c/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#15297 Add CHN token
  blockchains/ethereum/assets/0x41C37A4683d6a05adB31c39D71348A8403B13Ca9/info.json
  blockchains/ethereum/assets/0x41C37A4683d6a05adB31c39D71348A8403B13Ca9/logo.png
Labels: Payment Status: Paid

#15285 Add Celestial (BEP20)
  blockchains/smartchain/assets/0x4f34292F109870d5fdDA602Bc7e3ae56D520D6e1/info.json
  blockchains/smartchain/assets/0x4f34292F109870d5fdDA602Bc7e3ae56D520D6e1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15290 Adding missing tokens
  blockchains/smartchain/assets/0x07af67b392B7A202fAD8E0FBc64C34F33102165B/info.json
  blockchains/smartchain/assets/0x07af67b392B7A202fAD8E0FBc64C34F33102165B/logo.png
  blockchains/smartchain/assets/0x7A565284572d03EC50c35396F7d6001252eb43B6/info.json
  blockchains/smartchain/assets/0x7A565284572d03EC50c35396F7d6001252eb43B6/logo.png
  blockchains/smartchain/assets/0x9E24415d1e549EBc626a13a482Bb117a2B43e9CF/info.json
  blockchains/smartchain/assets/0x9E24415d1e549EBc626a13a482Bb117a2B43e9CF/logo.png
  blockchains/smartchain/assets/0xaF6Bd11A6F8f9c44b9D18f5FA116E403db599f8E/info.json
  blockchains/smartchain/assets/0xaF6Bd11A6F8f9c44b9D18f5FA116E403db599f8E/logo.png
  blockchains/smartchain/assets/0xc4a54699d24C5C130cf866974181E41e22bb3b07/info.json
Labels: Payment Status: Requested

#15295 Add FLOKIZ Token and info (#15168 PAID)
  blockchains/smartchain/assets/0xee901a8a13e5B71dD35AD259D87e17a891D1f0F3/info.json
  blockchains/smartchain/assets/0xee901a8a13e5B71dD35AD259D87e17a891D1f0F3/logo.png
Labels: Payment Status: Paid

#15292 Add SatoshiStreetBets Token (BEP20)
  blockchains/smartchain/assets/0x55B53855eaE06c4744841dbFA06FCe335dB4355B/info.json
  blockchains/smartchain/assets/0x55B53855eaE06c4744841dbFA06FCe335dB4355B/logo.png
Labels: Payment Status: Paid

#15152 Add Memeflate (BEP20)
  blockchains/smartchain/assets/0xaFE3321309A994831884fc1725F4c3236AC79f76/info.json
  blockchains/smartchain/assets/0xaFE3321309A994831884fc1725F4c3236AC79f76/logo.png
Labels: Status: On Hold, Payment Status: Paid

#15291 Add MOWA logo and info
  blockchains/smartchain/assets/0x411Ec510c85C9e56271bF4E10364Ffa909E685D9/info.json
  blockchains/smartchain/assets/0x411Ec510c85C9e56271bF4E10364Ffa909E685D9/logo.png
Labels: Status: On Hold, Payment Status: Paid

#15315 Add Scorpion Finance (BEP20)
  blockchains/smartchain/assets/0x475C8dF9860E42605d9917f0a2E522cC861cbf82/info.json
Labels: Payment Status: Paid

#15263 Add DKT token info (BEP20)
  blockchains/smartchain/assets/0x7Ceb519718A80Dd78a8545AD8e7f401dE4f2faA7/info.json
  blockchains/smartchain/assets/0x7Ceb519718A80Dd78a8545AD8e7f401dE4f2faA7/logo.png
Labels: Payment Status: Paid

#15294 Add LilDogeFloki Support for Trust Wallet
  blockchains/smartchain/assets/0xaa15f52Ef3994213a9e06731F6471786B75372CC/info.json
  blockchains/smartchain/assets/0xaa15f52Ef3994213a9e06731F6471786B75372CC/logo.png
Labels: Payment Status: Paid

#15231 Add Welnance Coin (BEP20)
  blockchains/smartchain/assets/0x854B4c305554c5fa72353e31b8480c0e5128A152/info.json
  blockchains/smartchain/assets/0x854B4c305554c5fa72353e31b8480c0e5128A152/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15331 Add dapps
  dapps/app.sushi.com.png
  dapps/poocoin.app.png
  dapps/v1exchange.pancakeswap.finance.png
Labels: Payment Status: Requested

#15324 Add Metaverse Inu (BEP20)
  blockchains/smartchain/assets/0xC75bcC3ae0844c16Fd1881b8bb47BD509303a135/info.json
  blockchains/smartchain/assets/0xC75bcC3ae0844c16Fd1881b8bb47BD509303a135/logo.png
Labels: Payment Status: Paid

#15309 Add Crystal logo and info(BEP20)
  blockchains/smartchain/assets/0xE93B4fb367F3678A32f28254355f9f6ac000c976/info.json
  blockchains/smartchain/assets/0xE93B4fb367F3678A32f28254355f9f6ac000c976/logo.png
Labels: Payment Status: Paid

#15323 Add Velorex (BEP20)
  blockchains/smartchain/assets/0xc029A12e4A002c6858878FD9D3cc74E227cc2DDa/info.json
  blockchains/smartchain/assets/0xc029A12e4A002c6858878FD9D3cc74E227cc2DDa/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15330 Add Doge King (BEP20)
  blockchains/smartchain/assets/0x01db446F7C6d20ce1FcA421B4397dA789fbb21F1/info.json
  blockchains/smartchain/assets/0x01db446F7C6d20ce1FcA421B4397dA789fbb21F1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15351 add ENS in token list
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid

#15289 Add Kishimoto Inu
  blockchains/ethereum/assets/0xf5b1Fd29d23e98Db2D9EBb8435E1082e3B38FB65/info.json
  blockchains/ethereum/assets/0xf5b1Fd29d23e98Db2D9EBb8435E1082e3B38FB65/logo.png
Labels: Payment Status: Requested

#15367 Add Vikings Inu (BEP20)
  blockchains/smartchain/assets/0xc3583C8328eCB4DC8751C7e4fe7bCC18E558A4b6/info.json
  blockchains/smartchain/assets/0xc3583C8328eCB4DC8751C7e4fe7bCC18E558A4b6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15371 Add Anji (BEP20)
  blockchains/smartchain/assets/0xfc619FfCc0e0F30427BF938f9A1B2BfAE15bDf84/info.json
  blockchains/smartchain/assets/0xfc619FfCc0e0F30427BF938f9A1B2BfAE15bDf84/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15369 Add Logo and Info (BEP20)
  blockchains/smartchain/assets/0xf2673f49d2737f97d70995eD43D128E0B8E560c5/info.json
  blockchains/smartchain/assets/0xf2673f49d2737f97d70995eD43D128E0B8E560c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15224 added Godzilla token
  blockchains/smartchain/assets/0xDa4714fEE90Ad7DE50bC185ccD06b175D23906c1/info.json
  blockchains/smartchain/assets/0xDa4714fEE90Ad7DE50bC185ccD06b175D23906c1/logo.png
Labels: Status: On Hold, Payment Status: Paid

#15341 Add FalconX (BEP20)
  blockchains/smartchain/assets/0x2D862c9FC46608d7ff83293cEB83330D6135BE5E/info.json
  blockchains/smartchain/assets/0x2D862c9FC46608d7ff83293cEB83330D6135BE5E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15385 Delete duplicate USDC
  blockchains/solana/assets/3K6rftdAaQYMPunrtNRHgnK2UAtjm2JwyT2oCiTDouYE/info.json
  blockchains/solana/assets/BXXkv6z8ykpG1yuvUDPgh732wzVHB69RnB9YgSYh3itW/info.json
  blockchains/solana/assets/BXXkv6z8ykpG1yuvUDPgh732wzVHB69RnB9YgSYh3itW/logo.png
  blockchains/solana/assets/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/info.json
Labels: Payment Status: Requested

#15381 Add Dali
  blockchains/smartchain/assets/0x5a119762B09Ed0bcB3b16075159AE43A62651383/info.json
  blockchains/smartchain/assets/0x5a119762B09Ed0bcB3b16075159AE43A62651383/logo.png
Labels: Payment Status: Paid

#15350 Add AFFINITY (BEP20)
  blockchains/smartchain/assets/0x0cAE6c43fe2f43757a767Df90cf5054280110F3e/info.json
  blockchains/smartchain/assets/0x0cAE6c43fe2f43757a767Df90cf5054280110F3e/logo.png
Labels: Payment Status: Paid

#15313 Add Merit Circle (MC) (ERC20)
  blockchains/ethereum/assets/0x949D48EcA67b17269629c7194F4b727d4Ef9E5d6/info.json
  blockchains/ethereum/assets/0x949D48EcA67b17269629c7194F4b727d4Ef9E5d6/logo.png
Labels: Payment Status: Paid

#15390 SonOfShib PR including Certik Audit Link
  blockchains/smartchain/assets/0x413EcA30181F7eD78De38da95F44fC53F664157A/info.json
  blockchains/smartchain/assets/0x413EcA30181F7eD78De38da95F44fC53F664157A/logo.png
Labels: Payment Status: Paid

#15398 Add files via upload
  blockchains/smartchain/assets/0xF28709f1daa6CEE2847C5B9526ceba457331742b/info.json
  blockchains/smartchain/assets/0xF28709f1daa6CEE2847C5B9526ceba457331742b/logo.png
Labels: Payment Status: Paid

#15403 Add FindShibby (BEP20)
  blockchains/smartchain/assets/0x9A21477b4e9EA5F7946D75876A186A1194559828/info.json
  blockchains/smartchain/assets/0x9A21477b4e9EA5F7946D75876A186A1194559828/logo.png
Labels: Payment Status: Paid

#15399 Add kitty inu logo and info
  blockchains/ethereum/assets/0x044727e50ff30DB57fad06Ff4F5846eAb5eA52a2/info.json
  blockchains/ethereum/assets/0x044727e50ff30DB57fad06Ff4F5846eAb5eA52a2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15271 Add Aegis Launchpad (BEP20)
  blockchains/smartchain/assets/0xf834673D496AEAcb5E99Dfbfc34f1bDCdf81D7Bd/info.json
  blockchains/smartchain/assets/0xf834673D496AEAcb5E99Dfbfc34f1bDCdf81D7Bd/logo.png
Labels: Payment Status: Paid

#15409 Delete assignOnPay: zachzwei
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#15375 [Internal] Update Ethereum tokenlist (uniswap)
  blockchains/ethereum/tokenlist.json
  script/config.ts
Labels: Payment Status: Paid, Payment Status: Requested

#15393 Added ADA BOY token.
  blockchains/smartchain/assets/0x1E653794A6849bC8A78be50C4D48981AfAD6359d/info.json
  blockchains/smartchain/assets/0x1E653794A6849bC8A78be50C4D48981AfAD6359d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15408 Add GLMS logo and info
  blockchains/smartchain/assets/0x75f53011f6D51C60e6DCbf54A8B1bCB54f07F0C9/info.json
  blockchains/smartchain/assets/0x75f53011f6D51C60e6DCbf54A8B1bCB54f07F0C9/logo.png
Labels: Payment Status: Paid

#15432 add gamingdoge
  blockchains/smartchain/assets/0x536627083e216C3Cf4476ec504eb51Bbd47cA4ac/info.json
  blockchains/smartchain/assets/0x536627083e216C3Cf4476ec504eb51Bbd47cA4ac/logo.png
Labels: Payment Status: Paid

#15438 add assignOnPay: ramsty
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#15444 Update README.md links
  README.md
Labels: Payment Status: Paid

#15445 Update merge-fee-bot-links
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#15453 Update logo icon
  blockchains/smartchain/assets/0x673Da443da2f6aE7c5c660A9F0D3DD24d1643D36/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15415 Add AD Token (BEP20)
  blockchains/smartchain/assets/0x538b972E46B86373638B14fa6F6a9C51f796394b/info.json
  blockchains/smartchain/assets/0x538b972E46B86373638B14fa6F6a9C51f796394b/logo.png
Labels: Payment Status: Paid

#15424 Add SPAY (BEP20)
  blockchains/smartchain/assets/0xb21225F833f2Fb1BE7d88Ee5347aae001F5b5DB1/info.json
  blockchains/smartchain/assets/0xb21225F833f2Fb1BE7d88Ee5347aae001F5b5DB1/logo.png
Labels: Payment Status: Paid

#15443 Add Doge Yellow Coin (BEP20)
  blockchains/smartchain/assets/0x6f373cD69c329B1DA2e00b861Ad950e59454aa18/info.json
  blockchains/smartchain/assets/0x6f373cD69c329B1DA2e00b861Ad950e59454aa18/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15437 Add Tokenoid (BEP20)
  blockchains/smartchain/assets/0xB068bD15AEDf75Be6c2c6d0Be10b286a32087120/info.json
  blockchains/smartchain/assets/0xB068bD15AEDf75Be6c2c6d0Be10b286a32087120/logo.png
Labels: Payment Status: Paid

#15462 Add Baby Mind (BEP20)
  blockchains/smartchain/assets/0x350c8a09ccf7f862F0D835b0AFF85898c22D2840/info.json
  blockchains/smartchain/assets/0x350c8a09ccf7f862F0D835b0AFF85898c22D2840/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15448 Add Kitty Shiba (BEP20)
  blockchains/smartchain/assets/0xc978BA9309f3c3bE3a79302251A2bB041bAa7118/info.json
  blockchains/smartchain/assets/0xc978BA9309f3c3bE3a79302251A2bB041bAa7118/logo.png
Labels: Payment Status: Paid

#15474 Add MTA logo and info.
  blockchains/smartchain/assets/0x19D3A7c26a1271eeBB6f04bDb4565b7F2B7EFc30/info.json
  blockchains/smartchain/assets/0x19D3A7c26a1271eeBB6f04bDb4565b7F2B7EFc30/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15504 Updating Bidali icon
  dapps/commerce.bidali.com.png
Labels: Payment Status: Requested

#15466 Add DEEPSPACE - DPS Token
  blockchains/smartchain/assets/0xf275e1AC303a4C9D987a2c48b8E555A77FeC3F1C/info.json
  blockchains/smartchain/assets/0xf275e1AC303a4C9D987a2c48b8E555A77FeC3F1C/logo.png
Labels: Payment Status: Paid

#15487 Add RLOKI logo and info
  blockchains/smartchain/assets/0x1476e96FAdb37668d7680921297e2ab98Ec36c2F/info.json
  blockchains/smartchain/assets/0x1476e96FAdb37668d7680921297e2ab98Ec36c2F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15446 Landshare logo and information
  blockchains/smartchain/assets/0x9D986A3f147212327Dd658F712d5264a73a1fdB0/info.json
  blockchains/smartchain/assets/0x9D986A3f147212327Dd658F712d5264a73a1fdB0/logo.png
Labels: Payment Status: Paid

#15539 Add Hachiko (BEP20)
  blockchains/smartchain/assets/0x87Ffc48C9f89fc5dfA05836e083406D684FD6331/info.json
  blockchains/smartchain/assets/0x87Ffc48C9f89fc5dfA05836e083406D684FD6331/logo.png
Labels: Payment Status: Paid

#15548 Add CG, CMC and whitepaper links
  blockchains/smartchain/assets/0x5a119762B09Ed0bcB3b16075159AE43A62651383/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#15533 Request to add FLOBO info and logo to Trustwallet
  blockchains/smartchain/assets/0x9d3E14B607b2f569CfAFe29AF71e811d7E575CFe/info.json
  blockchains/smartchain/assets/0x9d3E14B607b2f569CfAFe29AF71e811d7E575CFe/logo.png
Labels: Payment Status: Paid

#15525 Add Binancedog (BEP20)
  blockchains/smartchain/assets/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/info.json
  blockchains/smartchain/assets/0x265f638eAb14dD43D80bB71AAe3289B1c6d46A3f/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15455 Adding Revolotto (RVL) Logo
  blockchains/smartchain/assets/0x6dc3d0D6EC970BF5522611D8eFF127145D02b675/info.json
  blockchains/smartchain/assets/0x6dc3d0D6EC970BF5522611D8eFF127145D02b675/logo.png
Labels: Payment Status: Paid

#15540 Add HFT logo and info
  blockchains/smartchain/assets/0x186866858aEf38c05829166A7711b37563e15994/info.json
  blockchains/smartchain/assets/0x186866858aEf38c05829166A7711b37563e15994/logo.png
Labels: Payment Status: Paid

#15575 BODAV2 Token Logo Request with Audit complete
  blockchains/smartchain/assets/0xdc847755343C3A2B94d6aFC0aAE57651E1b14064/info.json
  blockchains/smartchain/assets/0xdc847755343C3A2B94d6aFC0aAE57651E1b14064/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15558 Add Binance-Peg Firo Token (BEP20)
  blockchains/smartchain/assets/0xd5d0322b6bAb6a762C79f8c81A0B674778E13aeD/info.json
  blockchains/smartchain/assets/0xd5d0322b6bAb6a762C79f8c81A0B674778E13aeD/logo.png
Labels: Payment Status: Requested

#15572 submition
  blockchains/smartchain/assets/0x5778A155fA82063C5C1E48771CAA44ea4d8a5d7a/info.json
  blockchains/smartchain/assets/0x5778A155fA82063C5C1E48771CAA44ea4d8a5d7a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15570 Add PNFT Logo
  blockchains/smartchain/assets/0xEC43D3153C1f08946fA71cDD3A14Af64fd58f27e/info.json
  blockchains/smartchain/assets/0xEC43D3153C1f08946fA71cDD3A14Af64fd58f27e/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15589 [Internal] Osmosis chain info
  blockchains/osmosis/info/info.json
  blockchains/osmosis/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15538 Add info and KDG logo
  blockchains/smartchain/assets/0x87A2d9a9A6b2D61B2a57798f1b4b2DDd19458Fb6/info.json
  blockchains/smartchain/assets/0x87A2d9a9A6b2D61B2a57798f1b4b2DDd19458Fb6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15568 Add Zoo Token (BEP20)
  blockchains/smartchain/assets/0xb3d691125514Db7a5bE3326af86a72ecdC2CDE16/info.json
  blockchains/smartchain/assets/0xb3d691125514Db7a5bE3326af86a72ecdC2CDE16/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15581 Add BNB Shinobi (BEP20)
  blockchains/smartchain/assets/0xEFf13653EEb698Ba291B8BfF7AAaaB648132c2D7/info.json
  blockchains/smartchain/assets/0xEFf13653EEb698Ba291B8BfF7AAaaB648132c2D7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15557 Add Flokimooni (BEP20)
  blockchains/smartchain/assets/0x0f5351B9EAefd6687dfF143DE6eA5d01cB9c1205/info.json
  blockchains/smartchain/assets/0x0f5351B9EAefd6687dfF143DE6eA5d01cB9c1205/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15602 Add DYT TOKEN (BEP20)
  blockchains/smartchain/assets/0x1802a63EFe3255aBC3004F8e63047dB96300bd1c/info.json
  blockchains/smartchain/assets/0x1802a63EFe3255aBC3004F8e63047dB96300bd1c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15600 Add SPONSEE Info + Logo
  blockchains/smartchain/assets/0xE41d9E1311209F2e05850F9de6201Ab4B930Bfc2/info.json
  blockchains/smartchain/assets/0xE41d9E1311209F2e05850F9de6201Ab4B930Bfc2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15598 Update token and Add token on BSC
  blockchains/ethereum/assets/0x358AA737e033F34df7c54306960a38d09AaBd523/info.json
  blockchains/smartchain/assets/0xf9752A6E8A5E5f5e6EB3aB4e7d8492460fb319f0/info.json
  blockchains/smartchain/assets/0xf9752A6E8A5E5f5e6EB3aB4e7d8492460fb319f0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15590 Add Aidi Finance BSC logo
  blockchains/smartchain/assets/0xb358b0e5A8943029e66175830D85198fE6cC93f6/info.json
  blockchains/smartchain/assets/0xb358b0e5A8943029e66175830D85198fE6cC93f6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15617 Add Hedge Token
  blockchains/smartchain/assets/0xE7784072FC769D8b7f8C0a3Fa008722eEF5dDDD5/info.json
  blockchains/smartchain/assets/0xE7784072FC769D8b7f8C0a3Fa008722eEF5dDDD5/logo.png
Labels: Payment Status: Paid

#15626 Update logo Anime
  blockchains/smartchain/assets/0xaC472D0EED2B8a2f57a6E304eA7eBD8E88D1d36f/logo.png
Labels: Payment Status: Requested

#15627 Add Pegaxy Stone logo and info
  blockchains/polygon/assets/0xc1c93D475dc82Fe72DBC7074d55f5a734F8cEEAE/info.json
  blockchains/polygon/assets/0xc1c93D475dc82Fe72DBC7074d55f5a734F8cEEAE/logo.png
Labels: Payment Status: Paid

#15631 Add logo and info.json for WKD (Wakanda Inu Token)
  blockchains/smartchain/assets/0x0025B42bfc22CbbA6c02d23d4Ec2aBFcf6E014d4/info.json
  blockchains/smartchain/assets/0x5344C20FD242545F31723689662AC12b9556fC3d/info.json
  blockchains/smartchain/assets/0x5344C20FD242545F31723689662AC12b9556fC3d/logo.png
Labels: Payment Status: Paid

#15641 Add BEP20 QANX token
  blockchains/smartchain/assets/0xAAA7A10a8ee237ea61E8AC46C50A8Db8bCC1baaa/info.json
  blockchains/smartchain/assets/0xAAA7A10a8ee237ea61E8AC46C50A8Db8bCC1baaa/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15643 Adding Elonomics logo and info to Trust Wallet
  blockchains/smartchain/assets/0xd3ecC6a4ce1a9fAEC1AA5E30B55f8a1a4b84F938/info.json
  blockchains/smartchain/assets/0xd3ecC6a4ce1a9fAEC1AA5E30B55f8a1a4b84F938/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15652 Add UNIMOON (BEP20)
  blockchains/smartchain/assets/0x893e14FAfa8df32D9bE7eab810027eeA8828A98c/info.json
  blockchains/smartchain/assets/0x893e14FAfa8df32D9bE7eab810027eeA8828A98c/logo.png
Labels: Payment Status: Paid

#15657 Add The Spartans (BEP20)
  blockchains/smartchain/assets/0x930CEc48eddC7f80AFaD2b08997D0A43912B80d4/info.json
  blockchains/smartchain/assets/0x930CEc48eddC7f80AFaD2b08997D0A43912B80d4/logo.png
Labels: Payment Status: Paid

#15639 Shibapup
  blockchains/smartchain/assets/0x8203612382f61baFaE549fBF31eFbf70992fA289/info.json
  blockchains/smartchain/assets/0x8203612382f61baFaE549fBF31eFbf70992fA289/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15674 Please add logo to BabyFlokiZilla token
  blockchains/smartchain/assets/0x9DC8Ae7F7f88e1344c289d75cd0D4Ce07Dc4Aae6/info.json
  blockchains/smartchain/assets/0x9DC8Ae7F7f88e1344c289d75cd0D4Ce07Dc4Aae6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15608 Add CGB COIN (BEP20)
  blockchains/smartchain/assets/0x7f247a00EaB12419e5dEB021B48f6eBf249CF86C/info.json
  blockchains/smartchain/assets/0x7f247a00EaB12419e5dEB021B48f6eBf249CF86C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14790 Add KWT logo and info
  blockchains/smartchain/assets/0x257a8d1E03D17B8535a182301f15290F11674b53/info.json
  blockchains/smartchain/assets/0x257a8d1E03D17B8535a182301f15290F11674b53/logo.png
Labels: Payment Status: Paid

#15662 Add Shiba Monk (BEP20)
  blockchains/smartchain/assets/0x9a95f03A305db3BD25D9C891793118D56C73d012/info.json
  blockchains/smartchain/assets/0x9a95f03A305db3BD25D9C891793118D56C73d012/logo.png
Labels: Payment Status: Paid

#15678 Add DAMN logo and info
  blockchains/smartchain/assets/0xB4AA0CD9FACeB466DB69b825DC666EdAF3293d28/info.json
  blockchains/smartchain/assets/0xB4AA0CD9FACeB466DB69b825DC666EdAF3293d28/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15673 Add ERC20 QANX token
  blockchains/ethereum/assets/0xAAA7A10a8ee237ea61E8AC46C50A8Db8bCC1baaa/info.json
  blockchains/ethereum/assets/0xAAA7A10a8ee237ea61E8AC46C50A8Db8bCC1baaa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15698 Update logo for KSHIBA token
  blockchains/smartchain/assets/0xc978BA9309f3c3bE3a79302251A2bB041bAa7118/logo.png
Labels: Payment Status: Requested

#15697 Add Mars Inu (BEP20)
  blockchains/smartchain/assets/0x9910f48EF7bd0291bC050CF900D732C24b39Ec31/info.json
  blockchains/smartchain/assets/0x9910f48EF7bd0291bC050CF900D732C24b39Ec31/logo.png
Labels: Payment Status: Paid

#15700 Update logo for CVR
  blockchains/ethereum/assets/0x3C03b4EC9477809072FF9CC9292C9B25d4A8e6c6/logo.png
Labels: Payment Status: Paid

#15709 Add Baby CateCoin (BEP20)
  blockchains/smartchain/assets/0x1529642Cd0075d3DA049aA43005fdfaBCa54a070/info.json
  blockchains/smartchain/assets/0x1529642Cd0075d3DA049aA43005fdfaBCa54a070/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#15721 Add SHAK logo and info
  blockchains/smartchain/assets/0x76E08e1c693D42551dd6ba7C2A659F74ff5Ba261/info.json
  blockchains/smartchain/assets/0x76E08e1c693D42551dd6ba7C2A659F74ff5Ba261/logo.png
Labels: Payment Status: Paid

#15718 Add Pixl Coin (BEP20)
  blockchains/smartchain/assets/0x72d2946094E6E57c2faDe4964777A9af2B7A51F9/info.json
  blockchains/smartchain/assets/0x72d2946094E6E57c2faDe4964777A9af2B7A51F9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#15663 Add Atlas Staking to the Kava Validator list
  blockchains/kava/validators/assets/kavavaloper1ua2yqfjck23vsmynltcgrvvg5rhfkm4cy78vmq/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#15730 Add DeVolution (BEP20)
  blockchains/smartchain/assets/0x0FD98b8C58560167A236f1D0553A9c2a42342ccf/info.json
  blockchains/smartchain/assets/0x0FD98b8C58560167A236f1D0553A9c2a42342ccf/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
