Repository trustwallet/assets, pull requests merged in 2021-06, with the labels that each got.

#9101 Adding DEXI logo and info
  blockchains/smartchain/assets/0x29b1E39A529d3B3cacEA55989594F71813e998Bb/info.json
  blockchains/smartchain/assets/0x29b1E39A529d3B3cacEA55989594F71813e998Bb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9094 Add O3 Swap (O3) (BEP20)
  blockchains/smartchain/assets/0xEe9801669C6138E84bD50dEB500827b776777d28/info.json
  blockchains/smartchain/assets/0xEe9801669C6138E84bD50dEB500827b776777d28/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9054 Add PuffyDogCoin (BEP20)
  blockchains/smartchain/assets/0x42873a833717753A8d77Ad6d0a8710aF2c66c052/info.json
  blockchains/smartchain/assets/0x42873a833717753A8d77Ad6d0a8710aF2c66c052/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9089 Add Glitchy logo and info
  blockchains/smartchain/assets/0x75dffAf163D67591fDCa3907a50655dB3a5516Ed/info.json
  blockchains/smartchain/assets/0x75dffAf163D67591fDCa3907a50655dB3a5516Ed/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9079 Bullet token added
  blockchains/smartchain/assets/0x1F8Fc5470846011646C4cb05Cf235B47d5A7ADe6/info.json
  blockchains/smartchain/assets/0x1F8Fc5470846011646C4cb05Cf235B47d5A7ADe6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9108 Added the Kawaiinu logo and info
  blockchains/smartchain/assets/0x099D6CC403C0a5B46A6dD384c622Da39f1e1001C/info.json
  blockchains/smartchain/assets/0x099D6CC403C0a5B46A6dD384c622Da39f1e1001C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9075 NudesCoin logo and info
  blockchains/smartchain/assets/0xE60ef2b118C35c987CE28d3b69f84378F2b84b4a/info.json
  blockchains/smartchain/assets/0xE60ef2b118C35c987CE28d3b69f84378F2b84b4a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9071 Add IMSL Token Logo and Info.
  blockchains/smartchain/assets/0xc8aE2289c032B119DFD29396F1FC68Ee91F80118/info.json
  blockchains/smartchain/assets/0xc8aE2289c032B119DFD29396F1FC68Ee91F80118/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9069 Request to add Direwolf to trust wallet assets
  blockchains/ethereum/assets/0xBdea5bB640DBFC4593809DEeC5CdB8F99b704Cd2/info.json
  blockchains/ethereum/assets/0xBdea5bB640DBFC4593809DEeC5CdB8F99b704Cd2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9122 Add SafeWojak Logo and Info
  blockchains/smartchain/assets/0xACce5119881693B1502ECAF732eb1d592adFc54b/info.json
  blockchains/smartchain/assets/0xACce5119881693B1502ECAF732eb1d592adFc54b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9096 Update logo.png
  blockchains/smartchain/assets/0xf5015995376a35b10dcBD96BA6B6e9de1c9f87c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9053 Add SNFT logo and info
  blockchains/smartchain/assets/0x311827832c1f670229eF0AFbE96D2DF8195c8C9A/info.json
  blockchains/smartchain/assets/0x311827832c1f670229eF0AFbE96D2DF8195c8C9A/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#9133 Add SHAGGY TOKEN (BEP20)
  blockchains/smartchain/assets/0x33a669a350807552a005845C13A37662FAcb041B/info.json
  blockchains/smartchain/assets/0x33a669a350807552a005845C13A37662FAcb041B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9132 Update Logo DOGU
  blockchains/smartchain/assets/0x346b426b5c4d3bcBb129Ed84b52D8717e245BCE1/info.json
  blockchains/smartchain/assets/0x346b426b5c4d3bcBb129Ed84b52D8717e245BCE1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9128 Add logo wXRP
  blockchains/smartchain/assets/0xbbC9Fa4B395FeE68465C2Cd4a88cdE267a34ed2a/info.json
  blockchains/smartchain/assets/0xbbC9Fa4B395FeE68465C2Cd4a88cdE267a34ed2a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9088 Add Pallapay (PALLA) LOGO ( TRC20 )
  blockchains/tron/assets/TCfLxS9xHxH8auBL3T8pf3NFTZhsxy4Ncg/info.json
  blockchains/tron/assets/TCfLxS9xHxH8auBL3T8pf3NFTZhsxy4Ncg/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9144 Add AINORI (BEP20)
  blockchains/smartchain/assets/0x7cE4AcCd9bb261508ABd20B134D6278902369057/info.json
  blockchains/smartchain/assets/0x7cE4AcCd9bb261508ABd20B134D6278902369057/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#8108 Added Vancat Egg Token Logo
  blockchains/smartchain/assets/0x1FF2a2c2DEAdb17B6Ba9949393d1406f4c61BFC9/info.json
  blockchains/smartchain/assets/0x1FF2a2c2DEAdb17B6Ba9949393d1406f4c61BFC9/logo.png
  blockchains/smartchain/assets/0x8597ba143AC509189E89aaB3BA28d661A5dD9830/info.json
  blockchains/smartchain/assets/0xE285510E5C14c2b8ff46147D9145f034B8Ff073B/info.json
Labels: Payment Status: Paid, Status: More Info / Change Requested

#9160 add Geek logo and info
  blockchains/smartchain/assets/0x9FBbcAa3162c74b24751f7c4b9CFB4af0811a622/info.json
  blockchains/smartchain/assets/0x9FBbcAa3162c74b24751f7c4b9CFB4af0811a622/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9159 Add USD SMART (BEP20)
  blockchains/smartchain/assets/0x303dE4bdb189B951F875eB4A8ECDe2985138161e/info.json
  blockchains/smartchain/assets/0x303dE4bdb189B951F875eB4A8ECDe2985138161e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9156 adding Saiyan Inu SAYAN
  blockchains/smartchain/assets/0x127CF9704DDFcf0e9eC1Dc20f11877731D18ac34/info.json
  blockchains/smartchain/assets/0x127CF9704DDFcf0e9eC1Dc20f11877731D18ac34/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9151 Add Ddai logo and info
  blockchains/smartchain/assets/0xa20Be0B824b963Bc7D11D124CdEfa0bC7cE85533/info.json
  blockchains/smartchain/assets/0xa20Be0B824b963Bc7D11D124CdEfa0bC7cE85533/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9172 Glitchy Logo Update
  blockchains/smartchain/assets/0x75dffAf163D67591fDCa3907a50655dB3a5516Ed/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9197 add gdoge logo and info
  blockchains/smartchain/assets/0xDeb9acA4F54ABd9b82Ca91B52fCCCF869882B9Fe/info.json
  blockchains/smartchain/assets/0xDeb9acA4F54ABd9b82Ca91B52fCCCF869882B9Fe/logo.png
Labels: Payment Status: Requested

#9193 adding Hukku on TWT
  blockchains/smartchain/assets/0xFa01D3A2B25cdF3b1A6B2361FA07CC71A5F2fBA0/info.json
  blockchains/smartchain/assets/0xFa01D3A2B25cdF3b1A6B2361FA07CC71A5F2fBA0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9187 Add Wcomp logo and info
  blockchains/smartchain/assets/0x0b771E34526886d9ffF8E764cF557d1Cb5943C89/info.json
  blockchains/smartchain/assets/0x0b771E34526886d9ffF8E764cF557d1Cb5943C89/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9178 Add Shilling (BEP20)
  blockchains/smartchain/assets/0x643B6ef6306417A0b3FA2813eb5BAf30F5dd8736/info.json
  blockchains/smartchain/assets/0x643B6ef6306417A0b3FA2813eb5BAf30F5dd8736/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9176 Compro token
  blockchains/smartchain/assets/0xF41D6F9680ea216aad62baa7101AF40FEe688046/info.json
  blockchains/smartchain/assets/0xF41D6F9680ea216aad62baa7101AF40FEe688046/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9148 HitChain
  blockchains/smartchain/assets/0x2d4852Ac322d7f5c0B01ff7E1333A2a36a644c3f/info.json
  blockchains/smartchain/assets/0x2d4852Ac322d7f5c0B01ff7E1333A2a36a644c3f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9115 Add Chibi token logo
  blockchains/smartchain/assets/0x504BeAf9B74f5e38B0AC2335c51B8BB6E86F0eC5/info.json
  blockchains/smartchain/assets/0x504BeAf9B74f5e38B0AC2335c51B8BB6E86F0eC5/logo.png
Labels: Payment Status: Paid

#9038 Add Chihua token (BEP20)
  blockchains/smartchain/assets/0x26fF6D16549A00BA8b36ce3159b5277E6e798d18/info.json
  blockchains/smartchain/assets/0x26fF6D16549A00BA8b36ce3159b5277E6e798d18/logo.png
Labels: Payment Status: Paid, Status: On Hold

#9198 Add Aidi Inu (AIDI) logo and info
  blockchains/ethereum/assets/0xdA1E53E088023Fe4D1DC5a418581748f52CBd1b8/info.json
  blockchains/ethereum/assets/0xdA1E53E088023Fe4D1DC5a418581748f52CBd1b8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9175 Updating info and logo for EBSC to Lithium
  blockchains/smartchain/assets/0x01a78db633940579E15e7bDB8EdfEE8ecDeA4522/info.json
  blockchains/smartchain/assets/0x01a78db633940579E15e7bDB8EdfEE8ecDeA4522/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9167 Add INSUR logo and info
  blockchains/ethereum/assets/0x544c42fBB96B39B21DF61cf322b5EDC285EE7429/info.json
  blockchains/ethereum/assets/0x544c42fBB96B39B21DF61cf322b5EDC285EE7429/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9203 Moon Nation Game (MNG) Logo Addition
  blockchains/smartchain/assets/0x5941f87EB62737eC5EBbECab3e373c40fe40566B/info.json
  blockchains/smartchain/assets/0x5941f87EB62737eC5EBbECab3e373c40fe40566B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9161 What is Vacay?
  blockchains/smartchain/assets/0xA3424FB48b9FA2FF8D3366eD91f36b4cDa7cAdd8/info.json
  blockchains/smartchain/assets/0xA3424FB48b9FA2FF8D3366eD91f36b4cDa7cAdd8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9056 Add Chimom token (BEP20)
  blockchains/smartchain/assets/0x17991D0A31c8B6BB2Dd430D51c54f72b77B14697/info.json
  blockchains/smartchain/assets/0x17991D0A31c8B6BB2Dd430D51c54f72b77B14697/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9238 Adding Captain (CAPT) Info and logo
  blockchains/smartchain/assets/0xDf5301b96ceCCb9C2a61505B3A7577111056A4C5/info.json
  blockchains/smartchain/assets/0xDf5301b96ceCCb9C2a61505B3A7577111056A4C5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9236 Add One Token (BEP20)
  blockchains/smartchain/assets/0x01eaedd1BC5F8198D174532Aa13BA150653E0E11/info.json
  blockchains/smartchain/assets/0x01eaedd1BC5F8198D174532Aa13BA150653E0E11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9227 Add SMEGMARS (BEP20)
  blockchains/smartchain/assets/0x74f3a669A8f35010F6f8811c495c0A5F60c5d04d/info.json
  blockchains/smartchain/assets/0x74f3a669A8f35010F6f8811c495c0A5F60c5d04d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9232 Add CatInu logo and info
  blockchains/smartchain/assets/0x7576FdBbE682EAD7dA1f764a07190C1fd16201CD/info.json
  blockchains/smartchain/assets/0x7576FdBbE682EAD7dA1f764a07190C1fd16201CD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9226 Add SiaCashCoin Logo BSC Network
  blockchains/smartchain/assets/0x743370645599ad355c90744d7e9388426Ad52d1c/info.json
  blockchains/smartchain/assets/0x743370645599ad355c90744d7e9388426Ad52d1c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9224 Add Doges logo and info
  blockchains/smartchain/assets/0xcE084e04fc2FE52962aB6E3CC464F80060c1C753/info.json
  blockchains/smartchain/assets/0xcE084e04fc2FE52962aB6E3CC464F80060c1C753/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9221 Add MATR logo and info
  blockchains/smartchain/assets/0x7d6b35ffBCbB8C59c34e4A58D10Bf81654e6Ff6d/info.json
  blockchains/smartchain/assets/0x7d6b35ffBCbB8C59c34e4A58D10Bf81654e6Ff6d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9180 Add TWT logo and info
  blockchains/smartchain/assets/0xf707155AAf4cD8E97D7B298964e84f3221241142/info.json
  blockchains/smartchain/assets/0xf707155AAf4cD8E97D7B298964e84f3221241142/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9248 Add BabyDoge
  blockchains/smartchain/assets/0xc748673057861a797275CD8A068AbB95A902e8de/info.json
  blockchains/smartchain/assets/0xc748673057861a797275CD8A068AbB95A902e8de/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9217 Adding UPDOG token logo to Trustwallet
  blockchains/smartchain/assets/0x400613f184D1207f5C07a67D67040A4e23E92feB/info.json
  blockchains/smartchain/assets/0x400613f184D1207f5C07a67D67040A4e23E92feB/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9126 Add Brigadeiro.Finance Token logo on Trust Wallet. A Charitable Yield-generating token.
  blockchains/smartchain/assets/0x5B69eAbF1c748F590F60906D964158DBA0F53285/info.json
  blockchains/smartchain/assets/0x5B69eAbF1c748F590F60906D964158DBA0F53285/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9218 Add Addax Logo and Info
  blockchains/smartchain/assets/0xce666D0e507C5F2Afe0671Ee29A99cfa97954c48/info.json
  blockchains/smartchain/assets/0xce666D0e507C5F2Afe0671Ee29A99cfa97954c48/logo.png
Labels: Payment Status: Paid

#9185 Update Solanium logo
  blockchains/solana/assets/xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9134 Add SUNT logo and info
  blockchains/smartchain/assets/0x319Bf3bB8aB93658074Be595C4Aa55Cd60380AF7/info.json
  blockchains/smartchain/assets/0x319Bf3bB8aB93658074Be595C4Aa55Cd60380AF7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9062 DartChain
  blockchains/smartchain/assets/0x12B6fFBa41844a51A25E13065d393e54Af0633df/info.json
  blockchains/smartchain/assets/0x12B6fFBa41844a51A25E13065d393e54Af0633df/logo.png
Labels: Payment Status: Paid, Status: On Hold

#9257 Add Fanspel Token
  blockchains/smartchain/assets/0xB0228Eb6c0b49f8265e6E161c3a987eeD7471F42/info.json
  blockchains/smartchain/assets/0xB0228Eb6c0b49f8265e6E161c3a987eeD7471F42/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9191 Add Electra (BEP20)
  blockchains/smartchain/assets/0xe365D0172A39f83660282DEbb6ab7dfaE7bEdA3E/info.json
  blockchains/smartchain/assets/0xe365D0172A39f83660282DEbb6ab7dfaE7bEdA3E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9263 Add UDOGE logo and info
  blockchains/smartchain/assets/0xd1948C71362386453Feb698BC5d902ABba38598F/info.json
  blockchains/smartchain/assets/0xd1948C71362386453Feb698BC5d902ABba38598F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9271 [Internal] Add missing info files for Waves tokens
  blockchains/waves/assets/4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8/info.json
  blockchains/waves/assets/6nSpVyNH7yM69eg446wrQR94ipbbcmZMU1ENPwanC97g/info.json
  blockchains/waves/assets/8inca5fv4xr6KZtRMRPYr7vADfk8fd6G2z1gMoRkbUYS/info.json
  blockchains/waves/assets/9sQutD5HnRvjM1uui5cVC4w9xkMPAfYEV8ymug3Mon2Y/info.json
  blockchains/waves/assets/DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p/info.json
  blockchains/waves/assets/DGbqkzM6Ds5NAF2B3GHYfyZRmWKt7xLYRYcwpMm7D6V4/info.json
  blockchains/waves/assets/DHgwrRvVyqJsepd32YbBqUeDH4GJ1N984X8QoekjgH8J/info.json
  blockchains/waves/assets/DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t/info.json
  blockchains/waves/assets/DhaaqiG8xz8njeBuMtTM2G6avg9Jdhfrxw5onm5GaXx1/info.json
  blockchains/waves/assets/DxFwXxS1r3uZ2QEiSqhe6uoXMJBsz4ShLtHvr4HDzNri/info.json
  blockchains/waves/assets/bPWkA3MNyEr1TuDchWgdpqJZhGhfPXj7dJdr3qiW2kD/info.json
  blockchains/waves/assets/eWeMD5KNeuRaALCAb4uuJKtAvon2JcTyXQyoBMhuN2X/info.json
  script/generic/asset-infos.ts
  script/generic/folders-and-files.ts
Labels: Payment Status: Requested

#9269 SKYrocket - A community driven token
  blockchains/smartchain/assets/0xb3B3C87C7d3FC6411f2d015760c30AF56b02Aa93/info.json
  blockchains/smartchain/assets/0xb3B3C87C7d3FC6411f2d015760c30AF56b02Aa93/logo.png
Labels: Payment Status: Paid

#9276 Add ElonXCoin Logo and Info
  blockchains/smartchain/assets/0xAa7E7C03C6864ccA116D34EC5B7103b030dE5262/info.json
  blockchains/smartchain/assets/0xAa7E7C03C6864ccA116D34EC5B7103b030dE5262/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9270 file charity
  blockchains/smartchain/assets/0x4EaBb20064586DeA07AAaF84d4bA35037854bd44/info.json
  blockchains/smartchain/assets/0x4EaBb20064586DeA07AAaF84d4bA35037854bd44/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9319 Add Orion (BEP20)
  blockchains/smartchain/assets/0x2821989877c0189bf63837f18a2856E30297AF70/info.json
  blockchains/smartchain/assets/0x2821989877c0189bf63837f18a2856E30297AF70/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9312 Add PAWGcoin (BEP20)
  blockchains/smartchain/assets/0x19B60612F9A93359bca835A788A334D4157E675B/info.json
  blockchains/smartchain/assets/0x19B60612F9A93359bca835A788A334D4157E675B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9310 Re-adding Altrucoin Logo and Info Files
  blockchains/smartchain/assets/0xeDAF1F5B8078d4feb4E13c8d5A2c8dE1365be7b6/info.json
  blockchains/smartchain/assets/0xeDAF1F5B8078d4feb4E13c8d5A2c8dE1365be7b6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9300 Add BurnCoin (BEP20)
  blockchains/smartchain/assets/0x6719F89Bb81b357D443eE93Eb254e9dBb590bFbE/info.json
  blockchains/smartchain/assets/0x6719F89Bb81b357D443eE93Eb254e9dBb590bFbE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9296 Add QTM logo and info
  blockchains/smartchain/assets/0x9a99eA92Ed1e0c963078ac5c0867dF85eC6d06B7/info.json
  blockchains/smartchain/assets/0x9a99eA92Ed1e0c963078ac5c0867dF85eC6d06B7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9295 Add ClearMoon (BEP20)
  blockchains/smartchain/assets/0xa178398a3A816d049588cC46D431f5EEC4dd7e96/info.json
  blockchains/smartchain/assets/0xa178398a3A816d049588cC46D431f5EEC4dd7e96/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#8839 Add Legend I, Legend II and Legend III Validators Logo.
  blockchains/binance/validators/assets/bva142lu7y78yk23cdeujduy9g8gqxp7xl3wrz4ska/logo.png
  blockchains/binance/validators/assets/bva16usf4rcvk9dyzpe8n82gq4nw9x5emlhhs2fftr/logo.png
  blockchains/binance/validators/assets/bva1z0g0cg8dkgczr6r8t6khva3srn5mwj8w5tlu7h/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#9289 Add Elephant Money (BEP20)
  blockchains/smartchain/assets/0xE283D0e3B8c102BAdF5E8166B73E02D96d92F688/info.json
  blockchains/smartchain/assets/0xE283D0e3B8c102BAdF5E8166B73E02D96d92F688/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9324 Add Vanity (BEP20)
  blockchains/smartchain/assets/0x2dE161f13Ab594aECD8F2A93e885A08d0ad362c7/info.json
  blockchains/smartchain/assets/0x2dE161f13Ab594aECD8F2A93e885A08d0ad362c7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9286 Adding info.json and logo.png files to repository.
  blockchains/smartchain/assets/0xAA5c91F3df88B8B3863d0899bcA33E70482beD2A/info.json
  blockchains/smartchain/assets/0xAA5c91F3df88B8B3863d0899bcA33E70482beD2A/logo.png
Labels: Payment Status: Paid

#9326 Add Moonarch.app info and logo
  blockchains/smartchain/assets/0xaf96a19c2DD4a0f6B077D9481fCc8C9102FAa141/info.json
  blockchains/smartchain/assets/0xaf96a19c2DD4a0f6B077D9481fCc8C9102FAa141/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9284 Add TENDIE logo and information
  blockchains/smartchain/assets/0x9853A30C69474BeD37595F9B149ad634b5c323d9/info.json
  blockchains/smartchain/assets/0x9853A30C69474BeD37595F9B149ad634b5c323d9/logo.png
Labels: Payment Status: Paid

#9283 Safemarscash Logo request
  blockchains/smartchain/assets/0xd948A2c11626a0EFC25f4e0ceA4986056AC41feD/info.json
  blockchains/smartchain/assets/0xd948A2c11626a0EFC25f4e0ceA4986056AC41feD/logo.png
Labels: Payment Status: Paid

#9220 Add ROTO logo and info
  blockchains/smartchain/assets/0xa9B21900115843D655c4A8A5cb7aDF49e8F4113a/info.json
  blockchains/smartchain/assets/0xa9B21900115843D655c4A8A5cb7aDF49e8F4113a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9341 Add BNB Cash (BEP20)
  blockchains/smartchain/assets/0x101D35140719EB2D07fFA71185f5bfBE31D6A212/info.json
  blockchains/smartchain/assets/0x101D35140719EB2D07fFA71185f5bfBE31D6A212/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9348 Add Logo & Info (BEP20)
  blockchains/smartchain/assets/0x09F956f1E0C28f0b436663D44e0830B7853203d4/info.json
  blockchains/smartchain/assets/0x09F956f1E0C28f0b436663D44e0830B7853203d4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9339 Modify the token logo from PR 9284
  blockchains/smartchain/assets/0x9853A30C69474BeD37595F9B149ad634b5c323d9/info.json
  blockchains/smartchain/assets/0x9853A30C69474BeD37595F9B149ad634b5c323d9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9344 Fix arix1
  blockchains/smartchain/assets/0x976427dd3E55e8a2D5e358DbC54528D1990AADf4/info.json
  blockchains/smartchain/assets/0x976427dd3E55e8a2D5e358DbC54528D1990AADf4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9005 updated logo for Karencoin
  blockchains/smartchain/assets/0xFD42728b76772A82cCaD527E298Dd15A55F4DdD6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9272 Add HyperMeteor (BEP20)
  blockchains/smartchain/assets/0x1fe38769ED41Fe7f47270C78d2F0507b508d06F0/info.json
  blockchains/smartchain/assets/0x1fe38769ED41Fe7f47270C78d2F0507b508d06F0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#7877 Add BRZ Token (BEP20) logo and info
  blockchains/smartchain/assets/0x71be881e9C5d4465B3FfF61e89c6f3651E69B5bb/info.json
  blockchains/smartchain/assets/0x71be881e9C5d4465B3FfF61e89c6f3651E69B5bb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9355 Add CATGIRL token logo and info
  blockchains/smartchain/assets/0x79eBC9A2ce02277A4b5b3A768b1C0A4ed75Bd936/info.json
  blockchains/smartchain/assets/0x79eBC9A2ce02277A4b5b3A768b1C0A4ed75Bd936/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9359 LOGO
  blockchains/smartchain/assets/0x7159B835Cbeb8d01136D6Cc321018b60cCec4B30/info.json
  blockchains/smartchain/assets/0x7159B835Cbeb8d01136D6Cc321018b60cCec4B30/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9351 Add SAFE & SECURE WALLET (BEP20)
  blockchains/smartchain/assets/0xcFDC1e2c7F4B40cFb3632188d6F766309151b7b8/info.json
  blockchains/smartchain/assets/0xcFDC1e2c7F4B40cFb3632188d6F766309151b7b8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9361 XStake LOGO
  blockchains/smartchain/assets/0x64197A553a03b8C9f23D5A15FA9fD91eac4A9538/info.json
  blockchains/smartchain/assets/0x64197A553a03b8C9f23D5A15FA9fD91eac4A9538/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9358 Add XCAD Network (BEP20)
  blockchains/ethereum/assets/0x7659CE147D0e714454073a5dd7003544234b6Aa0/info.json
  blockchains/ethereum/assets/0x7659CE147D0e714454073a5dd7003544234b6Aa0/logo.png
  blockchains/smartchain/assets/0x431e0cD023a32532BF3969CddFc002c00E98429d/info.json
  blockchains/smartchain/assets/0x431e0cD023a32532BF3969CddFc002c00E98429d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9365 Add Coco Swap (BEP20)
  blockchains/smartchain/assets/0x9AA6FC71aed1130DeE06a91A487BF5eA481dE80D/info.json
  blockchains/smartchain/assets/0x9AA6FC71aed1130DeE06a91A487BF5eA481dE80D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9364 Add TRONPAD.network (BEP20)
  blockchains/smartchain/assets/0x1Bf7AedeC439D6BFE38f8f9b20CF3dc99e3571C4/info.json
  blockchains/smartchain/assets/0x1Bf7AedeC439D6BFE38f8f9b20CF3dc99e3571C4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9072 Change info.json for Hamster
  blockchains/smartchain/assets/0xb7b36CA86685Af52186f1f9394e91d115A9Da654/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#8117 Upload Tokyo Inu to trust wallet
  blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/info.json
  blockchains/smartchain/assets/0xE405f6Ae74ad3efD31C23A40CE23b3D3A3B95FB9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9390 Add Xiasi Inu (BEP20)
  blockchains/smartchain/assets/0x0e20E3216EA172fcf9eAa19723b119e090fD353f/info.json
  blockchains/smartchain/assets/0x0e20E3216EA172fcf9eAa19723b119e090fD353f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9388 ADD SUGAR TOKEN - logo and info
  blockchains/smartchain/assets/0x41AA9F842AF935cC71252C0dE4BFF13F821546b8/info.json
  blockchains/smartchain/assets/0x41AA9F842AF935cC71252C0dE4BFF13F821546b8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9382 Add LUCK-INU (BEP20)
  blockchains/smartchain/assets/0xB2f7e860E302b18819970ceA41BcFc7349834e81/info.json
  blockchains/smartchain/assets/0xB2f7e860E302b18819970ceA41BcFc7349834e81/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9381 ADD IRONYMAN LOGO AND INFO
  blockchains/smartchain/assets/0x7f05907CDe5C540bE2e572FDD488994ee15d67a3/info.json
  blockchains/smartchain/assets/0x7f05907CDe5C540bE2e572FDD488994ee15d67a3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9376 KaikenCoin Logo + Info
  blockchains/smartchain/assets/0x43E061e3061241998d1C50DC27E5488696c23410/info.json
  blockchains/smartchain/assets/0x43E061e3061241998d1C50DC27E5488696c23410/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9399 Add BNU logo and info
  blockchains/smartchain/assets/0x4954e0062E0A7668A2FE3df924cD20E6440a7b77/info.json
  blockchains/smartchain/assets/0x4954e0062E0A7668A2FE3df924cD20E6440a7b77/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9398 Add EPRO
  blockchains/ethereum/assets/0xBa630d3BA20502BA07975B15c719BEECc8e4EBB0/info.json
  blockchains/ethereum/assets/0xBa630d3BA20502BA07975B15c719BEECc8e4EBB0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9374 Add SafeFinance $SFE logo and info
  blockchains/smartchain/assets/0x7983c8E6D09da2156Ec7E56fddDa91a517561781/info.json
  blockchains/smartchain/assets/0x7983c8E6D09da2156Ec7E56fddDa91a517561781/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9367 Add PinkPanda (BEP20)
  blockchains/smartchain/assets/0x631E1e455019c359b939fE214EDC761d36bF6aD6/info.json
  blockchains/smartchain/assets/0x631E1e455019c359b939fE214EDC761d36bF6aD6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9320 Add Saint Token logo and info
  blockchains/smartchain/assets/0x3Da67Ae8fcF0B733d799f65B2695d650eA11112A/info.json
  blockchains/smartchain/assets/0x3Da67Ae8fcF0B733d799f65B2695d650eA11112A/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9222 ADD AP LOGO and INFO
  blockchains/smartchain/assets/0xD919C54AdeF039727038De350215627383c4ccC4/info.json
  blockchains/smartchain/assets/0xD919C54AdeF039727038De350215627383c4ccC4/logo.png
Labels: Payment Status: Paid

#5716 Add EXF logo and info
  blockchains/smartchain/assets/0x6306e883493824Ccf606D90E25F68a28e47b98a3/info.json
  blockchains/smartchain/assets/0x6306e883493824Ccf606D90E25F68a28e47b98a3/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#9414 Add OCAT logo and info
  blockchains/smartchain/assets/0x7128E52cA302c5f5BeEB801B6aD373fDeBE3dc5E/info.json
  blockchains/smartchain/assets/0x7128E52cA302c5f5BeEB801B6aD373fDeBE3dc5E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9413 add BEP20/ERC20 MOMA logo and info
  blockchains/ethereum/assets/0xbd1848e1491d4308Ad18287A745DD4DB2A4BD55B/info.json
  blockchains/ethereum/assets/0xbd1848e1491d4308Ad18287A745DD4DB2A4BD55B/logo.png
  blockchains/smartchain/assets/0xB72842D6F5feDf91D22d56202802Bb9A79C6322E/info.json
  blockchains/smartchain/assets/0xB72842D6F5feDf91D22d56202802Bb9A79C6322E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9421 CARAMEL LOGO UPLOAD
  blockchains/smartchain/assets/0x7ce1e651374ec5324e6f37c4ff312D53428F0D50/info.json
  blockchains/smartchain/assets/0x7ce1e651374ec5324e6f37c4ff312D53428F0D50/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9407 Add AXO Info and Logo
  blockchains/smartchain/assets/0x52dCF5BEdc061604D8C592B0079A0FF2ceA22eB7/info.json
  blockchains/smartchain/assets/0x52dCF5BEdc061604D8C592B0079A0FF2ceA22eB7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9434 [Internal] RUNE decimals fix
  blockchains/thorchain/info/info.json
Labels: Payment Status: Requested

#9443 Add Bevo Token
  blockchains/smartchain/assets/0xc6Cb12df4520B7Bf83f64C79c585b8462e18B6Aa/info.json
  blockchains/smartchain/assets/0xc6Cb12df4520B7Bf83f64C79c585b8462e18B6Aa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9438 Request to add Sportemon-Go (BEP20)
  blockchains/smartchain/assets/0xe5D46cC0Fd592804B36F9dc6D2ed7D4D149EBd6F/info.json
  blockchains/smartchain/assets/0xe5D46cC0Fd592804B36F9dc6D2ed7D4D149EBd6F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9439 Add LOGO & INFO (BEP20)
  blockchains/smartchain/assets/0x00e7daf0E5FD1F5331c92d09e3C825A8e4Fc6515/info.json
  blockchains/smartchain/assets/0x00e7daf0E5FD1F5331c92d09e3C825A8e4Fc6515/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9437 Add FTV logo and info
  blockchains/smartchain/assets/0xfD2CEaF2A104b2817D8D3252801c52AF6B8Dae77/info.json
  blockchains/smartchain/assets/0xfD2CEaF2A104b2817D8D3252801c52AF6B8Dae77/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9436 Add Logo & Info
  blockchains/smartchain/assets/0x10B7Be52636882d7ECa1611144A9Df7642F95B5D/info.json
  blockchains/smartchain/assets/0x10B7Be52636882d7ECa1611144A9Df7642F95B5D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9435 Add SUPERDOGE Logo and Info (BEP20)
  blockchains/smartchain/assets/0x7895B3DE4169635da889Ca842740748136Ac7B11/info.json
  blockchains/smartchain/assets/0x7895B3DE4169635da889Ca842740748136Ac7B11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9432 Add Logo & Info
  blockchains/smartchain/assets/0x47dd8AEF9015d8e5a91d5B9062828BBCcd5fEFcc/info.json
  blockchains/smartchain/assets/0x47dd8AEF9015d8e5a91d5B9062828BBCcd5fEFcc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9416 Kindly Add SwiftMoon Info and Logo
  blockchains/smartchain/assets/0xB47D8D9CD415DAE40E364b140ae6aF186e2332f4/info.json
  blockchains/smartchain/assets/0xB47D8D9CD415DAE40E364b140ae6aF186e2332f4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9411 Add HPR logo and info
  blockchains/smartchain/assets/0xcB368FDb5264a6c2baE1b270EC6A3Ad3029C64C7/info.json
  blockchains/smartchain/assets/0xcB368FDb5264a6c2baE1b270EC6A3Ad3029C64C7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9410 Add SWW logo and info
  blockchains/smartchain/assets/0x5b8c1315D2a151355EA3BE9d2Cbdc4425648dCAb/info.json
  blockchains/smartchain/assets/0x5b8c1315D2a151355EA3BE9d2Cbdc4425648dCAb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9409 add SPR logo and info
  blockchains/smartchain/assets/0xE02018491ADf33B3Ef3001a0e2F2139821dA8d2F/info.json
  blockchains/smartchain/assets/0xE02018491ADf33B3Ef3001a0e2F2139821dA8d2F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9408 Add MARS logo and info
  blockchains/smartchain/assets/0x2d2bB6cC040010583F16Bb1c5afEE129ed13B532/info.json
  blockchains/smartchain/assets/0x2d2bB6cC040010583F16Bb1c5afEE129ed13B532/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9406 Add Elons logo and info
  blockchains/smartchain/assets/0xaF6B24d341cB5ec258e93aBe929a0326fC98eAF6/info.json
  blockchains/smartchain/assets/0xaF6B24d341cB5ec258e93aBe929a0326fC98eAF6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9100 Add Hunny Token logo
  blockchains/smartchain/assets/0x565b72163f17849832A692A3c5928cc502f46D69/info.json
  blockchains/smartchain/assets/0x565b72163f17849832A692A3c5928cc502f46D69/logo.png
Labels: Payment Status: Paid

#9460 Add Story
  blockchains/smartchain/assets/0xa1bc3505BB77735cE17484d00FfdE8C6eF53707b/info.json
  blockchains/smartchain/assets/0xa1bc3505BB77735cE17484d00FfdE8C6eF53707b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9454 $PAL token Logo submission to Trustwallet
  blockchains/smartchain/assets/0x569641e97cF794FEDC6277B490337654beA58942/info.json
  blockchains/smartchain/assets/0x569641e97cF794FEDC6277B490337654beA58942/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9483 Add KAINU (BEP20)
  blockchains/smartchain/assets/0xe26DFa937315592011fA90baF99B164f9F61bd08/info.json
  blockchains/smartchain/assets/0xe26DFa937315592011fA90baF99B164f9F61bd08/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9482 Add logo and info for FTXFUND
  blockchains/smartchain/assets/0xd90F0846b9D0F371b35a9Fe89102C306458AA56F/info.json
  blockchains/smartchain/assets/0xd90F0846b9D0F371b35a9Fe89102C306458AA56F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9496 Add files via upload , we need to update our old contract icon
  blockchains/smartchain/assets/0x62c2A6f57a65e1e4b1d9e31b3e3511c8C36841a8/info.json
  blockchains/smartchain/assets/0x62c2A6f57a65e1e4b1d9e31b3e3511c8C36841a8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9497 Add Maxima (BEP20)
  blockchains/smartchain/assets/0x283FA53f085F520D16a43e7c33180ff99E407b26/info.json
  blockchains/smartchain/assets/0x283FA53f085F520D16a43e7c33180ff99E407b26/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9495 Add Zabaku Inu (BEP20)
  blockchains/smartchain/assets/0x1e5F009d4f8cA44b5FcC4963dD301Da82b4eed09/info.json
  blockchains/smartchain/assets/0x1e5F009d4f8cA44b5FcC4963dD301Da82b4eed09/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9490 Info and logo for token MoonGhost
  blockchains/smartchain/assets/0xf818D092BeAF21BEaFe6aCDd8230BD5F7b861D9C/info.json
  blockchains/smartchain/assets/0xf818D092BeAF21BEaFe6aCDd8230BD5F7b861D9C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9458 submit BAT Token logo
  blockchains/smartchain/assets/0xe76804b43F17FC41F226d63Fd2A676DF409D4678/info.json
  blockchains/smartchain/assets/0xe76804b43F17FC41F226d63Fd2A676DF409D4678/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9462 Shield Token: 0x6884ae24deb7e8fa80dc9d0d56c91d78a250e9b1
  blockchains/smartchain/assets/0x6884AE24dEB7E8fa80dc9D0d56C91d78a250E9b1/info.json
  blockchains/smartchain/assets/0x6884AE24dEB7E8fa80dc9D0d56C91d78a250E9b1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9418 add BTCX logo and info in TWT
  blockchains/smartchain/assets/0xCaC9881a8EeCc6e98Ff3E681Ab497F263Fa88437/info.json
  blockchains/smartchain/assets/0xCaC9881a8EeCc6e98Ff3E681Ab497F263Fa88437/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9522 Add Aku The Bodyguard (BEP20)
  blockchains/smartchain/assets/0x78473c046C43b40eBf162d597D07Df3Fd9584923/info.json
  blockchains/smartchain/assets/0x78473c046C43b40eBf162d597D07Df3Fd9584923/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9520 add logo and Icc token info
  blockchains/smartchain/assets/0x447Ad4EF9293067E9FCbBBcd794BBD0FA6D6c470/info.json
  blockchains/smartchain/assets/0x447Ad4EF9293067E9FCbBBcd794BBD0FA6D6c470/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9499 Add Polarium.Finance (BEP20)
  blockchains/smartchain/assets/0xD983A29d0E966a3C51b540085314057D3bb4A227/info.json
  blockchains/smartchain/assets/0xD983A29d0E966a3C51b540085314057D3bb4A227/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9575 Add BitBook (BEP20)
  blockchains/smartchain/assets/0xD48474E7444727bF500a32D5AbE01943f3A59A64/info.json
  blockchains/smartchain/assets/0xD48474E7444727bF500a32D5AbE01943f3A59A64/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9565 Add Micro Bitcoin Token
  blockchains/smartchain/assets/0xe77011ed703ed06927dBd78e60c549baBAbF913e/info.json
  blockchains/smartchain/assets/0xe77011ed703ed06927dBd78e60c549baBAbF913e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9564 [trustwallet/assets] logo size updates (#9082) fee payed
  blockchains/smartchain/assets/0x5d6CDf1b7F7C35EAE688E4C563b6f16eeAC2cB6b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9562 Add Jinchuriki BEP20
  blockchains/smartchain/assets/0x238CC5438da55F1679E8509bddFaF267f2fAAF30/info.json
  blockchains/smartchain/assets/0x238CC5438da55F1679E8509bddFaF267f2fAAF30/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9581 [Internal] PR fee change
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#9546 Add TETRA PAY (BEP20)
  blockchains/smartchain/assets/0x1C9257e55318eb9B472ed45ef5C55ccD941538f0/info.json
  blockchains/smartchain/assets/0x1C9257e55318eb9B472ed45ef5C55ccD941538f0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9539 adding KETCHUP
  blockchains/smartchain/assets/0x714a84632Ed7edBbBFEb62DACf02DB4BeB4C69D9/info.json
  blockchains/smartchain/assets/0x714a84632Ed7edBbBFEb62DACf02DB4BeB4C69D9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9500 Update BEVO Token logo (Payment needed?)
  blockchains/smartchain/assets/0xc6Cb12df4520B7Bf83f64C79c585b8462e18B6Aa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9404 Add files via upload
  blockchains/ethereum/assets/0x348B7f3106B5Da47405332534d06069fF9CE4d1B/info.json
  blockchains/ethereum/assets/0x348B7f3106B5Da47405332534d06069fF9CE4d1B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9588 update yooshi token logo
  blockchains/smartchain/assets/0x02fF5065692783374947393723dbA9599e59F591/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9599 Add TeamTreesToken (BEP20)
  blockchains/smartchain/assets/0xe1F8C6ce0D69CbEB67c6bc3685e52C96291394a8/info.json
  blockchains/smartchain/assets/0xe1F8C6ce0D69CbEB67c6bc3685e52C96291394a8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9484 Fixing $MERL token on trust swap
  blockchains/smartchain/assets/0xDA360309C59CB8C434b28A91b823344a96444278/info.json
  blockchains/smartchain/assets/0xDA360309C59CB8C434b28A91b823344a96444278/logo.png
Labels: Payment Status: Paid

#9620 Add Logo and Info
  blockchains/smartchain/assets/0xA38f6b2848cAE0b61DDd3EC36560801e7eDA2b62/info.json
  blockchains/smartchain/assets/0xA38f6b2848cAE0b61DDd3EC36560801e7eDA2b62/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9617 Add Sushiba token to trust wallet
  blockchains/smartchain/assets/0xa96658cd0D04a8fdCDc30D1156CC65BbFC7591eD/info.json
  blockchains/smartchain/assets/0xa96658cd0D04a8fdCDc30D1156CC65BbFC7591eD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9615 Add MLN logo and info
  blockchains/smartchain/assets/0x8034Aa1EBB42a4E2110E91666497198e977c8d81/info.json
  blockchains/smartchain/assets/0x8034Aa1EBB42a4E2110E91666497198e977c8d81/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#9613 Add Parallel Universe (BEP20)
  blockchains/smartchain/assets/0x11ed1d93bdD3Ee180CA724AC82F911663f0daFB2/info.json
  blockchains/smartchain/assets/0x11ed1d93bdD3Ee180CA724AC82F911663f0daFB2/logo.png
Labels: Payment Status: Requested
