Repository trustwallet/assets, pull requests merged in 2021-08, with the labels that each got.

#12361 Add BabyDB Bep20
  blockchains/smartchain/assets/0x6d9fB3332f62Fc044d5075feEeA597A92F1ce0AD/info.json
  blockchains/smartchain/assets/0x6d9fB3332f62Fc044d5075feEeA597A92F1ce0AD/logo.png
Labels: Payment Status: Paid

#12348 Request to add RedFEG
  blockchains/smartchain/assets/0x25574Cad6F03FFacD9D08b288e8D5d88997fb2f3/info.json
  blockchains/smartchain/assets/0x25574Cad6F03FFacD9D08b288e8D5d88997fb2f3/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12405 Add PearZap (Polygon)
  blockchains/polygon/allowlist.json
  blockchains/polygon/assets/0xc8bcb58caEf1bE972C0B638B1dD8B0748Fdc8A44/info.json
  blockchains/polygon/assets/0xc8bcb58caEf1bE972C0B638B1dD8B0748Fdc8A44/logo.png
Labels: Payment Status: Paid

#12395 Update WOW contract and description
  blockchains/smartchain/assets/0x47e7dd5fA9BBd280C5422E5106b1Da444344c206/info.json
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12415 Add World of Waves (BEP20)
  blockchains/smartchain/assets/0x31353E2826Cc4402735E55a175a75CE2569B4226/info.json
  blockchains/smartchain/assets/0x31353E2826Cc4402735E55a175a75CE2569B4226/logo.png
Labels: Payment Status: Paid

#12428 add PWAR info & logo (BEP20)
  blockchains/smartchain/assets/0x16153214E683018D5aA318864c8e692b66E16778/info.json
  blockchains/smartchain/assets/0x16153214E683018D5aA318864c8e692b66E16778/logo.png
Labels: Payment Status: Paid

#12416 Add LiveTrade (BEP20)
  blockchains/smartchain/assets/0x0f7cd24E31293b162DcF6211C6AC5bD8EfCB81f4/info.json
  blockchains/smartchain/assets/0x0f7cd24E31293b162DcF6211C6AC5bD8EfCB81f4/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12382 Add DEXIT (BEP20)
  blockchains/smartchain/assets/0x2B2fF80c489dad868318a19FD6F258889a026da5/info.json
  blockchains/smartchain/assets/0x2B2fF80c489dad868318a19FD6F258889a026da5/logo.png
Labels: Payment Status: Paid

#12275 Add finance.vote (ERC20)
  blockchains/ethereum/assets/0x45080a6531d671DDFf20DB42f93792a489685e32/info.json
  blockchains/ethereum/assets/0x45080a6531d671DDFf20DB42f93792a489685e32/logo.png
Labels: Payment Status: Paid, Status: On Hold

#12462 add_BEP20_POTS
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x3Fcca8648651E5b974DD6d3e50F61567779772A8/info.json
  blockchains/smartchain/assets/0x3Fcca8648651E5b974DD6d3e50F61567779772A8/logo.png
Labels: Payment Status: Requested

#12472 Update ChainLink logo
  blockchains/ethereum/assets/0x514910771AF9Ca656af840dff83E8264EcF986CA/logo.png
Labels: Payment Status: Requested

#12454 Update WHACKD token informations
  blockchains/ethereum/assets/0xCF8335727B776d190f9D15a54E6B9B9348439eEE/info.json
  blockchains/ethereum/assets/0xCF8335727B776d190f9D15a54E6B9B9348439eEE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12450 Add CybrrrDOGE Logo and Info
  blockchains/smartchain/assets/0xecc62bd353EDd64Ed31595DbC4C92801aF1e2af0/info.json
  blockchains/smartchain/assets/0xecc62bd353EDd64Ed31595DbC4C92801aF1e2af0/logo.png
Labels: Payment Status: Paid

#12431 Add CHECOIN logo and info
  blockchains/smartchain/assets/0x54626300818E5C5b44Db0fcf45Ba4943CA89A9e2/info.json
  blockchains/smartchain/assets/0x54626300818E5C5b44Db0fcf45Ba4943CA89A9e2/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12360 DISC Token Information & Icon
  blockchains/smartchain/assets/0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569/info.json
  blockchains/smartchain/assets/0x2BCDCf1ef1320Fc5F9a71CA0BD1504D6125F7569/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#11955 Add CR Coin (CRC) (ERC20)
  blockchains/ethereum/assets/0xFB19C03a02a519a44542343803F3D42578CBc243/info.json
  blockchains/ethereum/assets/0xFB19C03a02a519a44542343803F3D42578CBc243/logo.png
Labels: Payment Status: Paid

#11863 Add KCCPAD (BEP20)
  blockchains/smartchain/assets/0x11582Ef4642B1e7F0a023804B497656E2663bC9B/info.json
  blockchains/smartchain/assets/0x11582Ef4642B1e7F0a023804B497656E2663bC9B/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12498 Add NUTS Gaming (BEP20)
  blockchains/smartchain/assets/0xe6E6A022b4d4e538Ca0a1f47941CbBF3F9cc1467/info.json
  blockchains/smartchain/assets/0xe6E6A022b4d4e538Ca0a1f47941CbBF3F9cc1467/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12532 [Internal] Update dependencies
  package-lock.json
  package.json
Labels: Payment Status: Requested

#12404 Add Crosswallet (BEP20)
  blockchains/smartchain/assets/0x5A726a26eDB0Df8Fd55f03cc30aF8A7cEa81e78D/info.json
  blockchains/smartchain/assets/0x5A726a26eDB0Df8Fd55f03cc30aF8A7cEa81e78D/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#12402 Add BSCView (BEP20)
  blockchains/smartchain/assets/0xbB3837Fa11d4B789717C8f622Ec4f6eee5375C49/info.json
  blockchains/smartchain/assets/0xbB3837Fa11d4B789717C8f622Ec4f6eee5375C49/logo.png
Labels: Payment Status: Paid, Status: On Hold

#12518 WIFEDOGE Info for token WifeDoge
  blockchains/smartchain/assets/0x07B36F2549291d320132712a1E64d3826B1FB4D7/info.json
  blockchains/smartchain/assets/0x07B36F2549291d320132712a1E64d3826B1FB4D7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12535 Add aqua icon
  blockchains/smartchain/assets/0x72B7D61E8fC8cF971960DD9cfA59B8C829D91991/info.json
  blockchains/smartchain/assets/0x72B7D61E8fC8cF971960DD9cfA59B8C829D91991/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12426 add BEP20 FOR
  blockchains/smartchain/assets/0x658A109C5900BC6d2357c87549B651670E5b0539/info.json
  blockchains/smartchain/assets/0x658A109C5900BC6d2357c87549B651670E5b0539/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12519 Update Asset Logos for RIO, RST assets
  blockchains/ethereum/assets/0x1a76bfFD6D1FC1660e1d0E0552Fde51ddbB120CF/logo.png
  blockchains/ethereum/assets/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12424 Add Pup Doge (BEP20)
  blockchains/smartchain/assets/0x3220CCbbC29d727Bde85b7333D31b21e0d6bC6F4/info.json
  blockchains/smartchain/assets/0x3220CCbbC29d727Bde85b7333D31b21e0d6bC6F4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12558 Add ARENA to Trust Wallet
  blockchains/smartchain/assets/0x2A17Dc11a1828725cdB318E0036ACF12727d27a2/info.json
  blockchains/smartchain/assets/0x2A17Dc11a1828725cdB318E0036ACF12727d27a2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12564 Add BabyPig logo and info
  blockchains/smartchain/assets/0x7b0b4C304B9149B692c1Acbc9dB4F4a1c17B2B91/info.json
  blockchains/smartchain/assets/0x7b0b4C304B9149B692c1Acbc9dB4F4a1c17B2B91/logo.png
Labels: Payment Status: Paid

#12565 Add KWD (BEP20)
  blockchains/smartchain/assets/0x65453110319e9ce742dd146beFfaC2A5eE655e7E/info.json
  blockchains/smartchain/assets/0x65453110319e9ce742dd146beFfaC2A5eE655e7E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12584 add MicroSHIBA info and logo
  blockchains/smartchain/assets/0xb78e41AE7fc8121978168557bB096e1A858be2Ea/info.json
  blockchains/smartchain/assets/0xb78e41AE7fc8121978168557bB096e1A858be2Ea/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12505 Add DOOR Token logo and information.
  blockchains/ethereum/assets/0x7D48FBe0A877bB1f511fcf9B57F12420C75841e9/info.json
  blockchains/ethereum/assets/0x7D48FBe0A877bB1f511fcf9B57F12420C75841e9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12553 Add DSCPL logo and info
  blockchains/smartchain/assets/0xdECE0F6864c1511369ae2c30B90Db9f5fe92832c/info.json
  blockchains/smartchain/assets/0xdECE0F6864c1511369ae2c30B90Db9f5fe92832c/logo.png
Labels: Payment Status: Paid

#12521 Add NanoDogeCoin Logo & Info
  blockchains/smartchain/assets/0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE/info.json
  blockchains/smartchain/assets/0x1B41821625d8CFAd21cd56491DACD57ECaCc83dE/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12523 Add SAFEARN BEP20 Token
  blockchains/smartchain/assets/0x099f551eA3cb85707cAc6ac507cBc36C96eC64Ff/info.json
  blockchains/smartchain/assets/0x099f551eA3cb85707cAc6ac507cBc36C96eC64Ff/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12460 Simargl Token
  blockchains/smartchain/assets/0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1/info.json
  blockchains/smartchain/assets/0xBDAC5C8bc3FF38083437bB712D55b668F44F6DF1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12193 Info for token Baby Bitcoin (BBTC)
  blockchains/smartchain/assets/0x5B0Dfe077B16479715C9838eb644892008abbFe6/info.json
  blockchains/smartchain/assets/0x5B0Dfe077B16479715C9838eb644892008abbFe6/logo.png
Labels: Status: On Hold, Payment Status: Paid

#12604 Logo change
  blockchains/smartchain/assets/0x0b3f42481C228F70756DbFA0309d3ddC2a5e0F6a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12552 Add HECO <> ThunderCore bridged tokens on ThunderCore network - TT-HT, TT-HUSD
  blockchains/thundertoken/allowlist.json
  blockchains/thundertoken/assets/0x0212b1F75503413b01A98158434c4570FB6e808c/info.json
  blockchains/thundertoken/assets/0x0212b1F75503413b01A98158434c4570FB6e808c/logo.png
  blockchains/thundertoken/assets/0x18fB0A62f207A2a082cA60aA78F47a1af4985190/info.json
  blockchains/thundertoken/assets/0x22e89898A04eaf43379BeB70bf4E38b1faf8A31e/info.json
  blockchains/thundertoken/assets/0x2b31e3b88847f03c1335E99A0d1274A2c72059DE/info.json
  blockchains/thundertoken/assets/0x4f3C8E20942461e2c3Bdd8311AC57B0c222f2b82/info.json
  blockchains/thundertoken/assets/0x6576Bb918709906DcbFDCeae4bB1e6df7C8a1077/info.json
  blockchains/thundertoken/assets/0x8EF1A1E0671Aa44852f4d87105eF482470bB3e69/info.json
  blockchains/thundertoken/assets/0xBEB0131D95AC3F03fd15894D0aDE5DBf7451d171/info.json
  blockchains/thundertoken/assets/0xFd6Ec3E37F112bD30BbD726E7b0E73000CC2B98d/info.json
  blockchains/thundertoken/assets/0xFd6Ec3E37F112bD30BbD726E7b0E73000CC2B98d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#11465 Dogecoin 2.0 Logo
  blockchains/smartchain/assets/0x3780E00D4c60887AF38345cCd44f7617dBFB10A0/info.json
  blockchains/smartchain/assets/0x3780E00D4c60887AF38345cCd44f7617dBFB10A0/logo.png
Labels: Payment Status: Paid

#12576 Add Fibo Token (BEP20)
  blockchains/smartchain/assets/0x5067c6e9E6c443372f2E62946273ABbF3Cc2f2B3/info.json
  blockchains/smartchain/assets/0x5067c6e9E6c443372f2E62946273ABbF3Cc2f2B3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12571 Add StarLink $STARL (ERC20)
  blockchains/ethereum/assets/0x8E6cd950Ad6ba651F6DD608Dc70e5886B1AA6B24/info.json
  blockchains/ethereum/assets/0x8E6cd950Ad6ba651F6DD608Dc70e5886B1AA6B24/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12611 Add MiniShibaInu (BEP20)
  blockchains/smartchain/assets/0xEB35aCBD23CF9D1C13D276815B9969eFfC5c878f/info.json
  blockchains/smartchain/assets/0xEB35aCBD23CF9D1C13D276815B9969eFfC5c878f/logo.png
Labels: Payment Status: Paid

#12476 Add LZ token to Trust Wallet
  blockchains/smartchain/assets/0x3B78458981eB7260d1f781cb8be2CaAC7027DbE2/info.json
  blockchains/smartchain/assets/0x3B78458981eB7260d1f781cb8be2CaAC7027DbE2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12617 Add Floki Inu (BEP20)
  blockchains/smartchain/assets/0x2B3F34e9D4b127797CE6244Ea341a83733ddd6E4/info.json
  blockchains/smartchain/assets/0x2B3F34e9D4b127797CE6244Ea341a83733ddd6E4/logo.png
Labels: Payment Status: Paid

#11439 Add DCB token info and logo
  blockchains/smartchain/assets/0xEAc9873291dDAcA754EA5642114151f3035c67A2/info.json
  blockchains/smartchain/assets/0xEAc9873291dDAcA754EA5642114151f3035c67A2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12641 Add WhenLambo (BEP20)
  blockchains/smartchain/assets/0xE03495fCa9e644d55B65c30ed9fdC3321C260126/info.json
  blockchains/smartchain/assets/0xE03495fCa9e644d55B65c30ed9fdC3321C260126/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12650 upload logo
  blockchains/smartchain/assets/0x154ECeB42679ac155EeF18820dE2Be75699263A8/info.json
  blockchains/smartchain/assets/0x154ECeB42679ac155EeF18820dE2Be75699263A8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12635 Update BLANK token after swap
  blockchains/ethereum/assets/0x41A3Dba3D677E573636BA691a70ff2D606c29666/info.json
  blockchains/ethereum/assets/0x41A3Dba3D677E573636BA691a70ff2D606c29666/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12633 Update logo and info
  blockchains/smartchain/assets/0xce4A4A15FcCD532eAd67BE3ECf7e6122c61D06bb/info.json
  blockchains/smartchain/assets/0xce4A4A15FcCD532eAd67BE3ECf7e6122c61D06bb/logo.png
Labels: Payment Status: Paid

#12651 Add Vention (BEP20)
  blockchains/smartchain/assets/0x2f053e33bd590830858161d42C67e9E8A9390019/info.json
  blockchains/smartchain/assets/0x2f053e33bd590830858161d42C67e9E8A9390019/logo.png
Labels: Payment Status: Paid

#12661 Add Zooshi (BEP20)
  blockchains/smartchain/assets/0xA060E0c0588D26CabA4a0009513337aCE50752dd/info.json
  blockchains/smartchain/assets/0xA060E0c0588D26CabA4a0009513337aCE50752dd/logo.png
Labels: Payment Status: Paid

#12684 resubmit PR#12630
  blockchains/tezos/validators/assets/tz1YiuvpfeVAHbnU8akcWErNfQGFHNQ7F45z/logo.png
  blockchains/tezos/validators/list.json
Labels: Payment Status: Requested

#12680 Add Vabble Token (VAB)
  blockchains/ethereum/assets/0xe7aE6D0C56CACaf007b7e4d312f9af686a9E9a04/info.json
  blockchains/ethereum/assets/0xe7aE6D0C56CACaf007b7e4d312f9af686a9E9a04/logo.png
Labels: Payment Status: Paid

#12620 Add NAFTY (BEP20)
  blockchains/smartchain/assets/0x18C5fAC26C5d8b859b3A83f0f167D8924098d28a/info.json
  blockchains/smartchain/assets/0x18C5fAC26C5d8b859b3A83f0f167D8924098d28a/logo.png
Labels: Payment Status: Paid

#12715 Add Bimp.Finance (BEP20)
  blockchains/smartchain/assets/0x8855cFbA493D8A22F924a5CE1B06EFBceA68FFeC/info.json
  blockchains/smartchain/assets/0x8855cFbA493D8A22F924a5CE1B06EFBceA68FFeC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12727 [Internal] Enforce decimals=8 for BEP2 tokens
  script/generic/asset-infos.ts
Labels: Payment Status: Requested

#12709 Add BURNACE (BEP20)
  blockchains/smartchain/assets/0x9A624b4190F38c888BbF7F845f14198f9C951de7/info.json
  blockchains/smartchain/assets/0x9A624b4190F38c888BbF7F845f14198f9C951de7/logo.png
Labels: Payment Status: Paid

#12636 Add POLO token to TrustWallet
  blockchains/smartchain/assets/0xb28a7f8f5328FafFDd862985177583c2Bb71E016/info.json
  blockchains/smartchain/assets/0xb28a7f8f5328FafFDd862985177583c2Bb71E016/logo.png
Labels: Payment Status: Paid

#12742 Add Position (BEP20) - Already Paid by #12441
  blockchains/smartchain/assets/0x5CA42204cDaa70d5c773946e69dE942b85CA6706/info.json
  blockchains/smartchain/assets/0x5CA42204cDaa70d5c773946e69dE942b85CA6706/logo.png
Labels: Payment Status: Paid

#12740 Adding Impossible Finance Assets
  blockchains/ethereum/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/info.json
  blockchains/ethereum/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/logo.png
  blockchains/ethereum/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/info.json
  blockchains/ethereum/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/logo.png
  blockchains/polygon/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/info.json
  blockchains/polygon/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/logo.png
  blockchains/polygon/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/info.json
  blockchains/polygon/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/logo.png
  blockchains/smartchain/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/info.json
  blockchains/smartchain/assets/0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89/logo.png
  blockchains/smartchain/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/info.json
  blockchains/smartchain/assets/0xB0e1fc65C1a741b4662B813eB787d369b8614Af1/logo.png
Labels: Payment Status: Paid

#12737 Adding TITS
  blockchains/smartchain/assets/0x534E99ff924038eB4a3aa7fac791D1eF8BB08b37/info.json
  blockchains/smartchain/assets/0x534E99ff924038eB4a3aa7fac791D1eF8BB08b37/logo.png
Labels: Payment Status: Paid

#12746 Add Bitrise Token (BEP20)
  blockchains/smartchain/assets/0x8FFf93E810a2eDaaFc326eDEE51071DA9d398E83/info.json
  blockchains/smartchain/assets/0x8FFf93E810a2eDaaFc326eDEE51071DA9d398E83/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12598 Add BabyPooCoin (BEP20)
  blockchains/smartchain/assets/0x38895e0b3E7cD13C45BD4E93aF5a402604B762E3/info.json
  blockchains/smartchain/assets/0x38895e0b3E7cD13C45BD4E93aF5a402604B762E3/logo.png
Labels: Status: On Hold, Payment Status: Paid

#12748 Add files via upload - (Payment Done On #12163)
  blockchains/smartchain/assets/0x5788105375ecF7F675C29e822FD85fCd84d4cd86/info.json
  blockchains/smartchain/assets/0x5788105375ecF7F675C29e822FD85fCd84d4cd86/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12755 Add Corgiswap (BEP20)
  blockchains/smartchain/assets/0x2a2cD8b1F69EB9dda5d703b3498d97080C2F194F/info.json
  blockchains/smartchain/assets/0x2a2cD8b1F69EB9dda5d703b3498d97080C2F194F/logo.png
Labels: Payment Status: Paid

#12760 feature: add ricefarm logo and token info
  blockchains/smartchain/assets/0xC4eEFF5aab678C3FF32362D80946A3f5De4a1861/info.json
  blockchains/smartchain/assets/0xC4eEFF5aab678C3FF32362D80946A3f5De4a1861/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12766 Add Little Angry Bunny v2 (BEP20)
  blockchains/smartchain/assets/0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945/info.json
  blockchains/smartchain/assets/0x07f5cEdeD6B3dba557B3663EDC8941FB37b63945/logo.png
Labels: Payment Status: Paid

#12756 [Internal] Add initial polkadot validators
  blockchains/polkadot/validators/assets/11AnciffJctDC28odTEjDVYP2yWyp6275WLbrAUHi2vJm9f/logo.png
  blockchains/polkadot/validators/assets/12713bbq45c66CN9AD7yusSXWE1kY91DcMpjVcB2rXqZKy2w/logo.png
  blockchains/polkadot/validators/assets/14BB4ZbvPadELb1jBhbJq6GbECvBfkxFmohybYexzpE4KMq2/logo.png
  blockchains/polkadot/validators/assets/14N5GT7YTaDBSsLpfxxtCxNdYfgDofGj5wQSfqC1URKHdT8C/logo.png
  blockchains/polkadot/validators/assets/14QBQABMSFBsT3pDTaEQdshq7ZLmhzKiae2weZH45pw5ErYu/logo.png
  blockchains/polkadot/validators/assets/14ShUZUYUR35RBZW6uVVt1zXDxmSQddkeDdXf1JkMA6P721N/logo.png
  blockchains/polkadot/validators/assets/14Y4s6V1PWrwBLvxW47gcYgZCGTYekmmzvFsK1kiqNH2d84t/logo.png
  blockchains/polkadot/validators/assets/153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC/logo.png
  blockchains/polkadot/validators/assets/15BQUqtqhmqJPyvvEH5GYyWffXWKuAgoSUHuG1UeNdb8oDNT/logo.png
  blockchains/polkadot/validators/assets/15FdawBwokuor5wzU2DAU2Cp8i9DwRS1HTNgTNDAbcXuAEXH/logo.png
  blockchains/polkadot/validators/assets/15fU523Wq5BCt2NWAmrCU6p8nFB29uVifeG7bwYJHbw5Mmd9/logo.png
  blockchains/polkadot/validators/assets/15kkg1mK1tCGgqqo3c1CghtKCQsBEAPPjYNNmmRT3r29FeRX/logo.png
  blockchains/polkadot/validators/assets/1653t723BHhC2krGCFKUUNDQb5sUafy5pZvKVwnwo1oMAMi7/logo.png
  blockchains/polkadot/validators/assets/16GDRhRYxk42paoK6TfHAqWej8PdDDUwdDazjv4bAn4KGNeb/logo.png
  blockchains/polkadot/validators/assets/16SpacegeUTft9v3ts27CEC3tJaxgvE4uZeCctThFH3Vb24p/logo.png
  blockchains/polkadot/validators/assets/1REAJ1k691g5Eqqg9gL7vvZCBG7FCCZ8zgQkZWd4va5ESih/logo.png
  blockchains/polkadot/validators/assets/1RG5T6zGY4XovW75mTgpH6Bx7Y6uwwMmPToMCJSdMwdm4EW/logo.png
  blockchains/polkadot/validators/assets/1WG3jyNqniQMRZGQUc7QD2kVLT8hkRPGMSqAb5XYQM1UDxN/logo.png
  blockchains/polkadot/validators/assets/1dGsgLgFez7gt5WjX2FYzNCJtaCjGG6W9dA42d9cHngDYGg/logo.png
  blockchains/polkadot/validators/assets/1hJdgnAPSjfuHZFHzcorPnFvekSHihK9jdNPWHXgeuL7zaJ/logo.png
  blockchains/polkadot/validators/assets/1pbMtabBc9MNJcam4o8uHGymybvPcnkU5AGmpSmUpms7SWh/logo.png
  blockchains/polkadot/validators/assets/1zugcapKRuHy2C1PceJxTvXWiq6FHEDm2xa5XSU7KYP3rJE/logo.png
  blockchains/polkadot/validators/list.json
Labels: Payment Status: Paid

#12777 Add RisingSun Token (BEP20)
  blockchains/smartchain/assets/0x917841c010b3d86ED886F36F2C9807E07a2e3093/info.json
  blockchains/smartchain/assets/0x917841c010b3d86ED886F36F2C9807E07a2e3093/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12812 Upload logo for Featured DApp
  dapps/featured.market.png
Labels: Payment Status: Requested

#12817 Add Ryoshi's Vision (ERC20)
  blockchains/ethereum/assets/0x777E2ae845272a2F540ebf6a3D03734A5a8f618e/info.json
  blockchains/ethereum/assets/0x777E2ae845272a2F540ebf6a3D03734A5a8f618e/logo.png
Labels: Payment Status: Paid

#12781 Add Super Floki (BEP20)
  blockchains/smartchain/assets/0xf7BF4507336AeA836ab5575eC1801d96c3059483/info.json
  blockchains/smartchain/assets/0xf7BF4507336AeA836ab5575eC1801d96c3059483/logo.png
Labels: Status: On Hold, Payment Status: Paid

#12645 Add MIX (BEP20)
  blockchains/smartchain/assets/0x398f7827DcCbeFe6990478876bBF3612D93baF05/info.json
  blockchains/smartchain/assets/0x398f7827DcCbeFe6990478876bBF3612D93baF05/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12835 Add Bpet token, we add links to the info.json
  blockchains/smartchain/assets/0xb26D2d67C7652f361b73552310dA5753041b3867/info.json
  blockchains/smartchain/assets/0xb26D2d67C7652f361b73552310dA5753041b3867/logo.png
Labels: Payment Status: Paid

#12340 Add Primex Token logo and info
  blockchains/smartchain/assets/0xA0C2A0A34c04135429a38f7F9a4354090e00145A/info.json
  blockchains/smartchain/assets/0xA0C2A0A34c04135429a38f7F9a4354090e00145A/logo.png
Labels: Payment Status: Paid

#12807 Add Flux (BEP20)
  blockchains/smartchain/assets/0xaFF9084f2374585879e8B434C399E29E80ccE635/info.json
  blockchains/smartchain/assets/0xaFF9084f2374585879e8B434C399E29E80ccE635/logo.png
Labels: Payment Status: Requested

#12145 Add Moonpot logo for DAPP
  dapps/play.moonpot.com.png
Labels: Payment Status: Requested

#12844 add Universal US Dollar token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x86367c0e517622DAcdab379f2de389c3C9524345/info.json
  blockchains/ethereum/assets/0x86367c0e517622DAcdab379f2de389c3C9524345/logo.png
Labels: Payment Status: Paid

#12824 Add HalfPizza Token (BEP20)
  blockchains/smartchain/assets/0xFC646D0B564bf191B3d3adF2B620a792E485e6Da/info.json
  blockchains/smartchain/assets/0xFC646D0B564bf191B3d3adF2B620a792E485e6Da/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12770 add mini football
  blockchains/smartchain/assets/0xD024Ac1195762F6F13f8CfDF3cdd2c97b33B248b/info.json
  blockchains/smartchain/assets/0xD024Ac1195762F6F13f8CfDF3cdd2c97b33B248b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12842 Dogemongo Update
  blockchains/smartchain/assets/0x9E6B3E35c8f563B45d864f9Ff697A144ad28A371/info.json
  blockchains/smartchain/assets/0x9E6B3E35c8f563B45d864f9Ff697A144ad28A371/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12861 Add MADAGASCAR (BEP20)
  blockchains/smartchain/assets/0x4AAd6A01068c2621545d087A3c5281837112585b/info.json
  blockchains/smartchain/assets/0x4AAd6A01068c2621545d087A3c5281837112585b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#12848 EthOS info - Merged from buidl, UniFi and Arte
  blockchains/ethereum/assets/0xFdB29741F239a2406AE287913Ef12415160378d3/info.json
  blockchains/ethereum/assets/0xFdB29741F239a2406AE287913Ef12415160378d3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12832 Adding BKS (BEP20)
  blockchains/smartchain/assets/0x3da69D719AD12EEAb2b7031697E84c2c62299C13/info.json
  blockchains/smartchain/assets/0x3da69D719AD12EEAb2b7031697E84c2c62299C13/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12875 Add Step Finance token
  blockchains/solana/allowlist.json
  blockchains/solana/assets/StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT/info.json
  blockchains/solana/assets/StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT/logo.png
Labels: Payment Status: Requested

#12881 Add CPIE token to Trust Wallet
  blockchains/polygon/allowlist.json
  blockchains/polygon/assets/0xfad70FD116559914240faB82b0078c4E82a6a1B8/info.json
  blockchains/polygon/assets/0xfad70FD116559914240faB82b0078c4E82a6a1B8/logo.png
Labels: Payment Status: Paid

#12870 adding MTV on BSC
  blockchains/smartchain/assets/0x8aa688AB789d1848d131C65D98CEAA8875D97eF1/info.json
  blockchains/smartchain/assets/0x8aa688AB789d1848d131C65D98CEAA8875D97eF1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12814 Add RIZE ABOVE EVOLUTION (BEP20)
  blockchains/smartchain/assets/0x01e9611dF08548994C883e4Ca729B0128E73470F/info.json
  blockchains/smartchain/assets/0x01e9611dF08548994C883e4Ca729B0128E73470F/logo.png
Labels: Status: On Hold, Payment Status: Paid

#12852 add HEROES (BEP20)
  blockchains/smartchain/assets/0x261510Dd6257494eEA1DDA7618DBe8a7b87870dd/info.json
  blockchains/smartchain/assets/0x261510Dd6257494eEA1DDA7618DBe8a7b87870dd/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12834 Add YFO info and logo
  blockchains/smartchain/assets/0xAc0C8dA4A4748d8d821A0973d00b157aA78C473D/info.json
  blockchains/smartchain/assets/0xAc0C8dA4A4748d8d821A0973d00b157aA78C473D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12913 Add Coin98 (ERC20)
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xAE12C5930881c53715B369ceC7606B70d8EB229f/info.json
  blockchains/ethereum/assets/0xAE12C5930881c53715B369ceC7606B70d8EB229f/logo.png
Labels: Payment Status: Requested

#12886 Add HONEY (BEP20)
  blockchains/smartchain/assets/0xFa363022816aBf82f18a9C2809dCd2BB393F6AC5/info.json
  blockchains/smartchain/assets/0xFa363022816aBf82f18a9C2809dCd2BB393F6AC5/logo.png
Labels: Payment Status: Paid

#12914 Add links to ERN
  blockchains/ethereum/assets/0xBBc2AE13b23d715c30720F079fcd9B4a74093505/info.json
Labels: Payment Status: Requested

#12667 Add DXCT Token
  blockchains/smartchain/assets/0x5b1BaeC64aF6dC54E6e04349315919129A6d3c23/info.json
  blockchains/smartchain/assets/0x5b1BaeC64aF6dC54E6e04349315919129A6d3c23/logo.png
Labels: Payment Status: Paid

#12915 Add links KEEP Token
  blockchains/ethereum/assets/0x85Eee30c52B0b379b046Fb0F85F4f3Dc3009aFEC/info.json
Labels: Payment Status: Requested

#12920 Add links TORN Token
  blockchains/ethereum/assets/0x77777FeDdddFfC19Ff86DB637967013e6C6A116C/info.json
Labels: Payment Status: Requested

#12921 Add links Gitcoin
  blockchains/ethereum/assets/0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F/info.json
Labels: Payment Status: Requested

#12922 Add links NuCypher
  blockchains/ethereum/assets/0x4fE83213D56308330EC302a8BD641f1d0113A4Cc/info.json
Labels: Payment Status: Requested

#12923 Add links Automata (ERC20)
  blockchains/ethereum/assets/0xA2120b9e674d3fC3875f415A7DF52e382F141225/info.json
Labels: Payment Status: Requested

#12924 Add links Automata (BEP20)
  blockchains/smartchain/assets/0xA2120b9e674d3fC3875f415A7DF52e382F141225/info.json
Labels: Payment Status: Requested

#12928 Add BEP20 MDX Token
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x9C65AB58d8d978DB963e63f2bfB7121627e3a739/info.json
  blockchains/smartchain/assets/0x9C65AB58d8d978DB963e63f2bfB7121627e3a739/logo.png
Labels: Payment Status: Requested

#12912 Add CBC logo and info
  blockchains/smartchain/assets/0x793cEa0F1003411396b3A81A77d92Fe37015E7A9/info.json
  blockchains/smartchain/assets/0x793cEa0F1003411396b3A81A77d92Fe37015E7A9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12946 Update README.md
  README.md
Labels: Payment Status: Requested

#12871 Adding dotmoovs info
  blockchains/smartchain/assets/0x0ebd9537A25f56713E34c45b38F421A1e7191469/info.json
  blockchains/smartchain/assets/0x0ebd9537A25f56713E34c45b38F421A1e7191469/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12907 Add Tiger King (TKING) (ERC20)
  blockchains/ethereum/assets/0x24E89bDf2f65326b94E36978A7EDeAc63623DAFA/info.json
  blockchains/ethereum/assets/0x24E89bDf2f65326b94E36978A7EDeAc63623DAFA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12960 Add links FORTH ERC20
  blockchains/ethereum/assets/0x77FbA179C79De5B7653F68b5039Af940AdA60ce0/info.json
Labels: Payment Status: Requested

#12961 update mini football token logo
  blockchains/smartchain/assets/0xD024Ac1195762F6F13f8CfDF3cdd2c97b33B248b/info.json
  blockchains/smartchain/assets/0xD024Ac1195762F6F13f8CfDF3cdd2c97b33B248b/logo.png
Labels: Payment Status: Paid

#12858 Add My Defi Legends Logo and Info
  blockchains/smartchain/assets/0x88c55B3255aE1e6628C953C5CDfF27Ad3Cc33C81/info.json
  blockchains/smartchain/assets/0x88c55B3255aE1e6628C953C5CDfF27Ad3Cc33C81/logo.png
Labels: Status: On Hold, Payment Status: Paid

#12983 Add CP (BEP20)
  blockchains/smartchain/assets/0x82C19905B036bf4E329740989DCF6aE441AE26c1/info.json
  blockchains/smartchain/assets/0x82C19905B036bf4E329740989DCF6aE441AE26c1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12980 Update American Shiba LOGO and Websites (USHIBA) (ERC20)
  blockchains/ethereum/assets/0xB893A8049f250b57eFA8C62D51527a22404D7c9A/info.json
  blockchains/ethereum/assets/0xB893A8049f250b57eFA8C62D51527a22404D7c9A/logo.png
Labels: Payment Status: Paid

#12895 Add 1Doge (BEP20)
  blockchains/smartchain/assets/0x40619dc9F00ea34e51D96b6EC5d8a6aD75457434/info.json
  blockchains/smartchain/assets/0x40619dc9F00ea34e51D96b6EC5d8a6aD75457434/logo.png
Labels: Payment Status: Paid

#12889 Add BEAR (BEP20)
  blockchains/smartchain/assets/0xc3EAE9b061Aa0e1B9BD3436080Dc57D2d63FEdc1/info.json
  blockchains/smartchain/assets/0xc3EAE9b061Aa0e1B9BD3436080Dc57D2d63FEdc1/logo.png
Labels: Payment Status: Paid

#12984 Update ARES website
  blockchains/ethereum/assets/0x358AA737e033F34df7c54306960a38d09AaBd523/info.json
Labels: Payment Status: Requested

#12639 Add MUSO Finance (BEP20)
  blockchains/smartchain/assets/0x20512Ee0052236B009772Af0Ed22BC58B40c27B9/info.json
  blockchains/smartchain/assets/0x20512Ee0052236B009772Af0Ed22BC58B40c27B9/logo.png
Labels: Status: On Hold, Payment Status: Paid

#13011 Update logo and info
  blockchains/smartchain/assets/0xb9654A42f0F5dCDEf5617DebF8bd048E33F180E7/info.json
  blockchains/smartchain/assets/0xb9654A42f0F5dCDEf5617DebF8bd048E33F180E7/logo.png
Labels: Payment Status: Paid

#13014 Add Jade Currency (BEP20)
  blockchains/smartchain/assets/0x330F4fe5ef44B4d0742fE8BED8ca5E29359870DF/info.json
  blockchains/smartchain/assets/0x330F4fe5ef44B4d0742fE8BED8ca5E29359870DF/logo.png
Labels: Payment Status: Paid

#13003 Add PVU info and logo
  blockchains/smartchain/assets/0x31471E0791fCdbE82fbF4C44943255e923F1b794/info.json
  blockchains/smartchain/assets/0x31471E0791fCdbE82fbF4C44943255e923F1b794/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12992 Add RACA
  blockchains/smartchain/assets/0x12BB890508c125661E03b09EC06E404bc9289040/info.json
  blockchains/smartchain/assets/0x12BB890508c125661E03b09EC06E404bc9289040/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12978 Add WSBDApp (BEP20)
  blockchains/smartchain/assets/0x22168882276e5D5e1da694343b41DD7726eeb288/info.json
  blockchains/smartchain/assets/0x22168882276e5D5e1da694343b41DD7726eeb288/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12919 add euro logo
  blockchains/smartchain/assets/0x5F16ba80a1F620055e35215028E90808c7CC365C/info.json
  blockchains/smartchain/assets/0x5F16ba80a1F620055e35215028E90808c7CC365C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#12744 add berrydata asset bry info and logo
  blockchains/smartchain/assets/0xf859Bf77cBe8699013d6Dbc7C2b926Aaf307F830/info.json
  blockchains/smartchain/assets/0xf859Bf77cBe8699013d6Dbc7C2b926Aaf307F830/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13012 Add DragonSlayer (BEP20)
  blockchains/smartchain/assets/0xc8E8ecB2A5B5d1eCFf007BF74d15A86434aA0c5C/info.json
  blockchains/smartchain/assets/0xc8E8ecB2A5B5d1eCFf007BF74d15A86434aA0c5C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13033 Fix naming DYDX
  blockchains/ethereum/assets/0x92D6C1e31e14520e676a687F0a93788B716BEff5/info.json
Labels: Payment Status: Requested

#13035 Add links WOLF
  blockchains/polygon/assets/0x8f18dC399594b451EdA8c5da02d0563c0b2d0f16/info.json
Labels: Payment Status: Requested

#13037 Add links YFTE (ERC20)
  blockchains/ethereum/assets/0x94F31aC896c9823D81cf9C2C93feCEeD4923218f/info.json
Labels: Payment Status: Requested

#13040 Add links KRL (ERC20)
  blockchains/ethereum/assets/0x464eBE77c293E473B48cFe96dDCf88fcF7bFDAC0/info.json
Labels: Payment Status: Requested

#13052 Add RoboDoge Coin (BEP20)
  blockchains/smartchain/assets/0x2f657932E65905eA09c7aacfe898bf79e207c1C0/info.json
  blockchains/smartchain/assets/0x2f657932E65905eA09c7aacfe898bf79e207c1C0/logo.png
Labels: Payment Status: Paid

#13019 Add CHESS logo and info
  blockchains/smartchain/assets/0x20de22029ab63cf9A7Cf5fEB2b737Ca1eE4c82A6/info.json
  blockchains/smartchain/assets/0x20de22029ab63cf9A7Cf5fEB2b737Ca1eE4c82A6/logo.png
Labels: Payment Status: Paid

#13010 Add ORI logo and info.
  blockchains/smartchain/assets/0x3045d1A840364c3657b8Df6c6F86a4359c23472B/info.json
  blockchains/smartchain/assets/0x3045d1A840364c3657b8Df6c6F86a4359c23472B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13142 Adding new ERC contract for dotmoovs
  blockchains/ethereum/assets/0x24EC2Ca132abf8F6f8a6E24A1B97943e31f256a7/info.json
  blockchains/ethereum/assets/0x24EC2Ca132abf8F6f8a6E24A1B97943e31f256a7/logo.png
Labels: Payment Status: Requested

#12856 Add ZooToken Logo and Info
  blockchains/smartchain/assets/0x1D229B958D5DDFca92146585a8711aECbE56F095/info.json
  blockchains/smartchain/assets/0x1D229B958D5DDFca92146585a8711aECbE56F095/logo.png
Labels: Status: On Hold, Payment Status: Paid

#13125 Add Kaiken Shiba (BEP20)
  blockchains/smartchain/assets/0x11C0c93035d1302083eB09841042cFa582839A8C/info.json
  blockchains/smartchain/assets/0x11C0c93035d1302083eB09841042cFa582839A8C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13132 Add CAKE BANK (BEP20)
  blockchains/smartchain/assets/0x5F1b95784a033CD6842cf26eb9A9687F91Ad9e78/info.json
  blockchains/smartchain/assets/0x5F1b95784a033CD6842cf26eb9A9687F91Ad9e78/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13023 Add Fat Cake (BEP20)
  blockchains/smartchain/assets/0xB7Dba4C673beDB174DC3Ff7Ec65d17C863d39b16/info.json
  blockchains/smartchain/assets/0xB7Dba4C673beDB174DC3Ff7Ec65d17C863d39b16/logo.png
Labels: Payment Status: Paid

#13007 Add Titan War (BEP20)
  blockchains/smartchain/assets/0x76F34cd142ca4a5ea2E197ebffbF5234A1c29268/info.json
  blockchains/smartchain/assets/0x76F34cd142ca4a5ea2E197ebffbF5234A1c29268/logo.png
Labels: Payment Status: Paid

#13158 Add TKB Token (BEP20)
  blockchains/smartchain/assets/0x3Ef99822759A2192e7A82f64484e79e89cd90d52/info.json
  blockchains/smartchain/assets/0x3Ef99822759A2192e7A82f64484e79e89cd90d52/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13176 Add links SFP (BEP20)
  blockchains/smartchain/assets/0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb/info.json
Labels: Payment Status: Requested

#13177 Add links LIT (BEP20)
  blockchains/smartchain/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/info.json
Labels: Payment Status: Requested

#13178 Add links LIT (ERC20)
  blockchains/ethereum/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/info.json
Labels: Payment Status: Requested

#13180 Add links BTCST (BEP20)
  blockchains/smartchain/assets/0x78650B139471520656b9E7aA7A5e9276814a38e9/info.json
Labels: Payment Status: Requested

#13181 Add links REEF (BEP20)
  blockchains/smartchain/assets/0xF21768cCBC73Ea5B6fd3C687208a7c2def2d966e/info.json
Labels: Payment Status: Requested

#13182 Add links REEF (ERC20)
  blockchains/ethereum/assets/0xFE3E6a25e6b192A42a44ecDDCd13796471735ACf/info.json
Labels: Payment Status: Requested

#12198 update antimatter token address
  blockchains/ethereum/assets/0x9B99CcA871Be05119B2012fd4474731dd653FEBe/info.json
  blockchains/ethereum/assets/0x9B99CcA871Be05119B2012fd4474731dd653FEBe/logo.png
Labels: Payment Status: Paid

#13204 Add Sombra (BEP20)
  blockchains/smartchain/assets/0x8ad8e9B85787ddd0D31b32ECF655E93bfc0747eF/info.json
  blockchains/smartchain/assets/0x8ad8e9B85787ddd0D31b32ECF655E93bfc0747eF/logo.png
Labels: Payment Status: Paid

#13188 Add UFO Token
  blockchains/ethereum/assets/0x249e38Ea4102D0cf8264d3701f1a0E39C4f2DC3B/info.json
  blockchains/ethereum/assets/0x249e38Ea4102D0cf8264d3701f1a0E39C4f2DC3B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13170 Add Aeron (ARNX) and CryptoBonusMiles (CBM) (BEP20) tokens
  blockchains/smartchain/assets/0x0C37Bcf456bC661C14D596683325623076D7e283/info.json
  blockchains/smartchain/assets/0x0C37Bcf456bC661C14D596683325623076D7e283/logo.png
  blockchains/smartchain/assets/0x61a97C4914C43f8BD98D01a99418E826C80AfAdC/info.json
  blockchains/smartchain/assets/0x61a97C4914C43f8BD98D01a99418E826C80AfAdC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#13169 Add CIV on ERC-20
  blockchains/ethereum/assets/0x37fE0f067FA808fFBDd12891C0858532CFE7361d/info.json
  blockchains/ethereum/assets/0x37fE0f067FA808fFBDd12891C0858532CFE7361d/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#12390 added MLTPX
  blockchains/smartchain/assets/0x9D7c580e0bc4eA441Db96eebc7e1440d264bcE51/info.json
  blockchains/smartchain/assets/0x9D7c580e0bc4eA441Db96eebc7e1440d264bcE51/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13214 Add links MLTPX
  blockchains/smartchain/assets/0x9D7c580e0bc4eA441Db96eebc7e1440d264bcE51/info.json
Labels: Payment Status: Requested

#13211 Add Fat Cake (BEP20)
  blockchains/smartchain/assets/0xB7Dba4C673beDB174DC3Ff7Ec65d17C863d39b16/info.json
  blockchains/smartchain/assets/0xB7Dba4C673beDB174DC3Ff7Ec65d17C863d39b16/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
