Repository trustwallet/assets, pull requests merged in 2021-02, with the labels that each got.

#5444 Update Tatcoin (TAT) token contract address and added info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x505d0fFa350B2687eB8393AeBD14632F2990991a/info.json
  blockchains/ethereum/assets/0x505d0fFa350B2687eB8393AeBD14632F2990991a/logo.png
Labels: Payment Status: Paid

#5371 Add KEBAB Token
  blockchains/smartchain/assets/0x7979F6C54ebA05E18Ded44C4F986F49a5De551c2/info.json
  blockchains/smartchain/assets/0x7979F6C54ebA05E18Ded44C4F986F49a5De551c2/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5446 julswap logo update
  dapps/julswap.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#5448 Mirror Protocol Assets
  blockchains/ethereum/assets/0x0cae9e4d663793c2a2A0b211c1Cf4bBca2B9cAa7/info.json
  blockchains/ethereum/assets/0x0cae9e4d663793c2a2A0b211c1Cf4bBca2B9cAa7/logo.png
  blockchains/ethereum/assets/0x13B02c8dE71680e71F0820c996E4bE43c2F57d15/info.json
  blockchains/ethereum/assets/0x13B02c8dE71680e71F0820c996E4bE43c2F57d15/logo.png
  blockchains/ethereum/assets/0x1d350417d9787E000cc1b95d70E9536DcD91F373/info.json
  blockchains/ethereum/assets/0x1d350417d9787E000cc1b95d70E9536DcD91F373/logo.png
  blockchains/ethereum/assets/0x21cA39943E91d704678F5D00b6616650F066fD63/info.json
  blockchains/ethereum/assets/0x21cA39943E91d704678F5D00b6616650F066fD63/logo.png
  blockchains/ethereum/assets/0x31c63146a635EB7465e5853020b39713AC356991/info.json
  blockchains/ethereum/assets/0x31c63146a635EB7465e5853020b39713AC356991/logo.png
  blockchains/ethereum/assets/0x41BbEDd7286dAab5910a1f15d12CBda839852BD7/info.json
  blockchains/ethereum/assets/0x41BbEDd7286dAab5910a1f15d12CBda839852BD7/logo.png
  blockchains/ethereum/assets/0x56aA298a19C93c6801FDde870fA63EF75Cc0aF72/info.json
  blockchains/ethereum/assets/0x56aA298a19C93c6801FDde870fA63EF75Cc0aF72/logo.png
  blockchains/ethereum/assets/0x59A921Db27Dd6d4d974745B7FfC5c33932653442/info.json
  blockchains/ethereum/assets/0x59A921Db27Dd6d4d974745B7FfC5c33932653442/logo.png
  blockchains/ethereum/assets/0x9d1555d8cB3C846Bb4f7D5B1B1080872c3166676/info.json
  blockchains/ethereum/assets/0x9d1555d8cB3C846Bb4f7D5B1B1080872c3166676/logo.png
  blockchains/ethereum/assets/0xC8d674114bac90148d11D3C1d33C61835a0F9DCD/info.json
  blockchains/ethereum/assets/0xC8d674114bac90148d11D3C1d33C61835a0F9DCD/logo.png
  blockchains/ethereum/assets/0xEdb0414627E6f1e3F082DE65cD4F9C693D78CCA9/info.json
  blockchains/ethereum/assets/0xEdb0414627E6f1e3F082DE65cD4F9C693D78CCA9/logo.png
  blockchains/ethereum/assets/0xd36932143F6eBDEDD872D5Fb0651f4B72Fd15a84/info.json
  blockchains/ethereum/assets/0xd36932143F6eBDEDD872D5Fb0651f4B72Fd15a84/logo.png
  blockchains/ethereum/assets/0xf72FCd9DCF0190923Fadd44811E240Ef4533fc86/info.json
  blockchains/ethereum/assets/0xf72FCd9DCF0190923Fadd44811E240Ef4533fc86/logo.png
Labels: Payment Status: Requested

#5450 [Internal] Update ETH & BSC trading pairs from external API
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
  script/config.ts
Labels: Payment Status: Paid

#5451 [Internal] Tokenlist pairs update: Only manual update; use exclude/include config; no tokenlist_base
  .github/workflows/periodic-update.yml
  blockchains/ethereum/tokenlist_base.json
  blockchains/smartchain/tokenlist_base.json
  package.json
  script/blockchain/binance.ts
  script/blockchain/ethereum.ts
  script/blockchain/smartchain.ts
  script/blockchain/tezos.ts
  script/config.ts
  script/entrypoint/updateAuto.ts
  script/entrypoint/updateManual.ts
  script/generic/interface.ts
  script/generic/repo-structure.ts
  script/generic/subgraph.ts
  script/generic/tokenlists.ts
  script/generic/update-all.ts
Labels: Payment Status: Paid

#5452 [Internal] Tokenpairs manual update
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#5456 Adding tokensoft and wrapped.com assets
  blockchains/ethereum/assets/0x4A64515E5E1d1073e83f30cB97BEd20400b66E10/info.json
  blockchains/ethereum/assets/0x4A64515E5E1d1073e83f30cB97BEd20400b66E10/logo.png
  blockchains/ethereum/assets/0x53c4871322Bb47e7A24136fce291a6dcC832a294/info.json
  blockchains/ethereum/assets/0x53c4871322Bb47e7A24136fce291a6dcC832a294/logo.png
  blockchains/ethereum/assets/0x62A6738d887F47e297676FaB05b902709B106C64/info.json
  blockchains/ethereum/assets/0x62A6738d887F47e297676FaB05b902709B106C64/logo.png
  blockchains/ethereum/assets/0x6e1A19F235bE7ED8E3369eF73b196C07257494DE/info.json
  blockchains/ethereum/assets/0x6e1A19F235bE7ED8E3369eF73b196C07257494DE/logo.png
  blockchains/ethereum/assets/0xA3865E64121537b5b59B5e239Db4aCBe6F36aa74/info.json
  blockchains/ethereum/assets/0xA3865E64121537b5b59B5e239Db4aCBe6F36aa74/logo.png
  blockchains/ethereum/assets/0xBBC7f7A6AADAc103769C66CBC69AB720f7F9Eae3/info.json
  blockchains/ethereum/assets/0xBBC7f7A6AADAc103769C66CBC69AB720f7F9Eae3/logo.png
  blockchains/ethereum/assets/0xad3E3Fc59dff318BecEaAb7D00EB4F68b1EcF195/info.json
  blockchains/ethereum/assets/0xad3E3Fc59dff318BecEaAb7D00EB4F68b1EcF195/logo.png
Labels: Payment Status: Requested

#5457 Add Wrapped Elastos
  blockchains/ethereum/assets/0xe6fd75ff38Adca4B97FBCD938c86b98772431867/info.json
  blockchains/ethereum/assets/0xe6fd75ff38Adca4B97FBCD938c86b98772431867/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5231 Add DerivaDEX logo and info
  blockchains/ethereum/assets/0x3A880652F47bFaa771908C07Dd8673A787dAEd3A/info.json
  blockchains/ethereum/assets/0x3A880652F47bFaa771908C07Dd8673A787dAEd3A/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5449 Update README.md
  README.md
Labels: Payment Status: Requested

#5466 [Internal] Document trading pair update in Readme
  README.md
Labels: Payment Status: Paid

#5443 Add PolkaCover Token(CVR) Logo and Info
  blockchains/ethereum/assets/0x3C03b4EC9477809072FF9CC9292C9B25d4A8e6c6/info.json
  blockchains/ethereum/assets/0x3C03b4EC9477809072FF9CC9292C9B25d4A8e6c6/logo.png
Labels: Payment Status: Requested

#5304 Add BCDC logo and info
  blockchains/ethereum/assets/0xa1069A93B0E44cc42bDceC90D010746d1b65a65C/info.json
  blockchains/ethereum/assets/0xa1069A93B0E44cc42bDceC90D010746d1b65a65C/logo.png
Labels: Payment Status: Paid, Under Review

#5477 add_ERC20+BEP20_HGET
  blockchains/ethereum/assets/0x7968bc6a03017eA2de509AAA816F163Db0f35148/info.json
  blockchains/ethereum/assets/0x7968bc6a03017eA2de509AAA816F163Db0f35148/logo.png
  blockchains/smartchain/assets/0xC7d8D35EBA58a0935ff2D5a33Df105DD9f071731/info.json
  blockchains/smartchain/assets/0xC7d8D35EBA58a0935ff2D5a33Df105DD9f071731/logo.png
Labels: Payment Status: Requested

#5479 Remove duplicated description
  blockchains/ethereum/assets/0x3C03b4EC9477809072FF9CC9292C9B25d4A8e6c6/info.json
  blockchains/ethereum/assets/0x509A38b7a1cC0dcd83Aa9d06214663D9eC7c7F4a/info.json
  blockchains/ethereum/assets/0x7968bc6a03017eA2de509AAA816F163Db0f35148/info.json
  blockchains/ethereum/assets/0xa1069A93B0E44cc42bDceC90D010746d1b65a65C/info.json
  blockchains/smartchain/assets/0x0E9d900C884964dC4B26db96Ba113825B1a09Baa/info.json
  blockchains/smartchain/assets/0x11883Cdea6bAb720092791cc89affa54428Ce069/info.json
  blockchains/smartchain/assets/0x19eE64850862cFd234e20c0db4edA286f12ec907/info.json
  blockchains/smartchain/assets/0x1Ffe17B99b439bE0aFC831239dDECda2A790fF3A/info.json
  blockchains/smartchain/assets/0x1aF8c1C3AD36A041cb6678feD86B1E095004fd16/info.json
  blockchains/smartchain/assets/0x264Bc4Ea2F45cF6331AD6C3aC8d7257Cf487FcbC/info.json
  blockchains/smartchain/assets/0x2Bc4eb013DDee29D37920938B96d353171289B7C/info.json
  blockchains/smartchain/assets/0x2d3bfaDF9BC94E3Ab796029A030e863F1898aA06/info.json
  blockchains/smartchain/assets/0x3942936782d788ce69155F776A51A5F1C9dd9B22/info.json
  blockchains/smartchain/assets/0x3B0Be453a4008EBc2eDd457e7Bd355f1C5469d68/info.json
  blockchains/smartchain/assets/0x426D6D53187be3288fe37f214e3F6901D8145b62/info.json
  blockchains/smartchain/assets/0x53D88d2ffDBE71E81D95b08AE0cA49D0C4A8515f/info.json
  blockchains/smartchain/assets/0x738f3810b3dA0F3e6dC8C689D0d72f3b4992c43b/info.json
  blockchains/smartchain/assets/0x8cc7E2a6de999758499658bB702143FD025E09B2/info.json
  blockchains/smartchain/assets/0x9095e8d707E40982aFFce41C61c10895157A1B22/info.json
  blockchains/smartchain/assets/0xAa46e2c21B7763a73DB48e9b318899253E66e20C/info.json
  blockchains/smartchain/assets/0xC7d8D35EBA58a0935ff2D5a33Df105DD9f071731/info.json
  blockchains/smartchain/assets/0xCb87Cee8c77CdFD310fb3C58ff72e688d46f90b1/info.json
  blockchains/smartchain/assets/0xD83C88DB3A6cA4a32FFf1603b0f7DDce01F5f727/info.json
  blockchains/smartchain/assets/0xE692714717a89E4F2ab89dd17d8DDdD7bb52De8e/info.json
  blockchains/smartchain/assets/0xEA466cd2583A0290b9E7b987a769a7Eb468FB0A5/info.json
  blockchains/smartchain/assets/0xEF6d459FE81C3Ed53d292c936b2df5a8084975De/info.json
  blockchains/smartchain/assets/0xb31f5d117541825D6692c10e4357008EDF3E2BCD/info.json
Labels: Payment Status: Requested

#5475 Update Request Logo
  blockchains/ethereum/assets/0x8f8221aFbB33998d8584A2B05749bA73c37a938a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5459 Add Blockzero Labs (erc20)
  blockchains/ethereum/assets/0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704/info.json
  blockchains/ethereum/assets/0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704/logo.png
  blockchains/ethereum/assets/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8/info.json
  blockchains/ethereum/assets/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8/logo.png
Labels: Payment Status: Paid

#5480 add_ERC20_SNOW
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xfe9A29aB92522D14Fc65880d817214261D8479AE/info.json
  blockchains/ethereum/assets/0xfe9A29aB92522D14Fc65880d817214261D8479AE/logo.png
Labels: Payment Status: Requested

#5465 Add Helmet Dapp Logo
  dapps/helmet.insure.png
Labels: Payment Status: Requested

#5323 XSGD is a Singapore Dollar backed stablecoin
  blockchains/ethereum/assets/0x70e8dE73cE538DA2bEEd35d14187F6959a8ecA96/info.json
  blockchains/ethereum/assets/0x70e8dE73cE538DA2bEEd35d14187F6959a8ecA96/logo.png
Labels: Payment Status: Paid

#5474 [Tezos] Remove not used baker update code
  script/blockchain/tezos.ts
Labels: Payment Status: Requested

#5002 Add CyberFi Logo
  blockchains/ethereum/assets/0x63b4f3e3fa4e438698CE330e365E831F7cCD1eF4/info.json
  blockchains/ethereum/assets/0x63b4f3e3fa4e438698CE330e365E831F7cCD1eF4/logo.png
Labels: Payment Status: Paid

#5488 [Internal] Enforce value of the ID field
  script/generic/asset-infos.ts
Labels: Payment Status: Paid

#5489 Update 0x3b62F3820e0B035cc4aD602dECe6d796BC325325 #DEUS
  blockchains/ethereum/assets/0x3b62F3820e0B035cc4aD602dECe6d796BC325325/logo.png
Labels: Payment Status: Requested

#5490 add_ERC20+BEP20_LIT
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/info.json
  blockchains/ethereum/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/logo.png
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/info.json
  blockchains/smartchain/assets/0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723/logo.png
Labels: Payment Status: Requested

#5397 Add UNN token info and logo
  blockchains/ethereum/assets/0x226f7b842E0F0120b7E194D05432b3fd14773a9D/info.json
  blockchains/ethereum/assets/0x226f7b842E0F0120b7E194D05432b3fd14773a9D/logo.png
Labels: Payment Status: Paid

#5491 Update DEUS logos to black bg, #5470
  blockchains/ethereum/assets/0x3b62F3820e0B035cc4aD602dECe6d796BC325325/logo.png
  blockchains/ethereum/assets/0x80aB141F324C3d6F2b18b030f1C4E95d4d658778/logo.png
Labels: Payment Status: Requested

#5492 Add SIREN to Trust Wallet
  blockchains/ethereum/assets/0xD23Ac27148aF6A2f339BD82D0e3CFF380b5093de/info.json
  blockchains/ethereum/assets/0xD23Ac27148aF6A2f339BD82D0e3CFF380b5093de/logo.png
Labels: Payment Status: Requested

#5494 Add BEP-20 YVS token information and logo
  blockchains/smartchain/assets/0x47c1C7B9D7941A7265D123DCfb100D8FB5348213/info.json
  blockchains/smartchain/assets/0x47c1C7B9D7941A7265D123DCfb100D8FB5348213/logo.png
Labels: Payment Status: Paid

#5497 OptionRoom token info update
  blockchains/ethereum/assets/0xAd4f86a25bbc20FfB751f2FAC312A0B4d8F88c64/info.json
  blockchains/ethereum/assets/0xAd4f86a25bbc20FfB751f2FAC312A0B4d8F88c64/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5439 Add Crowns Token logo. ERC-20 token of Seascape Network
  blockchains/ethereum/assets/0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0/info.json
  blockchains/ethereum/assets/0xaC0104Cca91D167873B8601d2e71EB3D4D8c33e0/logo.png
Labels: Payment Status: Paid

#5502 add_BEP20_SFP
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb/info.json
  blockchains/smartchain/assets/0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb/logo.png
Labels: Payment Status: Requested

#5501 Add DOGY
  blockchains/ethereum/assets/0x9c405acf8688AfB61B3197421cDeeC1A266c6839/info.json
  blockchains/ethereum/assets/0x9c405acf8688AfB61B3197421cDeeC1A266c6839/logo.png
Labels: Payment Status: Paid

#5435 Add Yftether.io
  blockchains/ethereum/assets/0x94F31aC896c9823D81cf9C2C93feCEeD4923218f/info.json
  blockchains/ethereum/assets/0x94F31aC896c9823D81cf9C2C93feCEeD4923218f/logo.png
Labels: Payment Status: Paid

#5509 [Internal] Add check for missing info files, only warning for now
  script/generic/folders-and-files.ts
Labels: Payment Status: Paid

#5510 [Internal] Adjust fee message
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#5513 [Internal] Enforce values for type in info files
  blockchains/gochain/assets/0x064353B5C02A9F35979524Ebbfff4042151cF0c6/info.json
  blockchains/gochain/assets/0x473A70391d961D1D81044f7e2b69eeCd59dc355c/info.json
  blockchains/gochain/assets/0x53A6Bec3126BCE4e0dE349a9Ad3D9e4F997E76C4/info.json
  blockchains/gochain/assets/0x721Cc970CB5A22915f7663a6833E605deDDb7B92/info.json
  blockchains/gochain/assets/0xB881f9bB7EEa9499073c279D6eAC59B1A9010617/info.json
  blockchains/ontology/assets/ong/info.json
  blockchains/tomochain/assets/0x01F83cE6636179b54b0CC0C408f9a8bce40ae776/info.json
  blockchains/tomochain/assets/0x5e55D0c59287F5F8d540eF0766cA3F3810C71B84/info.json
  blockchains/tomochain/assets/0x936b1F7290c8CFC57e31D7e4a301D5F9fA5B0cd8/info.json
  blockchains/tomochain/assets/0xcE98172f4fC9Ad02da607843A2C211b7834431da/info.json
  script/generic/asset-infos.ts
Labels: Payment Status: Paid

#5518 [Internal] README update: mention info.json
  README.md
Labels: Payment Status: Paid

#5487 Token/carvertical
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x50bC2Ecc0bfDf5666640048038C1ABA7B7525683/info.json
  blockchains/ethereum/assets/0x50bC2Ecc0bfDf5666640048038C1ABA7B7525683/logo.png
  blockchains/ethereum/assets/0xdA6cb58A0D0C01610a29c5A65c303e13e885887C/info.json
  blockchains/ethereum/assets/0xdA6cb58A0D0C01610a29c5A65c303e13e885887C/logo.png
Labels: Payment Status: Paid

#5522 Add assets & logo to METH token
  blockchains/ethereum/assets/0x11003E410ca3FcD220765B3d2f343433A0b2bffd/info.json
  blockchains/ethereum/assets/0x11003E410ca3FcD220765B3d2f343433A0b2bffd/logo.png
Labels: Payment Status: Paid

#5531 Add BEP20 BunnyToken
  blockchains/smartchain/assets/0xC9849E6fdB743d08fAeE3E34dd2D1bc69EA11a51/info.json
  blockchains/smartchain/assets/0xC9849E6fdB743d08fAeE3E34dd2D1bc69EA11a51/logo.png
Labels: Payment Status: Paid

#5418 add UMX token logo and info
  blockchains/ethereum/assets/0x10Be9a8dAe441d276a5027936c3aADEd2d82bC15/info.json
  blockchains/ethereum/assets/0x10Be9a8dAe441d276a5027936c3aADEd2d82bC15/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5537 [Internal] Adjust token type / chain check; case insensitive
  script/generic/asset-infos.ts
Labels: Payment Status: Paid

#5538 [Internal] README change, mention assets app
  README.md
Labels: Payment Status: Paid

#5533 Add RAZOR Token
  blockchains/ethereum/assets/0x50DE6856358Cc35f3A9a57eAAA34BD4cB707d2cd/info.json
  blockchains/ethereum/assets/0x50DE6856358Cc35f3A9a57eAAA34BD4cB707d2cd/logo.png
Labels: Payment Status: Paid

#5556 Add Bridge Mutual, #5445
  blockchains/ethereum/assets/0x725C263e32c72dDC3A19bEa12C5a0479a81eE688/info.json
  blockchains/ethereum/assets/0x725C263e32c72dDC3A19bEa12C5a0479a81eE688/logo.png
Labels: Payment Status: Paid

#5539 Add Wrapped ZCore (BEP20)
  blockchains/ethereum/allowlist.json
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x1F01Dc57C66C2f87D8eab9C625D335e9defE6912/info.json
  blockchains/smartchain/assets/0x1F01Dc57C66C2f87D8eab9C625D335e9defE6912/logo.png
Labels: Payment Status: Paid

#5525 Added BFLY ERC20
  blockchains/ethereum/assets/0xf680429328caaaCabee69b7A9FdB21a71419c063/info.json
  blockchains/ethereum/assets/0xf680429328caaaCabee69b7A9FdB21a71419c063/logo.png
Labels: Payment Status: Paid

#5557 [Internal] Cheksum fix
  blockchains/ethereum/assets/0xf680429328caaaCabee69b7A9FdB21a71419c063/info.json
Labels: Payment Status: Paid

#5544 Add PIZZA
  blockchains/smartchain/assets/0x2cc26dd730F548dc4ac291ae7D84a0C96980d2cB/info.json
  blockchains/smartchain/assets/0x2cc26dd730F548dc4ac291ae7D84a0C96980d2cB/logo.png
  dapps/pizzafinance.app.png
Labels: Payment Status: Paid

#5545 Please Add CHS
  blockchains/smartchain/assets/0xaDD8A06fd58761A5047426e160B2B88AD3B9D464/info.json
  blockchains/smartchain/assets/0xaDD8A06fd58761A5047426e160B2B88AD3B9D464/logo.png
  dapps/cheeseswap.app.png
Labels: Payment Status: Paid

#5543 Adding CC10
  blockchains/ethereum/assets/0x17aC188e09A7890a1844E5E65471fE8b0CcFadF3/info.json
  blockchains/ethereum/assets/0x17aC188e09A7890a1844E5E65471fE8b0CcFadF3/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5560 Adding CC10 and NDX
  blockchains/ethereum/assets/0x86772b1409b61c639EaAc9Ba0AcfBb6E238e5F83/info.json
  blockchains/ethereum/assets/0x86772b1409b61c639EaAc9Ba0AcfBb6E238e5F83/logo.png
Labels: Payment Status: Requested

#5564 Update coinshares set
  blockchains/ethereum/assets/0xAdA0A1202462085999652Dc5310a7A9e2BF3eD42/info.json
  blockchains/ethereum/assets/0xAdA0A1202462085999652Dc5310a7A9e2BF3eD42/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5558 consolidate Invictus fund details
  blockchains/ethereum/assets/0x26E75307Fc0C021472fEb8F727839531F112f317/info.json
  blockchains/ethereum/assets/0xaF1250fa68D7DECD34fD75dE8742Bc03B29BD58e/info.json
  blockchains/ethereum/assets/0xd83C569268930fadAd4cdE6D0cB64450fef32b65/info.json
  blockchains/ethereum/assets/0xd83C569268930fadAd4cdE6D0cB64450fef32b65/logo.png
Labels: Payment Status: Paid

#5559 add ALEPH BEP20 contract (Binance Smart Chain)
  blockchains/smartchain/assets/0x82D2f8E02Afb160Dd5A480a617692e62de9038C4/info.json
  blockchains/smartchain/assets/0x82D2f8E02Afb160Dd5A480a617692e62de9038C4/logo.png
Labels: Payment Status: Paid

#5570 Update Swapcoinz contract info
  blockchains/smartchain/assets/0x37109a51e712471Bd2C72d8D70718627e7fF0032/info.json
  blockchains/smartchain/assets/0x37109a51e712471Bd2C72d8D70718627e7fF0032/logo.png
Labels: Payment Status: Paid

#5576 add_BEP20_AUTO
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xa184088a740c695E156F91f5cC086a06bb78b827/info.json
  blockchains/smartchain/assets/0xa184088a740c695E156F91f5cC086a06bb78b827/logo.png
Labels: Payment Status: Requested

#5581 [Internal] Update run fix, add reduced VRAB-B56 logo
  blockchains/binance/assets/VRAB-B56/logo.png
Labels: Payment Status: Paid

#5577 Add NuCypher (NU) (erc20)
  blockchains/ethereum/assets/0x4fE83213D56308330EC302a8BD641f1d0113A4Cc/info.json
  blockchains/ethereum/assets/0x4fE83213D56308330EC302a8BD641f1d0113A4Cc/logo.png
Labels: Payment Status: Paid

#5486 Add logo and info.json for Premia
  blockchains/ethereum/assets/0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70/info.json
  blockchains/ethereum/assets/0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70/logo.png
  blockchains/ethereum/assets/0x9D47894f8BECB68B9cF3428d256311Affe8B068B/info.json
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5582 [Internal] Correction for Premia submission (status field)
  blockchains/ethereum/assets/0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70/info.json
Labels: Payment Status: Paid

#5586 Addition of Aave stkABPT token
  blockchains/ethereum/assets/0xa1116930326D21fB917d5A27F1E9943A9595fb47/info.json
  blockchains/ethereum/assets/0xa1116930326D21fB917d5A27F1E9943A9595fb47/logo.png
Labels: Payment Status: Requested

#5580 wOxen project
  blockchains/ethereum/assets/0xd1e2d5085b39B80C9948AeB1b9aA83AF6756bcc5/info.json
  blockchains/ethereum/assets/0xd1e2d5085b39B80C9948AeB1b9aA83AF6756bcc5/logo.png
Labels: Payment Status: Paid

#5578 Added Finxflo FXF
  blockchains/ethereum/assets/0x8a40c222996f9F3431f63Bf80244C36822060f12/info.json
  blockchains/ethereum/assets/0x8a40c222996f9F3431f63Bf80244C36822060f12/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5590 Merge for #5575
  blockchains/ethereum/assets/0x7f1F2D3dFa99678675ECE1C243d3f7bC3746db5D/info.json
  blockchains/ethereum/assets/0x7f1F2D3dFa99678675ECE1C243d3f7bC3746db5D/logo.png
Labels: Payment Status: Paid

#5587 Add WORLD token's logo and info
  blockchains/ethereum/assets/0xBF494F02EE3FdE1F20BEE6242bCe2d1ED0c15e47/info.json
  blockchains/ethereum/assets/0xBF494F02EE3FdE1F20BEE6242bCe2d1ED0c15e47/logo.png
Labels: Payment Status: Paid

#5592 Add Everest ID (ID) (erc20)
  blockchains/ethereum/assets/0xEBd9D99A3982d547C5Bb4DB7E3b1F9F14b67Eb83/info.json
  blockchains/ethereum/assets/0xEBd9D99A3982d547C5Bb4DB7E3b1F9F14b67Eb83/logo.png
Labels: Payment Status: Paid

#5594 Add CafeSwap Token (BREW)
  blockchains/smartchain/assets/0x790Be81C3cA0e53974bE2688cDb954732C9862e1/info.json
  blockchains/smartchain/assets/0x790Be81C3cA0e53974bE2688cDb954732C9862e1/logo.png
Labels: Payment Status: Paid

#5591 Add BotOcean (BOTS) ERC20
  blockchains/ethereum/assets/0xf9FBE825BFB2bF3E387af0Dc18caC8d87F29DEa8/info.json
  blockchains/ethereum/assets/0xf9FBE825BFB2bF3E387af0Dc18caC8d87F29DEa8/logo.png
Labels: Payment Status: Paid

#5601 update_BEP20_USC
  blockchains/smartchain/assets/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d/info.json
Labels: Payment Status: Requested

#5602 Add_BEP-20_DODO
  blockchains/smartchain/assets/0x67ee3Cb086F8a16f34beE3ca72FAD36F7Db929e2/info.json
  blockchains/smartchain/assets/0x67ee3Cb086F8a16f34beE3ca72FAD36F7Db929e2/logo.png
Labels: Payment Status: Requested

#5596 Update Jupiter (JUP) logo.png
  blockchains/ethereum/assets/0x4B1E80cAC91e2216EEb63e29B957eB91Ae9C2Be8/logo.png
Labels: Payment Status: Paid

#5600 Add MOD token logo and info
  blockchains/ethereum/assets/0xEA1ea0972fa092dd463f2968F9bB51Cc4c981D71/info.json
  blockchains/ethereum/assets/0xEA1ea0972fa092dd463f2968F9bB51Cc4c981D71/logo.png
Labels: Payment Status: Paid

#5604 Add WZYN logo and info
  blockchains/ethereum/assets/0x94Ec918ddEEcFDfCBf8C8d3E848B7c3E8D8CeAa1/info.json
  blockchains/ethereum/assets/0x94Ec918ddEEcFDfCBf8C8d3E848B7c3E8D8CeAa1/logo.png
Labels: Payment Status: Paid

#5607 Update OMG Network (OMG) (erc20)
  blockchains/ethereum/assets/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07/info.json
  blockchains/ethereum/assets/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07/logo.png
Labels: Payment Status: Paid

#5597 Add Weed Token (bep20)
  blockchains/smartchain/assets/0x9E7942a24be24B18A56CEac7bA9926C5FBFc4E27/info.json
  blockchains/smartchain/assets/0x9E7942a24be24B18A56CEac7bA9926C5FBFc4E27/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5620 Adding UMB Info (ERC-20)
  blockchains/ethereum/assets/0x6fC13EACE26590B80cCCAB1ba5d51890577D83B2/info.json
  blockchains/ethereum/assets/0x6fC13EACE26590B80cCCAB1ba5d51890577D83B2/logo.png
Labels: Payment Status: Paid

#5621 [Internal] Update info.json
  blockchains/ethereum/assets/0x0408D7ed44de8D93A2510CAEF3Db4Ac7a4a1DFEc/info.json
  blockchains/ethereum/assets/0x040f685A2ffE3598A5041af33643C5F731507917/info.json
  blockchains/ethereum/assets/0x04162AEe1c40cF63747E6BC3A7e84ACEC1Ba2A78/info.json
  blockchains/ethereum/assets/0x5D0fa08AEb173AdE44B0Cf7F31d506D8E04f0ac8/info.json
  blockchains/ethereum/assets/0x5D0fa08AEb173AdE44B0Cf7F31d506D8E04f0ac8/logo.png
  blockchains/ethereum/assets/0xeE9d859eEaEc3d8E3Ff176a89b18EDfC62c23728/info.json
Labels: Payment Status: Paid

#5611 Zytara USD - stablecoin for esports
  blockchains/ethereum/assets/0xbf0f3cCB8fA385A287106FbA22e6BB722F94d686/info.json
  blockchains/ethereum/assets/0xbf0f3cCB8fA385A287106FbA22e6BB722F94d686/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5628 edit_ERC20_TGBP
  blockchains/ethereum/assets/0x00000000441378008EA67F4284A57932B1c000a5/info.json
Labels: Payment Status: Requested

#5630 Added Genesis Lab Cosmos, Kava, Solana and Terra validators
  blockchains/cosmos/validators/assets/cosmosvaloper1wdrypwex63geqswmcy5qynv4w3z3dyef2qmyna/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/assets/kavavaloper1uvz0vus7ktxt47cermscwe3k9gs7h9ag05sh6g/logo.png
  blockchains/kava/validators/list.json
  blockchains/solana/validators/assets/EFEKcHrUBsRoQkuTSJAQNZnj1u8h9oE4LoCYerednc3F/logo.png
  blockchains/solana/validators/list.json
  blockchains/terra/validators/assets/terravaloper1gh7wpfpsjrqnash5uc84z4njt95y9g5nh3uqzx/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid

#5646 [Internal] Reduce fees (250 twt / 2 bnb)
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#5635 Add Wynaut Logo
  blockchains/smartchain/assets/0x067a5ad3f0f91AcF512fFE66Ea77f37b4DcaaF18/info.json
  blockchains/smartchain/assets/0x067a5ad3f0f91AcF512fFE66Ea77f37b4DcaaF18/logo.png
Labels: Payment Status: Paid

#5571 Add SHIELD Logo and Info
  blockchains/smartchain/assets/0x60b3BC37593853c04410c4F07fE4D6748245BF77/info.json
  blockchains/smartchain/assets/0x60b3BC37593853c04410c4F07fE4D6748245BF77/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#5637 Ape Swap Finance Token Info
  blockchains/smartchain/assets/0x1E1aFE9D9c5f290d8F6996dDB190bd111908A43D/info.json
  blockchains/smartchain/assets/0x1E1aFE9D9c5f290d8F6996dDB190bd111908A43D/logo.png
  blockchains/smartchain/assets/0x51e6D27FA57373d8d4C256231241053a70Cb1d93/info.json
  blockchains/smartchain/assets/0x51e6D27FA57373d8d4C256231241053a70Cb1d93/logo.png
  blockchains/smartchain/assets/0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95/info.json
  blockchains/smartchain/assets/0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95/logo.png
  blockchains/smartchain/assets/0x7Bd46f6Da97312AC2DBD1749f82E202764C0B914/info.json
  blockchains/smartchain/assets/0x7Bd46f6Da97312AC2DBD1749f82E202764C0B914/logo.png
  blockchains/smartchain/assets/0xA0C3Ef24414ED9C9B456740128d8E63D016A9e11/info.json
  blockchains/smartchain/assets/0xA0C3Ef24414ED9C9B456740128d8E63D016A9e11/logo.png
  blockchains/smartchain/assets/0xF65C1C0478eFDe3c19b49EcBE7ACc57BB6B1D713/info.json
  blockchains/smartchain/assets/0xF65C1C0478eFDe3c19b49EcBE7ACc57BB6B1D713/logo.png
  dapps/apeswap.finance.png
Labels: Payment Status: Paid

#5643 Add CafeSwap Dapp logos
  dapps/cafeswap.finance.png
  dapps/exchange.cafeswap.finance.png
  dapps/voting.cafeswap.finance.png
Labels: Payment Status: Paid

#5629 Add Absorber (bep20)
  blockchains/smartchain/assets/0x6c5FE6e99D2484db7E4BF34F365ABA42d0E4dC20/info.json
  blockchains/smartchain/assets/0x6c5FE6e99D2484db7E4BF34F365ABA42d0E4dC20/logo.png
Labels: Payment Status: Paid

#5648 Add Digg (DIGG) (erc20)
  blockchains/ethereum/assets/0x798D1bE841a82a273720CE31c822C61a67a601C3/info.json
  blockchains/ethereum/assets/0x798D1bE841a82a273720CE31c822C61a67a601C3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5026 Add Benchmark Protocol (MARK)
  blockchains/ethereum/assets/0x67c597624B17b16fb77959217360B7cD18284253/info.json
  blockchains/ethereum/assets/0x67c597624B17b16fb77959217360B7cD18284253/logo.png
Labels: Payment Status: Paid

#5652 [Internal] More prominent error markers
  script/generic/update-all.ts
Labels: Payment Status: Paid

#5653 [Internal] Infrastructure for change management (history)
  history/LATEST.json
  history/versions/PLACEHOLDER
  package.json
  script/config.ts
  script/entrypoint/history.ts
  script/generic/history.ts
Labels: Payment Status: Paid

#5654 [Internal] Update version to 2
  history/LATEST.json
  history/versions/2.json
  script/generic/history.ts
Labels: Payment Status: Paid

#5655 [Internal] Perform history update after each commit to master (git action build)
  .github/workflows/history.yml
Labels: Payment Status: Paid

#5658 [Internal] History update build fixes
  .github/workflows/history.yml
  script/entrypoint/history.ts
Labels: Payment Status: Paid

#5659 [Internal] Adjust History update build, github.ref
  .github/workflows/history.yml
Labels: Payment Status: Paid

#5660 History update: add Readme, make build green when there is no change
  history/README.md
  script/generic/history.ts
Labels: Payment Status: Paid

#5667 [Internal] Merge fix and history build into one
  .github/workflows/fix.yml
  .github/workflows/history.yml
Labels: Payment Status: Paid

#5668 [Internal] Filter changed files to blockchains and dapps folders
  .github/workflows/fix.yml
  script/generic/history.ts
Labels: Payment Status: Paid

#5671 [Internal] No-effect change to an abandoned token, to test history
  blockchains/binance/assets/BAW-DFB/info.json
Labels: Payment Status: Paid

#5672 [Internal] Condition for fix build; test token change
  .github/workflows/fix.yml
  blockchains/binance/assets/BAW-DFB/info.json
Labels: Payment Status: Paid

#5651 Add XBN logo and info
  blockchains/smartchain/assets/0x547CBE0f0c25085e7015Aa6939b28402EB0CcDAC/info.json
  blockchains/smartchain/assets/0x547CBE0f0c25085e7015Aa6939b28402EB0CcDAC/logo.png
Labels: Payment Status: Paid

#5656 Add BLOCKv (VEE) (erc20)
  blockchains/ethereum/assets/0x340D2bdE5Eb28c1eed91B2f790723E3B160613B7/info.json
  blockchains/ethereum/assets/0x340D2bdE5Eb28c1eed91B2f790723E3B160613B7/logo.png
Labels: Payment Status: Paid

#5661 Added SuperFarm SUPER token.
  blockchains/ethereum/assets/0xe53EC727dbDEB9E2d5456c3be40cFF031AB40A55/info.json
  blockchains/ethereum/assets/0xe53EC727dbDEB9E2d5456c3be40cFF031AB40A55/logo.png
Labels: Payment Status: Paid

#5682 [Internal] Re-init history ALL changes
  history/LATEST.json
  history/versions/10.json
  history/versions/11.json
  history/versions/12.json
  history/versions/13.json
  history/versions/14.json
  history/versions/15.json
  history/versions/16.json
  history/versions/17.json
  history/versions/18.json
  history/versions/19.json
  history/versions/2.json
  history/versions/20.json
  history/versions/3.json
  history/versions/4.json
  history/versions/5.json
  history/versions/6.json
  history/versions/7.json
  history/versions/8.json
  history/versions/9.json
  script/generic/history.ts
Labels: Payment Status: Paid, Payment Status: Requested

#5675 Changed uSD V1 info to WUSD (uSD V2)
  blockchains/ethereum/assets/0x44086035439E676c02D411880FcCb9837CE37c57/logo.png
  blockchains/ethereum/assets/0x7C974104DF9dd7fb91205ab3D66d15AFf1049DE8/info.json
  blockchains/ethereum/assets/0x7C974104DF9dd7fb91205ab3D66d15AFf1049DE8/logo.png
Labels: Payment Status: Paid

#5689 Add ERC20 KEX
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x16980b3B4a3f9D89E33311B5aa8f80303E5ca4F8/info.json
  blockchains/ethereum/assets/0x16980b3B4a3f9D89E33311B5aa8f80303E5ca4F8/logo.png
Labels: Payment Status: Requested

#5710 Added CAS Logo and info
  blockchains/binance/assets/CAS-167/info.json
  blockchains/ethereum/assets/0xe8780B48bdb05F928697A5e8155f672ED91462F7/info.json
  blockchains/smartchain/assets/0x780207B8C0Fdc32cF60E957415bFa1f2d4d9718c/info.json
  blockchains/smartchain/assets/0x780207B8C0Fdc32cF60E957415bFa1f2d4d9718c/logo.png
Labels: Payment Status: Paid

#5703 Add CROW logo and info (BEP20)
  blockchains/smartchain/assets/0xcc2E12a9b5b75360c6FBf23B584c275D52cDdb0E/info.json
  blockchains/smartchain/assets/0xcc2E12a9b5b75360c6FBf23B584c275D52cDdb0E/logo.png
Labels: Payment Status: Paid

#5713 Add Freedom Reserve on Smart Chain, fixed, #5683
  blockchains/ethereum/assets/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532/info.json
  blockchains/smartchain/assets/0xBea7086c99A85D4b5E6A0494C18B037fDD8eE932/info.json
  blockchains/smartchain/assets/0xBea7086c99A85D4b5E6A0494C18B037fDD8eE932/logo.png
Labels: Payment Status: Paid

#5711 Add Fractal (FCL)
  blockchains/ethereum/assets/0xF4d861575ecC9493420A3f5a14F85B13f0b50EB3/info.json
  blockchains/ethereum/assets/0xF4d861575ecC9493420A3f5a14F85B13f0b50EB3/logo.png
Labels: Payment Status: Paid

#5709 Added STAKD Finance Token Logo
  blockchains/smartchain/assets/0xFfB3eDd21be33d5e78C9e0C2A275b3Fd42670D67/info.json
  blockchains/smartchain/assets/0xFfB3eDd21be33d5e78C9e0C2A275b3Fd42670D67/logo.png
Labels: Payment Status: Paid, Status: More Info / Change Requested

#5723 Add Crowns as PolyCrowns on Smartchain
  blockchains/smartchain/assets/0xbcf39F0EDDa668C58371E519AF37CA705f2bFcbd/info.json
  blockchains/smartchain/assets/0xbcf39F0EDDa668C58371E519AF37CA705f2bFcbd/logo.png
Labels: Payment Status: Requested

#5726 [Internal] Minor fixes to 2 dapp logo
  dapps/beta.adex.network.jpeg
  dapps/phoswap.io.png
Labels: Payment Status: Paid

#5727 [Internal] Reduce size of large dapps logos
  dapps/app.zerion.io.png
  dapps/beta.cent.co.png
  dapps/beta.dharma.io.png
  dapps/everdragons.com.png
  dapps/phoswap.io.png
  dapps/www.google.com.png
Labels: Payment Status: Paid

#5627 chore: added NGNT logo for BSC
  blockchains/smartchain/assets/0xB7d9905eDf8B7B093E3C74af8d6982D0F3d37762/logo.png
Labels: Payment Status: Paid

#5694 Add new TXL logo
  blockchains/ethereum/assets/0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41/info.json
  blockchains/ethereum/assets/0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41/logo.png
Labels: Payment Status: Paid

#5692 Add VesperToken (VSP) (erc20)
  blockchains/ethereum/assets/0x1b40183EFB4Dd766f11bDa7A7c3AD8982e998421/info.json
  blockchains/ethereum/assets/0x1b40183EFB4Dd766f11bDa7A7c3AD8982e998421/logo.png
Labels: Payment Status: Requested

#5724 add pexmons validator
  blockchains/binance/validators/assets/bva16kujlngdxq4pvyf87gpzx2x7ya4lgsz96j0aqt/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5730 Add SPONGE (bep20)
  blockchains/smartchain/assets/0x3aabCf53A1930A42E18D938C019E83Ebee50a849/info.json
  blockchains/smartchain/assets/0x3aabCf53A1930A42E18D938C019E83Ebee50a849/logo.png
Labels: Payment Status: Paid

#5731 Updated info.json and logo.png
  blockchains/ethereum/assets/0xABe580E7ee158dA464b51ee1a83Ac0289622e6be/info.json
  blockchains/ethereum/assets/0xABe580E7ee158dA464b51ee1a83Ac0289622e6be/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
