Repository trustwallet/assets, pull requests merged in 2021-03, with the labels that each got.

#5761 [Internal] Make some lowercase type's in info files uppercase.
  blockchains/ethereum/assets/0x1b40183EFB4Dd766f11bDa7A7c3AD8982e998421/info.json
  blockchains/ethereum/assets/0x340D2bdE5Eb28c1eed91B2f790723E3B160613B7/info.json
  blockchains/ethereum/assets/0x4fE83213D56308330EC302a8BD641f1d0113A4Cc/info.json
  blockchains/ethereum/assets/0x798D1bE841a82a273720CE31c822C61a67a601C3/info.json
  blockchains/ethereum/assets/0xD23Ac27148aF6A2f339BD82D0e3CFF380b5093de/info.json
  blockchains/ethereum/assets/0xEBd9D99A3982d547C5Bb4DB7E3b1F9F14b67Eb83/info.json
  blockchains/ontology/assets/ong/info.json
  blockchains/smartchain/assets/0x3aabCf53A1930A42E18D938C019E83Ebee50a849/info.json
  blockchains/smartchain/assets/0x6c5FE6e99D2484db7E4BF34F365ABA42d0E4dC20/info.json
  blockchains/smartchain/assets/0x9E7942a24be24B18A56CEac7bA9926C5FBFc4E27/info.json
Labels: Payment Status: Paid

#5712 Adding NBU ERC20 token
  blockchains/ethereum/assets/0xEB58343b36C7528F23CAAe63a150240241310049/info.json
  blockchains/ethereum/assets/0xEB58343b36C7528F23CAAe63a150240241310049/logo.png
Labels: Payment Status: Paid

#5690 Polkamarkets Token Add
  blockchains/ethereum/assets/0xD478161C952357F05f0292B56012Cd8457F1cfbF/info.json
  blockchains/ethereum/assets/0xD478161C952357F05f0292B56012Cd8457F1cfbF/logo.png
Labels: Payment Status: Paid

#5733 Add Public Mint Token assets
  blockchains/ethereum/assets/0x0CDF9acd87E940837ff21BB40c9fd55F68bba059/info.json
  blockchains/ethereum/assets/0x0CDF9acd87E940837ff21BB40c9fd55F68bba059/logo.png
Labels: Payment Status: Paid

#5691 DNA token swap information
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81/info.json
  blockchains/ethereum/assets/0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81/logo.png
  blockchains/ethereum/assets/0xef6344de1fcfC5F48c30234C16c1389e8CdC572C/info.json
  blockchains/ethereum/assets/0xef6344de1fcfC5F48c30234C16c1389e8CdC572C/logo.png
  blockchains/ethereum/denylist.json
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid

#5762 [Internal] Info type files: accept both casing, in fix make it uppercase
  script/generic/asset-infos.ts
  script/generic/interface.ts
  script/generic/update-all.ts
Labels: Payment Status: Paid

#5766 [Internal] Update pacakeswap API provider
  script/config.ts
  script/generic/subgraph.ts
Labels: Payment Status: Paid

#5776 Update smartchain iotex
  blockchains/smartchain/assets/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#5765 [BSC] add more validator logos
  blockchains/binance/validators/assets/bva13le7wtdw3kttw0cp30pprq049esmndvdsavysq/logo.png
  blockchains/binance/validators/assets/bva16av8zgzpjwlt7m8khwdl69ge0hx865lzq7wu80/logo.png
  blockchains/binance/validators/assets/bva16kujlngdxq4pvyf87gpzx2x7ya4lgsz96j0aqt/logo.png
  blockchains/binance/validators/assets/bva18w9m90ksmcnsw6rd2kwpd74m4l5agkc68su3et/logo.png
  blockchains/binance/validators/assets/bva18wgcs0k0glcmaxreweyeydu9mudtsftcxpkt4n/logo.png
  blockchains/binance/validators/assets/bva1ah8tgrjj5zes0rt5y6gc6m3zr5zwayt6nzaghh/logo.png
  blockchains/binance/validators/assets/bva1fjtft76yv69d9e00ey9a5ud0aa23z6yu4m2jch/logo.png
  blockchains/binance/validators/assets/bva1ghewcuxuunp4g0xj6yznnk6j2ccgxxhtf6h0r2/logo.png
  blockchains/binance/validators/assets/bva1jdv73wa8u9wya5zgwj3tgddeuwc432f8ex0j74/logo.png
  blockchains/binance/validators/assets/bva1krd023w6ptjs388fgkw7futq4fmzkscrmr0hg5/logo.png
  blockchains/binance/validators/assets/bva1nwyq37v4f02wu7zkc2rsynn8y7hh97ura39qyf/logo.png
  blockchains/binance/validators/assets/bva1r57gcwpa7f0slcef7z8jl7m50e2vmc854wnf7l/logo.png
  blockchains/binance/validators/assets/bva1wlrgdtdu2fs2555ed3qdg3e74ayhdtmavy3pg2/logo.png
  blockchains/binance/validators/assets/bva1yck3fkt2ltedev80skwjdmtfftv2lvpzfwmzfl/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5759 Added DeFi Wizard
  blockchains/ethereum/assets/0x7DEE45dff03ec7137979586cA20a2F4917BAC9Fa/info.json
  blockchains/ethereum/assets/0x7DEE45dff03ec7137979586cA20a2F4917BAC9Fa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5758 Add logo and info
  blockchains/smartchain/assets/0x2ed9e96EDd11A1fF5163599A66fb6f1C77FA9C66/info.json
  blockchains/smartchain/assets/0x2ed9e96EDd11A1fF5163599A66fb6f1C77FA9C66/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5702 Add Moola (MLA)
  blockchains/smartchain/assets/0xbDDD7D426274fc5F370817C80C06b86D651963e4/info.json
  blockchains/smartchain/assets/0xbDDD7D426274fc5F370817C80C06b86D651963e4/logo.png
Labels: Payment Status: Paid

#5760 update FRY token info - payment pending
  blockchains/ethereum/assets/0x6c972b70c533E2E045F333Ee28b9fFb8D717bE69/info.json
Labels: Payment Status: Paid

#5764 Fix/daomaker info
  blockchains/ethereum/assets/0x0f51bb10119727a7e5eA3538074fb341F56B09Ad/info.json
  blockchains/ethereum/assets/0x0f51bb10119727a7e5eA3538074fb341F56B09Ad/logo.png
Labels: Payment Status: Paid

#5778 Create 0xb9784C1633ef3b839563B988c323798634714368
  blockchains/smartchain/assets/0xb9784C1633ef3b839563B988c323798634714368/info.json
  blockchains/smartchain/assets/0xb9784C1633ef3b839563B988c323798634714368/logo.png
Labels: Payment Status: Paid

#5770 Add Hydro BEP20 on trustwallet
  blockchains/smartchain/assets/0xf3DBB49999B25c9D6641a9423C7ad84168D00071/info.json
  blockchains/smartchain/assets/0xf3DBB49999B25c9D6641a9423C7ad84168D00071/logo.png
Labels: Payment Status: Paid

#5767 [Internal] Update ETH tokenlist from Uniswap.
  blockchains/ethereum/tokenlist.json
  script/config.ts
Labels: Payment Status: Paid

#5772 added LPOOL token
  blockchains/ethereum/assets/0x6149C26Cd2f7b5CCdb32029aF817123F6E37Df5B/info.json
  blockchains/ethereum/assets/0x6149C26Cd2f7b5CCdb32029aF817123F6E37Df5B/logo.png
Labels: Payment Status: Paid

#5774 Add BEP-20 CryptEx Token (CRX) info
  blockchains/smartchain/assets/0x97a30C692eCe9C317235d48287d23d358170FC40/info.json
  blockchains/smartchain/assets/0x97a30C692eCe9C317235d48287d23d358170FC40/logo.png
Labels: Payment Status: Paid

#5735 Add Mushroom (MUSH) (erc20)
  blockchains/ethereum/assets/0xea6412Fb370e8d1605E6aEeAA21aD07C3C7e9F24/info.json
  blockchains/ethereum/assets/0xea6412Fb370e8d1605E6aEeAA21aD07C3C7e9F24/logo.png
Labels: Payment Status: Paid

#5741 Add antimatter logo and info
  blockchains/ethereum/assets/0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F/info.json
  blockchains/ethereum/assets/0x1C9491865a1DE77C5b6e19d2E6a5F1D7a6F2b25F/logo.png
Labels: Payment Status: Paid

#5102 Update SpiderDAO Token logo
  blockchains/ethereum/assets/0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd/info.json
  blockchains/ethereum/assets/0xbcD4b7dE6fde81025f74426D43165a5b0D790Fdd/logo.png
Labels: Payment Status: Paid

#5755 add_ERC20_SLICE
  blockchains/ethereum/assets/0x0AeE8703D34DD9aE107386d3eFF22AE75Dd616D1/info.json
  blockchains/ethereum/assets/0x0AeE8703D34DD9aE107386d3eFF22AE75Dd616D1/logo.png
Labels: Payment Status: Paid

#5787 string Defi
  blockchains/smartchain/assets/0x250342dD21cAE01583e8F3eDe4eB64753f665084/info.json
  blockchains/smartchain/assets/0x250342dD21cAE01583e8F3eDe4eB64753f665084/logo.png
Labels: Payment Status: Paid

#5798 [Internal] Update smartchain tokenlist
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#5782 Add HOPR token icon and info
  blockchains/ethereum/assets/0xF5581dFeFD8Fb0e4aeC526bE659CFaB1f8c781dA/info.json
  blockchains/ethereum/assets/0xF5581dFeFD8Fb0e4aeC526bE659CFaB1f8c781dA/logo.png
Labels: Payment Status: Requested

#5775 Adding token info xMark (BEP20) and xMark (ERC20)
  blockchains/ethereum/assets/0x36b679bd64Ed73DBfd88909cDCB892cB66Bd4CBb/info.json
  blockchains/ethereum/assets/0x36b679bd64Ed73DBfd88909cDCB892cB66Bd4CBb/logo.png
  blockchains/smartchain/assets/0x26A5dFab467d4f58fB266648CAe769503CEC9580/info.json
  blockchains/smartchain/assets/0x26A5dFab467d4f58fB266648CAe769503CEC9580/logo.png
Labels: Payment Status: Paid

#5794 Add BUBO Token logo and information
  blockchains/ethereum/assets/0xCCbf21ba6EF00802AB06637896B799f7101F54A2/info.json
  blockchains/ethereum/assets/0xCCbf21ba6EF00802AB06637896B799f7101F54A2/logo.png
Labels: Payment Status: Paid

#5796 Add OXT logo
  blockchains/smartchain/assets/0xAd6172123E1Bd3B4ce0B01ef92fDD63E83590b99/info.json
  blockchains/smartchain/assets/0xAd6172123E1Bd3B4ce0B01ef92fDD63E83590b99/logo.png
Labels: Payment Status: Paid

#5813 [Binance] Add Trust and BscScan to validator list
  blockchains/binance/validators/assets/bva13le7wtdw3kttw0cp30pprq049esmndvdsavysq/logo.png
  blockchains/binance/validators/assets/bva16av8zgzpjwlt7m8khwdl69ge0hx865lzq7wu80/logo.png
  blockchains/binance/validators/assets/bva16kujlngdxq4pvyf87gpzx2x7ya4lgsz96j0aqt/logo.png
  blockchains/binance/validators/assets/bva18w9m90ksmcnsw6rd2kwpd74m4l5agkc68su3et/logo.png
  blockchains/binance/validators/assets/bva18wgcs0k0glcmaxreweyeydu9mudtsftcxpkt4n/logo.png
  blockchains/binance/validators/assets/bva1ah8tgrjj5zes0rt5y6gc6m3zr5zwayt6nzaghh/logo.png
  blockchains/binance/validators/assets/bva1c6aqe9ndzcn2nsan963z43xg6kgrvzynl97785/logo.png
  blockchains/binance/validators/assets/bva1fjtft76yv69d9e00ey9a5ud0aa23z6yu4m2jch/logo.png
  blockchains/binance/validators/assets/bva1ghewcuxuunp4g0xj6yznnk6j2ccgxxhtf6h0r2/logo.png
  blockchains/binance/validators/assets/bva1jdv73wa8u9wya5zgwj3tgddeuwc432f8ex0j74/logo.png
  blockchains/binance/validators/assets/bva1krd023w6ptjs388fgkw7futq4fmzkscrmr0hg5/logo.png
  blockchains/binance/validators/assets/bva1nwyq37v4f02wu7zkc2rsynn8y7hh97ura39qyf/logo.png
  blockchains/binance/validators/assets/bva1r57gcwpa7f0slcef7z8jl7m50e2vmc854wnf7l/logo.png
  blockchains/binance/validators/assets/bva1t42gtf6hawqgpmdpjzmvlzvmlttlqtkvlmgjxt/logo.png
  blockchains/binance/validators/assets/bva1wlrgdtdu2fs2555ed3qdg3e74ayhdtmavy3pg2/logo.png
  blockchains/binance/validators/assets/bva1yck3fkt2ltedev80skwjdmtfftv2lvpzfwmzfl/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5810 Add Shadows logo and info
  blockchains/ethereum/assets/0x661Ab0Ed68000491d98C796146bcF28c20d7c559/info.json
  blockchains/ethereum/assets/0x661Ab0Ed68000491d98C796146bcF28c20d7c559/logo.png
Labels: Payment Status: Paid

#5797 updated typescript etc to 4
  package-lock.json
  package.json
Labels: Payment Status: Requested

#5814 Add xToken
  blockchains/ethereum/assets/0x7F3EDcdD180Dbe4819Bd98FeE8929b5cEdB3AdEB/info.json
  blockchains/ethereum/assets/0x7F3EDcdD180Dbe4819Bd98FeE8929b5cEdB3AdEB/logo.png
Labels: Payment Status: Paid

#5695 New ICHI logo
  blockchains/ethereum/assets/0x18Cc17a1EeD37C02A77B0B96b7890C7730E2a2CF/info.json
  blockchains/ethereum/assets/0x18Cc17a1EeD37C02A77B0B96b7890C7730E2a2CF/logo.png
  blockchains/ethereum/assets/0x6fcBBB527Fb2954BED2B224A5BB7c23C5AeEb6E1/info.json
  blockchains/ethereum/assets/0x70605a6457B0A8fBf1EEE896911895296eAB467E/info.json
  blockchains/ethereum/assets/0x70605a6457B0A8fBf1EEE896911895296eAB467E/logo.png
  blockchains/ethereum/assets/0x8F041A3940a5e6FB580075C3774E15FcFA0E1618/info.json
  blockchains/ethereum/assets/0x8F041A3940a5e6FB580075C3774E15FcFA0E1618/logo.png
  blockchains/ethereum/assets/0x903bEF1736CDdf2A537176cf3C64579C3867A881/logo.png
  blockchains/ethereum/assets/0xC88F47067dB2E25851317A2FDaE73a22c0777c37/info.json
  blockchains/ethereum/assets/0xC88F47067dB2E25851317A2FDaE73a22c0777c37/logo.png
  blockchains/ethereum/assets/0xEc0d77a58528a218cBf41Fa6E1585c8D7A085868/info.json
  blockchains/ethereum/assets/0xEc0d77a58528a218cBf41Fa6E1585c8D7A085868/logo.png
Labels: Payment Status: Paid

#5802 Add token info & logo of Contentos (COS)
  blockchains/smartchain/assets/0x96Dd399F9c3AFda1F194182F71600F1B65946501/info.json
  blockchains/smartchain/assets/0x96Dd399F9c3AFda1F194182F71600F1B65946501/logo.png
Labels: Payment Status: Paid

#5812 Add XGT Token
  blockchains/ethereum/assets/0xf1738912ae7439475712520797583ac784ea9033/info.json
  blockchains/ethereum/assets/0xf1738912ae7439475712520797583ac784ea9033/logo.png
Labels: Payment Status: Paid

#5619 Add info and logo for Goose Finance
  blockchains/smartchain/assets/0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6/info.json
  blockchains/smartchain/assets/0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6/logo.png
Labels: Payment Status: Paid

#5815 Add BFC info
  blockchains/ethereum/assets/0x0c7D5ae016f806603CB1782bEa29AC69471CAb9c/info.json
  blockchains/ethereum/assets/0x0c7D5ae016f806603CB1782bEa29AC69471CAb9c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5721 Add Polygon (Matic) asset
  blockchains/matic/info/info.json
  blockchains/matic/info/logo.png
Labels: Payment Status: Paid

#5701 Add Kylin logo
  blockchains/ethereum/assets/0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C/info.json
  blockchains/ethereum/assets/0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C/logo.png
Labels: Payment Status: Paid

#5826 Add details of BNB48 Club BSC Validator
  blockchains/binance/validators/assets/bva1ygrhjdjfyn2ffh5ha5llf5g6l3wxjt29hz9q4s/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5801 Adding WSCRT logo and info.
  blockchains/ethereum/assets/0x2B89bF8ba858cd2FCee1faDa378D5cd6936968Be/info.json
  blockchains/ethereum/assets/0x2B89bF8ba858cd2FCee1faDa378D5cd6936968Be/logo.png
Labels: Payment Status: Paid

#5616 Add HYPR (BSC)
  blockchains/smartchain/assets/0x03D6BD3d48F956D783456695698C407A46ecD54d/info.json
  blockchains/smartchain/assets/0x03D6BD3d48F956D783456695698C407A46ecD54d/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5838 add_BEP2-BEP20_COCOS
  blockchains/binance/allowlist.json
  blockchains/binance/assets/COCOS-CED/info.json
  blockchains/binance/assets/COCOS-CED/logo.png
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xAb301DaE71f5B386C566f484e636Aee60318F12F/info.json
  blockchains/smartchain/assets/0xAb301DaE71f5B386C566f484e636Aee60318F12F/logo.png
Labels: Payment Status: Requested

#5848 Improve bsc validator logos for dark mode
  blockchains/binance/validators/assets/bva13le7wtdw3kttw0cp30pprq049esmndvdsavysq/logo.png
  blockchains/binance/validators/assets/bva16av8zgzpjwlt7m8khwdl69ge0hx865lzq7wu80/logo.png
  blockchains/binance/validators/assets/bva1ah8tgrjj5zes0rt5y6gc6m3zr5zwayt6nzaghh/logo.png
  blockchains/binance/validators/assets/bva1fjtft76yv69d9e00ey9a5ud0aa23z6yu4m2jch/logo.png
  blockchains/binance/validators/assets/bva1yck3fkt2ltedev80skwjdmtfftv2lvpzfwmzfl/logo.png
Labels: Payment Status: Requested

#5844 add SOUL (APOyield SOULS)
  blockchains/smartchain/assets/0x67d012F731c23F0313CEA1186d0121779c77fcFE/info.json
  blockchains/smartchain/assets/0x67d012F731c23F0313CEA1186d0121779c77fcFE/logo.png
Labels: Payment Status: Paid

#5846 Add DGCL logo of token for Trustwallet and Uniswap
  blockchains/ethereum/assets/0x63B8b7d4A3EFD0735c4BFFBD95B332a55e4eB851/info.json
  blockchains/ethereum/assets/0x63B8b7d4A3EFD0735c4BFFBD95B332a55e4eB851/logo.png
Labels: Payment Status: Paid

#5853 [Internal] Assets fix script: format all JSON files, not only eth-fork info files
  script/generic/eth-forks.ts
  script/generic/json-format.ts
  script/generic/json.ts
Labels: Payment Status: Paid

#5851 OVR Token Listing
  blockchains/ethereum/assets/0x21BfBDa47A0B4B5b1248c767Ee49F7caA9B23697/info.json
  blockchains/ethereum/assets/0x21BfBDa47A0B4B5b1248c767Ee49F7caA9B23697/logo.png
Labels: Payment Status: Paid

#5856 PRs
  blockchains/binance/assets/ARPA-575/info.json
  blockchains/binance/assets/ATP-38C/info.json
  blockchains/binance/assets/BAND-34B/info.json
  blockchains/binance/assets/BOLT-4C6/info.json
  blockchains/binance/assets/BULL-BE4/info.json
  blockchains/binance/assets/CNNS-E16/info.json
  blockchains/binance/assets/CRPT-8C9/info.json
  blockchains/binance/assets/DARC-24B/info.json
  blockchains/binance/assets/DOS-120/info.json
  blockchains/binance/assets/DUSK-45E/info.json
  blockchains/binance/assets/EET-45C/info.json
  blockchains/binance/assets/ERD-D06/info.json
  blockchains/binance/assets/FSN-E14/info.json
  blockchains/binance/assets/GMAT-FC8/info.json
  blockchains/binance/assets/HNST-3C9/info.json
  blockchains/binance/assets/INJ-FAE/info.json
  blockchains/binance/assets/KAVA-10C/info.json
  blockchains/binance/assets/LIT-099/info.json
  blockchains/binance/assets/LTO-BDF/info.json
  blockchains/binance/assets/MCASH-869/info.json
  blockchains/binance/assets/MEETONE-031/info.json
  blockchains/binance/assets/MTV-4C6/info.json
  blockchains/binance/assets/MZK-2C7/info.json
  blockchains/binance/assets/NOIZB-878/info.json
  blockchains/binance/assets/NPXSXEM-89C/info.json
  blockchains/binance/assets/OWTX-A6B/info.json
  blockchains/binance/assets/PVT-554/info.json
  blockchains/binance/assets/RAVEN-F66/info.json
Labels: Payment Status: Requested

#5858 [Internal] Assets: Adjust reminder and closing times
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#5840 Add yETH Token logo ( Bep20 )
  blockchains/smartchain/assets/0x77DFb1DaFC92c5Df29996f5528BA1829941cD3Bb/info.json
  blockchains/smartchain/assets/0x77DFb1DaFC92c5Df29996f5528BA1829941cD3Bb/logo.png
Labels: Payment Status: Paid

#5842 Add ARGON logo and Info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x851F7a700c5d67DB59612b871338a85526752c25/info.json
  blockchains/smartchain/assets/0x851F7a700c5d67DB59612b871338a85526752c25/logo.png
Labels: Payment Status: Paid

#5854 Update FLASH logo
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x20398aD62bb2D930646d45a6D4292baa0b860C1f/info.json
  blockchains/ethereum/assets/0x20398aD62bb2D930646d45a6D4292baa0b860C1f/logo.png
  blockchains/ethereum/assets/0xB4467E8D621105312a914F1D42f10770C0Ffe3c8/info.json
Labels: Payment Status: Paid

#5824 Add LOTTO logo
  blockchains/ethereum/assets/0xb0dFd28d3CF7A5897C694904Ace292539242f858/info.json
  blockchains/ethereum/assets/0xb0dFd28d3CF7A5897C694904Ace292539242f858/logo.png
Labels: Payment Status: Paid

#5821 Update Axion logo
  blockchains/ethereum/assets/0x71F85B2E46976bD21302B64329868fd15eb0D127/logo.png
Labels: Payment Status: Paid

#5865 Update list.json with existing active validators
  blockchains/binance/validators/assets/bva16wc0mnv7g3kcvegd0ee5f3u25y05g97w7nqyhz/logo.png
  blockchains/binance/validators/assets/bva1ds4jdqh2mh6qczwur2nrx22l53kwt4eellrgyz/logo.png
  blockchains/binance/validators/assets/bva1gz3mdtzsznsrs7d3hr6gjusfh22tr59qf4rtzp/logo.png
  blockchains/binance/validators/assets/bva1jh99vrdj0g3n2snrelzrh45s7cs7usqr3x40kk/logo.png
  blockchains/binance/validators/assets/bva1s0ntnh523dc2u5ez3dcj2t34k2x7y60cue46rt/logo.png
  blockchains/binance/validators/assets/bva1vr8d0kzvnkfgxl4980udka8psdj7434zxjezuq/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#5873 Revert "Update list.json with existing active validators"
  blockchains/binance/validators/assets/bva16wc0mnv7g3kcvegd0ee5f3u25y05g97w7nqyhz/logo.png
  blockchains/binance/validators/assets/bva1ds4jdqh2mh6qczwur2nrx22l53kwt4eellrgyz/logo.png
  blockchains/binance/validators/assets/bva1gz3mdtzsznsrs7d3hr6gjusfh22tr59qf4rtzp/logo.png
  blockchains/binance/validators/assets/bva1jh99vrdj0g3n2snrelzrh45s7cs7usqr3x40kk/logo.png
  blockchains/binance/validators/assets/bva1s0ntnh523dc2u5ez3dcj2t34k2x7y60cue46rt/logo.png
  blockchains/binance/validators/assets/bva1vr8d0kzvnkfgxl4980udka8psdj7434zxjezuq/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5877 Update logos for 6 active BSC validators (Revert 5873 revert 5865 master)
  blockchains/binance/validators/assets/bva16wc0mnv7g3kcvegd0ee5f3u25y05g97w7nqyhz/logo.png
  blockchains/binance/validators/assets/bva1ds4jdqh2mh6qczwur2nrx22l53kwt4eellrgyz/logo.png
  blockchains/binance/validators/assets/bva1gz3mdtzsznsrs7d3hr6gjusfh22tr59qf4rtzp/logo.png
  blockchains/binance/validators/assets/bva1jh99vrdj0g3n2snrelzrh45s7cs7usqr3x40kk/logo.png
  blockchains/binance/validators/assets/bva1s0ntnh523dc2u5ez3dcj2t34k2x7y60cue46rt/logo.png
  blockchains/binance/validators/assets/bva1vr8d0kzvnkfgxl4980udka8psdj7434zxjezuq/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5878 [Internal] Extend collaborators
  .github/merge-fee-bot.yaml
Labels: Payment Status: Paid

#5841 added new yieldwatch logo
  dapps/yieldwatch.net.png
Labels: Payment Status: Requested

#5860 Add Ethernity Chain (ERC20)
  blockchains/ethereum/assets/0xBBc2AE13b23d715c30720F079fcd9B4a74093505/info.json
  blockchains/ethereum/assets/0xBBc2AE13b23d715c30720F079fcd9B4a74093505/logo.png
Labels: Payment Status: Paid

#5887 Add ankr to bsc validator list
  blockchains/binance/validators/assets/bva1xnudjls7x4p48qrk0j247htt7rl2k2dzp3mr3j/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#5850 Add TrueFi TrueUSD (tfTUSD)
  blockchains/ethereum/assets/0xa1e72267084192Db7387c8CC1328fadE470e4149/info.json
  blockchains/ethereum/assets/0xa1e72267084192Db7387c8CC1328fadE470e4149/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5884 Add files via upload
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x4691937a7508860F876c9c0a2a617E7d9E945D4B/info.json
  blockchains/ethereum/assets/0x4691937a7508860F876c9c0a2a617E7d9E945D4B/logo.png
Labels: Payment Status: Paid

#5885 Adding GNBU ERC20 token
  blockchains/ethereum/assets/0x28fd5f6C915c7438B8Cf9E2f682883F79875520C/info.json
  blockchains/ethereum/assets/0x28fd5f6C915c7438B8Cf9E2f682883F79875520C/logo.png
Labels: Payment Status: Paid

#5777 Add new FKX token details + remove old and invalid FKX token details
  blockchains/ethereum/assets/0x009e864923b49263c7F10D19B7f8Ab7a9A5AAd33/info.json
  blockchains/ethereum/assets/0x009e864923b49263c7F10D19B7f8Ab7a9A5AAd33/logo.png
  blockchains/ethereum/assets/0x16484d73Ac08d2355F466d448D2b79D2039F6EBB/info.json
  blockchains/ethereum/assets/0x16484d73Ac08d2355F466d448D2b79D2039F6EBB/logo.png
Labels: Payment Status: Paid

#5822 Add logo and info.json
  blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607/info.json
  blockchains/ethereum/assets/0xfAd45E47083e4607302aa43c65fB3106F1cd7607/logo.png
Labels: Payment Status: Paid

#5888 Add ZCore Finance
  blockchains/smartchain/assets/0x0288D3E353fE2299F11eA2c2e1696b4A648eCC07/info.json
  blockchains/smartchain/assets/0x0288D3E353fE2299F11eA2c2e1696b4A648eCC07/logo.png
Labels: Payment Status: Paid

#5852 Add Believer (BEP20)
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x43a0EE2e4c005277195F409E77919D1b1a5c9c1f/info.json
  blockchains/smartchain/assets/0x43a0EE2e4c005277195F409E77919D1b1a5c9c1f/logo.png
Labels: Payment Status: Paid

#5889 Updating GNBU ERC20 address info
  blockchains/ethereum/assets/0x639ae8F3EEd18690bF451229d14953a5A5627b72/info.json
  blockchains/ethereum/assets/0x639ae8F3EEd18690bF451229d14953a5A5627b72/logo.png
Labels: Payment Status: Paid

#5892 edit_ERC20_PAID
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x1614F18Fc94f47967A3Fbe5FfcD46d4e7Da3D787/info.json
  blockchains/ethereum/assets/0x1614F18Fc94f47967A3Fbe5FfcD46d4e7Da3D787/logo.png
  blockchains/ethereum/assets/0x8c8687fC965593DFb2F0b4EAeFD55E9D8df348df/info.json
Labels: Payment Status: Requested

#5898 Add DOGE-B67 Dogecoin BEP2
  blockchains/binance/allowlist.json
  blockchains/binance/assets/DOGE-B67/info.json
  blockchains/binance/assets/DOGE-B67/logo.png
Labels: Payment Status: Paid

#5897 Add MASK info and logo
  blockchains/ethereum/assets/0x69af81e73A73B40adF4f3d4223Cd9b1ECE623074/info.json
  blockchains/ethereum/assets/0x69af81e73A73B40adF4f3d4223Cd9b1ECE623074/logo.png
Labels: Payment Status: Requested

#5893 Add TAT to smartchain
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x290c665656a67e0ea0784f90ECBaeFF77c884217/info.json
  blockchains/smartchain/assets/0x290c665656a67e0ea0784f90ECBaeFF77c884217/logo.png
Labels: Payment Status: Paid

#5831 Add CGG Token
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x1fE24F25b1Cf609B9c4e7E12D802e3640dFA5e43/info.json
  blockchains/ethereum/assets/0x1fE24F25b1Cf609B9c4e7E12D802e3640dFA5e43/logo.png
Labels: Payment Status: Paid

#5793 adding tokenized version of Wagerr.
  blockchains/ethereum/assets/0xC237868a9c5729bdF3173dDDacaa336a0a5BB6e0/info.json
  blockchains/ethereum/assets/0xC237868a9c5729bdF3173dDDacaa336a0a5BB6e0/logo.png
  blockchains/smartchain/assets/0xdBf8265B1d5244A13424f13977723AcF5395eAB2/info.json
  blockchains/smartchain/assets/0xdBf8265B1d5244A13424f13977723AcF5395eAB2/logo.png
Labels: Payment Status: Paid

#5895 Add Staked TrueFi (stkTRU)
  blockchains/ethereum/assets/0x23696914Ca9737466D8553a2d619948f548Ee424/info.json
  blockchains/ethereum/assets/0x23696914Ca9737466D8553a2d619948f548Ee424/logo.png
Labels: Payment Status: Requested

#5904 [Internal] Add check and fix id field
  blockchains/ethereum/assets/0x0c7D5ae016f806603CB1782bEa29AC69471CAb9c/info.json
  blockchains/ethereum/assets/0x1fE24F25b1Cf609B9c4e7E12D802e3640dFA5e43/info.json
  blockchains/ethereum/assets/0x2B89bF8ba858cd2FCee1faDa378D5cd6936968Be/info.json
  blockchains/ethereum/assets/0x4691937a7508860F876c9c0a2a617E7d9E945D4B/info.json
  blockchains/ethereum/assets/0x661Ab0Ed68000491d98C796146bcF28c20d7c559/info.json
  blockchains/ethereum/assets/0xb0dFd28d3CF7A5897C694904Ace292539242f858/info.json
  blockchains/smartchain/assets/0x851F7a700c5d67DB59612b871338a85526752c25/info.json
  blockchains/smartchain/assets/0xAd6172123E1Bd3B4ce0B01ef92fDD63E83590b99/info.json
  blockchains/smartchain/assets/0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6/info.json
  script/generic/asset-infos.ts
Labels: Payment Status: Paid

#5906 Add VRAP Token Logo
  blockchains/smartchain/assets/0x271C418B045d05A1D52c6bF849d47b5B5B4d769e/info.json
  blockchains/smartchain/assets/0x271C418B045d05A1D52c6bF849d47b5B5B4d769e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5922 Add DOS Network Token BEP20
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xDc0f0a5719c39764b011eDd02811BD228296887C/info.json
  blockchains/smartchain/assets/0xDc0f0a5719c39764b011eDd02811BD228296887C/logo.png
Labels: Payment Status: Paid

#5929 BogTools add BOG token (final)
  blockchains/smartchain/assets/0xD7B729ef857Aa773f47D37088A1181bB3fbF0099/info.json
  blockchains/smartchain/assets/0xD7B729ef857Aa773f47D37088A1181bB3fbF0099/logo.png
Labels: Payment Status: Paid

#5921 Add HyperJump Dapps+ALLOY
  blockchains/smartchain/assets/0x5eF5994fA33FF4eB6c82d51ee1DC145c546065Bd/info.json
  blockchains/smartchain/assets/0x5eF5994fA33FF4eB6c82d51ee1DC145c546065Bd/logo.png
  dapps/farm.hyperjump.fi.png
  dapps/info.hyperjump.fi.png
  dapps/swap.hyperjump.fi.png
Labels: Payment Status: Paid

#5943 Add entry for 0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD
  blockchains/ethereum/assets/0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD/info.json
  blockchains/ethereum/assets/0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5951 [Internal] Add check for valid values of status field
  blockchains/ethereum/assets/0x5807CA447851C98569c567963B25B1C83D41BeBc/info.json
  blockchains/ethereum/assets/0x58a5d3e4873A75B07fB3c7CF477EeBc44ea73B3B/info.json
  blockchains/ethereum/assets/0x6aCf5940974E2a935f3F4e4FEDAc798583eEE826/info.json
  blockchains/ethereum/assets/0x82b0E50478eeaFde392D45D1259Ed1071B6fDa81/info.json
  blockchains/ethereum/assets/0x9c197c4b58527fAAAb67CB35E3145166B23D242e/info.json
  blockchains/ethereum/assets/0xdD6Bf56CA2ada24c683FAC50E37783e55B57AF9F/info.json
  script/generic/asset-infos.ts
  script/generic/status-values.ts
  test/index.test.ts
Labels: Payment Status: Paid

#5948 Add TurtleDex (BEP20)
  blockchains/smartchain/assets/0xc4957a864245AA4373Be1f33ae24E93876b7Dfe1/info.json
  blockchains/smartchain/assets/0xc4957a864245AA4373Be1f33ae24E93876b7Dfe1/logo.png
Labels: Payment Status: Paid

#5947 Add TFF token
  blockchains/smartchain/assets/0x2d69c55baEcefC6ec815239DA0a985747B50Db6E/info.json
  blockchains/smartchain/assets/0x2d69c55baEcefC6ec815239DA0a985747B50Db6E/logo.png
Labels: Payment Status: Paid

#5939 Included BSC version of the SUPER token.
  blockchains/smartchain/assets/0x51BA0b044d96C3aBfcA52B64D733603CCC4F0d4D/info.json
  blockchains/smartchain/assets/0x51BA0b044d96C3aBfcA52B64D733603CCC4F0d4D/logo.png
Labels: Payment Status: Paid, Status: On Hold

#5792 Add WHIRL logo and info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x7f479d78380Ad00341fdD7322fE8AEf766e29e5A/info.json
  blockchains/smartchain/assets/0x7f479d78380Ad00341fdD7322fE8AEf766e29e5A/logo.png
Labels: Payment Status: Paid

#5825 Add PADtether logo and info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x5A37F6a7fFa184E2287aD226989441D685e4Bf7A/info.json
  blockchains/smartchain/assets/0x5A37F6a7fFa184E2287aD226989441D685e4Bf7A/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#5957 Add Hydro Token new ERC20 #5799
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x946112efaB61C3636CBD52DE2E1392D7A75A6f01/info.json
  blockchains/ethereum/assets/0x946112efaB61C3636CBD52DE2E1392D7A75A6f01/logo.png
  blockchains/ethereum/assets/0xEBBdf302c940c6bfd49C6b165f457fdb324649bc/info.json
Labels: Payment Status: Requested

#5960 [Internal] Add check for tags field (array)
  blockchains/smartchain/assets/0x4B0F1812e5Df2A09796481Ff14017e6005508003/info.json
  script/generic/asset-infos.ts
  script/generic/tag-values.ts
  script/tags.json
  test/index.test.ts
Labels: Payment Status: Paid

#5964 Add CAKE-435 BEP2
  blockchains/binance/allowlist.json
  blockchains/binance/assets/CAKE-435/info.json
  blockchains/binance/assets/CAKE-435/logo.png
Labels: Payment Status: Paid

#5954 Add DYP logo and info
  blockchains/ethereum/allowlist.json
  blockchains/ethereum/assets/0x961C8c0B1aaD0c0b10a51FeF6a867E3091BCef17/info.json
  blockchains/ethereum/assets/0x961C8c0B1aaD0c0b10a51FeF6a867E3091BCef17/logo.png
Labels: Payment Status: Paid

#5955 Add PAINT logo and info
  blockchains/ethereum/assets/0x4C6eC08CF3fc987c6C4BEB03184D335A2dFc4042/info.json
  blockchains/ethereum/assets/0x4C6eC08CF3fc987c6C4BEB03184D335A2dFc4042/logo.png
Labels: Payment Status: Paid

#5959 Logo KGO + INFO
  blockchains/smartchain/assets/0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773/info.json
  blockchains/smartchain/assets/0x5d3AfBA1924aD748776E4Ca62213BF7acf39d773/logo.png
Labels: Payment Status: Paid

#5953 Add Coin (COIN) (ERC20)
  blockchains/ethereum/assets/0xE61fDAF474Fac07063f2234Fb9e60C1163Cfa850/info.json
  blockchains/ethereum/assets/0xE61fDAF474Fac07063f2234Fb9e60C1163Cfa850/logo.png
Labels: Payment Status: Paid

#5933 Add XRT info and logo
  blockchains/smartchain/assets/0xC0A51ac9d548BdcDe53Fa59448029e41A39FEB20/info.json
  blockchains/smartchain/assets/0xC0A51ac9d548BdcDe53Fa59448029e41A39FEB20/logo.png
Labels: Payment Status: Paid

#5911 [Internal] Add tagging support
  blockchains/algorand/info/info.json
  blockchains/binance/info/info.json
  blockchains/cosmos/info/info.json
  blockchains/kava/info/info.json
  blockchains/smartchain/assets/0x4B0F1812e5Df2A09796481Ff14017e6005508003/info.json
  blockchains/tezos/info/info.json
  blockchains/tron/info/info.json
  script/tags.json
  test/index.test.ts
Labels: Payment Status: Paid

#5981 Updated 1inch.exchange logo
  dapps/1inch.exchange.png
Labels: Payment Status: Requested

#5967 Add Radicle (RAD) token
  blockchains/ethereum/assets/0x31c8EAcBFFdD875c74b94b077895Bd78CF1E64A3/info.json
  blockchains/ethereum/assets/0x31c8EAcBFFdD875c74b94b077895Bd78CF1E64A3/logo.png
Labels: Payment Status: Paid

#5958 Add TOZ Token info
  blockchains/ethereum/assets/0x29239242A83479a4074Cb1c9e2A3e6705A4A4455/info.json
  blockchains/ethereum/assets/0x29239242A83479a4074Cb1c9e2A3e6705A4A4455/logo.png
Labels: Payment Status: Paid

#5972 Uplode SFM Logo
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x3A66D3d2EDB25182430d01b991BC6eaC73aD5AA8/info.json
  blockchains/smartchain/assets/0x3A66D3d2EDB25182430d01b991BC6eaC73aD5AA8/logo.png
Labels: Payment Status: Paid

#5968 Add PKF token info and logo
  blockchains/ethereum/assets/0x8B39B70E39Aa811b69365398e0aACe9bee238AEb/info.json
  blockchains/ethereum/assets/0x8B39B70E39Aa811b69365398e0aACe9bee238AEb/logo.png
Labels: Payment Status: Paid

#5982 Logo
  blockchains/smartchain/assets/0x8850D2c68c632E3B258e612abAA8FadA7E6958E5/info.json
  blockchains/smartchain/assets/0x8850D2c68c632E3B258e612abAA8FadA7E6958E5/logo.png
Labels: Payment Status: Paid

#5978 Add json for ERC20(ERC20) on Smart Chain for #5935
  blockchains/ethereum/assets/0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA/info.json
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x58730ae0FAA10d73b0cDdb5e7b87C3594f7a20CB/info.json
  blockchains/smartchain/assets/0x58730ae0FAA10d73b0cDdb5e7b87C3594f7a20CB/logo.png
Labels: Payment Status: Paid

#6003 Added ZeroSwap BSC Logo
  blockchains/smartchain/assets/0x44754455564474A89358B2C2265883DF993b12F0/info.json
  blockchains/smartchain/assets/0x44754455564474A89358B2C2265883DF993b12F0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#5996 Add FWB Pro
  blockchains/ethereum/assets/0x35bD01FC9d6D5D81CA9E055Db88Dc49aa2c699A8/info.json
  blockchains/ethereum/assets/0x35bD01FC9d6D5D81CA9E055Db88Dc49aa2c699A8/logo.png
Labels: Payment Status: Requested

#6007 Add YETU logo and info
  blockchains/smartchain/assets/0x6652048Fa5E66ed63a0225FFd7C82e106b0Aa18b/info.json
  blockchains/smartchain/assets/0x6652048Fa5E66ed63a0225FFd7C82e106b0Aa18b/logo.png
Labels: Payment Status: Paid

#6000 GOVI token info and logo
  blockchains/ethereum/assets/0xeEAA40B28A2d1b0B08f6f97bB1DD4B75316c6107/info.json
  blockchains/ethereum/assets/0xeEAA40B28A2d1b0B08f6f97bB1DD4B75316c6107/logo.png
Labels: Payment Status: Paid

#5998 add KIND LOGO
  blockchains/smartchain/assets/0xE3Ba88c38D2789FE58465020CC0FB60b70c10d32/info.json
  blockchains/smartchain/assets/0xE3Ba88c38D2789FE58465020CC0FB60b70c10d32/logo.png
Labels: Payment Status: Paid

#5991 Add KINE logo and info
  blockchains/ethereum/assets/0xCbfef8fdd706cde6F208460f2Bf39Aa9c785F05D/info.json
  blockchains/ethereum/assets/0xCbfef8fdd706cde6F208460f2Bf39Aa9c785F05D/logo.png
Labels: Payment Status: Paid

#6016 [Internal] Tag values config in typed file
  script/generic/tag-values.ts
  script/tags-config.ts
  script/tags.json
Labels: Payment Status: Paid

#6029 add_BEP20_SAFEMOON
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x8076C74C5e3F5852037F31Ff0093Eeb8c8ADd8D3/info.json
  blockchains/smartchain/assets/0x8076C74C5e3F5852037F31Ff0093Eeb8c8ADd8D3/logo.png
Labels: Payment Status: Requested

#6002 Add PNIX logo and info
  blockchains/smartchain/assets/0xc25D94fc3f8D7bD1d88f89802fe075338F71dEC7/info.json
  blockchains/smartchain/assets/0xc25D94fc3f8D7bD1d88f89802fe075338F71dEC7/logo.png
Labels: Payment Status: Paid

#5874 Add CO2 logo and info
  blockchains/ethereum/assets/0x75739d5944534115d7C54ee8C73F186D793BAE02/info.json
  blockchains/ethereum/assets/0x75739d5944534115d7C54ee8C73F186D793BAE02/logo.png
Labels: Payment Status: Paid

#5999 Add NAUT LOGO & INFO ( Bep20 )
  blockchains/smartchain/assets/0x05B339B0A346bF01f851ddE47a5d485c34FE220c/info.json
  blockchains/smartchain/assets/0x05B339B0A346bF01f851ddE47a5d485c34FE220c/logo.png
Labels: Payment Status: Paid

#6037 Add BUX token
  blockchains/smartchain/assets/0x211FfbE424b90e25a15531ca322adF1559779E45/info.json
  blockchains/smartchain/assets/0x211FfbE424b90e25a15531ca322adF1559779E45/logo.png
Labels: Payment Status: Paid

#5997 Uploading Visor Logo and info.json
  blockchains/ethereum/assets/0xF938424F7210f31dF2Aee3011291b658f872e91e/info.json
  blockchains/ethereum/assets/0xF938424F7210f31dF2Aee3011291b658f872e91e/logo.png
Labels: Payment Status: Paid

#6039 [Internal] Remove unused import; Lint fix
  script/generic/tag-values.ts
Labels: Payment Status: Requested

#6019 Add BSC <> ThunderCore bridged tokens - TT-BNB, TT-BUSD and Bep20-TT
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x990E7154bB999FAa9b2fa5Ed29E822703311eA85/info.json
  blockchains/smartchain/assets/0x990E7154bB999FAa9b2fa5Ed29E822703311eA85/logo.png
  blockchains/thundertoken/allowlist.json
  blockchains/thundertoken/assets/0x8EF1A1E0671Aa44852f4d87105eF482470bB3e69/info.json
  blockchains/thundertoken/assets/0x8EF1A1E0671Aa44852f4d87105eF482470bB3e69/logo.png
  blockchains/thundertoken/assets/0xBEB0131D95AC3F03fd15894D0aDE5DBf7451d171/info.json
  blockchains/thundertoken/assets/0xBEB0131D95AC3F03fd15894D0aDE5DBf7451d171/logo.png
Labels: Payment Status: Paid

#5950 Add Oddz token from Oddz finance(https://oddz.fi)
  blockchains/ethereum/assets/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6/info.json
  blockchains/ethereum/assets/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6/logo.png
Labels: Payment Status: Paid

#6042 Add maps.me ERC/SPL tokens
  blockchains/ethereum/assets/0x2b915b505c017ABb1547aA5Ab355FbE69865cC6D/info.json
  blockchains/ethereum/assets/0x2b915b505c017ABb1547aA5Ab355FbE69865cC6D/logo.png
  blockchains/solana/assets/MAPS41MDahZ9QdKXhVa4dWB9RuyfV4XqhyAZ8XcYepb/info.json
  blockchains/solana/assets/MAPS41MDahZ9QdKXhVa4dWB9RuyfV4XqhyAZ8XcYepb/logo.png
Labels: Payment Status: Requested

#6045 Add Ara Token (ARA) (ERC20)
  blockchains/ethereum/assets/0xa92E7c82B11d10716aB534051B271D2f6aEf7Df5/info.json
  blockchains/ethereum/assets/0xa92E7c82B11d10716aB534051B271D2f6aEf7Df5/logo.png
Labels: Payment Status: Paid

#6015 add BLZD logo & info
  blockchains/smartchain/assets/0x57067A6BD75c0E95a6A5f158455926e43E79BeB0/info.json
  blockchains/smartchain/assets/0x57067A6BD75c0E95a6A5f158455926e43E79BeB0/logo.png
  dapps/blizzard.money.png
Labels: Payment Status: Paid, Status: On Hold

#6057 Add POOL PoolTogether token info and logo
  blockchains/ethereum/assets/0x0cEC1A9154Ff802e7934Fc916Ed7Ca50bDE6844e/info.json
  blockchains/ethereum/assets/0x0cEC1A9154Ff802e7934Fc916Ed7Ca50bDE6844e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#6044 Added SafeMars Logo and Info
  blockchains/smartchain/assets/0x3aD9594151886Ce8538C1ff615EFa2385a8C3A88/info.json
  blockchains/smartchain/assets/0x3aD9594151886Ce8538C1ff615EFa2385a8C3A88/logo.png
Labels: Payment Status: Paid

#6008 Add DailySwap logo and info
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xe0d6AD5A77fD1ed1A22F89657E4248A8ac6a8cbF/info.json
  blockchains/smartchain/assets/0xe0d6AD5A77fD1ed1A22F89657E4248A8ac6a8cbF/logo.png
Labels: Payment Status: Paid

#6054 Adding RTF logo
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0xb4A92eDAb7c9Ba94b6637E8052D8bd133EC4221C/info.json
  blockchains/smartchain/assets/0xb4A92eDAb7c9Ba94b6637E8052D8bd133EC4221C/logo.png
Labels: Payment Status: Paid, Status: Correction needed

#6011 Add TOWER token info and logo
  blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B/info.json
  blockchains/ethereum/assets/0x1C9922314ED1415c95b9FD453c3818fd41867d0B/logo.png
Labels: Payment Status: Paid

#6063 Add SoupSwap (BEP20)
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x604D105f2F1f68641a000f03b5DC557bFFfdB8FE/info.json
  blockchains/smartchain/assets/0x604D105f2F1f68641a000f03b5DC557bFFfdB8FE/logo.png
Labels: Payment Status: Paid

#6023 Add USDf and Gaia
  blockchains/ethereum/assets/0x05462671C05aDc39A6521fA60D5e9443e9E9d2B9/info.json
  blockchains/ethereum/assets/0x05462671C05aDc39A6521fA60D5e9443e9E9d2B9/logo.png
  blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/info.json
  blockchains/ethereum/assets/0x4B9E5fe882b2fbB3E098c9A25a8Ce66135Ed2be4/logo.png
Labels: Payment Status: Paid

#6077 [Internal] Enforce that info.id field matches exactly folder name (i.e. in check…
  script/generic/asset-infos.ts
Labels: Payment Status: Paid

#6025 Avalanche (AVAX)
  blockchains/avalanche/info/info.json
  blockchains/avalanche/info/logo.png
Labels: Payment Status: Paid

#6059 Add K21
  blockchains/ethereum/assets/0xB9d99C33eA2d86EC5eC6b8A4dD816EBBA64404AF/info.json
  blockchains/ethereum/assets/0xB9d99C33eA2d86EC5eC6b8A4dD816EBBA64404AF/logo.png
Labels: Payment Status: Requested

#6073 Add SaTT logo and info
  blockchains/smartchain/assets/0x448BEE2d93Be708b54eE6353A7CC35C4933F1156/info.json
  blockchains/smartchain/assets/0x448BEE2d93Be708b54eE6353A7CC35C4933F1156/logo.png
Labels: Payment Status: Paid

#6075 Add files via upload
  blockchains/smartchain/assets/0x1bA8c21c623C843Cd4c60438d70E7Ad50f363fbb/info.json
  blockchains/smartchain/assets/0x1bA8c21c623C843Cd4c60438d70E7Ad50f363fbb/logo.png
Labels: Payment Status: Paid

#6069 Add CONV logo and info
  blockchains/ethereum/assets/0xc834Fa996fA3BeC7aAD3693af486ae53D8aA8B50/info.json
  blockchains/ethereum/assets/0xc834Fa996fA3BeC7aAD3693af486ae53D8aA8B50/logo.png
Labels: Payment Status: Paid

#5974 Add VIDTC NFT Claim
  blockchains/smartchain/assets/0xCD9b26795d834d75867d950898695a30b1Eb17E1/info.json
  blockchains/smartchain/assets/0xCD9b26795d834d75867d950898695a30b1Eb17E1/logo.png
Labels: Payment Status: Paid

#6046 Add MSS logo and info
  blockchains/smartchain/assets/0xAcABD3f9b8F76fFd2724604185Fa5AFA5dF25aC6/info.json
  blockchains/smartchain/assets/0xAcABD3f9b8F76fFd2724604185Fa5AFA5dF25aC6/logo.png
Labels: Payment Status: Paid

#6081 [Internal] Update README with info on checks
  README.md
Labels: Payment Status: Paid

#6084 add_BEP20_LINA
  blockchains/smartchain/allowlist.json
  blockchains/smartchain/assets/0x762539b45A1dCcE3D36d080F74d1AED37844b878/info.json
  blockchains/smartchain/assets/0x762539b45A1dCcE3D36d080F74d1AED37844b878/logo.png
Labels: Payment Status: Requested

#6085 add infstones to bsc validator list
  blockchains/binance/validators/assets/bva1a7n56r44h4tlgrk3mazxx6cavhgpkrm7a8p6g4/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Requested

#6087 Add BitcoinAsset (BEP20)
  blockchains/smartchain/assets/0xAd9787017e82f6368BbE4893b475CaadA2258564/info.json
  blockchains/smartchain/assets/0xAd9787017e82f6368BbE4893b475CaadA2258564/logo.png
Labels: Payment Status: Paid

#5980 ERC20 token listing on Trust Wallet - Kauri crypto
  blockchains/ethereum/assets/0xe172F366678EC7B559F6C2913a437BaaDfd4e6c8/info.json
  blockchains/ethereum/assets/0xe172F366678EC7B559F6C2913a437BaaDfd4e6c8/logo.png
Labels: Payment Status: Paid

#6098 [Internal] Manual commit from updateAuto, tokenlist and XVS logo
  blockchains/binance/assets/XVS-795/logo.png
  blockchains/binance/tokenlist.json
Labels: Payment Status: Paid

#6058 Add Wrapped CrescoFin (WCRES) (ERC20)
  blockchains/ethereum/assets/0xa0afAA285Ce85974c3C881256cB7F225e3A1178a/info.json
  blockchains/ethereum/assets/0xa0afAA285Ce85974c3C881256cB7F225e3A1178a/logo.png
Labels: Payment Status: Paid

#6091 Add MERO logo and info.
  blockchains/smartchain/assets/0x476DA763fb6D22B8465f7886d2d652A428a93984/info.json
  blockchains/smartchain/assets/0x476DA763fb6D22B8465f7886d2d652A428a93984/logo.png
Labels: Payment Status: Paid

#6078 Add MNDAO logo and info
  blockchains/smartchain/assets/0x069B2619Eb24367A46Fda638Bd1b88Aa4daD7879/info.json
  blockchains/smartchain/assets/0x069B2619Eb24367A46Fda638Bd1b88Aa4daD7879/logo.png
Labels: Payment Status: Paid

#6086 add Burnaby to BSC validator list
  blockchains/binance/validators/assets/bva1r3g3akxj46p85tye2vjy64tal9ql2hyce4y4d3/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid
