Repository trustwallet/assets, pull requests merged in 2021-10, with the labels that each got.

#14024 Add token CVX (ERC20)
  blockchains/ethereum/assets/0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B/info.json
  blockchains/ethereum/assets/0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B/logo.png
Labels: Payment Status: Requested

#14020 Add TC token logo and info #13652
  blockchains/tron/assets/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y/info.json
  blockchains/tron/assets/TCMwzYUUCxLkTNpXjkYSBgXgqXwt7KJ82y/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13988 Add Crossswap.com (BEP20)
  blockchains/smartchain/assets/0xb8e3bB633F7276cc17735D86154E0ad5ec9928C0/info.json
  blockchains/smartchain/assets/0xe0b0C16038845BEd3fCf70304D3e167Df81ce225/info.json
  blockchains/smartchain/assets/0xe0b0C16038845BEd3fCf70304D3e167Df81ce225/logo.png
Labels: Payment Status: Paid

#13991 Add ADAPad.io (BEP20)
  blockchains/smartchain/assets/0xDB0170e2d0c1CC1b2E7a90313d9B9afA4f250289/info.json
  blockchains/smartchain/assets/0xDB0170e2d0c1CC1b2E7a90313d9B9afA4f250289/logo.png
  blockchains/smartchain/assets/0xb8e3bB633F7276cc17735D86154E0ad5ec9928C0/info.json
Labels: Payment Status: Paid

#13978 Anon inu ( AINU ) Trust wallet logo and info update
  blockchains/smartchain/assets/0x64F36701138f0E85cC10c34Ea535FdBADcB54147/info.json
  blockchains/smartchain/assets/0x64F36701138f0E85cC10c34Ea535FdBADcB54147/logo.png
Labels: Payment Status: Paid

#14016 Add dexIRA (BEP20)
  blockchains/smartchain/assets/0x147E07976E1ae78287c33aAFAab87760d32E50A5/info.json
  blockchains/smartchain/assets/0x147E07976E1ae78287c33aAFAab87760d32E50A5/logo.png
Labels: Payment Status: Paid

#14029 Add Parabolic (BEP20)
  blockchains/smartchain/assets/0xB5bCF4fAa81457e98f4609a2a3291dF64E246f01/info.json
  blockchains/smartchain/assets/0xB5bCF4fAa81457e98f4609a2a3291dF64E246f01/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14025 add Alkemi Network ALK
  blockchains/ethereum/assets/0x6C16119B20fa52600230F074b349dA3cb861a7e3/info.json
  blockchains/ethereum/assets/0x6C16119B20fa52600230F074b349dA3cb861a7e3/logo.png
Labels: Payment Status: Paid

#14012 Add Adamant (BEP20)
  blockchains/smartchain/assets/0xA55EF2fB2B7b6A60371FD3def9B806E74a48bE69/info.json
  blockchains/smartchain/assets/0xA55EF2fB2B7b6A60371FD3def9B806E74a48bE69/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#13990 Add NFTLaunch.network (BEP20)
  blockchains/smartchain/assets/0xb8e3bB633F7276cc17735D86154E0ad5ec9928C0/info.json
  blockchains/smartchain/assets/0xe7F72Bc0252cA7B16dBb72eEee1AfcDb2429F2DD/info.json
  blockchains/smartchain/assets/0xe7F72Bc0252cA7B16dBb72eEee1AfcDb2429F2DD/logo.png
Labels: Payment Status: Paid

#14036 Add EMP Token logo and infos
  blockchains/smartchain/assets/0x86A45b508a375ac8f0FD387e7532B70f71291152/info.json
  blockchains/smartchain/assets/0x86A45b508a375ac8f0FD387e7532B70f71291152/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14052 [Internal] Adjust assignee github users.
  .github/merge-fee-bot.yaml
Labels: Payment Status: Requested

#14049 change status to abandoned for old Burn1 (BEP20)
  blockchains/smartchain/assets/0x07e330A210B8128c7b32476704C3052cD8c10e5b/info.json
Labels: Payment Status: Requested

#14056 change status to abandoned for LIGHT
  blockchains/smartchain/assets/0x7B9c3Df47F3326FbC0674d51dc3EB0f2Df29F37F/info.json
Labels: Payment Status: Requested

#14057 Remove logo for Burn1
  blockchains/smartchain/assets/0x07e330A210B8128c7b32476704C3052cD8c10e5b/logo.png
Labels: Payment Status: Requested

#14058 Remove logo for old LIGHT
  blockchains/smartchain/assets/0x7B9c3Df47F3326FbC0674d51dc3EB0f2Df29F37F/logo.png
Labels: Payment Status: Requested

#14046 add logo
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/info.json
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14045 Add Burn1 Coin Logo
  blockchains/smartchain/assets/0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43/info.json
  blockchains/smartchain/assets/0x31A9042dCE0C13975D04d0E9758Cb7B596F0dD43/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14064 add MUSK logo and info
  blockchains/smartchain/assets/0xcD657182A749554fc8487757612F02226355269d/info.json
  blockchains/smartchain/assets/0xcD657182A749554fc8487757612F02226355269d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14022 Added new Contract Address for $LIGHT
  blockchains/smartchain/assets/0x037838b556d9c9d654148a284682C55bB5f56eF4/info.json
  blockchains/smartchain/assets/0x037838b556d9c9d654148a284682C55bB5f56eF4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14072 Add CZFarm (BEP20)
  blockchains/smartchain/assets/0x7c1608C004F20c3520f70b924E2BfeF092dA0043/info.json
  blockchains/smartchain/assets/0x7c1608C004F20c3520f70b924E2BfeF092dA0043/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14018 Added XLD logo and info
  blockchains/smartchain/assets/0xC79d1fD14F514cD713b5cA43D288a782Ae53eAb2/info.json
  blockchains/smartchain/assets/0xC79d1fD14F514cD713b5cA43D288a782Ae53eAb2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14075 Change logo for MRC (BEP20)
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/logo.png
Labels: Payment Status: Requested

#14070 Add BABYSPACEFLOKI (BEP20)
  blockchains/smartchain/assets/0x689437C050678935DB89381fE0B8F6ED4A3eec66/info.json
  blockchains/smartchain/assets/0x689437C050678935DB89381fE0B8F6ED4A3eec66/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14079 Add $XTRA Tara Platform (BEP20)
  blockchains/smartchain/assets/0x5F02C4Dcb270999282b850Caa47Af749Ce49FE00/info.json
  blockchains/smartchain/assets/0x5F02C4Dcb270999282b850Caa47Af749Ce49FE00/logo.png
Labels: Payment Status: Paid

#14031 Add BonusCake logo and info
  blockchains/smartchain/assets/0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a/info.json
  blockchains/smartchain/assets/0xb84ddc645c27D4Dc4bFA325c946f9d89d3AfCc7a/logo.png
Labels: Payment Status: Paid

#14081 Add Pokmi (BEP20)
  blockchains/smartchain/assets/0x4B5DeCb9327B4D511A58137A1aDE61434AacdD43/info.json
  blockchains/smartchain/assets/0x4B5DeCb9327B4D511A58137A1aDE61434AacdD43/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14078 Adding Dynamix Logo and info.json
  blockchains/smartchain/assets/0xc41689A727469C1573009757200371edf36D540e/info.json
  blockchains/smartchain/assets/0xc41689A727469C1573009757200371edf36D540e/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14104 [Internal] Fix for Binance token update, exclude tokens with no decimals
  script/blockchain/binance.ts
Labels: Payment Status: Paid, Payment Status: Requested

#14110 Update Pokmi logo
  blockchains/smartchain/assets/0x4B5DeCb9327B4D511A58137A1aDE61434AacdD43/logo.png
Labels: Payment Status: Requested

#14102 Update Bcoin (BEP20)
  blockchains/smartchain/assets/0x00e1656e45f18ec6747F5a8496Fd39B50b38396D/info.json
  blockchains/smartchain/assets/0x00e1656e45f18ec6747F5a8496Fd39B50b38396D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14093 Add SADBABY (BEP20)
  blockchains/smartchain/assets/0x3AD405ef7AeA80CCb41beEf0a74510e18Feef190/info.json
  blockchains/smartchain/assets/0x3AD405ef7AeA80CCb41beEf0a74510e18Feef190/logo.png
Labels: Payment Status: Requested

#14123 Delete validators TERRA
  blockchains/terra/validators/assets/terravaloper163phlen6dn7sp9khhjar2gqqx6kga0ly8d7h9g/logo.png
  blockchains/terra/validators/assets/terravaloper1d3hatwcsvkktgwp3elglw9glca0h42yg6xy4lp/logo.png
  blockchains/terra/validators/assets/terravaloper1eutun6vh83lmyq0wmyf9vgghvurze2xanl9sq6/logo.png
  blockchains/terra/validators/assets/terravaloper1rgu3qmm6rllfxlrfk94pgxa0jm37902dynqehm/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid

#14120 update logo
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/info.json
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/logo.png
Labels: Payment Status: Paid

#14137 [Internal] Add Wrapped MATIC (POLYGON)
  blockchains/polygon/assets/0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270/info.json
  blockchains/polygon/assets/0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14136 [Internal] Infrastructure for Polygon tokenlist
  blockchains/polygon/tokenlist.json
  script/blockchain/polygon.ts
  script/config.ts
  script/generic/subgraph.ts
  script/generic/update-all.ts
Labels: Payment Status: Paid, Payment Status: Requested

#14095 Add new BSL Token
  blockchains/ethereum/assets/0x26a79Bd709A7eF5E5F747B8d8f83326EA044d8cC/info.json
  blockchains/smartchain/assets/0x0AF55d5fF28A3269d69B98680Fd034f115dd53Ac/info.json
  blockchains/smartchain/assets/0x0AF55d5fF28A3269d69B98680Fd034f115dd53Ac/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#14042 Add Gamezone info
  blockchains/smartchain/assets/0xb6ADB74efb5801160Ff749b1985Fd3bD5000e938/info.json
  blockchains/smartchain/assets/0xb6ADB74efb5801160Ff749b1985Fd3bD5000e938/logo.png
Labels: Payment Status: Paid

#14146 updated BSL logo
  blockchains/smartchain/assets/0x0AF55d5fF28A3269d69B98680Fd034f115dd53Ac/logo.png
Labels: Payment Status: Requested

#14143 Add Kodi (BEP20)
  blockchains/smartchain/assets/0x7f4f3BC4A5634454398580b9112b7E493E2129Fa/info.json
  blockchains/smartchain/assets/0x7f4f3BC4A5634454398580b9112b7E493E2129Fa/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14152 Update ChainCade Logo and Info (BEP20)
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/info.json
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#14186 Add Wagyuswap.org (BEP20)
  blockchains/smartchain/assets/0x7FA7dF4996AC59F398476892cfB195eD38543520/info.json
  blockchains/smartchain/assets/0x7FA7dF4996AC59F398476892cfB195eD38543520/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14185 Add Swapz.app (BEP20)
  blockchains/smartchain/assets/0xd522A1DcE1CA4B138DDA042a78672307eb124CC2/info.json
  blockchains/smartchain/assets/0xd522A1DcE1CA4B138DDA042a78672307eb124CC2/logo.png
Labels: Payment Status: Paid

#14195 Add UMG logo and info.
  blockchains/smartchain/assets/0xA73505453F58E367c80F16685079dAD6f4EA6b18/info.json
  blockchains/smartchain/assets/0xA73505453F58E367c80F16685079dAD6f4EA6b18/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#14174 Add Polkadog (EINSTEIN)
  blockchains/smartchain/assets/0xBd65a197408230247F05247A71D1A9Aea9Db0C3c/info.json
  blockchains/smartchain/assets/0xBd65a197408230247F05247A71D1A9Aea9Db0C3c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14217 append MPress
  blockchains/kava/validators/assets/kavavaloper13rzkukgxsae26tn2h6vuhlrdxap6rzrc29uhmq/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#14244 Add CRIR MSH (BEP20)
  blockchains/smartchain/assets/0xEae2BBBC0000F605bD37A02c7fE346a3b68B03eb/info.json
  blockchains/smartchain/assets/0xEae2BBBC0000F605bD37A02c7fE346a3b68B03eb/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14246 Logo update due to previous request
  blockchains/smartchain/assets/0x7EaeE60040135F20f508A393ca400dEd339d654e/info.json
  blockchains/smartchain/assets/0x7EaeE60040135F20f508A393ca400dEd339d654e/logo.png
Labels: Payment Status: Paid

#14243 Add Buff Doge Coin Logo and Info
  blockchains/smartchain/assets/0x23125108bc4c63E4677b2E253Fa498cCb4B3298b/info.json
  blockchains/smartchain/assets/0x23125108bc4c63E4677b2E253Fa498cCb4B3298b/logo.png
Labels: Payment Status: Paid

#14199 Add token BAGEL once more
  blockchains/smartchain/assets/0xBb238FcE6E2eE90781cD160C9C6eAf3a4CfAD801/info.json
  blockchains/smartchain/assets/0xBb238FcE6E2eE90781cD160C9C6eAf3a4CfAD801/logo.png
Labels: Payment Status: Paid

#14240 Add BNB Cash
  blockchains/smartchain/assets/0x840BCd536d647C3433bF830DBCb8debFa5B71c79/info.json
  blockchains/smartchain/assets/0x840BCd536d647C3433bF830DBCb8debFa5B71c79/logo.png
Labels: Payment Status: Paid

#14197 Add Coin Discovery Token (BEP20)
  blockchains/smartchain/assets/0x4AC32178097c1f62beadCC2D215B54D6915013ee/info.json
  blockchains/smartchain/assets/0x4AC32178097c1f62beadCC2D215B54D6915013ee/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14296 feat(dogebull): added logo and info
  blockchains/smartchain/assets/0xbD4a49e1a0bd8D17fAa881D057b48BC18b983E51/info.json
  blockchains/smartchain/assets/0xbD4a49e1a0bd8D17fAa881D057b48BC18b983E51/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14312 new logo Binamon
  blockchains/smartchain/assets/0x08ba0619b1e7A582E0BCe5BBE9843322C954C340/info.json
  blockchains/smartchain/assets/0x08ba0619b1e7A582E0BCe5BBE9843322C954C340/logo.png
Labels: Payment Status: Paid

#14326 Update token logo for existing token
  blockchains/smartchain/assets/0xeBC76079Da0c245faE7225b58a57A54809b40618/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14343 Add 867 (BEP20)
  blockchains/smartchain/assets/0x9CEFd9588f076c5f805341864adC8a6F077A5b99/info.json
  blockchains/smartchain/assets/0x9CEFd9588f076c5f805341864adC8a6F077A5b99/logo.png
Labels: Payment Status: Paid

#14340 Binamon Energy add token
  blockchains/smartchain/assets/0x08ba0619b1e7A582E0BCe5BBE9843322C954C340/info.json
  blockchains/smartchain/assets/0x80E15FE54e9D155f8366187A6a32BDEF9C2366c4/info.json
  blockchains/smartchain/assets/0xd8813B5Dfa9AbEB693F217Bb905ec99B66FB017C/info.json
  blockchains/smartchain/assets/0xd8813B5Dfa9AbEB693F217Bb905ec99B66FB017C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14377 Continue to pull request #12838
  blockchains/tron/assets/TWmocwvHpui48QXUVJeW2SvcFe8LyNgLCU/info.json
  blockchains/tron/assets/TWmocwvHpui48QXUVJeW2SvcFe8LyNgLCU/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14373 add YAY token
  blockchains/smartchain/assets/0x524dF384BFFB18C0C8f3f43d012011F8F9795579/info.json
  blockchains/smartchain/assets/0x524dF384BFFB18C0C8f3f43d012011F8F9795579/logo.png
Labels: Payment Status: Paid

#14341 Add TWT logo and info
  blockchains/smartchain/assets/0x16dCc0eC78E91e868DCa64bE86aeC62bf7C61037/info.json
  blockchains/smartchain/assets/0x16dCc0eC78E91e868DCa64bE86aeC62bf7C61037/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14356 Add Logo + Info to Xenon Play [Urgent]
  blockchains/smartchain/assets/0xB7FeEAb5ea787e83a40f185237C717597363E0d6/info.json
  blockchains/smartchain/assets/0xB7FeEAb5ea787e83a40f185237C717597363E0d6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14397 Add High logo and info
  blockchains/ethereum/assets/0x71Ab77b7dbB4fa7e017BC15090b2163221420282/info.json
  blockchains/ethereum/assets/0x71Ab77b7dbB4fa7e017BC15090b2163221420282/logo.png
  blockchains/smartchain/assets/0x5f4Bde007Dc06b867f86EBFE4802e34A1fFEEd63/info.json
  blockchains/smartchain/assets/0x5f4Bde007Dc06b867f86EBFE4802e34A1fFEEd63/logo.png
Labels: Payment Status: Paid

#14324 Updating logo for Frosted Cake BEP-20 token
  blockchains/smartchain/assets/0x94ba29d58D419BD798B282476db3Dd9d97BA8C23/info.json
  blockchains/smartchain/assets/0x94ba29d58D419BD798B282476db3Dd9d97BA8C23/logo.png
Labels: Status: On Hold, Payment Status: Paid

#14410 Update ChainCade Logo (BEP20)
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/info.json
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/logo.png
Labels: Payment Status: Paid

#14406 request to add CNS token
  blockchains/smartchain/assets/0xF6Cb4ad242BaB681EfFc5dE40f7c8FF921a12d63/info.json
  blockchains/smartchain/assets/0xF6Cb4ad242BaB681EfFc5dE40f7c8FF921a12d63/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14429 request to add CNR token
  blockchains/smartchain/assets/0xdCbA3fbd7BBc28abD18A472D28358089467A8a74/info.json
  blockchains/smartchain/assets/0xdCbA3fbd7BBc28abD18A472D28358089467A8a74/logo.png
Labels: Payment Status: Paid

#14414 Adding MON logo and info
  blockchains/smartchain/assets/0x8888818f35BbeD1C632364bf1b15446FAD088888/info.json
  blockchains/smartchain/assets/0x8888818f35BbeD1C632364bf1b15446FAD088888/logo.png
Labels: Payment Status: Paid

#14417 Add Red Floki (BEP20)
  blockchains/smartchain/assets/0x2A3E1D095F2902C9B6Da1bFF7813a7B2fc65C3dA/info.json
  blockchains/smartchain/assets/0x2A3E1D095F2902C9B6Da1bFF7813a7B2fc65C3dA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14261 Add files via upload
  blockchains/smartchain/assets/0x4DB2495AfAd4c0E481fFc40FDaF66E13A786b619/info.json
  blockchains/smartchain/assets/0x4DB2495AfAd4c0E481fFc40FDaF66E13A786b619/logo.png
Labels: Status: On Hold, Payment Status: Paid

#14419 add and update info
  blockchains/smartchain/assets/0x17D749D3E2ac204a07e19D8096d9a05c423ea3af/info.json
  dapps/newlittlerabbit.net.png
Labels: Payment Status: Paid, Payment Status: Requested

#14434 Update ChainCade Logo (BEP20)
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/info.json
  blockchains/smartchain/assets/0x2FFEE7b4DF74F7C6508A4Af4D6D91058dA5420D0/logo.png
Labels: Payment Status: Paid

#14268 Add KST Token PLEASE READ the comment!
  blockchains/ethereum/assets/0xBc17729fDf562723f0267F79FF25aDE441056d87/info.json
  blockchains/ethereum/assets/0xBc17729fDf562723f0267F79FF25aDE441056d87/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#14438 Add ZOE CASH (BEP20)
  blockchains/smartchain/assets/0x8D2b2e3dcF0BcaD65765D256390c5154D3Ba19cF/info.json
  blockchains/smartchain/assets/0x8D2b2e3dcF0BcaD65765D256390c5154D3Ba19cF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14444 Add Ownix (ONX) (ERC20)
  blockchains/ethereum/assets/0xcF78C7dD70d6F30F6E3609e905e78305Da98c863/info.json
  blockchains/ethereum/assets/0xcF78C7dD70d6F30F6E3609e905e78305Da98c863/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14481 Add RPG Token
  blockchains/smartchain/assets/0xc2098a8938119A52B1F7661893c0153A6CB116d5/info.json
  blockchains/smartchain/assets/0xc2098a8938119A52B1F7661893c0153A6CB116d5/logo.png
Labels: Payment Status: Paid

#14445 Add BitUp
  blockchains/smartchain/assets/0x28A27ba716d306c842a4b5dA20a42e1d4D1E8d6b/info.json
  blockchains/smartchain/assets/0x28A27ba716d306c842a4b5dA20a42e1d4D1E8d6b/logo.png
Labels: Payment Status: Paid

#14505 Add StrikeX (BEP20)
  blockchains/smartchain/assets/0xd6fDDe76B8C1C45B33790cc8751D5b88984c44ec/info.json
  blockchains/smartchain/assets/0xd6fDDe76B8C1C45B33790cc8751D5b88984c44ec/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14467 Add Kampay (BEP20)
  blockchains/smartchain/assets/0x8E984e03ab35795C60242c902ECe2450242C90e9/info.json
  blockchains/smartchain/assets/0x8E984e03ab35795C60242c902ECe2450242C90e9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14539 Add THORSwap token (ERC20)
  blockchains/ethereum/assets/0xa5f2211B9b8170F694421f2046281775E8468044/info.json
  blockchains/ethereum/assets/0xa5f2211B9b8170F694421f2046281775E8468044/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14552 Add Xtremcoin (BEP20)
  blockchains/smartchain/assets/0x927fF4AD97991C1eeC44AB02c6970088ffa85250/info.json
  blockchains/smartchain/assets/0x927fF4AD97991C1eeC44AB02c6970088ffa85250/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14526 Adding Doge Dash token
  blockchains/smartchain/assets/0x7AE5709c585cCFB3e61fF312EC632C21A5F03F70/info.json
  blockchains/smartchain/assets/0x7AE5709c585cCFB3e61fF312EC632C21A5F03F70/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14760 Emergency: OS Address switch
  blockchains/ethereum/assets/0x6100dd79fCAA88420750DceE3F735d168aBcB771/info.json
  blockchains/ethereum/assets/0x6100dd79fCAA88420750DceE3F735d168aBcB771/logo.png
  blockchains/ethereum/assets/0xFdB29741F239a2406AE287913Ef12415160378d3/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#14765 Add Baby Doge Money Maker
  blockchains/smartchain/assets/0xEc3D04C82aF8C4b97Ecd058D543c2c0673ca72dC/info.json
  blockchains/smartchain/assets/0xEc3D04C82aF8C4b97Ecd058D543c2c0673ca72dC/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14818 Add Futura Finance logo and info
  blockchains/smartchain/assets/0x183B2c147fE11788b73BC0D6A7E0186aA5464BfA/info.json
  blockchains/smartchain/assets/0x183B2c147fE11788b73BC0D6A7E0186aA5464BfA/logo.png
Labels: Payment Status: Paid

#14832 Add NFT Global (BEP20)
  blockchains/smartchain/assets/0x76F6cd75cE81E88916f8D933ab76efE18cEd6ad3/info.json
  blockchains/smartchain/assets/0x76F6cd75cE81E88916f8D933ab76efE18cEd6ad3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14804 Baby Floki Doge Trust Wallet logo
  blockchains/smartchain/assets/0xe24F6Bc7635501d5684a963f7e75C8062b9c0eA4/info.json
  blockchains/smartchain/assets/0xe24F6Bc7635501d5684a963f7e75C8062b9c0eA4/logo.png
Labels: Payment Status: Paid

#14788 Add Logo and Info for Lil Floki (BEP-20)
  blockchains/smartchain/assets/0x3271D12D5ba36B6582fafA029598FEe0F5F6Db35/info.json
  blockchains/smartchain/assets/0x3271D12D5ba36B6582fafA029598FEe0F5F6Db35/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14834 Add JINDO INU (BEP20)
  blockchains/smartchain/assets/0x5fEAD99998788AC1BCA768796483d899F1Aef4c4/info.json
  blockchains/smartchain/assets/0x5fEAD99998788AC1BCA768796483d899F1Aef4c4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14824 Added PancakePoll to Trust Wallet
  blockchains/smartchain/assets/0xc29000A4b1eCD326b6DafAE17bDA636475FeA1e7/info.json
  blockchains/smartchain/assets/0xc29000A4b1eCD326b6DafAE17bDA636475FeA1e7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14821 Adding ADACash Logo to Trustwallet
  blockchains/smartchain/assets/0x651a89fed302227d41425235F8E934502FB94C48/info.json
  blockchains/smartchain/assets/0x651a89fed302227d41425235F8E934502FB94C48/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14854 Add logo ShibaZilla
  blockchains/smartchain/assets/0xD00A7EdD637B776eC5a6461F5e7ac055F14a0C1E/info.json
  blockchains/smartchain/assets/0xD00A7EdD637B776eC5a6461F5e7ac055F14a0C1E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14846 Add bPRIVA (BEP20)
  blockchains/smartchain/assets/0xD0f4afA85a667d27837e9c07c81169869c16Dd16/info.json
  blockchains/smartchain/assets/0xD0f4afA85a667d27837e9c07c81169869c16Dd16/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14731 Add ETA to trust wallet
  blockchains/smartchain/assets/0x90727C1195fB2246fd758172f9253873790d06a4/info.json
  blockchains/smartchain/assets/0x90727C1195fB2246fd758172f9253873790d06a4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14826 Hero Floki
  blockchains/smartchain/assets/0x5d96991648d22935Bdf6c7064B65c3c93F82Aa61/info.json
  blockchains/smartchain/assets/0x5d96991648d22935Bdf6c7064B65c3c93F82Aa61/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14783 Add CQT
  blockchains/ethereum/assets/0xD417144312DbF50465b1C641d016962017Ef6240/info.json
  blockchains/ethereum/assets/0xD417144312DbF50465b1C641d016962017Ef6240/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14825 Add Next Token (BEP20)
  blockchains/smartchain/assets/0x8e428aA75b271EbF905DB7e3F2970453E976481e/info.json
  blockchains/smartchain/assets/0x8e428aA75b271EbF905DB7e3F2970453E976481e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#14857 Add Squidanomics (BEP20)
  blockchains/smartchain/assets/0x1F878d0BccD3D502ff55F7a4797C556f103d6e4b/info.json
  blockchains/smartchain/assets/0x1F878d0BccD3D502ff55F7a4797C556f103d6e4b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14864 Add AnpanSwap Token (BEP20)
  blockchains/smartchain/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/info.json
  blockchains/smartchain/assets/0x10B0a78520fBDDa95aDc331445d9319B164F85D5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#14865 Add Piccolo Inu (ERC20)
  blockchains/ethereum/assets/0x3a1311B8C404629E38f61D566cefEFed083B9670/info.json
  blockchains/ethereum/assets/0x3a1311B8C404629E38f61D566cefEFed083B9670/logo.png
Labels: Payment Status: Paid

#14868 Add MagicDOGE (BEP20)
  blockchains/smartchain/assets/0x46568808a8d73c301071b8dF710402Ce44F1C472/info.json
  blockchains/smartchain/assets/0x46568808a8d73c301071b8dF710402Ce44F1C472/logo.png
Labels: Payment Status: Paid

#14912 Add Mind Music (BEP20)
  blockchains/smartchain/assets/0x897304D4606B2d5FcAf886aa7AA143e478EC36C5/info.json
  blockchains/smartchain/assets/0x897304D4606B2d5FcAf886aa7AA143e478EC36C5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
