Repository trustwallet/assets, pull requests merged in 2022-10, with the labels that each got.

#22588 Add BabyApeFunClub (BEP20)
  blockchains/smartchain/assets/0x035aD59058c557be4532141FBCD60f0998fCE413/info.json
  blockchains/smartchain/assets/0x035aD59058c557be4532141FBCD60f0998fCE413/logo.png
Labels: Payment Status: Paid

#22611 Add Bazaars (BZR) (ERC20)
  blockchains/ethereum/assets/0x8d96B4ab6C741a4C8679AE323a100d74f085BA8F/info.json
  blockchains/ethereum/assets/0x8d96B4ab6C741a4C8679AE323a100d74f085BA8F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22608 Add Tamadoge (TAMA) (ERC20)
  blockchains/ethereum/assets/0x12b6893cE26Ea6341919FE289212ef77e51688c8/info.json
  blockchains/ethereum/assets/0x12b6893cE26Ea6341919FE289212ef77e51688c8/logo.png
Labels: Payment Status: Paid

#22627 Add Lego Coin
  blockchains/smartchain/assets/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC/info.json
  blockchains/smartchain/assets/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC/logo.png
Labels: Payment Status: Paid

#22331 Add PointPay Crypto Banking Token V2 (ERC20)
  blockchains/ethereum/assets/0x95aA5d2DbD3c16ee3fdea82D5C6EC3E38CE3314f/info.json
  blockchains/ethereum/assets/0x95aA5d2DbD3c16ee3fdea82D5C6EC3E38CE3314f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22648 Add vEmpire DDAO (VEMP) (BEP20)
  blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/info.json
  blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22647 Add vEmpire DDAO (VEMP) (ERC20)
  blockchains/ethereum/assets/0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC/info.json
  blockchains/ethereum/assets/0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC/logo.png
Labels: Payment Status: Requested

#22625 Add W3C info and logo
  blockchains/smartchain/assets/0x2fa6ee42BacF983F050210A1ca42f88686327FC9/info.json
  blockchains/smartchain/assets/0x2fa6ee42BacF983F050210A1ca42f88686327FC9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22668 FCF logo, tag, description update
  blockchains/smartchain/assets/0x4673f018cc6d401AAD0402BdBf2abcBF43dd69F3/info.json
  blockchains/smartchain/assets/0x4673f018cc6d401AAD0402BdBf2abcBF43dd69F3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22682 Add PALM (BEP20)
  blockchains/smartchain/assets/0x29745314B4D294B7C77cDB411B8AAa95923aae38/info.json
  blockchains/smartchain/assets/0x29745314B4D294B7C77cDB411B8AAa95923aae38/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22642 Add Bit Hotel Token (BEP20)
  blockchains/smartchain/assets/0x57Bc18F6177cDafFb34aCE048745bc913a1B1b54/info.json
  blockchains/smartchain/assets/0x57Bc18F6177cDafFb34aCE048745bc913a1B1b54/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22685 info for BendDAO Token(ERC20)
  blockchains/ethereum/assets/0x0d02755a5700414B26FF040e1dE35D337DF56218/info.json
  blockchains/ethereum/assets/0x0d02755a5700414B26FF040e1dE35D337DF56218/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22688 Add Bombcrypto Coin (POLYGON)
  blockchains/polygon/assets/0xB2C63830D4478cB331142FAc075A39671a5541dC/info.json
  blockchains/polygon/assets/0xB2C63830D4478cB331142FAc075A39671a5541dC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22686 Add Legion Network (BEP20)
  blockchains/smartchain/assets/0x9096B4309224d751FCB43d7eB178dcFFc122aD15/info.json
  blockchains/smartchain/assets/0x9096B4309224d751FCB43d7eB178dcFFc122aD15/logo.png
Labels: Payment Status: Paid

#22701 Add Pax Gold (POLYGON)
  blockchains/polygon/assets/0x553d3D295e0f695B9228246232eDF400ed3560B5/info.json
  blockchains/polygon/assets/0x553d3D295e0f695B9228246232eDF400ed3560B5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22707 Add Renewable Energy Token (BEP20)
  blockchains/smartchain/assets/0x10b9dd394467f2CFbc769e07E88dC7e2c41B0965/info.json
  blockchains/smartchain/assets/0x10b9dd394467f2CFbc769e07E88dC7e2c41B0965/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22694 Add Lunar (BEP20)
  blockchains/smartchain/assets/0xc1A59a17F87ba6651Eb8E8F707db7672647c45bD/info.json
  blockchains/smartchain/assets/0xc1A59a17F87ba6651Eb8E8F707db7672647c45bD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22722 Add chainlist and EthereumPoW
  .github/assets.config.yaml
  blockchains/ethereum/chainlist.json
  blockchains/ethereumpow/info/info.json
  blockchains/ethereumpow/info/logo.png
Labels: Payment Status: Paid

#22723 Format chainlist.json
  blockchains/ethereum/chainlist.json
Labels: Payment Status: Requested

#22721 Add Cardano validators
  blockchains/cardano/validators/assets/pool10akpqvczl93ep4rc59c0aqyn3dm0env2ydysuwmdm670wl24pd8/logo.png
  blockchains/cardano/validators/assets/pool12z39rkzfylvn9wfe8j6x9ucq6g2l4mw4azj70y0gd8ejczznyj3/logo.png
  blockchains/cardano/validators/assets/pool16agnvfan65ypnswgg6rml52lqtcqe5guxltexkn82sqgj2crqtx/logo.png
  blockchains/cardano/validators/assets/pool16fyda57p3c8gp5r6gmcq5tvqsp6mnzwvkxswgznkuh8wztrp6vv/logo.png
  blockchains/cardano/validators/assets/pool17rjst78s67lvellg8s586rf076jxa3wnsdz730f4xk2zwuhrtej/logo.png
  blockchains/cardano/validators/assets/pool195gdnmj6smzuakm4etxsxw3fgh8asqc4awtcskpyfnkpcvh2v8t/logo.png
  blockchains/cardano/validators/assets/pool19w5khsnmu27au0kprw0kjm8jr7knneysj7lfkqvnu66hyz0jxsx/logo.png
  blockchains/cardano/validators/assets/pool1ju8f57hyvaa32tp85r468kuedvmjmcy56f8u9968drea57p50l5/logo.png
  blockchains/cardano/validators/assets/pool1qqqqdktl6pq46td0mwut0qn30g7nlue0sete9wxl0hwsq37wrw8/logo.png
  blockchains/cardano/validators/assets/pool1vx9tzlkgafernd9vpjpxkenutx2gncj4yn88fpq69823qlwcqrt/logo.png
  blockchains/cardano/validators/list.json
Labels: Payment Status: Paid

#22728 Add Ethereum pow chain
  blockchains/ethereum/chainlist.json
Labels: Payment Status: Requested

#22763 Change logo for Injective
  blockchains/ethereum/assets/0xe28b3B32B6c345A34Ff64674606124Dd5Aceca30/logo.png
  blockchains/smartchain/assets/0xa2B726B1145A4773F68593CF171187d8EBe4d495/info.json
  blockchains/smartchain/assets/0xa2B726B1145A4773F68593CF171187d8EBe4d495/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#22774 Add Offshore Plan (BEP20)
  blockchains/smartchain/assets/0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef/info.json
  blockchains/smartchain/assets/0xDD3162aD2185928bf3D92Bc05174Aa442E7382Ef/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22746 add tcc logo and info
  blockchains/smartchain/assets/0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2/info.json
  blockchains/smartchain/assets/0x6A684b3578f5B07c0Aa02fAFc33ED248AE0c2dB2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22783 Add DAO Maker (BEP20)
  blockchains/smartchain/assets/0x4d2d32d8652058Bf98c772953E1Df5c5c85D9F45/info.json
  blockchains/smartchain/assets/0x4d2d32d8652058Bf98c772953E1Df5c5c85D9F45/logo.png
Labels: Payment Status: Paid

#22695 Add XSGD (POLYGON)
  blockchains/polygon/assets/0xDC3326e71D45186F113a2F448984CA0e8D201995/info.json
  blockchains/polygon/assets/0xDC3326e71D45186F113a2F448984CA0e8D201995/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22788 Add logo and info Mafagafo project
  blockchains/smartchain/assets/0x6Dd60AFB2586D31Bf390450aDf5E6A9659d48c4A/info.json
  blockchains/smartchain/assets/0x6Dd60AFB2586D31Bf390450aDf5E6A9659d48c4A/logo.png
Labels: Payment Status: Paid

#22801 Update info.json for ton blockchain
  blockchains/ton/info/info.json
Labels: Payment Status: Requested

#22819 Add new blockchains
  blockchains/canto/info/info.json
  blockchains/canto/info/logo.png
  blockchains/dogechain/info/info.json
  blockchains/dogechain/info/logo.png
  blockchains/ethereum/chainlist.json
  blockchains/fusion/info/info.json
  blockchains/fusion/info/logo.png
  blockchains/hoo/info/info.json
  blockchains/hoo/info/logo.png
  blockchains/okxchain/info/info.json
  blockchains/okxchain/info/logo.png
Labels: Payment Status: Paid

#22824 Add KOL logo and token information
  blockchains/smartchain/assets/0x6a731582f6189477c379A8da7d26Dcec3F0a0919/info.json
  blockchains/smartchain/assets/0x6a731582f6189477c379A8da7d26Dcec3F0a0919/logo.png
Labels: Payment Status: Paid

#22804 Add GG TOKEN (BEP20)
  blockchains/smartchain/assets/0x1F7e8fe01AEbA6fDAEA85161746f4D53DC9bdA4F/info.json
  blockchains/smartchain/assets/0x1F7e8fe01AEbA6fDAEA85161746f4D53DC9bdA4F/logo.png
Labels: Status: On Hold, Payment Status: Paid

#22832 Add RTC_Plus (BEP20)
  blockchains/smartchain/assets/0x1d507f58e4B7CDdE877CA96A727608d5E1187E55/info.json
  blockchains/smartchain/assets/0x1d507f58e4B7CDdE877CA96A727608d5E1187E55/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22690 Add ZOMBIE SKRAT (BEP20)
  blockchains/smartchain/assets/0x49954Ad438fa9e27C21AeCd35078dD52cDDd96be/info.json
  blockchains/smartchain/assets/0x49954Ad438fa9e27C21AeCd35078dD52cDDd96be/logo.png
Labels: Payment Status: Paid

#22875 Add Clever Minu (POLYGON)
  blockchains/polygon/assets/0x155AB9Cd3655Aa6174E1e743a6DA1E208762b03d/info.json
  blockchains/polygon/assets/0x155AB9Cd3655Aa6174E1e743a6DA1E208762b03d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22881 Add FRZ Swapping (BEP20)
  blockchains/smartchain/assets/0x2a5dFE9EDd6D1431eecEA70cBb1635Ba88347BaD/info.json
  blockchains/smartchain/assets/0x2a5dFE9EDd6D1431eecEA70cBb1635Ba88347BaD/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
