Repository trustwallet/assets, pull requests merged in 2022-03, with the labels that each got.

#18393 Add Defina Token (BEP20)
  blockchains/smartchain/assets/0x426c72701833fdDBdFc06c944737C6031645c708/info.json
  blockchains/smartchain/assets/0x426c72701833fdDBdFc06c944737C6031645c708/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18533 Add MetaPortal Gaming Index (ERC20)
  blockchains/ethereum/assets/0xa1EA9aA32CBba8c203DDC510a144aD1F439d436c/info.json
  blockchains/ethereum/assets/0xa1EA9aA32CBba8c203DDC510a144aD1F439d436c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18636 Add Quantic (BEP20)
  blockchains/smartchain/assets/0x7700Edc3DBb30cBB7603212E061c804220c3cA54/info.json
  blockchains/smartchain/assets/0x7700Edc3DBb30cBB7603212E061c804220c3cA54/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18639 Add SHIP (BEP20)
  blockchains/smartchain/assets/0xC0A696BBb66352E5b88624F1d1B8909C34Dc4E4a/info.json
  blockchains/smartchain/assets/0xC0A696BBb66352E5b88624F1d1B8909C34Dc4E4a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18554 Add DYOR Token (BEP20)
  blockchains/smartchain/assets/0x10051147418C42218986CeDD0aDC266441F8a14f/info.json
  blockchains/smartchain/assets/0x10051147418C42218986CeDD0aDC266441F8a14f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18611 Add FROYO (BEP20)
  blockchains/smartchain/assets/0xe369fec23380f9F14ffD07a1DC4b7c1a9fdD81c9/info.json
  blockchains/smartchain/assets/0xe369fec23380f9F14ffD07a1DC4b7c1a9fdD81c9/logo.png
Labels: Payment Status: Paid

#18655 Migration for BNBPay (BEP20)
  blockchains/smartchain/assets/0xeBC76079Da0c245faE7225b58a57A54809b40618/info.json
  blockchains/smartchain/assets/0xeBC76079Da0c245faE7225b58a57A54809b40618/logo.png
Labels: Payment Status: Paid

#18618 Add PayBolt Token (ERC20, BEP20, POLYGON)
  blockchains/ethereum/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/info.json
  blockchains/ethereum/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/logo.png
  blockchains/polygon/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/info.json
  blockchains/polygon/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/logo.png
  blockchains/smartchain/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/info.json
  blockchains/smartchain/assets/0xe580074A10360404AF3ABfe2d524D5806D993ea3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18651 Add Lunar (BEP20)
  blockchains/smartchain/assets/0x9D4451151A8dE5B545a1bC6c8fdEB9d94a2868e1/info.json
  blockchains/smartchain/assets/0x9D4451151A8dE5B545a1bC6c8fdEB9d94a2868e1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18649 Add BLP & GMPD (BEP-20)
  blockchains/smartchain/assets/0x9720CA160Bbd4E7f3dD4bb3f8BD4227ca0342e63/info.json
  blockchains/smartchain/assets/0x9720CA160Bbd4E7f3dD4bb3f8BD4227ca0342e63/logo.png
  blockchains/smartchain/assets/0xfE1d7f7a8f0bdA6E415593a2e4F82c64b446d404/info.json
  blockchains/smartchain/assets/0xfE1d7f7a8f0bdA6E415593a2e4F82c64b446d404/logo.png
Labels: Payment Status: Paid

#18658 Add RUBY (BEP20)
  blockchains/smartchain/assets/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e/info.json
  blockchains/smartchain/assets/0xf7722aA0714096f1FB5ef83e6041CEBB4d58a08e/logo.png
Labels: Payment Status: Paid

#18681 Add NINO logo and info
  blockchains/smartchain/assets/0x6CAD12b3618a3C7ef1FEb6C91FdC3251f58c2a90/info.json
  blockchains/smartchain/assets/0x6CAD12b3618a3C7ef1FEb6C91FdC3251f58c2a90/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18662 Add Quantum Assets Token (BEP20)
  blockchains/smartchain/assets/0x4ef29F3B804C316bA8bA464A765C601Fc092a2e9/info.json
  blockchains/smartchain/assets/0x4ef29F3B804C316bA8bA464A765C601Fc092a2e9/logo.png
Labels: Payment Status: Paid

#18668 Add TRAVEL logo and info
  blockchains/smartchain/assets/0x826e5Ec70DbC5607fF9218011FBb97F9a8D97953/info.json
  blockchains/smartchain/assets/0x826e5Ec70DbC5607fF9218011FBb97F9a8D97953/logo.png
Labels: Payment Status: Paid

#18698 Add BIGH BULL (BEP20)
  blockchains/smartchain/assets/0x0bCF5693655A159bd7D9DC5064de9BD692a7b7C6/info.json
  blockchains/smartchain/assets/0x0bCF5693655A159bd7D9DC5064de9BD692a7b7C6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18736 Add Baby Catcoin (BEP20)
  blockchains/smartchain/assets/0x1Bd5ddCD740F2D13b2255fc325c02509da35C4e4/info.json
  blockchains/smartchain/assets/0x1Bd5ddCD740F2D13b2255fc325c02509da35C4e4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18737 Add ENHANCE (BEP20)
  blockchains/smartchain/assets/0xA001862BA0866Ee3e3a2613fAb5954861452B9Bf/info.json
  blockchains/smartchain/assets/0xA001862BA0866Ee3e3a2613fAb5954861452B9Bf/logo.png
Labels: Payment Status: Paid

#18739 Add Clifford Inu (CLIFF) (ERC20)
  blockchains/ethereum/assets/0x1B9BAF2A3EdeA91eE431f02d449a1044d5726669/info.json
  blockchains/ethereum/assets/0x1B9BAF2A3EdeA91eE431f02d449a1044d5726669/logo.png
Labels: Payment Status: Paid

#18773 Add BEM (BEP20)
  blockchains/smartchain/assets/0x7B86b0836f3454e50C6F6a190cd692bB17da1928/info.json
  blockchains/smartchain/assets/0x7B86b0836f3454e50C6F6a190cd692bB17da1928/logo.png
Labels: Payment Status: Paid

#18780 Add LuckyBlock (BEP20)
  blockchains/smartchain/assets/0x2cD96e8C3FF6b5E01169F6E3b61D28204E7810Bb/info.json
  blockchains/smartchain/assets/0x2cD96e8C3FF6b5E01169F6E3b61D28204E7810Bb/logo.png
Labels: Payment Status: Paid

#18591 what next step to complete the task
  blockchains/smartchain/assets/0x5445451C07E20bA1ca887B6c74d66D358F46D083/info.json
  blockchains/smartchain/assets/0x5445451C07E20bA1ca887B6c74d66D358F46D083/logo.png
Labels: Status: On Hold, Payment Status: Paid

#18788 Add CatBoy (BEP20)
  blockchains/smartchain/assets/0x39C3F75B837EAE0d6d0eA87425Ac99bD646a7B1E/info.json
  blockchains/smartchain/assets/0x39C3F75B837EAE0d6d0eA87425Ac99bD646a7B1E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18789 Update CHN to XCN
  blockchains/ethereum/assets/0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18/info.json
  blockchains/ethereum/assets/0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18389 Add BITLIVE (BEP20)
  blockchains/smartchain/assets/0x449aeD32C1685dbeca28D1aE45462b6156A6096D/info.json
  blockchains/smartchain/assets/0x449aeD32C1685dbeca28D1aE45462b6156A6096D/logo.png
Labels: Payment Status: Paid

#18818 Add SOCA logo and info
  blockchains/smartchain/assets/0x57Af121A8dDb1F9A8FafcF3229c92bF2856A8a29/info.json
  blockchains/smartchain/assets/0x57Af121A8dDb1F9A8FafcF3229c92bF2856A8a29/logo.png
Labels: Payment Status: Paid

#18823 Add CBT logo and info
  blockchains/smartchain/assets/0x7c73967dC8c804Ea028247f5A953052f0CD5Fd58/info.json
  blockchains/smartchain/assets/0x7c73967dC8c804Ea028247f5A953052f0CD5Fd58/logo.png
Labels: Payment Status: Paid

#18798 Add: Go Crypto Me (BEP20)
  blockchains/smartchain/assets/0x9528cCEb678B90dAf02cA5cA45622D5cBaF58A30/info.json
  blockchains/smartchain/assets/0x9528cCEb678B90dAf02cA5cA45622D5cBaF58A30/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18819 Adding 4JNET logo to Trust Wallet
  blockchains/smartchain/assets/0xbfb1a68962Fb4ED040FD3a0a71dC2C2015BCc667/info.json
  blockchains/smartchain/assets/0xbfb1a68962Fb4ED040FD3a0a71dC2C2015BCc667/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18896 Add links for ODDZ (BEP20), (ERC20)
  blockchains/ethereum/assets/0xCd2828fc4D8E8a0eDe91bB38CF64B1a81De65Bf6/info.json
  blockchains/smartchain/assets/0xCD40F2670CF58720b694968698A5514e924F742d/info.json
Labels: Payment Status: Paid

#18901 Update Website & CMC
  blockchains/smartchain/assets/0x97c6825e6911578A515B11e25B552Ecd5fE58dbA/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#18899 Add Fairface Token (BEP20)
  blockchains/smartchain/assets/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9/info.json
  blockchains/smartchain/assets/0xe65313B085258a671d044F7Ad9D9fcd514c5d9e9/logo.png
Labels: Payment Status: Paid

#18917 Add Volt Inu (BEP20)
  blockchains/ethereum/assets/0x3F7Aff0EF20AA2E646290DfA4E67611B2220C597/info.json
  blockchains/ethereum/assets/0x3F7Aff0EF20AA2E646290DfA4E67611B2220C597/logo.png
  blockchains/smartchain/assets/0x07EC61Ae90860641972E9B41A706325a1E928BF8/info.json
  blockchains/smartchain/assets/0x07EC61Ae90860641972E9B41A706325a1E928BF8/logo.png
Labels: Payment Status: Paid

#18926 Add Elvantis (BEP20)
  blockchains/smartchain/assets/0xE942C48044FB1C7f4C9eB456f6097fa4A1A17B8f/info.json
  blockchains/smartchain/assets/0xE942C48044FB1C7f4C9eB456f6097fa4A1A17B8f/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18929 Update Splyt (SHOPX) Logo (ERC20)
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/info.json
  blockchains/ethereum/assets/0x7BEF710a5759d197EC0Bf621c3Df802C2D60D848/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18937 Migration for Mind Music
  blockchains/smartchain/assets/0x897304D4606B2d5FcAf886aa7AA143e478EC36C5/info.json
  blockchains/smartchain/assets/0x897304D4606B2d5FcAf886aa7AA143e478EC36C5/logo.png
Labels: Payment Status: Paid

#18936 Add Mind Music (BEP20)
  blockchains/smartchain/assets/0xCB0B74476d72BBBC77f14724a859b2e960Ca1803/info.json
  blockchains/smartchain/assets/0xCB0B74476d72BBBC77f14724a859b2e960Ca1803/logo.png
Labels: Payment Status: Paid

#18972 adding KATA (Katana Inu)
  blockchains/ethereum/assets/0x2e85ae1C47602f7927bCabc2Ff99C40aA222aE15/info.json
  blockchains/ethereum/assets/0x2e85ae1C47602f7927bCabc2Ff99C40aA222aE15/logo.png
  blockchains/smartchain/assets/0x6D6bA21E4C4b29CA7Bfa1c344Ba1E35B8DaE7205/info.json
  blockchains/smartchain/assets/0x6D6bA21E4C4b29CA7Bfa1c344Ba1E35B8DaE7205/logo.png
Labels: Payment Status: Paid

#19030 Add AmazingDoge logo and info
  blockchains/smartchain/assets/0x0EBc30459551858e81306d583025d12C7d795FA2/info.json
  blockchains/smartchain/assets/0x0EBc30459551858e81306d583025d12C7d795FA2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19015 Update XCN description
  blockchains/ethereum/assets/0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18/info.json
Labels: Payment Status: Requested

#19046 Add VEKTOR (BEP20)
  blockchains/smartchain/assets/0xF2DA079867785018E6d823DD0FF332f05AAfe485/info.json
  blockchains/smartchain/assets/0xF2DA079867785018E6d823DD0FF332f05AAfe485/logo.png
Labels: Payment Status: Paid

#19023 Add PEX logo and info
  blockchains/smartchain/assets/0x6a0b66710567b6beb81A71F7e9466450a91a384b/info.json
  blockchains/smartchain/assets/0x6a0b66710567b6beb81A71F7e9466450a91a384b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19045 MinerBlox token (MBLOX) re-apply (original request PR #18519)
  blockchains/smartchain/assets/0xAD0A3901eFf23b9143985bCB42F0171a112A2fD3/info.json
  blockchains/smartchain/assets/0xAD0A3901eFf23b9143985bCB42F0171a112A2fD3/logo.png
Labels: Payment Status: Paid

#19013 Update Boda Token Logo
  blockchains/smartchain/assets/0xdc847755343C3A2B94d6aFC0aAE57651E1b14064/info.json
  blockchains/smartchain/assets/0xdc847755343C3A2B94d6aFC0aAE57651E1b14064/logo.png
Labels: Payment Status: Paid

#19021 Add SpacePi Token (BEP20)
  blockchains/smartchain/assets/0x69b14e8D3CEBfDD8196Bfe530954A0C226E5008E/info.json
  blockchains/smartchain/assets/0x69b14e8D3CEBfDD8196Bfe530954A0C226E5008E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18390 add Kunci Coin
  blockchains/smartchain/assets/0x6cf271270662be1C4fc1b7BB7D7D7Fc60Cc19125/info.json
  blockchains/smartchain/assets/0x6cf271270662be1C4fc1b7BB7D7D7Fc60Cc19125/logo.png
Labels: Payment Status: Paid

#18377 Add KING FOREVER (BEP20)
  blockchains/smartchain/assets/0xAcFF4E9E9110971E1A4D8f013F5f97dd8fB4F430/info.json
  blockchains/smartchain/assets/0xAcFF4E9E9110971E1A4D8f013F5f97dd8fB4F430/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#19070 Add Atlantis (BEP20)
  blockchains/smartchain/assets/0xC7dDF690942b74171F7e3763baf260B686516bc0/info.json
  blockchains/smartchain/assets/0xC7dDF690942b74171F7e3763baf260B686516bc0/logo.png
Labels: Payment Status: Paid

#19044 Add TOSKA (BEP20)
  blockchains/smartchain/assets/0xca85585A160058e21770e4118A5187a09793b333/info.json
  blockchains/smartchain/assets/0xca85585A160058e21770e4118A5187a09793b333/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#19103 Add AXL INU (AXL) (BEP20)
  blockchains/ethereum/assets/0x25b24B3c47918b7962B3e49C4F468367F73CC0E0/info.json
  blockchains/ethereum/assets/0x25b24B3c47918b7962B3e49C4F468367F73CC0E0/logo.png
  blockchains/smartchain/assets/0x25b24B3c47918b7962B3e49C4F468367F73CC0E0/info.json
  blockchains/smartchain/assets/0x25b24B3c47918b7962B3e49C4F468367F73CC0E0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#19076 Add MetaHouse logo and info
  blockchains/smartchain/assets/0x825791Bc83A377Ba3931E8a56504a1EACAAE0f76/info.json
  blockchains/smartchain/assets/0x825791Bc83A377Ba3931E8a56504a1EACAAE0f76/logo.png
Labels: Payment Status: Paid

#19117 Add Centcex (BEP20)
  blockchains/smartchain/assets/0x739e81BCd49854d7BDF526302989f14A2E7994B2/info.json
  blockchains/smartchain/assets/0x739e81BCd49854d7BDF526302989f14A2E7994B2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19128 Add GIGA BLOCK (BEP20)
  blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/info.json
  blockchains/smartchain/assets/0x8397Eb3EC07615cE88ff854d08e9E27B5155128b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19167 Add Green Chart (BEP20)
  blockchains/smartchain/assets/0x7403802c0FFeE2d83FB13513e23aAF4a3a9C69f0/info.json
  blockchains/smartchain/assets/0x7403802c0FFeE2d83FB13513e23aAF4a3a9C69f0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19178 Update DEEPSPACE (BEP20) Listing and Add dapp Logo and Request dapp Listing
  blockchains/smartchain/assets/0xf275e1AC303a4C9D987a2c48b8E555A77FeC3F1C/info.json
  dapps/app.deepspace.game.png
Labels: Payment Status: Paid

#19224 [Internal] Add Green Metaverse Token (GMT) SPL
  blockchains/solana/assets/7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx/info.json
  blockchains/solana/assets/7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx/logo.png
Labels: Payment Status: Paid

#19221 kava: validators: add Mega
  blockchains/kava/validators/assets/kavavaloper1st7akgudd4d3x5t4zd3kn0fg948zn9yf4qpa0m/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#19197 Add Tiny Coin (BEP20)
  blockchains/smartchain/assets/0x05aD6E30A855BE07AfA57e08a4f30d00810a402e/info.json
  blockchains/smartchain/assets/0x05aD6E30A855BE07AfA57e08a4f30d00810a402e/logo.png
Labels: Payment Status: Paid

#19255 Add Mystery (BEP20)
  blockchains/smartchain/assets/0xCdcaef3cE3a138C47ddB0B04a9b04649c13D50Ed/info.json
  blockchains/smartchain/assets/0xCdcaef3cE3a138C47ddB0B04a9b04649c13D50Ed/logo.png
Labels: Payment Status: Paid

#19213 metaniagames assets added
  blockchains/smartchain/assets/0x6F64cC61d0d5542E40e6f2828cBddA84507D214D/info.json
  blockchains/smartchain/assets/0x6F64cC61d0d5542E40e6f2828cBddA84507D214D/logo.png
Labels: Payment Status: Paid

#19203 Add DEMON (BEP20)
  blockchains/smartchain/assets/0x2E51b6f3181b342d098B1a939Ae1944ED6768fd4/info.json
  blockchains/smartchain/assets/0x2E51b6f3181b342d098B1a939Ae1944ED6768fd4/logo.png
Labels: Payment Status: Paid

#19241 Add Logo Fwc
  blockchains/smartchain/assets/0x6D3a160B86eDcD46D8F9bBa25c2F88ccCADe19fc/info.json
  blockchains/smartchain/assets/0x6D3a160B86eDcD46D8F9bBa25c2F88ccCADe19fc/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#19262 Update OPEN token asset
  blockchains/smartchain/assets/0x27a339d9B59b21390d7209b78a839868E319301B/info.json
  blockchains/smartchain/assets/0x27a339d9B59b21390d7209b78a839868E319301B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#19260 Add Rune Shards (RXS) (BEP20)
  blockchains/smartchain/assets/0x2098fEf7eEae592038f4f3C4b008515fed0d5886/info.json
  blockchains/smartchain/assets/0x2098fEf7eEae592038f4f3C4b008515fed0d5886/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#19282 Add ELGOS Token (BEP20)
  blockchains/smartchain/assets/0xF37cAc4783a343D6258DdD52AA4e2566C0CbE25a/info.json
  blockchains/smartchain/assets/0xF37cAc4783a343D6258DdD52AA4e2566C0CbE25a/logo.png
Labels: Payment Status: Paid

#19297 Add YOUWHO (BEP20)
  blockchains/smartchain/assets/0xB583961E033Dfe0FfF161952f7BA21c411b6103d/info.json
  blockchains/smartchain/assets/0xB583961E033Dfe0FfF161952f7BA21c411b6103d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#19299 Submit MEXI logo token
  blockchains/smartchain/assets/0x70D8d5B3416888fD05e806195312DD2D9597d50C/info.json
  blockchains/smartchain/assets/0x70D8d5B3416888fD05e806195312DD2D9597d50C/logo.png
Labels: Payment Status: Paid

#19302 Add MetaUFO LOGO
  blockchains/smartchain/assets/0x2ad7F18DcFA131e33411770A9c6c4fe49b187Bc2/info.json
  blockchains/smartchain/assets/0x2ad7F18DcFA131e33411770A9c6c4fe49b187Bc2/logo.png
Labels: Payment Status: Paid

#19315 Add ATR logo and info
  blockchains/smartchain/assets/0x7559C49c3Aec50E763A486bB232fA8d0d76078e4/info.json
  blockchains/smartchain/assets/0x7559C49c3Aec50E763A486bB232fA8d0d76078e4/logo.png
Labels: Payment Status: Paid

#19326 Add Stakely Cosmoshub, Osmosis, Polkadot & Terra validators
  blockchains/cosmos/validators/assets/cosmosvaloper16yupepagywvlk7uhpfchtwa0stu5f8cyhh54f2/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1z5xyynz9ewuf044uaweswldut34z34z3cwpt7y/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/polkadot/validators/assets/15R1Th3ULXAq81QPGeEDfE1ywbw19AjZiARxH7czm83wS2w2/logo.png
  blockchains/polkadot/validators/list.json
  blockchains/terra/validators/assets/terravaloper108lmrztvc3pc3w774shgvpry4d3lf79k2ummna/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid

#19244 Add Frz solar system (BEP20)
  blockchains/smartchain/assets/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28/info.json
  blockchains/smartchain/assets/0xaC41Fb8013c0B63588fC63997785A5d79E73eb28/logo.png
Labels: Payment Status: Paid

#19362 [Internal] Add KuCoin Community Chain logo
  blockchains/kcc/info/info.json
  blockchains/kcc/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#19334 add energyweb to blockchains
  blockchains/energyweb/info/info.json
  blockchains/energyweb/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#19353 Update CAN BEP20 json.info token details
  blockchains/smartchain/assets/0x007EA5C0Ea75a8DF45D288a4debdD5bb633F9e56/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#19361 Add Cylum Finance (BEP20)
  blockchains/smartchain/assets/0x15Ea6B8481bF1C991aC3dC8e67279d31651a56FE/info.json
  blockchains/smartchain/assets/0x15Ea6B8481bF1C991aC3dC8e67279d31651a56FE/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
