Repository trustwallet/assets, pull requests merged in 2022-07, with the labels that each got.

#21250 Add TIME (BEP20)
  blockchains/smartchain/assets/0x26619FA1d4c957C58096bBbeCa6588dCFB12E109/info.json
  blockchains/smartchain/assets/0x26619FA1d4c957C58096bBbeCa6588dCFB12E109/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#21163 Add Starfish OS (BEP20)
  blockchains/smartchain/assets/0xC544D8aB2b5ED395B96E3Ec87462801ECa579aE1/info.json
  blockchains/smartchain/assets/0xC544D8aB2b5ED395B96E3Ec87462801ECa579aE1/logo.png
Labels: Payment Status: Paid

#21308 Add SquidGrow (BEP20)
  blockchains/smartchain/assets/0x88479186BAC914E4313389a64881F5ed0153C765/info.json
  blockchains/smartchain/assets/0x88479186BAC914E4313389a64881F5ed0153C765/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21316 Follow up request for the request #21197
  blockchains/smartchain/assets/0x7EeFB6AeB8BC2c1ba6be1D4273eC0758a1321272/info.json
  blockchains/smartchain/assets/0x7EeFB6AeB8BC2c1ba6be1D4273eC0758a1321272/logo.png
Labels: Status: On Hold, Payment Status: Paid

#21315 Add BlueLotus Solana Validator
  blockchains/solana/validators/assets/1234LB7uvDC23rdCQoK8C3jNwnovUNyeKxz8wC3dghJ5/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21321 Migration for Spookyshiba (BEP20)
  blockchains/smartchain/assets/0x9c2B1B3780A8B36B695f0b2781668664aC1Bf25A/info.json
  blockchains/smartchain/assets/0x9c2B1B3780A8B36B695f0b2781668664aC1Bf25A/logo.png
  blockchains/smartchain/assets/0xed74Bc5DC139356E08dE28143996F5eF6e4334a4/info.json
  blockchains/smartchain/assets/0xed74Bc5DC139356E08dE28143996F5eF6e4334a4/logo.png
Labels: Payment Status: Paid

#21362 Add beef tokens (CELO) (FANTOM) (POLYGON) (HECO)
  blockchains/celo/assets/0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C/info.json
  blockchains/celo/assets/0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C/logo.png
  blockchains/fantom/assets/0xd6070ae98b8069de6B494332d1A1a81B6179D960/info.json
  blockchains/fantom/assets/0xd6070ae98b8069de6B494332d1A1a81B6179D960/logo.png
  blockchains/heco/assets/0x765277EebeCA2e31912C9946eAe1021199B39C61/info.json
  blockchains/heco/assets/0x765277EebeCA2e31912C9946eAe1021199B39C61/logo.png
  blockchains/polygon/assets/0xFbdd194376de19a88118e84E279b977f165d01b8/info.json
  blockchains/polygon/assets/0xFbdd194376de19a88118e84E279b977f165d01b8/logo.png
Labels: Payment Status: Paid

#21335 Add 1USE to Trustwallet
  blockchains/smartchain/assets/0x60d66a5152612F7D550796910d022Cb2c77B09de/info.json
  blockchains/smartchain/assets/0x60d66a5152612F7D550796910d022Cb2c77B09de/logo.png
Labels: Payment Status: Paid

#21404 Add Kava EVM
  blockchains/kavaevm/info/info.json
  blockchains/kavaevm/info/logo.png
Labels: Payment Status: Requested

#21405 Change dapps for beefy.finance
  blockchains/binance/assets/BIFI-290/info.json
  dapps/app.beefy.png
Labels: Payment Status: Paid

#21419 Add ERC20 token BitDAO (BIT)
  blockchains/ethereum/assets/0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5/info.json
  blockchains/ethereum/assets/0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21443 Migration for Birb v2 (BEP20)
  blockchains/smartchain/assets/0x3CF33Ff134c0e00A2664f148A4232adeA1515C6f/info.json
  blockchains/smartchain/assets/0x3CF33Ff134c0e00A2664f148A4232adeA1515C6f/logo.png
Labels: Payment Status: Paid

#21444 Migration for Birbv2 (BEP20)
  blockchains/smartchain/assets/0x88888888Fc33e4ECba8958c0c2AD361089E19885/info.json
  blockchains/smartchain/assets/0x88888888Fc33e4ECba8958c0c2AD361089E19885/logo.png
Labels: Payment Status: Paid

#21435 Add DUET (BEP20)
  blockchains/smartchain/assets/0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B/info.json
  blockchains/smartchain/assets/0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21475 Update app.venus.io.png
  dapps/app.venus.io.png
Labels: Payment Status: Paid

#21447 Update Student Coin logo
  blockchains/ethereum/assets/0x15B543e986b8c34074DFc9901136d9355a537e7E/logo.png
Labels: Payment Status: Paid

#21430 Add Meter chain assets
  blockchains/meter/assets/0x1cf09D1B5Da9d9d24365D87B932A7c4bD018A419/info.json
  blockchains/meter/assets/0x1cf09D1B5Da9d9d24365D87B932A7c4bD018A419/logo.png
  blockchains/meter/assets/0x228ebBeE999c6a7ad74A6130E81b12f9Fe237Ba3/info.json
  blockchains/meter/assets/0x228ebBeE999c6a7ad74A6130E81b12f9Fe237Ba3/logo.png
  blockchains/meter/assets/0x24aA189DfAa76c671c279262F94434770F557c35/info.json
  blockchains/meter/assets/0x24aA189DfAa76c671c279262F94434770F557c35/logo.png
  blockchains/meter/assets/0x5Fa41671c48e3C951AfC30816947126CCC8C162e/info.json
  blockchains/meter/assets/0x5Fa41671c48e3C951AfC30816947126CCC8C162e/logo.png
  blockchains/meter/assets/0x6CFe9AdaD5215195c1Aa9755DAed29360e6Ab986/info.json
  blockchains/meter/assets/0x6CFe9AdaD5215195c1Aa9755DAed29360e6Ab986/logo.png
  blockchains/meter/assets/0x8Df95e66Cb0eF38F91D2776DA3c921768982fBa0/info.json
  blockchains/meter/assets/0x8Df95e66Cb0eF38F91D2776DA3c921768982fBa0/logo.png
  blockchains/meter/assets/0x983147FB73A45FC7F8B4DFA1cd61Bdc7b111e5b6/info.json
  blockchains/meter/assets/0x983147FB73A45FC7F8B4DFA1cd61Bdc7b111e5b6/logo.png
  blockchains/meter/assets/0xD86e243FC0007e6226B07c9A50C9d70D78299EB5/info.json
  blockchains/meter/assets/0xD86e243FC0007e6226B07c9A50C9d70D78299EB5/logo.png
  blockchains/meter/assets/0xF0E86246519Be0810C9FAfc8430C49799985aAA8/info.json
  blockchains/meter/assets/0xF0E86246519Be0810C9FAfc8430C49799985aAA8/logo.png
  blockchains/meter/assets/0xb158870beB809Ad955Bf56065C5C10D7Fd957cC0/info.json
  blockchains/meter/assets/0xb158870beB809Ad955Bf56065C5C10D7Fd957cC0/logo.png
  blockchains/meter/assets/0xc1f6C86ABEe8e2e0B6fd5BD80F0b51fef783635C/info.json
  blockchains/meter/assets/0xc1f6C86ABEe8e2e0B6fd5BD80F0b51fef783635C/logo.png
  blockchains/meter/info/info.json
  blockchains/meter/info/logo.png
  blockchains/meter/tokenlist.json
Labels: Payment Status: Paid

#21445 Add new Solana validator - Atomic Nodes
  blockchains/solana/validators/assets/2Y2opv8Kq8zFATg6ipqb2AjgCf18tkv1CLMLXQGif2NH/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21332 Add AZW logo to Trustwallet
  blockchains/smartchain/assets/0x1F2Cfde19976A2bF0A250900f7aCe9c362908C93/info.json
  blockchains/smartchain/assets/0x1F2Cfde19976A2bF0A250900f7aCe9c362908C93/logo.png
Labels: Status: On Hold, Payment Status: Paid

#21490 Add My Liquidity Partner (MLP) (ERC20)
  blockchains/ethereum/assets/0xE22020F47B7378dfedcedd2C81d4137c22fE1152/info.json
  blockchains/ethereum/assets/0xE22020F47B7378dfedcedd2C81d4137c22fE1152/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21498 Add Grove (BEP20)
  blockchains/smartchain/assets/0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB/info.json
  blockchains/smartchain/assets/0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB/logo.png
Labels: Payment Status: Paid

#21500 Add WETH and SNX to Optimism tokenlist
  blockchains/optimism/tokenlist-extended.json
  blockchains/optimism/tokenlist.json
Labels: Payment Status: Paid

#21534 Fix name and description for BEP20 tokens
  blockchains/smartchain/assets/0x01e9611dF08548994C883e4Ca729B0128E73470F/info.json
  blockchains/smartchain/assets/0x1F01Dc57C66C2f87D8eab9C625D335e9defE6912/info.json
  blockchains/smartchain/assets/0x1F82a9b541FE4C322B5cd81DCB066620D57de35C/info.json
  blockchains/smartchain/assets/0x1FF2a2c2DEAdb17B6Ba9949393d1406f4c61BFC9/info.json
  blockchains/smartchain/assets/0x2A1d286ed5edAD78BeFD6E0d8BEb38791e8cD69d/info.json
  blockchains/smartchain/assets/0x2A9718defF471f3Bb91FA0ECEAB14154F150a385/info.json
  blockchains/smartchain/assets/0x2BA8c3066F36B998bC74CE8DcE260Fb5D2ba6bCc/info.json
  blockchains/smartchain/assets/0x2cA25319E2E63719F87221D8bF3646F8F5dE5DED/info.json
  blockchains/smartchain/assets/0x3C70260eEe0a2bFc4b375feB810325801f289fBd/info.json
  blockchains/smartchain/assets/0x3Da67Ae8fcF0B733d799f65B2695d650eA11112A/info.json
  blockchains/smartchain/assets/0x3da69D719AD12EEAb2b7031697E84c2c62299C13/info.json
  blockchains/smartchain/assets/0x4BbB275012EBE258556B8debE5C07bE98e8d3859/info.json
  blockchains/smartchain/assets/0x4c48cca6153Db911002F965D22fdeFcD95f33BE9/info.json
  blockchains/smartchain/assets/0x4c4da68D45F23E38ec8407272ee4f38F280263c0/info.json
  blockchains/smartchain/assets/0x4ef29F3B804C316bA8bA464A765C601Fc092a2e9/info.json
  blockchains/smartchain/assets/0x5A054554b3F0C75063D29250984A921402E1E3a7/info.json
  blockchains/smartchain/assets/0x5A3010d4d8D3B5fB49f8B6E57FB9E48063f16700/info.json
  blockchains/smartchain/assets/0x5B0Dfe077B16479715C9838eb644892008abbFe6/info.json
  blockchains/smartchain/assets/0x5E5C9001Aa81332D405D993FFd1468751D659d1e/info.json
  blockchains/smartchain/assets/0x5F1b95784a033CD6842cf26eb9A9687F91Ad9e78/info.json
  blockchains/smartchain/assets/0x5b8DC8b4f438b1932Ddb2F320b4b7Ea65BA41798/info.json
  blockchains/smartchain/assets/0x5c792740a7d4684E75e5551Fb239f512Fe0d47d0/info.json
  blockchains/smartchain/assets/0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350/info.json
  blockchains/smartchain/assets/0x7BA3cD00229C1beCC95a4B056fF15C123DcB456D/info.json
  blockchains/smartchain/assets/0x7CF23DfF6DEDBf80211FfaDa15Ae01463C47D034/info.json
  blockchains/smartchain/assets/0x7db5af2B9624e1b3B4Bb69D6DeBd9aD1016A58Ac/info.json
Labels: Payment Status: Paid

#21512 [internal] Add tokenlist XDAI
  blockchains/xdai/tokenlist.json
Labels: Payment Status: Paid

#21511 [internal] Add tokenlist for fantom
  blockchains/fantom/tokenlist.json
Labels: Payment Status: Paid

#21509 [internal] Arbitrum add tokens to tokenlist
  blockchains/arbitrum/tokenlist-extended.json
  blockchains/arbitrum/tokenlist.json
Labels: Payment Status: Paid

#21507 [internal] Add more tokens to optimism tokenlist
  blockchains/optimism/tokenlist-extended.json
  blockchains/optimism/tokenlist.json
Labels: Payment Status: Requested

#21550 Update Solana Validators list with Juicy Stake
  blockchains/solana/validators/assets/juicQdAnksqZ5Yb8NQwCLjLWhykvXGktxnQCDvMe6Nx/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#21558 Add MPH (POLYGON)
  blockchains/polygon/assets/0x65C9e3289e5949134759119DBc9F862E8d6F2fBE/info.json
  blockchains/polygon/assets/0x65C9e3289e5949134759119DBc9F862E8d6F2fBE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21580 Add Ancient Kingdom Logo And Info
  blockchains/smartchain/assets/0x8c282eA9eACd1B95D44a3A18DCdd1D0472868998/info.json
  blockchains/smartchain/assets/0x8c282eA9eACd1B95D44a3A18DCdd1D0472868998/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21589 Add Square Token logo and info
  blockchains/smartchain/assets/0xB82BEb6Ee0063Abd5fC8E544c852237aA62CBb14/info.json
  blockchains/smartchain/assets/0xB82BEb6Ee0063Abd5fC8E544c852237aA62CBb14/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21590 Add ArenaPlay (BEP20)
  blockchains/smartchain/assets/0x2AA504586d6CaB3C59Fa629f74c586d78b93A025/info.json
  blockchains/smartchain/assets/0x2AA504586d6CaB3C59Fa629f74c586d78b93A025/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21604 Add synclub node info
  blockchains/binance/validators/assets/bva1m02zrj77ahdz3597nscq7a6dhxnwsuutsljcvj/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21613 Fix description (ERC20)
  blockchains/ethereum/assets/0x0000000000085d4780B73119b644AE5ecd22b376/info.json
  blockchains/ethereum/assets/0x07150e919B4De5fD6a63DE1F9384828396f25fDC/info.json
  blockchains/ethereum/assets/0xFf19138b039D938db46bDDA0067DC4BA132ec71C/info.json
Labels: Payment Status: Paid

#21618 Add Route (ERC20)
  blockchains/ethereum/assets/0x16ECCfDbb4eE1A85A33f3A9B21175Cd7Ae753dB4/info.json
  blockchains/ethereum/assets/0x16ECCfDbb4eE1A85A33f3A9B21175Cd7Ae753dB4/logo.png
Labels: Payment Status: Paid

#21631 Add Pige Inu (BEP20)
  blockchains/smartchain/assets/0x1FDB2c3851D067502Ce2122bE80a41ea212949E2/info.json
  blockchains/smartchain/assets/0x1FDB2c3851D067502Ce2122bE80a41ea212949E2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21638 Updating Prom (ERC20 and BEP20)
  blockchains/ethereum/assets/0xfc82bb4ba86045Af6F327323a46E80412b91b27d/info.json
  blockchains/ethereum/assets/0xfc82bb4ba86045Af6F327323a46E80412b91b27d/logo.png
  blockchains/smartchain/assets/0xaF53d56ff99f1322515E54FdDE93FF8b3b7DAFd5/info.json
  blockchains/smartchain/assets/0xaF53d56ff99f1322515E54FdDE93FF8b3b7DAFd5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21654 Add Cryptostone (BEP20)
  blockchains/smartchain/assets/0x569f4957176Ffa0dff76c507604f6a66d4B9C578/info.json
  blockchains/smartchain/assets/0x569f4957176Ffa0dff76c507604f6a66d4B9C578/logo.png
Labels: Payment Status: Paid

#21656 Added ERC20 Ambire Wallet token
  blockchains/ethereum/assets/0x88800092fF476844f74dC2FC427974BBee2794Ae/info.json
  blockchains/ethereum/assets/0x88800092fF476844f74dC2FC427974BBee2794Ae/logo.png
  blockchains/polygon/assets/0x564906ec1DF8399F00e4ad32c0eCAC0404a27A1c/info.json
  blockchains/polygon/assets/0x564906ec1DF8399F00e4ad32c0eCAC0404a27A1c/logo.png
Labels: Payment Status: Paid

#21660 Add VLaunch
  blockchains/ethereum/assets/0x51FE2E572e97BFEB1D719809d743Ec2675924EDc/info.json
  blockchains/ethereum/assets/0x51FE2E572e97BFEB1D719809d743Ec2675924EDc/logo.png
  blockchains/smartchain/assets/0xc3601108947A46B219C09f24c668a52756C8d977/info.json
  blockchains/smartchain/assets/0xc3601108947A46B219C09f24c668a52756C8d977/logo.png
Labels: Payment Status: Paid

#21657 Update for the Allnodes validator nodes
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/assets/kavavaloper14vk3997r4ea4m7eej7ugmr503ru768fxwynsmq/logo.png
  blockchains/kava/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1e9ucjn5fjmetky5wezzcsccp7hqcwzrrdulz7n/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/polkadot/validators/assets/15ML93PH72j5fFfqLrXRy7uDh7pUBCTUcSVYbaDV18LaTfeW/logo.png
  blockchains/polkadot/validators/list.json
  blockchains/solana/validators/assets/6F5xdRXh2W3B2vhte12VG79JVUkUSLYrHydGX1SAadfZ/logo.png
  blockchains/solana/validators/list.json
  blockchains/terra/validators/assets/terravaloper120ppepaj2lh5vreadx42wnjjznh55vvktp78wk/logo.png
  blockchains/terra/validators/list.json
  blockchains/tron/validators/assets/TMAqheVWMaNm15UJTNgasEVpJ7YHYiZVZ8/logo.png
  blockchains/tron/validators/list.json
Labels: Payment Status: Paid

#21630 Add Aura Finance (AURA) (ERC20)
  blockchains/ethereum/assets/0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF/info.json
  blockchains/ethereum/assets/0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF/logo.png
Labels: Payment Status: Paid

#21592 Add YES WORLD (BEP20)
  blockchains/smartchain/assets/0xB9d35811424600fa9E8cD62A0471fBd025131cb8/info.json
  blockchains/smartchain/assets/0xB9d35811424600fa9E8cD62A0471fBd025131cb8/logo.png
Labels: Status: On Hold, Payment Status: Paid, Payment Status: Requested

#21661 Add Lunatics (BEP20)
  blockchains/smartchain/assets/0x2A48eCe377b87ce941406657B9278b4459595E06/info.json
  blockchains/smartchain/assets/0x2A48eCe377b87ce941406657B9278b4459595E06/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21634 Add OLE token
  blockchains/smartchain/assets/0xa865197A84E780957422237B5D152772654341F3/info.json
  blockchains/smartchain/assets/0xa865197A84E780957422237B5D152772654341F3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21484 Add Panther Protocol (ZKP) token and logo
  blockchains/ethereum/assets/0x909E34d3f6124C324ac83DccA84b74398a6fa173/info.json
  blockchains/ethereum/assets/0x909E34d3f6124C324ac83DccA84b74398a6fa173/logo.png
  blockchains/polygon/assets/0x9A06Db14D639796B25A6ceC6A1bf614fd98815EC/info.json
  blockchains/polygon/assets/0x9A06Db14D639796B25A6ceC6A1bf614fd98815EC/logo.png
Labels: Payment Status: Paid

#21740 Add ZionTopia (BEP20)
  blockchains/smartchain/assets/0xE0399378f7a92A39DA849EB64CdDdE2940e234Bb/info.json
  blockchains/smartchain/assets/0xE0399378f7a92A39DA849EB64CdDdE2940e234Bb/logo.png
Labels: Payment Status: Requested
