Repository trustwallet/assets, pull requests merged in 2022-06, with the labels that each got.

#20813 Wilder World Token Info
  blockchains/ethereum/assets/0x2a3bFF78B79A009976EeA096a51A948a3dC00e34/info.json
  blockchains/ethereum/assets/0x2a3bFF78B79A009976EeA096a51A948a3dC00e34/logo.png
Labels: Payment Status: Paid

#20694 Add Galaxy Finance Token (BEP20)
  blockchains/smartchain/assets/0xE77932B1216125848e82C3967e75698362168f99/info.json
  blockchains/smartchain/assets/0xE77932B1216125848e82C3967e75698362168f99/logo.png
Labels: Payment Status: Paid

#20824 Add Optimism
  blockchains/optimism/assets/0x4200000000000000000000000000000000000042/info.json
  blockchains/optimism/assets/0x4200000000000000000000000000000000000042/logo.png
Labels: Payment Status: Paid

#20847 Update BUSD Kava token info
  blockchains/kava/assets/busd/info.json
  blockchains/kava/assets/busd/logo.png
Labels: Payment Status: Requested

#20848 Add apollox dApp
  dapps/apollox.finance.png
Labels: Payment Status: Requested

#20836 Add SafeBLAST (BLAST) (ERC20)
  blockchains/ethereum/assets/0x614D7f40701132E25fe6fc17801Fbd34212d2Eda/info.json
  blockchains/ethereum/assets/0x614D7f40701132E25fe6fc17801Fbd34212d2Eda/logo.png
Labels: Payment Status: Paid

#20854 Update token symbol for Aurora
  blockchains/aurora/info/info.json
Labels: Payment Status: Requested

#20874 Add Vita Inu (BEP20) - (Already paid - refer to Pull #20103)
  blockchains/smartchain/assets/0xfEbe8C1eD424DbF688551D4E2267e7A53698F0aa/info.json
  blockchains/smartchain/assets/0xfEbe8C1eD424DbF688551D4E2267e7A53698F0aa/logo.png
Labels: Payment Status: Paid

#20863 Update logo
  blockchains/smartchain/assets/0x3e24BBb2c9a0f2fAEcFDBDCa20BBa6F35b73C4CB/info.json
  blockchains/smartchain/assets/0x3e24BBb2c9a0f2fAEcFDBDCa20BBa6F35b73C4CB/logo.png
Labels: Payment Status: Paid

#20876 Add info and logo for Moonriver and Moonbeam
  blockchains/moonbeam/info/info.json
  blockchains/moonbeam/info/logo.png
  blockchains/moonriver/info/info.json
  blockchains/moonriver/info/logo.png
Labels: Payment Status: Requested

#20887 add melea One validator
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#20898 BEP20 Token Logo, Info (re-request)
  blockchains/smartchain/assets/0x698111b771363B81D1179AD102e3d8B9cD093a11/info.json
  blockchains/smartchain/assets/0x698111b771363B81D1179AD102e3d8B9cD093a11/logo.png
Labels: Payment Status: Paid

#20910 Citadel.one solana validator
  blockchains/solana/validators/assets/DP3iT6AXJxWsn5pR1ik13vchaTeeyr3fqXFTeysxrXtv/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#20907 add melea Two
  blockchains/solana/validators/assets/6hTLQ5HSdWcpZkbXmZxXaGjCgTh7zh8UeWKWKgGE1BPp/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#20918 Add WEB2 Inu (BEP20)
  blockchains/smartchain/assets/0x00998d97c22B564d1dAF39d493e74C21D83fffbA/info.json
  blockchains/smartchain/assets/0x00998d97c22B564d1dAF39d493e74C21D83fffbA/logo.png
Labels: Payment Status: Paid

#20921 [Internal] AURORA governance token
  blockchains/aurora/assets/0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79/info.json
  blockchains/aurora/assets/0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79/logo.png
Labels: Payment Status: Requested

#20946 Migration for BRG (TRC20) -> (BEP20)
  blockchains/smartchain/assets/0x6e4a971B81CA58045a2AA982EaA3d50C4Ac38F42/info.json
  blockchains/smartchain/assets/0x6e4a971B81CA58045a2AA982EaA3d50C4Ac38F42/logo.png
  blockchains/tron/assets/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC/info.json
  blockchains/tron/assets/TJvqNiWUN2v2NBG12UhfV7WSvReJkRP3VC/logo.png
Labels: Payment Status: Paid

#20959 Add ZEDXION (BEP20)
  blockchains/smartchain/assets/0x734D66f635523D7ddb7d2373C128333DA313041b/info.json
  blockchains/smartchain/assets/0x734D66f635523D7ddb7d2373C128333DA313041b/logo.png
Labels: Payment Status: Paid

#19467 Add Ecoin Finance (BEP20)
  blockchains/smartchain/assets/0x7d38315b92d0E7A85B35B2b7FE969B25935619D7/info.json
  blockchains/smartchain/assets/0x7d38315b92d0E7A85B35B2b7FE969B25935619D7/logo.png
Labels: Payment Status: Paid

#20970 Add new blockchain Terra (terrav2)
  blockchains/terra/info/logo.png
  blockchains/terrav2/info/info.json
  blockchains/terrav2/info/logo.png
Labels: Payment Status: Paid

#20969 [Internal] Add klaytn info and logo
  blockchains/klaytn/info/info.json
  blockchains/klaytn/info/logo.png
Labels: Payment Status: Requested

#20961 HDL commit
  blockchains/algorand/assets/137594422/info.json
  blockchains/algorand/assets/137594422/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21038 Add Irena Green Energy (BEP20)
  blockchains/smartchain/assets/0x9eeB6c5ff183E6001c65a12D70026b900AE76781/info.json
  blockchains/smartchain/assets/0x9eeB6c5ff183E6001c65a12D70026b900AE76781/logo.png
Labels: Payment Status: Paid

#21014 Add KleeKai (KLEE) (ERC20)
  blockchains/ethereum/assets/0xA67E9F021B9d208F7e3365B2A155E3C55B27de71/info.json
  blockchains/ethereum/assets/0xA67E9F021B9d208F7e3365B2A155E3C55B27de71/logo.png
Labels: Payment Status: Paid

#20957 add background for sushi logo
  dapps/app.sushi.com.png
Labels: Payment Status: Requested

#21071 Update tokenlist for Avalanche
  blockchains/avalanchec/tokenlist.json
Labels: Payment Status: Paid

#21057 Add NVIR token
  blockchains/ethereum/assets/0x9d71CE49ab8A0E6D2a1e7BFB89374C9392FD6804/info.json
  blockchains/ethereum/assets/0x9d71CE49ab8A0E6D2a1e7BFB89374C9392FD6804/logo.png
Labels: Payment Status: Paid

#21055 Add NDT METAVERSE (BEP20)
  blockchains/smartchain/assets/0x83300C06aDFd8225560f8505Dba7493A9B60194C/info.json
  blockchains/smartchain/assets/0x83300C06aDFd8225560f8505Dba7493A9B60194C/logo.png
Labels: Payment Status: Paid

#21058 add Fixed Elrond BHAT-c1fde3 ESDT token for whitelisting
  blockchains/elrond/assets/BHAT-c1fde3/info.json
  blockchains/elrond/assets/BHAT-c1fde3/logo.png
Labels: Payment Status: Paid

#21100 Add TTcoin (BEP20)
  blockchains/smartchain/assets/0x659049786cB66E4486b8C0E0cCC90a5929a21162/info.json
  blockchains/smartchain/assets/0x659049786cB66E4486b8C0E0cCC90a5929a21162/logo.png
Labels: Payment Status: Paid

#21128 Add Elrond assets (UTK, ITH)
  blockchains/elrond/assets/ITHWEGLD-1adc53/info.json
  blockchains/elrond/assets/ITHWEGLD-1adc53/logo.png
  blockchains/elrond/assets/UTK-2f80e9/info.json
  blockchains/elrond/assets/UTK-2f80e9/logo.png
  blockchains/elrond/assets/UTKWEGLD-c960d1/info.json
  blockchains/elrond/assets/UTKWEGLD-c960d1/logo.png
Labels: Payment Status: Paid

#21157 Add BlueSparrow (BLUESPARROW) (ERC20)
  blockchains/ethereum/assets/0x24cCeDEBF841544C9e6a62Af4E8c2fA6e5a46FdE/info.json
  blockchains/ethereum/assets/0x24cCeDEBF841544C9e6a62Af4E8c2fA6e5a46FdE/logo.png
Labels: Payment Status: Paid

#21162 Add Volt Inu (ERC20)
  blockchains/ethereum/assets/0x7db5af2B9624e1b3B4Bb69D6DeBd9aD1016A58Ac/info.json
  blockchains/ethereum/assets/0x7db5af2B9624e1b3B4Bb69D6DeBd9aD1016A58Ac/logo.png
Labels: Payment Status: Paid

#21161 Add Volt Inu (BEP20)
  blockchains/smartchain/assets/0x7db5af2B9624e1b3B4Bb69D6DeBd9aD1016A58Ac/info.json
  blockchains/smartchain/assets/0x7db5af2B9624e1b3B4Bb69D6DeBd9aD1016A58Ac/logo.png
Labels: Payment Status: Paid

#21166 Add Pallapay (BEP20)
  blockchains/smartchain/assets/0x8F49733210700D38098d7375C221c7d02F700cc8/info.json
  blockchains/smartchain/assets/0x8F49733210700D38098d7375C221c7d02F700cc8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21172 Rename evmos to nativeevmos
  blockchains/nativeevmos/validators/assets/evmosvaloper14zatq4jagqtm9ejgvglnv0t364d88u80futp65/logo.png
  blockchains/nativeevmos/validators/assets/evmosvaloper1f35jtt5m68zlxkpxn75403vv82cchahqvfsrup/logo.png
  blockchains/nativeevmos/validators/assets/evmosvaloper1mx9nqk5agvlsvt2yc8259nwztmxq7zjqep5khu/logo.png
  blockchains/nativeevmos/validators/assets/evmosvaloper1p5k54qk9jdamvw4r756g7dxsjarf6p0l3huk84/logo.png
  blockchains/nativeevmos/validators/assets/evmosvaloper1sp9frqwep52chwavv3xd776myy8gyyvkv5uysl/logo.png
  blockchains/nativeevmos/validators/list.json
Labels: Payment Status: Requested

#21165 Update kyber websites' logo
  dapps/kyber.network.png
  dapps/kyber.org.png
  dapps/kyberswap.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#21205 Update logo ADMC
  blockchains/smartchain/assets/0xA55EF2fB2B7b6A60371FD3def9B806E74a48bE69/info.json
  blockchains/smartchain/assets/0xA55EF2fB2B7b6A60371FD3def9B806E74a48bE69/logo.png
Labels: Payment Status: Paid

#21195 Add WeWay (BEP20)
  blockchains/smartchain/assets/0x9Ab70e92319f0b9127df78868Fd3655fB9f1E322/info.json
  blockchains/smartchain/assets/0x9Ab70e92319f0b9127df78868Fd3655fB9f1E322/logo.png
Labels: Status: On Hold, Payment Status: Paid

#21203 Add HEC and TOR on smartchain. Add HEC, TOR, sHEC and wsHEC on FANTOM.
  blockchains/fantom/assets/0x5C4FDfc5233f935f20D2aDbA572F770c2E377Ab0/info.json
  blockchains/fantom/assets/0x5C4FDfc5233f935f20D2aDbA572F770c2E377Ab0/logo.png
  blockchains/fantom/assets/0x74E23dF9110Aa9eA0b6ff2fAEE01e740CA1c642e/info.json
  blockchains/fantom/assets/0x74E23dF9110Aa9eA0b6ff2fAEE01e740CA1c642e/logo.png
  blockchains/fantom/assets/0x75bdeF24285013387A47775828bEC90b91Ca9a5F/info.json
  blockchains/fantom/assets/0x75bdeF24285013387A47775828bEC90b91Ca9a5F/logo.png
  blockchains/fantom/assets/0x94CcF60f700146BeA8eF7832820800E2dFa92EdA/info.json
  blockchains/fantom/assets/0x94CcF60f700146BeA8eF7832820800E2dFa92EdA/logo.png
  blockchains/smartchain/assets/0x1d6Cbdc6b29C6afBae65444a1f65bA9252b8CA83/info.json
  blockchains/smartchain/assets/0x1d6Cbdc6b29C6afBae65444a1f65bA9252b8CA83/logo.png
  blockchains/smartchain/assets/0x638EEBe886B0e9e7C6929E69490064a6C94d204d/info.json
  blockchains/smartchain/assets/0x638EEBe886B0e9e7C6929E69490064a6C94d204d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21259 Add TWT logo and info
  blockchains/smartchain/assets/0x39bca4d597062378b5669CD31a3bBFECCDd36B3c/info.json
  blockchains/smartchain/assets/0x39bca4d597062378b5669CD31a3bBFECCDd36B3c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
