Repository trustwallet/assets, pull requests merged in 2022-11, with the labels that each got.

#22898 Migration for ellipsis
  blockchains/smartchain/assets/0xA7f552078dcC247C2684336020c03648500C6d9F/info.json
  blockchains/smartchain/assets/0xA7f552078dcC247C2684336020c03648500C6d9F/logo.png
Labels: Payment Status: Paid

#22899 Migration for Ellipsis X
  blockchains/smartchain/assets/0xAf41054C1487b0e5E2B9250C0332eCBCe6CE9d71/info.json
  blockchains/smartchain/assets/0xAf41054C1487b0e5E2B9250C0332eCBCe6CE9d71/logo.png
Labels: Payment Status: Paid

#22872 add new token twoge logo
  blockchains/smartchain/assets/0xD5FFAB1841B9137D5528Ed09D6Ebb66c3088aeDE/info.json
  blockchains/smartchain/assets/0xD5FFAB1841B9137D5528Ed09D6Ebb66c3088aeDE/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22906 Add FarmerDoge (BEP20)
  blockchains/smartchain/assets/0xEe0736c93E98B2e9fbf11f47dB19E7B68Db71E94/info.json
  blockchains/smartchain/assets/0xEe0736c93E98B2e9fbf11f47dB19E7B68Db71E94/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22918 Add Football INU (BEP20)
  blockchains/smartchain/assets/0x0416846Db6bEa02588e546271D4d83c4061b7757/info.json
  blockchains/smartchain/assets/0x0416846Db6bEa02588e546271D4d83c4061b7757/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22949 Clover
  blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/info.json
  blockchains/ethereum/assets/0x80C62FE4487E1351b47Ba49809EBD60ED085bf52/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22954 Add ETHLAX (BEP20)
  blockchains/smartchain/assets/0x056cB5463Db539985fd6EbfbE5C3D5904C5E8A95/info.json
  blockchains/smartchain/assets/0x056cB5463Db539985fd6EbfbE5C3D5904C5E8A95/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22981 Update logo for Venus (BEP20)
  blockchains/smartchain/assets/0x151B1e2635A717bcDc836ECd6FbB62B674FE3E1D/logo.png
Labels: Payment Status: Paid

#22991 Add XSGD to the tokenlist
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid

#23005 Update vXVS and XVS logos
  blockchains/smartchain/assets/0x151B1e2635A717bcDc836ECd6FbB62B674FE3E1D/logo.png
  blockchains/smartchain/assets/0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63/logo.png
Labels: Payment Status: Requested

#23013 Add tokens APE (BEP20) and OMI (ERC20)
  blockchains/ethereum/assets/0xeD35af169aF46a02eE13b9d79Eb57d6D68C1749e/info.json
  blockchains/ethereum/assets/0xeD35af169aF46a02eE13b9d79Eb57d6D68C1749e/logo.png
  blockchains/smartchain/assets/0xC762043E211571eB34f1ef377e5e8e76914962f9/info.json
  blockchains/smartchain/assets/0xC762043E211571eB34f1ef377e5e8e76914962f9/logo.png
Labels: Payment Status: Paid

#23011 Add Presale.World (BEP20)
  blockchains/smartchain/assets/0x5C197A2D2c9081D30715C80bD1b57c996A14cda0/info.json
  blockchains/smartchain/assets/0x5C197A2D2c9081D30715C80bD1b57c996A14cda0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22992 Add Tamadoge (TAMA) (ERC20)
  blockchains/ethereum/assets/0x12b6893cE26Ea6341919FE289212ef77e51688c8/info.json
  blockchains/ethereum/assets/0x12b6893cE26Ea6341919FE289212ef77e51688c8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23004 Add MMS COIN (BEP20)
  blockchains/smartchain/assets/0x67Db74b6D1Ea807CB47248489c99D144323D348d/info.json
  blockchains/smartchain/assets/0x67Db74b6D1Ea807CB47248489c99D144323D348d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23033 ZFMCOIN Logo Add
  blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/info.json
  blockchains/smartchain/assets/0xce6b8B2787C657f1b98b7A66B5B63178863fd719/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23056 Support Aptos PancakeSwap
  dapps/aptos.pancakeswap.finance.png
Labels: Payment Status: Requested

#23058 Add tokens cronos
  blockchains/cronos/assets/0x0e517979C2c1c1522ddB0c73905e0D39b3F990c0/info.json
  blockchains/cronos/assets/0x0e517979C2c1c1522ddB0c73905e0D39b3F990c0/logo.png
  blockchains/cronos/assets/0xe44Fd7fCb2b1581822D0c862B68222998a0c299a/info.json
  blockchains/cronos/assets/0xe44Fd7fCb2b1581822D0c862B68222998a0c299a/logo.png
  blockchains/smartchain/assets/0x67b725d7e342d7B611fa85e859Df9697D9378B2e/info.json
  blockchains/smartchain/assets/0x67b725d7e342d7B611fa85e859Df9697D9378B2e/logo.png
Labels: Payment Status: Paid

#23060 Migrate for MTG
  blockchains/smartchain/assets/0x68D10dFe87a838D63BbEf6c9A0D0b44beB799DC1/info.json
  blockchains/smartchain/assets/0x68D10dFe87a838D63BbEf6c9A0D0b44beB799DC1/logo.png
Labels: Payment Status: Paid

#23065 Add tokens CRO and KCC
  blockchains/cronos/assets/0x02DCcaf514C98451320a9365C5b46C61d3246ff3/info.json
  blockchains/cronos/assets/0x02DCcaf514C98451320a9365C5b46C61d3246ff3/logo.png
  blockchains/cronos/assets/0xf78a326ACd53651F8dF5D8b137295e434B7c8ba5/info.json
  blockchains/cronos/assets/0xf78a326ACd53651F8dF5D8b137295e434B7c8ba5/logo.png
  blockchains/kcc/assets/0x652D253b7Ca91810A4a05ACFc39729387c5090C0/info.json
  blockchains/kcc/assets/0x652D253b7Ca91810A4a05ACFc39729387c5090C0/logo.png
Labels: Payment Status: Paid

#23027 Add token GAL (ERC20 & BEP20)
  blockchains/ethereum/assets/0x5fAa989Af96Af85384b8a938c2EdE4A7378D9875/info.json
  blockchains/ethereum/assets/0x5fAa989Af96Af85384b8a938c2EdE4A7378D9875/logo.png
  blockchains/smartchain/assets/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5/info.json
  blockchains/smartchain/assets/0xe4Cc45Bb5DBDA06dB6183E8bf016569f40497Aa5/logo.png
Labels: Payment Status: Paid

#23067 Add top tokens exchanges
  blockchains/ethereum/assets/0x94a7f270cd12545A277E656266Aef5e27dF3Eb28/info.json
  blockchains/ethereum/assets/0x94a7f270cd12545A277E656266Aef5e27dF3Eb28/logo.png
  blockchains/ethereum/assets/0xba5BDe662c17e2aDFF1075610382B9B691296350/info.json
  blockchains/ethereum/assets/0xba5BDe662c17e2aDFF1075610382B9B691296350/logo.png
  blockchains/polygon/assets/0x1B815d120B3eF02039Ee11dC2d33DE7aA4a8C603/info.json
  blockchains/polygon/assets/0x1B815d120B3eF02039Ee11dC2d33DE7aA4a8C603/logo.png
  blockchains/polygon/assets/0xA3c322Ad15218fBFAEd26bA7f616249f7705D945/info.json
  blockchains/polygon/assets/0xA3c322Ad15218fBFAEd26bA7f616249f7705D945/logo.png
  blockchains/polygon/assets/0xE7879BaFa6A41F919f145a97207e54839d34c9bA/info.json
  blockchains/polygon/assets/0xE7879BaFa6A41F919f145a97207e54839d34c9bA/logo.png
  blockchains/smartchain/assets/0x35bEdBF9291b22218a0dA863170dcC9329Ef2563/info.json
  blockchains/smartchain/assets/0x35bEdBF9291b22218a0dA863170dcC9329Ef2563/logo.png
  blockchains/smartchain/assets/0x7758a52c1Bb823d02878B67aD87B6bA37a0CDbF5/info.json
  blockchains/smartchain/assets/0x7758a52c1Bb823d02878B67aD87B6bA37a0CDbF5/logo.png
  blockchains/smartchain/assets/0x7A532Aa9A2Ab86f6BD7E1Dcd93d3FdD2B0B410a6/info.json
  blockchains/smartchain/assets/0x7A532Aa9A2Ab86f6BD7E1Dcd93d3FdD2B0B410a6/logo.png
  blockchains/smartchain/assets/0x800a25741A414Ea6E6e2B382435081A479A8Cc3c/info.json
  blockchains/smartchain/assets/0x800a25741A414Ea6E6e2B382435081A479A8Cc3c/logo.png
  blockchains/smartchain/assets/0xAE788F80F2756A86aa2F410C651F2aF83639B95b/info.json
  blockchains/smartchain/assets/0xAE788F80F2756A86aa2F410C651F2aF83639B95b/logo.png
  blockchains/smartchain/assets/0xeD00Fc7D48B57B81FE65D1cE71c0985e4CF442CB/info.json
  blockchains/smartchain/assets/0xeD00Fc7D48B57B81FE65D1cE71c0985e4CF442CB/logo.png
  blockchains/solana/assets/E5rk3nmgLUuKUiS94gg4bpWwWwyjCMtddsAXkTFLtHEy/info.json
  blockchains/solana/assets/E5rk3nmgLUuKUiS94gg4bpWwWwyjCMtddsAXkTFLtHEy/logo.png
Labels: Payment Status: Paid

#23072 Migration for LOF (BEP20)
  blockchains/smartchain/assets/0xB3225aC90B741f762BecA76dEA1eaD278Ef26A96/info.json
  blockchains/smartchain/assets/0xB3225aC90B741f762BecA76dEA1eaD278Ef26A96/logo.png
Labels: Payment Status: Paid

#23073 Migration for LOF (BEP20)
  blockchains/smartchain/assets/0xe702c303173f90094ce8c9c6CA3f198eCA0E027C/info.json
  blockchains/smartchain/assets/0xe702c303173f90094ce8c9c6CA3f198eCA0E027C/logo.png
Labels: Payment Status: Paid

#23071 Add kavaevm rpc
  blockchains/kavaevm/info/info.json
Labels: Payment Status: Paid

#23082 Add rpc url
  blockchains/aurora/info/info.json
  blockchains/avalanchec/info/info.json
  blockchains/boba/info/info.json
  blockchains/celo/info/info.json
  blockchains/fantom/info/info.json
  blockchains/heco/info/info.json
  blockchains/klaytn/info/info.json
  blockchains/polygon/info/info.json
Labels: Payment Status: Paid

#23091 [NewBlockchain]: add Hedera blockchain
  blockchains/hedera/info/info.json
  blockchains/hedera/info/logo.png
Labels: Payment Status: Paid

#22045 Add Flycoin (POLYGON)
  blockchains/polygon/assets/0×486FFAf06A681bf22B5209e9fFCE722662A60E8C/info.json
  blockchains/polygon/assets/0×486FFAf06A681bf22B5209e9fFCE722662A60E8C/logo.png
Labels: Status: On Hold, Payment Status: Paid, Payment Status: Requested

#23104 Add tokens (CRC20) (KRC20)
  blockchains/cronos/assets/0x63888BaFc5975630E4E5CF50c3845a3250115F64/info.json
  blockchains/cronos/assets/0x63888BaFc5975630E4E5CF50c3845a3250115F64/logo.png
  blockchains/kcc/assets/0x73b6086955c820370A18002F60E9b51FB67d7e1A/info.json
  blockchains/kcc/assets/0x73b6086955c820370A18002F60E9b51FB67d7e1A/logo.png
  blockchains/kcc/assets/0xf55aF137A98607F7ED2eFEfA4cd2DfE70E4253b1/info.json
  blockchains/kcc/assets/0xf55aF137A98607F7ED2eFEfA4cd2DfE70E4253b1/logo.png
Labels: Payment Status: Paid

#23039 Add Cherry Network (BEP20, POLYGON, ERC20)
  blockchains/ethereum/assets/0xa20f77B7ad5A88badC48800C56507B7274c06Fdc/info.json
  blockchains/ethereum/assets/0xa20f77B7ad5A88badC48800C56507B7274c06Fdc/logo.png
  blockchains/polygon/assets/0x8f36Cc333F55B09Bb71091409A3d7ADE399e3b1C/info.json
  blockchains/polygon/assets/0x8f36Cc333F55B09Bb71091409A3d7ADE399e3b1C/logo.png
  blockchains/smartchain/assets/0x8f36Cc333F55B09Bb71091409A3d7ADE399e3b1C/info.json
  blockchains/smartchain/assets/0x8f36Cc333F55B09Bb71091409A3d7ADE399e3b1C/logo.png
Labels: Payment Status: Paid

#23111 Add tokens
  blockchains/ethereum/assets/0x3A8cCCB969a61532d1E6005e2CE12C200caeCe87/info.json
  blockchains/ethereum/assets/0x3A8cCCB969a61532d1E6005e2CE12C200caeCe87/logo.png
  blockchains/ethereum/assets/0xa3EE21C306A700E682AbCdfe9BaA6A08F3820419/info.json
  blockchains/ethereum/assets/0xa3EE21C306A700E682AbCdfe9BaA6A08F3820419/logo.png
  blockchains/ethereum/assets/0xdebe620609674F21B1089042527F420372eA98A5/info.json
  blockchains/ethereum/assets/0xdebe620609674F21B1089042527F420372eA98A5/logo.png
  blockchains/smartchain/assets/0x6Ced2d77eEb7a6e392CC2b1A3b44C872F49fa602/info.json
  blockchains/smartchain/assets/0x6Ced2d77eEb7a6e392CC2b1A3b44C872F49fa602/logo.png
Labels: Payment Status: Paid

#23034 Add BBC and logo
  blockchains/smartchain/assets/0x37e5da11b6A4DC6d2f7Abe232cDd30B0B8Fc63B1/info.json
  blockchains/smartchain/assets/0x37e5da11b6A4DC6d2f7Abe232cDd30B0B8Fc63B1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23113 Update description
  blockchains/smartchain/assets/0x6Ced2d77eEb7a6e392CC2b1A3b44C872F49fa602/info.json
Labels: Payment Status: Paid

#23166 Migration for QBX (ERC20)
  blockchains/ethereum/assets/0x2467AA6B5A2351416fD4C3DeF8462d841feeecEC/info.json
  blockchains/ethereum/assets/0x2467AA6B5A2351416fD4C3DeF8462d841feeecEC/logo.png
  blockchains/ethereum/assets/0x26E1f9F817b3b5FC2146c01ae34826593E593962/info.json
  blockchains/ethereum/assets/0x26E1f9F817b3b5FC2146c01ae34826593E593962/logo.png
Labels: Payment Status: Paid

#23168 Add KCC-Peg Aave(KRC20)
  blockchains/kcc/assets/0xE76e97C157658004eE22e01C03a5e21A4655A2Fd/info.json
  blockchains/kcc/assets/0xE76e97C157658004eE22e01C03a5e21A4655A2Fd/logo.png
Labels: Payment Status: Paid

#23125 add kodexpay
  blockchains/smartchain/assets/0x02a655942Dbb886c77bb22B270060c561300B0E2/info.json
  blockchains/smartchain/assets/0x02a655942Dbb886c77bb22B270060c561300B0E2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23162 Add GGT logo and info
  blockchains/smartchain/assets/0xd2359c576632234D1354B20Bf51B0277Be20C81e/info.json
  blockchains/smartchain/assets/0xd2359c576632234D1354B20Bf51B0277Be20C81e/logo.png
Labels: Payment Status: Paid

#23163 Add new Terra Classic validator: 1% MAX fee & 100% UPTIME
  blockchains/terra/validators/assets/terravaloper1pu8lpz64erz47eemtkhq9wzwu9st9ehywnlw4q/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid

#23190 Add iMe Lab (BEP20)
  blockchains/smartchain/assets/0x7bC75e291E656E8658D66Be1cc8154A3769A35Dd/info.json
  blockchains/smartchain/assets/0x7bC75e291E656E8658D66Be1cc8154A3769A35Dd/logo.png
Labels: Payment Status: Paid

#23207 Add Atomic Nodes Cosmos validator
  blockchains/cosmos/validators/assets/cosmosvaloper1hjadhj9nqzpye2vkmkz4thahhd0z8dh3udhq74/logo.png
  blockchains/cosmos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23209 Update logo and info for ton blockchain
  blockchains/ton/info/info.json
  blockchains/ton/info/logo.png
Labels: Payment Status: Requested

#23212 Add juno blockchain
  blockchains/cosmos/chainlist.json
  blockchains/juno/info/info.json
  blockchains/juno/info/logo.png
Labels: Payment Status: Paid

#23102 Add Tronix (TRX) (ERC20)
  blockchains/ethereum/assets/0xf230b790E05390FC8295F4d3F60332c93BEd42e2/info.json
  blockchains/ethereum/assets/0xf230b790E05390FC8295F4d3F60332c93BEd42e2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23241 Add Polygon (KRC20)
  blockchains/kcc/assets/0x1B8e27ABA297466fc6765Ce55BD12A8E216759da/info.json
  blockchains/kcc/assets/0x1B8e27ABA297466fc6765Ce55BD12A8E216759da/logo.png
Labels: Payment Status: Paid

#23217 Add chainlist Cosmos
  blockchains/axelar/info/info.json
  blockchains/axelar/info/logo.png
  blockchains/cosmos/chainlist.json
  blockchains/secret/info/info.json
  blockchains/secret/info/logo.png
  blockchains/stargaze/info/info.json
  blockchains/stargaze/info/logo.png
Labels: Payment Status: Paid

#23246 Add Silo Finance (SILO) (ERC20)
  blockchains/ethereum/assets/0x6f80310CA7F2C654691D1383149Fa1A57d8AB1f8/info.json
  blockchains/ethereum/assets/0x6f80310CA7F2C654691D1383149Fa1A57d8AB1f8/logo.png
Labels: Payment Status: Paid

#23250 Update logo for PNG
  blockchains/avalanchec/assets/0x60781C2586D68229fde47564546784ab3fACA982/info.json
  blockchains/avalanchec/assets/0x60781C2586D68229fde47564546784ab3fACA982/logo.png
Labels: Payment Status: Paid

#23258 Update info and logo for Thunder tokens
  blockchains/smartchain/assets/0x990E7154bB999FAa9b2fa5Ed29E822703311eA85/info.json
  blockchains/thundertoken/assets/0x0212b1F75503413b01A98158434c4570FB6e808c/info.json
  blockchains/thundertoken/assets/0x0212b1F75503413b01A98158434c4570FB6e808c/logo.png
  blockchains/thundertoken/assets/0x18fB0A62f207A2a082cA60aA78F47a1af4985190/info.json
  blockchains/thundertoken/assets/0x18fB0A62f207A2a082cA60aA78F47a1af4985190/logo.png
  blockchains/thundertoken/assets/0x22e89898A04eaf43379BeB70bf4E38b1faf8A31e/info.json
  blockchains/thundertoken/assets/0x22e89898A04eaf43379BeB70bf4E38b1faf8A31e/logo.png
  blockchains/thundertoken/assets/0x2b31e3b88847f03c1335E99A0d1274A2c72059DE/info.json
  blockchains/thundertoken/assets/0x4f3C8E20942461e2c3Bdd8311AC57B0c222f2b82/info.json
  blockchains/thundertoken/assets/0x4f3C8E20942461e2c3Bdd8311AC57B0c222f2b82/logo.png
  blockchains/thundertoken/assets/0x6576Bb918709906DcbFDCeae4bB1e6df7C8a1077/info.json
  blockchains/thundertoken/assets/0x6576Bb918709906DcbFDCeae4bB1e6df7C8a1077/logo.png
  blockchains/thundertoken/assets/0x8EF1A1E0671Aa44852f4d87105eF482470bB3e69/info.json
  blockchains/thundertoken/assets/0x8EF1A1E0671Aa44852f4d87105eF482470bB3e69/logo.png
  blockchains/thundertoken/assets/0xBEB0131D95AC3F03fd15894D0aDE5DBf7451d171/info.json
  blockchains/thundertoken/assets/0xBEB0131D95AC3F03fd15894D0aDE5DBf7451d171/logo.png
  blockchains/thundertoken/assets/0xFd6Ec3E37F112bD30BbD726E7b0E73000CC2B98d/info.json
  blockchains/thundertoken/assets/0xFd6Ec3E37F112bD30BbD726E7b0E73000CC2B98d/logo.png
  blockchains/thundertoken/info/info.json
Labels: Payment Status: Paid
