Repository trustwallet/assets, pull requests merged in 2022-01, with the labels that each got.

#16916 Add ISLAMICOIN (SPL)
  blockchains/solana/assets/HG2FnifX1WPY6UvnkXnMx2kAt4E4Ssu6DZ2aiB5RmLHo/info.json
  blockchains/solana/assets/HG2FnifX1WPY6UvnkXnMx2kAt4E4Ssu6DZ2aiB5RmLHo/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#16907 Add KAKA logo and info
  blockchains/smartchain/assets/0x26a1BdFa3bb86b2744c4A42EBfDd205761d13a8a/info.json
  blockchains/smartchain/assets/0x26a1BdFa3bb86b2744c4A42EBfDd205761d13a8a/logo.png
Labels: Payment Status: Paid

#16975 Change contract for CLEAN (BEP20)
  blockchains/smartchain/assets/0x579F11C75Eb4e47F5290122e87CA411644aDCD97/info.json
  blockchains/smartchain/assets/0x579F11C75Eb4e47F5290122e87CA411644aDCD97/logo.png
Labels: Payment Status: Paid

#16973 Change contract address
  blockchains/smartchain/assets/0x5E19266e4a17521d65EFF608517fA0c82CA24813/info.json
  blockchains/smartchain/assets/0x5E19266e4a17521d65EFF608517fA0c82CA24813/logo.png
Labels: Payment Status: Paid

#16968 Adding BNBGOLD
  blockchains/smartchain/assets/0xC836DCC9c880D4558C301e6d439db1B1DCaF7F3a/info.json
  blockchains/smartchain/assets/0xC836DCC9c880D4558C301e6d439db1B1DCaF7F3a/logo.png
Labels: Payment Status: Paid

#16974 Add The Essential Coin (BEP20)
  blockchains/smartchain/assets/0x4c48cca6153Db911002F965D22fdeFcD95f33BE9/info.json
  blockchains/smartchain/assets/0x4c48cca6153Db911002F965D22fdeFcD95f33BE9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#16937 Migrate TrustWallet Support from Avalanche to BSC
  blockchains/smartchain/assets/0xcAf23964Ca8db16D816eB314a56789F58fE0e10e/info.json
  blockchains/smartchain/assets/0xcAf23964Ca8db16D816eB314a56789F58fE0e10e/logo.png
Labels: Payment Status: Paid

#17014 Add NFT token (BEP20)
  blockchains/smartchain/assets/0x1fC9004eC7E5722891f5f38baE7678efCB11d34D/info.json
  blockchains/smartchain/assets/0x1fC9004eC7E5722891f5f38baE7678efCB11d34D/logo.png
Labels: Payment Status: Paid

#17039 Add Wrapped ElectricCash (BEP20)
  blockchains/smartchain/assets/0x1722bf5DA9391D6986092b90a53672E8E0fead83/info.json
  blockchains/smartchain/assets/0x1722bf5DA9391D6986092b90a53672E8E0fead83/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17046 Add token RADAR (ERC20)
  blockchains/ethereum/assets/0x44709a920fCcF795fbC57BAA433cc3dd53C44DbE/info.json
  blockchains/ethereum/assets/0x44709a920fCcF795fbC57BAA433cc3dd53C44DbE/logo.png
Labels: Payment Status: Paid

#17030 Add GMI token (ERC20)
  blockchains/ethereum/assets/0x47110d43175f7f2C2425E7d15792acC5817EB44f/info.json
  blockchains/ethereum/assets/0x47110d43175f7f2C2425E7d15792acC5817EB44f/logo.png
Labels: Payment Status: Paid

#17067 Add Dx.App DAPP
  dapps/dx.app.png
Labels: Payment Status: Paid, Payment Status: Requested

#17003 application for Son of Doge V2
  blockchains/smartchain/assets/0xCDB943908DE5Ee37998a53f23467017d1A307E60/info.json
  blockchains/smartchain/assets/0xCDB943908DE5Ee37998a53f23467017d1A307E60/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17074 Add TFI token
  blockchains/smartchain/assets/0x7565ab68D3F9DaDff127F864103C8c706Cf28235/info.json
  blockchains/smartchain/assets/0x7565ab68D3F9DaDff127F864103C8c706Cf28235/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17091 Change logo for FTM (ERC20)
  blockchains/ethereum/assets/0x4E15361FD6b4BB609Fa63C81A2be19d873717870/info.json
  blockchains/ethereum/assets/0x4E15361FD6b4BB609Fa63C81A2be19d873717870/logo.png
Labels: Payment Status: Paid

#17089 Add Baby Doge Coin (BEP20)
  blockchains/smartchain/assets/0xc748673057861a797275CD8A068AbB95A902e8de/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#17099 Add demanding tokens
  blockchains/ethereum/assets/0x0E69D0A2bbB30aBcB7e5CfEA0E4FDe19C00A8d47/info.json
  blockchains/ethereum/assets/0x0E69D0A2bbB30aBcB7e5CfEA0E4FDe19C00A8d47/logo.png
  blockchains/polygon/assets/0x229b1b6C23ff8953D663C4cBB519717e323a0a84/info.json
  blockchains/polygon/assets/0x229b1b6C23ff8953D663C4cBB519717e323a0a84/logo.png
  blockchains/smartchain/assets/0x0b33542240d6fA323c796749F6D6869fdB7F13cA/info.json
  blockchains/smartchain/assets/0x0b33542240d6fA323c796749F6D6869fdB7F13cA/logo.png
  blockchains/smartchain/assets/0x12b83d77a606D8f5c4CE29dfFdb592C523364995/info.json
  blockchains/smartchain/assets/0x12b83d77a606D8f5c4CE29dfFdb592C523364995/logo.png
  blockchains/smartchain/assets/0x16f9cc3c6F8d8006cfc0ee693CeF9D76b0d44C36/info.json
  blockchains/smartchain/assets/0x16f9cc3c6F8d8006cfc0ee693CeF9D76b0d44C36/logo.png
  blockchains/smartchain/assets/0x17FEa92CA2e7570d07b63ecD6B698e01386555A4/info.json
  blockchains/smartchain/assets/0x17FEa92CA2e7570d07b63ecD6B698e01386555A4/logo.png
  blockchains/smartchain/assets/0x26165a5a3Dd21FA528bECf3Ff7F114D00a517344/info.json
  blockchains/smartchain/assets/0x26165a5a3Dd21FA528bECf3Ff7F114D00a517344/logo.png
  blockchains/smartchain/assets/0x2e42C9EAc96833C6e16Dc71c743cECC114CCD7e3/info.json
  blockchains/smartchain/assets/0x2e42C9EAc96833C6e16Dc71c743cECC114CCD7e3/logo.png
  blockchains/smartchain/assets/0x6397de0F9aEDc0F7A8Fa8B438DDE883B9c201010/info.json
  blockchains/smartchain/assets/0x6397de0F9aEDc0F7A8Fa8B438DDE883B9c201010/logo.png
  blockchains/smartchain/assets/0x68810a6F5bB0491cB9Ccf8c52735A1acf5f28009/info.json
  blockchains/smartchain/assets/0x68810a6F5bB0491cB9Ccf8c52735A1acf5f28009/logo.png
  blockchains/smartchain/assets/0x68E374F856bF25468D365E539b700b648Bf94B67/info.json
  blockchains/smartchain/assets/0x68E374F856bF25468D365E539b700b648Bf94B67/logo.png
  blockchains/smartchain/assets/0x755f34709E369D37C6Fa52808aE84A32007d1155/info.json
  blockchains/smartchain/assets/0x755f34709E369D37C6Fa52808aE84A32007d1155/logo.png
  blockchains/smartchain/assets/0x7CD8c22D3F4b66230F73D7FfCB48576233c3fe33/info.json
  blockchains/smartchain/assets/0x7CD8c22D3F4b66230F73D7FfCB48576233c3fe33/logo.png
  blockchains/smartchain/assets/0x7dDEE176F665cD201F93eEDE625770E2fD911990/info.json
  blockchains/smartchain/assets/0x7dDEE176F665cD201F93eEDE625770E2fD911990/logo.png
  blockchains/smartchain/assets/0x88803312628fd21542F706B0C7dC8495c1c10B2e/info.json
  blockchains/smartchain/assets/0x88803312628fd21542F706B0C7dC8495c1c10B2e/logo.png
  blockchains/smartchain/assets/0x8C851d1a123Ff703BD1f9dabe631b69902Df5f97/info.json
  blockchains/smartchain/assets/0x8C851d1a123Ff703BD1f9dabe631b69902Df5f97/logo.png
  blockchains/smartchain/assets/0x8d9fB713587174Ee97e91866050c383b5cEE6209/info.json
  blockchains/smartchain/assets/0x8d9fB713587174Ee97e91866050c383b5cEE6209/logo.png
  blockchains/smartchain/assets/0x921d3a6ed8223AFb6358410F717e2FB13cbae700/info.json
  blockchains/smartchain/assets/0x921d3a6ed8223AFb6358410F717e2FB13cbae700/logo.png
  blockchains/smartchain/assets/0xB7DAcf54a54bFea818F21472d3E71a89287841A7/info.json
  blockchains/smartchain/assets/0xB7DAcf54a54bFea818F21472d3E71a89287841A7/logo.png
  blockchains/smartchain/assets/0xE38950f71E2D2Fc4cA9dC9C3625d82560b0A5d8F/info.json
  blockchains/smartchain/assets/0xE38950f71E2D2Fc4cA9dC9C3625d82560b0A5d8F/logo.png
  blockchains/smartchain/assets/0xEC126e20e7cb114dd3BA356100eaca2Cc2921322/info.json
  blockchains/smartchain/assets/0xEC126e20e7cb114dd3BA356100eaca2Cc2921322/logo.png
  blockchains/smartchain/assets/0xF0A8EcBCE8caADB7A07d1FcD0f87Ae1Bd688dF43/info.json
  blockchains/smartchain/assets/0xF0A8EcBCE8caADB7A07d1FcD0f87Ae1Bd688dF43/logo.png
  blockchains/smartchain/assets/0xF7A086BFf67DeD4Aa785e8a0a81D4345d9bb4740/info.json
  blockchains/smartchain/assets/0xF7A086BFf67DeD4Aa785e8a0a81D4345d9bb4740/logo.png
  blockchains/smartchain/assets/0xbbe0A94f363a52dA9229A7546434b6e657A6A78F/info.json
  blockchains/smartchain/assets/0xbbe0A94f363a52dA9229A7546434b6e657A6A78F/logo.png
  blockchains/smartchain/assets/0xcea59DCE6A6d73a24e6d6944CFaBc330814c098A/info.json
  blockchains/smartchain/assets/0xcea59DCE6A6d73a24e6d6944CFaBc330814c098A/logo.png
  blockchains/smartchain/assets/0xd4EBABd6E70Bf0a16e8cCDBc6b00fE7817390f47/info.json
  blockchains/smartchain/assets/0xd4EBABd6E70Bf0a16e8cCDBc6b00fE7817390f47/logo.png
  blockchains/smartchain/assets/0xec6cA5A04B08e382d218De9Cb30C9d8176406D34/info.json
  blockchains/smartchain/assets/0xec6cA5A04B08e382d218De9Cb30C9d8176406D34/logo.png
  dapps/dapps-www.pinksale.finance.png
  dapps/marketplace.thetanarena.com.png
Labels: Payment Status: Paid

#17097 Add SPACES info and logo
  blockchains/smartchain/assets/0x156df0dd6300C73ac692D805720967cf4464776e/info.json
  blockchains/smartchain/assets/0x156df0dd6300C73ac692D805720967cf4464776e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17100 Add Blockchain Monster Hunt (BCMC) (BEP20)
  blockchains/smartchain/assets/0xc10358f062663448a3489fC258139944534592ac/info.json
  blockchains/smartchain/assets/0xc10358f062663448a3489fC258139944534592ac/logo.png
Labels: Payment Status: Paid

#17103 add tag to BCMC
  blockchains/smartchain/assets/0xc10358f062663448a3489fC258139944534592ac/info.json
Labels: Payment Status: Paid

#17101 Add Nyx Token (ERC20)
  blockchains/ethereum/assets/0x118b552725e1892137740cB4d29390D952709639/info.json
  blockchains/ethereum/assets/0x118b552725e1892137740cB4d29390D952709639/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17105 Update BCMC logo
  blockchains/smartchain/assets/0xc10358f062663448a3489fC258139944534592ac/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17075 Add LFW logo and info
  blockchains/smartchain/assets/0xD71239a33C8542Bd42130c1B4ACA0673B4e4f48B/info.json
  blockchains/smartchain/assets/0xD71239a33C8542Bd42130c1B4ACA0673B4e4f48B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17106 Add Sphynx ETH (SPHYNX) (ERC20)
  blockchains/ethereum/assets/0x94DFd4E2210Fa5B752c3CD0f381edad9dA6640f8/info.json
  blockchains/ethereum/assets/0x94DFd4E2210Fa5B752c3CD0f381edad9dA6640f8/logo.png
Labels: Payment Status: Paid

#17113 Add Metakings (BEP20)
  blockchains/smartchain/assets/0x129385C4ACd0075e45A0C9a5177BdfEc9678A138/info.json
  blockchains/smartchain/assets/0x129385C4ACd0075e45A0C9a5177BdfEc9678A138/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17114 Change logo for Polkadot (BEP20)
  blockchains/polkadot/info/logo.png
  blockchains/smartchain/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/logo.png
Labels: Payment Status: Paid

#17102 add Token Meta-World
  blockchains/smartchain/assets/0xfCe3EFebC79d21a6B7cc7F3A7216E66e81f4B23B/info.json
  blockchains/smartchain/assets/0xfCe3EFebC79d21a6B7cc7F3A7216E66e81f4B23B/logo.png
Labels: Payment Status: Paid

#17115 Add WEB3 Inu (BEP20)
  blockchains/smartchain/assets/0xd0c4BC1B89BbD105EeCb7EBa3f13E7648c0De38F/info.json
  blockchains/smartchain/assets/0xd0c4BC1B89BbD105EeCb7EBa3f13E7648c0De38F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17153 Add OBRok Token (BEP20)
  blockchains/smartchain/assets/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C/info.json
  blockchains/smartchain/assets/0x205AFD08ceFe438377a0abC5a20Cb4462E1a8C5C/logo.png
Labels: Payment Status: Paid

#17163 Fix Binance tokenlist
  blockchains/binance/tokenlist.json
Labels: FeePayment: Paid

#17150 Add WOOP (BEEP20)
  blockchains/smartchain/assets/0x8b303d5BbfBbf46F1a4d9741E491e06986894e18/info.json
  blockchains/smartchain/assets/0x8b303d5BbfBbf46F1a4d9741E491e06986894e18/logo.png
Labels: Payment Status: Paid

#17187 Add Wrapped JAXNET (BEP20)
  blockchains/smartchain/assets/0xcA1262e77Fb25c0a4112CFc9bad3ff54F617f2e6/info.json
  blockchains/smartchain/assets/0xcA1262e77Fb25c0a4112CFc9bad3ff54F617f2e6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17057 Add DG token logo and info (ERC20)
  blockchains/ethereum/assets/0x4b520c812E8430659FC9f12f6d0c39026C83588D/info.json
  blockchains/ethereum/assets/0x4b520c812E8430659FC9f12f6d0c39026C83588D/logo.png
  blockchains/polygon/assets/0xef938b6da8576a896f6E0321ef80996F4890f9c4/info.json
  blockchains/polygon/assets/0xef938b6da8576a896f6E0321ef80996F4890f9c4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17199 Add Multi-Chain Capital (BEP20)
  blockchains/smartchain/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/info.json
  blockchains/smartchain/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/logo.png
Labels: Payment Status: Paid

#17194 Add HeroCatKey (BEP20)
  blockchains/smartchain/assets/0x032A4E59387e08443Cf1df662141da09c31ceFa1/info.json
  blockchains/smartchain/assets/0x032A4E59387e08443Cf1df662141da09c31ceFa1/logo.png
Labels: Payment Status: Paid

#17191 Add HeroCatToken (BEP20)
  blockchains/smartchain/assets/0x29A1e54DE0fCE58E1018535d30aF77A9d2D940c4/info.json
  blockchains/smartchain/assets/0x29A1e54DE0fCE58E1018535d30aF77A9d2D940c4/logo.png
Labels: Payment Status: Paid

#17176 add Daily COP info and logo for Polygon
  blockchains/polygon/assets/0x1659fFb2d40DfB1671Ac226A0D9Dcc95A774521A/info.json
  blockchains/polygon/assets/0x1659fFb2d40DfB1671Ac226A0D9Dcc95A774521A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17205 Add JACY (JACY) (ERC20)
  blockchains/ethereum/assets/0x916c5DE09cF63f6602d1e1793FB41F6437814A62/info.json
  blockchains/ethereum/assets/0x916c5DE09cF63f6602d1e1793FB41F6437814A62/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#17237 Add Tranchess BSC validator node logo and info
  blockchains/binance/validators/assets/bva1m3nj2sglp7mlz3y08qjlqyhycenz8m9cl4h4ht/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#17026 Add CR7 Token (BEP20)
  blockchains/smartchain/assets/0x6C43751FeF27C956f7E75D5c345a65df1465f7E0/info.json
  blockchains/smartchain/assets/0x6C43751FeF27C956f7E75D5c345a65df1465f7E0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17226 We got our Certik audit now so we hope we can get listed
  blockchains/smartchain/assets/0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483/info.json
  blockchains/smartchain/assets/0x8B6fA031c7D2E60fbFe4E663EC1B8f37Df1ba483/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17243 add links for LOOKS (ERC20)
  blockchains/ethereum/assets/0xf4d2888d29D722226FafA5d9B24F9164c092421E/info.json
  blockchains/ethereum/assets/0xf4d2888d29D722226FafA5d9B24F9164c092421E/logo.png
Labels: Payment Status: Paid

#17251 Refactor code
  internal/file/types.go
  internal/processor/service.go
Labels: Payment Status: Requested

#17218 Update GNBU token info (ERC20)
  blockchains/smartchain/assets/0xA4d872235dde5694AF92a1d0df20d723E8e9E5fC/info.json
  blockchains/smartchain/assets/0xA4d872235dde5694AF92a1d0df20d723E8e9E5fC/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17219 Update NBU token info (ERC20)
  blockchains/ethereum/assets/0xEB58343b36C7528F23CAAe63a150240241310049/info.json
  blockchains/ethereum/assets/0xEB58343b36C7528F23CAAe63a150240241310049/logo.png
Labels: Payment Status: Paid

#17248 Add TWT logo and Info
  blockchains/smartchain/assets/0x66dA5cc445feC38A9475Ae7941f89110b9d256b9/info.json
  blockchains/smartchain/assets/0x66dA5cc445feC38A9475Ae7941f89110b9d256b9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17254 Add Kiba Inu (ERC20)
  blockchains/ethereum/assets/0x4B2C54b80B77580dc02A0f6734d3BAD733F50900/info.json
  blockchains/ethereum/assets/0x4B2C54b80B77580dc02A0f6734d3BAD733F50900/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17260 Add The Flash Currency (TRC10)
  blockchains/tron/assets/1004117/info.json
  blockchains/tron/assets/1004117/logo.png
Labels: Payment Status: Paid

#17274 Br0109 121848
  blockchains/smartchain/assets/0xe5a46Bf898ce7583B612E5D168073ff773D7857e/info.json
  blockchains/smartchain/assets/0xe5a46Bf898ce7583B612E5D168073ff773D7857e/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17319 Add Kiba Inu (BEP20)
  blockchains/smartchain/assets/0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341/info.json
  blockchains/smartchain/assets/0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17139 add ZenFi AI logo and info
  blockchains/smartchain/assets/0xA84d7A90bDbBe6dE3FFFe9B7F549366320EF90D3/info.json
  blockchains/smartchain/assets/0xA84d7A90bDbBe6dE3FFFe9B7F549366320EF90D3/logo.png
Labels: Payment Status: Paid

#17301 Add SpongeBob Square (BEP20)
  blockchains/smartchain/assets/0x471f883BBd2c705F418Ba3d6667ef05342C4ee05/info.json
  blockchains/smartchain/assets/0x471f883BBd2c705F418Ba3d6667ef05342C4ee05/logo.png
Labels: Status: On Hold, Payment Status: Paid

#17270 Add Reserve Rights (RSR) (ERC20)
  blockchains/ethereum/assets/0x320623b8E4fF03373931769A31Fc52A4E78B5d70/info.json
  blockchains/ethereum/assets/0x320623b8E4fF03373931769A31Fc52A4E78B5d70/logo.png
Labels: Payment Status: Requested

#17338 Add command for adding asset template
  .github/workflows/check.yml
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
  .github/workflows/pr-ci.yml
  Makefile
  README.md
  blockchains/terra/assets/ukrw/info.json
  blockchains/terra/assets/umnt/info.json
  blockchains/terra/assets/usdr/info.json
  blockchains/terra/assets/uusd/info.json
  cmd/main.go
  go.mod
  go.sum
  internal/config/values.go
  internal/manager/commands.go
  internal/manager/helpers.go
  internal/service/service.go
Labels: Payment Status: Requested

#17340 [Internal] Add CW20 Terra token Anchor Protocol ANC
  blockchains/terra/assets/terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76/info.json
  blockchains/terra/assets/terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76/logo.png
Labels: Payment Status: Paid

#17364 Add Consensus One
  blockchains/osmosis/validators/assets/osmovaloper1ldu6ew0cff400qmn0trkad38gx250zny45q9au/logo.png
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#17271 Add Euro Shiba Inu #16348 (BEP20)
  blockchains/smartchain/assets/0xFfaA85705aE216363e4e843B67fF3C238Fcf0de2/info.json
  blockchains/smartchain/assets/0xFfaA85705aE216363e4e843B67fF3C238Fcf0de2/logo.png
Labels: Payment Status: Paid

#17357 Add BleuFi (BEP20)
  blockchains/smartchain/assets/0xfFdC00285DDe1f5b5c65C6a963357b4C55d8f601/info.json
  blockchains/smartchain/assets/0xfFdC00285DDe1f5b5c65C6a963357b4C55d8f601/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17339 Add deflationary tags (ERC20)
  blockchains/ethereum/assets/0x14409B0Fc5C7f87b5DAd20754fE22d29A3dE8217/info.json
  blockchains/ethereum/assets/0x1C95b093d6C236d3EF7c796fE33f9CC6b8606714/info.json
  blockchains/ethereum/assets/0x239Dc02A28a0774738463E06245544a72745d5c5/info.json
  blockchains/ethereum/assets/0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1/info.json
  blockchains/ethereum/assets/0x382f0160c24f5c515A19f155BAc14d479433A407/info.json
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/info.json
  blockchains/ethereum/assets/0x3B7f247f21BF3A07088C2D3423F64233d4B069F7/info.json
  blockchains/ethereum/assets/0x456D8f0D25A4e787eE60c401F8B963a465148f70/info.json
  blockchains/ethereum/assets/0x92a42Db88Ed0F02c71D439e55962Ca7CAB0168b5/info.json
  blockchains/ethereum/assets/0xB6eE603933E024d8d53dDE3faa0bf98fE2a3d6f1/info.json
  blockchains/ethereum/assets/0xBdea5bB640DBFC4593809DEeC5CdB8F99b704Cd2/info.json
  blockchains/ethereum/assets/0xDB7Eab9bA6be88B869F738f6DEeBa96d49Fe13fd/info.json
  blockchains/smartchain/assets/0x92a42Db88Ed0F02c71D439e55962Ca7CAB0168b5/info.json
  blockchains/smartchain/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/info.json
Labels: Payment Status: Paid

#17431 Update Cake Logo (BEP20)
  blockchains/smartchain/assets/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82/logo.png
Labels: Payment Status: Requested

#17273 Uploading Additional Information Regarding "NFTY"
  blockchains/smartchain/assets/0x5774B2fc3e91aF89f89141EacF76545e74265982/info.json
  blockchains/smartchain/assets/0x5774B2fc3e91aF89f89141EacF76545e74265982/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17452 add osmosis validators
  blockchains/osmosis/validators/assets/osmovaloper10rsjwrcj7maz4f0l8dh3smjd022n9ya8ycuyg7/logo.png
  blockchains/osmosis/validators/assets/osmovaloper16gm3cvhluf9xfurkx9qgxq7pldvd479l0j6zms/logo.png
  blockchains/osmosis/validators/assets/osmovaloper16n0t7lmy4wnhjytzkncjdkxrsu9yfjm3ex7hxr/logo.png
  blockchains/osmosis/validators/assets/osmovaloper1glmy88g0uf6vmw29pyxu3yq0pxpjqtzqr5e57n/logo.png
  blockchains/osmosis/validators/assets/osmovaloper1nskmzc8cqf8m9vwrxvnggtw4vw9cwx54jtfmuj/logo.png
  blockchains/osmosis/validators/assets/osmovaloper1xgqr7pn80g6w398wzdmye3lu6wsgk32sw670ec/logo.png
  blockchains/osmosis/validators/assets/osmovaloper1xwazl8ftks4gn00y5x3c47auquc62ssuh8af89/logo.png
  blockchains/osmosis/validators/assets/osmovaloper1z0sh4s80u99l6y9d3vfy582p8jejeeu6tcucs2/logo.png
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#17467 add eCash
  blockchains/ecash/info/info.json
  blockchains/ecash/info/logo.png
Labels: Payment Status: Requested

#17466 Add DeepMaze (BEP20)
  blockchains/smartchain/assets/0xdC0118B27276065C573386aa44e7a6E5e2AF07C1/info.json
  blockchains/smartchain/assets/0xdC0118B27276065C573386aa44e7a6E5e2AF07C1/logo.png
Labels: Payment Status: Paid

#17439 noku token informations update
  blockchains/ethereum/assets/0x1fC52f1ABade452Dd4674477D4711951700b3d27/info.json
  blockchains/ethereum/assets/0x1fC52f1ABade452Dd4674477D4711951700b3d27/logo.png
  blockchains/ethereum/assets/0x8167D3B1024cB51A2DD1B4d889ddf7023420796a/info.json
  blockchains/ethereum/assets/0x8167D3B1024cB51A2DD1B4d889ddf7023420796a/logo.png
  blockchains/smartchain/assets/0xfB4D42BEd5618fb1a377DDB64EB56B92a6d117f2/info.json
  blockchains/smartchain/assets/0xfB4D42BEd5618fb1a377DDB64EB56B92a6d117f2/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#17484 update GMT token info and logo
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
Labels: Payment Status: Paid

#17472 Add AirNFT Token (POLYGON)
  blockchains/polygon/assets/0xBCD287ca1C614Ecd8c5Ca95bFf3c13c392192df5/info.json
  blockchains/polygon/assets/0xBCD287ca1C614Ecd8c5Ca95bFf3c13c392192df5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17480 kava: validators: add asteroid staking.
  blockchains/kava/validators/assets/kavavaloper1maa34q0gfmw44tayr6r287z9ngrucaw770qu34/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid

#17438 Add Stream (BEP20)
  blockchains/smartchain/assets/0xC598275452fA319d75ee5f176FD3B8384925b425/info.json
  blockchains/smartchain/assets/0xC598275452fA319d75ee5f176FD3B8384925b425/logo.png
Labels: Payment Status: Paid

#17502 Add AgeOfGods (BEP20)
  blockchains/smartchain/assets/0x40C8225329Bd3e28A043B029E0D07a5344d2C27C/info.json
  blockchains/smartchain/assets/0x40C8225329Bd3e28A043B029E0D07a5344d2C27C/logo.png
Labels: Payment Status: Paid

#17367 add KAVA BUSD
  blockchains/kava/assets/c459_tbusd/info.json
  blockchains/kava/assets/c459_tbusd/logo.png
Labels: Payment Status: Paid

#17533 Update libs
  go.mod
  go.sum
  internal/processor/fixers.go
  internal/processor/updaters_auto.go
  internal/processor/validators.go
Labels: Payment Status: Requested

#17534 Add ElonGoat (BEP20)
  blockchains/smartchain/assets/0x2cA25319E2E63719F87221D8bF3646F8F5dE5DED/info.json
  blockchains/smartchain/assets/0x2cA25319E2E63719F87221D8bF3646F8F5dE5DED/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17547 Add Hoppy logo and info in Trust Wallet
  blockchains/smartchain/assets/0x984811e6f2695192add6f88615dF637bf52a5Cae/info.json
  blockchains/smartchain/assets/0x984811e6f2695192add6f88615dF637bf52a5Cae/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17571 Add METAVERSE FACE (BEP20)
  blockchains/smartchain/assets/0x6Ad0F087501Eee603AeDa0407c52864bc7f83322/info.json
  blockchains/smartchain/assets/0x6Ad0F087501Eee603AeDa0407c52864bc7f83322/logo.png
Labels: Payment Status: Paid

#17593 Add NOSHIT (BEP20)
  blockchains/smartchain/assets/0x53F042f3e809d2DcC9492dE2DbF05d1DA0EF5fbb/info.json
  blockchains/smartchain/assets/0x53F042f3e809d2DcC9492dE2DbF05d1DA0EF5fbb/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17572 Update Thoreum V2 logo
  blockchains/smartchain/assets/0xF2A92BC1Cf798fF4De14502a9C6FdA58865e8D5d/info.json
  blockchains/smartchain/assets/0xF2A92BC1Cf798fF4De14502a9C6FdA58865e8D5d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17608 Add top FANTOM tokens
  blockchains/fantom/assets/0x1E4F97b9f9F913c46F1632781732927B9019C68b/info.json
  blockchains/fantom/assets/0x1E4F97b9f9F913c46F1632781732927B9019C68b/logo.png
  blockchains/fantom/assets/0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83/info.json
  blockchains/fantom/assets/0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83/logo.png
  blockchains/fantom/assets/0x29b0Da86e484E1C0029B56e817912d778aC0EC69/info.json
  blockchains/fantom/assets/0x29b0Da86e484E1C0029B56e817912d778aC0EC69/logo.png
  blockchains/fantom/assets/0x468003B688943977e6130F4F68F23aad939a1040/info.json
  blockchains/fantom/assets/0x468003B688943977e6130F4F68F23aad939a1040/logo.png
  blockchains/fantom/assets/0x4cdF39285D7Ca8eB3f090fDA0C069ba5F4145B37/info.json
  blockchains/fantom/assets/0x4cdF39285D7Ca8eB3f090fDA0C069ba5F4145B37/logo.png
  blockchains/fantom/assets/0x56ee926bD8c72B2d5fa1aF4d9E4Cbb515a1E3Adc/info.json
  blockchains/fantom/assets/0x56ee926bD8c72B2d5fa1aF4d9E4Cbb515a1E3Adc/logo.png
  blockchains/fantom/assets/0x658b0c7613e890EE50B8C4BC6A3f41ef411208aD/info.json
  blockchains/fantom/assets/0x658b0c7613e890EE50B8C4BC6A3f41ef411208aD/logo.png
  blockchains/fantom/assets/0x69c744D3444202d35a2783929a0F930f2FBB05ad/info.json
  blockchains/fantom/assets/0x69c744D3444202d35a2783929a0F930f2FBB05ad/logo.png
  blockchains/fantom/assets/0x6a07A792ab2965C72a5B8088d3a069A7aC3a993B/info.json
  blockchains/fantom/assets/0x6a07A792ab2965C72a5B8088d3a069A7aC3a993B/logo.png
  blockchains/fantom/assets/0x7d016eec9c25232b01F23EF992D98ca97fc2AF5a/info.json
  blockchains/fantom/assets/0x7d016eec9c25232b01F23EF992D98ca97fc2AF5a/logo.png
  blockchains/fantom/assets/0x82f0B8B456c1A451378467398982d4834b6829c1/info.json
  blockchains/fantom/assets/0x82f0B8B456c1A451378467398982d4834b6829c1/logo.png
  blockchains/fantom/assets/0xae75A438b2E0cB8Bb01Ec1E1e376De11D44477CC/info.json
  blockchains/fantom/assets/0xae75A438b2E0cB8Bb01Ec1E1e376De11D44477CC/logo.png
  blockchains/fantom/assets/0xb3654dc3D10Ea7645f8319668E8F54d2574FBdC8/info.json
  blockchains/fantom/assets/0xb3654dc3D10Ea7645f8319668E8F54d2574FBdC8/logo.png
  blockchains/fantom/assets/0xdc301622e621166BD8E82f2cA0A26c13Ad0BE355/info.json
  blockchains/fantom/assets/0xdc301622e621166BD8E82f2cA0A26c13Ad0BE355/logo.png
  blockchains/fantom/assets/0xe1146b9AC456fCbB60644c36Fd3F868A9072fc6E/info.json
  blockchains/fantom/assets/0xe1146b9AC456fCbB60644c36Fd3F868A9072fc6E/logo.png
Labels: Payment Status: Paid

#17603 Add Mouse Haunt Token (BEP20)
  blockchains/smartchain/assets/0x5Cb2C3Ed882E37DA610f9eF5b0FA25514d7bc85B/info.json
  blockchains/smartchain/assets/0x5Cb2C3Ed882E37DA610f9eF5b0FA25514d7bc85B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17596 Add CheersLand (BEP20)
  blockchains/smartchain/assets/0xbBBcB350C64Fe974e5C42A55c7070644191823f3/info.json
  blockchains/smartchain/assets/0xbBBcB350C64Fe974e5C42A55c7070644191823f3/logo.png
Labels: Payment Status: Paid

#17617 Add Santos FC Fan Token (BEP20)
  blockchains/smartchain/assets/0xA64455a4553C9034236734FadDAddbb64aCE4Cc7/info.json
  blockchains/smartchain/assets/0xA64455a4553C9034236734FadDAddbb64aCE4Cc7/logo.png
Labels: Payment Status: Requested

#17619 Add FC Porto Fan Token (BEP20)
  blockchains/smartchain/assets/0x49f2145d6366099e13B10FbF80646C0F377eE7f6/info.json
  blockchains/smartchain/assets/0x49f2145d6366099e13B10FbF80646C0F377eE7f6/logo.png
Labels: Payment Status: Requested

#17627 Add Flag Network (BEP20)
  blockchains/smartchain/assets/0xa5496935A247fA81B1462E553ad139d2FD0af795/info.json
  blockchains/smartchain/assets/0xa5496935A247fA81B1462E553ad139d2FD0af795/logo.png
Labels: Payment Status: Paid

#17651 Add BUDG info.json and logo
  blockchains/smartchain/assets/0x446320C9FfA57030ca977A1f90F8049DF4004647/info.json
  blockchains/smartchain/assets/0x446320C9FfA57030ca977A1f90F8049DF4004647/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17618 Add Inflation Hedging Coin (BEP20)
  blockchains/smartchain/assets/0x86a53fcd199212FEa44FA7e16EB1f28812be911D/info.json
  blockchains/smartchain/assets/0x86a53fcd199212FEa44FA7e16EB1f28812be911D/logo.png
Labels: Payment Status: Paid

#17671 Add TankBattle Token (BEP20)
  blockchains/smartchain/assets/0x59F6B2435Cd1421f409907aD2D9F811849ca555f/info.json
  blockchains/smartchain/assets/0x59F6B2435Cd1421f409907aD2D9F811849ca555f/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17686 Add SolChicks (SPL)
  blockchains/solana/assets/cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2/info.json
  blockchains/solana/assets/cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2/logo.png
Labels: Payment Status: Paid

#17436 add blk info and logo
  blockchains/smartchain/assets/0xc0E6AD13BD58413Ed308729b688d601243E1CF77/info.json
  blockchains/smartchain/assets/0xc0E6AD13BD58413Ed308729b688d601243E1CF77/logo.png
Labels: Payment Status: Paid

#17693 add RiseHero Token, fee has paid in PR 17691
  blockchains/smartchain/assets/0xa3d80275E300237a62D3431C26d52f185584cC1B/info.json
  blockchains/smartchain/assets/0xa3d80275E300237a62D3431C26d52f185584cC1B/logo.png
Labels: Payment Status: Paid

#17677 Add Head Football (BEP20)
  blockchains/smartchain/assets/0x7917C830ECA3360e24e09fD422310A734AC9D2c9/info.json
  blockchains/smartchain/assets/0x7917C830ECA3360e24e09fD422310A734AC9D2c9/logo.png
Labels: Payment Status: Paid

#17705 Add DYOR Token (BEP20)
  blockchains/smartchain/assets/0x10051147418C42218986CeDD0aDC266441F8a14f/info.json
  blockchains/smartchain/assets/0x10051147418C42218986CeDD0aDC266441F8a14f/logo.png
Labels: Payment Status: Paid

#17704 Add BTT Token (BEP20 & ERC20)
  blockchains/ethereum/assets/0xC669928185DbCE49d2230CC9B0979BE6DC797957/info.json
  blockchains/ethereum/assets/0xC669928185DbCE49d2230CC9B0979BE6DC797957/logo.png
  blockchains/smartchain/assets/0x352Cb5E19b12FC216548a2677bD0fce83BaE434B/info.json
  blockchains/smartchain/assets/0x352Cb5E19b12FC216548a2677bD0fce83BaE434B/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17743 Update TOKEN SDC refer #17487
  blockchains/smartchain/assets/0xAE4cA3272792d8499575AEFacdc299F0cBdc9270/info.json
  blockchains/smartchain/assets/0xAE4cA3272792d8499575AEFacdc299F0cBdc9270/logo.png
Labels: Payment Status: Paid

#17706 Add top10 tokens (OPTIMISM), (ARETH)
  blockchains/arbitrum/assets/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/info.json
  blockchains/arbitrum/assets/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/logo.png
  blockchains/arbitrum/assets/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1/info.json
  blockchains/arbitrum/assets/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1/logo.png
  blockchains/arbitrum/assets/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/info.json
  blockchains/arbitrum/assets/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/logo.png
  blockchains/arbitrum/assets/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9/info.json
  blockchains/arbitrum/assets/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9/logo.png
  blockchains/arbitrum/assets/0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a/info.json
  blockchains/arbitrum/assets/0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a/logo.png
  blockchains/optimism/assets/0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6/info.json
  blockchains/optimism/assets/0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6/logo.png
  blockchains/optimism/assets/0x4200000000000000000000000000000000000006/info.json
  blockchains/optimism/assets/0x4200000000000000000000000000000000000006/logo.png
  blockchains/optimism/assets/0x5029C236320b8f15eF0a657054B84d90bfBEDED3/info.json
  blockchains/optimism/assets/0x5029C236320b8f15eF0a657054B84d90bfBEDED3/logo.png
  blockchains/optimism/assets/0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb/info.json
  blockchains/optimism/assets/0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb/logo.png
  blockchains/optimism/assets/0x61BAADcF22d2565B0F471b291C475db5555e0b76/info.json
  blockchains/optimism/assets/0x61BAADcF22d2565B0F471b291C475db5555e0b76/logo.png
  blockchains/optimism/assets/0x9Bcef72be871e61ED4fBbc7630889beE758eb81D/info.json
  blockchains/optimism/assets/0x9Bcef72be871e61ED4fBbc7630889beE758eb81D/logo.png
  blockchains/optimism/assets/0x9e1028F5F1D5eDE59748FFceE5532509976840E0/info.json
  blockchains/optimism/assets/0x9e1028F5F1D5eDE59748FFceE5532509976840E0/logo.png
  blockchains/optimism/assets/0xF98dCd95217E15E05d8638da4c91125E59590B07/info.json
  blockchains/optimism/assets/0xF98dCd95217E15E05d8638da4c91125E59590B07/logo.png
  blockchains/optimism/assets/0xffD27b572246f35c992EfB28DD8cB730b93Ed301/info.json
  blockchains/optimism/assets/0xffD27b572246f35c992EfB28DD8cB730b93Ed301/logo.png
Labels: Payment Status: Paid

#17707 Add LucidLandsGem (BEP20)
  blockchains/smartchain/assets/0xE4C293Eadbb9d72d68a680F1A66979726992c396/info.json
  blockchains/smartchain/assets/0xE4C293Eadbb9d72d68a680F1A66979726992c396/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17512 Add top Elrond assets (ESDT / SFT) - part 1
  blockchains/elrond/assets/EGLDMEX-0be9e5/info.json
  blockchains/elrond/assets/EGLDMEX-0be9e5/logo.png
  blockchains/elrond/assets/EGLDMEXF-5bcc57/info.json
  blockchains/elrond/assets/EGLDMEXF-5bcc57/logo.png
  blockchains/elrond/assets/EGLDUSDC-594e5e/info.json
  blockchains/elrond/assets/EGLDUSDC-594e5e/logo.png
  blockchains/elrond/assets/EGLDUSDCF-8600f8/info.json
  blockchains/elrond/assets/EGLDUSDCF-8600f8/logo.png
  blockchains/elrond/assets/LKMEX-aab910/info.json
  blockchains/elrond/assets/LKMEX-aab910/logo.png
  blockchains/elrond/assets/MEX-455c57/info.json
  blockchains/elrond/assets/MEX-455c57/logo.png
  blockchains/elrond/assets/MEXFARM-e7af52/info.json
  blockchains/elrond/assets/MEXFARM-e7af52/logo.png
  blockchains/elrond/assets/RIDE-7d18e9/info.json
  blockchains/elrond/assets/RIDE-7d18e9/logo.png
  blockchains/elrond/assets/USDC-c76f1f/info.json
  blockchains/elrond/assets/USDC-c76f1f/logo.png
  blockchains/elrond/assets/WEGLD-bd4d79/info.json
  blockchains/elrond/assets/WEGLD-bd4d79/logo.png
Labels: Payment Status: Paid

#17782 Implement tokenlist/tokenlist-extended duplicate validaton
  blockchains/optimism/assets/0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6/info.json
  blockchains/optimism/assets/0x4200000000000000000000000000000000000006/info.json
  blockchains/optimism/assets/0x5029C236320b8f15eF0a657054B84d90bfBEDED3/info.json
  blockchains/optimism/assets/0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb/info.json
  blockchains/optimism/assets/0x61BAADcF22d2565B0F471b291C475db5555e0b76/info.json
  blockchains/optimism/assets/0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4/info.json
  blockchains/optimism/assets/0x9Bcef72be871e61ED4fBbc7630889beE758eb81D/info.json
  blockchains/optimism/assets/0x9e1028F5F1D5eDE59748FFceE5532509976840E0/info.json
  blockchains/optimism/assets/0xF98dCd95217E15E05d8638da4c91125E59590B07/info.json
  blockchains/optimism/assets/0xffD27b572246f35c992EfB28DD8cB730b93Ed301/info.json
  blockchains/polygon/tokenlist-extended.json
  blockchains/smartchain/tokenlist-extended.json
  go.mod
  go.sum
  internal/processor/fixers.go
  internal/processor/updaters_auto.go
  internal/processor/validators.go
Labels: Payment Status: Requested

#17790 Update go mod
  go.mod
  go.sum
Labels: Payment Status: Requested

#17780 Add JMPT logo and info
  blockchains/smartchain/assets/0x88D7e9B65dC24Cf54f5eDEF929225FC3E1580C25/info.json
  blockchains/smartchain/assets/0x88D7e9B65dC24Cf54f5eDEF929225FC3E1580C25/logo.png
Labels: Payment Status: Paid

#17766 Add LittleBabyDoge (BEP20)
  blockchains/smartchain/assets/0xf67006f8d22edEbd1191f3E728ab9a90289e6C38/info.json
  blockchains/smartchain/assets/0xf67006f8d22edEbd1191f3E728ab9a90289e6C38/logo.png
Labels: Payment Status: Paid
