Repository trustwallet/assets, pull requests merged in 2022-12, with the labels that each got.

#23275 Add HOOK (BEP20)
  blockchains/smartchain/assets/0xa260E12d2B924cb899AE80BB58123ac3fEE1E2F0/info.json
  blockchains/smartchain/assets/0xa260E12d2B924cb899AE80BB58123ac3fEE1E2F0/logo.png
Labels: Payment Status: Paid

#23296 Migration for Dogecola
  blockchains/smartchain/assets/0xe320Df552e78D57E95cF1182B6960746d5016561/info.json
  blockchains/smartchain/assets/0xe320Df552e78D57E95cF1182B6960746d5016561/logo.png
Labels: Payment Status: Paid

#23290 Add: Dogecola V2 new smart contract
  blockchains/smartchain/assets/0x4756cd85Cd07769c2Ce07A73497f208D56D48eC1/info.json
  blockchains/smartchain/assets/0x4756cd85Cd07769c2Ce07A73497f208D56D48eC1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23304 Add REGENT COIN (BEP20)
  blockchains/smartchain/assets/0x4fFa143Ce16A24215e8dF96c0CEF5677a7B91EE4/info.json
  blockchains/smartchain/assets/0x4fFa143Ce16A24215e8dF96c0CEF5677a7B91EE4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23291 Add OwlDAO Token (BEP20)
  blockchains/fantom/assets/0x9564fBfD3B3819D6Fb2DbC88C75E112400bE8F0C/info.json
  blockchains/fantom/assets/0x9564fBfD3B3819D6Fb2DbC88C75E112400bE8F0C/logo.png
  blockchains/polygon/assets/0x9085B4d52c3e0B8B6F9AF6213E85A433c7D76f19/info.json
  blockchains/polygon/assets/0x9085B4d52c3e0B8B6F9AF6213E85A433c7D76f19/logo.png
  blockchains/smartchain/assets/0x9085B4d52c3e0B8B6F9AF6213E85A433c7D76f19/info.json
  blockchains/smartchain/assets/0x9085B4d52c3e0B8B6F9AF6213E85A433c7D76f19/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23269 Kin logo and info change
  blockchains/solana/assets/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/info.json
  blockchains/solana/assets/kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6/logo.png
Labels: Payment Status: Requested

#23314 Add chainlist dapps
  dapps/chainlist.org.png
Labels: Payment Status: Paid

#23325 Add HFT (BEP20)
  blockchains/smartchain/assets/0x44Ec807ce2F4a6F2737A92e985f318d035883e47/info.json
  blockchains/smartchain/assets/0x44Ec807ce2F4a6F2737A92e985f318d035883e47/logo.png
Labels: Payment Status: Paid

#23326 Add JOE (AVALANCHE)
  blockchains/avalanchec/assets/0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd/info.json
  blockchains/avalanchec/assets/0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd/logo.png
Labels: Payment Status: Paid

#23306 Add Football World Community (BEP20)
  blockchains/smartchain/assets/0x6D3a160B86eDcD46D8F9bBa25c2F88ccCADe19fc/info.json
  blockchains/smartchain/assets/0x6D3a160B86eDcD46D8F9bBa25c2F88ccCADe19fc/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23342 Migration for shibnobi
  blockchains/ethereum/assets/0xab167E816E4d76089119900e941BEfdfA37d6b32/info.json
  blockchains/ethereum/assets/0xab167E816E4d76089119900e941BEfdfA37d6b32/logo.png
Labels: Payment Status: Paid

#23343 Migration for shinja (ERC20)
  blockchains/ethereum/assets/0x7DAc25b1A665e1c70F25F1fC37d88C99274984ed/info.json
  blockchains/ethereum/assets/0x7DAc25b1A665e1c70F25F1fC37d88C99274984ed/logo.png
Labels: Payment Status: Paid

#23340 Add Buddy DAO (BEP20)
  blockchains/smartchain/assets/0x8E062E7f7e95b9b51519a6f47C28F260ab1064e4/info.json
  blockchains/smartchain/assets/0x8E062E7f7e95b9b51519a6f47C28F260ab1064e4/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23356 Add Lenda (BEP20)
  blockchains/smartchain/assets/0x2D7A47908d817dd359f9aBA7FEaA89c92a289c7E/info.json
  blockchains/smartchain/assets/0x2D7A47908d817dd359f9aBA7FEaA89c92a289c7E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23394 Add new tokens from top exchanges
  blockchains/ethereum/assets/0xcAfE001067cDEF266AfB7Eb5A286dCFD277f3dE5/info.json
  blockchains/ethereum/assets/0xcAfE001067cDEF266AfB7Eb5A286dCFD277f3dE5/logo.png
  blockchains/polygon/assets/0x23D29D30e35C5e8D321e1dc9A8a61BFD846D4C5C/info.json
  blockchains/polygon/assets/0x23D29D30e35C5e8D321e1dc9A8a61BFD846D4C5C/logo.png
  blockchains/polygon/assets/0x28C388FB1F4fa9F9eB445f0579666849EE5eeb42/info.json
  blockchains/polygon/assets/0x28C388FB1F4fa9F9eB445f0579666849EE5eeb42/logo.png
  blockchains/polygon/assets/0xB25e20De2F2eBb4CfFD4D16a55C7B395e8a94762/info.json
  blockchains/polygon/assets/0xB25e20De2F2eBb4CfFD4D16a55C7B395e8a94762/logo.png
  blockchains/smartchain/assets/0x07e551E31A793E20dc18494ff6b03095A8F8Ee36/info.json
  blockchains/smartchain/assets/0x07e551E31A793E20dc18494ff6b03095A8F8Ee36/logo.png
  blockchains/smartchain/assets/0x5f588EfAf8eB57e3837486e834fC5a4E07768D98/info.json
  blockchains/smartchain/assets/0x5f588EfAf8eB57e3837486e834fC5a4E07768D98/logo.png
  blockchains/smartchain/assets/0x861f1E1397daD68289e8f6a09a2ebb567f1B895C/info.json
  blockchains/smartchain/assets/0x861f1E1397daD68289e8f6a09a2ebb567f1B895C/logo.png
  blockchains/smartchain/assets/0xBbcF57177D8752B21d080bf30a06CE20aD6333F8/info.json
  blockchains/smartchain/assets/0xBbcF57177D8752B21d080bf30a06CE20aD6333F8/logo.png
  blockchains/smartchain/assets/0xccE7162344Dc758e4715079C8Abc981dc72273B9/info.json
  blockchains/smartchain/assets/0xccE7162344Dc758e4715079C8Abc981dc72273B9/logo.png
Labels: Payment Status: Paid

#23411 include latest go-primitives
  .gitignore
  go.mod
  go.sum
Labels: Payment Status: Requested

#23422 Add USDC (RONIN), CAKE (APTOS)
  blockchains/aptos/assets/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6%3A%3Aoft%3A%3ACakeOFT/info.json
  blockchains/aptos/assets/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6%3A%3Aoft%3A%3ACakeOFT/logo.png
  blockchains/ronin/assets/0x0B7007c13325C48911F73A2daD5FA5dCBf808aDc/info.json
  blockchains/ronin/assets/0x0B7007c13325C48911F73A2daD5FA5dCBf808aDc/logo.png
Labels: Payment Status: Paid

#23464 Add new Terra Classic validator: lunc_nymph
  blockchains/terra/validators/assets/terravaloper1qrgwphlf9c64m5ys6pzsvy055ud03e4kr7sq8u/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23480 Add Atomic Nodes OSMO validator
  blockchains/osmosis/validators/assets/osmovaloper1x2e2pnenh0mmc99cnp7sukngnt8lc4saljavr3/logo.png
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23503 Add top tokens exchanges
  blockchains/ethereum/assets/0x19E98c4921aAb7E3f5FD2aDca36CFb669c63E926/info.json
  blockchains/ethereum/assets/0x19E98c4921aAb7E3f5FD2aDca36CFb669c63E926/logo.png
  blockchains/ethereum/assets/0x23894DC9da6c94ECb439911cAF7d337746575A72/info.json
  blockchains/ethereum/assets/0x23894DC9da6c94ECb439911cAF7d337746575A72/logo.png
  blockchains/ethereum/assets/0x33349B282065b0284d756F0577FB39c158F935e6/info.json
  blockchains/ethereum/assets/0x33349B282065b0284d756F0577FB39c158F935e6/logo.png
  blockchains/ethereum/assets/0x3D382228C54736d831FAC2748F4734D9177c7332/info.json
  blockchains/ethereum/assets/0x3D382228C54736d831FAC2748F4734D9177c7332/logo.png
  blockchains/ethereum/assets/0x62959c699A52eC647622c91e79CE73344e4099f5/info.json
  blockchains/ethereum/assets/0x62959c699A52eC647622c91e79CE73344e4099f5/logo.png
  blockchains/ethereum/assets/0x720CD16b011b987Da3518fbf38c3071d4F0D1495/info.json
  blockchains/ethereum/assets/0x720CD16b011b987Da3518fbf38c3071d4F0D1495/logo.png
  blockchains/ethereum/assets/0x839e71613f9aA06E5701CF6de63E303616B0DDE3/info.json
  blockchains/ethereum/assets/0x839e71613f9aA06E5701CF6de63E303616B0DDE3/logo.png
  blockchains/ethereum/assets/0xc314b0E758D5FF74f63e307A86EbfE183C95767b/info.json
  blockchains/ethereum/assets/0xc314b0E758D5FF74f63e307A86EbfE183C95767b/logo.png
  blockchains/smartchain/assets/0x4620C701e8853Eaa1BF791EfB1d7d4d784734baD/info.json
  blockchains/smartchain/assets/0x4620C701e8853Eaa1BF791EfB1d7d4d784734baD/logo.png
Labels: Payment Status: Paid

#23505 Remove XJOE(AVALANCHE)
  blockchains/avalanchec/assets/0x57319d41F71E81F3c65F2a47CA4e001EbAFd4F33/info.json
  blockchains/avalanchec/assets/0x57319d41F71E81F3c65F2a47CA4e001EbAFd4F33/logo.png
  blockchains/avalanchec/tokenlist.json
Labels: Payment Status: Paid

#23532 Add Legend IV Validator & Update Legend I, II, III Validators.
  blockchains/binance/validators/assets/bva142lu7y78yk23cdeujduy9g8gqxp7xl3wrz4ska/logo.png
  blockchains/binance/validators/assets/bva16usf4rcvk9dyzpe8n82gq4nw9x5emlhhs2fftr/logo.png
  blockchains/binance/validators/assets/bva1we4frydjkyejdzp506gzpljaqpqu5fs0flu60p/logo.png
  blockchains/binance/validators/assets/bva1z0g0cg8dkgczr6r8t6khva3srn5mwj8w5tlu7h/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23473 Add IMPT (ERC20)
  blockchains/ethereum/assets/0x04C17b9D3b29A78F7Bd062a57CF44FC633e71f85/info.json
  blockchains/ethereum/assets/0x04C17b9D3b29A78F7Bd062a57CF44FC633e71f85/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23061 Add Corite (BEP20)
  blockchains/smartchain/assets/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6/info.json
  blockchains/smartchain/assets/0x936B6659Ad0C1b244Ba8Efe639092acae30dc8d6/logo.png
Labels: Payment Status: Paid
