Repository trustwallet/assets, pull requests merged in 2022-08, with the labels that each got.

#21760 Add OKC assets
  blockchains/okc/assets/0x382bB369d343125BfB2117af9c149795C6C65C50/info.json
  blockchains/okc/assets/0x382bB369d343125BfB2117af9c149795C6C65C50/logo.png
  blockchains/okc/assets/0x8F8526dbfd6E38E3D8307702cA8469Bae6C56C15/info.json
  blockchains/okc/assets/0x8F8526dbfd6E38E3D8307702cA8469Bae6C56C15/logo.png
  blockchains/okc/assets/0xc946DAf81b08146B1C7A8Da2A851Ddf2B3EAaf85/info.json
  blockchains/okc/assets/0xc946DAf81b08146B1C7A8Da2A851Ddf2B3EAaf85/logo.png
  blockchains/okc/assets/0xdF54B6c6195EA4d948D03bfD818D365cf175cFC2/info.json
  blockchains/okc/assets/0xdF54B6c6195EA4d948D03bfD818D365cf175cFC2/logo.png
  blockchains/okc/info/info.json
  blockchains/okc/info/logo.png
  blockchains/okc/tokenlist.json
Labels: Payment Status: Requested

#21705 Adding Logo and Description to Fat Cat Killer
  blockchains/smartchain/assets/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726/info.json
  blockchains/smartchain/assets/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726/logo.png
Labels: Status: On Hold, Payment Status: Paid

#21762 Add mail³ logo to Trustwallet
  dapps/app.mail3.me.png
Labels: Payment Status: Paid

#21775 Add METFX Watch-To-Earn (BEP20)
  blockchains/smartchain/assets/0x6266a18F1605DA94e8317232ffa634C74646ac40/info.json
  blockchains/smartchain/assets/0x6266a18F1605DA94e8317232ffa634C74646ac40/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21787 [Internal] Evmos and Native Evmos chains
  blockchains/evmos/info/info.json
  blockchains/evmos/info/logo.png
  blockchains/nativeevmos/info/info.json
Labels: Payment Status: Paid

#21781 Add Overclock Validator
  blockchains/solana/validators/assets/AS3nKBQfKs8fJ8ncyHrdvo4FDT6S8HMRhD75JjCcyr1t/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21794 Correcting logo size, fees already paid in #21705
  blockchains/smartchain/assets/0xE0b1EF69BC4AB4173989C1190f0d77A813f3B726/logo.png
Labels: Payment Status: Paid

#21797 Add Sports 2K75 (BEP20)
  blockchains/smartchain/assets/0x42bfa18f3f7D82BD7240d8Ce5935d51679C5115d/info.json
  blockchains/smartchain/assets/0x42bfa18f3f7D82BD7240d8Ce5935d51679C5115d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21743 Add Crypto Legions Bloodstone (BEP20)
  blockchains/smartchain/assets/0x10cb66ce2969d8c8193707A9dCD559D2243B8b37/info.json
  blockchains/smartchain/assets/0x10cb66ce2969d8c8193707A9dCD559D2243B8b37/logo.png
Labels: Payment Status: Paid

#21812 Add LunaGens (BEP20)
  blockchains/smartchain/assets/0x28B9aed756De31B6b362aA0f23211D13093EBb79/info.json
  blockchains/smartchain/assets/0x28B9aed756De31B6b362aA0f23211D13093EBb79/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21416 Add Libera Logo
  blockchains/smartchain/assets/0x3A806A3315E35b3F5F46111ADb6E2BAF4B14A70D/info.json
  blockchains/smartchain/assets/0x3A806A3315E35b3F5F46111ADb6E2BAF4B14A70D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21838 Add Stakin Validator
  blockchains/nativeevmos/validators/assets/evmosvaloper1sq9ggymzx02vcp7kf6yyar83scfm4r22swu673/logo.png
  blockchains/nativeevmos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21869 Add Muu Inu (BEP20)
  blockchains/smartchain/assets/0xEA5E9F39F4B4Bc2684e49A0E43127F7f6F6be3b8/info.json
  blockchains/smartchain/assets/0xEA5E9F39F4B4Bc2684e49A0E43127F7f6F6be3b8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21889 Add pStake Finance (BEP20)
  blockchains/smartchain/assets/0x4C882ec256823eE773B25b414d36F92ef58a7c0C/info.json
  blockchains/smartchain/assets/0x4C882ec256823eE773B25b414d36F92ef58a7c0C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21881 Add Staked BNB (BEP20)
  blockchains/smartchain/assets/0xc2E9d07F66A89c44062459A47a0D2Dc038E4fb16/info.json
  blockchains/smartchain/assets/0xc2E9d07F66A89c44062459A47a0D2Dc038E4fb16/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21868 Add MIKU (BEP20)
  blockchains/smartchain/assets/0x73419De8E3E26A17e0E6b0436e29dd04A25B061D/info.json
  blockchains/smartchain/assets/0x73419De8E3E26A17e0E6b0436e29dd04A25B061D/logo.png
Labels: Payment Status: Paid

#21880 Add LITE (BEP20)
  blockchains/smartchain/assets/0x4a846D300F793752eE8bd579192C477130C4B369/info.json
  blockchains/smartchain/assets/0x4a846D300F793752eE8bd579192C477130C4B369/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21905 Add BitBurn (BEP20)
  blockchains/smartchain/assets/0x5A5844CAb96A7b8B257Fc606Aa6119c5cBc6D4c4/info.json
  blockchains/smartchain/assets/0x5A5844CAb96A7b8B257Fc606Aa6119c5cBc6D4c4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21964 Migration for GHC (BEP20)
  blockchains/smartchain/assets/0x22dE16487955AE1f842fa0C0bFf6083a7fDEfeDd/info.json
  blockchains/smartchain/assets/0x22dE16487955AE1f842fa0C0bFf6083a7fDEfeDd/logo.png
Labels: Payment Status: Paid

#21963 Add logo to GHC (Migration)
  blockchains/smartchain/assets/0xd10Fe9d371C22416df34340287cd5D9029842Fc3/info.json
  blockchains/smartchain/assets/0xd10Fe9d371C22416df34340287cd5D9029842Fc3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#21971 Add ApeNow dapp logo to TrustWallet
  dapps/apenowpaylater.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#21954 Add MetaBUSDCoin (BEP20)
  blockchains/smartchain/assets/0xF14D3692B0055Db9Ca4c04065165d59B87E763f1/info.json
  blockchains/smartchain/assets/0xF14D3692B0055Db9Ca4c04065165d59B87E763f1/logo.png
Labels: Payment Status: Paid

#21982 Update Stakely validators
  blockchains/cosmos/validators/list.json
  blockchains/nativeevmos/validators/assets/evmosvaloper19fxanpnjlggzuur3m3x0puk5ez7j9lrttexwsw/logo.png
  blockchains/nativeevmos/validators/list.json
  blockchains/osmosis/validators/list.json
  blockchains/polkadot/validators/list.json
  blockchains/solana/validators/assets/BmMVRAVef2qmJ1tJpG3JwRUtnfEiTbvDw9ZeFEi4wE7D/logo.png
  blockchains/solana/validators/list.json
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#21976 https://github.com/trustwallet/assets/pull/21972
  blockchains/smartchain/assets/0x75aFA9915B2210Cd6329E820af0365e932bC1dd5/info.json
  blockchains/smartchain/assets/0x75aFA9915B2210Cd6329E820af0365e932bC1dd5/logo.png
Labels: Payment Status: Paid

#21990 Add JoyStick Games (JOY) (ERC20)
  blockchains/ethereum/assets/0xdb4D1099D53e92593430e33483Db41c63525f55F/info.json
  blockchains/ethereum/assets/0xdb4D1099D53e92593430e33483Db41c63525f55F/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21969 Add Luffy token information to Trustwallet
  blockchains/ethereum/assets/0x7121D00b4fA18F13Da6c2e30d19C04844E6AfDC8/info.json
  blockchains/ethereum/assets/0x7121D00b4fA18F13Da6c2e30d19C04844E6AfDC8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#21941 Add Chihuahua (BEP20)
  blockchains/smartchain/assets/0x2fd6c9B869Dea106730269E13113361b684f843a/info.json
  blockchains/smartchain/assets/0x2fd6c9B869Dea106730269E13113361b684f843a/logo.png
Labels: Payment Status: Paid

#21973 update logo of Peel
  blockchains/smartchain/assets/0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB/info.json
  blockchains/smartchain/assets/0x734548a9e43d2D564600b1B2ed5bE9C2b911c6aB/logo.png
Labels: Payment Status: Paid

#22038 Add Bobcoin (ERC20)
  blockchains/ethereum/assets/0xe803178b48A0e560C2b19F3b3d4e504f79D229ce/info.json
  blockchains/ethereum/assets/0xe803178b48A0e560C2b19F3b3d4e504f79D229ce/logo.png
Labels: Payment Status: Paid

#22025 Added Vault Staking to Evmos validators
  blockchains/nativeevmos/validators/assets/evmosvaloper1k5hcl0cjprzewwvzhz3um589kx8skzlrneuepu/logo.png
  blockchains/nativeevmos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#22041 Add Everscale
  blockchains/everscale/info/info.json
  blockchains/everscale/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22046 Add DRAC Token (BEP20)
  blockchains/smartchain/assets/0x123458C167a371250d325Bd8B1ffF12C8AF692A7/info.json
  blockchains/smartchain/assets/0x123458C167a371250d325Bd8B1ffF12C8AF692A7/logo.png
Labels: Payment Status: Paid

#22040 Add Reflex V2 (BEP20)
  blockchains/smartchain/assets/0x2f499c6DA2C84063BB7e0CB1C478687210cDB615/info.json
  blockchains/smartchain/assets/0x2f499c6DA2C84063BB7e0CB1C478687210cDB615/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22098 fix decimals for KAVA BUSD
  blockchains/kava/assets/busd/info.json
Labels: Payment Status: Paid

#22097 Add SquidGrow (BEP20)
  blockchains/smartchain/assets/0x88479186BAC914E4313389a64881F5ed0153C765/info.json
  blockchains/smartchain/assets/0x88479186BAC914E4313389a64881F5ed0153C765/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22022 Add logo on TWT
  blockchains/smartchain/assets/0x6C46422A0f7dbbAD9BEC3BbBC1189bfAf9794B05/info.json
  blockchains/smartchain/assets/0x6C46422A0f7dbbAD9BEC3BbBC1189bfAf9794B05/logo.png
Labels: Status: On Hold, Payment Status: Paid

#22063 Add Arbitrage Token (BEP20)
  blockchains/smartchain/assets/0x6469b35d2D5FAb6c53F73c7d9aBF537892DdB34a/info.json
  blockchains/smartchain/assets/0x6469b35d2D5FAb6c53F73c7d9aBF537892DdB34a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22096 Add Reflecto (RTO) to Trust Wallet
  blockchains/smartchain/assets/0x5A341DCF49e161CC73591f02e5f8CDE8A29733fb/info.json
  blockchains/smartchain/assets/0x5A341DCF49e161CC73591f02e5f8CDE8A29733fb/logo.png
Labels: Payment Status: Paid

#22116 Add DecentralizedUnited (BEP20)
  blockchains/smartchain/assets/0xCb1DDC8F705e2737685A9C1e6B84A63d04D200e5/info.json
  blockchains/smartchain/assets/0xCb1DDC8F705e2737685A9C1e6B84A63d04D200e5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22117 Add Grove Token (GVR) (ERC20)
  blockchains/ethereum/assets/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e/info.json
  blockchains/ethereum/assets/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e/logo.png
Labels: Payment Status: Paid

#22121 Add Toncoin (ERC20)
  blockchains/ethereum/assets/0x582d872A1B094FC48F5DE31D3B73F2D9bE47def1/info.json
  blockchains/ethereum/assets/0x582d872A1B094FC48F5DE31D3B73F2D9bE47def1/logo.png
Labels: Payment Status: Paid

#22135 Change status for PAYN (TRC20)
  blockchains/tron/assets/TLLo3PU91yKPbwvSbuawvWKCzNX2JHYEE2/info.json
  blockchains/tron/assets/TLLo3PU91yKPbwvSbuawvWKCzNX2JHYEE2/logo.png
Labels: Payment Status: Paid

#22136 Change status for PAYN (TRC20)
  blockchains/tron/assets/TQYuR8FpmhMJK3ZpfoTgERjaZRywqMnFAH/info.json
  blockchains/tron/assets/TQYuR8FpmhMJK3ZpfoTgERjaZRywqMnFAH/logo.png
Labels: Payment Status: Paid

#22179 Change logo for Chainlink (BEP20) (OPTIMISM)
  blockchains/optimism/assets/0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6/logo.png
  blockchains/smartchain/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/logo.png
Labels: Payment Status: Paid

#22185 Add Bobcoin (BEP20)
  blockchains/smartchain/assets/0xCE6bD1833BD077f62B2c1F9a777bB829801d6811/info.json
  blockchains/smartchain/assets/0xCE6bD1833BD077f62B2c1F9a777bB829801d6811/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#22186 Upload logo and info WETUX
  blockchains/smartchain/assets/0x58f0C2fd4B7B0fBaC97c9cC71A5Eb810627734C8/info.json
  blockchains/smartchain/assets/0x58f0C2fd4B7B0fBaC97c9cC71A5Eb810627734C8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#22177 Update logo and name for EverGrow (BEP20)
  blockchains/smartchain/assets/0xC001BBe2B87079294C63EcE98BdD0a88D761434e/info.json
  blockchains/smartchain/assets/0xC001BBe2B87079294C63EcE98BdD0a88D761434e/logo.png
Labels: Payment Status: Paid

#22200 Add IBAT logo and info
  blockchains/smartchain/assets/0x19cd9B8e42d4EF62c3EA124110D5Cfd283CEaC43/info.json
  blockchains/smartchain/assets/0x19cd9B8e42d4EF62c3EA124110D5Cfd283CEaC43/logo.png
Labels: Payment Status: Paid
