Repository trustwallet/assets, pull requests merged in 2022-02, with the labels that each got.

#17791 Add DIFX token to smartchain assets
  blockchains/smartchain/assets/0x697bd938e7E572E787ecd7bC74a31f1814C21264/info.json
  blockchains/smartchain/assets/0x697bd938e7E572E787ecd7bC74a31f1814C21264/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17801 Add SOURCE Token (ERC20) (CELO) - reopening #17680
  blockchains/celo/assets/0x74c0C58B99b68cF16A717279AC2d056A34ba2bFe/info.json
  blockchains/celo/assets/0x74c0C58B99b68cF16A717279AC2d056A34ba2bFe/logo.png
  blockchains/ethereum/assets/0x7118057ff0F4Fd0994fb9d2D94de8231d5cca79E/info.json
  blockchains/ethereum/assets/0x7118057ff0F4Fd0994fb9d2D94de8231d5cca79E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17749 Add HRC20 top 20 tokens
  blockchains/heco/assets/0x09006b66d89e5213Fc173403AACBA30620A91F4e/info.json
  blockchains/heco/assets/0x09006b66d89e5213Fc173403AACBA30620A91F4e/logo.png
  blockchains/heco/assets/0x202b4936fE1a82A4965220860aE46d7d3939Bb25/info.json
  blockchains/heco/assets/0x202b4936fE1a82A4965220860aE46d7d3939Bb25/logo.png
  blockchains/heco/assets/0x22C54cE8321A4015740eE1109D9cBc25815C46E6/info.json
  blockchains/heco/assets/0x22C54cE8321A4015740eE1109D9cBc25815C46E6/logo.png
  blockchains/heco/assets/0x34D75515090902a513F009f4505A750efaaD63b0/info.json
  blockchains/heco/assets/0x34D75515090902a513F009f4505A750efaaD63b0/logo.png
  blockchains/heco/assets/0x3D760a45D0887DFD89A2F5385a236B29Cb46ED2a/info.json
  blockchains/heco/assets/0x3D760a45D0887DFD89A2F5385a236B29Cb46ED2a/logo.png
  blockchains/heco/assets/0x5eE41aB6edd38cDfB9f6B4e6Cf7F75c87E170d98/info.json
  blockchains/heco/assets/0x5eE41aB6edd38cDfB9f6B4e6Cf7F75c87E170d98/logo.png
  blockchains/heco/assets/0x66a79D23E58475D2738179Ca52cd0b41d73f0BEa/info.json
  blockchains/heco/assets/0x66a79D23E58475D2738179Ca52cd0b41d73f0BEa/logo.png
  blockchains/heco/assets/0x70D171d269D964d14aF9617858540061e7bE9EF1/info.json
  blockchains/heco/assets/0x70D171d269D964d14aF9617858540061e7bE9EF1/logo.png
  blockchains/heco/assets/0x9362Bbef4B8313A8Aa9f0c9808B80577Aa26B73B/info.json
  blockchains/heco/assets/0x9362Bbef4B8313A8Aa9f0c9808B80577Aa26B73B/logo.png
  blockchains/heco/assets/0x9e004545c59D359F6B7BFB06a26390b087717b42/info.json
  blockchains/heco/assets/0x9e004545c59D359F6B7BFB06a26390b087717b42/logo.png
  blockchains/heco/assets/0xC7f7a54892B78b5c812c58d9Df8035FcE9F4D445/info.json
  blockchains/heco/assets/0xC7f7a54892B78b5c812c58d9Df8035FcE9F4D445/logo.png
  blockchains/heco/assets/0xfAdD0c7762c59cEBC5248019dBAC652319CEBDbd/info.json
  blockchains/heco/assets/0xfAdD0c7762c59cEBC5248019dBAC652319CEBDbd/logo.png
Labels: Payment Status: Paid

#17808 Add tags heco tag for HRC20
  blockchains/heco/assets/0x09006b66d89e5213Fc173403AACBA30620A91F4e/info.json
  blockchains/heco/assets/0x202b4936fE1a82A4965220860aE46d7d3939Bb25/info.json
  blockchains/heco/assets/0x22C54cE8321A4015740eE1109D9cBc25815C46E6/info.json
  blockchains/heco/assets/0x34D75515090902a513F009f4505A750efaaD63b0/info.json
  blockchains/heco/assets/0x3D760a45D0887DFD89A2F5385a236B29Cb46ED2a/info.json
  blockchains/heco/assets/0x5eE41aB6edd38cDfB9f6B4e6Cf7F75c87E170d98/info.json
  blockchains/heco/assets/0x66a79D23E58475D2738179Ca52cd0b41d73f0BEa/info.json
  blockchains/heco/assets/0x70D171d269D964d14aF9617858540061e7bE9EF1/info.json
  blockchains/heco/assets/0x9362Bbef4B8313A8Aa9f0c9808B80577Aa26B73B/info.json
  blockchains/heco/assets/0x9e004545c59D359F6B7BFB06a26390b087717b42/info.json
  blockchains/heco/assets/0xC7f7a54892B78b5c812c58d9Df8035FcE9F4D445/info.json
  blockchains/heco/assets/0xfAdD0c7762c59cEBC5248019dBAC652319CEBDbd/info.json
Labels: Payment Status: Paid

#17806 Add BXST token INFO to Trust Wallet
  blockchains/smartchain/assets/0xF2E71B054B6b0F3C5513Af505E6c072008ECFaCD/info.json
  blockchains/smartchain/assets/0xF2E71B054B6b0F3C5513Af505E6c072008ECFaCD/logo.png
Labels: Payment Status: Paid

#17792 Add MicroPets (BEP20)
  blockchains/smartchain/assets/0xA77346760341460B42C230ca6D21d4c8E743Fa9c/info.json
  blockchains/smartchain/assets/0xA77346760341460B42C230ca6D21d4c8E743Fa9c/logo.png
Labels: Payment Status: Paid

#17775 Shiba Floki Inu
  blockchains/smartchain/assets/0x4AadaD81487c3fadD9F162b851E6a61b729200cb/info.json
  blockchains/smartchain/assets/0x4AadaD81487c3fadD9F162b851E6a61b729200cb/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17822 Add EverEarn (BEP20)
  blockchains/smartchain/assets/0x47d42E0e864ceFf8C4270F7b6E1f6F91Da45882C/info.json
  blockchains/smartchain/assets/0x47d42E0e864ceFf8C4270F7b6E1f6F91Da45882C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17823 Add Multi-Chain Capital (MCC) (ERC20)
  blockchains/ethereum/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/info.json
  blockchains/ethereum/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/logo.png
Labels: Payment Status: Paid

#17839 fix website for MCC
  blockchains/ethereum/assets/0xC146B7CdBaff065090077151d391f4c96Aa09e0C/info.json
Labels: Payment Status: Paid

#17864 Add tokenlist-extended validation
  internal/file/path.go
  internal/file/types.go
  internal/processor/service.go
  internal/processor/validators.go
Labels: Payment Status: Requested

#17825 Update logo
  blockchains/smartchain/assets/0x4c4da68D45F23E38ec8407272ee4f38F280263c0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17856 Add ASIX Token (BEP20)
  blockchains/smartchain/assets/0xc98a8EC7A07f1b743E86896a52434C4C6A0Dbc42/info.json
  blockchains/smartchain/assets/0xc98a8EC7A07f1b743E86896a52434C4C6A0Dbc42/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17857 kava: validators: add nodesByGirls
  blockchains/kava/validators/assets/kavavaloper1xfyyvg9v66yef6cea5ruw8kaqw5a84kjd86r75/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#17774 Add MetaGear Token (BEP20)
  blockchains/smartchain/assets/0xb4404DaB7C0eC48b428Cf37DeC7fb628bcC41B36/info.json
  blockchains/smartchain/assets/0xb4404DaB7C0eC48b428Cf37DeC7fb628bcC41B36/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#17868 Libero logo updated
  blockchains/smartchain/assets/0x0DFCb45EAE071B3b846E220560Bbcdd958414d78/info.json
  blockchains/smartchain/assets/0x0DFCb45EAE071B3b846E220560Bbcdd958414d78/logo.png
Labels: Payment Status: Paid

#17859 Add KOKO token to smartchain assets
  blockchains/smartchain/assets/0x7320c128e89bA4584Ab02ed1C9c96285b726443C/info.json
  blockchains/smartchain/assets/0x7320c128e89bA4584Ab02ed1C9c96285b726443C/logo.png
Labels: Payment Status: Paid

#17889 Add VCGamers (BEP20)
  blockchains/smartchain/assets/0x1F36FB2D91d9951Cf58aE4c1956C0b77e224F1E9/info.json
  blockchains/smartchain/assets/0x1F36FB2D91d9951Cf58aE4c1956C0b77e224F1E9/logo.png
Labels: Payment Status: Paid

#17908 Add Crypto Inu (BEP20)
  blockchains/smartchain/assets/0xa0CC3A881AEf241d6cB3B7Db3168BD26094560BE/info.json
  blockchains/smartchain/assets/0xa0CC3A881AEf241d6cB3B7Db3168BD26094560BE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17897 Add Puli Inu (BEP20)
  blockchains/smartchain/assets/0xAEf0a177c8c329CBC8508292Bb7E06c00786BBfC/info.json
  blockchains/smartchain/assets/0xAEf0a177c8c329CBC8508292Bb7E06c00786BBfC/logo.png
Labels: Payment Status: Paid

#17931 Add Alchemy(ACH) (BEP20)
  blockchains/smartchain/assets/0xBc7d6B50616989655AfD682fb42743507003056D/info.json
  blockchains/smartchain/assets/0xBc7d6B50616989655AfD682fb42743507003056D/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17917 DEXTF token: new logo
  blockchains/ethereum/assets/0x5F64Ab1544D28732F0A24F4713c2C8ec0dA089f0/info.json
  blockchains/ethereum/assets/0x5F64Ab1544D28732F0A24F4713c2C8ec0dA089f0/logo.png
Labels: Payment Status: Requested

#17950 Add: RTT (BEP20)
  blockchains/smartchain/assets/0x8F046a2457a8F1618cAe4706Fa57Bf790e2532a6/info.json
  blockchains/smartchain/assets/0x8F046a2457a8F1618cAe4706Fa57Bf790e2532a6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#17926 Add SquidGameToken (BEP20)
  blockchains/smartchain/assets/0x440Fc7DA66e34e01af5201BdF5815739B0Ae743f/info.json
  blockchains/smartchain/assets/0x440Fc7DA66e34e01af5201BdF5815739B0Ae743f/logo.png
Labels: Payment Status: Paid

#17984 Transfer file package to assets-go-libs
  go.mod
  go.sum
  internal/file/cache.go
  internal/file/path.go
  internal/file/service.go
  internal/file/types.go
  internal/manager/manager.go
  internal/processor/fixers.go
  internal/processor/model.go
  internal/processor/service.go
  internal/processor/validators.go
  internal/service/service.go
Labels: Payment Status: Requested

#17959 Add: RTT (ERC20)
  blockchains/ethereum/assets/0x8F046a2457a8F1618cAe4706Fa57Bf790e2532a6/info.json
  blockchains/ethereum/assets/0x8F046a2457a8F1618cAe4706Fa57Bf790e2532a6/logo.png
Labels: Payment Status: Paid

#17988 Add DOGEFOOD (BEP20)
  blockchains/smartchain/assets/0x1bEc41a36356D5574Aeb068B599Ab7e48dD008b8/info.json
  blockchains/smartchain/assets/0x1bEc41a36356D5574Aeb068B599Ab7e48dD008b8/logo.png
Labels: Payment Status: Paid

#17964 adding SIDUS
  blockchains/ethereum/assets/0x549020a9Cb845220D66d3E9c6D9F9eF61C981102/info.json
  blockchains/ethereum/assets/0x549020a9Cb845220D66d3E9c6D9F9eF61C981102/logo.png
Labels: Payment Status: Paid

#17965 Add LinkSync (BEP20)
  blockchains/smartchain/assets/0xF6a22B0593df74F218027A2d8b7953c9b4542AA1/info.json
  blockchains/smartchain/assets/0xF6a22B0593df74F218027A2d8b7953c9b4542AA1/logo.png
Labels: Payment Status: Paid

#17985 Add XDEFI (ERC20)
  blockchains/ethereum/assets/0x72B886d09C117654aB7dA13A14d603001dE0B777/info.json
  blockchains/ethereum/assets/0x72B886d09C117654aB7dA13A14d603001dE0B777/logo.png
Labels: Payment Status: Paid

#17978 Add Torum (BEP20)
  blockchains/smartchain/assets/0xCd1fAFf6e578Fa5cAC469d2418C95671bA1a62Fe/info.json
  blockchains/smartchain/assets/0xCd1fAFf6e578Fa5cAC469d2418C95671bA1a62Fe/logo.png
Labels: Payment Status: Paid

#17989 add Gather BEP20 address
  blockchains/smartchain/assets/0xeb986DA994E4a118d5956b02d8b7c3C7CE373674/info.json
  blockchains/smartchain/assets/0xeb986DA994E4a118d5956b02d8b7c3C7CE373674/logo.png
Labels: Payment Status: Paid

#18036 Add Shintama (SHINTAMA) (ERC20)
  blockchains/ethereum/assets/0x7e794eD35788b698AE60cefC98eE48015C4876dA/info.json
  blockchains/ethereum/assets/0x7e794eD35788b698AE60cefC98eE48015C4876dA/logo.png
Labels: Payment Status: Paid

#18044 change name for Shintama
  blockchains/ethereum/assets/0x7e794eD35788b698AE60cefC98eE48015C4876dA/info.json
Labels: Payment Status: Paid

#17944 Add MAST
  blockchains/smartchain/assets/0xB31FD05CAF496CEf34C945667E90dd89C20E0D09/info.json
  blockchains/smartchain/assets/0xB31FD05CAF496CEf34C945667E90dd89C20E0D09/logo.png
Labels: Payment Status: Paid

#18000 Add Wrapped Flow (ERC20)
  blockchains/ethereum/assets/0x5c147e74D63B1D31AA3Fd78Eb229B65161983B2b/info.json
  blockchains/ethereum/assets/0x5c147e74D63B1D31AA3Fd78Eb229B65161983B2b/logo.png
Labels: Payment Status: Requested

#18061 Add Dinoland Metaverse (BEP20)
  blockchains/smartchain/assets/0x6B9481FB5465ef9Ab9347b332058D894aB09B2f6/info.json
  blockchains/smartchain/assets/0x6B9481FB5465ef9Ab9347b332058D894aB09B2f6/logo.png
Labels: Payment Status: Paid

#18058 Add ETHEKing (BEP20)
  blockchains/smartchain/assets/0x33efbC79BbF863dB11b4A1BF6570FFB6Bf41d0d2/info.json
  blockchains/smartchain/assets/0x33efbC79BbF863dB11b4A1BF6570FFB6Bf41d0d2/logo.png
Labels: Payment Status: Paid

#18037 Add Petmoon (BEP20)
  blockchains/smartchain/assets/0x97012db0142825526239580CAeAce634C082bb34/info.json
  blockchains/smartchain/assets/0x97012db0142825526239580CAeAce634C082bb34/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18045 Add Rise of Defenders Token (BEP20)
  blockchains/smartchain/assets/0x92dA433dA84d58DFe2aade1943349e491Cbd6820/info.json
  blockchains/smartchain/assets/0x92dA433dA84d58DFe2aade1943349e491Cbd6820/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18053 Add Luxurious Pro Network Token (ERC20)
  blockchains/ethereum/assets/0x6a4C76874e686A7d080D173987A35A9c48905583/info.json
  blockchains/ethereum/assets/0x6a4C76874e686A7d080D173987A35A9c48905583/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18066 Add UBXS Token (BEP20)
  blockchains/smartchain/assets/0x4f1960E29b2cA581a38c5c474e123f420F8092db/info.json
  blockchains/smartchain/assets/0x4f1960E29b2cA581a38c5c474e123f420F8092db/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18068 Add ERTHA Token (BEP20)
  blockchains/smartchain/assets/0x62823659d09F9F9D2222058878f89437425eB261/info.json
  blockchains/smartchain/assets/0x62823659d09F9F9D2222058878f89437425eB261/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18125 Add Chihiro Inu Info and Logo
  blockchains/ethereum/assets/0x35156b404C3f9bdaf45ab65Ba315419bcDe3775c/info.json
  blockchains/ethereum/assets/0x35156b404C3f9bdaf45ab65Ba315419bcDe3775c/logo.png
Labels: Payment Status: Paid

#18129 Add Meta Ruffy (BEP20)
  blockchains/smartchain/assets/0x2456BBAD80BfAD346AecEa45fA38C81a6963132D/info.json
  blockchains/smartchain/assets/0x2456BBAD80BfAD346AecEa45fA38C81a6963132D/logo.png
Labels: Payment Status: Paid

#18146 Add AETHERIUS TOKEN (BEP20)
  blockchains/smartchain/assets/0x5A3B6f18Dc79D50ab208af2fCd61D10BF7e4896F/info.json
  blockchains/smartchain/assets/0x5A3B6f18Dc79D50ab208af2fCd61D10BF7e4896F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18156 Add logo and update information
  blockchains/smartchain/assets/0xCA1aCAB14e85F30996aC83c64fF93Ded7586977C/info.json
  blockchains/smartchain/assets/0xCA1aCAB14e85F30996aC83c64fF93Ded7586977C/logo.png
Labels: Payment Status: Paid

#18142 Add Value Finance (BEP20)
  blockchains/smartchain/assets/0x14E8BCd053e68A22f239b9e9bEaD87932465D245/info.json
  blockchains/smartchain/assets/0x14E8BCd053e68A22f239b9e9bEaD87932465D245/logo.png
Labels: Payment Status: Paid

#18198 Add cREAL (CELO)
  blockchains/celo/assets/0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787/info.json
  blockchains/celo/assets/0xe8537a3d056DA446677B9E9d6c5dB704EaAb4787/logo.png
Labels: Payment Status: Paid

#18209 Add CoW Protocol Virtual Token (vCOW) (ERC20)
  blockchains/ethereum/assets/0xD057B63f5E69CF1B929b356b579Cba08D7688048/info.json
  blockchains/ethereum/assets/0xD057B63f5E69CF1B929b356b579Cba08D7688048/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18219 Add logo and info
  blockchains/smartchain/assets/0x3215f7D921549Bb4a8FD2C93D88021B2902e30d0/info.json
  blockchains/smartchain/assets/0x3215f7D921549Bb4a8FD2C93D88021B2902e30d0/logo.png
Labels: Payment Status: Paid

#18200 Add STA TOKEN (BEP20)
  blockchains/smartchain/assets/0x4D1E90aB966ae26c778b2f9f365aA40abB13f53C/info.json
  blockchains/smartchain/assets/0x4D1E90aB966ae26c778b2f9f365aA40abB13f53C/logo.png
Labels: Payment Status: Paid

#18253 Add Zada (BEP20)
  blockchains/smartchain/assets/0xfCaDD830fF2D6Cf3AD1681E1e8FC5DDCe9d59E74/info.json
  blockchains/smartchain/assets/0xfCaDD830fF2D6Cf3AD1681E1e8FC5DDCe9d59E74/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18267 Change name and logo for BNB (BEP20) (BEP2)
  blockchains/binance/info/info.json
  blockchains/binance/tokenlist.json
  blockchains/smartchain/info/info.json
  blockchains/smartchain/info/logo.png
Labels: Payment Status: Paid

#18226 Add CZUSD (BEP20)
  blockchains/smartchain/assets/0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70/info.json
  blockchains/smartchain/assets/0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70/logo.png
Labels: Payment Status: Paid

#18237 Add FINO DAO token and description
  blockchains/smartchain/assets/0x6C9AE5d6746ee1B6bD03310079AA11d8EC409212/info.json
  blockchains/smartchain/assets/0x6C9AE5d6746ee1B6bD03310079AA11d8EC409212/logo.png
Labels: Payment Status: Paid

#18288 Add ICN Logo and info for TrustWallet
  blockchains/smartchain/assets/0x4F7413B6ac872D971684A26825AF43870864579C/info.json
  blockchains/smartchain/assets/0x4F7413B6ac872D971684A26825AF43870864579C/logo.png
Labels: Payment Status: Paid

#18275 Add BB Coin (BEP20)
  blockchains/smartchain/assets/0xC1CD1fc18fE1Ec87A24F2858cAC493CcA86632c6/info.json
  blockchains/smartchain/assets/0xC1CD1fc18fE1Ec87A24F2858cAC493CcA86632c6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18296 Add DogeFather (BEP20)
  blockchains/smartchain/assets/0x15E2BFF3AB5dcF1F7b5b854636939F3649ce3cf8/info.json
  blockchains/smartchain/assets/0x15E2BFF3AB5dcF1F7b5b854636939F3649ce3cf8/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18312 Add Gem Exchange and Trading (BEP20)
  blockchains/ethereum/assets/0x4674672BcDdDA2ea5300F5207E1158185c944bc0/info.json
  blockchains/smartchain/assets/0x3107C0A1126268CA303f8d99c712392fA596e6D7/info.json
  blockchains/smartchain/assets/0x3107C0A1126268CA303f8d99c712392fA596e6D7/logo.png
Labels: Payment Status: Paid

#18339 Add Coinerr (BEP20)
  blockchains/smartchain/assets/0x8fE8df37335EDB6E9F41F6baF550d2A973F48f21/info.json
  blockchains/smartchain/assets/0x8fE8df37335EDB6E9F41F6baF550d2A973F48f21/logo.png
Labels: Payment Status: Paid

#18338 Add Step (BEP20)
  blockchains/smartchain/assets/0x465707181ACba42Ed01268A33f0507e320a154bD/info.json
  blockchains/smartchain/assets/0x465707181ACba42Ed01268A33f0507e320a154bD/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#18323 Adding logo.png and info.json for XTblock Token
  blockchains/smartchain/assets/0x70B6C6A555507EE4ac91C15E5c80b7dc8FF3b489/info.json
  blockchains/smartchain/assets/0x70B6C6A555507EE4ac91C15E5c80b7dc8FF3b489/logo.png
Labels: Payment Status: Paid

#18297 Add LOA Token (BEP20)
  blockchains/smartchain/assets/0x94b69263FCA20119Ae817b6f783Fc0F13B02ad50/info.json
  blockchains/smartchain/assets/0x94b69263FCA20119Ae817b6f783Fc0F13B02ad50/logo.png
Labels: Payment Status: Paid

#18308 Add CryptoTanks (BEP20)
  blockchains/smartchain/assets/0x4444A19C8bb86E9BDbC023709A363bbCE91aF33E/info.json
  blockchains/smartchain/assets/0x4444A19C8bb86E9BDbC023709A363bbCE91aF33E/logo.png
Labels: Payment Status: Paid

#18332 Add ERA7 logo and info，Paid at #18313
  blockchains/smartchain/assets/0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9/info.json
  blockchains/smartchain/assets/0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9/logo.png
Labels: Payment Status: Paid

#18336 Add Infinity Rocket Token (BEP20)
  blockchains/smartchain/assets/0xCBE5BcA571628894A38836b0baE833ff012f71D8/info.json
  blockchains/smartchain/assets/0xCBE5BcA571628894A38836b0baE833ff012f71D8/logo.png
Labels: Payment Status: Paid

#18344 Add Digichain Coin (BEP20)
  blockchains/smartchain/assets/0x4732A86106064577933552FCea993D30BEC950a5/info.json
  blockchains/smartchain/assets/0x4732A86106064577933552FCea993D30BEC950a5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18358 Add MetaPlanet (BEP20)
  blockchains/smartchain/assets/0xBa007b6170C602C08545ff97395677408688D3a2/info.json
  blockchains/smartchain/assets/0xBa007b6170C602C08545ff97395677408688D3a2/logo.png
Labels: Payment Status: Paid

#18381 Add sea
  blockchains/smartchain/assets/0x26193C7fa4354AE49eC53eA2cEBC513dc39A10aa/info.json
  blockchains/smartchain/assets/0x26193C7fa4354AE49eC53eA2cEBC513dc39A10aa/logo.png
Labels: Payment Status: Paid

#18388 Add UZYTH (BEP20)
  blockchains/smartchain/assets/0x0Df044b7f0aadfEaB21bC134fE525A19484Ac133/info.json
  blockchains/smartchain/assets/0x0Df044b7f0aadfEaB21bC134fE525A19484Ac133/logo.png
Labels: Payment Status: Paid

#18216 Add Alpine F1 Team Fan Token (BEP20)
  blockchains/smartchain/assets/0x287880Ea252b52b63Cc5f40a2d3E5A44aa665a76/info.json
  blockchains/smartchain/assets/0x287880Ea252b52b63Cc5f40a2d3E5A44aa665a76/logo.png
Labels: Payment Status: Requested

#18395 Add ASPO World (BEP20)
  blockchains/smartchain/assets/0x1a9b49E9f075c37Fe5f86C916bac9DEb33556D7E/info.json
  blockchains/smartchain/assets/0x1a9b49E9f075c37Fe5f86C916bac9DEb33556D7E/logo.png
Labels: Payment Status: Paid

#18311 Add AutoCrypto (BEP20)
  blockchains/smartchain/assets/0x8Ea2f890CB86DFb0E376137451c6fD982AFefc15/info.json
  blockchains/smartchain/assets/0x8Ea2f890CB86DFb0E376137451c6fD982AFefc15/logo.png
Labels: Payment Status: Paid

#18302 Add ShibaDoge (ERC20)
  blockchains/ethereum/assets/0x6ADb2E268de2aA1aBF6578E4a8119b960E02928F/info.json
  blockchains/ethereum/assets/0x6ADb2E268de2aA1aBF6578E4a8119b960E02928F/logo.png
Labels: Payment Status: Paid

#18427 Add KODI COIN (BEP20)
  blockchains/smartchain/assets/0xbA5eAB68a7203C9FF72E07b708991F07f55eF40E/info.json
  blockchains/smartchain/assets/0xbA5eAB68a7203C9FF72E07b708991F07f55eF40E/logo.png
Labels: Payment Status: Paid

#18428 update audit NBG
  blockchains/smartchain/assets/0x6cC76132A84e2095c1F4f2EA71881dAEf8a75D5e/info.json
  blockchains/smartchain/assets/0x6cC76132A84e2095c1F4f2EA71881dAEf8a75D5e/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#18386 Add Singularity SGLY Coin (BEP20)
  blockchains/smartchain/assets/0x5f50411CDE3eEC27b0eaC21691b4e500c69a5a2e/info.json
  blockchains/smartchain/assets/0x5f50411CDE3eEC27b0eaC21691b4e500c69a5a2e/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#18484 add stakepile logo
  blockchains/kava/validators/assets/kavavaloper1q8srckh50n0hygw8ntylkvrtfzgexvf364yule/logo.png
  blockchains/kava/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper14syzusqsh8gp7evd0gcqxjjywljgdtdurn79r3/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/polkadot/validators/assets/124X3VPduasSodAjS6MPd5nEqM8SUdKN5taMUUPtkWqF1fVf/logo.png
  blockchains/polkadot/validators/list.json
Labels: Payment Status: Paid

#18492 Updated the better logo
  blockchains/smartchain/assets/0x6C9AE5d6746ee1B6bD03310079AA11d8EC409212/logo.png
Labels: Payment Status: Paid

#18498 Add WEB3 Doge (BEP20)
  blockchains/smartchain/assets/0xf45de5A6d02c4a6E050B90Add33ebf0A34D017e0/info.json
  blockchains/smartchain/assets/0xf45de5A6d02c4a6E050B90Add33ebf0A34D017e0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18509 update info
  blockchains/smartchain/assets/0xd9dE2B1973E57Dc9DBA90c35d6Cd940ae4A3CBe1/info.json
  blockchains/smartchain/assets/0xd9dE2B1973E57Dc9DBA90c35d6Cd940ae4A3CBe1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#18503 Add NBT (BEP20)
  blockchains/smartchain/assets/0x1D3437E570e93581Bd94b2fd8Fbf202d4a65654A/info.json
  blockchains/smartchain/assets/0x1D3437E570e93581Bd94b2fd8Fbf202d4a65654A/logo.png
Labels: Payment Status: Requested

#18511 Mirgation for Santa Floki v2 (BEP20)
  blockchains/smartchain/assets/0x14940169E2Db1595CDD3CACd30DECC5bbB4d9f19/info.json
  blockchains/smartchain/assets/0x14940169E2Db1595CDD3CACd30DECC5bbB4d9f19/logo.png
  blockchains/smartchain/assets/0xb8a5e028f833F08A29564ded368b4CaCB4e18FF5/info.json
  blockchains/smartchain/assets/0xb8a5e028f833F08A29564ded368b4CaCB4e18FF5/logo.png
Labels: Payment Status: Paid

#18527 Add FqSwap (BEP20)
  blockchains/smartchain/assets/0x9075055C3Ee590Ee0d7a2e1EF4376A851369E8E0/info.json
  blockchains/smartchain/assets/0x9075055C3Ee590Ee0d7a2e1EF4376A851369E8E0/logo.png
Labels: Payment Status: Paid

#18501 Add MetaDoge V2 (BEP20)
  blockchains/smartchain/assets/0x9953170dcAac530AD7D6949c7295207c6ec5669D/info.json
  blockchains/smartchain/assets/0x9953170dcAac530AD7D6949c7295207c6ec5669D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
