Repository trustwallet/assets, pull requests merged in 2022-05, with the labels that each got.

#20197 Add API Inu (BEP20)
  blockchains/smartchain/assets/0xA1943Bc4a417ffd2E9e11A97383fa3f9548291c3/info.json
  blockchains/smartchain/assets/0xA1943Bc4a417ffd2E9e11A97383fa3f9548291c3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#20204 Add Nexm logo and info (BEP20)
  blockchains/smartchain/assets/0xfa37E513E6cd506c4694b992825a8B614C035581/info.json
  blockchains/smartchain/assets/0xfa37E513E6cd506c4694b992825a8B614C035581/logo.png
Labels: Payment Status: Paid

#20194 Add Vulkania (BEP20)
  blockchains/smartchain/assets/0x797Bb0BeeA437D2762A755ea911C0046C1284568/info.json
  blockchains/smartchain/assets/0x797Bb0BeeA437D2762A755ea911C0046C1284568/logo.png
Labels: Status: On Hold, Payment Status: Paid

#20196 Add USDD Token (TRON & BEP20 & ERC20)
  blockchains/ethereum/assets/0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6/info.json
  blockchains/ethereum/assets/0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6/logo.png
  blockchains/smartchain/assets/0xd17479997F34dd9156Deef8F95A52D81D265be9c/info.json
  blockchains/smartchain/assets/0xd17479997F34dd9156Deef8F95A52D81D265be9c/logo.png
  blockchains/tron/assets/TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn/info.json
  blockchains/tron/assets/TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn/logo.png
Labels: Payment Status: Requested

#20209 Fix Stellar USDC decimals
  blockchains/stellar/assets/USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN/info.json
Labels: Payment Status: Requested

#20207 Add StepD (BEP20)
  blockchains/smartchain/assets/0x2582d7Afc1bF4496bcb87b6C2a72D24DB279dD0e/info.json
  blockchains/smartchain/assets/0x2582d7Afc1bF4496bcb87b6C2a72D24DB279dD0e/logo.png
Labels: Payment Status: Paid

#20219 Add FireToken (FIRE) (BEP20)
  blockchains/smartchain/assets/0x0f0Dd5E2c0e0c4A41F8908D73D36B8D142F6745a/info.json
  blockchains/smartchain/assets/0x0f0Dd5E2c0e0c4A41F8908D73D36B8D142F6745a/logo.png
Labels: Payment Status: Paid

#20246 Update BSC social links.
  blockchains/smartchain/info/info.json
Labels: Payment Status: Requested

#20221 Add Petoverse (BEP20)
  blockchains/smartchain/assets/0xe327eD2037F133cdA9F56171b68B6b7b4Dfa6175/info.json
  blockchains/smartchain/assets/0xe327eD2037F133cdA9F56171b68B6b7b4Dfa6175/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20258 Add unrekt logo
  dapps/app.unrekt.net.png
Labels: Payment Status: Requested

#20222 Add Chumbi Valley Token (CHMB)
  blockchains/smartchain/assets/0x5492Ef6aEebA1A3896357359eF039a8B11621b45/info.json
  blockchains/smartchain/assets/0x5492Ef6aEebA1A3896357359eF039a8B11621b45/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#20265 Fix Aurora logo
  blockchains/aurora/info/logo.png
Labels: Payment Status: Paid

#20279 [Internal] Add BNX token for swap on smartchain
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Requested

#20280 [Internal] UST (Wormhole) name and website was updated
  blockchains/ethereum/assets/0xa693B19d2931d498c5B318dF961919BB4aee87a5/info.json
  blockchains/polygon/assets/0xE6469Ba6D2fD6130788E0eA9C0a0515900563b59/info.json
  blockchains/smartchain/assets/0x3d4350cD54aeF9f9b2C29435e0fa809957B3F30a/info.json
Labels: Payment Status: Requested

#20281 [Internal] Build a new list of solana validators
  blockchains/solana/validators/assets/9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF/logo.png
  blockchains/solana/validators/assets/CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu/logo.png
  blockchains/solana/validators/assets/Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE/logo.png
  blockchains/solana/validators/assets/DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a/logo.png
  blockchains/solana/validators/assets/beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Requested

#20294 [Internal] Update Validators List
  blockchains/solana/validators/list.json
Labels: Payment Status: Requested

#20312 Change decimal for USD (ARBITRUM)
  blockchains/arbitrum/assets/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8/info.json
  blockchains/arbitrum/tokenlist-extended.json
Labels: Payment Status: Paid

#20306 Add BEX (BEP20) token
  blockchains/smartchain/assets/0x3eE08275b513f3085231Ccc85de4C386FCc1f18b/info.json
  blockchains/smartchain/assets/0x3eE08275b513f3085231Ccc85de4C386FCc1f18b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20373 Add OtterSync
  blockchains/kava/validators/assets/kavavaloper1fwru9at8hsu7hmhu0zypdn3863xvdcg80nm5dv/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#20372 update Solana validator list with Cogent Crypto
  blockchains/solana/validators/assets/CogentC52e7kktFfWHwsqSmr8LiS1yAtfqhHcftCPcBJ/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#20346 Add ENERGY COIN (BEP20)
  blockchains/smartchain/assets/0x8a505D5Cb3Db9fcf404c0A72aF3dF8Be4eFB707c/info.json
  blockchains/smartchain/assets/0x8a505D5Cb3Db9fcf404c0A72aF3dF8Be4eFB707c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20436 Migration for ASIX (BEP20)
  blockchains/smartchain/assets/0xc98a8EC7A07f1b743E86896a52434C4C6A0Dbc42/info.json
  blockchains/smartchain/assets/0xc98a8EC7A07f1b743E86896a52434C4C6A0Dbc42/logo.png
Labels: Payment Status: Paid

#20223 Add ASIX+ (BEP20)
  blockchains/smartchain/assets/0x2bF4BE7C4520C41d012EB09a034179E03b898534/info.json
  blockchains/smartchain/assets/0x2bF4BE7C4520C41d012EB09a034179E03b898534/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20473 Add Sunflower solana validator
  blockchains/solana/validators/assets/EPWrFd8jJ4SLA1YtcZcRAsAMxmnikSVqbumerCq5yV6z/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#20485 Add APX Token (BEP20)
  blockchains/smartchain/assets/0x78F5d389F5CDCcFc41594aBaB4B0Ed02F31398b3/info.json
  blockchains/smartchain/assets/0x78F5d389F5CDCcFc41594aBaB4B0Ed02F31398b3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20449 Quint in Trustwallet
  blockchains/smartchain/assets/0x64619f611248256F7F4b72fE83872F89d5d60d64/info.json
  blockchains/smartchain/assets/0x64619f611248256F7F4b72fE83872F89d5d60d64/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#20519 [Internal] Add KuCoin Community Chain Assets
  blockchains/kcc/assets/0x0039f574eE5cC39bdD162E9A88e3EB1f111bAF48/info.json
  blockchains/kcc/assets/0x0039f574eE5cC39bdD162E9A88e3EB1f111bAF48/logo.png
  blockchains/kcc/assets/0x2cA48b4eeA5A731c2B54e7C3944DBDB87c0CFB6F/info.json
  blockchains/kcc/assets/0x2cA48b4eeA5A731c2B54e7C3944DBDB87c0CFB6F/logo.png
  blockchains/kcc/assets/0x4446Fc4eb47f2f6586f9fAAb68B3498F86C07521/info.json
  blockchains/kcc/assets/0x4446Fc4eb47f2f6586f9fAAb68B3498F86C07521/logo.png
  blockchains/kcc/assets/0x980a5AfEf3D17aD98635F6C5aebCBAedEd3c3430/info.json
  blockchains/kcc/assets/0x980a5AfEf3D17aD98635F6C5aebCBAedEd3c3430/logo.png
Labels: Payment Status: Requested

#20520 [Internal] Add WannaSwap token on Aurora network
  blockchains/aurora/assets/0x7faA64Faf54750a2E3eE621166635fEAF406Ab22/info.json
  blockchains/aurora/assets/0x7faA64Faf54750a2E3eE621166635fEAF406Ab22/logo.png
Labels: Payment Status: Requested

#20522 Add PulseDogecoin (ERC20)
  blockchains/ethereum/assets/0x34F0915a5f15a66Eba86F6a58bE1A471FB7836A7/info.json
  blockchains/ethereum/assets/0x34F0915a5f15a66Eba86F6a58bE1A471FB7836A7/logo.png
Labels: Payment Status: Paid

#20527 Add TendaCoin (BEP20)
  blockchains/smartchain/assets/0x07a3554899D97a087Bda931Dd5224B3B7435E568/info.json
  blockchains/smartchain/assets/0x07a3554899D97a087Bda931Dd5224B3B7435E568/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#20540 Add Elrond ESDT ITHEUM-df6f26
  blockchains/elrond/assets/ITHEUM-df6f26/info.json
  blockchains/elrond/assets/ITHEUM-df6f26/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#20528 Add PlatON logo and info
  blockchains/platon/info/info.json
  blockchains/platon/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#20598 Add gallar logo
  dapps/galler.io.png
Labels: Payment Status: Requested

#20600 Rename gallar logo
  dapps/www.galler.io.png
Labels: Payment Status: Requested

#20616 Migration for ERR (BEP20 -> POLYGON)
  blockchains/polygon/assets/0xFB32513135e3267995268E3099d2B6114d20B6eD/info.json
  blockchains/polygon/assets/0xFB32513135e3267995268E3099d2B6114d20B6eD/logo.png
Labels: Payment Status: Paid

#20620 Add Openlive NFT (BEP20)
  blockchains/smartchain/assets/0x36C7B164F85D6F775cD128966D5819c7d36FEfF3/info.json
  blockchains/smartchain/assets/0x36C7B164F85D6F775cD128966D5819c7d36FEfF3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20611 Add CCN (BEP20)
  blockchains/smartchain/assets/0x721F40adC793e951EdF2ECE86376e7a103211252/info.json
  blockchains/smartchain/assets/0x721F40adC793e951EdF2ECE86376e7a103211252/logo.png
Labels: Status: On Hold, Payment Status: Paid

#20643 Add Marshall Rogan Inu (ERC20)
  blockchains/ethereum/assets/0x0913dDAE242839f8995c0375493f9a1A3Bddc977/info.json
  blockchains/ethereum/assets/0x0913dDAE242839f8995c0375493f9a1A3Bddc977/logo.png
Labels: Payment Status: Paid

#20634 Fix update-auto command & run it
  .github/assets.config.yaml
  .github/workflows/check.yml
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
  .github/workflows/pr-ci.yml
  .golangci.yml
  blockchains/binance/tokenlist.json
  go.mod
  go.sum
  internal/processor/updaters_auto.go
  internal/processor/updaters_auto_test.go
Labels: Payment Status: Requested

#20658 Add Aeterna Logo
  blockchains/smartchain/assets/0xe75BF67Df2388183d9b7714231996C937d4a855A/info.json
  blockchains/smartchain/assets/0xe75BF67Df2388183d9b7714231996C937d4a855A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20653 Add StarShip (BEP20)
  blockchains/smartchain/assets/0x52419258E3fa44DEAc7E670eaDD4c892B480A805/info.json
  blockchains/smartchain/assets/0x52419258E3fa44DEAc7E670eaDD4c892B480A805/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20612 Add X Doge (BEP20)
  blockchains/smartchain/assets/0xA2086F4a3955A520A1743D68CDbcf064Ee1746Cd/info.json
  blockchains/smartchain/assets/0xA2086F4a3955A520A1743D68CDbcf064Ee1746Cd/logo.png
Labels: Payment Status: Paid

#20614 Add Son of Doge (BEP20)
  blockchains/smartchain/assets/0xF078580015Cdfaa849BDAd8B38e72F5803C316c4/info.json
  blockchains/smartchain/assets/0xF078580015Cdfaa849BDAd8B38e72F5803C316c4/logo.png
Labels: Payment Status: Paid, Under Review

#20700 Add Banana Task Force Ape (BTFA) (ERC20)
  blockchains/ethereum/assets/0xC631bE100F6Cf9A7012C23De5a6ccb990EAFC133/info.json
  blockchains/ethereum/assets/0xC631bE100F6Cf9A7012C23De5a6ccb990EAFC133/logo.png
Labels: Payment Status: Paid

#20710 Add DELOT (BEP20) token
  blockchains/smartchain/assets/0x3e24BBb2c9a0f2fAEcFDBDCa20BBa6F35b73C4CB/info.json
  blockchains/smartchain/assets/0x3e24BBb2c9a0f2fAEcFDBDCa20BBa6F35b73C4CB/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#20746 Add NUM Token (BEP20)
  blockchains/smartchain/assets/0xeCEB87cF00DCBf2D4E2880223743Ff087a995aD9/info.json
  blockchains/smartchain/assets/0xeCEB87cF00DCBf2D4E2880223743Ff087a995aD9/logo.png
Labels: Payment Status: Paid

#20673 Add WEDEX TOKEN V2 (BEP20)
  blockchains/smartchain/assets/0x09BB6042A19BB3A6981e9a47EC0f006dBd28a8d1/info.json
  blockchains/smartchain/assets/0x09BB6042A19BB3A6981e9a47EC0f006dBd28a8d1/logo.png
Labels: Payment Status: Paid

#20764 Add Marvin Inu (BEP20)
  blockchains/smartchain/assets/0x71aB195498b6dC1656aBb4D9233f83Ae5F19495B/info.json
  blockchains/smartchain/assets/0x71aB195498b6dC1656aBb4D9233f83Ae5F19495B/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#20774 Migration for pinkpanda
  blockchains/smartchain/assets/0x631E1e455019c359b939fE214EDC761d36bF6aD6/info.json
  blockchains/smartchain/assets/0x631E1e455019c359b939fE214EDC761d36bF6aD6/logo.png
Labels: Payment Status: Paid

#20759 Uploading info and logo for $BAM—migrating from $PINKPANDA
  blockchains/smartchain/assets/0x1382A2Fd1b9F5607D956b68491babA00e21bE472/info.json
  blockchains/smartchain/assets/0x1382A2Fd1b9F5607D956b68491babA00e21bE472/logo.png
Labels: Payment Status: Paid

#20776 Migration for kiba inu
  blockchains/ethereum/assets/0x005D1123878Fc55fbd56b54C73963b234a64af3c/info.json
  blockchains/ethereum/assets/0x005D1123878Fc55fbd56b54C73963b234a64af3c/logo.png
  blockchains/ethereum/assets/0x4B2C54b80B77580dc02A0f6734d3BAD733F50900/info.json
  blockchains/ethereum/assets/0x4B2C54b80B77580dc02A0f6734d3BAD733F50900/logo.png
Labels: Payment Status: Paid

#20777 Migration for Kiba (BEP20)
  blockchains/smartchain/assets/0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341/info.json
  blockchains/smartchain/assets/0x31d3778A7Ac0d98c4aAA347D8b6EaF7977448341/logo.png
Labels: Payment Status: Paid

#20772 Add Kiba Inu (KIBA) (BEP20)
  blockchains/smartchain/assets/0xC3afDe95B6Eb9ba8553cDAea6645D45fB3a7FAF5/info.json
  blockchains/smartchain/assets/0xC3afDe95B6Eb9ba8553cDAea6645D45fB3a7FAF5/logo.png
Labels: Payment Status: Paid
