Repository trustwallet/assets, pull requests merged in 2023-10, with the labels that each got.

#26500 Add Graph Token (PoS)
  blockchains/polygon/assets/0x5fe2B58c013d7601147DcdD68C143A77499f5531/info.json
  blockchains/polygon/assets/0x5fe2B58c013d7601147DcdD68C143A77499f5531/logo.png
Labels: Payment Status: Requested

#26410 Add Northern Lottery (XSMB) (TRC21)
  blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/info.json
  blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#26502 Add Kingstaker validator for Crypto.org Chain
  blockchains/cryptoorg/validators/assets/crocncl1398htakkpn2esmp3czjs548ujj5278xmxw2tyj/logo.png
  blockchains/cryptoorg/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26463 Add Wall Street Memes (WSM) (ERC20)
  blockchains/ethereum/assets/0xB62E45c3Df611dcE236A6Ddc7A493d79F9DFadEf/info.json
  blockchains/ethereum/assets/0xB62E45c3Df611dcE236A6Ddc7A493d79F9DFadEf/logo.png
Labels: Status: More Info / Change Requested, Status: On Hold, Payment Status: Paid, Payment Status: Requested

#26564 Add PLANET token logo and Info
  blockchains/smartchain/assets/0xCa6d678e74f553f0E59cccC03ae644a3c2c5EE7d/info.json
  blockchains/smartchain/assets/0xCa6d678e74f553f0E59cccC03ae644a3c2c5EE7d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26582 [Internal] Migrate FreewayToken FWT ERC20
  blockchains/ethereum/assets/0x20e7125677311Fca903A8897042b9983f22Ea295/info.json
  blockchains/ethereum/assets/0x20e7125677311Fca903A8897042b9983f22Ea295/logo.png
  blockchains/ethereum/assets/0xf151980E7A781481709e8195744bF2399FB3Cba4/info.json
  blockchains/smartchain/assets/0xCa6d678e74f553f0E59cccC03ae644a3c2c5EE7d/info.json
Labels: Payment Status: Requested

#26608 [Internal] Trust logo updated
  blockchains/binance/validators/assets/bva1c6aqe9ndzcn2nsan963z43xg6kgrvzynl97785/logo.png
  blockchains/cardano/validators/assets/pool1gaztx97t53k47fr7282d70tje8323vvzx8pshgts30t9krw62tm/logo.png
  blockchains/kava/validators/assets/kavavaloper1t787gjxtyswnncltluwaefg0dfgvwrm87d3g9d/logo.png
  blockchains/nativeinjective/validators/assets/injvaloper1dyntafvjynns5zyltwgyktej0y5zt84y3npkt4/logo.png
  blockchains/near/validators/assets/trust-nodes.poolv1.near/logo.png
  blockchains/solana/validators/assets/FiijvR2ibXEHaFqB127CxrL3vSj19K2Kx1jf2RbK4BWS/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26572 Add Darik (BEP20)
  blockchains/smartchain/assets/0x595a67D180BAE10314384265d56927C8ff073426/info.json
  blockchains/smartchain/assets/0x595a67D180BAE10314384265d56927C8ff073426/logo.png
Labels: Payment Status: Paid

#26686 Updated Logo, name & info
  blockchains/ethereum/assets/0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1/info.json
  blockchains/ethereum/assets/0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26697 [Internal] Node added
  blockchains/tron/validators/assets/TFqEaQBVpJmc6y6sbvXgzu9zsXL1pTKw47/logo.png
  blockchains/tron/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested
