Repository trustwallet/assets, pull requests merged in 2023-11, with the labels that each got.

#26699 Add TXGPRO (BEP20)
  blockchains/smartchain/assets/0x6739e0572A24bE7864B466f79844C4f3B7d6f857/info.json
  blockchains/smartchain/assets/0x6739e0572A24bE7864B466f79844C4f3B7d6f857/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26690 Add Internet Computer
  blockchains/internetcomputer/info/info.json
  blockchains/internetcomputer/info/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26714 Add ATOR Protocol (ERC20)
  blockchains/ethereum/assets/0x0F7B3F5a8FeD821c5eb60049538a548dB2D479ce/info.json
  blockchains/ethereum/assets/0x0F7B3F5a8FeD821c5eb60049538a548dB2D479ce/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26712 Add Crypto For Betting (TRC21)
  blockchains/tomochain/assets/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532/info.json
  blockchains/tomochain/assets/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26738 Update Memecoin logo and links
  blockchains/ethereum/assets/0xb131f4A55907B10d1F0A50d8ab8FA09EC342cd74/info.json
  blockchains/ethereum/assets/0xb131f4A55907B10d1F0A50d8ab8FA09EC342cd74/logo.png
Labels: Payment Status: Requested

#26732 Add VizslaSwap (BEP20)
  blockchains/smartchain/assets/0xaDAaE082237cB1772c9e079dB95c117E6Dd0C5aF/info.json
  blockchains/smartchain/assets/0xaDAaE082237cB1772c9e079dB95c117E6Dd0C5aF/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26753 Disable old MKR token
  blockchains/ethereum/assets/0xC66eA802717bFb9833400264Dd12c2bCeAa34a6d/info.json
Labels: Payment Status: Requested

#26754 Update Internet Computer Path
  blockchains/internet_computer/info/info.json
  blockchains/internet_computer/info/logo.png
Labels: Payment Status: Requested

#26748 Add First Digital USD (ERC20)
  blockchains/ethereum/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/info.json
  blockchains/ethereum/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26749 Add First Digital USD (BEP20)
  blockchains/smartchain/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/info.json
  blockchains/smartchain/assets/0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26739 Add IguVerse (BEP20)
  blockchains/smartchain/assets/0x201bC9F242f74C47Bbd898a5DC99cDCD81A21943/info.json
  blockchains/smartchain/assets/0x201bC9F242f74C47Bbd898a5DC99cDCD81A21943/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25814 Abandon RUNE assets on BNB/ETH chains
  blockchains/binance/assets/RUNE-B1A/info.json
  blockchains/ethereum/assets/0x3155BA85D5F96b2d030a4966AF206230e46849cb/info.json
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid, Payment Status: Requested

#26707 Add TokenFi (TOKEN) on ETH and BNB chain
  blockchains/ethereum/assets/0x4507cEf57C46789eF8d1a19EA45f4216bae2B528/info.json
  blockchains/ethereum/assets/0x4507cEf57C46789eF8d1a19EA45f4216bae2B528/logo.png
  blockchains/smartchain/assets/0x4507cEf57C46789eF8d1a19EA45f4216bae2B528/info.json
  blockchains/smartchain/assets/0x4507cEf57C46789eF8d1a19EA45f4216bae2B528/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26790 [Internal] Atom node
  blockchains/binance/validators/list.json
  blockchains/cardano/validators/list.json
  blockchains/cosmos/validators/assets/cosmosvaloper1k6e7l0lz497l8njqjxpd3g4wlkdfwe93uqf03k/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/list.json
  blockchains/nativeinjective/validators/list.json
  blockchains/near/validators/list.json
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#26771 Bump Golang version to 1.19
  go.mod
  go.sum
Labels: Payment Status: Requested

#26789 Add DinoLFG (DINO) (ERC20)
  blockchains/ethereum/assets/0x49642110B712C1FD7261Bc074105E9E44676c68F/info.json
  blockchains/ethereum/assets/0x49642110B712C1FD7261Bc074105E9E44676c68F/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26794 Update FOUR token info
  blockchains/ethereum/assets/0x4730fB1463A6F1F44AEB45F6c5c422427f37F4D0/info.json
  blockchains/ethereum/assets/0x4730fB1463A6F1F44AEB45F6c5c422427f37F4D0/logo.png
  blockchains/polygon/assets/0x48cBc913dE09317dF2365e6827Df50dA083701D5/info.json
  blockchains/polygon/assets/0x48cBc913dE09317dF2365e6827Df50dA083701D5/logo.png
  blockchains/smartchain/assets/0xd882739Fca9CBAE00F3821c4c65189E2D7e26147/info.json
  blockchains/smartchain/assets/0xd882739Fca9CBAE00F3821c4c65189E2D7e26147/logo.png
  blockchains/solana/assets/DAtU322C23YpoZyWBm8szk12QyqHa9rUQe1EYXzbm1JE/info.json
  blockchains/solana/assets/DAtU322C23YpoZyWBm8szk12QyqHa9rUQe1EYXzbm1JE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26769 Add xAI (BEP20)
  blockchains/smartchain/assets/0x8Ea43e15b1a616a19903F6A87498F7dCa1efae0f/info.json
  blockchains/smartchain/assets/0x8Ea43e15b1a616a19903F6A87498F7dCa1efae0f/logo.png
Labels: Payment Status: Paid

#26818 [internal] osmosis, evmos validators
  blockchains/evmos/validators/assets/evmosvaloper1k875gxzhegt59na74z5a8ejhen2thhvejk4r2e/logo.png
  blockchains/evmos/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1f7jtv9sd3g9jay64zrydfqh7l3eqdzgs289m8u/logo.png
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid

#26820 Validator from evmos moved to nativeevmos
  blockchains/evmos/validators/assets/evmosvaloper1f6m9d94lkenw9fy5wmytatt76l849kx6ugdz70/logo.png
  blockchains/evmos/validators/assets/evmosvaloper1shvcjzhcxau6qtlz9w82a646ecwp4hq7ayqt0w/logo.png
  blockchains/evmos/validators/list.json
  blockchains/info.json
  blockchains/logo.png
  blockchains/nativeevmos/validators/list.json
  blockchains/osmosis/validators/assets/evmosvaloper1k875gxzhegt59na74z5a8ejhen2thhvejk4r2e/logo.png
  blockchains/osmosis/validators/assets/evmosvaloper1mh2lvhy0clzlx645yet4340ra0p5hh2zjyptj9/logo.png
Labels: Payment Status: Paid

#26826 Add DOGAMI (POLYGON)
  blockchains/polygon/assets/0x2F3E306d9F02ee8e8850F9040404918d0b345207/info.json
  blockchains/polygon/assets/0x2F3E306d9F02ee8e8850F9040404918d0b345207/logo.png
Labels: Payment Status: Requested

#26841 Update descriptions
  blockchains/comdex/validators/assets/comdexvaloper1g6zz4d7j6fvxy24nsqkjrcxqrt7hwp6p6hws7c/logo.png
  blockchains/comdex/validators/list.json
  blockchains/cosmos/validators/list.json
  blockchains/crescent/validators/assets/crevaloper126nxgyruw03fyr3rmxg76squcy08pjtm9zkl5d/logo.png
  blockchains/crescent/validators/list.json
  blockchains/iris/validators/assets/iva1aj6frfd5g0a5d88j6mjpvy0ql5afd5crt90uqx/logo.png
  blockchains/iris/validators/list.json
  blockchains/kava/validators/list.json
  blockchains/nativeevmos/validators/list.json
  blockchains/persistence/validators/assets/persistencevaloper1xykmyvzk88qrlqh3wuw4jckewleyygupsumyj5/logo.png
  blockchains/persistence/validators/list.json
  blockchains/solana/validators/list.json
  blockchains/terra/validators/list.json
  blockchains/terrav2/validators/assets/terravaloper1mgpgp53tynj4djmckxdjhufa7q8lqqjuwnrlqm/logo.png
  blockchains/terrav2/validators/list.json
  blockchains/tia/validators/assets/celestiavaloper1dlsl4u42ycahzjfwc6td6upgsup9tt7cz8vqm4/logo.png
  blockchains/tia/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26850 Add Legend VII and VIII Validator Logos.
  blockchains/binance/validators/assets/bva1346977fnwf790657wxl0w3396ddsw7rygh9hgg/logo.png
  blockchains/binance/validators/assets/bva1nsm7askda5z8r3lfvu6l26acm0rycqh3w87lag/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26567 Add WinsToken (POLYGON)
  blockchains/polygon/assets/0x1A49E59aB7101D6a66D6B2Fa6d09932079cC80EC/info.json
  blockchains/polygon/assets/0x1A49E59aB7101D6a66D6B2Fa6d09932079cC80EC/logo.png
Labels: Status: On Hold, Payment Status: Paid
