Repository trustwallet/assets, pull requests merged in 2023-06, with the labels that each got.

#25263 Add Renq Finance (RENQ) (ERC20)
  blockchains/ethereum/assets/0xff8C479134A18918059493243943150776cF8CF2/info.json
  blockchains/ethereum/assets/0xff8C479134A18918059493243943150776cF8CF2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25299 Add INRx (BEP20)
  blockchains/smartchain/assets/0xcD6970d5211EfDF2516A4fc73163db7bA812B212/info.json
  blockchains/smartchain/assets/0xcD6970d5211EfDF2516A4fc73163db7bA812B212/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25268 Add Pepecoin (BEP20)
  blockchains/smartchain/assets/0x43B9cE0394d9AFfc97501359646A410A48c21a11/info.json
  blockchains/smartchain/assets/0x43B9cE0394d9AFfc97501359646A410A48c21a11/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25342 Add SEEDx (BEP20)
  blockchains/smartchain/assets/0x0cBfDea4F45A486Cc7dB53CB6e37b312A137C605/info.json
  blockchains/smartchain/assets/0x0cBfDea4F45A486Cc7dB53CB6e37b312A137C605/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25344 Add WATER RABBIT (BEP20)
  blockchains/smartchain/assets/0x57Bfe2aF99AeB7a3de3bc0c42c22353742bfD20D/info.json
  blockchains/smartchain/assets/0x57Bfe2aF99AeB7a3de3bc0c42c22353742bfD20D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25343 Add Coinhub (BEP20)
  blockchains/ethereum/assets/0xf68D4d917592f3a62417aCE42592F15296cc33A0/info.json
  blockchains/ethereum/assets/0xf68D4d917592f3a62417aCE42592F15296cc33A0/logo.png
  blockchains/smartchain/assets/0xf68D4d917592f3a62417aCE42592F15296cc33A0/info.json
  blockchains/smartchain/assets/0xf68D4d917592f3a62417aCE42592F15296cc33A0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested, Under Review

#25388 Added Tortuga Finance
  blockchains/aptos/validators/assets/0x8f396e4246b2ba87b51c0739ef5ea4f26515a98375308c31ac2ec1e42142a57f/logo.png
  blockchains/aptos/validators/list.json
Labels: Payment Status: Requested

#25333 Add Jesus Coin (BEP20)
  blockchains/smartchain/assets/0x6120ba0B3538E40aA7aAc32558E5dd0737B7ac90/info.json
  blockchains/smartchain/assets/0x6120ba0B3538E40aA7aAc32558E5dd0737B7ac90/logo.png
Labels: Payment Status: Paid, Under Review

#25337 Add Pink BNB (BEP20)
  blockchains/smartchain/assets/0xf5BDe7Eb378661F04C841B22bA057326B0370153/info.json
  blockchains/smartchain/assets/0xf5BDe7Eb378661F04C841B22bA057326B0370153/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25415 Add YO EXCHANGE (BEP20)
  blockchains/smartchain/assets/0x26C98b27aB51Af12C616d2D2Eb99909B6BDE6dde/info.json
  blockchains/smartchain/assets/0x26C98b27aB51Af12C616d2D2Eb99909B6BDE6dde/logo.png
Labels: Payment Status: Paid

#25413 BEP20 PAYS
  blockchains/smartchain/assets/0xdb5642fC3Ffd7a8BdC2C837197736c54B120872d/info.json
  blockchains/smartchain/assets/0xdb5642fC3Ffd7a8BdC2C837197736c54B120872d/logo.png
Labels: Payment Status: Paid

#25423 NodesByGirls: Update Kava & Osmosis, Add Akash
  blockchains/akash/validators/assets/akashvaloper105nkdqgkj3hpgqss0elcec2t72ujg09w5mzhm8/logo.png
  blockchains/akash/validators/list.json
  blockchains/kava/validators/list.json
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#25452 Add ELF wallet (BEP20)
  blockchains/smartchain/assets/0x56D594D76b37BE83C54aBF8a4747D60CE58D32C2/info.json
  blockchains/smartchain/assets/0x56D594D76b37BE83C54aBF8a4747D60CE58D32C2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25411 Update to $BEN Coin Info and Logo
  blockchains/ethereum/assets/0x9bf1D7D63dD7a4ce167CF4866388226EEefa702E/info.json
  blockchains/ethereum/assets/0x9bf1D7D63dD7a4ce167CF4866388226EEefa702E/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25527 Add Jasan Wellness (BEP20)
  blockchains/smartchain/assets/0xaB785054251DB0fc44538F5DeeBE7507B748b692/info.json
  blockchains/smartchain/assets/0xaB785054251DB0fc44538F5DeeBE7507B748b692/logo.png
Labels: Payment Status: Paid

#25534 Update validator in3s.com
  blockchains/cosmos/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1rcp29q3hpd246n6qak7jluqep4v006cd8q9sme/logo.png
  blockchains/osmosis/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#25518 Add Minati (BEP20)
  blockchains/smartchain/assets/0xe4e11e02AA14c7f24DB749421986EAEc1369e8C9/info.json
  blockchains/smartchain/assets/0xe4e11e02AA14c7f24DB749421986EAEc1369e8C9/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25546 Update for Allnodes
  blockchains/akash/validators/assets/akashvaloper1c07ughj0a396vdg7t9edy2wyrzr90p02yhl7p8/logo.png
  blockchains/akash/validators/list.json
  blockchains/cardano/validators/assets/pool1du3r4a7xq60hg2x0wcz7lw5ya3qs74rk258c8kanp93rsqdqu45/logo.png
  blockchains/cardano/validators/list.json
  blockchains/osmosis/validators/list.json
  blockchains/stride/validators/assets/stridevaloper17axr56uvurzt9dzjl6zplk4qwjkmxgmmqmthwv/logo.png
  blockchains/stride/validators/list.json
  blockchains/sui/validators/assets/0x885c0345bbf4441f39b98caf2295640a4dc3696ee9e8bc68f2101ca5e6f9bbf1/logo.png
  blockchains/sui/validators/list.json
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#25558 Add Sekuya (BEP20)
  blockchains/smartchain/assets/0x71d03A620646f8b572282Ef39228D36Add67ee20/info.json
  blockchains/smartchain/assets/0x71d03A620646f8b572282Ef39228D36Add67ee20/logo.png
Labels: Payment Status: Paid

#25521 Add Big Eyes ($BIG) (ERC20)
  blockchains/ethereum/assets/0xc8De43Bfe33FF496Fa14c270D9CB29Bda196B9B5/info.json
  blockchains/ethereum/assets/0xc8De43Bfe33FF496Fa14c270D9CB29Bda196B9B5/logo.png
Labels: Payment Status: Paid
