Repository trustwallet/assets, pull requests merged in 2023-02, with the labels that each got.

#23912 Pleasure Coin
  blockchains/smartchain/assets/0xaA076B62EFC6f357882E07665157A271aB46A063/info.json
  blockchains/smartchain/assets/0xaA076B62EFC6f357882E07665157A271aB46A063/logo.png
Labels: Payment Status: Paid

#23931 Add WeSendit (BEP20)
  blockchains/smartchain/assets/0x837A130aED114300Bab4f9f1F4f500682f7efd48/info.json
  blockchains/smartchain/assets/0x837A130aED114300Bab4f9f1F4f500682f7efd48/logo.png
Labels: Payment Status: Paid

#23943 Add Galaxy Heroes (BEP20)
  blockchains/smartchain/assets/0x9Cb9478C5Db5dAe52D5Af91737FF706F60195e45/info.json
  blockchains/smartchain/assets/0x9Cb9478C5Db5dAe52D5Af91737FF706F60195e45/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23963 ankr assets
  blockchains/avalanchec/assets/0x20CF1b6E9d856321ed4686877CF4538F2C84B4dE/info.json
  blockchains/avalanchec/assets/0x20CF1b6E9d856321ed4686877CF4538F2C84B4dE/logo.png
  blockchains/avalanchec/assets/0xc3344870d52688874b06d844E0C36cc39FC727F6/info.json
  blockchains/avalanchec/assets/0xc3344870d52688874b06d844E0C36cc39FC727F6/logo.png
  blockchains/ethereum/assets/0x26dcFbFa8Bc267b250432c01C982Eaf81cC5480C/info.json
  blockchains/ethereum/assets/0x26dcFbFa8Bc267b250432c01C982Eaf81cC5480C/logo.png
  blockchains/fantom/assets/0x0615Dbba33Fe61a31c7eD131BDA6655Ed76748B1/info.json
  blockchains/fantom/assets/0x0615Dbba33Fe61a31c7eD131BDA6655Ed76748B1/logo.png
  blockchains/fantom/assets/0xCfC785741Dc0e98ad4c9F6394Bb9d43Cd1eF5179/info.json
  blockchains/fantom/assets/0xCfC785741Dc0e98ad4c9F6394Bb9d43Cd1eF5179/logo.png
  blockchains/polygon/assets/0x0E9b89007eEE9c958c0EDA24eF70723C2C93dD58/info.json
  blockchains/polygon/assets/0x0E9b89007eEE9c958c0EDA24eF70723C2C93dD58/logo.png
  blockchains/polygon/assets/0x101A023270368c0D50BFfb62780F4aFd4ea79C35/info.json
  blockchains/polygon/assets/0x101A023270368c0D50BFfb62780F4aFd4ea79C35/logo.png
  blockchains/smartchain/assets/0x52F24a5e03aee338Da5fd9Df68D2b6FAe1178827/info.json
  blockchains/smartchain/assets/0x52F24a5e03aee338Da5fd9Df68D2b6FAe1178827/logo.png
  blockchains/smartchain/assets/0x738d96Caf7096659DB4C1aFbf1E1BDFD281f388C/info.json
  blockchains/smartchain/assets/0x738d96Caf7096659DB4C1aFbf1E1BDFD281f388C/logo.png
  blockchains/smartchain/assets/0xe05A08226c49b636ACf99c40Da8DC6aF83CE5bB3/info.json
  blockchains/smartchain/assets/0xe05A08226c49b636ACf99c40Da8DC6aF83CE5bB3/logo.png
Labels: Payment Status: Paid

#23974 Add Bitconey token logo and info1
  blockchains/smartchain/assets/0x2189455051A1c1E6190276f84f73Ec6Fb2fe62DF/info.json
  blockchains/smartchain/assets/0x2189455051A1c1E6190276f84f73Ec6Fb2fe62DF/logo.png
Labels: Status: On Hold, Payment Status: Paid

#23965 update xcn info
  blockchains/ethereum/assets/0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18/info.json
  blockchains/ethereum/assets/0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18/logo.png
  blockchains/smartchain/assets/0x7324c7C0d95CEBC73eEa7E85CbAac0dBdf88a05b/info.json
  blockchains/smartchain/assets/0x7324c7C0d95CEBC73eEa7E85CbAac0dBdf88a05b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24011 Migration for Flash(ERC20)
  blockchains/ethereum/assets/0x20398aD62bb2D930646d45a6D4292baa0b860C1f/info.json
  blockchains/ethereum/assets/0x20398aD62bb2D930646d45a6D4292baa0b860C1f/logo.png
  blockchains/ethereum/assets/0xB1f1F47061A7Be15C69f378CB3f69423bD58F2F8/info.json
  blockchains/ethereum/assets/0xB1f1F47061A7Be15C69f378CB3f69423bD58F2F8/logo.png
Labels: Payment Status: Paid

#23979 Adding everrise.com logo for dApp
  dapps/everrise.com.png
Labels: Payment Status: Paid, Payment Status: Requested

#24010 Add Sheikh Inu (BEP20)
  blockchains/smartchain/assets/0xE5b5d4Bea7468B4994FA676949308a79497aa24c/info.json
  blockchains/smartchain/assets/0xE5b5d4Bea7468B4994FA676949308a79497aa24c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24009 [Atomic Nodes] - Add Kava Validator
  blockchains/kava/validators/assets/kavavaloper1y8elet4hh0qpl9jq5hlkkejgl2gx845ekmdq55/logo.png
  blockchains/kava/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24035 Add Shina Inu (SHI) (ERC20)
  blockchains/ethereum/assets/0x243cACb4D5fF6814AD668C3e225246efA886AD5a/info.json
  blockchains/ethereum/assets/0x243cACb4D5fF6814AD668C3e225246efA886AD5a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24034 Add Dejitaru TSUKA (ERC20)
  blockchains/ethereum/assets/0xc5fB36dd2fb59d3B98dEfF88425a3F425Ee469eD/info.json
  blockchains/ethereum/assets/0xc5fB36dd2fb59d3B98dEfF88425a3F425Ee469eD/logo.png
Labels: Payment Status: Paid

#24037 Add Stablz (STABLZ) (ERC20)
  blockchains/ethereum/assets/0xA4Eb9C64eC359D093eAc7B65F51Ef933D6e5F7cd/info.json
  blockchains/ethereum/assets/0xA4Eb9C64eC359D093eAc7B65F51Ef933D6e5F7cd/logo.png
Labels: Payment Status: Paid

#23925 Add CTC(TM) logo and info
  blockchains/smartchain/assets/0x7e41E454b6A29C54e4cDB565E47542f4BCb37ef1/info.json
  blockchains/smartchain/assets/0x7e41E454b6A29C54e4cDB565E47542f4BCb37ef1/logo.png
Labels: Payment Status: Paid

#24012 Add new validator
  blockchains/band/validators/assets/bandvaloper1hcu2spr3r80v36us40mg938f5qhaqq2qeajtfv/logo.png
  blockchains/band/validators/list.json
  blockchains/cosmos/validators/assets/cosmosvaloper1gf4wlkutql95j7wwsxz490s6fahlvk2s9xpwax/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/kava/validators/assets/kavavaloper1j4tymd9r3au3vm508l4jugdg7l892l2lmh4jry/logo.png
  blockchains/kava/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper122yaxffys6rmv03nwwkmn3rvr5skzxl9lry2a5/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/solana/validators/assets/D1J7k7WouxgwzCfPN5qnW7TSmCTNqgNxWhjAxq62UK8U/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24041 Update Fuse Token (ERC20)
  blockchains/ethereum/assets/0x970B9bB2C0444F5E81e9d0eFb84C8ccdcdcAf84d/info.json
  blockchains/ethereum/assets/0x970B9bB2C0444F5E81e9d0eFb84C8ccdcdcAf84d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24062 Delete CORE from chainlist
  blockchains/ethereum/chainlist.json
Labels: Payment Status: Paid

#24077 Add new tokens from top exchanges
  blockchains/arbitrum/assets/0x6694340fc020c5E6B96567843da2df01b2CE1eb6/info.json
  blockchains/arbitrum/assets/0x6694340fc020c5E6B96567843da2df01b2CE1eb6/logo.png
  blockchains/arbitrum/assets/0xaE6aab43C4f3E0cea4Ab83752C278f8dEbabA689/info.json
  blockchains/arbitrum/assets/0xaE6aab43C4f3E0cea4Ab83752C278f8dEbabA689/logo.png
  blockchains/ethereum/assets/0x1b5036bEc1B82D44d52Fa953A370b3c6Cd9328B5/info.json
  blockchains/ethereum/assets/0x1b5036bEc1B82D44d52Fa953A370b3c6Cd9328B5/logo.png
  blockchains/ethereum/assets/0x5283D291DBCF85356A21bA090E6db59121208b44/info.json
  blockchains/ethereum/assets/0x5283D291DBCF85356A21bA090E6db59121208b44/logo.png
  blockchains/ethereum/assets/0x9f826324bb9BdcF7E7Eb274BEDc417BD45D74F39/info.json
  blockchains/ethereum/assets/0x9f826324bb9BdcF7E7Eb274BEDc417BD45D74F39/logo.png
  blockchains/polygon/assets/0x08C15FA26E519A78a666D19CE5C646D55047e0a3/info.json
  blockchains/polygon/assets/0x08C15FA26E519A78a666D19CE5C646D55047e0a3/logo.png
  blockchains/smartchain/assets/0x0a3A21356793B49154Fd3BbE91CBc2A16c0457f5/info.json
  blockchains/smartchain/assets/0x0a3A21356793B49154Fd3BbE91CBc2A16c0457f5/logo.png
  blockchains/smartchain/assets/0x26734ADd0650719eA29087fe5CC0AaB81b4f237D/info.json
  blockchains/smartchain/assets/0x26734ADd0650719eA29087fe5CC0AaB81b4f237D/logo.png
  blockchains/smartchain/assets/0x4A9A2b2b04549C3927dd2c9668A5eF3fCA473623/info.json
  blockchains/smartchain/assets/0x4A9A2b2b04549C3927dd2c9668A5eF3fCA473623/logo.png
Labels: Payment Status: Paid

#24073 Add BNB Tiger Inu (BEP20)
  blockchains/smartchain/assets/0xAC68931B666E086E9de380CFDb0Fb5704a35dc2D/info.json
  blockchains/smartchain/assets/0xAC68931B666E086E9de380CFDb0Fb5704a35dc2D/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24075 Add FET, TERITORY, IRIS to chainlist
  blockchains/axelar/info/info.json
  blockchains/cosmos/chainlist.json
  blockchains/fetch/info/info.json
  blockchains/fetch/info/logo.png
  blockchains/iris/info/info.json
  blockchains/iris/info/logo.png
  blockchains/juno/info/info.json
  blockchains/stargaze/info/info.json
  blockchains/teritory/info/info.json
  blockchains/teritory/info/logo.png
Labels: Payment Status: Paid

#24095 Fix name for blockchain TERITORI
  blockchains/ethereum/chainlist.json
  blockchains/stargaze/info/info.json
  blockchains/teritori/info/info.json
  blockchains/teritori/info/logo.png
Labels: Payment Status: Paid

#24096 Fix explorer for TERITORI
  blockchains/cosmos/chainlist.json
  blockchains/teritori/info/info.json
Labels: Payment Status: Paid

#24086 Add tokentool.bitbond.com logo for dApp
  dapps/tokentool.bitbond.com.png
Labels: Payment Status: Paid

#24106 Add King Finance (BEP20)
  blockchains/smartchain/assets/0x74f08aF7528Ffb751e3A435ddD779b5C4565e684/info.json
  blockchains/smartchain/assets/0x74f08aF7528Ffb751e3A435ddD779b5C4565e684/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24117 rename 'Binance-Peg' to 'BNB pegged'
  blockchains/smartchain/assets/0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153/info.json
  blockchains/smartchain/assets/0x0Eb3a705fc54725037CC9e008bDede697f62F335/info.json
  blockchains/smartchain/assets/0x101d82428437127bF1608F699CD651e6Abf9766E/info.json
  blockchains/smartchain/assets/0x14016E85a25aeb13065688cAFB43044C2ef86784/info.json
  blockchains/smartchain/assets/0x16939ef78684453bfDFb47825F8a5F714f12623a/info.json
  blockchains/smartchain/assets/0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3/info.json
  blockchains/smartchain/assets/0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb/info.json
  blockchains/smartchain/assets/0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE/info.json
  blockchains/smartchain/assets/0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63/info.json
  blockchains/smartchain/assets/0x1f9f6a696C6Fd109cD3956F45dC709d2b3902163/info.json
  blockchains/smartchain/assets/0x2170Ed0880ac9A755fd29B2688956BD959F933F8/info.json
  blockchains/smartchain/assets/0x2859e4544C4bB03966803b044A93563Bd2D0DD4D/info.json
  blockchains/smartchain/assets/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47/info.json
  blockchains/smartchain/assets/0x3d6545b08693daE087E957cb1180ee38B9e3c25E/info.json
  blockchains/smartchain/assets/0x4338665CBB7B2485A8855A139b75D5e34AB0DB94/info.json
  blockchains/smartchain/assets/0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8/info.json
  blockchains/smartchain/assets/0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6/info.json
  blockchains/smartchain/assets/0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402/info.json
  blockchains/smartchain/assets/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c/info.json
  blockchains/smartchain/assets/0x715D400F88C167884bbCc41C5FeA407ed4D2f8A0/info.json
  blockchains/smartchain/assets/0x7F70642d88cf1C4a3a7abb072B53B929b653edA5/info.json
  blockchains/smartchain/assets/0x8595F9dA7b868b1822194fAEd312235E43007b49/info.json
  blockchains/smartchain/assets/0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e/info.json
  blockchains/smartchain/assets/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d/info.json
  blockchains/smartchain/assets/0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf/info.json
  blockchains/smartchain/assets/0x9678E42ceBEb63F23197D726B29b1CB20d0064E5/info.json
  blockchains/smartchain/assets/0x990E7154bB999FAa9b2fa5Ed29E822703311eA85/info.json
  blockchains/smartchain/assets/0x9Ac983826058b8a9C7Aa1C9171441191232E8404/info.json
  blockchains/smartchain/assets/0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18/info.json
  blockchains/smartchain/assets/0xBf5140A22578168FD562DCcF235E5D43A02ce9B1/info.json
  blockchains/smartchain/assets/0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD/info.json
  blockchains/smartchain/assets/0xFd7B3A77848f1C2D67E05E54d78d174a0C850335/info.json
  blockchains/smartchain/assets/0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094/info.json
  blockchains/smartchain/assets/0xbA2aE424d960c26247Dd6c32edC70B295c744C43/info.json
  blockchains/smartchain/assets/0xbF7c81FFF98BbE61B40Ed186e4AfD6DDd01337fe/info.json
  blockchains/smartchain/assets/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56/info.json
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#24126 Rename Apenft
  blockchains/smartchain/assets/0x1fC9004eC7E5722891f5f38baE7678efCB11d34D/info.json
Labels: Payment Status: Paid

#24103 Add Carbon (BEP20)
  blockchains/smartchain/assets/0x04756126F044634C9a0f0E985e60c88a51ACC206/info.json
  blockchains/smartchain/assets/0x04756126F044634C9a0f0E985e60c88a51ACC206/logo.png
Labels: Payment Status: Paid

#24127 Add Gains Network (GNS) to Arbitrum and Polygon
  blockchains/arbitrum/assets/0x18c11FD286C5EC11c3b683Caa813B77f5163A122/info.json
  blockchains/arbitrum/assets/0x18c11FD286C5EC11c3b683Caa813B77f5163A122/logo.png
  blockchains/polygon/assets/0xE5417Af564e4bFDA1c483642db72007871397896/info.json
  blockchains/polygon/assets/0xE5417Af564e4bFDA1c483642db72007871397896/logo.png
  dapps/gains.trade.png
Labels: Payment Status: Paid

#24144 Migration for XFT
  blockchains/ethereum/assets/0x76BC677d444f1E9d57dAf5187ee2b7dC852745aE/info.json
  blockchains/ethereum/assets/0x76BC677d444f1E9d57dAf5187ee2b7dC852745aE/logo.png
  blockchains/ethereum/assets/0xABe580E7ee158dA464b51ee1a83Ac0289622e6be/info.json
  blockchains/ethereum/assets/0xABe580E7ee158dA464b51ee1a83Ac0289622e6be/logo.png
Labels: Payment Status: Paid

#24124 Add Wrapped GICT (BEP20)
  blockchains/smartchain/assets/0x27B2D695eF01d10EE96582a23db201B0Aa338639/info.json
  blockchains/smartchain/assets/0x27B2D695eF01d10EE96582a23db201B0Aa338639/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24151 Add Legend V Validator
  blockchains/binance/validators/assets/bva1lup0myq4xqu0ze0ng92w69jqwd2qqycxc76v2r/logo.png
  blockchains/binance/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24157 Migration for NXRA(ERC20)
  blockchains/ethereum/assets/0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0/info.json
  blockchains/ethereum/assets/0x00a8b738E453fFd858a7edf03bcCfe20412f0Eb0/logo.png
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid

#24132 Add AllianceBlock Nexera Token (ERC20)
  blockchains/ethereum/assets/0x644192291cc835A93d6330b24EA5f5FEdD0eEF9e/info.json
  blockchains/ethereum/assets/0x644192291cc835A93d6330b24EA5f5FEdD0eEF9e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24169 Add USDC (optimism)
  blockchains/optimism/assets/0x7F5c764cBc14f9669B88837ca1490cCa17c31607/info.json
  blockchains/optimism/assets/0x7F5c764cBc14f9669B88837ca1490cCa17c31607/logo.png
  blockchains/optimism/assets/0x94b008aA00579c1307B0EF2c499aD98a8ce58e58/info.json
  blockchains/optimism/assets/0x94b008aA00579c1307B0EF2c499aD98a8ce58e58/logo.png
Labels: Payment Status: Paid

#24180 Fix Tori explorer
  blockchains/teritori/info/info.json
Labels: Payment Status: Requested

#24187 Rename explorers (FETCH) (IRIS)
  blockchains/fetch/info/info.json
  blockchains/iris/info/info.json
Labels: Payment Status: Paid
