Repository trustwallet/assets, pull requests merged in 2023-12, with the labels that each got.

#26889 Update PLANET token description
  blockchains/ethereum/assets/0x2aD9adDD0d97EC3cDBA27F92bF6077893b76Ab0b/info.json
Labels: Payment Status: Requested

#26851 Add Beam (BEAM) (ERC20)
  blockchains/ethereum/assets/0x62D0A8458eD7719FDAF978fe5929C6D342B0bFcE/info.json
  blockchains/ethereum/assets/0x62D0A8458eD7719FDAF978fe5929C6D342B0bFcE/logo.png
  blockchains/smartchain/assets/0x62D0A8458eD7719FDAF978fe5929C6D342B0bFcE/info.json
  blockchains/smartchain/assets/0x62D0A8458eD7719FDAF978fe5929C6D342B0bFcE/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25771 Update info.json
  blockchains/smartchain/assets/0x3Fa52142B7836468aEd78753e6325b2aEE7dDafe/info.json
  blockchains/smartchain/assets/0x3Fa52142B7836468aEd78753e6325b2aEE7dDafe/logo.png
Labels: Payment Status: Paid

#26852 Add Moonlight Token (BEP20)
  blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/info.json
  blockchains/smartchain/assets/0xB1CeD2e320E3f4C8e3511B1DC59203303493F382/logo.png
Labels: Payment Status: Requested

#26775 Add Big Amber Stone (BEP20)
  blockchains/smartchain/assets/0x40FfAFcd7415ed2F7A902312407181140Ad14E68/info.json
  blockchains/smartchain/assets/0x40FfAFcd7415ed2F7A902312407181140Ad14E68/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#26825 Add AWT (BEP20)
  blockchains/smartchain/assets/0xceacCe74f7e1C42c157b6184fB4FBD59dA8F509e/info.json
  blockchains/smartchain/assets/0xceacCe74f7e1C42c157b6184fB4FBD59dA8F509e/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26921 Tomochain and axl usdc
  .github/assets.config.yaml
  blockchains/base/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
  blockchains/base/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/logo.png
  blockchains/kavaevm/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
  blockchains/kavaevm/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/logo.png
  blockchains/linea/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
  blockchains/linea/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/logo.png
  blockchains/mantle/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
  blockchains/mantle/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/logo.png
  blockchains/optimism/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
  blockchains/optimism/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/logo.png
  blockchains/tomochain/assets/0x01F83cE6636179b54b0CC0C408f9a8bce40ae776/info.json
  blockchains/tomochain/assets/0x01F83cE6636179b54b0CC0C408f9a8bce40ae776/logo.png
  blockchains/tomochain/assets/0x17B26400621695c2D8C2D8869f6259E82D7544c4/info.json
  blockchains/tomochain/assets/0x453B71962b5ffbe830a47AbB11A5CFd35C4250BA/info.json
  blockchains/tomochain/assets/0x5080781e91237b6D7f026D5306b7233e26Cd6C16/info.json
  blockchains/tomochain/assets/0x567b1e373f7285e9a32f5eeB9305b6964B6a3532/info.json
  blockchains/tomochain/assets/0x5e55D0c59287F5F8d540eF0766cA3F3810C71B84/info.json
  blockchains/tomochain/assets/0x5e55D0c59287F5F8d540eF0766cA3F3810C71B84/logo.png
  blockchains/tomochain/assets/0x8103Bb77eD2035b5da9A3A65d9c313cb6eE41dbD/info.json
  blockchains/tomochain/assets/0x936b1F7290c8CFC57e31D7e4a301D5F9fA5B0cd8/info.json
  blockchains/tomochain/assets/0x936b1F7290c8CFC57e31D7e4a301D5F9fA5B0cd8/logo.png
  blockchains/tomochain/assets/0xcE98172f4fC9Ad02da607843A2C211b7834431da/info.json
  blockchains/tomochain/assets/0xcE98172f4fC9Ad02da607843A2C211b7834431da/logo.png
  blockchains/tomochain/info/info.json
  blockchains/tomochain/info/logo.png
  go.mod
  go.sum
  internal/config/validators.go
  internal/manager/manager.go
Labels: Payment Status: Requested

#26922 Update OLE token
  blockchains/arbitrum/assets/0x7Be5Dd337CC6cE3e474F64E2A92A566445290864/info.json
  blockchains/arbitrum/assets/0x7Be5Dd337CC6cE3e474F64E2A92A566445290864/logo.png
  blockchains/arbitrum/assets/0xD4d026322C88C2d49942A75DfF920FCfbC5614C1/info.json
  blockchains/arbitrum/assets/0xD4d026322C88C2d49942A75DfF920FCfbC5614C1/logo.png
  blockchains/ethereum/assets/0x1B6e9c73beE68102d9dd4A2627f97bFf4183ab0A/info.json
  blockchains/ethereum/assets/0x1B6e9c73beE68102d9dd4A2627f97bFf4183ab0A/logo.png
  blockchains/ethereum/assets/0x92CfbEC26C206C90aeE3b7C66A9AE673754FaB7e/info.json
  blockchains/ethereum/assets/0x92CfbEC26C206C90aeE3b7C66A9AE673754FaB7e/logo.png
  blockchains/smartchain/assets/0xB7E2713CF55cf4b469B5a8421Ae6Fc0ED18F1467/info.json
  blockchains/smartchain/assets/0xB7E2713CF55cf4b469B5a8421Ae6Fc0ED18F1467/logo.png
  blockchains/smartchain/assets/0xa865197A84E780957422237B5D152772654341F3/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#26809 Add Grok (BEP20)
  blockchains/smartchain/assets/0x2e53414853f058A9BC14E052431008483bD85B4c/info.json
  blockchains/smartchain/assets/0x2e53414853f058A9BC14E052431008483bD85B4c/logo.png
Labels: Payment Status: Paid

#26977 Add icon for a TW article
  dapps/tw_scw_writing_hand.png
Labels: Payment Status: Requested

#26990 decimals
  blockchains/mantle/assets/0xEB466342C4d449BC9f53A865D5Cb90586f405215/info.json
Labels: Payment Status: Requested

#26953 Add TEM (BEP20)
  blockchains/smartchain/assets/0x19e6BfC1A6e4B042Fb20531244D47E252445df01/info.json
  blockchains/smartchain/assets/0x19e6BfC1A6e4B042Fb20531244D47E252445df01/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26978 Add Neurashi (BEP20)
  blockchains/smartchain/assets/0x6cda2862fd4B88CCFA522FFeD66bC4277e7D9Cc9/info.json
  blockchains/smartchain/assets/0x6cda2862fd4B88CCFA522FFeD66bC4277e7D9Cc9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#27001 Update Everscale info
  blockchains/everscale/info/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#27037 add feedback logo for Swift Wallet
  dapps/tw.swift.feedback_logo.png
Labels: Payment Status: Requested

#27026 Add GROK (BEP20)
  blockchains/smartchain/assets/0xC53ca0d56C420E8f913316e84d2c492eDe99c61e/info.json
  blockchains/smartchain/assets/0xC53ca0d56C420E8f913316e84d2c492eDe99c61e/logo.png
Labels: Payment Status: Paid

#27034 Add Jesus Coin (ERC20)
  blockchains/ethereum/assets/0xba386A4Ca26B85FD057ab1Ef86e3DC7BdeB5ce70/info.json
  blockchains/ethereum/assets/0xba386A4Ca26B85FD057ab1Ef86e3DC7BdeB5ce70/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27095 Add Matrix Chain (BEP20)
  blockchains/smartchain/assets/0x67009eB16ff64d06b4F782b3c552b924B1D1bb93/info.json
  blockchains/smartchain/assets/0x67009eB16ff64d06b4F782b3c552b924B1D1bb93/logo.png
Labels: Payment Status: Paid

#26968 Add Chain Games (CHAIN) (ERC20)
  blockchains/ethereum/assets/0xC4C2614E694cF534D407Ee49F8E44D125E4681c4/info.json
  blockchains/ethereum/assets/0xC4C2614E694cF534D407Ee49F8E44D125E4681c4/logo.png
Labels: Payment Status: Paid

#27028 Add MUBI(MUBI) (ERC20)
  blockchains/ethereum/assets/0x38e382F74dfb84608F3C1F10187f6bEf5951DE93/info.json
  blockchains/ethereum/assets/0x38e382F74dfb84608F3C1F10187f6bEf5951DE93/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
