Repository trustwallet/assets, pull requests merged in 2023-07, with the labels that each got.

#25673 Add Pepe 2.0 (PEPE2.0) (ERC20)
  blockchains/ethereum/assets/0xfb66321D7C674995dFcC2cb67A30bC978dc862AD/info.json
  blockchains/ethereum/assets/0xfb66321D7C674995dFcC2cb67A30bC978dc862AD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25687 Add Akita Inu (ERC20)
  blockchains/ethereum/assets/0x3301Ee63Fb29F863f2333Bd4466acb46CD8323E6/info.json
  blockchains/ethereum/assets/0x3301Ee63Fb29F863f2333Bd4466acb46CD8323E6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25688 Add ICLICK INU (BEP20)
  blockchains/smartchain/assets/0xc8C06a58E4ad7c01b9bb5Af6C76a7a1CfEBd0319/info.json
  blockchains/smartchain/assets/0xc8C06a58E4ad7c01b9bb5Af6C76a7a1CfEBd0319/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25770 Add GridX (BEP20)
  blockchains/smartchain/assets/0x7fFb5A90cdbd2aE2A65d5bFe259AC936Cc302bE2/info.json
  blockchains/smartchain/assets/0x7fFb5A90cdbd2aE2A65d5bFe259AC936Cc302bE2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25764 Add DRAC Network (DRAC) (ERC20)
  blockchains/ethereum/assets/0xc8A34E86C187830922f841985E376f412eE0088A/info.json
  blockchains/ethereum/assets/0xc8A34E86C187830922f841985E376f412eE0088A/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25799 Add PVC META (BEP20)
  blockchains/smartchain/assets/0x75ca521892DE7f2ecFB070Cab545c250d0cEB7e3/info.json
  blockchains/smartchain/assets/0x75ca521892DE7f2ecFB070Cab545c250d0cEB7e3/logo.png
Labels: Payment Status: Paid

#25830 Add TRUSTxGAMING (BEP20)
  blockchains/smartchain/assets/0x9f46EcF92E7F6eE8C03f393ADf04C2e17B8cD0B0/info.json
  blockchains/smartchain/assets/0x9f46EcF92E7F6eE8C03f393ADf04C2e17B8cD0B0/logo.png
Labels: Payment Status: Paid

#25865 add cosmos validator
  blockchains/cosmos/validators/assets/cosmosvaloper15w6ra6m68c63t0sv2hzmkngwr9t88e23r8vtg5/logo.png
  blockchains/cosmos/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#25879 Add Mega Lottery (MLR) (TRC21)
  blockchains/tomochain/assets/0x5080781e91237b6D7f026D5306b7233e26Cd6C16/info.json
  blockchains/tomochain/assets/0x5080781e91237b6D7f026D5306b7233e26Cd6C16/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25857 Add X AI (BEP20)
  blockchains/smartchain/assets/0x2A45a892877Ef383c5fc93A5206546c97496da9e/info.json
  blockchains/smartchain/assets/0x2A45a892877Ef383c5fc93A5206546c97496da9e/logo.png
Labels: Status: On Hold, Payment Status: Paid, Under Review
