Repository trustwallet/assets, pull requests merged in 2023-08, with the labels that each got.

#25919 Add Rimaunangis (BEP20)
  blockchains/smartchain/assets/0x8D1427a32F0A4C4BF052252e68E7FF1B2Ba80c01/info.json
  blockchains/smartchain/assets/0x8D1427a32F0A4C4BF052252e68E7FF1B2Ba80c01/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25944 Enable staking for near
  blockchains/near/info/info.json
Labels: Payment Status: Requested

#26035 Add Bad Idea AI (BAD) (ERC20)
  blockchains/ethereum/assets/0x32b86b99441480a7E5BD3A26c124ec2373e3F015/info.json
  blockchains/ethereum/assets/0x32b86b99441480a7E5BD3A26c124ec2373e3F015/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26045 Stakin validator info
  blockchains/agoric/validators/assets/agoricvaloper1nkrt7kjln9rsypg3m4k23q703nww9lj9msvqp5/logo.png
  blockchains/agoric/validators/list.json
  blockchains/akash/validators/assets/akashvaloper12fnzqmnja37mf2y9m6r3dleq5n3jkz7pfkpzmy/logo.png
  blockchains/akash/validators/list.json
  blockchains/axelar/validators/assets/axelarvaloper1uf7s2v44qqpe9lpnsjy6cfjueqytakuzayfg0h/logo.png
  blockchains/axelar/validators/list.json
  blockchains/cryptoorg/validators/assets/crocncl18nc2zx5rs7jwm7dwk5gvelul2wer8zfykfmg8h/logo.png
  blockchains/cryptoorg/validators/list.json
  blockchains/juno/validators/assets/junovaloper1xdywquvz5g6r5wv6tpkj6chad0fkk459gf9ny6/logo.png
  blockchains/juno/validators/list.json
  blockchains/near/validators/assets/stakin.poolv1.near/logo.png
  blockchains/near/validators/list.json
  blockchains/sei/validators/assets/seivaloper1eqgnd7ey0hnha8rrfukjrsawulhna0zagcg6a4/logo.png
  blockchains/sei/validators/list.json
  blockchains/stargaze/validators/assets/starsvaloper1swer6tl0s59g82xnq5gmgsdueld79wpw8vptlu/logo.png
  blockchains/stargaze/validators/list.json
  blockchains/sui/validators/assets/0x9b8b11c9b2336d35f2db8d5318ff32de51b85857f0e53a5c31242cf3797f4be4/logo.png
  blockchains/sui/validators/list.json
  blockchains/umee/validators/assets/umeevaloper10nsytn9zmtfnhk37hqfe2h9v599ld3h5zs9fqj/logo.png
  blockchains/umee/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26040 Added Terra Classic validators
  blockchains/terra/validators/assets/terravaloper13avdm9rqxpftv3vrkaqaakakgh30909x8c07v3/logo.png
  blockchains/terra/validators/assets/terravaloper15ahd0dg9qwkg5tjmkn7fm6sdrpwa47m50l4zrg/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26089 Update btcmt bep-20 logo
  blockchains/smartchain/assets/0x410a56541bD912F9B60943fcB344f1E3D6F09567/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26112 Migration for Crypto Snack
  blockchains/smartchain/assets/0x86aCCc2580dA5Bd522A0eEc7C881A0d4f33De657/info.json
  blockchains/smartchain/assets/0x86aCCc2580dA5Bd522A0eEc7C881A0d4f33De657/logo.png
  blockchains/smartchain/assets/0xe52bB35344cceedd014Be2896d01e604ad992c85/info.json
  blockchains/smartchain/assets/0xe52bB35344cceedd014Be2896d01e604ad992c85/logo.png
Labels: Payment Status: Paid

#26054 Added Hexxagon (terravaloper1aa6f2qeu0hrqpsxe4rggz0k7e43jfce43arz82) validator
  blockchains/terra/validators/assets/terravaloper1aa6f2qeu0hrqpsxe4rggz0k7e43jfce43arz82/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26134 Add AutoStake Solana validator
  blockchains/solana/validators/assets/D4mLBafAJjpRABT5Tyj6UhuwJ8DLRk74JzyuTMUdU9Fz/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#26046 Add ScottyBeam token info
  blockchains/smartchain/assets/0x000351d035D8BBf2aa3131EbFECD66Fb21836f6c/info.json
  blockchains/smartchain/assets/0x000351d035D8BBf2aa3131EbFECD66Fb21836f6c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#26146 Add Squid router logo
  dapps/squidrouter.com.png
Labels: Payment Status: Requested

#26114 Add UNS Token (BEP20)
  blockchains/smartchain/assets/0xEcf99aB23C11ddc6520252105308C251001AEfBB/info.json
  blockchains/smartchain/assets/0xEcf99aB23C11ddc6520252105308C251001AEfBB/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#26154 Add WEB3MET (BEP20)
  blockchains/smartchain/assets/0x7208A2671a2f96950D44C6dAAF24719Ce44dEA78/info.json
  blockchains/smartchain/assets/0x7208A2671a2f96950D44C6dAAF24719Ce44dEA78/logo.png
Labels: Payment Status: Paid

#26169 Add AutoStake providers
  blockchains/agoric/validators/assets/agoricvaloper1df98lt4ph685ujr69jy5w8xvrtszad7te7pna9/logo.png
  blockchains/agoric/validators/list.json
  blockchains/akash/validators/assets/akashvaloper1strxz39h5fapp7zvn5mvf8xm0ea9aajqjstv6g/logo.png
  blockchains/akash/validators/list.json
  blockchains/axelar/validators/assets/axelarvaloper1kafxdlrq8svz68j2tn8qtqk74j4yhylyf364pt/logo.png
  blockchains/axelar/validators/list.json
  blockchains/band/validators/assets/bandvaloper1xs2penspev206jj0egh5qu7qmr6mjzfgj299xl/logo.png
  blockchains/band/validators/list.json
  blockchains/cardano/validators/assets/pool194usk2h8vcq6yw89xs5asrvw22g08kcfy72xyfrnnkg6qrhtlfw/logo.png
  blockchains/cardano/validators/assets/pool1ljywsch33t7gaf02aeeqkqpuku0ngpwl9fm04t7u5sl5xyunmgp/logo.png
  blockchains/cardano/validators/assets/pool1yet04d4ykpp7me8uc2jx2glxrx88kt9uhmv6jeh7xkmtu5zucna/logo.png
  blockchains/cardano/validators/assets/pool1zz7x8ergn02chznayj9fjds2gk5q6prmpdr49faspd65kzqsrjs/logo.png
  blockchains/cardano/validators/list.json
  blockchains/comdex/validators/assets/comdexvaloper195re7mhwh9urewm3rvaj9r7vm6j63c4sd78njd/logo.png
  blockchains/comdex/validators/list.json
  blockchains/crescent/validators/assets/crevaloper173rqm36cj5efq2yhsedd8vhfrl7rjqeftkp80f/logo.png
  blockchains/crescent/validators/list.json
  blockchains/evmos/validators/assets/evmosvaloper1shvcjzhcxau6qtlz9w82a646ecwp4hq7ayqt0w/logo.png
  blockchains/evmos/validators/list.json
  blockchains/fetch/validators/assets/fetchvaloper1ph02ux2dujl7uv4lzv6vy2y6vjstd4eplfznuw/logo.png
  blockchains/fetch/validators/list.json
  blockchains/harmony/validators/assets/one1na6669ra9r99wsz39440fxdf6d29vhmz8mkdha/logo.png
  blockchains/harmony/validators/list.json
  blockchains/juno/validators/assets/junovaloper15yuuev6n8sfvvkqx2m4rqvrnu8vyuzvmkku3fm/logo.png
  blockchains/juno/validators/list.json
  blockchains/kava/validators/assets/kavavaloper1hztgl202pvetspxch0pcchaqzrduw4qq64q08u/logo.png
  blockchains/kava/validators/list.json
  blockchains/kujira/validators/assets/kujiravaloper1rc2h9eg3wul70a8yruadmn9vf947nhcdzcjyg0/logo.png
  blockchains/kujira/validators/list.json
  blockchains/mars/validators/assets/marsvaloper1c4r6mndnmrvr9455e88nad7lg09zd89f3c0xpq/logo.png
  blockchains/mars/validators/list.json
  blockchains/nativecanto/validators/assets/cantovaloper1z2gk5exs2ysh24cwg57eg99wy03y95khjl2qyz/logo.png
  blockchains/nativecanto/validators/list.json
  blockchains/nativeevmos/validators/assets/evmosvaloper1shvcjzhcxau6qtlz9w82a646ecwp4hq7ayqt0w/logo.png
  blockchains/nativeevmos/validators/list.json
  blockchains/near/validators/assets/autostake.poolv1.near/logo.png
  blockchains/near/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1pxphtfhqnx9ny27d53z4052e3r76e7qq495ehm/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/persistence/validators/assets/persistencevaloper16jd664rd04j5lyckykjedt7vrha7k822vlkxty/logo.png
  blockchains/persistence/validators/list.json
  blockchains/secret/validators/assets/secretvaloper12y30xefd0wg53xtyv9lw7mjcdvf8nxgzzva3sr/logo.png
  blockchains/secret/validators/list.json
  blockchains/sommelier/validators/assets/sommvaloper1tl6jl7ecqwvgagsc4w46n9nm470cwjyg24hlw3/logo.png
  blockchains/sommelier/validators/list.json
  blockchains/stargaze/validators/assets/starsvaloper1r6usxgxmrz6ynjz2y5ez5u8ts3fpmtlrl8c9xr/logo.png
  blockchains/stargaze/validators/list.json
  blockchains/stride/validators/assets/stridevaloper1a5c3ejnzy0827t62cyj7etmuchdqvznhp5yp94/logo.png
  blockchains/stride/validators/list.json
  blockchains/teritori/validators/assets/torivaloper1g3pncd7m5ak8yeh9n42as57pvrcqqv4rjvh87h/logo.png
  blockchains/teritori/validators/list.json
  blockchains/terra/validators/assets/terravaloper1f2t96sz9hnwsqnneux6v28xfgn07pkxjduvwjz/logo.png
  blockchains/terra/validators/list.json
  blockchains/terrav2/validators/assets/terravaloper1yy5379nk24xffpq4egw7ue4ad3j7l79ma2enmz/logo.png
  blockchains/terrav2/validators/list.json
  blockchains/umee/validators/assets/umeevaloper1py60fpud4w468zn7mthfa25xnzuawjum7w90q2/logo.png
  blockchains/umee/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#26214 [BUSD.e] Decimals value for BUSD.e fixed
  blockchains/avalanchec/assets/0x19860CCB0A68fd4213aB9D8266F7bBf05A8dDe98/info.json
  blockchains/avalanchec/tokenlist.json
Labels: Payment Status: Paid
