Repository trustwallet/assets, pull requests merged in 2023-04, with the labels that each got.

#24550 Add Monetas(BEP20)
  blockchains/smartchain/assets/0x89e4818eD21F668D65f7851839d2dD8cE5D208b0/info.json
  blockchains/smartchain/assets/0x89e4818eD21F668D65f7851839d2dD8cE5D208b0/logo.png
Labels: Payment Status: Paid

#24547 Add tokens for zkEVM&zkSYNC
  blockchains/polygonzkevm/assets/0x1E4a5963aBFD975d8c9021ce480b42188849D41d/info.json
  blockchains/polygonzkevm/assets/0x1E4a5963aBFD975d8c9021ce480b42188849D41d/logo.png
  blockchains/polygonzkevm/assets/0x4F9A0e7FD2Bf6067db6994CF12E4495Df938E6e9/info.json
  blockchains/polygonzkevm/assets/0x4F9A0e7FD2Bf6067db6994CF12E4495Df938E6e9/logo.png
  blockchains/polygonzkevm/assets/0x68286607A1d43602d880D349187c3c48c0fD05E6/info.json
  blockchains/polygonzkevm/assets/0x68286607A1d43602d880D349187c3c48c0fD05E6/logo.png
  blockchains/polygonzkevm/assets/0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035/info.json
  blockchains/polygonzkevm/assets/0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035/logo.png
  blockchains/polygonzkevm/assets/0xa2036f0538221a77A3937F1379699f44945018d0/info.json
  blockchains/polygonzkevm/assets/0xa2036f0538221a77A3937F1379699f44945018d0/logo.png
  blockchains/polygonzkevm/info/info.json
  blockchains/zksync/assets/0x0000000000000000000000000000000000000000/info.json
  blockchains/zksync/assets/0x0000000000000000000000000000000000000000/logo.png
  blockchains/zksync/assets/0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4/info.json
  blockchains/zksync/assets/0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4/logo.png
  go.mod
  go.sum
Labels: Payment Status: Paid

#24578 Adding migrated FEGtoken to Trustwallet [ETH+BSC] (same CA)
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/info.json
  blockchains/ethereum/assets/0x389999216860AB8E0175387A0c90E5c52522C945/logo.png
  blockchains/ethereum/assets/0xbededDf2eF49E87037c4fb2cA34d1FF3D3992A11/info.json
  blockchains/ethereum/assets/0xbededDf2eF49E87037c4fb2cA34d1FF3D3992A11/logo.png
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/info.json
  blockchains/smartchain/assets/0xacFC95585D80Ab62f67A14C566C1b7a49Fe91167/logo.png
  blockchains/smartchain/assets/0xbededDf2eF49E87037c4fb2cA34d1FF3D3992A11/info.json
  blockchains/smartchain/assets/0xbededDf2eF49E87037c4fb2cA34d1FF3D3992A11/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24583 Add new Testnets
  blockchains/arbitrumgoerli/info/info.json
  blockchains/arbitrumgoerli/info/logo.png
  blockchains/avalanchecfuji/info/info.json
  blockchains/avalanchecfuji/info/logo.png
  blockchains/bnbt/info/info.json
  blockchains/bnbt/info/logo.png
  blockchains/ethereum/chainlist.json
  blockchains/goerlitestnet/info/info.json
  blockchains/goerlitestnet/info/logo.png
  blockchains/moonbasealpha/info/info.json
  blockchains/moonbasealpha/info/logo.png
  blockchains/optimismgoerli/info/info.json
  blockchains/optimismgoerli/info/logo.png
  blockchains/polygonmumbai/info/info.json
  blockchains/polygonmumbai/info/logo.png
  blockchains/polygonzkevm/info/info.json
  blockchains/sepolia/info/info.json
  blockchains/sepolia/info/logo.png
  blockchains/tftm/info/info.json
  blockchains/tftm/info/logo.png
  blockchains/zksync/info/info.json
Labels: Payment Status: Paid

#24647 makefile udpate
  .github/workflows/codeql.yml
  .github/workflows/fix.yml
  .gitignore
  Makefile
Labels: Payment Status: Requested

#24604 Add OKXChain Mainnet
  blockchains/ethereum/chainlist.json
  blockchains/okx/info/info.json
  blockchains/okx/info/logo.png
Labels: Payment Status: Paid

#24667 Add Crypto AI (BEP20)
  blockchains/smartchain/assets/0x3CEf8d4CC106a169902eA985ceC2dc6Ab055ad4c/info.json
  blockchains/smartchain/assets/0x3CEf8d4CC106a169902eA985ceC2dc6Ab055ad4c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24673 Add Ultimate Champions Token (ERC20, BEP20, POLYGON)
  blockchains/ethereum/assets/0x456125Cd98107ae0480Ba566f1b716D48Ba31453/info.json
  blockchains/ethereum/assets/0x456125Cd98107ae0480Ba566f1b716D48Ba31453/logo.png
  blockchains/polygon/assets/0xED755dBa6Ec1eb520076Cec051a582A6d81A8253/info.json
  blockchains/polygon/assets/0xED755dBa6Ec1eb520076Cec051a582A6d81A8253/logo.png
  blockchains/smartchain/assets/0x7e9AB560d37E62883E882474b096643caB234B65/info.json
  blockchains/smartchain/assets/0x7e9AB560d37E62883E882474b096643caB234B65/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24619 Add PirateCash (PIRATE) token on BSC
  blockchains/smartchain/assets/0x35f3fffFcb622bC9f64fA561D74e983Fd488D90c/info.json
  blockchains/smartchain/assets/0x35f3fffFcb622bC9f64fA561D74e983Fd488D90c/logo.png
Labels: Status: On Hold, Payment Status: Paid

#24654 Token Rebrand from OS to SOON
  blockchains/ethereum/assets/0x6100dd79fCAA88420750DceE3F735d168aBcB771/info.json
  blockchains/ethereum/assets/0x6100dd79fCAA88420750DceE3F735d168aBcB771/logo.png
Labels: Payment Status: Paid

#24713 Remove extra space
  blockchains/smartchain/assets/0x9f589e3eabe42ebC94A44727b3f3531C0c877809/info.json
Labels: Payment Status: Requested

#24716 Add Sakai Vault (BEP20)
  blockchains/smartchain/assets/0x43B35e89d15B91162Dea1C51133C4c93bdd1C4aF/info.json
  blockchains/smartchain/assets/0x43B35e89d15B91162Dea1C51133C4c93bdd1C4aF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24719 Add new cosmos chains
  blockchains/akash/info/info.json
  blockchains/akash/info/logo.png
  blockchains/comdex/info/info.json
  blockchains/comdex/info/logo.png
  blockchains/coreum/info/info.json
  blockchains/coreum/info/logo.png
  blockchains/crescent/info/info.json
  blockchains/crescent/info/logo.png
  blockchains/ethereum/assets/0x6100dd79fCAA88420750DceE3F735d168aBcB771/info.json
  blockchains/kujira/info/info.json
  blockchains/kujira/info/logo.png
  blockchains/mars/info/info.json
  blockchains/mars/info/logo.png
  blockchains/nativecanto/info/info.json
  blockchains/nativecanto/info/logo.png
  blockchains/neutrontestnet/info/info.json
  blockchains/neutrontestnet/info/logo.png
  blockchains/noble/info/info.json
  blockchains/noble/info/logo.png
  blockchains/persistence/info/info.json
  blockchains/persistence/info/logo.png
  blockchains/quasar/info/info.json
  blockchains/quasar/info/logo.png
  blockchains/sommelier/info/info.json
  blockchains/sommelier/info/logo.png
  blockchains/stride/info/info.json
  blockchains/stride/info/logo.png
  blockchains/umee/info/info.json
  blockchains/umee/info/logo.png
Labels: Payment Status: Paid

#24721 Renaming token (GMT Token to Gomining)
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24727 Add tokens from top exchanges
  blockchains/arbitrum/assets/0x319f865b287fCC10b30d8cE6144e8b6D1b476999/info.json
  blockchains/arbitrum/assets/0x319f865b287fCC10b30d8cE6144e8b6D1b476999/logo.png
  blockchains/arbitrum/assets/0x371c7ec6D8039ff7933a2AA28EB827Ffe1F52f07/info.json
  blockchains/arbitrum/assets/0x371c7ec6D8039ff7933a2AA28EB827Ffe1F52f07/logo.png
  blockchains/arbitrum/assets/0xaa54e84A3e6e5A80288d2C2f8e36eA5cA3A3Ca30/info.json
  blockchains/arbitrum/assets/0xaa54e84A3e6e5A80288d2C2f8e36eA5cA3A3Ca30/logo.png
  blockchains/ethereum/assets/0xF3A3023e6Dede84AD88a656A3269F2A36e83c9a9/info.json
  blockchains/ethereum/assets/0xF3A3023e6Dede84AD88a656A3269F2A36e83c9a9/logo.png
  blockchains/smartchain/assets/0x371c7ec6D8039ff7933a2AA28EB827Ffe1F52f07/info.json
  blockchains/smartchain/assets/0x371c7ec6D8039ff7933a2AA28EB827Ffe1F52f07/logo.png
  blockchains/smartchain/assets/0xc4736F2611A62d545DC2D0d8f0766283617e6FcB/info.json
  blockchains/smartchain/assets/0xc4736F2611A62d545DC2D0d8f0766283617e6FcB/logo.png
Labels: Payment Status: Paid

#24732 Add Bgvt logo
  blockchains/smartchain/assets/0xa03110800894b3CcF8723D991d80875561F96777/info.json
  blockchains/smartchain/assets/0xa03110800894b3CcF8723D991d80875561F96777/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24720 Add IoTex EVM
  blockchains/iotexevm/info/info.json
  blockchains/iotexevm/info/logo.png
  blockchains/smartchain/assets/0xa03110800894b3CcF8723D991d80875561F96777/info.json
Labels: Payment Status: Paid

#24731 Add Pepe (PEPE) (ERC20)
  blockchains/ethereum/assets/0x6982508145454Ce325dDbE47a25d4ec3d2311933/info.json
  blockchains/ethereum/assets/0x6982508145454Ce325dDbE47a25d4ec3d2311933/logo.png
Labels: Payment Status: Requested

#24702 Add CRYPTO SNACK (BEP20)
  blockchains/smartchain/assets/0x86aCCc2580dA5Bd522A0eEc7C881A0d4f33De657/info.json
  blockchains/smartchain/assets/0x86aCCc2580dA5Bd522A0eEc7C881A0d4f33De657/logo.png
Labels: Status: On Hold, Payment Status: Paid

#24779 StakeBoard dapp
  dapps/app.stakepark.xyz.png
Labels: Payment Status: Paid

#24786 Add AntNetworX (BEP20)
  blockchains/smartchain/assets/0x9186359F82c3c0Cc005A0b3563Dc4Ccd2627D82A/info.json
  blockchains/smartchain/assets/0x9186359F82c3c0Cc005A0b3563Dc4Ccd2627D82A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24805 Add Pepa Inu (BEP20)
  blockchains/smartchain/assets/0xC3137c696796D69F783CD0Be4aB4bB96814234Aa/info.json
  blockchains/smartchain/assets/0xC3137c696796D69F783CD0Be4aB4bB96814234Aa/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Status: On Hold, Payment Status: Paid

#24802 Add HELLO (BEP20)
  blockchains/smartchain/assets/0x0F1cBEd8EFa0E012AdbCCB1638D0aB0147D5Ac00/info.json
  blockchains/smartchain/assets/0x0F1cBEd8EFa0E012AdbCCB1638D0aB0147D5Ac00/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24809 Add babydoge to tokenlist
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#24824 Adding Larissa.Health - Cardano validator / stakepool
  blockchains/cardano/validators/assets/pool10c9l3k0z50ytt4krkfet7w3gwpv9d9nq47kk9ecy2c5f2uyvkgk/logo.png
  blockchains/cardano/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24815 Add Cheelee info and logo
  blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0/info.json
  blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24842 Add testnets zkBNB, BNB GREENFIELD
  blockchains/cardano/validators/list.json
  blockchains/ethereum/chainlist.json
  blockchains/gbnb/info/info.json
  blockchains/gbnb/info/logo.png
  blockchains/smartchain/assets/0x1F1C90aEb2fd13EA972F0a71e35c0753848e3DB0/info.json
Labels: Payment Status: Paid

#24852 Fix decimals of Tellor
  blockchains/ethereum/assets/0x0Ba45A8b5d5575935B8158a88C631E9F9C95a2e5/info.json
  blockchains/ethereum/assets/0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0/info.json
Labels: Payment Status: Requested

#24853 Change rpc_url for KLAY
  blockchains/klaytn/info/info.json
Labels: Payment Status: Paid
