Repository trustwallet/assets, pull requests merged in 2023-03, with the labels that each got.

#24196 [assets]: add zkevm blockchains supported in WC
  blockchains/polygonzkevm/info/info.json
  blockchains/polygonzkevm/info/logo.png
  blockchains/zksync/info/info.json
  blockchains/zksync/info/logo.png
Labels: Payment Status: Requested

#24200 Add FTM(BEP20) YGG(POLYGON)
  blockchains/ethereum/assets/0xcFEB09C3c5F0f78aD72166D55f9e6E9A60e96eEC/logo.png
  blockchains/polygon/assets/0x82617aA52dddf5Ed9Bb7B370ED777b3182A30fd1/info.json
  blockchains/polygon/assets/0x82617aA52dddf5Ed9Bb7B370ED777b3182A30fd1/logo.png
  blockchains/smartchain/assets/0xAD29AbB318791D579433D831ed122aFeAf29dcfe/info.json
  blockchains/smartchain/assets/0xAD29AbB318791D579433D831ed122aFeAf29dcfe/logo.png
  blockchains/smartchain/assets/0xeDF3ce4Dd6725650a8e9398e5C6398D061Fa7955/logo.png
Labels: Payment Status: Paid

#24206 Add ATM (BEP20)
  blockchains/smartchain/assets/0xF02b31b0B6dCabd579e41A0250288608FA43F898/info.json
  blockchains/smartchain/assets/0xF02b31b0B6dCabd579e41A0250288608FA43F898/logo.png
Labels: Payment Status: Paid

#24226 Add Mysterium (POLYGON)
  blockchains/polygon/assets/0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3/info.json
  blockchains/polygon/assets/0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24227 Add Mysterium (ERC20)
  blockchains/ethereum/assets/0x4Cf89ca06ad997bC732Dc876ed2A7F26a9E7f361/info.json
  blockchains/ethereum/assets/0x4Cf89ca06ad997bC732Dc876ed2A7F26a9E7f361/logo.png
Labels: Payment Status: Paid

#24228 Add Mysterium (BEP20)
  blockchains/smartchain/assets/0x2fF0B946A6782190C4Fe5D4971CFE79F0b6E4df2/info.json
  blockchains/smartchain/assets/0x2fF0B946A6782190C4Fe5D4971CFE79F0b6E4df2/logo.png
Labels: Payment Status: Paid

#24253 Add UnityMeta Token (BEP20)
  blockchains/smartchain/assets/0xca861e289f04cB9C67fd6b87ca7EAFa59192f164/info.json
  blockchains/smartchain/assets/0xca861e289f04cB9C67fd6b87ca7EAFa59192f164/logo.png
Labels: Payment Status: Paid

#24259 Migration for TRON BEP20
  blockchains/smartchain/assets/0x85EAC5Ac2F758618dFa09bDbe0cf174e7d574D5B/info.json
  blockchains/smartchain/assets/0x85EAC5Ac2F758618dFa09bDbe0cf174e7d574D5B/logo.png
Labels: Payment Status: Paid

#24201 Add FLOKI CEO (BEP20)
  blockchains/smartchain/assets/0x45289007706E7Ee7B42b1fA506661d97740Edfb4/info.json
  blockchains/smartchain/assets/0x45289007706E7Ee7B42b1fA506661d97740Edfb4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24267 Migration for ZEDXION (BEP20) (ERC20)
  blockchains/ethereum/assets/0xFbC4f3f645C4003a2E4F4e9b51077d2DaA9a9341/info.json
  blockchains/ethereum/assets/0xFbC4f3f645C4003a2E4F4e9b51077d2DaA9a9341/logo.png
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/assets/0xFbC4f3f645C4003a2E4F4e9b51077d2DaA9a9341/info.json
  blockchains/smartchain/assets/0xFbC4f3f645C4003a2E4F4e9b51077d2DaA9a9341/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#24268 Migration for ZEDXION
  blockchains/ethereum/assets/0xbAFDabaDcf19d0cFbbe0AB9C69CF050D86ff888C/info.json
  blockchains/ethereum/assets/0xbAFDabaDcf19d0cFbbe0AB9C69CF050D86ff888C/logo.png
  blockchains/ethereum/tokenlist.json
  blockchains/smartchain/assets/0xff44967f2E4EBE0b8c5b6812f25e1b9BceC70b34/info.json
  blockchains/smartchain/assets/0xff44967f2E4EBE0b8c5b6812f25e1b9BceC70b34/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#24204 Add PandAI Token (BEP20)
  blockchains/smartchain/assets/0x550D7984b7AdFfF88815E5528e12E322DF6D3B9B/info.json
  blockchains/smartchain/assets/0x550D7984b7AdFfF88815E5528e12E322DF6D3B9B/logo.png
Labels: Status: On Hold, Payment Status: Paid

#24288 Add new validator
  blockchains/solana/validators/assets/PUmpKiNnSVAZ3w4KaFX6jKSjXUNHFShGkXbERo54xjb/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24293 Add Cat (BEP20)
  blockchains/smartchain/assets/0x0173295183685F27C84db046B5F0bea3e683c24b/info.json
  blockchains/smartchain/assets/0x0173295183685F27C84db046B5F0bea3e683c24b/logo.png
Labels: Payment Status: Paid

#24274 Add EG Token (BEP20). Upgrade from existing ELONGATE token
  blockchains/smartchain/assets/0x74AFe449D1BEFfc90456CfEbD700AB391abD7DAF/info.json
  blockchains/smartchain/assets/0x74AFe449D1BEFfc90456CfEbD700AB391abD7DAF/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24291 Add Okcash - OK token (BEP20) (POLYGON) (ERC20) (AVALANCHE) (ARBITRUM) (OPTIMISM) (FANTOM)
  blockchains/arbitrum/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/arbitrum/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/avalanchec/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/avalanchec/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/ethereum/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/ethereum/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/fantom/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/fantom/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/optimism/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/optimism/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/polygon/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/info.json
  blockchains/polygon/assets/0xd3Ac016b1B8C80EeAdDe4D186A9138C9324e4189/logo.png
  blockchains/smartchain/assets/0x523821d20a283d955f6205B4C9252779Cd0f964B/info.json
  blockchains/smartchain/assets/0x523821d20a283d955f6205B4C9252779Cd0f964B/logo.png
Labels: Payment Status: Paid

#24305 Change DIA logo to new version
  blockchains/ethereum/assets/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419/info.json
  blockchains/ethereum/assets/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24318 Add Minions INU (BEP20) #24063
  blockchains/smartchain/assets/0xba7E2a9E5193E60368F440E4Ae881cC312d6a160/info.json
  blockchains/smartchain/assets/0xba7E2a9E5193E60368F440E4Ae881cC312d6a160/logo.png
Labels: Payment Status: Paid

#24316 Add WOR (BEP20)
  blockchains/smartchain/assets/0xd6edbB510af7901b2C049ce778b65a740c4aeB7f/info.json
  blockchains/smartchain/assets/0xd6edbB510af7901b2C049ce778b65a740c4aeB7f/logo.png
Labels: Payment Status: Paid

#24333 Add ECLAT (BEP20)
  blockchains/smartchain/assets/0xaE90CA218f9c3b1AA84af33A7907E4890Ec6A167/info.json
  blockchains/smartchain/assets/0xaE90CA218f9c3b1AA84af33A7907E4890Ec6A167/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24335 Migration for Zedxion (TRC20)
  blockchains/tron/assets/TMNTn2uFAHhkGE3uuM84rhfRRjt6ry9xnL/info.json
  blockchains/tron/assets/TUP3g7kbaESRFRhULeA19USSrcVBEpWLVY/info.json
  blockchains/tron/assets/TUP3g7kbaESRFRhULeA19USSrcVBEpWLVY/logo.png
Labels: Payment Status: Paid

#24341 Migration for Landshare (BEP20)
  blockchains/smartchain/assets/0x9D986A3f147212327Dd658F712d5264a73a1fdB0/info.json
  blockchains/smartchain/assets/0x9D986A3f147212327Dd658F712d5264a73a1fdB0/logo.png
Labels: Payment Status: Paid

#24334 Add Landshare Token (BEP20)
  blockchains/smartchain/assets/0xA73164DB271931CF952cBaEfF9E8F5817b42fA5C/info.json
  blockchains/smartchain/assets/0xA73164DB271931CF952cBaEfF9E8F5817b42fA5C/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24424 Add Arbitrum (ERC20) (ARBITRUM)
  blockchains/arbitrum/assets/0x912CE59144191C1204E64559FE8253a0e49E6548/info.json
  blockchains/arbitrum/assets/0x912CE59144191C1204E64559FE8253a0e49E6548/logo.png
  blockchains/ethereum/assets/0xB50721BCf8d664c30412Cfbc6cf7a15145234ad1/info.json
  blockchains/ethereum/assets/0xB50721BCf8d664c30412Cfbc6cf7a15145234ad1/logo.png
Labels: Payment Status: Paid

#24430 Add Space ID (ERC20) (BEP20)
  blockchains/ethereum/assets/0x2dfF88A56767223A5529eA5960Da7A3F5f766406/info.json
  blockchains/ethereum/assets/0x2dfF88A56767223A5529eA5960Da7A3F5f766406/logo.png
  blockchains/smartchain/assets/0x2dfF88A56767223A5529eA5960Da7A3F5f766406/info.json
  blockchains/smartchain/assets/0x2dfF88A56767223A5529eA5960Da7A3F5f766406/logo.png
Labels: Payment Status: Paid

#24452 New PR needed for Migration of PR (#12009)
  blockchains/ethereum/assets/0x5919DeA604631016c15c805e3D948A0384879892/info.json
  blockchains/ethereum/assets/0x5919DeA604631016c15c805e3D948A0384879892/logo.png
  blockchains/ethereum/assets/0xe1030B48b2033314979143766d7dC1F40ef8CE11/info.json
  blockchains/ethereum/assets/0xe1030B48b2033314979143766d7dC1F40ef8CE11/logo.png
Labels: Payment Status: Paid

#24482 Migration for Luffy (ERC20)
  blockchains/ethereum/assets/0x7121D00b4fA18F13Da6c2e30d19C04844E6AfDC8/info.json
  blockchains/ethereum/assets/0x7121D00b4fA18F13Da6c2e30d19C04844E6AfDC8/logo.png
Labels: Payment Status: Paid

#24478 Add TWT Logo and info - remove the old one
  blockchains/ethereum/assets/0x54012cDF4119DE84218F7EB90eEB87e25aE6EBd7/info.json
  blockchains/ethereum/assets/0x54012cDF4119DE84218F7EB90eEB87e25aE6EBd7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24485 Update explorer for Polygon zkEVM
  blockchains/polygonzkevm/info/info.json
Labels: Payment Status: Paid

#24481 Update PEEPS to match migration tokenomics
  blockchains/ethereum/assets/0x5919DeA604631016c15c805e3D948A0384879892/info.json
  blockchains/ethereum/assets/0xe1030B48b2033314979143766d7dC1F40ef8CE11/info.json
Labels: Payment Status: Paid

#24497 Update CZUSD (paid previously)
  blockchains/smartchain/assets/0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70/info.json
  blockchains/smartchain/assets/0xE68b79e51bf826534Ff37AA9CeE71a3842ee9c70/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24504 Update CELO decimals to 18
  blockchains/celo/info/info.json
Labels: Payment Status: Requested

#24505 Upload mclaren logo
  dapps/mclaren.png
Labels: Payment Status: Paid, Payment Status: Requested

#24487 Added RDNT v2 on BSC
  blockchains/smartchain/assets/0xf7DE7E8A6bd59ED41a4b5fe50278b3B7f31384dF/info.json
  blockchains/smartchain/assets/0xf7DE7E8A6bd59ED41a4b5fe50278b3B7f31384dF/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#24509 Fix staking-native
  blockchains/cardano/info/info.json
  blockchains/evmos/info/info.json
  blockchains/nativeevmos/info/info.json
  blockchains/polkadot/info/info.json
  blockchains/terra/info/info.json
Labels: Payment Status: Requested

#24503 Add JESUSisLORD LUNC Staking Validator
  blockchains/terra/validators/assets/terravaloper16e0s5t7q69elnlchrupryw3h7vu8zk23pe5wh8/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#24506 Add QLINDO ERC-20 token.
  blockchains/ethereum/assets/0xC18c07a18198A6340cf4d94855fE5eb6DD33b46E/info.json
  blockchains/ethereum/assets/0xC18c07a18198A6340cf4d94855fE5eb6DD33b46E/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24516 Add PolkaBridge (BEP20)
  blockchains/smartchain/assets/0x1D1cB8997570e73949930c01Fe5796C88d7336c6/info.json
  blockchains/smartchain/assets/0x1D1cB8997570e73949930c01Fe5796C88d7336c6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
