Repository trustwallet/assets, pull requests merged in 2023-05, with the labels that each got.

#24835 Add Pollen (AVALANCHE)
  blockchains/avalanchec/assets/0x7b2B702706D9b361dfE3f00bD138C0CFDA7FB2Cf/info.json
  blockchains/avalanchec/assets/0x7b2B702706D9b361dfE3f00bD138C0CFDA7FB2Cf/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24862 Add Oggy Inu (BEP20)
  blockchains/smartchain/assets/0x92eD61FB8955Cc4e392781cB8b7cD04AADc43D0c/info.json
  blockchains/smartchain/assets/0x92eD61FB8955Cc4e392781cB8b7cD04AADc43D0c/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24884 Add Trillioner (BEP20)
  blockchains/smartchain/assets/0x29A5DaF6E3FDF964DEf07706eA1ABee7EC03D021/info.json
  blockchains/smartchain/assets/0x29A5DaF6E3FDF964DEf07706eA1ABee7EC03D021/logo.png
Labels: Payment Status: Paid

#24886 Add FRZ Solar System Coin (BEP20)
  blockchains/smartchain/assets/0xFbDB1Fa163a0e8d90DD88104F44C093882A71914/info.json
  blockchains/smartchain/assets/0xFbDB1Fa163a0e8d90DD88104F44C093882A71914/logo.png
Labels: Payment Status: Paid

#24907 Add top SUI validators
  blockchains/sui/validators/assets/0x184fbf9d6c2d2d3f27e27fe3ca2d3b4080bd406221e345e2d36633e638e988e1/logo.png
  blockchains/sui/validators/assets/0x4f9791d5c689306862b4eb9a25914c5433b7dfd5cb4827b461f7dfc813f28a7c/logo.png
  blockchains/sui/validators/assets/0x4fffd0005522be4bc029724c7f0f6ed7093a6bf3a09b90e62f61dc15181e1a3e/logo.png
  blockchains/sui/validators/assets/0x60ce054d9dc5771fcbeb9a52a1881a97d3092efc8eb29befc3e60281dbe80ca0/logo.png
  blockchains/sui/validators/assets/0x61953ea72709eed72f4441dd944eec49a11b4acabfc8e04015e89c63be81b6ab/logo.png
  blockchains/sui/validators/assets/0x68cf08c4ef8b0462d8c3879f4e26cc371fbddd844650d0c41a9c3badc8104609/logo.png
  blockchains/sui/validators/assets/0x91b3d7211dbe057d02e2aa06f1cd678f1408438d494d2e783e0b67a77cca4599/logo.png
  blockchains/sui/validators/assets/0xad1ca3844353d0c1b86fea2d848fda0c62439168c29e132ef17f9964a19a551f/logo.png
  blockchains/sui/validators/assets/0xe719405821d7bd32ded86a2aed34f06f3dacd09c91241ec3f34b219ebeddc6f0/logo.png
  blockchains/sui/validators/assets/0xec73ec4d6b2a9403937b12ca625f7b3124c4459ff4e3caae6cf6376edefb9f3a/logo.png
  blockchains/sui/validators/list.json
Labels: Payment Status: Paid

#24912 Add tokens from top exchanges
  blockchains/arbitrum/assets/0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E/info.json
  blockchains/arbitrum/assets/0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E/logo.png
  blockchains/ethereum/assets/0x91Af0fBB28ABA7E31403Cb457106Ce79397FD4E6/info.json
  blockchains/ethereum/assets/0x91Af0fBB28ABA7E31403Cb457106Ce79397FD4E6/logo.png
  blockchains/ethereum/assets/0xA0Ef786Bf476fE0810408CaBA05E536aC800ff86/info.json
  blockchains/ethereum/assets/0xA0Ef786Bf476fE0810408CaBA05E536aC800ff86/logo.png
  blockchains/ethereum/assets/0xAaEf88cEa01475125522e117BFe45cF32044E238/info.json
  blockchains/ethereum/assets/0xAaEf88cEa01475125522e117BFe45cF32044E238/logo.png
  blockchains/smartchain/assets/0x4e2434294a722329B6B64e0c2Fca51B2533D7015/info.json
  blockchains/smartchain/assets/0x4e2434294a722329B6B64e0c2Fca51B2533D7015/logo.png
  blockchains/smartchain/assets/0xf9c27de474ccE832fAD75107853b78838888ac11/info.json
  blockchains/smartchain/assets/0xf9c27de474ccE832fAD75107853b78838888ac11/logo.png
Labels: Payment Status: Paid

#24917 Add TURBO(ERC20)
  blockchains/ethereum/assets/0xA35923162C49cF95e6BF26623385eb431ad920D3/info.json
  blockchains/ethereum/assets/0xA35923162C49cF95e6BF26623385eb431ad920D3/logo.png
Labels: Payment Status: Paid

#24955 Add tokens from top exchanges
  blockchains/arbitrum/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/info.json
  blockchains/arbitrum/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/logo.png
  blockchains/avalanchec/assets/0xc4B06F17ECcB2215a5DBf042C672101Fc20daF55/info.json
  blockchains/avalanchec/assets/0xc4B06F17ECcB2215a5DBf042C672101Fc20daF55/logo.png
  blockchains/ethereum/assets/0x65Ef703f5594D2573eb71Aaf55BC0CB548492df4/info.json
  blockchains/ethereum/assets/0x65Ef703f5594D2573eb71Aaf55BC0CB548492df4/logo.png
  blockchains/fantom/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/info.json
  blockchains/fantom/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/logo.png
  blockchains/polygon/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/info.json
  blockchains/polygon/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/logo.png
  blockchains/smartchain/assets/0x16E79E09b3B56BCBBA83667aFf88dc6ca727Af2e/info.json
  blockchains/smartchain/assets/0x16E79E09b3B56BCBBA83667aFf88dc6ca727Af2e/logo.png
  blockchains/smartchain/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/info.json
  blockchains/smartchain/assets/0x9Fb9a33956351cf4fa040f65A13b835A3C8764E3/logo.png
Labels: Payment Status: Paid

#24920 Add MMIT LOGO reference #24564 #24733
  blockchains/smartchain/assets/0x9767c8E438Aa18f550208e6d1fDf5f43541cC2c8/info.json
  blockchains/smartchain/assets/0x9767c8E438Aa18f550208e6d1fDf5f43541cC2c8/logo.png
Labels: Payment Status: Paid, Under Review

#24950 Add BemChain (TRC20)
  blockchains/tron/assets/TAoA331n3iKDkR62kAZ4H2n3vNL7y3d8x9/info.json
  blockchains/tron/assets/TAoA331n3iKDkR62kAZ4H2n3vNL7y3d8x9/logo.png
Labels: Status: On Hold, Payment Status: Paid

#24963 Add SUI tokens
  blockchains/neutron/info/info.json
  blockchains/neutron/info/logo.png
  blockchains/smartchain/assets/0x9767c8E438Aa18f550208e6d1fDf5f43541cC2c8/info.json
  blockchains/sui/assets/0xb231fcda8bbddb31f2ef02e6161444aec64a514e2c89279584ac9806ce9cf037::coin::COIN/info.json
  blockchains/sui/assets/0xb231fcda8bbddb31f2ef02e6161444aec64a514e2c89279584ac9806ce9cf037::coin::COIN/logo.png
  blockchains/sui/assets/0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN/info.json
  blockchains/sui/assets/0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN/logo.png
  blockchains/sui/assets/0xebbf537bc3686be32fe22b498b42715641bbb209267be72236a352e0444cc5df::sui_pepe::SUI_PEPE/info.json
  blockchains/sui/assets/0xebbf537bc3686be32fe22b498b42715641bbb209267be72236a352e0444cc5df::sui_pepe::SUI_PEPE/logo.png
Labels: Payment Status: Paid

#24991 Add BEN and BONE tokens (ERC20)
  blockchains/ethereum/assets/0x9813037ee2218799597d83D4a5B6F3b6778218d9/info.json
  blockchains/ethereum/assets/0x9813037ee2218799597d83D4a5B6F3b6778218d9/logo.png
  blockchains/ethereum/assets/0x9bf1D7D63dD7a4ce167CF4866388226EEefa702E/info.json
  blockchains/ethereum/assets/0x9bf1D7D63dD7a4ce167CF4866388226EEefa702E/logo.png
Labels: Payment Status: Paid

#24996 Add trending tokens
  blockchains/ethereum/assets/0x1A963Df363D01EEBB2816b366d61C917F20e1EbE/info.json
  blockchains/ethereum/assets/0x1A963Df363D01EEBB2816b366d61C917F20e1EbE/logo.png
  blockchains/ethereum/assets/0x1ce270557C1f68Cfb577b856766310Bf8B47FD9C/info.json
  blockchains/ethereum/assets/0x1ce270557C1f68Cfb577b856766310Bf8B47FD9C/logo.png
  blockchains/ethereum/assets/0x5026F006B85729a8b14553FAE6af249aD16c9aaB/info.json
  blockchains/ethereum/assets/0x5026F006B85729a8b14553FAE6af249aD16c9aaB/logo.png
  blockchains/ethereum/assets/0x7D8146cf21e8D7cbe46054e01588207b51198729/info.json
  blockchains/ethereum/assets/0x7D8146cf21e8D7cbe46054e01588207b51198729/logo.png
Labels: Payment Status: Paid

#24631 Add Symbiosis (BEP20)
  blockchains/smartchain/assets/0xF98b660AdF2ed7d9d9D9dAACC2fb0CAce4F21835/info.json
  blockchains/smartchain/assets/0xF98b660AdF2ed7d9d9D9dAACC2fb0CAce4F21835/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#24994 Fix info and logo for Neutron
  blockchains/neutron/info/info.json
  blockchains/neutron/info/logo.png
Labels: Payment Status: Paid

#25042 Change status for TRX
  blockchains/ethereum/assets/0xf230b790E05390FC8295F4d3F60332c93BEd42e2/info.json
Labels: Payment Status: Paid

#25005 Add Jerry Inu (BEP20)
  blockchains/smartchain/assets/0xdd6978F36c98AfF4287E5ac803C9CF1b865641F6/info.json
  blockchains/smartchain/assets/0xdd6978F36c98AfF4287E5ac803C9CF1b865641F6/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25043 Add The DONS (BEP20)
  blockchains/smartchain/assets/0x95c91eEf65F50570cFC3f269961a00108Cf7BF59/info.json
  blockchains/smartchain/assets/0x95c91eEf65F50570cFC3f269961a00108Cf7BF59/logo.png
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#25065 Add trending tokens
  blockchains/ethereum/assets/0x12970E6868f88f6557B76120662c1B3E50A646bf/info.json
  blockchains/ethereum/assets/0x12970E6868f88f6557B76120662c1B3E50A646bf/logo.png
  blockchains/ethereum/assets/0xCEBA2a8F6Ec221AEB5f3a7bcd15Cbc7e6a387bfb/info.json
  blockchains/ethereum/assets/0xCEBA2a8F6Ec221AEB5f3a7bcd15Cbc7e6a387bfb/logo.png
  blockchains/smartchain/assets/0x7704d0EaD6F74E625d7371b079D8b2475bc852d4/info.json
  blockchains/smartchain/assets/0x7704d0EaD6F74E625d7371b079D8b2475bc852d4/logo.png
  blockchains/smartchain/assets/0x818835503F55283cd51A4399f595e295A9338753/info.json
  blockchains/smartchain/assets/0x818835503F55283cd51A4399f595e295A9338753/logo.png
  blockchains/smartchain/assets/0x95c91eEf65F50570cFC3f269961a00108Cf7BF59/info.json
Labels: Payment Status: Paid

#24983 Add X AI (BEP20)
  blockchains/smartchain/assets/0xD16EaabA33a0822f5cBe4E0C63CA51D3c3fbB08B/info.json
  blockchains/smartchain/assets/0xD16EaabA33a0822f5cBe4E0C63CA51D3c3fbB08B/logo.png
Labels: Status: More Info / Change Requested, Status: On Hold, Payment Status: Paid

#25076 Add HUDI (BEP20)
  blockchains/smartchain/assets/0x83d8Ea5A4650B68Cd2b57846783d86DF940F7458/info.json
  blockchains/smartchain/assets/0x83d8Ea5A4650B68Cd2b57846783d86DF940F7458/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#24873 Add DragonKing (BEP20)
  blockchains/smartchain/assets/0x11aC6aF070Fe1991a457c56FB85c577EFE57F0e4/info.json
  blockchains/smartchain/assets/0x11aC6aF070Fe1991a457c56FB85c577EFE57F0e4/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25041 Add NOOT (BEP20)
  blockchains/smartchain/assets/0x98A2500A2C3B8877B0eD5ac3ACC300C50Bf7064b/info.json
  blockchains/smartchain/assets/0x98A2500A2C3B8877B0eD5ac3ACC300C50Bf7064b/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25088 Add ADD FINANCE (BEP20)
  blockchains/smartchain/assets/0xc30C95205C7BC70D81da8e852255Cc89B90480f7/info.json
  blockchains/smartchain/assets/0xc30C95205C7BC70D81da8e852255Cc89B90480f7/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25125 Add tokens from exchanges & trending tokens
  blockchains/arbitrum/assets/0x040d1EdC9569d4Bab2D15287Dc5A4F10F56a56B8/info.json
  blockchains/arbitrum/assets/0x040d1EdC9569d4Bab2D15287Dc5A4F10F56a56B8/logo.png
  blockchains/arbitrum/assets/0xa0b862F60edEf4452F25B4160F177db44DeB6Cf1/info.json
  blockchains/arbitrum/assets/0xa0b862F60edEf4452F25B4160F177db44DeB6Cf1/logo.png
  blockchains/ethereum/assets/0x8Fc8f8269ebca376D046Ce292dC7eaC40c8D358A/info.json
  blockchains/ethereum/assets/0x8Fc8f8269ebca376D046Ce292dC7eaC40c8D358A/logo.png
  blockchains/ethereum/tokenlist.json
  blockchains/optimism/assets/0xFE8B128bA8C78aabC59d4c64cEE7fF28e9379921/info.json
  blockchains/optimism/assets/0xFE8B128bA8C78aabC59d4c64cEE7fF28e9379921/logo.png
  blockchains/smartchain/assets/0x361C60b7c2828fCAb80988d00D1D542c83387b50/info.json
  blockchains/smartchain/assets/0x361C60b7c2828fCAb80988d00D1D542c83387b50/logo.png
  blockchains/smartchain/assets/0x7E60C74b9096f8FA6fb5a9FD88405dED8B7D44f3/info.json
  blockchains/smartchain/assets/0x7cF551258d6871b72EE1bD1624588a6245bF48c4/info.json
  blockchains/smartchain/assets/0x7cF551258d6871b72EE1bD1624588a6245bF48c4/logo.png
Labels: Payment Status: Paid

#24630 Add Symbiosis Finance (SIS) (ERC20)
  blockchains/ethereum/assets/0xd38BB40815d2B0c2d2c866e0c72c5728ffC76dd9/info.json
  blockchains/ethereum/assets/0xd38BB40815d2B0c2d2c866e0c72c5728ffC76dd9/logo.png
Labels: Payment Status: Paid

#25116 Add Pepe AI (BEP20)
  blockchains/smartchain/assets/0xe57F73EB27Da9D17f90C994744D842e95700C100/info.json
  blockchains/smartchain/assets/0xe57F73EB27Da9D17f90C994744D842e95700C100/logo.png
Labels: Payment Status: Paid

#25157 Add IL CAPO (BEP20)
  blockchains/smartchain/assets/0x922722E9Ef614EC9A3E94b78496e92AbFBb5A624/info.json
  blockchains/smartchain/assets/0x922722E9Ef614EC9A3E94b78496e92AbFBb5A624/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25124 Add MuratiAI (BEP20)
  blockchains/smartchain/assets/0x69C2fcAe7e30b429166BD616A322e32BeC036bCf/info.json
  blockchains/smartchain/assets/0x69C2fcAe7e30b429166BD616A322e32BeC036bCf/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#25188 Add validators for Stride
  blockchains/stride/validators/assets/stride1624f0qe76yhnwvlwp3ury2r2xh6cqemmz75myu/logo.png
  blockchains/stride/validators/assets/stride19nktvlnhd7j2tsyt97jyfnv3kdemx8cq9ls0ym/logo.png
  blockchains/stride/validators/assets/stride1dae4zycvmyd2qt5td9zzgdjdnwyawp79mp0q4a/logo.png
  blockchains/stride/validators/assets/stride1dqpg0hfva0k0awzhxwarjpgzj82hlmvrsnm7ug/logo.png
  blockchains/stride/validators/assets/stride1dtqsnk3mlqrcxgfvu39lm0jm3pyd0mkrcajj4a/logo.png
  blockchains/stride/validators/assets/stride1gp957czryfgyvxwn3tfnyy2f0t9g2p4pxxdj7c/logo.png
  blockchains/stride/validators/assets/stride1jj9z2xwxesuy65n90dujsak554eqkrr2ygyan2/logo.png
  blockchains/stride/validators/assets/stride1kvwpcr45lh7wn53wp9ac42ypr3t8zjqyer5e3e/logo.png
  blockchains/stride/validators/assets/stride1md2j38ls8hg94vjfafu0a2p9htwlkjmhlnp9ef/logo.png
  blockchains/stride/validators/assets/stride1x0agh4jnvamn6y5ss94s6ktugwkljp6yf7jwrt/logo.png
  blockchains/stride/validators/list.json
Labels: Payment Status: Paid

#25189 Strd validators fix
  blockchains/stride/validators/list.json
Labels: Payment Status: Requested

#25192 Fix STRD logo validators
  blockchains/stride/validators/assets/stridevaloper1624f0qe76yhnwvlwp3ury2r2xh6cqemmpts8ge/logo.png
  blockchains/stride/validators/assets/stridevaloper19nktvlnhd7j2tsyt97jyfnv3kdemx8cqx25ng7/logo.png
  blockchains/stride/validators/assets/stridevaloper1dae4zycvmyd2qt5td9zzgdjdnwyawp79c5tuec/logo.png
  blockchains/stride/validators/assets/stridevaloper1dqpg0hfva0k0awzhxwarjpgzj82hlmvrnxlzsd/logo.png
  blockchains/stride/validators/assets/stridevaloper1dtqsnk3mlqrcxgfvu39lm0jm3pyd0mkrmgkwec/logo.png
  blockchains/stride/validators/assets/stridevaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4p9nfwja/logo.png
  blockchains/stride/validators/assets/stridevaloper1jj9z2xwxesuy65n90dujsak554eqkrr28aqpl0/logo.png
  blockchains/stride/validators/assets/stridevaloper1kvwpcr45lh7wn53wp9ac42ypr3t8zjqy6ks9au/logo.png
  blockchains/stride/validators/assets/stridevaloper1md2j38ls8hg94vjfafu0a2p9htwlkjmhux9e4v/logo.png
  blockchains/stride/validators/assets/stridevaloper1x0agh4jnvamn6y5ss94s6ktugwkljp6y2tkj0w/logo.png
Labels: Payment Status: Paid

#25233 chore: update Ben logo
  blockchains/ethereum/assets/0x9bf1D7D63dD7a4ce167CF4866388226EEefa702E/logo.png
Labels: Status: On Hold, Payment Status: Paid

#25242 Add Ignore Fud (BEP20)
  blockchains/smartchain/assets/0x61B83eDF87Ea662C695439A807c386455c9E797C/info.json
  blockchains/smartchain/assets/0x61B83eDF87Ea662C695439A807c386455c9E797C/logo.png
Labels: Payment Status: Paid

#25229 Add Minto (BEP20)
  blockchains/smartchain/assets/0x410a56541bD912F9B60943fcB344f1E3D6F09567/info.json
  blockchains/smartchain/assets/0x410a56541bD912F9B60943fcB344f1E3D6F09567/logo.png
Labels: Payment Status: Paid

#25270 Add Symbiosis (SIS) (ZKSYNC)
  blockchains/zksync/assets/0xdd9f72afED3631a6C85b5369D84875e6c42f1827/info.json
  blockchains/zksync/assets/0xdd9f72afED3631a6C85b5369D84875e6c42f1827/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#25254 Add STRIDE tokens
  blockchains/stride/assets/staevmos/info.json
  blockchains/stride/assets/staevmos/logo.png
  blockchains/stride/assets/stinj/info.json
  blockchains/stride/assets/stinj/logo.png
  blockchains/stride/assets/stuatom/info.json
  blockchains/stride/assets/stuatom/logo.png
  blockchains/stride/assets/stujuno/info.json
  blockchains/stride/assets/stujuno/logo.png
  blockchains/stride/assets/stuluna/info.json
  blockchains/stride/assets/stuluna/logo.png
  blockchains/stride/assets/stuosmo/info.json
  blockchains/stride/assets/stuosmo/logo.png
  blockchains/stride/assets/stustars/info.json
  blockchains/stride/assets/stustars/logo.png
  blockchains/stride/assets/stuumee/info.json
  blockchains/stride/assets/stuumee/logo.png
Labels: Payment Status: Paid
