Repository trustwallet/assets, pull requests merged in 2023-01, with the labels that each got.

#23591 Add WEB5 Inu (BEP20)
  blockchains/smartchain/assets/0x7d220240Cf958C5c47f2DAAC821dB965f9837e82/info.json
  blockchains/smartchain/assets/0x7d220240Cf958C5c47f2DAAC821dB965f9837e82/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23595 Listing new Dapp PRDT
  dapps/prdt.finance.png
Labels: Payment Status: Paid, Payment Status: Requested

#23604 update linter version
  Makefile
Labels: Payment Status: Requested

#23602 Add New Terra Classic Validator Classy's Sphere 🔮 | 0% Fees
  blockchains/terra/validators/assets/terravaloper14xjkj5rv72fgqz3h78l883rw0njwhmzce45006/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23612 Add GroveCoin (BEP20)
  blockchains/smartchain/assets/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c/info.json
  blockchains/smartchain/assets/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c/logo.png
Labels: Payment Status: Paid

#23606 Add Grove Token (ERC20)
  blockchains/ethereum/assets/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c/info.json
  blockchains/ethereum/assets/0xF33893DE6eB6aE9A67442E066aE9aBd228f5290c/logo.png
Labels: Payment Status: Paid

#23613 Migration for Grove (ERC20) (BEP20)
  blockchains/ethereum/assets/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e/info.json
  blockchains/ethereum/assets/0x84FA8f52E437Ac04107EC1768764B2b39287CB3e/logo.png
  blockchains/smartchain/assets/0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB/info.json
  blockchains/smartchain/assets/0xaFb64E73dEf6fAa8B6Ef9a6fb7312d5C4C15ebDB/logo.png
Labels: Payment Status: Paid

#23597 Add Agoric info
  blockchains/agoric/info/info.json
  blockchains/agoric/info/logo.png
Labels: Payment Status: Requested

#23053 Add Magpie Token (BEP20)
  blockchains/smartchain/assets/0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa/info.json
  blockchains/smartchain/assets/0xD06716E1Ff2E492Cc5034c2E81805562dd3b45fa/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23624 BUSD Token (BUSD) TRC20
  blockchains/tron/assets/TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH/info.json
  blockchains/tron/assets/TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH/logo.png
Labels: Payment Status: Paid

#23626 BIRB token migration
  blockchains/smartchain/assets/0x2e8799f0A26d8A9f37a0b4747Fa534f039C2d234/info.json
  blockchains/smartchain/assets/0x2e8799f0A26d8A9f37a0b4747Fa534f039C2d234/logo.png
  blockchains/smartchain/assets/0x88888888Fc33e4ECba8958c0c2AD361089E19885/info.json
  blockchains/smartchain/assets/0x88888888Fc33e4ECba8958c0c2AD361089E19885/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23647 Add Bonk (SPL)
  blockchains/solana/assets/DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263/info.json
  blockchains/solana/assets/DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263/logo.png
Labels: Payment Status: Paid

#23654 Add SquidGrow (SquidGrow) (ERC20)
  blockchains/ethereum/assets/0x88479186BAC914E4313389a64881F5ed0153C765/info.json
  blockchains/ethereum/assets/0x88479186BAC914E4313389a64881F5ed0153C765/logo.png
Labels: Payment Status: Paid

#23667 Fix logo and name for SquidGrow
  blockchains/ethereum/assets/0x88479186BAC914E4313389a64881F5ed0153C765/info.json
  blockchains/smartchain/assets/0x88479186BAC914E4313389a64881F5ed0153C765/logo.png
Labels: Payment Status: Paid

#23648 Add Injective logo and info
  blockchains/injective/info/info.json
  blockchains/injective/info/logo.png
Labels: Payment Status: Requested

#23685 Add hodlx update hodl
  blockchains/smartchain/assets/0x0E9766dF73973abCfEDDE700497c57110ee5c301/info.json
  blockchains/smartchain/assets/0xAeBdbcc7d6821E3924EE5167b4138a43c19Cf681/info.json
  blockchains/smartchain/assets/0xAeBdbcc7d6821E3924EE5167b4138a43c19Cf681/logo.png
  dapps/hodltoken.net.png
  dapps/hodlx.exchange.png
Labels: Payment Status: Paid, Payment Status: Requested

#23703 Update Logo HODLX
  blockchains/smartchain/assets/0xAeBdbcc7d6821E3924EE5167b4138a43c19Cf681/logo.png
Labels: Payment Status: Paid

#23690 Add WKC logo and info
  blockchains/smartchain/assets/0x6Ec90334d89dBdc89E08A133271be3d104128Edb/info.json
  blockchains/smartchain/assets/0x6Ec90334d89dBdc89E08A133271be3d104128Edb/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23714 Add ZAX LOGO
  blockchains/smartchain/assets/0x9A2478C4036548864d96a97Fbf93f6a3341fedac/info.json
  blockchains/smartchain/assets/0x9A2478C4036548864d96a97Fbf93f6a3341fedac/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23715 Add AWC Token (BEP20)
  blockchains/smartchain/assets/0x798aF7725376765e7F3cA86d5e0Cf1BEaEf19F34/info.json
  blockchains/smartchain/assets/0x798aF7725376765e7F3cA86d5e0Cf1BEaEf19F34/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23721 Add dapps surnft
  dapps/surnft.com.png
Labels: Payment Status: Paid

#23730 Update ZAX LOGO
  blockchains/smartchain/assets/0x9A2478C4036548864d96a97Fbf93f6a3341fedac/info.json
  blockchains/smartchain/assets/0x9A2478C4036548864d96a97Fbf93f6a3341fedac/logo.png
Labels: Payment Status: Paid

#23734 Add Lunc validator
  blockchains/terra/validators/assets/terravaloper1der0lqp4grpnmpuefhwlj72fzccqmhmwgjh6ys/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid

#23706 Add ATR (BEP20)
  blockchains/smartchain/assets/0x7559C49c3Aec50E763A486bB232fA8d0d76078e4/info.json
  blockchains/smartchain/assets/0x7559C49c3Aec50E763A486bB232fA8d0d76078e4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23740 Update tokenlist
  blockchains/smartchain/tokenlist.json
Labels: Payment Status: Paid

#23742 Add gmx dapps
  dapps/gmx.io.png
Labels: Payment Status: Paid

#23739 Add BTP logo & info.
  blockchains/smartchain/assets/0x40F75eD09c7Bc89Bf596cE0fF6FB2ff8D02aC019/info.json
  blockchains/smartchain/assets/0x40F75eD09c7Bc89Bf596cE0fF6FB2ff8D02aC019/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23762 Add Defi Tiger Logo and Info
  blockchains/smartchain/assets/0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6/info.json
  blockchains/smartchain/assets/0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23787 Change status for Chia
  blockchains/smartchain/assets/0x611DFe661C82B858087AB5b16e3Cb082552df4F3/info.json
  blockchains/smartchain/assets/0x611DFe661C82B858087AB5b16e3Cb082552df4F3/logo.png
Labels: Payment Status: Paid

#23789 Add Atomic Nodes Terra Validator
  blockchains/terra/validators/assets/terravaloper1fuk24ujq5e7zrj7st2m4wvgczdfchhzm5f2ml0/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23802 Add CORE to chainlist
  blockchains/ethereum/chainlist.json
Labels: Payment Status: Paid

#23829 Add Index Coop's Diversified Staked ETH Index
  blockchains/ethereum/assets/0x341c05c0E9b33C0E38d64de76516b2Ce970bB3BE/info.json
  blockchains/ethereum/assets/0x341c05c0E9b33C0E38d64de76516b2Ce970bB3BE/logo.png
Labels: Payment Status: Paid

#23814 added dankuzone w/ DAIC cosmos, osmosis and terra validators
  blockchains/cosmos/validators/assets/cosmosvaloper140e7u946a2nqqkvcnjpjm83d0ynsqem8dnp684/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1cwurrzatev9lfkn3ak6hh59t6yc0zy00rzp8yd/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/terra/validators/assets/terravaloper12r8929na0amxfj406zw7vk8jmd03fmzcj9r2gg/logo.png
  blockchains/terra/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23812 PLEASE ADD BLOCKCHAIN AND COIN ON TRUSTWALLET
  blockchains/info.json
  blockchains/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23791 Add SingularityDAO
  blockchains/ethereum/assets/0x7bb1A6b19e37028B3aA5c580339c640720E35203/info.json
  blockchains/ethereum/assets/0x7bb1A6b19e37028B3aA5c580339c640720E35203/logo.png
  blockchains/ethereum/assets/0x976a95786DA6f6eE1c0755cCFB9A22adac2BF7B2/info.json
  blockchains/ethereum/assets/0x976a95786DA6f6eE1c0755cCFB9A22adac2BF7B2/logo.png
  blockchains/ethereum/assets/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F/info.json
  blockchains/ethereum/assets/0x993864E43Caa7F7F12953AD6fEb1d1Ca635B875F/logo.png
  blockchains/ethereum/assets/0xDa49AF8773Cb162ca56f8431442c750896F8C87A/info.json
  blockchains/ethereum/assets/0xDa49AF8773Cb162ca56f8431442c750896F8C87A/logo.png
  blockchains/ethereum/assets/0xbBbfa5d0Bfd30B9ebce64b06E3E9Fc85E7f0F396/info.json
  blockchains/ethereum/assets/0xbBbfa5d0Bfd30B9ebce64b06E3E9Fc85E7f0F396/logo.png
  blockchains/smartchain/assets/0x5569B42513203f49a761Cc9720D4Bb9B6b9E5AB8/info.json
  blockchains/smartchain/assets/0x5569B42513203f49a761Cc9720D4Bb9B6b9E5AB8/logo.png
  blockchains/smartchain/assets/0x90Ed8F1dc86388f14b64ba8fb4bbd23099f18240/info.json
  blockchains/smartchain/assets/0x90Ed8F1dc86388f14b64ba8fb4bbd23099f18240/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23859 Update tokenlist tron
  blockchains/tron/tokenlist.json
Labels: Payment Status: Paid

#23857 Add Pleasure Coin also to ethereum
  blockchains/ethereum/assets/0x8f006D1e1D9dC6C98996F50a4c810F17a47fBF19/info.json
  blockchains/ethereum/assets/0x8f006D1e1D9dC6C98996F50a4c810F17a47fBF19/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23831 Add Ethereum Swarm
  blockchains/ethereum/assets/0x19062190B1925b5b6689D7073fDfC8c2976EF8Cb/info.json
  blockchains/ethereum/assets/0x19062190B1925b5b6689D7073fDfC8c2976EF8Cb/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23863 Migration for Thoreum (BEP20)
  blockchains/smartchain/assets/0xF2A92BC1Cf798fF4De14502a9C6FdA58865e8D5d/info.json
  blockchains/smartchain/assets/0xF2A92BC1Cf798fF4De14502a9C6FdA58865e8D5d/logo.png
Labels: Payment Status: Paid

#23864 Migration for Thoreum(BEP20)
  blockchains/smartchain/assets/0xCE1b3e5087e8215876aF976032382dd338cF8401/info.json
  blockchains/smartchain/assets/0xCE1b3e5087e8215876aF976032382dd338cF8401/logo.png
Labels: Payment Status: Paid

#23865 Add Atomic Nodes Cardano Validator
  blockchains/cardano/validators/assets/pool15wkxegrfflzcyhurrjxsm9ljqtz09xr5rtnqsarnp7hmsz5um3t/logo.png
  blockchains/cardano/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#23851 Add OFE Token from MultiversX (old Elrond)
  blockchains/elrond/assets/OFE-29eb54/info.json
  blockchains/elrond/assets/OFE-29eb54/logo.png
Labels: Status: On Hold, Payment Status: Paid, Payment Status: Requested

#23873 [Blockchain]: Add Sui
  blockchains/sui/info/info.json
  blockchains/sui/info/logo.png
Labels: Payment Status: Requested

#23868 Add LUCRO (BEP20)
  blockchains/smartchain/assets/0x988F7c894e4001EEB7B570CDE80dffE21CF7B6B9/info.json
  blockchains/smartchain/assets/0x988F7c894e4001EEB7B570CDE80dffE21CF7B6B9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#23872 Add EverGrow Coin (BEP20)
  blockchains/smartchain/assets/0xC001BBe2B87079294C63EcE98BdD0a88D761434e/info.json
  blockchains/smartchain/assets/0xC001BBe2B87079294C63EcE98BdD0a88D761434e/logo.png
Labels: Payment Status: Paid

#23869 Add CATVILLS (BEP20)
  blockchains/smartchain/assets/0xa531a733070a5fF4866D1327d82e403Fa35290A6/info.json
  blockchains/smartchain/assets/0xa531a733070a5fF4866D1327d82e403Fa35290A6/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23886 Add USDZ (ERC20)
  blockchains/ethereum/assets/0x0a661F6AD63a1500D714ED1EeEdb64ec493a54A8/info.json
  blockchains/ethereum/assets/0x0a661F6AD63a1500D714ED1EeEdb64ec493a54A8/logo.png
Labels: Payment Status: Paid

#23894 Migration for Hyper
  blockchains/smartchain/assets/0x0469F8Ca65Ce318888cc0d6459d0c7cbe5912c98/info.json
  blockchains/smartchain/assets/0x0469F8Ca65Ce318888cc0d6459d0c7cbe5912c98/logo.png
Labels: Payment Status: Paid

#23888 Add HyperChainX (BEP20)
  blockchains/smartchain/assets/0xEE5b03b769Ca6c690D140CafB52fC8de3f38FC28/info.json
  blockchains/smartchain/assets/0xEE5b03b769Ca6c690D140CafB52fC8de3f38FC28/logo.png
Labels: Status: On Hold, Payment Status: Paid

#23903 Add NEST Token information and Logo
  blockchains/smartchain/assets/0x98f8669F6481EbB341B522fCD3663f79A3d1A6A7/info.json
  blockchains/smartchain/assets/0x98f8669F6481EbB341B522fCD3663f79A3d1A6A7/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#23913 Add Aptos tokens
  blockchains/aptos/assets/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948:lp_coin:LP/info.json
  blockchains/aptos/assets/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948:lp_coin:LP/logo.png
  blockchains/aptos/assets/0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5:staked_coin:StakedAptos/info.json
  blockchains/aptos/assets/0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5:staked_coin:StakedAptos/logo.png
Labels: Payment Status: Paid

#23914 Remove LP (Aptos)
  blockchains/aptos/assets/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948:lp_coin:LP/info.json
  blockchains/aptos/assets/0x5a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948:lp_coin:LP/logo.png
Labels: Payment Status: Paid
