Repository trustwallet/assets, pull requests merged in 2024-11, with the labels that each got.

#29363 Add BabyCate (BEP20)
  blockchains/smartchain/assets/0x76B560b628F74BF192bE09F0449abef8e456BE79/info.json
  blockchains/smartchain/assets/0x76B560b628F74BF192bE09F0449abef8e456BE79/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28879 Add Based Chad (ERC20)
  blockchains/base/assets/0xecaF81Eb42cd30014EB44130b89Bcd6d4Ad98B92/info.json
  blockchains/base/assets/0xecaF81Eb42cd30014EB44130b89Bcd6d4Ad98B92/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#29380 Add insurance (BEP20)
  blockchains/smartchain/assets/0x64E4fea6e4F3637025c7Bcd878E2B238B01f7D4e/info.json
  blockchains/smartchain/assets/0x64E4fea6e4F3637025c7Bcd878E2B238B01f7D4e/logo.png
Labels: Payment Status: Paid

#29436 Add Panther AI (BEP20)
  blockchains/smartchain/assets/0x13a5c811093dd001C328b59a0CC9deC88951F042/info.json
  blockchains/smartchain/assets/0x13a5c811093dd001C328b59a0CC9deC88951F042/logo.png
Labels: Payment Status: Paid

#29495 add new rats_discover.png
  dapps/rats_discover.png
Labels: Payment Status: Requested

#29463 Add Benefit Mine (BEP20)
  blockchains/smartchain/assets/0xEcCA434e838eEbE30E561d0Ec3E3016efd1d340A/info.json
  blockchains/smartchain/assets/0xEcCA434e838eEbE30E561d0Ec3E3016efd1d340A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29462 Add Koma Inu (BEP20)
  blockchains/smartchain/assets/0xd5eaAaC47bD1993d661bc087E15dfb079a7f3C19/info.json
  blockchains/smartchain/assets/0xd5eaAaC47bD1993d661bc087E15dfb079a7f3C19/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29528 Add sundog icon
  dapps/sundog.png
Labels: Payment Status: Requested

#29546 Add tesa icon
  dapps/tesa.png
Labels: Payment Status: Requested

#29326 Add Pactus Blockchain
  blockchains/pactus/info/info.json
  blockchains/pactus/info/logo.png
Labels: Status: On Hold, Payment Status: Paid

#29581 add cgm icon
  dapps/cgm.discover.png
Labels: Payment Status: Requested

#29624 discover wod swap
  dapps/discover_wod.png
Labels: Payment Status: Requested

#29594 Update Moonbeam Information
  blockchains/moonbasealpha/info/info.json
  blockchains/moonbasealpha/info/logo.png
  blockchains/moonbeam/info/info.json
  blockchains/moonbeam/info/logo.png
  blockchains/moonriver/info/info.json
  blockchains/moonriver/info/logo.png
Labels: Payment Status: Requested

#29510 Add BitBonk (BEP20)
  blockchains/smartchain/assets/0xbbBBBBe1da5EAB142B32f8887EE8d3872D847c20/info.json
  blockchains/smartchain/assets/0xbbBBBBe1da5EAB142B32f8887EE8d3872D847c20/logo.png
Labels: Payment Status: Paid
