Repository trustwallet/assets, pull requests merged in 2024-08, with the labels that each got.

#28842 Add NeyroAI (NAI) (ERC20)
  blockchains/ethereum/assets/0xA74FD910a6dcC844bA42839108A7A72AA2EE2c24/info.json
  blockchains/ethereum/assets/0xA74FD910a6dcC844bA42839108A7A72AA2EE2c24/logo.png
Labels: Payment Status: Paid

#28838 Add WINPRO (BEP20)
  blockchains/smartchain/assets/0x53c17Ecaa2C662cff7C380729c7E9f7989280b2A/info.json
  blockchains/smartchain/assets/0x53c17Ecaa2C662cff7C380729c7E9f7989280b2A/logo.png
Labels: Payment Status: Paid

#28857 Add NCoin (BEP20)
  blockchains/smartchain/assets/0x4a7E278C67543731A864C89e5EB28EaCfa8794EB/info.json
  blockchains/smartchain/assets/0x4a7E278C67543731A864C89e5EB28EaCfa8794EB/logo.png
Labels: Payment Status: Paid

#28783 Add Real Smurf Cat (ERC20)
  blockchains/ethereum/assets/0xfF836A5821E69066c87E268bC51b849FaB94240C/info.json
  blockchains/ethereum/assets/0xfF836A5821E69066c87E268bC51b849FaB94240C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28835 Add Meria Validators on 10 chains.
  blockchains/akash/validators/assets/akashvaloper14mdu3xwpdr4qkayuv0aut5j6l9lgegc4hnvm9e/logo.png
  blockchains/akash/validators/list.json
  blockchains/axelar/validators/assets/axelarvaloper1aqhvg88ghtdv7du6kqlc9eccukpu8l7mhtauk5/logo.png
  blockchains/axelar/validators/list.json
  blockchains/band/validators/assets/bandvaloper1plau7keptn9qdt7nmhphltakv5t054f8lgwjdn/logo.png
  blockchains/band/validators/list.json
  blockchains/cosmos/validators/assets/cosmosvaloper1wrx0x9m9ykdhw9sg04v7uljme53wuj03aa5d4f/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/fetch/validators/assets/fetchvaloper1zntja9step52hq3a262fd9ee4n9w7mjutru8rc/logo.png
  blockchains/fetch/validators/list.json
  blockchains/kava/validators/assets/kavavaloper16l4cn6tzqm8ll7t3t8zkwd0ut3lny7dttrk0dk/logo.png
  blockchains/kava/validators/list.json
  blockchains/nativeevmos/validators/assets/evmosvaloper1hn8u6x03mklzdy69r9khsd9q4yft7gmrkz8qkj/logo.png
  blockchains/nativeevmos/validators/list.json
  blockchains/near/validators/assets/meria-staking.poolv1.near/logo.png
  blockchains/near/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper1q5xvvmf03dx8amz66ku6z0x4u39f0aphqf42wc/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/persistence/validators/assets/persistencevaloper1cp4rjdsuyhzhgvrkswsay44tt8207s487jcu59/logo.png
  blockchains/persistence/validators/list.json
Labels: Status: Correction needed, Payment Status: Paid, Payment Status: Requested

#28909 Change logo for Neiro
  blockchains/ethereum/assets/0xEE2a03Aa6Dacf51C18679C516ad5283d8E7C2637/info.json
  blockchains/ethereum/assets/0xEE2a03Aa6Dacf51C18679C516ad5283d8E7C2637/logo.png
Labels: Payment Status: Requested

#28903 Add FX Stock Token (BEP20)
  blockchains/smartchain/assets/0xA99600043E84181A9d4137aD1cefB8cfE9138674/info.json
  blockchains/smartchain/assets/0xA99600043E84181A9d4137aD1cefB8cfE9138674/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28936 Abandon old Quidax Token (QDX) Bep20
  blockchains/smartchain/assets/0x9e3a9F1612028eeE48F85cA85f8Bed2f37d76848/info.json
  blockchains/smartchain/assets/0x9e3a9F1612028eeE48F85cA85f8Bed2f37d76848/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#28980 Adding Trust logo with Ton required dims
  dapps/trust.logo.png
Labels: Payment Status: Requested

#28947 Add Paxe (BEP20)
  blockchains/smartchain/assets/0xd2A3eec06719D5Ac66248003B5488E02165dd2fa/info.json
  blockchains/smartchain/assets/0xd2A3eec06719D5Ac66248003B5488E02165dd2fa/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28943 Add BiCity AI Projects (BEP20)
  blockchains/smartchain/assets/0x6Fa9C0EE8a1F237466bB9CAc8466bFA2aA63A978/info.json
  blockchains/smartchain/assets/0x6Fa9C0EE8a1F237466bB9CAc8466bFA2aA63A978/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29010 Add YAWN (YAWN) (ERC20)
  blockchains/ethereum/assets/0x881d4C8618D68872fA404518B2460eA839A02a6a/info.json
  blockchains/ethereum/assets/0x881d4C8618D68872fA404518B2460eA839A02a6a/logo.png
Labels: Payment Status: Paid, Payment Status: Requested
