Repository trustwallet/assets, pull requests merged in 2024-02, with the labels that each got.

#27327 updated OVR token info
  blockchains/ethereum/assets/0x21BfBDa47A0B4B5b1248c767Ee49F7caA9B23697/info.json
  blockchains/ethereum/assets/0x21BfBDa47A0B4B5b1248c767Ee49F7caA9B23697/logo.png
  blockchains/polygon/assets/0x1631244689EC1fEcbDD22fb5916E920dFC9b8D30/info.json
  blockchains/polygon/assets/0x1631244689EC1fEcbDD22fb5916E920dFC9b8D30/logo.png
  blockchains/smartchain/assets/0x7E35D0e9180bF3A1fc47b0d110bE7a21A10B41Fe/info.json
  blockchains/smartchain/assets/0x7E35D0e9180bF3A1fc47b0d110bE7a21A10B41Fe/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#27324 Add VLaunch (BEP20) and deprecate old contracts
  blockchains/ethereum/assets/0x51FE2E572e97BFEB1D719809d743Ec2675924EDc/info.json
  blockchains/ethereum/assets/0x51FE2E572e97BFEB1D719809d743Ec2675924EDc/logo.png
  blockchains/smartchain/assets/0xF574Ba6bde97cC09784e616ebAeD432b4e896B49/info.json
  blockchains/smartchain/assets/0xF574Ba6bde97cC09784e616ebAeD432b4e896B49/logo.png
  blockchains/smartchain/assets/0xc3601108947A46B219C09f24c668a52756C8d977/info.json
  blockchains/smartchain/assets/0xc3601108947A46B219C09f24c668a52756C8d977/logo.png
Labels: Payment Status: Paid

#27236 Add Unagi Token (UNA) (ERC20, BEP20, POLYGON)
  blockchains/ethereum/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/info.json
  blockchains/ethereum/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/logo.png
  blockchains/polygon/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/info.json
  blockchains/polygon/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/logo.png
  blockchains/smartchain/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/info.json
  blockchains/smartchain/assets/0x0B6f3eA2814F3FFf804bA5D5c237aebbc364fba9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27311 Add IDRX Token (POLYGON, BEP20)
  blockchains/polygon/assets/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC/info.json
  blockchains/polygon/assets/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC/logo.png
  blockchains/smartchain/assets/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC/info.json
  blockchains/smartchain/assets/0x649a2DA7B28E0D54c13D5eFf95d3A660652742cC/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27353 [internal] Zeta EVM and Native ZetaChain
  blockchains/nativezetachain/info/info.json
  blockchains/nativezetachain/info/logo.png
  blockchains/zetaevm/info/info.json
  blockchains/zetaevm/info/logo.png
Labels: Payment Status: Paid

#27369 attempt to trigger CI with correct info
  blockchains/opbnb/assets/0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb/info.json
Labels: Type: Bug

#27364 Add Heroes of Mavia (ERC20)
  blockchains/ethereum/assets/0x24fcFC492C1393274B6bcd568ac9e225BEc93584/info.json
  blockchains/ethereum/assets/0x24fcFC492C1393274B6bcd568ac9e225BEc93584/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27378 Adding Seed.Photo Token logo and info
  blockchains/smartchain/assets/0x6730f7A6BbB7b9C8e60843948f7FEB4B6a17B7F7/info.json
  blockchains/smartchain/assets/0x6730f7A6BbB7b9C8e60843948f7FEB4B6a17B7F7/logo.png
Labels: Payment Status: Paid

#27358 Add member
  blockchains/base/assets/0x7d89E05c0B93B24B5Cb23A073E60D008FEd1aCF9/info.json
  blockchains/base/assets/0x7d89E05c0B93B24B5Cb23A073E60D008FEd1aCF9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#27396 Add Pandora and DeFrogs ERC404 tokens
  blockchains/ethereum/assets/0x9E9FbDE7C7a83c43913BddC8779158F1368F0413/info.json
  blockchains/ethereum/assets/0x9E9FbDE7C7a83c43913BddC8779158F1368F0413/logo.png
  blockchains/ethereum/assets/0xd555498a524612c67f286dF0e0a9a64a73a7Cdc7/info.json
  blockchains/ethereum/assets/0xd555498a524612c67f286dF0e0a9a64a73a7Cdc7/logo.png
Labels: Payment Status: Requested

#27330 Add EtherPoS (ETPOS)
  blockchains/smartchain/assets/0xdE7B72c2c2828A81bEe8D7FA86c7FC22B58A713d/info.json
  blockchains/smartchain/assets/0xdE7B72c2c2828A81bEe8D7FA86c7FC22B58A713d/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27408 Add Catcoin (BEP20)
  blockchains/smartchain/assets/0x59F4F336Bf3D0C49dBfbA4A74eBD2a6aCE40539A/info.json
  blockchains/smartchain/assets/0x59F4F336Bf3D0C49dBfbA4A74eBD2a6aCE40539A/logo.png
Labels: Payment Status: Paid

#27411 Remove duplicate
  blockchains/ethereum/chainlist.json
Labels: Payment Status: Requested

#27407 Update BabyBonk Logo and Info
  blockchains/smartchain/assets/0xBb2826Ab03B6321E170F0558804F2B6488C98775/info.json
  blockchains/smartchain/assets/0xBb2826Ab03B6321E170F0558804F2B6488C98775/logo.png
Labels: Payment Status: Paid

#27413 Add MCNCOIN (BEP20)
  blockchains/smartchain/assets/0xdd02bC212E79ACdAb476C9295cDea8a61099Cb79/info.json
  blockchains/smartchain/assets/0xdd02bC212E79ACdAb476C9295cDea8a61099Cb79/logo.png
Labels: Payment Status: Paid

#27457 PirateCash token swap
  blockchains/smartchain/assets/0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05/info.json
  blockchains/smartchain/assets/0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#27454 [Internal] brc20 tokens
  blockchains/bitcoin/assets/btcs/info.json
  blockchains/bitcoin/assets/btcs/logo.png
  blockchains/bitcoin/assets/ligo/info.json
  blockchains/bitcoin/assets/ligo/logo.png
  blockchains/bitcoin/assets/ordi/info.json
  blockchains/bitcoin/assets/ordi/logo.png
  blockchains/bitcoin/assets/piin/info.json
  blockchains/bitcoin/assets/piin/logo.png
  blockchains/bitcoin/assets/rats/info.json
  blockchains/bitcoin/assets/rats/logo.png
  blockchains/bitcoin/assets/sats/info.json
  blockchains/bitcoin/assets/sats/logo.png
Labels: Payment Status: Paid

#27498 disable lint
  .github/workflows/check.yml
Labels: Payment Status: Requested
