Repository trustwallet/assets, pull requests merged in 2024-09, with the labels that each got.

#29023 Add Kahuna assets
  blockchains/akash/validators/assets/akashvaloper17r0cp9zrtkvzlz7a2r09gmdxwqfyje98aup3je/logo.png
  blockchains/akash/validators/list.json
  blockchains/cosmos/validators/assets/cosmosvaloper17r0cp9zrtkvzlz7a2r09gmdxwqfyje98l3k9h6/logo.png
  blockchains/cosmos/validators/list.json
  blockchains/nativeinjective/validators/assets/injvaloper1qkwpk4pf6txgazfs8lnjzj75pc47z9g26lww7r/logo.png
  blockchains/nativeinjective/validators/list.json
  blockchains/osmosis/validators/assets/osmovaloper17r0cp9zrtkvzlz7a2r09gmdxwqfyje98gfer6u/logo.png
  blockchains/osmosis/validators/list.json
  blockchains/quasar/validators/assets/quasarvaloper17r0cp9zrtkvzlz7a2r09gmdxwqfyje98scge77/logo.png
  blockchains/quasar/validators/list.json
  blockchains/stargaze/validators/assets/starsvaloper17r0cp9zrtkvzlz7a2r09gmdxwqfyje9898petq/logo.png
  blockchains/stargaze/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#29008 Add Vista Finance (BEP20)
  blockchains/smartchain/assets/0x493361D6164093936c86Dcb35Ad03b4C0D032076/info.json
  blockchains/smartchain/assets/0x493361D6164093936c86Dcb35Ad03b4C0D032076/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#28965 Add Styleo Coin (BEP20)
  blockchains/smartchain/assets/0xd9361d306A9e9A43f5883a064038220EF0D46fB0/info.json
  blockchains/smartchain/assets/0xd9361d306A9e9A43f5883a064038220EF0D46fB0/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28975 Add LandRocker (POLYGON)
  blockchains/polygon/assets/0xfb7f8A2C0526D01BFB00192781B7a7761841B16C/info.json
  blockchains/polygon/assets/0xfb7f8A2C0526D01BFB00192781B7a7761841B16C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29073 Add Marketmaking.PRO (MMPRO) token
  blockchains/smartchain/assets/0x6067490d05F3cF2fdFFC0e353b1f5Fd6E5CCDF70/info.json
  blockchains/smartchain/assets/0x6067490d05F3cF2fdFFC0e353b1f5Fd6E5CCDF70/logo.png
Labels: Payment Status: Paid

#29054 Add SportPoint (BEP20)
  blockchains/smartchain/assets/0x0cF453DC7EA21ef8FdfFC1B14Cb848E1e3884Be5/info.json
  blockchains/smartchain/assets/0x0cF453DC7EA21ef8FdfFC1B14Cb848E1e3884Be5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29084 Update Polygon ERC20 zkEVM
  blockchains/polygonzkevm/assets/0xa2036f0538221a77A3937F1379699f44945018d0/info.json
Labels: Payment Status: Requested

#29085 Add Polygon Ecosystem Token (POL)
  blockchains/ethereum/assets/0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6/info.json
  blockchains/ethereum/assets/0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6/logo.png
  blockchains/polygonzkevm/assets/0x22B21BedDef74FE62F031D2c5c8F7a9F8a4b304D/info.json
  blockchains/polygonzkevm/assets/0x22B21BedDef74FE62F031D2c5c8F7a9F8a4b304D/logo.png
Labels: Payment Status: Requested

#29030 Add Blombard (BEP20)
  blockchains/smartchain/assets/0xA82D8d81557f6Da6dd4DDAD9f09a417530cfd4e7/info.json
  blockchains/smartchain/assets/0xA82D8d81557f6Da6dd4DDAD9f09a417530cfd4e7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29067 Add EtherMail Project to Base Chain
  blockchains/base/assets/0xe2c86869216aC578bd62a4b8313770d9EE359A05/info.json
  blockchains/base/assets/0xe2c86869216aC578bd62a4b8313770d9EE359A05/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29099 Add Neiro logo and info
  blockchains/ethereum/assets/0x812Ba41e071C7b7fA4EBcFB62dF5F45f6fA853Ee/info.json
  blockchains/ethereum/assets/0x812Ba41e071C7b7fA4EBcFB62dF5F45f6fA853Ee/logo.png
Labels: Payment Status: Paid

#29068 Add Binstarter (BEP20)
  blockchains/smartchain/assets/0x5cE12F6d9F2FcAf0b11494a1C39E09eeB16Ca7e8/info.json
  blockchains/smartchain/assets/0x5cE12F6d9F2FcAf0b11494a1C39E09eeB16Ca7e8/logo.png
  blockchains/smartchain/assets/0xab287e6D370C61f105630e656B5468ACB4D00423/info.json
  blockchains/smartchain/assets/0xab287e6D370C61f105630e656B5468ACB4D00423/logo.png
Labels: Payment Status: Paid

#29126 Add SquidGrow (ERC20)
  blockchains/ethereum/assets/0xb72E76cCf005313868DB7b48070901a44629da98/info.json
  blockchains/ethereum/assets/0xb72E76cCf005313868DB7b48070901a44629da98/logo.png
Labels: Payment Status: Requested

#29130 Add AVACOIN (JETTON)
  blockchains/ton/assets/EQAR-KBduwL4w-Lg72QFX4tWTOAJCGS72FkGHrJL9Qt7P9ln/info.json
  blockchains/ton/assets/EQAR-KBduwL4w-Lg72QFX4tWTOAJCGS72FkGHrJL9Qt7P9ln/logo.png
Labels: Payment Status: Requested

#29132 Add Sky (ERC20)
  blockchains/ethereum/assets/0x56072C95FAA701256059aa122697B133aDEd9279/info.json
  blockchains/ethereum/assets/0x56072C95FAA701256059aa122697B133aDEd9279/logo.png
Labels: Payment Status: Requested

#29134 Add Nya multichain - Migrated from Catgirl
  blockchains/arbitrum/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/arbitrum/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/avalanchec/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/avalanchec/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/base/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/base/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/ethereum/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/ethereum/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/optimism/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/optimism/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/polygon/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/polygon/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/smartchain/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/info.json
  blockchains/smartchain/assets/0x38F9bf9dCe51833Ec7f03C9dC218197999999999/logo.png
  blockchains/smartchain/assets/0x79eBC9A2ce02277A4b5b3A768b1C0A4ed75Bd936/info.json
  blockchains/smartchain/assets/0x79eBC9A2ce02277A4b5b3A768b1C0A4ed75Bd936/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29196 Add TON logo
  dapps/tw.discover.ton.png
Labels: Payment Status: Requested

#29197 Modify TON logo
  dapps/tw.discover.ton.png
Labels: Payment Status: Requested
