Repository trustwallet/assets, pull requests merged in 2024-01, with the labels that each got.

#27127 Added new solana validator
  blockchains/solana/validators/assets/DTwEEF6VSrmTBYkDcj3BKAc52qhvP8CEQUEAMMT1cG3/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, Payment Status: Requested

#27137 Add Grok Inu (BEP20)
  blockchains/smartchain/assets/0xD08b9e557D1f64c8dd50A168453eA302A83E47FC/info.json
  blockchains/smartchain/assets/0xD08b9e557D1f64c8dd50A168453eA302A83E47FC/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27164 Add frgx finance token
  blockchains/smartchain/assets/0xC703dA39aE3B9Db67C207c7Bad8100E1AfdC0F9c/info.json
  blockchains/smartchain/assets/0xC703dA39aE3B9Db67C207c7Bad8100E1AfdC0F9c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27213 Add Rango icon
  dapps/rango.png
Labels: Payment Status: Requested

#27211 Add Pepe 2.0 (PEPE2.0) (ERC20)
  blockchains/ethereum/assets/0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B/info.json
  blockchains/ethereum/assets/0x0305f515fa978cf87226cf8A9776D25bcfb2Cc0B/logo.png
  blockchains/ethereum/assets/0xfb66321D7C674995dFcC2cb67A30bC978dc862AD/info.json
  blockchains/ethereum/assets/0xfb66321D7C674995dFcC2cb67A30bC978dc862AD/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#26866 Add Teller USD (BEP20)
  blockchains/smartchain/assets/0x4953d28b12D862250Cc96163A9C46Ae2B8ef52c5/info.json
  blockchains/smartchain/assets/0x4953d28b12D862250Cc96163A9C46Ae2B8ef52c5/logo.png
Labels: Payment Status: Paid, Payment Status: Requested, Awaiting CMC Listing

#27204 Update XcelPay token info
  blockchains/smartchain/assets/0xC79d1fD14F514cD713b5cA43D288a782Ae53eAb2/info.json
  blockchains/smartchain/assets/0xC79d1fD14F514cD713b5cA43D288a782Ae53eAb2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27284 eth staking
  blockchains/ethereum/info/info.json
Labels: Payment Status: Requested

#27285 Update AVA token logo image on Ethereum and BNB
  blockchains/ethereum/assets/0xa6C0c097741D55ECd9a3A7DeF3A8253fD022ceB9/logo.png
  blockchains/smartchain/assets/0xd9483EA7214FCfd89B4Fb8f513B544920E315A52/logo.png
Labels: Payment Status: Requested

#27299 Add Payvertise (BEP20)
  blockchains/smartchain/assets/0xb4E14166F6dE109f800C52A84a434C383137C8dC/info.json
  blockchains/smartchain/assets/0xb4E14166F6dE109f800C52A84a434C383137C8dC/logo.png
Labels: Payment Status: Paid

#27295 LQR token updated to the new contract address
  blockchains/smartchain/assets/0xC4a1E7106d08B7FF947254B6D75cf2b877d55daF/info.json
  blockchains/smartchain/assets/0xC4a1E7106d08B7FF947254B6D75cf2b877d55daF/logo.png
  blockchains/smartchain/assets/0xbc81ea817b579eC0334BcA8E65E436b7cB540147/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#27293 Add AITECH (BEP20)
  blockchains/smartchain/assets/0x2D060Ef4d6BF7f9e5edDe373Ab735513c0e4F944/info.json
  blockchains/smartchain/assets/0x2D060Ef4d6BF7f9e5edDe373Ab735513c0e4F944/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
