Repository trustwallet/assets, pull requests merged in 2024-05, with the labels that each got.

#28099 bump go-primitives
  go.mod
  go.sum
Labels: Payment Status: Requested

#27973 Add Film.io (POLYGON)
  blockchains/polygon/assets/0x3B9E9100Db1389c518d47c635D80a90ad4C4f41b/info.json
  blockchains/polygon/assets/0x3B9E9100Db1389c518d47c635D80a90ad4C4f41b/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28112 Add logo and info IMPCOIN (BEP20)
  blockchains/smartchain/assets/0x5FE7D4aD1794365f6812cf425a99484444417EDD/info.json
  blockchains/smartchain/assets/0x5FE7D4aD1794365f6812cf425a99484444417EDD/logo.png
Labels: Payment Status: Paid

#28131 Br0321 145256
  blockchains/ethereum/assets/0xed328E9C1179a30ddC1E7595E036AEd8760C22aF/info.json
  blockchains/ethereum/assets/0xed328E9C1179a30ddC1E7595E036AEd8760C22aF/logo.png
Labels: Payment Status: Paid

#28085 Migrate DOTMOOVS MOOV Token Contract (ERC20)
  blockchains/ethereum/assets/0x24EC2Ca132abf8F6f8a6E24A1B97943e31f256a7/info.json
  blockchains/ethereum/assets/0x24EC2Ca132abf8F6f8a6E24A1B97943e31f256a7/logo.png
  blockchains/ethereum/assets/0x4116f14b6d462B32a1C10F98049E4B1765e34FA9/info.json
  blockchains/ethereum/assets/0x4116f14b6d462B32a1C10F98049E4B1765e34FA9/logo.png
Labels: Payment Status: Requested

#28141 Add logo
  blockchains/smartchain/assets/0xEC80E6EF54D43aaDc0e0556a73eC34D840d5a294/info.json
  blockchains/smartchain/assets/0xEC80E6EF54D43aaDc0e0556a73eC34D840d5a294/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28026 Add Catcoin (SPL)
  blockchains/solana/assets/7hWcHohzwtLddDUG81H2PkWq6KEkMtSDNkYXsso18Fy3/info.json
  blockchains/solana/assets/7hWcHohzwtLddDUG81H2PkWq6KEkMtSDNkYXsso18Fy3/logo.png
Labels: Payment Status: Paid

#27796 Add Rabi (BEP20)
  blockchains/smartchain/assets/0x3D90DB6cC52E95679fb431E88B1830BA18E41889/info.json
  blockchains/smartchain/assets/0x3D90DB6cC52E95679fb431E88B1830BA18E41889/logo.png
Labels: Status: More Info / Change Requested, Status: On Hold, Payment Status: Paid

#28244 add layer3 icon
  dapps/app.layer3.xyz.png
Labels: Payment Status: Requested

#28306 add scroll campaign icon
  dapps/tw.discover.scroll_campaign.png
Labels: Payment Status: Requested

#28326 Added zkRace (ZERC)
  blockchains/ethereum/assets/0xf8428A5a99cb452Ea50B6Ea70b052DaA3dF4934F/info.json
  blockchains/ethereum/assets/0xf8428A5a99cb452Ea50B6Ea70b052DaA3dF4934F/logo.png
  blockchains/polygon/assets/0xE1b3eb06806601828976e491914e3De18B5d6b28/info.json
  blockchains/polygon/assets/0xE1b3eb06806601828976e491914e3De18B5d6b28/logo.png
  blockchains/smartchain/assets/0x9c47E503b2f497e9Ad9F1c0dfA6Bd9Fd5456AA4e/info.json
  blockchains/smartchain/assets/0x9c47E503b2f497e9Ad9F1c0dfA6Bd9Fd5456AA4e/logo.png
Labels: Payment Status: Paid
