Repository trustwallet/assets, pull requests merged in 2024-04, with the labels that each got.

#27374 Add HOKK logo and update info
  blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/info.json
  blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/logo.png
Labels: Payment Status: Paid

#27869 Delete outdated workflows
  .github/workflows/fix-dryrun.yml
  .github/workflows/fix.yml
  .github/workflows/periodic-update.yml
Labels: Payment Status: Requested

#27868 chore: update MANTRA OM logo and tags info
  blockchains/ethereum/assets/0x3593D125a4f7849a1B059E64F4517A86Dd60c95d/info.json
  blockchains/ethereum/assets/0x3593D125a4f7849a1B059E64F4517A86Dd60c95d/logo.png
  blockchains/polygon/assets/0xC3Ec80343D2bae2F8E680FDADDe7C17E71E114ea/info.json
  blockchains/polygon/assets/0xC3Ec80343D2bae2F8E680FDADDe7C17E71E114ea/logo.png
  blockchains/smartchain/assets/0xF78D2e7936F5Fe18308A3B2951A93b6c4a41F5e2/info.json
  blockchains/smartchain/assets/0xF78D2e7936F5Fe18308A3B2951A93b6c4a41F5e2/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#27888 Add Zero1 Labs (ERC20)
  blockchains/ethereum/assets/0x1495bc9e44Af1F8BCB62278D2bEC4540cF0C05ea/info.json
  blockchains/ethereum/assets/0x1495bc9e44Af1F8BCB62278D2bEC4540cF0C05ea/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27919 Add LSD (BEP20)
  blockchains/smartchain/assets/0xcD1B51b87a8a7137D6421bA5A976225187a26777/info.json
  blockchains/smartchain/assets/0xcD1B51b87a8a7137D6421bA5A976225187a26777/logo.png
Labels: Payment Status: Paid

#27983 Add BitFloki (BEP20)
  blockchains/smartchain/assets/0x79CDc9cA057E16dFfd45BD803491f328f49e1762/info.json
  blockchains/smartchain/assets/0x79CDc9cA057E16dFfd45BD803491f328f49e1762/logo.png
Labels: Payment Status: Paid

#27981 Update QRDO brand to OPEN info.json
  blockchains/ethereum/assets/0x4123a133ae3c521FD134D7b13A2dEC35b56c2463/info.json
  blockchains/ethereum/assets/0x4123a133ae3c521FD134D7b13A2dEC35b56c2463/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#27917 Add Moriarty (BEP20)
  blockchains/smartchain/assets/0x13aAC25C16a8c1FA93D78C4026CEE7166403A595/info.json
  blockchains/smartchain/assets/0x13aAC25C16a8c1FA93D78C4026CEE7166403A595/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27987 Add ANDY (ERC20)
  blockchains/ethereum/assets/0x68BbEd6A47194EFf1CF514B50Ea91895597fc91E/info.json
  blockchains/ethereum/assets/0x68BbEd6A47194EFf1CF514B50Ea91895597fc91E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28028 Add Monbase Info and Logo
  blockchains/smartchain/assets/0x551FAAB1027Cc50eFAeA5BED092E330475C3Cd99/info.json
  blockchains/smartchain/assets/0x551FAAB1027Cc50eFAeA5BED092E330475C3Cd99/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#27988 Add MetaGamescoin (BEP20)
  blockchains/smartchain/assets/0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11/info.json
  blockchains/smartchain/assets/0xbb73BB2505AC4643d5C0a99c2A1F34B3DfD09D11/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28040 Add Agatech (BEP20)
  blockchains/smartchain/assets/0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029/info.json
  blockchains/smartchain/assets/0xb427e47e8fDD678278d2A91EEaC014ffcDDaF029/logo.png
Labels: Payment Status: Paid

#27918 Add Basenji (ERC20)
  blockchains/ethereum/assets/0xBC45647eA894030a4E9801Ec03479739FA2485F0/info.json
  blockchains/ethereum/assets/0xBC45647eA894030a4E9801Ec03479739FA2485F0/logo.png
Labels: Payment Status: Paid

#28073 Update ATOS logo
  blockchains/ethereum/assets/0x4D0528598F916Fd1D8dc80e5f54a8fEEDcFd4b18/info.json
  blockchains/ethereum/assets/0x4D0528598F916Fd1D8dc80e5f54a8fEEDcFd4b18/logo.png
Labels: Payment Status: Requested
