Repository trustwallet/assets, pull requests merged in 2024-10, with the labels that each got.

#29115 Replaced Klaytn assets to Kaia
  blockchains/ethereum/chainlist.json
  blockchains/klaytn/assets/0x5c74070FDeA071359b86082bd9f9b3dEaafbe32b/info.json
  blockchains/klaytn/assets/0x6270B58BE569a7c0b8f47594F191631Ae5b2C86C/info.json
  blockchains/klaytn/info/info.json
  blockchains/klaytn/info/logo.png
Labels: Payment Status: Requested

#29155 Add FutureToken (BEP20)
  blockchains/smartchain/assets/0x63F712B7EC2b9f7146b54a79133900F9458eeC6a/info.json
  blockchains/smartchain/assets/0x63F712B7EC2b9f7146b54a79133900F9458eeC6a/logo.png
Labels: Payment Status: Paid

#29194 Add The Green World (BEP20)
  blockchains/smartchain/assets/0x80C260cd80d8a2855b554A7d5001BD06421a6fd4/info.json
  blockchains/smartchain/assets/0x80C260cd80d8a2855b554A7d5001BD06421a6fd4/logo.png
Labels: Payment Status: Paid

#29200 Add GBANK APY (BEP20)
  blockchains/smartchain/assets/0xdA0638EA374c4c5bF2914E6F4D5B2335dEb8D80D/info.json
  blockchains/smartchain/assets/0xdA0638EA374c4c5bF2914E6F4D5B2335dEb8D80D/logo.png
Labels: Payment Status: Paid

#29253 Revert "Change name for Gomining"
  blockchains/ethereum/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
  blockchains/smartchain/assets/0x7Ddc52c4De30e94Be3A6A0A2b259b2850f421989/info.json
Labels: Payment Status: Requested

#29265 Add FU coin (BEP20)
  blockchains/smartchain/assets/0xED6AF21Df463c7f116A6d7d687A4c190c4cf7586/info.json
  blockchains/smartchain/assets/0xED6AF21Df463c7f116A6d7d687A4c190c4cf7586/logo.png
Labels: Payment Status: Paid

#29294 Add WibeGram (BEP20)
  blockchains/smartchain/assets/0x25d624E571d6d7B32729B11DdbbD96Fe89Af44E1/info.json
  blockchains/smartchain/assets/0x25d624E571d6d7B32729B11DdbbD96Fe89Af44E1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29295 Add CV TOKEN (BEP20)
  blockchains/smartchain/assets/0x6A50A1f2fF0C5658815215b498f7aB003a783Dc7/info.json
  blockchains/smartchain/assets/0x6A50A1f2fF0C5658815215b498f7aB003a783Dc7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29305 Add HIPPO (SUI)
  blockchains/sui/assets/0x8993129d72e733985f7f1a00396cbd055bad6f817fee36576ce483c8bbb8b87b::sudeng::SUDENG/info.json
  blockchains/sui/assets/0x8993129d72e733985f7f1a00396cbd055bad6f817fee36576ce483c8bbb8b87b::sudeng::SUDENG/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29331 Launchpool icon
  dapps/launchpool_rocket.png
  dapps/tw.discover.cgpt_promo.png
  dapps/tw.discover.ton.png
Labels: Payment Status: Requested
