Repository trustwallet/assets, pull requests merged in 2024-12, with the labels that each got.

#29587 Add FEG Token (BEP20)
  blockchains/smartchain/assets/0xF3c7CECF8cBC3066F9a87b310cEBE198d00479aC/info.json
  blockchains/smartchain/assets/0xF3c7CECF8cBC3066F9a87b310cEBE198d00479aC/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29682 Add files via upload
  dapps/discover_12days_4ever.png
Labels: Payment Status: Requested

#29641 Add K9 Finance DAO (ERC20)
  blockchains/ethereum/assets/0x91fbB2503AC69702061f1AC6885759Fc853e6EaE/info.json
  blockchains/ethereum/assets/0x91fbB2503AC69702061f1AC6885759Fc853e6EaE/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29700 Add files via upload
  dapps/discover_12days_bump.png
Labels: Payment Status: Requested

#29703 Abandon old Realio Network (RIO) - ERC20
  blockchains/ethereum/assets/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097/info.json
  blockchains/ethereum/assets/0xf21661D0D1d76d3ECb8e1B9F1c923DBfffAe4097/logo.png
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Requested

#29671 Update info and logo for Prosper (PROS) on Ethereum and BSC
  blockchains/ethereum/assets/0x8642A849D0dcb7a15a974794668ADcfbe4794B56/info.json
  blockchains/ethereum/assets/0x8642A849D0dcb7a15a974794668ADcfbe4794B56/logo.png
  blockchains/smartchain/assets/0xEd8c8Aa8299C10f067496BB66f8cC7Fb338A3405/info.json
  blockchains/smartchain/assets/0xEd8c8Aa8299C10f067496BB66f8cC7Fb338A3405/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29719 Add files via upload
  dapps/discover_12days_freename.png
Labels: Payment Status: Requested

#29730 Add files via upload
  dapps/discover_12days_wagmi.png
Labels: Payment Status: Requested

#29763 Add files via upload
  dapps/discover_12days_heat.png
Labels: Payment Status: Requested

#29777 Add files via upload
  dapps/discover_12days_wcoin.png
Labels: Payment Status: Requested

#29788 Updated KLAY ticker to KAIA
  blockchains/klaytn/info/info.json
Labels: Payment Status: Requested

#29801 Added GUI INU
  blockchains/aptos/assets/0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002/info.json
  blockchains/aptos/assets/0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29756 RE OPEN ADD PROPC INFO AND LOGO
  blockchains/ethereum/assets/0x9ff58067Bd8D239000010c154C6983A325Df138E/info.json
  blockchains/ethereum/assets/0x9ff58067Bd8D239000010c154C6983A325Df138E/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29775 Add GRAB (BEP20)
  blockchains/smartchain/assets/0x6d8058cDaa406Ea4924D47B48F2ef5f18d35637c/info.json
  blockchains/smartchain/assets/0x6d8058cDaa406Ea4924D47B48F2ef5f18d35637c/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29782 Add Based Coin (ERC20) Base chain
  blockchains/base/assets/0x07d15798a67253D76cea61F0eA6F57AeDC59DffB/info.json
  blockchains/base/assets/0x07d15798a67253D76cea61F0eA6F57AeDC59DffB/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29818 Internal Trending Token
  blockchains/solana/assets/7dUKUopcNWW6CcU4eRxCHh1uiMh32zDrmGf6ufqhxann/info.json
  blockchains/solana/assets/7dUKUopcNWW6CcU4eRxCHh1uiMh32zDrmGf6ufqhxann/logo.png
Labels: Payment Status: Requested

#29819 Internal Trending Token
  blockchains/solana/assets/2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo/info.json
  blockchains/solana/assets/2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo/logo.png
  blockchains/solana/assets/HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC/info.json
  blockchains/solana/assets/HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC/logo.png
Labels: Payment Status: Requested

#29817 Add Snake (BEP20)
  blockchains/smartchain/assets/0x34980c35353A8D7B1A1BA02e02E387a8383e004A/info.json
  blockchains/smartchain/assets/0x34980c35353A8D7B1A1BA02e02E387a8383e004A/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29547 Include DOVU Wrapped Assets via Hashport Bridge.
  blockchains/arbitrum/assets/0xe821C045f9149B44ef96f8054B9c6d94f4c89417/info.json
  blockchains/arbitrum/assets/0xe821C045f9149B44ef96f8054B9c6d94f4c89417/logo.png
  blockchains/aurora/assets/0x4007168965cBdB189A98E03C28695F900D92a11E/info.json
  blockchains/aurora/assets/0x4007168965cBdB189A98E03C28695F900D92a11E/logo.png
  blockchains/base/assets/0xB38266e0e9D9681b77aEB0A280E98131b953F865/info.json
  blockchains/base/assets/0xB38266e0e9D9681b77aEB0A280E98131b953F865/logo.png
  blockchains/cronos/assets/0xf58988341516DFADE0eaE3710D69083E0Ce75235/info.json
  blockchains/cronos/assets/0xf58988341516DFADE0eaE3710D69083E0Ce75235/logo.png
  blockchains/ethereum/assets/0x2aeAbde1aB736c59E9A19BeD67681869eEF39526/info.json
  blockchains/ethereum/assets/0x2aeAbde1aB736c59E9A19BeD67681869eEF39526/logo.png
  blockchains/fantom/assets/0x2E64747523Fb2Bd079f7cAa3Af904cC15886916F/info.json
  blockchains/fantom/assets/0x2E64747523Fb2Bd079f7cAa3Af904cC15886916F/logo.png
  blockchains/hedera/assets/0x000000000000000000000000000000000038b3db/info.json
  blockchains/hedera/assets/0x000000000000000000000000000000000038b3db/logo.png
  blockchains/moonbeam/assets/0xe32C01d807C2290fEe75625CdEde876a0a1c8eC0/info.json
  blockchains/moonbeam/assets/0xe32C01d807C2290fEe75625CdEde876a0a1c8eC0/logo.png
  blockchains/optimism/assets/0xd91fF310DF12FBb9D4C77A55BeDa0367e2244Ca6/info.json
  blockchains/optimism/assets/0xd91fF310DF12FBb9D4C77A55BeDa0367e2244Ca6/logo.png
  blockchains/polygon/assets/0x8B4caE9Af23EB752515A88497e678e9aDff1753d/info.json
  blockchains/polygon/assets/0x8B4caE9Af23EB752515A88497e678e9aDff1753d/logo.png
  blockchains/smartchain/assets/0x08707eaEFCc344ad35BD35C5fF5691c2D3db456e/info.json
  blockchains/smartchain/assets/0x08707eaEFCc344ad35BD35C5fF5691c2D3db456e/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29858 Add files via upload
  dapps/discover_arena_games.png
Labels: Payment Status: Requested

#29861 Add files via upload
  dapps/discover_arena_games.png
Labels: Payment Status: Requested

#29862 Add files via upload
  dapps/discover_arena_games_updated.png
Labels: Payment Status: Requested

#29850 logo update
  blockchains/ethereum/assets/0xb72E76cCf005313868DB7b48070901a44629da98/info.json
  blockchains/ethereum/assets/0xb72E76cCf005313868DB7b48070901a44629da98/logo.png
Labels: Payment Status: Requested

#29846 Add shrub token
  blockchains/ethereum/assets/0x3b991130eaE3CcA364406D718DA22FA1C3E7C256/info.json
  blockchains/ethereum/assets/0x3b991130eaE3CcA364406D718DA22FA1C3E7C256/logo.png
Labels: Payment Status: Paid

#29863 Add files via upload
  dapps/discover_limewire_updated.png
Labels: Payment Status: Requested

#29878 Add files via upload
  dapps/discover_12days_quack.png
Labels: Payment Status: Requested

#29877 Internal Trending Token
  blockchains/solana/assets/2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv/info.json
  blockchains/solana/assets/2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv/logo.png
Labels: Payment Status: Requested

#29932 Add Solana Tokens
  blockchains/solana/assets/2Crpmvk14W1tzqLJ4QGc6KSkzHDju93jcqYq6kSs4BGi/info.json
  blockchains/solana/assets/2Crpmvk14W1tzqLJ4QGc6KSkzHDju93jcqYq6kSs4BGi/logo.png
  blockchains/solana/assets/5BKTP1cWao5dhr8tkKcfPW9mWkKtuheMEAU6nih2jSX/info.json
  blockchains/solana/assets/5BKTP1cWao5dhr8tkKcfPW9mWkKtuheMEAU6nih2jSX/logo.png
  blockchains/solana/assets/5MBBsoCVddAuF8XixvCcXNbHAw6WfpZ8WyTKMmczxxRN/info.json
  blockchains/solana/assets/5MBBsoCVddAuF8XixvCcXNbHAw6WfpZ8WyTKMmczxxRN/logo.png
  blockchains/solana/assets/5pKj7qx29jzWZb36xYw2R5ZahMESCCyKdq2fphiziM9d/info.json
  blockchains/solana/assets/5pKj7qx29jzWZb36xYw2R5ZahMESCCyKdq2fphiziM9d/logo.png
  blockchains/solana/assets/66dzGbVZg9cBNb3sTWd9iAtDZKjgAyztNwAhTitfgoLj/info.json
  blockchains/solana/assets/66dzGbVZg9cBNb3sTWd9iAtDZKjgAyztNwAhTitfgoLj/logo.png
  blockchains/solana/assets/7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT/info.json
  blockchains/solana/assets/7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT/logo.png
  blockchains/solana/assets/7unYePWUHcpB28cnS65TpqT2qqmZaftRz9QABkdR8yN7/info.json
  blockchains/solana/assets/7unYePWUHcpB28cnS65TpqT2qqmZaftRz9QABkdR8yN7/logo.png
  blockchains/solana/assets/9dLuVbJMd4ZpTpFgmaFHAGSsFwVjtcnzFWaLAA1expHg/info.json
  blockchains/solana/assets/9dLuVbJMd4ZpTpFgmaFHAGSsFwVjtcnzFWaLAA1expHg/logo.png
  blockchains/solana/assets/9iUX4DG2BqmJSGHvZcqx75UM4BRXKUMHLVL2d7P2pump/info.json
  blockchains/solana/assets/9iUX4DG2BqmJSGHvZcqx75UM4BRXKUMHLVL2d7P2pump/logo.png
  blockchains/solana/assets/AcV2T3mwLUqMiiqcsafVm35zwPQkmLrfRtaW3716Fzvi/info.json
  blockchains/solana/assets/AcV2T3mwLUqMiiqcsafVm35zwPQkmLrfRtaW3716Fzvi/logo.png
  blockchains/solana/assets/DCCA1ivqRYFqwSQTz3ArKfKpD6uXv6an8jDW5s3EvkQZ/info.json
  blockchains/solana/assets/DCCA1ivqRYFqwSQTz3ArKfKpD6uXv6an8jDW5s3EvkQZ/logo.png
  blockchains/solana/assets/DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK/info.json
  blockchains/solana/assets/DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK/logo.png
  blockchains/solana/assets/DNyxufTEwqNCgGruJ4W2ue6u1RTFcH61H4sa42LGpump/info.json
  blockchains/solana/assets/DNyxufTEwqNCgGruJ4W2ue6u1RTFcH61H4sa42LGpump/logo.png
  blockchains/solana/assets/DeaKMzAeZja3Mh5okZE6WUvygLP3Lfuvm6Rg78HqXTz9/info.json
  blockchains/solana/assets/DeaKMzAeZja3Mh5okZE6WUvygLP3Lfuvm6Rg78HqXTz9/logo.png
  blockchains/solana/assets/DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t/info.json
  blockchains/solana/assets/DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t/logo.png
  blockchains/solana/assets/EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q/info.json
  blockchains/solana/assets/EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q/logo.png
  blockchains/solana/assets/EtBc6gkCvsB9c6f5wSbwG8wPjRqXMB5euptK6bqG1R4X/info.json
  blockchains/solana/assets/EtBc6gkCvsB9c6f5wSbwG8wPjRqXMB5euptK6bqG1R4X/logo.png
  blockchains/solana/assets/EvPUFsBikS1B3GpbmVvUWAc4DXaBXD4zLDER9SVSEF27/info.json
  blockchains/solana/assets/EvPUFsBikS1B3GpbmVvUWAc4DXaBXD4zLDER9SVSEF27/logo.png
  blockchains/solana/assets/F6TsRcjtLBzkdtZYqjTPVq9WtnwHMMc1WcQguEgCpump/info.json
  blockchains/solana/assets/F6TsRcjtLBzkdtZYqjTPVq9WtnwHMMc1WcQguEgCpump/logo.png
  blockchains/solana/assets/Fo6tfAkXj74X6j8hati8SxtwZHHcdGeqXVUPLP9Abvqu/info.json
  blockchains/solana/assets/Fo6tfAkXj74X6j8hati8SxtwZHHcdGeqXVUPLP9Abvqu/logo.png
  blockchains/solana/assets/G33s1LiUADEBLzN5jL6ocSXqrT2wsUq9W6nZ8o4k1b4L/info.json
  blockchains/solana/assets/G33s1LiUADEBLzN5jL6ocSXqrT2wsUq9W6nZ8o4k1b4L/logo.png
  blockchains/solana/assets/H1aN3vcvB68eaFPbMkoAss3vnfi4AhP5C2dpnrZzdBc7/info.json
  blockchains/solana/assets/H1aN3vcvB68eaFPbMkoAss3vnfi4AhP5C2dpnrZzdBc7/logo.png
  blockchains/solana/assets/H53UGEyBrB9easo9ego8yYk7o4Zq1G5cCtkxD3E3hZav/info.json
  blockchains/solana/assets/H53UGEyBrB9easo9ego8yYk7o4Zq1G5cCtkxD3E3hZav/logo.png
  blockchains/solana/assets/HGTxJQKzuMjzKkHVpRLcFHwE6ngVCJbcP35FDQtmRzhx/info.json
  blockchains/solana/assets/HGTxJQKzuMjzKkHVpRLcFHwE6ngVCJbcP35FDQtmRzhx/logo.png
  blockchains/solana/assets/J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv/info.json
  blockchains/solana/assets/J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv/logo.png
  blockchains/solana/assets/METADDFL6wWMWEoKTFJwcThTbUmtarRJZjRpzUvkxhr/info.json
  blockchains/solana/assets/METADDFL6wWMWEoKTFJwcThTbUmtarRJZjRpzUvkxhr/logo.png
  blockchains/solana/assets/PENGEKyPYXYDnbXGKcjXaSfMsovhcrtPT8S7127tKcg/info.json
  blockchains/solana/assets/PENGEKyPYXYDnbXGKcjXaSfMsovhcrtPT8S7127tKcg/logo.png
Labels: Payment Status: Requested
