Repository trustwallet/assets, pull requests merged in 2024-03, with the labels that each got.

#27466 Add FxBox (BEP20)
  blockchains/smartchain/assets/0x0DbCec4214d7E9c316e0eB53991a43F42F432e15/info.json
  blockchains/smartchain/assets/0x0DbCec4214d7E9c316e0eB53991a43F42F432e15/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested

#27543 lint fix (ICE Token)
  blockchains/ethereum/assets/0x79F05c263055BA20EE0e814ACD117C20CAA10e0c/info.json
Labels: Payment Status: Requested

#27550 Cleanup renamed dirs
  blockchains/ethereum/assets/0xafcdd4f666c84fed1d8bd825aa762e3714f652c9/info.json
  blockchains/ethereum/assets/0xafcdd4f666c84fed1d8bd825aa762e3714f652c9/logo.png
  blockchains/polygon/assets/0xafcdd4f666c84fed1d8bd825aa762e3714f652c9/info.json
  blockchains/polygon/assets/0xafcdd4f666c84fed1d8bd825aa762e3714f652c9/logo.png
Labels: Payment Status: Requested

#27414 Update Wrapped Centrifuge (wCFG)
  blockchains/ethereum/assets/0xc221b7E65FfC80DE234bbB6667aBDd46593D34F0/info.json
Labels: Payment Status: Paid, Payment Status: Requested

#27560 fix failing checks
  .github/workflows/check.yml
  blockchains/bitcoin/assets/rats/info.json
  blockchains/ethereum/assets/0x79F05c263055BA20EE0e814ACD117C20CAA10e0c/info.json
  blockchains/ethereum/assets/0x8248270620Aa532E4d64316017bE5E873E37cc09/info.json
  blockchains/ethereum/assets/0xc221b7E65FfC80DE234bbB6667aBDd46593D34F0/info.json
  go.mod
  go.sum
Labels: Payment Status: Requested

#27554 Add Dione (DIONE) (ERC20)
  blockchains/ethereum/assets/0x89B69F2d1adffA9A253d40840B6Baa7fC903D697/info.json
  blockchains/ethereum/assets/0x89B69F2d1adffA9A253d40840B6Baa7fC903D697/logo.png
Labels: Payment Status: Paid

#27557 rebrand SuperFarm to SuperVerse
  blockchains/ethereum/assets/0xe53EC727dbDEB9E2d5456c3be40cFF031AB40A55/info.json
  blockchains/ethereum/assets/0xe53EC727dbDEB9E2d5456c3be40cFF031AB40A55/logo.png
  blockchains/ethereum/tokenlist.json
Labels: Payment Status: Paid, Payment Status: Requested

#27569 empty commit - trigger / test sync flow
  blockchains/smartchain/assets/0xe552Fb52a4F19e44ef5A967632DBc320B0820639/info.json
Labels: Payment Status: Requested

#27625 Add TetherTV (BEP20)
  blockchains/smartchain/assets/0x9906DBDeD3dbf64A1f69b6E89a5c9f2E94d12a79/info.json
  blockchains/smartchain/assets/0x9906DBDeD3dbf64A1f69b6E89a5c9f2E94d12a79/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#27661 Add Chickencoin (ERC20)
  blockchains/ethereum/assets/0xD55210Bb6898C021a19de1F58d27b71f095921Ee/info.json
  blockchains/ethereum/assets/0xD55210Bb6898C021a19de1F58d27b71f095921Ee/logo.png
Labels: Status: On Hold, Payment Status: Paid, Payment Status: Requested

#27697 Add ivendPay (BEP20)
  blockchains/smartchain/assets/0xDE5BDcbd4d7dFa86E527fEF9971bd6Ca6A76eefB/info.json
  blockchains/smartchain/assets/0xDE5BDcbd4d7dFa86E527fEF9971bd6Ca6A76eefB/logo.png
Labels: Payment Status: Paid

#27688 Add Stakely validators for KSM, INJ, CRO, NEAR, STRD, SUI, JUNO, & BLD
  blockchains/agoric/validators/assets/agoricvaloper1mxhgvj2c93xahahx9d9fc7rwwtufqza5cn6uhn/logo.png
  blockchains/agoric/validators/list.json
  blockchains/cryptoorg/validators/assets/crocncl1tkev46yqrjzrjzrqtty30ex68eja2zcltyq2vj/logo.png
  blockchains/cryptoorg/validators/list.json
  blockchains/juno/validators/assets/junovaloper1hx9yj7qgnp8zhkrqfanvz74mcsg9d8eyskvsxg/logo.png
  blockchains/juno/validators/list.json
  blockchains/kusama/validators/assets/EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui/logo.png
  blockchains/kusama/validators/list.json
  blockchains/nativeinjective/validators/assets/injvaloper1mwerm24kce7dcl59t6n0caw7c8zxgkrjj9svwj/logo.png
  blockchains/nativeinjective/validators/list.json
  blockchains/near/validators/assets/stakely_io.poolv1.near/logo.png
  blockchains/near/validators/list.json
  blockchains/stride/validators/assets/stridevaloper16yupepagywvlk7uhpfchtwa0stu5f8cyjayqas/logo.png
  blockchains/stride/validators/list.json
  blockchains/sui/validators/assets/0x9c7376a3f903cbe1f467a4edbefb54bb5a2f10886496c591ca955c22f0ae10c9/logo.png
  blockchains/sui/validators/list.json
Labels: Status: Correction needed, Payment Status: Paid

#27669 Add Basket (SPL)
  blockchains/solana/assets/6gnCPhXtLnUD76HjQuSYPENLSZdG8RvDB1pTLM5aLSJA/info.json
  blockchains/solana/assets/6gnCPhXtLnUD76HjQuSYPENLSZdG8RvDB1pTLM5aLSJA/logo.png
Labels: Payment Status: Paid

#27710 GCCOIN INFO update
  blockchains/smartchain/assets/0x2D8269Dae518e78D95110dbFADf1fb479b8152e7/info.json
  blockchains/smartchain/assets/0x2D8269Dae518e78D95110dbFADf1fb479b8152e7/logo.png
Labels: Status: On Hold, Payment Status: Paid

#27749 Add Farcana (POLYGON)
  blockchains/polygon/assets/0x5F32AbeeBD3c2fac1E7459A27e1AE9f1C16ccccA/info.json
  blockchains/polygon/assets/0x5F32AbeeBD3c2fac1E7459A27e1AE9f1C16ccccA/logo.png
Labels: Payment Status: Paid
