Repository trustwallet/assets, pull requests merged in 2024-07, with the labels that each got.

#28655 abandon celo erc20
  blockchains/celo/assets/0x471EcE3750Da237f93B8E339c536989b8978a438/info.json
Labels: Payment Status: Requested

#28656 rename cGLD to CELO
  blockchains/celo/assets/0x471EcE3750Da237f93B8E339c536989b8978a438/info.json
Labels: Payment Status: Requested

#28659 add wcoin icon
  dapps/tw.discover.w_coin.png
Labels: Payment Status: Paid, Payment Status: Requested

#28419 Abond info
  blockchains/smartchain/assets/0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd/info.json
  blockchains/smartchain/assets/0x34294AfABCbaFfc616ac6614F6d2e17260b78BEd/logo.png
Labels: Payment Status: Paid, Under Review

#28403 Update token
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/info.json
  blockchains/smartchain/assets/0x27Ae27110350B98d564b9A3eeD31bAeBc82d878d/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#28413 Add: Taiko L2 Blockchain and TAIKO Token
  blockchains/ethereum/assets/0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800/info.json
  blockchains/ethereum/assets/0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800/logo.png
Labels: Payment Status: Paid

#28633 Add Opex (POLYGON)
  blockchains/polygon/assets/0xA3fB72CBF2e07dC1b34AEA569Ed40755fd978BD8/info.json
  blockchains/polygon/assets/0xA3fB72CBF2e07dC1b34AEA569Ed40755fd978BD8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#28626 Add XCN @ Base network
  blockchains/base/assets/0x9c632E6Aaa3eA73f91554f8A3cB2ED2F29605e0C/info.json
  blockchains/base/assets/0x9c632E6Aaa3eA73f91554f8A3cB2ED2F29605e0C/logo.png
Labels: Payment Status: Paid

#28718 Add 1000X.sh Solana validator
  blockchains/solana/validators/assets/1KXz4xKV2viJCGpxqnQqdf2J45vQr5USdmtcJLTaHkm/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid, FeePayment: Requested

#27846 Add EYE Network (BEP20)
  blockchains/smartchain/assets/0xE9a97602Ea2985634032a6dFE8a391F7124328F1/info.json
  blockchains/smartchain/assets/0xE9a97602Ea2985634032a6dFE8a391F7124328F1/logo.png
Labels: Payment Status: Paid

#28709 Add AZ BANC SERVICES (BEP20)
  blockchains/smartchain/assets/0x68ef00dAd00925e060b177c7ac59382FD0EB00c2/info.json
  blockchains/smartchain/assets/0x68ef00dAd00925e060b177c7ac59382FD0EB00c2/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28713 Add shelling (BEP20)
  blockchains/smartchain/assets/0xBb689057fE1c4bFc573A54c0679ae1a7A1982F26/info.json
  blockchains/smartchain/assets/0xBb689057fE1c4bFc573A54c0679ae1a7A1982F26/logo.png
Labels: Payment Status: Paid

#28736 Add Verum Coin (BEP20)
  blockchains/smartchain/assets/0xE6e4D9E1ddd783b6BeEccC059ABc17be88EE1A03/info.json
  blockchains/smartchain/assets/0xE6e4D9E1ddd783b6BeEccC059ABc17be88EE1A03/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28742 Add PeiPei fee paid in #28660
  blockchains/ethereum/assets/0x3fFEea07a27Fab7ad1df5297fa75e77a43CB5790/info.json
  blockchains/ethereum/assets/0x3fFEea07a27Fab7ad1df5297fa75e77a43CB5790/logo.png
Labels: Payment Status: Paid

#28763 Update Text and Logo of Solana Validator 1000X
  blockchains/solana/validators/assets/1KXz4xKV2viJCGpxqnQqdf2J45vQr5USdmtcJLTaHkm/logo.png
  blockchains/solana/validators/list.json
Labels: Payment Status: Paid

#28717 info for token decentrawood
  blockchains/polygon/assets/0xE77aBB1E75D2913B2076DD16049992FFeACa5235/info.json
  blockchains/polygon/assets/0xE77aBB1E75D2913B2076DD16049992FFeACa5235/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28751 Add Hoppy (ERC20)
  blockchains/ethereum/assets/0x6E79B51959CF968d87826592f46f819F92466615/info.json
  blockchains/ethereum/assets/0x6E79B51959CF968d87826592f46f819F92466615/logo.png
Labels: Payment Status: Paid

#28808 Add Develocity (BEP-20)
  blockchains/smartchain/assets/0x00f9928315196cdFBeE0205520A8ebe60D9172F0/info.json
  blockchains/smartchain/assets/0x00f9928315196cdFBeE0205520A8ebe60D9172F0/logo.png
Labels: Payment Status: Paid

#28845 Add HashAI (ERC20) change logo
  blockchains/ethereum/assets/0x292fcDD1B104DE5A00250fEBbA9bC6A5092A0076/info.json
  blockchains/ethereum/assets/0x292fcDD1B104DE5A00250fEBbA9bC6A5092A0076/logo.png
Labels: Payment Status: Requested

#28816 Evin Token Logo & Info - Requirment met done - Please Check it
  blockchains/smartchain/assets/0x269B7A30497F92EBf307e7467fD4F1210a6C36b6/info.json
  blockchains/smartchain/assets/0x269B7A30497F92EBf307e7467fD4F1210a6C36b6/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#28819 Updated information for the DEXE token
  blockchains/ethereum/assets/0xde4EE8057785A7e8e800Db58F9784845A5C2Cbd6/info.json
  blockchains/ethereum/assets/0xde4EE8057785A7e8e800Db58F9784845A5C2Cbd6/logo.png
  blockchains/smartchain/assets/0x039cB485212f996A9DBb85A9a75d898F94d38dA6/info.json
  blockchains/smartchain/assets/0x039cB485212f996A9DBb85A9a75d898F94d38dA6/logo.png
  blockchains/smartchain/assets/0x6E88056E8376Ae7709496Ba64d37fa2f8015ce3e/info.json
  blockchains/smartchain/assets/0x6E88056E8376Ae7709496Ba64d37fa2f8015ce3e/logo.png
Labels: Status: Correction needed, Payment Status: Paid
