Repository trustwallet/assets, pull requests merged in 2025-02, with the labels that each got.

#30135 Add Movo
  blockchains/smartchain/assets/0xB71aC215670aA57c8ac382547D0a0f0A962a73E5/info.json
  blockchains/smartchain/assets/0xB71aC215670aA57c8ac382547D0a0f0A962a73E5/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30066 Add NIX (BEP20)
  blockchains/smartchain/assets/0xBe96fcF736AD906b1821Ef74A0e4e346C74e6221/info.json
  blockchains/smartchain/assets/0xBe96fcF736AD906b1821Ef74A0e4e346C74e6221/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30253 add sonic
  blockchains/sonic/info/info.json
  blockchains/sonic/info/logo.png
Labels: Payment Status: Requested

#30286 Add files via upload
  dapps/discover_chaingpt_wd.png
Labels: Payment Status: Requested

#30287 Add files via upload
  dapps/discover_qubetics_wd.png
Labels: Payment Status: Requested

#30223 Add car (BEP20)
  blockchains/smartchain/assets/0xBB1106c7dEb7cC60EfA51391760b14aEd8CB5BEd/info.json
  blockchains/smartchain/assets/0xBB1106c7dEb7cC60EfA51391760b14aEd8CB5BEd/logo.png
Labels: Payment Status: Paid

#30357 Add files via upload
  dapps/discover_web3digest_feb.png
Labels: Payment Status: Requested

#30361 10to13 feb daily assets
  blockchains/base/assets/0x161e113B8E9BBAEfb846F73F31624F6f9607bd44/info.json
  blockchains/base/assets/0x161e113B8E9BBAEfb846F73F31624F6f9607bd44/logo.png
  blockchains/base/assets/0x23A96680Ccde03Bd4Bdd9a3e9a0Cb56A5D27F7c9/info.json
  blockchains/base/assets/0x23A96680Ccde03Bd4Bdd9a3e9a0Cb56A5D27F7c9/logo.png
  blockchains/base/assets/0x333333C465a19C85f85c6CfbED7B16b0B26E3333/info.json
  blockchains/base/assets/0x333333C465a19C85f85c6CfbED7B16b0B26E3333/logo.png
  blockchains/base/assets/0x96419929d7949D6A801A6909c145C8EEf6A40431/info.json
  blockchains/base/assets/0x96419929d7949D6A801A6909c145C8EEf6A40431/logo.png
  blockchains/base/assets/0xD1D7aa941c71Fd95E9d31bBd81937B3E71Bd6231/info.json
  blockchains/base/assets/0xD1D7aa941c71Fd95E9d31bBd81937B3E71Bd6231/logo.png
  blockchains/base/assets/0xdd32659B1e7a6A6B3C6e96Cd8a4c936bCfea0607/info.json
  blockchains/base/assets/0xdd32659B1e7a6A6B3C6e96Cd8a4c936bCfea0607/logo.png
  blockchains/ethereum/assets/0xde6AcEAF7F2dCEB3d425643C5F85351f2B38FcdE/info.json
  blockchains/ethereum/assets/0xde6AcEAF7F2dCEB3d425643C5F85351f2B38FcdE/logo.png
  blockchains/solana/assets/3Yie9s6iuEmk8aiXYC19xaq2iccTuFzyfKBWv6gFpump/info.json
  blockchains/solana/assets/3Yie9s6iuEmk8aiXYC19xaq2iccTuFzyfKBWv6gFpump/logo.png
  blockchains/solana/assets/7vsKatZ8BAKXXb16ZZMJyg9X3iLn8Zpq4yBPg8mWBLMd/info.json
  blockchains/solana/assets/7vsKatZ8BAKXXb16ZZMJyg9X3iLn8Zpq4yBPg8mWBLMd/logo.png
  blockchains/solana/assets/A3t4ap3oHBGRZATex6tFnCDZUdFqybTMhGPbTMzF9kzb/info.json
  blockchains/solana/assets/A3t4ap3oHBGRZATex6tFnCDZUdFqybTMhGPbTMzF9kzb/logo.png
Labels: Payment Status: Requested

#30363 SolanaAssets(13Feb)
  blockchains/solana/assets/2XW7Qx12j6djvB5Dea2d4jJFNu927CtutaVjm887pump/info.json
  blockchains/solana/assets/2XW7Qx12j6djvB5Dea2d4jJFNu927CtutaVjm887pump/logo.png
  blockchains/solana/assets/3cqMmudbNeAHv9JWA2X3TqmgTtZng5CajuZY2Yo74AfD/info.json
  blockchains/solana/assets/3cqMmudbNeAHv9JWA2X3TqmgTtZng5CajuZY2Yo74AfD/logo.png
  blockchains/solana/assets/4AkCN6KLeCmUDjWLg4XyQpuZuWtwBdPcbtBQjsA2pump/info.json
  blockchains/solana/assets/4AkCN6KLeCmUDjWLg4XyQpuZuWtwBdPcbtBQjsA2pump/logo.png
  blockchains/solana/assets/4NzK1HGD51owZUyLYcXyE42ZxqPkgRysyRdhpZaWpump/info.json
  blockchains/solana/assets/4NzK1HGD51owZUyLYcXyE42ZxqPkgRysyRdhpZaWpump/logo.png
  blockchains/solana/assets/5TaSR6RgfC4o7NNAW7ybYXEKCf9x6stZz7GCLnJ8pump/info.json
  blockchains/solana/assets/5TaSR6RgfC4o7NNAW7ybYXEKCf9x6stZz7GCLnJ8pump/logo.png
  blockchains/solana/assets/6LDF727vvVi5YzisQ5XRr5Mu38sr8qttMe6MbvdHpump/info.json
  blockchains/solana/assets/6LDF727vvVi5YzisQ5XRr5Mu38sr8qttMe6MbvdHpump/logo.png
  blockchains/solana/assets/6NcdiK8B5KK2DzKvzvCfqi8EHaEqu48fyEzC8Mm9pump/info.json
  blockchains/solana/assets/6NcdiK8B5KK2DzKvzvCfqi8EHaEqu48fyEzC8Mm9pump/logo.png
  blockchains/solana/assets/8BW7q2DY6YqVNzk5KkwRgPy2NZv5Sujf6zUUhFcFETeh/info.json
  blockchains/solana/assets/8BW7q2DY6YqVNzk5KkwRgPy2NZv5Sujf6zUUhFcFETeh/logo.png
  blockchains/solana/assets/9soX9xpDQS9U3UotRw6y2gH5Ash97yWgxeoeB5Ripump/info.json
  blockchains/solana/assets/9soX9xpDQS9U3UotRw6y2gH5Ash97yWgxeoeB5Ripump/logo.png
  blockchains/solana/assets/ANPSUN2NSA25w47r3U4NxQitHWCSSzgz4grzTL34pump/info.json
  blockchains/solana/assets/ANPSUN2NSA25w47r3U4NxQitHWCSSzgz4grzTL34pump/logo.png
  blockchains/solana/assets/CJTttRCmShQRjientZnYUcM9z1jRPv2437oS4Ewovirt/info.json
  blockchains/solana/assets/CJTttRCmShQRjientZnYUcM9z1jRPv2437oS4Ewovirt/logo.png
  blockchains/solana/assets/CQvadZTR8vikRqqwyhvYV8YpdfCRjUCGyQwCuY4rxBQt/info.json
  blockchains/solana/assets/CQvadZTR8vikRqqwyhvYV8YpdfCRjUCGyQwCuY4rxBQt/logo.png
  blockchains/solana/assets/CcfWx71YLn3pDfLMnnECcAwU5KeC2eBsBUCcoQzMpump/info.json
  blockchains/solana/assets/CcfWx71YLn3pDfLMnnECcAwU5KeC2eBsBUCcoQzMpump/logo.png
  blockchains/solana/assets/EfqR6H3knDCgYq7QLtwjRAC5wPzustQvkzNTAMzUvirt/info.json
  blockchains/solana/assets/EfqR6H3knDCgYq7QLtwjRAC5wPzustQvkzNTAMzUvirt/logo.png
  blockchains/solana/assets/FG9Fgc2NjiaLF7CcrsDZM9vc9ttmR84Jzw8WfuFzE4kH/info.json
  blockchains/solana/assets/FG9Fgc2NjiaLF7CcrsDZM9vc9ttmR84Jzw8WfuFzE4kH/logo.png
  blockchains/solana/assets/Fx968z3Bfp8rn2BNqsTXv9Ym9QUdLk1GnQXpEx2Tpump/info.json
  blockchains/solana/assets/Fx968z3Bfp8rn2BNqsTXv9Ym9QUdLk1GnQXpEx2Tpump/logo.png
  blockchains/solana/assets/Gdck9KXSSiMMhNyjUjo4sVT1GDzeZnZP2yse9jhax3GR/info.json
  blockchains/solana/assets/Gdck9KXSSiMMhNyjUjo4sVT1GDzeZnZP2yse9jhax3GR/logo.png
  blockchains/solana/assets/Gx5dX1pM5aCQn8wtXEmEHSUia3W57Jq7qdu7kKsHvirt/info.json
  blockchains/solana/assets/Gx5dX1pM5aCQn8wtXEmEHSUia3W57Jq7qdu7kKsHvirt/logo.png
  blockchains/solana/assets/H7VfCzzPJvnqfs1b8uA9uUuVjXiYfzAUDw5gmyV9pump/info.json
  blockchains/solana/assets/H7VfCzzPJvnqfs1b8uA9uUuVjXiYfzAUDw5gmyV9pump/logo.png
  blockchains/solana/assets/SoLiDMWBct5TurG1LNcocemBK7QmTn4P33GSrRrcd2n/info.json
  blockchains/solana/assets/SoLiDMWBct5TurG1LNcocemBK7QmTn4P33GSrRrcd2n/logo.png
  blockchains/solana/assets/xMJ9BnMvrpEUrTEihDKSuQUh8J7P89oEQrbuCWWpump/info.json
  blockchains/solana/assets/xMJ9BnMvrpEUrTEihDKSuQUh8J7P89oEQrbuCWWpump/logo.png
Labels: Payment Status: Requested

#29959 Add OilMetaGames (BEP20)
  blockchains/smartchain/assets/0xE94444Ba62208431a27C764E2e28794e81f5B235/info.json
  blockchains/smartchain/assets/0xE94444Ba62208431a27C764E2e28794e81f5B235/logo.png
Labels: Payment Status: Paid

#30377 14th feb base asset
  blockchains/base/assets/0x0028e1E60167b48a938B785AA5292917E7eacA8b/info.json
  blockchains/base/assets/0x0028e1E60167b48a938B785AA5292917E7eacA8b/logo.png
  blockchains/base/assets/0x0808Bf94d57C905F1236212654268EF82E1e594E/info.json
  blockchains/base/assets/0x0808Bf94d57C905F1236212654268EF82E1e594E/logo.png
  blockchains/base/assets/0x0C5142BC58f9A61AB8C3D2085DD2F4e550c5cE0B/info.json
  blockchains/base/assets/0x0C5142BC58f9A61AB8C3D2085DD2F4e550c5cE0B/logo.png
  blockchains/base/assets/0x1B5cE2a593a840E3ad3549a34D7b3dEc697c114D/info.json
  blockchains/base/assets/0x1B5cE2a593a840E3ad3549a34D7b3dEc697c114D/logo.png
  blockchains/base/assets/0x38d513Ec43ddA20f323f26c7bef74c5cF80b6477/info.json
  blockchains/base/assets/0x38d513Ec43ddA20f323f26c7bef74c5cF80b6477/logo.png
  blockchains/base/assets/0x623cD3a3EdF080057892aaF8D773Bbb7A5C9b6e9/info.json
  blockchains/base/assets/0x623cD3a3EdF080057892aaF8D773Bbb7A5C9b6e9/logo.png
  blockchains/base/assets/0x7A8A5012022BCCBf3EA4b03cD2bb5583d915fb1A/info.json
  blockchains/base/assets/0x7A8A5012022BCCBf3EA4b03cD2bb5583d915fb1A/logo.png
  blockchains/base/assets/0x8761155c814c807cD3CcD15B256D69D3C10f198C/info.json
  blockchains/base/assets/0x8761155c814c807cD3CcD15B256D69D3C10f198C/logo.png
  blockchains/base/assets/0x99b2B1A2aDB02B38222ADcD057783D7e5D1FCC7D/info.json
  blockchains/base/assets/0x99b2B1A2aDB02B38222ADcD057783D7e5D1FCC7D/logo.png
  blockchains/base/assets/0x9a33406165f562E16C3abD82fd1185482E01b49a/info.json
  blockchains/base/assets/0x9a33406165f562E16C3abD82fd1185482E01b49a/logo.png
  blockchains/base/assets/0xD9eA93A38D1771C870128f9134D4622d331C04C8/info.json
  blockchains/base/assets/0xD9eA93A38D1771C870128f9134D4622d331C04C8/logo.png
  blockchains/base/assets/0xF0268c5F9aA95Baf5C25D646AAbB900Ac12F0800/info.json
  blockchains/base/assets/0xF0268c5F9aA95Baf5C25D646AAbB900Ac12F0800/logo.png
  blockchains/base/assets/0xF56B3b3972F2f154555a0b62FF5A22b7b2A3C90B/info.json
  blockchains/base/assets/0xF56B3b3972F2f154555a0b62FF5A22b7b2A3C90B/logo.png
  blockchains/base/assets/0xd85EFF20288ca72eA9eEcFFb428F89EE5066CA5C/info.json
  blockchains/base/assets/0xd85EFF20288ca72eA9eEcFFb428F89EE5066CA5C/logo.png
  blockchains/base/assets/0xe095780bA2A64a4Efa7a74830F0b71656f0b0AD4/info.json
  blockchains/base/assets/0xe095780bA2A64a4Efa7a74830F0b71656f0b0AD4/logo.png
Labels: Payment Status: Requested

#30334 Add KRWO (BEP20)
  blockchains/smartchain/assets/0x5868A0Bc3a64CFf82e19A135E17fE18E18E03bC1/info.json
  blockchains/smartchain/assets/0x5868A0Bc3a64CFf82e19A135E17fE18E18E03bC1/logo.png
Labels: Payment Status: Paid

#30396 Priority tokens(17 feb)
  blockchains/smartchain/assets/0x2114eD8Ed375C2056053234F0a457f700E04B650/info.json
  blockchains/smartchain/assets/0x2114eD8Ed375C2056053234F0a457f700E04B650/logo.png
  blockchains/smartchain/assets/0x228456C7a52fC184F17F75F9440F277d3aAd0FB7/info.json
  blockchains/smartchain/assets/0x228456C7a52fC184F17F75F9440F277d3aAd0FB7/logo.png
  blockchains/smartchain/assets/0x5fdfaFd107Fc267bD6d6B1C08fcafb8d31394ba1/info.json
  blockchains/smartchain/assets/0x5fdfaFd107Fc267bD6d6B1C08fcafb8d31394ba1/logo.png
  blockchains/smartchain/assets/0x6cC43ffC4d2956eD15B8cD263Ac8E9884775e7DC/info.json
  blockchains/smartchain/assets/0x6cC43ffC4d2956eD15B8cD263Ac8E9884775e7DC/logo.png
  blockchains/smartchain/assets/0x7DC3a19BCC33a63549FF2520b5c67cB4670C1457/info.json
  blockchains/smartchain/assets/0x7DC3a19BCC33a63549FF2520b5c67cB4670C1457/logo.png
  blockchains/smartchain/assets/0x7ba2710210b525AA5b90b4Dee4cC781dAD8Aec49/info.json
  blockchains/smartchain/assets/0x7ba2710210b525AA5b90b4Dee4cC781dAD8Aec49/logo.png
  blockchains/smartchain/assets/0x8afC14fb1954F909c167bDF06C93ED4e1E51592b/info.json
  blockchains/smartchain/assets/0x8afC14fb1954F909c167bDF06C93ED4e1E51592b/logo.png
  blockchains/smartchain/assets/0xCAb6311f95faF6B5Db4fD306092b6BcD9807e8F0/info.json
  blockchains/smartchain/assets/0xCAb6311f95faF6B5Db4fD306092b6BcD9807e8F0/logo.png
  blockchains/smartchain/assets/0xCE13951DdC789ca61D80142Daff472f898D3d2bC/info.json
  blockchains/smartchain/assets/0xCE13951DdC789ca61D80142Daff472f898D3d2bC/logo.png
  blockchains/smartchain/assets/0xcE30b968d5e76A67f3946E0598F95d551ce03Ac3/info.json
  blockchains/smartchain/assets/0xcE30b968d5e76A67f3946E0598F95d551ce03Ac3/logo.png
  blockchains/smartchain/assets/0xf061F47c436440E3e98EFaB66bfeb2F739d9caaC/info.json
  blockchains/smartchain/assets/0xf061F47c436440E3e98EFaB66bfeb2F739d9caaC/logo.png
Labels: Payment Status: Requested

#30414 Add files via upload
  dapps/discover_bnbmemes.png
Labels: Payment Status: Requested

#30422 19 feb (trending tokens)
  blockchains/arbitrum/assets/0xF18e4466F26B4cA55bbAb890b314a54976E45B17/info.json
  blockchains/arbitrum/assets/0xF18e4466F26B4cA55bbAb890b314a54976E45B17/logo.png
  blockchains/ethereum/assets/0x429F0d8233e517f9acf6F0C8293BF35804063a83/info.json
  blockchains/ethereum/assets/0x429F0d8233e517f9acf6F0C8293BF35804063a83/logo.png
  blockchains/ethereum/assets/0x76A0e27618462bDAC7a29104bdcfFf4E6BFCea2D/info.json
  blockchains/ethereum/assets/0x76A0e27618462bDAC7a29104bdcfFf4E6BFCea2D/logo.png
  blockchains/smartchain/assets/0x10eC175cBBAc1B06b8a3f509e373EeEc7a5F5d63/info.json
  blockchains/smartchain/assets/0x10eC175cBBAc1B06b8a3f509e373EeEc7a5F5d63/logo.png
  blockchains/smartchain/assets/0x1FA0f5ed24a1a2b43741E88F8FEc19633e67082B/info.json
  blockchains/smartchain/assets/0x1FA0f5ed24a1a2b43741E88F8FEc19633e67082B/logo.png
  blockchains/solana/assets/6B6meNabem1xPxs8EgwmYZudykPS6qye3HpCx49XP4zP/info.json
  blockchains/solana/assets/6B6meNabem1xPxs8EgwmYZudykPS6qye3HpCx49XP4zP/logo.png
  blockchains/solana/assets/EnrfQThbgGVNdjWXtKzmBqTiqD7WXK8jBDMxLtMopump/info.json
  blockchains/solana/assets/EnrfQThbgGVNdjWXtKzmBqTiqD7WXK8jBDMxLtMopump/logo.png
  blockchains/solana/assets/MbetZheK6wDs22ftMat7PLiBtoXYBdrMHfpkKRihCYK/info.json
  blockchains/solana/assets/MbetZheK6wDs22ftMat7PLiBtoXYBdrMHfpkKRihCYK/logo.png
Labels: Payment Status: Requested

#30424 Add Puffer (ERC20)
  blockchains/ethereum/assets/0x4d1C297d39C5c1277964D0E3f8Aa901493664530/info.json
  blockchains/ethereum/assets/0x4d1C297d39C5c1277964D0E3f8Aa901493664530/logo.png
Labels: Payment Status: Requested

#30425 Add trending tokens
  blockchains/ethereum/assets/0xf2c88757f8d03634671208935974B60a2a28Bdb3/info.json
  blockchains/ethereum/assets/0xf2c88757f8d03634671208935974B60a2a28Bdb3/logo.png
  blockchains/smartchain/assets/0x1ec5da0f1e43EF6802DE631A1323a37E7b530B2b/info.json
  blockchains/smartchain/assets/0x1ec5da0f1e43EF6802DE631A1323a37E7b530B2b/logo.png
  blockchains/smartchain/assets/0x27BB50c0927891CD21C8Db530490373d295FCBf5/info.json
  blockchains/smartchain/assets/0x27BB50c0927891CD21C8Db530490373d295FCBf5/logo.png
  blockchains/smartchain/assets/0x5DDA861716cD6b1baa17F7F2dB0fbB70D783A5F8/info.json
  blockchains/smartchain/assets/0x5DDA861716cD6b1baa17F7F2dB0fbB70D783A5F8/logo.png
  blockchains/smartchain/assets/0x60b1b7eeD75a787ab7f3e92dbF5E8Af382Bb1a6b/info.json
  blockchains/smartchain/assets/0x60b1b7eeD75a787ab7f3e92dbF5E8Af382Bb1a6b/logo.png
  blockchains/smartchain/assets/0xA2171868C06e578ffF91fDfD186b22A3dF3fF2C7/info.json
  blockchains/smartchain/assets/0xA2171868C06e578ffF91fDfD186b22A3dF3fF2C7/logo.png
  blockchains/smartchain/assets/0xC07D28F8e9D9b5644676196aFE14af09e1c79AfD/info.json
  blockchains/smartchain/assets/0xC07D28F8e9D9b5644676196aFE14af09e1c79AfD/logo.png
  blockchains/smartchain/assets/0xf117DFCB241c0003d5e2FC72F288755C17a46980/info.json
  blockchains/smartchain/assets/0xf117DFCB241c0003d5e2FC72F288755C17a46980/logo.png
  blockchains/solana/assets/D13VkjDiCxtgRJsH4s1VCxKS4bFZq5UEz2iRsSbapump/info.json
  blockchains/solana/assets/D13VkjDiCxtgRJsH4s1VCxKS4bFZq5UEz2iRsSbapump/logo.png
Labels: Payment Status: Requested

#30432 Trending token20 feb
  blockchains/ethereum/assets/0x64c5cbA9A1BfBD2A5faf601D91Beff2dCac2c974/info.json
  blockchains/ethereum/assets/0x64c5cbA9A1BfBD2A5faf601D91Beff2dCac2c974/logo.png
  blockchains/smartchain/assets/0x3CF8F65Eb5866E02f5cC542Dd2FD1325Dae4FD8C/info.json
  blockchains/smartchain/assets/0x3CF8F65Eb5866E02f5cC542Dd2FD1325Dae4FD8C/logo.png
  blockchains/smartchain/assets/0x4De57ba3C5Be7361F3d5a7C2705A44e194670210/info.json
  blockchains/smartchain/assets/0x4De57ba3C5Be7361F3d5a7C2705A44e194670210/logo.png
  blockchains/smartchain/assets/0x51363F073b1E4920fdA7AA9E9d84BA97EdE1560e/info.json
  blockchains/smartchain/assets/0x51363F073b1E4920fdA7AA9E9d84BA97EdE1560e/logo.png
  blockchains/smartchain/assets/0x62475fB57669EfEBd411D9C05109870Bf1BBfdEE/info.json
  blockchains/smartchain/assets/0x62475fB57669EfEBd411D9C05109870Bf1BBfdEE/logo.png
  blockchains/smartchain/assets/0x6c2BE0F7EE3CAa392bA661151eaa6Fb900532B07/info.json
  blockchains/smartchain/assets/0x6c2BE0F7EE3CAa392bA661151eaa6Fb900532B07/logo.png
  blockchains/smartchain/assets/0xA501Cb70CB2beCFfEB5aC491f91E2f7916E5a3fC/info.json
  blockchains/smartchain/assets/0xA501Cb70CB2beCFfEB5aC491f91E2f7916E5a3fC/logo.png
  blockchains/smartchain/assets/0xAaBb6066809a1B25e34Da5D130A84A15b47FDCD0/info.json
  blockchains/smartchain/assets/0xAaBb6066809a1B25e34Da5D130A84A15b47FDCD0/logo.png
  blockchains/smartchain/assets/0xCF2aDB160d78528127Df3ba471Cb3Ede0f06b99e/info.json
  blockchains/smartchain/assets/0xCF2aDB160d78528127Df3ba471Cb3Ede0f06b99e/logo.png
  blockchains/smartchain/assets/0xE87739E3494aE2AFe555CDD46Df45050Cc709522/info.json
  blockchains/smartchain/assets/0xE87739E3494aE2AFe555CDD46Df45050Cc709522/logo.png
  blockchains/smartchain/assets/0xadFF8332D429E420BaC898b934E90D40Fb51121B/info.json
  blockchains/smartchain/assets/0xadFF8332D429E420BaC898b934E90D40Fb51121B/logo.png
  blockchains/smartchain/assets/0xbBC6057d21BD9c8FcEEDfFe821D7d8bE10d3d82a/info.json
  blockchains/smartchain/assets/0xbBC6057d21BD9c8FcEEDfFe821D7d8bE10d3d82a/logo.png
  blockchains/solana/assets/H4phNbsqjV5rqk8u6FUACTLB6rNZRTAPGnBb8KXJpump/info.json
  blockchains/solana/assets/H4phNbsqjV5rqk8u6FUACTLB6rNZRTAPGnBb8KXJpump/logo.png
Labels: Payment Status: Requested

#30455 Add files via upload
  dapps/discover_bnbmemeswap.png
Labels: Payment Status: Requested

#30457 21 feb token adding
  blockchains/base/assets/0x1F1c695f6b4A3F8B05f2492ceF9474Afb6d6Ad69/info.json
  blockchains/base/assets/0x1F1c695f6b4A3F8B05f2492ceF9474Afb6d6Ad69/logo.png
  blockchains/ethereum/assets/0x4E9623B7e5b6438542458f5EE828d65c24d3AF8c/info.json
  blockchains/ethereum/assets/0x4E9623B7e5b6438542458f5EE828d65c24d3AF8c/logo.png
  blockchains/ethereum/assets/0x6e15A54B5EcAc17e58daDedDbe8506a7560252F9/info.json
  blockchains/ethereum/assets/0x6e15A54B5EcAc17e58daDedDbe8506a7560252F9/logo.png
  blockchains/ethereum/assets/0x712bd4Beb54C6B958267d9dB0259abdBb0BFF606/info.json
  blockchains/ethereum/assets/0x712bd4Beb54C6B958267d9dB0259abdBb0BFF606/logo.png
  blockchains/ethereum/assets/0xDAe0faFD65385E7775Cf75b1398735155EF6aCD2/info.json
  blockchains/ethereum/assets/0xDAe0faFD65385E7775Cf75b1398735155EF6aCD2/logo.png
  blockchains/smartchain/assets/0x709A6bB090b8C4C72Cb44533624F3DF320a8bA80/info.json
  blockchains/smartchain/assets/0x709A6bB090b8C4C72Cb44533624F3DF320a8bA80/logo.png
  blockchains/smartchain/assets/0xED19B2B301E8a4e18c5DCa374a27e7d209Ba02c9/info.json
  blockchains/smartchain/assets/0xED19B2B301E8a4e18c5DCa374a27e7d209Ba02c9/logo.png
  blockchains/solana/assets/3UYS3XXYC9yWvNyBWFKqqb5w9YQfX65RQzoAKd8jEUCB/info.json
  blockchains/solana/assets/3UYS3XXYC9yWvNyBWFKqqb5w9YQfX65RQzoAKd8jEUCB/logo.png
  blockchains/solana/assets/7QnZ1w55EbRJKrMFmnDg7BokyJjCBc8bLpBaaJcQykPw/info.json
  blockchains/solana/assets/7QnZ1w55EbRJKrMFmnDg7BokyJjCBc8bLpBaaJcQykPw/logo.png
  blockchains/solana/assets/Bp7Cz7TpFXyz2Hz8cXE8r1uoD8szQEpx5sz56PfoLA6W/info.json
  blockchains/solana/assets/Bp7Cz7TpFXyz2Hz8cXE8r1uoD8szQEpx5sz56PfoLA6W/logo.png
  blockchains/solana/assets/FasH397CeZLNYWkd3wWK9vrmjd1z93n3b59DssRXpump/info.json
  blockchains/solana/assets/FasH397CeZLNYWkd3wWK9vrmjd1z93n3b59DssRXpump/logo.png
  blockchains/solana/assets/GEuuznWpn6iuQAJxLKQDVGXPtrqXHNWTk3gZqqvJpump/info.json
  blockchains/solana/assets/GEuuznWpn6iuQAJxLKQDVGXPtrqXHNWTk3gZqqvJpump/logo.png
  blockchains/solana/assets/HUPysX7Cfye9XM5LPjR9KkPgixQ8DGSk9pg2KLisYHyP/info.json
  blockchains/solana/assets/HUPysX7Cfye9XM5LPjR9KkPgixQ8DGSk9pg2KLisYHyP/logo.png
  blockchains/solana/assets/Jambjx1oJoZNBZiqbiF9TqgatEZPdyfvYa9WVsKNzUh/info.json
  blockchains/solana/assets/Jambjx1oJoZNBZiqbiF9TqgatEZPdyfvYa9WVsKNzUh/logo.png
  blockchains/solana/assets/VaxZxmFXV8tmsd72hUn22ex6GFzZ5uq9DVJ5wA5pump/info.json
  blockchains/solana/assets/VaxZxmFXV8tmsd72hUn22ex6GFzZ5uq9DVJ5wA5pump/logo.png
Labels: Payment Status: Requested

#30485 24th feb
  blockchains/base/assets/0xE198a5f4c784A5A97f28B2B790603c2B3dfa85C1/info.json
  blockchains/base/assets/0xE198a5f4c784A5A97f28B2B790603c2B3dfa85C1/logo.png
  blockchains/ethereum/assets/0x5e29CF3E3fEd4df50aCab95f8268e9ee26Ea36f2/info.json
  blockchains/ethereum/assets/0x5e29CF3E3fEd4df50aCab95f8268e9ee26Ea36f2/logo.png
  blockchains/ethereum/assets/0xdBDE08d475bd50E2D1A6af34c7b10DD430D8396e/info.json
  blockchains/ethereum/assets/0xdBDE08d475bd50E2D1A6af34c7b10DD430D8396e/logo.png
  blockchains/smartchain/assets/0xCAD5a334DC54143d122d1E753bAD5050181270C8/info.json
  blockchains/smartchain/assets/0xCAD5a334DC54143d122d1E753bAD5050181270C8/logo.png
  blockchains/smartchain/assets/0xa4c3497b57C8b6D510F3707A1e9694fD791f45FB/info.json
  blockchains/smartchain/assets/0xa4c3497b57C8b6D510F3707A1e9694fD791f45FB/logo.png
  blockchains/solana/assets/41fZewbrb8x24yE9KeMJExoVXCDggebPMEwRVvX8pump/info.json
  blockchains/solana/assets/41fZewbrb8x24yE9KeMJExoVXCDggebPMEwRVvX8pump/logo.png
  blockchains/solana/assets/6HXabQ7iG4QUXwsiLoWNdZXLZmM7a5CoTGQbCE3ST7ki/info.json
  blockchains/solana/assets/6HXabQ7iG4QUXwsiLoWNdZXLZmM7a5CoTGQbCE3ST7ki/logo.png
  blockchains/solana/assets/CN162nCPpq3DxPCyKLbAvEJeB1aCxsnVTEG4ZU8vpump/info.json
  blockchains/solana/assets/CN162nCPpq3DxPCyKLbAvEJeB1aCxsnVTEG4ZU8vpump/logo.png
  blockchains/solana/assets/EFS13abzbWru8aV5TnYUdy2dvjGGZbGuAHpJSSFdoge/info.json
  blockchains/solana/assets/EFS13abzbWru8aV5TnYUdy2dvjGGZbGuAHpJSSFdoge/logo.png
  blockchains/solana/assets/FrkF4GNdqKZLuzWXTk1imqMJRGK9uxCRE3PaBKZbpump/info.json
  blockchains/solana/assets/FrkF4GNdqKZLuzWXTk1imqMJRGK9uxCRE3PaBKZbpump/logo.png
Labels: Payment Status: Requested

#30479 Adding broccoli token
  blockchains/smartchain/assets/0x12819623921Be0F4d5ebfC12C75E6D08a1683080/info.json
  blockchains/smartchain/assets/0x12819623921Be0F4d5ebfC12C75E6D08a1683080/logo.png
Labels: Payment Status: Paid

#30380 Add Liza Coin (BEP20)
  blockchains/smartchain/assets/0x84A238Aa527181F2354A40e9a1C4C3Eb4a01bB8a/info.json
  blockchains/smartchain/assets/0x84A238Aa527181F2354A40e9a1C4C3Eb4a01bB8a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30490 25th feb
  blockchains/base/assets/0x1C4CcA7C5DB003824208aDDA61Bd749e55F463a3/info.json
  blockchains/base/assets/0x1C4CcA7C5DB003824208aDDA61Bd749e55F463a3/logo.png
  blockchains/base/assets/0x64FCC3A02eeEba05Ef701b7eed066c6ebD5d4E51/info.json
  blockchains/base/assets/0x64FCC3A02eeEba05Ef701b7eed066c6ebD5d4E51/logo.png
  blockchains/base/assets/0x6C7ebB64E258F5712EEeC83CEaf41c3dcbb534B1/info.json
  blockchains/base/assets/0x6C7ebB64E258F5712EEeC83CEaf41c3dcbb534B1/logo.png
  blockchains/base/assets/0x768BE13e1680b5ebE0024C42c896E3dB59ec0149/info.json
  blockchains/base/assets/0x768BE13e1680b5ebE0024C42c896E3dB59ec0149/logo.png
  blockchains/base/assets/0x8bFAc1b375bf2894D6F12fb2Eb48B1C1a7916789/info.json
  blockchains/base/assets/0x8bFAc1b375bf2894D6F12fb2Eb48B1C1a7916789/logo.png
  blockchains/base/assets/0xab964f7b7b6391bd6c4e8512eF00d01f255d9c0D/info.json
  blockchains/base/assets/0xab964f7b7b6391bd6c4e8512eF00d01f255d9c0D/logo.png
  blockchains/base/assets/0xdb08CA267e824fb29eb455B7e06Fe73FB0370895/info.json
  blockchains/base/assets/0xdb08CA267e824fb29eb455B7e06Fe73FB0370895/logo.png
  blockchains/smartchain/assets/0x09f4eBB8567ea0e969f10799CA678F9A172DC2Bb/info.json
  blockchains/smartchain/assets/0x09f4eBB8567ea0e969f10799CA678F9A172DC2Bb/logo.png
  blockchains/smartchain/assets/0x3917d6BdFFe43105A74E6F9c09B5206f0f3F5FC0/info.json
  blockchains/smartchain/assets/0x3917d6BdFFe43105A74E6F9c09B5206f0f3F5FC0/logo.png
  blockchains/solana/assets/3CoTXmxP8pCKoJxd6QSxeYPzi9gzBQB6TmQzH8m1gza2/info.json
  blockchains/solana/assets/3CoTXmxP8pCKoJxd6QSxeYPzi9gzBQB6TmQzH8m1gza2/logo.png
  blockchains/solana/assets/5pPkhLEJDMFDHUuE1wW5os5YJeyNUDVmih1DKgMFpB38/info.json
  blockchains/solana/assets/5pPkhLEJDMFDHUuE1wW5os5YJeyNUDVmih1DKgMFpB38/logo.png
  blockchains/solana/assets/6LrY2g3dUsnZcJXjXw5EUd9LjnSEz8mA9TbKNEstNT7D/info.json
  blockchains/solana/assets/6LrY2g3dUsnZcJXjXw5EUd9LjnSEz8mA9TbKNEstNT7D/logo.png
  blockchains/solana/assets/7kCwAK7QTD3RfytgCV4vX8i5RX3NXZDJHsxG8W9wk7DA/info.json
  blockchains/solana/assets/7kCwAK7QTD3RfytgCV4vX8i5RX3NXZDJHsxG8W9wk7DA/logo.png
  blockchains/solana/assets/8fJCtfbuAaFzdwTnQP84nNhSpZdVy4Uc929eXZRBN8H4/info.json
  blockchains/solana/assets/8fJCtfbuAaFzdwTnQP84nNhSpZdVy4Uc929eXZRBN8H4/logo.png
  blockchains/solana/assets/B7NPUGvxC8BUF5a8BdxurBNxCjV3HwyN6DaRivtqNAjB/info.json
  blockchains/solana/assets/B7NPUGvxC8BUF5a8BdxurBNxCjV3HwyN6DaRivtqNAjB/logo.png
  blockchains/solana/assets/F3XTBj4cD9AvqqbR5E6CZYigyTcmEpgAi3LqaX3pmoon/info.json
  blockchains/solana/assets/F3XTBj4cD9AvqqbR5E6CZYigyTcmEpgAi3LqaX3pmoon/logo.png
  blockchains/solana/assets/FaQvXD4Ww6F5qJ5ruvs58fjR5oSD9AozryebhovWHjNk/info.json
  blockchains/solana/assets/FaQvXD4Ww6F5qJ5ruvs58fjR5oSD9AozryebhovWHjNk/logo.png
  blockchains/solana/assets/J8eZkbpXmTxijvrWYs3Nf59H89ANcS8NFW4KpaMfhdYh/info.json
  blockchains/solana/assets/J8eZkbpXmTxijvrWYs3Nf59H89ANcS8NFW4KpaMfhdYh/logo.png
Labels: Payment Status: Requested

#30493 Add files via upload
  dapps/discover_jettonfeatured.png
Labels: Payment Status: Requested

#30385 Add GoldenRat (BEP20)
  blockchains/smartchain/assets/0x45787821a0BD5e6bba8E709783C773A386e34D65/info.json
  blockchains/smartchain/assets/0x45787821a0BD5e6bba8E709783C773A386e34D65/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30351 Add rzusd (BEP20)
  blockchains/smartchain/assets/0xC4A1cc5cA8955a4650BDC109bddf110E33a1e344/info.json
  blockchains/smartchain/assets/0xC4A1cc5cA8955a4650BDC109bddf110E33a1e344/logo.png
Labels: Payment Status: Paid

#30404 Add jewelry (BEP20)
  blockchains/smartchain/assets/0xf04FaB6Dda66261eaBfD65e92A6b81dDaF6a950a/info.json
  blockchains/smartchain/assets/0xf04FaB6Dda66261eaBfD65e92A6b81dDaF6a950a/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30488 Add A7A5 (TRC20)
  blockchains/tron/assets/TLeVfrdym8RoJreJ23dAGyfJDygRtiWKBZ/info.json
  blockchains/tron/assets/TLeVfrdym8RoJreJ23dAGyfJDygRtiWKBZ/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30508 26 Feb Tokens
  blockchains/base/assets/0x06A63c498eF95AD1fA4FfF841955e512b4B2198a/info.json
  blockchains/base/assets/0x06A63c498eF95AD1fA4FfF841955e512b4B2198a/logo.png
  blockchains/base/assets/0x08c81699F9a357a9F0d04A09b353576ca328d60D/info.json
  blockchains/base/assets/0x08c81699F9a357a9F0d04A09b353576ca328d60D/logo.png
  blockchains/base/assets/0x0fD7a301B51d0A83FCAf6718628174D527B373b6/info.json
  blockchains/base/assets/0x0fD7a301B51d0A83FCAf6718628174D527B373b6/logo.png
  blockchains/base/assets/0x10f434B3d1cC13A4A79B062Dcc25706f64D10D47/info.json
  blockchains/base/assets/0x10f434B3d1cC13A4A79B062Dcc25706f64D10D47/logo.png
  blockchains/base/assets/0x1dd2d631c92b1aCdFCDd51A0F7145A50130050C4/info.json
  blockchains/base/assets/0x1dd2d631c92b1aCdFCDd51A0F7145A50130050C4/logo.png
  blockchains/base/assets/0x2941D526E22406c5d6F273E281899Cfc042a7332/info.json
  blockchains/base/assets/0x2941D526E22406c5d6F273E281899Cfc042a7332/logo.png
  blockchains/base/assets/0x3124678D62D2aa1f615B54525310fbfDa6DcF7AE/info.json
  blockchains/base/assets/0x3124678D62D2aa1f615B54525310fbfDa6DcF7AE/logo.png
  blockchains/base/assets/0x9aAaE745cf2830FB8DDc6248B17436dC3a5E701C/info.json
  blockchains/base/assets/0x9aAaE745cf2830FB8DDc6248B17436dC3a5E701C/logo.png
  blockchains/base/assets/0xcc0adB6C436eB1f65B2f27733Bf926691b94c5f1/info.json
  blockchains/base/assets/0xcc0adB6C436eB1f65B2f27733Bf926691b94c5f1/logo.png
  blockchains/ethereum/assets/0x6ef69Ba2d051761aFD38F218F0a3cF517D64A760/info.json
  blockchains/ethereum/assets/0x6ef69Ba2d051761aFD38F218F0a3cF517D64A760/logo.png
  blockchains/smartchain/assets/0x034e3d48c7d742ff7Eb40365aC7366A35ECB1EF6/info.json
  blockchains/smartchain/assets/0x034e3d48c7d742ff7Eb40365aC7366A35ECB1EF6/logo.png
  blockchains/smartchain/assets/0x8873e32E39BB52ae06F9746B889D4A50df1096db/info.json
  blockchains/smartchain/assets/0x8873e32E39BB52ae06F9746B889D4A50df1096db/logo.png
  blockchains/solana/assets/3XktN2eZiv5g62qSQ3bbTjTefSxrPjde4PyKDtcRpump/info.json
  blockchains/solana/assets/3XktN2eZiv5g62qSQ3bbTjTefSxrPjde4PyKDtcRpump/logo.png
  blockchains/solana/assets/CXPLyc3EX8WySgEXLbjhuA7vy8EKQokVJYQuJm2jpump/info.json
  blockchains/solana/assets/CXPLyc3EX8WySgEXLbjhuA7vy8EKQokVJYQuJm2jpump/logo.png
  blockchains/solana/assets/ELdqGtj2MhejZzudGfz7b798si2Av5Asuw9ryEQSpump/info.json
  blockchains/solana/assets/ELdqGtj2MhejZzudGfz7b798si2Av5Asuw9ryEQSpump/logo.png
  blockchains/solana/assets/GCxg4FotpjcCk9S3VwvKG41dGryFfaS8MPeja1j33mCP/info.json
  blockchains/solana/assets/GCxg4FotpjcCk9S3VwvKG41dGryFfaS8MPeja1j33mCP/logo.png
  blockchains/solana/assets/GTAU72q34CVcN72VvHZxyuDt2ybyLKvEj4ojqyXJpump/info.json
  blockchains/solana/assets/GTAU72q34CVcN72VvHZxyuDt2ybyLKvEj4ojqyXJpump/logo.png
Labels: Payment Status: Requested

#29748 Adding UP on Base
  blockchains/base/assets/0xaC27fa800955849d6D17cC8952Ba9dD6EAA66187/info.json
  blockchains/base/assets/0xaC27fa800955849d6D17cC8952Ba9dD6EAA66187/logo.png
  blockchains/base/tokenlist.json
Labels: Status: Correction needed, Payment Status: Paid

#30531 28th feb daily
  blockchains/base/assets/0x3C8cd0dB9a01EfA063a7760267b822A129bc7DCA/info.json
  blockchains/base/assets/0x3C8cd0dB9a01EfA063a7760267b822A129bc7DCA/logo.png
  blockchains/solana/assets/2sNvt9tRAW29cZgj3cVmwEGLJFfqb127GKnAiEN8iBxY/info.json
  blockchains/solana/assets/2sNvt9tRAW29cZgj3cVmwEGLJFfqb127GKnAiEN8iBxY/logo.png
  blockchains/solana/assets/313t1ZZcLBEmw4uWRjSei1xCDEK4B73KqawJ5xfCpump/info.json
  blockchains/solana/assets/313t1ZZcLBEmw4uWRjSei1xCDEK4B73KqawJ5xfCpump/logo.png
  blockchains/solana/assets/3gV3t7Y9zsd7wNjGXXukn2RT81vfH46hA3oEcHgVpump/info.json
  blockchains/solana/assets/3gV3t7Y9zsd7wNjGXXukn2RT81vfH46hA3oEcHgVpump/logo.png
  blockchains/solana/assets/4YbYyAVsgyVmN1q9wbzecMoigkZqJKQFdKmns3ZUe5yv/info.json
  blockchains/solana/assets/4YbYyAVsgyVmN1q9wbzecMoigkZqJKQFdKmns3ZUe5yv/logo.png
  blockchains/solana/assets/6tq8614cfS1QoRDxgzScvhcVGCEwkFAFzUcmjuybiAwh/info.json
  blockchains/solana/assets/6tq8614cfS1QoRDxgzScvhcVGCEwkFAFzUcmjuybiAwh/logo.png
  blockchains/solana/assets/81f9WRdbdpf4qrwLMSrG3DVMHbNUxfPemhGbkE7bpump/info.json
  blockchains/solana/assets/81f9WRdbdpf4qrwLMSrG3DVMHbNUxfPemhGbkE7bpump/logo.png
  blockchains/solana/assets/89D8aUdgHfyCRXYMxgo7ogHDbNnuVpHYRnqFfNF7gone/info.json
  blockchains/solana/assets/89D8aUdgHfyCRXYMxgo7ogHDbNnuVpHYRnqFfNF7gone/logo.png
  blockchains/solana/assets/B4f5Tj8h8xSoF9zGHxhL1fLQwvgKWcEFhbTMyVhXJ4ch/info.json
  blockchains/solana/assets/B4f5Tj8h8xSoF9zGHxhL1fLQwvgKWcEFhbTMyVhXJ4ch/logo.png
  blockchains/solana/assets/BjCmA9ZYwJ1BwusMGaSxe4pgaa9gfXTtdyX27NYEpump/info.json
  blockchains/solana/assets/BjCmA9ZYwJ1BwusMGaSxe4pgaa9gfXTtdyX27NYEpump/logo.png
  blockchains/solana/assets/GUdXKe5B35QBcqa8VrPQqn8LCQrK2X1aecCQSJs3EVrS/info.json
  blockchains/solana/assets/GUdXKe5B35QBcqa8VrPQqn8LCQrK2X1aecCQSJs3EVrS/logo.png
  blockchains/solana/assets/JCeoBX79HfatfaY6xvuNyCHf86hwgkCCWDpEycVHtime/info.json
  blockchains/solana/assets/JCeoBX79HfatfaY6xvuNyCHf86hwgkCCWDpEycVHtime/logo.png
Labels: Payment Status: Requested
