Repository trustwallet/assets, pull requests merged in 2025-05, with the labels that each got.

#31316 Add SwapKit Logo
  dapps/swapkit.dev.png
Labels: Payment Status: Requested

#31423 Add Sonic Token List
  blockchains/sonic/tokenlist.json
  dapps/swapkit.dev.png
Labels: Payment Status: Requested

#30330 Add B3 token logo
  blockchains/base/assets/0xB3B32F9f8827D4634fE7d973Fa1034Ec9fdDB3B3/info.json
  blockchains/base/assets/0xB3B32F9f8827D4634fE7d973Fa1034Ec9fdDB3B3/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#31492 Adding ELDE
  blockchains/klaytn/assets/0x8755D2e532b1559454689Bf0E8964Bd78b187Ff6/info.json
  blockchains/klaytn/assets/0x8755D2e532b1559454689Bf0E8964Bd78b187Ff6/logo.png
  blockchains/smartchain/assets/0x799a290F9CC4085a0ce5b42b5F2C30193A7a872B/info.json
  blockchains/smartchain/assets/0x799a290F9CC4085a0ce5b42b5F2C30193A7a872B/logo.png
Labels: Payment Status: Paid

#31245 Add REVOX Governance Token (BEP20)
  blockchains/smartchain/assets/0x90869b3a42E399951bd5F5fF278B8CC5ee1Dc0fE/info.json
  blockchains/smartchain/assets/0x90869b3a42E399951bd5F5fF278B8CC5ee1Dc0fE/logo.png
Labels: Payment Status: Paid

#31458 Add BugsCoin (BEP20)
  blockchains/smartchain/assets/0xa4B68D48D7bc6f04420e8077E6F74bdeF809dEa3/info.json
  blockchains/smartchain/assets/0xa4B68D48D7bc6f04420e8077E6F74bdeF809dEa3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#31675 Add Plumbus (SPL)
  blockchains/solana/assets/Ec2XMdQpLcHnBjaEB5CzeshprAnRdMtHMAVPWmcwTxxA/info.json
  blockchains/solana/assets/Ec2XMdQpLcHnBjaEB5CzeshprAnRdMtHMAVPWmcwTxxA/logo.png
Labels: Payment Status: Requested

#30811 Add Neurashi (SPL)
  blockchains/solana/assets/FrQNn7xSTQWdv3SC8stZfT76QeWgvFWVQtCJhdGVjHJK/info.json
  blockchains/solana/assets/FrQNn7xSTQWdv3SC8stZfT76QeWgvFWVQtCJhdGVjHJK/logo.png
Labels: Payment Status: Paid

#31705 Add Aftermath provider logo
  dapps/aftermath.finance.png
Labels: Payment Status: Requested

#30977 Add Kinto (Arbitrum)
  blockchains/arbitrum/assets/0x010700AB046Dd8e92b0e3587842080Df36364ed3/info.json
  blockchains/arbitrum/assets/0x010700AB046Dd8e92b0e3587842080Df36364ed3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
