Repository trustwallet/assets, pull requests merged in 2025-01, with the labels that each got.

#29836 Add TWT logo and info for HODL token
  blockchains/smartchain/assets/0x32B407ee915432Be6D3F168bc1EfF2a6F8b2034C/info.json
  blockchains/smartchain/assets/0x32B407ee915432Be6D3F168bc1EfF2a6F8b2034C/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30000 Add Andy (BEP20)
  blockchains/smartchain/assets/0x01CA78a2B5F1a9152D8A3A625bd7dF5765eeE1D8/info.json
  blockchains/smartchain/assets/0x01CA78a2B5F1a9152D8A3A625bd7dF5765eeE1D8/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#29970 Add AMATERASU OMIKAMI (OMIKAMI) (ERC20)
  blockchains/ethereum/assets/0x9e18d5BAB2FA94a6A95F509Ecb38F8F68322AbD3/info.json
  blockchains/ethereum/assets/0x9e18d5BAB2FA94a6A95F509Ecb38F8F68322AbD3/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#29882 Add EuropaCoin (BEP20)
  blockchains/smartchain/assets/0x8A972Ed397bEd7C0Cbc84cc3EFbC760bb07F80bb/info.json
  blockchains/smartchain/assets/0x8A972Ed397bEd7C0Cbc84cc3EFbC760bb07F80bb/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30048 Add Deep Blue USD (DBUSD) token for Ethereum and Arbitrum chains
  blockchains/arbitrum/assets/0x26B95c59BE6464f8fd7da08e84eB8475B9B7592C/info.json
  blockchains/arbitrum/assets/0x26B95c59BE6464f8fd7da08e84eB8475B9B7592C/logo.png
  blockchains/ethereum/assets/0x32bDD8b97868ACf7014cFE6EB49Bf4f2936C8F02/info.json
  blockchains/ethereum/assets/0x32bDD8b97868ACf7014cFE6EB49Bf4f2936C8F02/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#30057 Add files via upload
  dapps/discover_trust_talks_1.png
Labels: Payment Status: Requested

#30083 Add files via upload
  dapps/discover_trumpswaps.png
Labels: Payment Status: Requested

#30085 Add melania meme
  blockchains/solana/assets/FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P/info.json
  blockchains/solana/assets/FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P/logo.png
Labels: Payment Status: Requested

#30093 Add hot tokens
  blockchains/solana/assets/4HjE7Eebj7iowo1GFfthmvvcp1Zb4QUXKLc3uq3opump/info.json
  blockchains/solana/assets/4HjE7Eebj7iowo1GFfthmvvcp1Zb4QUXKLc3uq3opump/logo.png
  blockchains/solana/assets/6Qn2muot6pbTTWJ6F83zrpBQTFjb69FcmG1xbg64RoUD/info.json
  blockchains/solana/assets/6Qn2muot6pbTTWJ6F83zrpBQTFjb69FcmG1xbg64RoUD/logo.png
  blockchains/solana/assets/BEgBsVSKJSxreiCE1XmWWq8arnwit7xDqQXSWYgay9xP/info.json
  blockchains/solana/assets/BEgBsVSKJSxreiCE1XmWWq8arnwit7xDqQXSWYgay9xP/logo.png
  blockchains/solana/assets/BUhS5coXEt9hcxN3JSpGYUWSKbNo96RsKu52LcMo12rf/info.json
  blockchains/solana/assets/BUhS5coXEt9hcxN3JSpGYUWSKbNo96RsKu52LcMo12rf/logo.png
  blockchains/solana/assets/BeMqCPzbhXKzFScmTwcWwa97XHE11ANoqn1psDfJpump/info.json
  blockchains/solana/assets/BeMqCPzbhXKzFScmTwcWwa97XHE11ANoqn1psDfJpump/logo.png
  blockchains/solana/assets/D5WJ9eH4WLF1SUazsMZLUKTz4xb6mKHNzS1ufeynmoon/info.json
  blockchains/solana/assets/D5WJ9eH4WLF1SUazsMZLUKTz4xb6mKHNzS1ufeynmoon/logo.png
  blockchains/solana/assets/DFkp2Jd5y4rCuPJAz9djtqUMHyVF5FxRkVgjztyGpump/info.json
  blockchains/solana/assets/DFkp2Jd5y4rCuPJAz9djtqUMHyVF5FxRkVgjztyGpump/logo.png
  blockchains/solana/assets/GHichsGq8aPnqJyz6Jp1ASTK4PNLpB5KrD6XrfDjpump/info.json
  blockchains/solana/assets/GHichsGq8aPnqJyz6Jp1ASTK4PNLpB5KrD6XrfDjpump/logo.png
Labels: Payment Status: Requested

#30143 Top500 cmc
  blockchains/ethereum/assets/0x0C356B7fD36a5357E5A017EF11887ba100C9AB76/info.json
  blockchains/ethereum/assets/0x0C356B7fD36a5357E5A017EF11887ba100C9AB76/logo.png
  blockchains/ethereum/assets/0x1151CB3d861920e07a38e03eEAd12C32178567F6/info.json
  blockchains/ethereum/assets/0x1151CB3d861920e07a38e03eEAd12C32178567F6/logo.png
  blockchains/ethereum/assets/0x152649eA73beAb28c5b49B26eb48f7EAD6d4c898/info.json
  blockchains/ethereum/assets/0x152649eA73beAb28c5b49B26eb48f7EAD6d4c898/logo.png
  blockchains/ethereum/assets/0x3073f7aAA4DB83f95e9FFf17424F71D4751a3073/info.json
  blockchains/ethereum/assets/0x3073f7aAA4DB83f95e9FFf17424F71D4751a3073/logo.png
  blockchains/ethereum/assets/0x4c9EDD5852cd905f086C759E8383e09bff1E68B3/info.json
  blockchains/ethereum/assets/0x4c9EDD5852cd905f086C759E8383e09bff1E68B3/logo.png
  blockchains/ethereum/assets/0x5aFE3855358E112B5647B952709E6165e1c1eEEe/info.json
  blockchains/ethereum/assets/0x5aFE3855358E112B5647B952709E6165e1c1eEEe/logo.png
  blockchains/ethereum/assets/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8/info.json
  blockchains/ethereum/assets/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8/logo.png
  blockchains/ethereum/assets/0x8D983cb9388EaC77af0474fA441C4815500Cb7BB/info.json
  blockchains/ethereum/assets/0x8D983cb9388EaC77af0474fA441C4815500Cb7BB/logo.png
  blockchains/ethereum/assets/0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91/info.json
  blockchains/ethereum/assets/0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91/logo.png
  blockchains/ethereum/assets/0xcb1592591996765Ec0eFc1f92599A19767ee5ffA/info.json
  blockchains/ethereum/assets/0xcb1592591996765Ec0eFc1f92599A19767ee5ffA/logo.png
Labels: Payment Status: Requested

#30144 Add top500
  blockchains/ethereum/assets/0x73A15FeD60Bf67631dC6cd7Bc5B6e8da8190aCF5/info.json
  blockchains/ethereum/assets/0x73A15FeD60Bf67631dC6cd7Bc5B6e8da8190aCF5/logo.png
  blockchains/ethereum/assets/0x7FF7Fa94b8b66Ef313f7970d4EEbd2CB3103a2C0/info.json
  blockchains/ethereum/assets/0x7FF7Fa94b8b66Ef313f7970d4EEbd2CB3103a2C0/logo.png
  blockchains/ethereum/assets/0x93A62Ccfcf1EfCB5f60317981F71ed6Fb39F4BA2/info.json
  blockchains/ethereum/assets/0x93A62Ccfcf1EfCB5f60317981F71ed6Fb39F4BA2/logo.png
  blockchains/ethereum/assets/0xe77f6aCD24185e149e329C1C0F479201b9Ec2f4B/info.json
  blockchains/ethereum/assets/0xe77f6aCD24185e149e329C1C0F479201b9Ec2f4B/logo.png
  blockchains/smartchain/assets/0x238D02eE3F80FBf5E381F049616025c186889B68/info.json
  blockchains/smartchain/assets/0x238D02eE3F80FBf5E381F049616025c186889B68/logo.png
  blockchains/smartchain/assets/0x308bfaeAaC8BDab6e9Fc5Ead8EdCb5f95b0599d9/info.json
  blockchains/smartchain/assets/0x308bfaeAaC8BDab6e9Fc5Ead8EdCb5f95b0599d9/logo.png
  blockchains/smartchain/assets/0x87266413e5b64DB72f11bB6795Ee976545DBAf43/info.json
  blockchains/smartchain/assets/0x87266413e5b64DB72f11bB6795Ee976545DBAf43/logo.png
  blockchains/smartchain/assets/0x90bbdDbF3223363898065b9C736e2B86C655762b/info.json
  blockchains/smartchain/assets/0x90bbdDbF3223363898065b9C736e2B86C655762b/logo.png
  blockchains/smartchain/assets/0xabE8E5CabE24Cb36df9540088fD7cE1175b9bc52/info.json
  blockchains/smartchain/assets/0xabE8E5CabE24Cb36df9540088fD7cE1175b9bc52/logo.png
  blockchains/smartchain/assets/0xc2c28b58db223DA89b567A0A98197Fc17C115148/info.json
  blockchains/smartchain/assets/0xc2c28b58db223DA89b567A0A98197Fc17C115148/logo.png
Labels: Payment Status: Requested

#30154 Add top500
  blockchains/smartchain/assets/0x3E7f1039896454B9cb27c53CC7383e1AB9D9512a/info.json
  blockchains/smartchain/assets/0x3E7f1039896454B9cb27c53CC7383e1AB9D9512a/logo.png
  blockchains/smartchain/assets/0x3e81Aa8d6813Ec9D7E6ddB4e523fb1601a0e86F3/info.json
  blockchains/smartchain/assets/0x3e81Aa8d6813Ec9D7E6ddB4e523fb1601a0e86F3/logo.png
  blockchains/smartchain/assets/0xdF677713a2C661ECD0b2BD4d7485170Aa8c1ECeB/info.json
  blockchains/smartchain/assets/0xdF677713a2C661ECD0b2BD4d7485170Aa8c1ECeB/logo.png
  blockchains/smartchain/assets/0xe6DF05CE8C8301223373CF5B969AFCb1498c5528/info.json
  blockchains/smartchain/assets/0xe6DF05CE8C8301223373CF5B969AFCb1498c5528/logo.png
Labels: Payment Status: Requested

#30076 Existing token update: XIN (ERC20)
  blockchains/ethereum/assets/0xA974c709cFb4566686553a20790685A47acEAA33/info.json
  blockchains/ethereum/assets/0xA974c709cFb4566686553a20790685A47acEAA33/logo.png
Labels: Status: Correction needed, Payment Status: Paid

#30159 Add RLUSD
  blockchains/ripple/assets/524C555344000000000000000000000000000000.rMxCKbEDwqr76QuheSUMdEGf4B9xJ8m5De/info.json
  blockchains/ripple/assets/524C555344000000000000000000000000000000.rMxCKbEDwqr76QuheSUMdEGf4B9xJ8m5De/logo.png
Labels: Payment Status: Requested

#30208 Add top500
  blockchains/ethereum/assets/0x15700B564Ca08D9439C58cA5053166E8317aa138/info.json
  blockchains/ethereum/assets/0x15700B564Ca08D9439C58cA5053166E8317aa138/logo.png
  blockchains/ethereum/assets/0x64d0f55Cd8C7133a9D7102b13987235F486F2224/info.json
  blockchains/ethereum/assets/0x64d0f55Cd8C7133a9D7102b13987235F486F2224/logo.png
  blockchains/ethereum/assets/0x96F6eF951840721AdBF46Ac996b59E0235CB985C/info.json
  blockchains/ethereum/assets/0x96F6eF951840721AdBF46Ac996b59E0235CB985C/logo.png
  blockchains/ethereum/assets/0x9Ce84F6A69986a83d92C324df10bC8E64771030f/info.json
  blockchains/ethereum/assets/0x9Ce84F6A69986a83d92C324df10bC8E64771030f/logo.png
  blockchains/ethereum/assets/0xC4441c2BE5d8fA8126822B9929CA0b81Ea0DE38E/info.json
  blockchains/ethereum/assets/0xC4441c2BE5d8fA8126822B9929CA0b81Ea0DE38E/logo.png
  blockchains/ethereum/assets/0xC71B5F631354BE6853eFe9C3Ab6b9590F8302e81/info.json
  blockchains/ethereum/assets/0xC71B5F631354BE6853eFe9C3Ab6b9590F8302e81/logo.png
  blockchains/ethereum/assets/0xEeB4d8400AEefafC1B2953e0094134A887C76Bd8/info.json
  blockchains/ethereum/assets/0xEeB4d8400AEefafC1B2953e0094134A887C76Bd8/logo.png
  blockchains/ethereum/assets/0xF944e35f95E819E752f3cCB5Faf40957d311e8c5/info.json
  blockchains/ethereum/assets/0xF944e35f95E819E752f3cCB5Faf40957d311e8c5/logo.png
  blockchains/ethereum/assets/0xe3c408BD53c31C085a1746AF401A4042954ff740/info.json
  blockchains/ethereum/assets/0xe3c408BD53c31C085a1746AF401A4042954ff740/logo.png
  blockchains/ethereum/assets/0xf8173a39c56a554837C4C7f104153A005D284D11/info.json
  blockchains/ethereum/assets/0xf8173a39c56a554837C4C7f104153A005D284D11/logo.png
Labels: Payment Status: Requested

#30214 Top500 recent
  blockchains/ethereum/assets/0x046BAd07658f3B6cAd9A396CFcbC1243AF452ec1/info.json
  blockchains/ethereum/assets/0x046BAd07658f3B6cAd9A396CFcbC1243AF452ec1/logo.png
  blockchains/ethereum/assets/0x0649Cef6D11ed6F88535462E147304d3FE5ae14D/info.json
  blockchains/ethereum/assets/0x0649Cef6D11ed6F88535462E147304d3FE5ae14D/logo.png
  blockchains/ethereum/assets/0x1121AcC14c63f3C872BFcA497d10926A6098AAc5/info.json
  blockchains/ethereum/assets/0x1121AcC14c63f3C872BFcA497d10926A6098AAc5/logo.png
  blockchains/ethereum/assets/0x2565ae0385659badCada1031DB704442E1b69982/info.json
  blockchains/ethereum/assets/0x2565ae0385659badCada1031DB704442E1b69982/logo.png
  blockchains/ethereum/assets/0x2A79324c19Ef2B89Ea98b23BC669B7E7c9f8A517/info.json
  blockchains/ethereum/assets/0x2A79324c19Ef2B89Ea98b23BC669B7E7c9f8A517/logo.png
  blockchains/ethereum/assets/0x44108f0223A3C3028F5Fe7AEC7f9bb2E66beF82F/info.json
  blockchains/ethereum/assets/0x44108f0223A3C3028F5Fe7AEC7f9bb2E66beF82F/logo.png
  blockchains/ethereum/assets/0x44971ABF0251958492FeE97dA3e5C5adA88B9185/info.json
  blockchains/ethereum/assets/0x44971ABF0251958492FeE97dA3e5C5adA88B9185/logo.png
  blockchains/ethereum/assets/0x487d62468282Bd04ddf976631C23128A425555EE/info.json
  blockchains/ethereum/assets/0x487d62468282Bd04ddf976631C23128A425555EE/logo.png
  blockchains/ethereum/assets/0x590F820444fA3638e022776752c5eEF34E2F89A6/info.json
  blockchains/ethereum/assets/0x590F820444fA3638e022776752c5eEF34E2F89A6/logo.png
  blockchains/ethereum/assets/0x5DE8ab7E27f6E7A1fFf3E5B337584Aa43961BEeF/info.json
  blockchains/ethereum/assets/0x5DE8ab7E27f6E7A1fFf3E5B337584Aa43961BEeF/logo.png
  blockchains/ethereum/assets/0x5a3e6A77ba2f983eC0d371ea3B475F8Bc0811AD5/info.json
  blockchains/ethereum/assets/0x5a3e6A77ba2f983eC0d371ea3B475F8Bc0811AD5/logo.png
  blockchains/ethereum/assets/0x6033F7f88332B8db6ad452B7C6D5bB643990aE3f/info.json
  blockchains/ethereum/assets/0x6033F7f88332B8db6ad452B7C6D5bB643990aE3f/logo.png
  blockchains/ethereum/assets/0x643C4E15d7d62Ad0aBeC4a9BD4b001aA3Ef52d66/info.json
  blockchains/ethereum/assets/0x643C4E15d7d62Ad0aBeC4a9BD4b001aA3Ef52d66/logo.png
  blockchains/ethereum/assets/0x7296eaA225804451a91616b29D040cAB05435f0d/info.json
  blockchains/ethereum/assets/0x7296eaA225804451a91616b29D040cAB05435f0d/logo.png
  blockchains/ethereum/assets/0x72e4f9F808C49A2a61dE9C5896298920Dc4EEEa9/info.json
  blockchains/ethereum/assets/0x72e4f9F808C49A2a61dE9C5896298920Dc4EEEa9/logo.png
  blockchains/ethereum/assets/0x786A6743efe9500011C92c7D8540608a62382b6f/info.json
  blockchains/ethereum/assets/0x786A6743efe9500011C92c7D8540608a62382b6f/logo.png
  blockchains/ethereum/assets/0x7A58c0Be72BE218B41C608b7Fe7C5bB630736C71/info.json
  blockchains/ethereum/assets/0x7A58c0Be72BE218B41C608b7Fe7C5bB630736C71/logo.png
  blockchains/ethereum/assets/0x7ABc8A5768E6bE61A6c693a6e4EAcb5B60602C4D/info.json
  blockchains/ethereum/assets/0x7ABc8A5768E6bE61A6c693a6e4EAcb5B60602C4D/logo.png
  blockchains/ethereum/assets/0x825459139C897D769339f295E962396C4F9E4A4D/info.json
  blockchains/ethereum/assets/0x825459139C897D769339f295E962396C4F9E4A4D/logo.png
  blockchains/ethereum/assets/0xDBB5Cf12408a3Ac17d668037Ce289f9eA75439D7/info.json
  blockchains/ethereum/assets/0xDBB5Cf12408a3Ac17d668037Ce289f9eA75439D7/logo.png
  blockchains/ethereum/assets/0xEe7527841A932d2912224E20a405e1a1FF747084/info.json
  blockchains/ethereum/assets/0xEe7527841A932d2912224E20a405e1a1FF747084/logo.png
  blockchains/ethereum/assets/0xFeAc2Eae96899709a43E252B6B92971D32F9C0F9/info.json
  blockchains/ethereum/assets/0xFeAc2Eae96899709a43E252B6B92971D32F9C0F9/logo.png
  blockchains/ethereum/assets/0xa21Af1050F7B26e0cfF45ee51548254C41ED6b5c/info.json
  blockchains/ethereum/assets/0xa21Af1050F7B26e0cfF45ee51548254C41ED6b5c/logo.png
  blockchains/ethereum/assets/0xbdC7c08592Ee4aa51D06C27Ee23D5087D65aDbcD/info.json
  blockchains/ethereum/assets/0xbdC7c08592Ee4aa51D06C27Ee23D5087D65aDbcD/logo.png
  blockchains/ethereum/assets/0xd459ECeddafcc1d876a3be7290A2E16e801073a3/info.json
  blockchains/ethereum/assets/0xd459ECeddafcc1d876a3be7290A2E16e801073a3/logo.png
  blockchains/ethereum/assets/0xfd418e42783382E86Ae91e445406600Ba144D162/info.json
  blockchains/ethereum/assets/0xfd418e42783382E86Ae91e445406600Ba144D162/logo.png
Labels: Payment Status: Requested

#30180 Adding Pett AI (AIP) to BASE
  blockchains/base/assets/0x02D4f76656C2B4f58430e91f8ac74896c9281Cb9/info.json
  blockchains/base/assets/0x02D4f76656C2B4f58430e91f8ac74896c9281Cb9/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid
