Repository trustwallet/assets, pull requests merged in 2025-04, with the labels that each got.

#31033 Spam - Test (TST) on BSC
  blockchains/smartchain/assets/0x034e3d48c7d742ff7Eb40365aC7366A35ECB1EF6/info.json
  blockchains/smartchain/assets/0x034e3d48c7d742ff7Eb40365aC7366A35ECB1EF6/logo.png
Labels: Payment Status: Requested

#31094 add WCT token on Ethereum Mainnet
  blockchains/ethereum/assets/0xeF4461891DfB3AC8572cCf7C794664A8DD927945/info.json
  blockchains/ethereum/assets/0xeF4461891DfB3AC8572cCf7C794664A8DD927945/logo.png
Labels: FeePayment: Paid

#30994 Add A7A5 (ERC20)
  blockchains/ethereum/assets/0x6fA0BE17e4beA2fCfA22ef89BF8ac9aab0AB0fc9/info.json
  blockchains/ethereum/assets/0x6fA0BE17e4beA2fCfA22ef89BF8ac9aab0AB0fc9/logo.png
Labels: Payment Status: Paid

#30995 Add Wrapped A7A5 (ERC20)
  blockchains/ethereum/assets/0x0D57436F2d39c0664C6f0f2E349229483f87EA38/info.json
  blockchains/ethereum/assets/0x0D57436F2d39c0664C6f0f2E349229483f87EA38/logo.png
Labels: Payment Status: Paid
