Repository trustwallet/assets, pull requests merged in 2025-03, with the labels that each got.

#30564 Spam - GameStop Coin (GME) on BSC
  blockchains/smartchain/assets/0xf0C99B0288508D004F4aBeCa34d830CE7682977C/info.json
  blockchains/smartchain/assets/0xf0C99B0288508D004F4aBeCa34d830CE7682977C/logo.png
Labels: Payment Status: Requested

#30534 Add NeutralAI (BEP20)
  blockchains/smartchain/assets/0xE36fb7548d16D1B1DDB484A322f06e4ECd3E1f68/info.json
  blockchains/smartchain/assets/0xE36fb7548d16D1B1DDB484A322f06e4ECd3E1f68/logo.png
Labels: Payment Status: Paid

#30550 Add trip (BEP20)
  blockchains/smartchain/assets/0xC9Bfb93d75645c4681BB63794ABf1acAD44725e7/info.json
  blockchains/smartchain/assets/0xC9Bfb93d75645c4681BB63794ABf1acAD44725e7/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30569 Spam - Dog on Base (DOG) on Base network
  blockchains/base/assets/0x2D99436Dea34a1c3B15D45db4394C8C01251EFd6/info.json
  blockchains/base/assets/0x2D99436Dea34a1c3B15D45db4394C8C01251EFd6/logo.png
Labels: Payment Status: Requested

#30565 Add realestate (BEP20)
  blockchains/smartchain/assets/0x32477Cf0e324F9A9cb49E8803fa4dE9f80F8d0D4/info.json
  blockchains/smartchain/assets/0x32477Cf0e324F9A9cb49E8803fa4dE9f80F8d0D4/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid

#30665 Add Mubarakah
  blockchains/smartchain/assets/0x3199A64Bc8aaBDFd9A3937a346CC59c3d81D8a9a/info.json
  blockchains/smartchain/assets/0x3199A64Bc8aaBDFd9A3937a346CC59c3d81D8a9a/logo.png
Labels: Payment Status: Requested

#30666 Add rqstd1 tokens
  blockchains/smartchain/assets/0x1415E784282e11F3972D98b28A4A07f89b82170d/info.json
  blockchains/smartchain/assets/0x1415E784282e11F3972D98b28A4A07f89b82170d/logo.png
  blockchains/smartchain/assets/0x1ed4E5C54B7EC819B1e3f53b15F5808780E89832/info.json
  blockchains/smartchain/assets/0x1ed4E5C54B7EC819B1e3f53b15F5808780E89832/logo.png
  blockchains/smartchain/assets/0x24127d5F034bb3811Cad4123A4ffc20a1f084F95/info.json
  blockchains/smartchain/assets/0x24127d5F034bb3811Cad4123A4ffc20a1f084F95/logo.png
  blockchains/smartchain/assets/0x29a206A67fD4f410034885F5f03A8bB4aa4961aa/info.json
  blockchains/smartchain/assets/0x29a206A67fD4f410034885F5f03A8bB4aa4961aa/logo.png
  blockchains/smartchain/assets/0x9D25ce197f8EbA9aCbc53D0c09cC41bB9A446e52/info.json
  blockchains/smartchain/assets/0x9D25ce197f8EbA9aCbc53D0c09cC41bB9A446e52/logo.png
  blockchains/smartchain/assets/0xA81AfE5D5390e5B645d46097B5D2975f04A47EbB/info.json
  blockchains/smartchain/assets/0xA81AfE5D5390e5B645d46097B5D2975f04A47EbB/logo.png
  blockchains/smartchain/assets/0xC468aCf451922712Cf45aF9801dF89578B0418b4/info.json
  blockchains/smartchain/assets/0xC468aCf451922712Cf45aF9801dF89578B0418b4/logo.png
  blockchains/smartchain/assets/0xcE33deFeFAC76BF36367D0640B5079bb3065e9D7/info.json
  blockchains/smartchain/assets/0xcE33deFeFAC76BF36367D0640B5079bb3065e9D7/logo.png
  blockchains/smartchain/assets/0xcc13194c6be156BAf0FBF3dc93a0eE8cA95fb1d9/info.json
  blockchains/smartchain/assets/0xcc13194c6be156BAf0FBF3dc93a0eE8cA95fb1d9/logo.png
Labels: Payment Status: Requested

#30653 Add Blend (BEP20)
  blockchains/smartchain/assets/0xda52b818c1348bFee27989E2a0DF39224A3E52fA/info.json
  blockchains/smartchain/assets/0xda52b818c1348bFee27989E2a0DF39224A3E52fA/logo.png
Labels: Payment Status: Paid, Payment Status: Requested

#30670 Add BNB Card
  blockchains/smartchain/assets/0xDc06717F367e57A16e06CcE0c4761604460da8Fc/info.json
  blockchains/smartchain/assets/0xDc06717F367e57A16e06CcE0c4761604460da8Fc/logo.png
Labels: Payment Status: Requested

#30671 Add rqstd3 tokens
  blockchains/smartchain/assets/0x338cfc61E23d9D086779f37542e7Acb8517E9faE/info.json
  blockchains/smartchain/assets/0x338cfc61E23d9D086779f37542e7Acb8517E9faE/logo.png
  blockchains/smartchain/assets/0x4AD663403df2F0E7987bC9C74561687472e1611C/info.json
  blockchains/smartchain/assets/0x4AD663403df2F0E7987bC9C74561687472e1611C/logo.png
  blockchains/smartchain/assets/0x50cd57Dc9768509fC256FF4f2A0B4461cBC1B779/info.json
  blockchains/smartchain/assets/0x50cd57Dc9768509fC256FF4f2A0B4461cBC1B779/logo.png
  blockchains/smartchain/assets/0xC9882dEF23bc42D53895b8361D0b1EDC7570Bc6A/info.json
  blockchains/smartchain/assets/0xC9882dEF23bc42D53895b8361D0b1EDC7570Bc6A/logo.png
  blockchains/smartchain/assets/0xFdb624a9a617820260e5B3CB024C85da0441e6A8/info.json
  blockchains/smartchain/assets/0xFdb624a9a617820260e5B3CB024C85da0441e6A8/logo.png
Labels: Payment Status: Requested

#30676 Internal add trending tokens
  blockchains/smartchain/assets/0x339ea0a961E1F5690B9754880f284830ce87CEE1/info.json
  blockchains/smartchain/assets/0x339ea0a961E1F5690B9754880f284830ce87CEE1/logo.png
  blockchains/smartchain/assets/0x3a828E1ea6511E367d436C601E14CDb2b446896D/info.json
  blockchains/smartchain/assets/0x3a828E1ea6511E367d436C601E14CDb2b446896D/logo.png
  blockchains/smartchain/assets/0x3f16ed45679f28111C92aae5912c85B14AbF7637/info.json
  blockchains/smartchain/assets/0x3f16ed45679f28111C92aae5912c85B14AbF7637/logo.png
  blockchains/smartchain/assets/0x4988967B2cC002eDCCeA8d40870b7958E5aBa704/info.json
  blockchains/smartchain/assets/0x4988967B2cC002eDCCeA8d40870b7958E5aBa704/logo.png
  blockchains/smartchain/assets/0x8B0B1D4016f912561D9420ae6035AA543fE9a69d/info.json
  blockchains/smartchain/assets/0x8B0B1D4016f912561D9420ae6035AA543fE9a69d/logo.png
  blockchains/smartchain/assets/0x9B6B44FA816C5Da30DEb7d7d640D7644C2060b0e/info.json
  blockchains/smartchain/assets/0x9B6B44FA816C5Da30DEb7d7d640D7644C2060b0e/logo.png
  blockchains/smartchain/assets/0xBb44Fbeb1bCA7E032D34005791d1b99DfEE187A9/info.json
  blockchains/smartchain/assets/0xBb44Fbeb1bCA7E032D34005791d1b99DfEE187A9/logo.png
  blockchains/smartchain/assets/0xb568922CE28142A70CE3D108BD3Da20B285CAb81/info.json
  blockchains/smartchain/assets/0xb568922CE28142A70CE3D108BD3Da20B285CAb81/logo.png
  blockchains/smartchain/assets/0xe7BA3E4BE1fb144D9e097736a5CF93fC45c6d270/info.json
  blockchains/smartchain/assets/0xe7BA3E4BE1fb144D9e097736a5CF93fC45c6d270/logo.png
Labels: Payment Status: Requested

#30680 Add szn - TRC20
  blockchains/tron/assets/TDxL4V5LE6TYSFXSCWJkkSsCYbgmrDnTer/info.json
  blockchains/tron/assets/TDxL4V5LE6TYSFXSCWJkkSsCYbgmrDnTer/logo.png
Labels: Payment Status: Requested

#30613 Add Pepemusk (BEP20)
  blockchains/smartchain/assets/0x0dcD05357B83BF100e668F152bf14Bf96b679Cd1/info.json
  blockchains/smartchain/assets/0x0dcD05357B83BF100e668F152bf14Bf96b679Cd1/logo.png
Labels: Status: More Info / Change Requested, Payment Status: Paid, Payment Status: Requested
